### ISSUE TITLE
React compatibility

### ISSUE THREAD

**Issue by gyzerok** [babel/babel#1001]
Hello, guys!

First of all thank you for such an incredible project!

I cant found in the docs version of react babel compatible with. Am I missing something? Whats the current compatible version? How soon babel would support react 0.13?

**Comment by neVERberleRfellerER** [comment]
Babel transpiled JSX output is compatible with React 0.12. Since JSX for React 0.13 is transpiled to same code as it was for React 0.12, Babel is compatible with React 0.13 too.
You can easily confirm this by taking sample code from http://facebook.github.io/react/ , transpiling it with Babel and comparing with reference compiled code, or by reading breaking changes on React Blog --- as long, as `React.createElement` is not changed in breaking way, Babel is compatible.

**Comment by sebmck** [comment]
There's nothing about React 0.13 that changes React semantics so yes, it's perfectly compatible. And if you're using pre-0.12 there's the [reactCompat](http://babeljs.io/docs/usage/transformers/other/react-compat/) transformer.
