### ISSUE TITLE
@babel/plugin-transform-runtime with corejs 3 polyfill issue

### ISSUE THREAD

**Issue by mohsinulhaq** [babel/babel#10133]
When I use `@babel/preset-env` with `['@babel/plugin-transform-runtime', {corejs: 3}]`, it seems to replace even the most basic things like `[].map` with its own pure implementation from `core-js`, even though the target supports `Array.prototype.map`, thus increasing bundle size quite considerably. I wanted to know if this is expected, or am I configuring it wrong.
Because using `['@babel/preset-env', {corejs: 3, useBuiltIns: 'usage'}]` polyfills only the features that actually require polyfilling, thereby keeping the bundle size low.

**Comment by nicolo-ribaudo** [comment]
Yes, currently it's the expected behavior.
`@babel/plugin-transform-runtime` is separate from the `env` preset, and it doesn't have access to its `targets`.

You might be interested in https://github.com/babel/babel/issues/10008 which changes how we handle polyfills, and makes it possible to use `targets` when loading "pure" polyfills (which are currently handled by `@babel/transform-runtime`).

**Comment by zloirock** [comment]
Also, see [this](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babelruntime-for-target-environment).

**Comment by mohsinulhaq** [comment]
Thank you guys! It's all clear now! 😃
