### ISSUE TITLE
@babel/standalone transform failed when using preset-typescript

### ISSUE THREAD

**Issue by akira-cn** [babel/babel#10154]
## Bug Report

**Current Behavior**
@babel/standalone transform failed when using preset-typescript

**Input Code**
- REPL or Repo link if applicable:

```js
const _code = Babel.transform(code, { presets: ['typescript'] }).code;
```

**Environment**
- Babel version(s): @babel/standalone@7.4.5
- Node/npm version: node v8.9.3 / npm v6.9.0
- OS: OSX 10.13.2
- Monorepo: [no]
- How you are using Babel: standalone

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

![](https://p2.ssl.qhimg.com/t01eb4af14ae67dddc6.jpg)

**Comment by JLHwung** [comment]
Pass a `filename` option and it should work
```js
Babel.transform(code, { filename: 'example.ts', presets: ['typescript'] });
```

`@babel/preset-typescript` uses `filename` to test if it is a TypeScript file and then it will apply `plugin-transform-typescript` by cases.
```js
{
  test: /\.ts$/,
  plugins: [[transformTypeScript, { jsxPragma }]],
}
```
Per [`filename` options document](https://babeljs.io/docs/en/options#filename), although `filename` is optional, options like `test` rely on `filename` to match test rules. In your case, since the `filename` is not passed but the config builder has to test `/\.ts$/`, it bails out because it could not determine if it is a `.ts` file.

If the `filename` option seems artificial here as I guess you are transforming a code snippet instead of a file, you can also pass `allExtensions: true` to the [typescript preset options](https://babeljs.io/docs/en/babel-preset-typescript#allextensions). It will assume your code is `.tsx` and apply typescript transforms _and_ JSX transforms.

```js
Babel.transform(code, { presets: [['typescript', { allExtensions: true }]] })
```


@nicolo-ribaudo Although the behavior is expected, I think if we can have better documents [here](https://babeljs.io/docs/en/babel-standalone#usage). For those presets, i.e. preset-typescript, using pattern match options, we could post a reminder to declare artificial `filename` option in transform API.

**Comment by nicolo-ribaudo** [comment]
We definetly need a better error message. If the `test` option is used in a preset instead of a user-defined config, it should throw something like `The PRESET_NAME preset needs the filename to be passed to Babel, but it was not provided`.

**Comment by JLHwung** [comment]
> The PRESET_NAME preset needs the filename to be passed to Babel, but it was not provided.

Make sense, we could keep the issue open and I would spare some time to improve the error message.
