### ISSUE TITLE
Pipeline F# BinaryExpression vs PipelineExpression

### ISSUE THREAD

**Issue by goodmind** [babel/babel#10173]
## Bug Report

Why babel defines it as `BinaryExpression` when spec defines new node `PipelineExpression`?

https://tc39.es/proposal-pipeline-operator/#prod-PipelineExpression

**Comment by nicolo-ribaudo** [comment]
Because Babel uses `BinaryExpression` for every binary operator: `AdditiveExpression`, `MultiplicativeExpression`...

**Comment by goodmind** [comment]
@nicolo-ribaudo what about `LogicalExpression`?

**Comment by nicolo-ribaudo** [comment]
That's a good point.

Currently `BinaryExpression` is used for `+`, `-`, `/`, `%`, `*`, `**`, `&`, `|`, `>>`, `>>>`, `<<`, `^`, `|>`, `==`, `===`, `!=`, `!==`, `in`, `instanceof`, `>`, `<`, `>=` and `<=`.
`LogicalExpression` is used for `&&`, `||` and `??`.

I don't know the historical reason behind this inconsistency, but I belive that it is because their evaluation is different:
- `BinaryExpression`s are
   - Evaluate `left`
   - Evaluate `right`
   - Apply the operator
- `LogicalExpression`s are
   - Evaluate `left`
   - Apply the operator
   - Maybe evaluate `right`

`|>` correctly falls in the first category.

**Comment by goodmind** [comment]
Ah, probably makes sense
