### ISSUE TITLE
objectSpread2 failure

### ISSUE THREAD

**Issue by XhmikosR** [babel/babel#10192]
## Bug Report

**Current Behavior**

While trying to update babel and its plugins to the latest v7.5.4 version, we still get some failures in our test suite https://travis-ci.org/twbs/bootstrap/jobs/556685620#L788

The related code should be https://github.com/twbs/bootstrap/blob/master/js/src/dom/manipulator.js#L47

Going back to v7.4.x and `objectSpread` works as expected.

**Input Code**

- https://github.com/twbs/bootstrap

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  presets: [
    [
      '@babel/env',
      {
        loose: true,
        modules: false,
        exclude: ['transform-typeof-symbol']
      }
    ]
  ],
  plugins: [
    '@babel/plugin-proposal-object-rest-spread'
  ],
  env: {
    test: {
      plugins: [ 'istanbul' ]
    }
  }
};
```

**Environment**

- Babel version(s): v7.5.4
- Node/npm version: Node 10.16.0/npm 6.9.0
- OS: Windows 10
- Monorepo: no
- How you are using Babel: `cli`

**Comment by JLHwung** [comment]
The unit test fails after `Object.getOwnPropertyDescriptor` is [stub to return false](https://github.com/twbs/bootstrap/blob/master/js/tests/unit/dom/manipulator.js#L57). 

Since 7.5.0, the `objectSpread` will [call](https://github.com/babel/babel/blob/v7.5.4/packages/babel-helpers/src/helpers.js#L418) `Object.getOwnPropertyDescriptor` under the hood to filter enumerable properties. However, since most of time a `DOMStringMap` would not include a symbol key and `Object.keys()` always return enumerable string properties, `objectSpread` should not invoke `Object.getOwnPropertyDescriptor`.

Though it seems quite irrelevant on the surface. This issue would be fixed by #10189.

A workaround will be to remove the stub and wait until #10189 is released. After it is released it should be okay to keep the stub.

**Comment by nicolo-ribaudo** [comment]
Note: while I'm happy that this issue has been fixed for your use case, unfortunately Babel can't guarantee that it works (or will work) when built-in functions have been modified in a nonstandard way.

**Comment by Johann-S** [comment]
Thanks @JLHwung it was because of our unit tests nothings related to Babel here 👍
