### ISSUE TITLE
code split fail with preset-env modules:commonjs  v7.5.4 

### ISSUE THREAD

**Issue by Bermudarat** [babel/babel#10202]
## Bug Report

**Current Behavior**
code split fail with preset-env modules:commonjs  v7.5.4 

**Expected behavior/code**
when modules: 'common' and plugin @babel/plugin-syntax-dynamic-import''; babel will tranfrom import(...) to require(...),  then will cause code split fail

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
    presets: [
        [
            '@babel/preset-env',
            {
                modules: 'commonjs'
            }
        ],
        '@babel/preset-react'
    ],
    plugins: [
        '@babel/plugin-syntax-dynamic-import'
    ]
};
```

**Environment**
- Babel version(s): v7.5.4
- Node/npm version: v11.6.0/6.5.0-next.0
- OS: [e.g. OSX 10.13.4, Windows 10] OSX
- Monorepo: [e.g. yes/no/Lerna]no
- How you are using Babel: [e.g. `cli`, `register`, `loader`] cli

**Comment by nicolo-ribaudo** [comment]
`@babel/preset-env` goal is explicitly to transpile all the standard syntax features which aren't supported by your target environment.
If you don't specify any target (like in your config), it defaults to "every engine". For this reason, it needs to transpile it to "something" and since you specified that you want your modules to be transformed to CommonJS, it will transform it to a `require` call.
That said, we have a bug: for example node 12 supports `import()`, but even when it is the only target we currently transpile it.

The reason you saw the change in it's behavior is because `@babel/preset-env` supports "the latest JavaScript" (quoting the docs), i.e. "standard JavaScript", and `import()` just become standard.

You will be soon able to disable it using the preset's `exclude` option (https://github.com/babel/babel/issues/10194#issuecomment-510369452). In the meanwhile, you can work it around using `modules: false` and including `@babel/plugin-transform-modules-commonjs` in your plugins.

**Comment by nicolo-ribaudo** [comment]
Out of curiosity, if you are using a bundler which supports code splitting, why do you need to transpile modules to commonjs?

**Comment by JLHwung** [comment]
Close it as it duplicates #10273.
