### ISSUE TITLE
Update lodash dependency

### ISSUE THREAD

**Issue by josias-r** [babel/babel#10226]
Released yesterday, causes a lot of high severity vulnerabilities.
https://www.npmjs.com/advisories/1065

**Comment by grappler** [comment]
This seems to be fixed in https://github.com/babel/babel/pull/10191 Just waiting for a release.

**Comment by nicolo-ribaudo** [comment]
Fixed in v7.5.5

**Comment by cdeutsch** [comment]
When I run `npm audit`, `@babel/types` still reports issues, because it's referencing an old version of `lodash`

![image](https://user-images.githubusercontent.com/404765/62738675-7eaff700-b9f8-11e9-8967-6699faa42e84.png)

It seems like it should install a newer version, but something seems to be locking it
