### ISSUE TITLE
babel-parser: missing errors on assignment pattern in object expression

### ISSUE THREAD

**Issue by jj-choi** [babel/babel#10262]
## Bug Report

**Current Behavior**
Does not throw errors

**Input Code**
Bug
```js
var obj = {
  foo = 123, // no error
  bar: x = 123
};
```
Works fine
```js
var obj = {
  foo = 123 // SyntaxError: Unexpected token
};
```

**Expected behavior/code**
Should throw errors.
Chrome
SyntaxError: Invalid shorthand property initializer
TypeScript
error TS1312: '=' can only be used in an object literal property inside a destructuring assignment.

**Environment**
Babel version(s): 7.5.5
Node/npm version: Node 11.13 / npm 6.7

**Comment by tanhauhau** [comment]
@jj-choi it throws error in v7.5.5 ([repl](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBA9gRgVhAvBA3gKAhAZlKSICMATAMwQD05EAygJ4B2ALiAB4CiYYUYAXBAKr0ApiwAOQgMaMhAEwiMoAayH00AXwDcaIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.5.5&externalPlugins=))

**Comment by jj-choi** [comment]
@tanhauhau that is not buggy case.
First code is a bug code.

**Comment by rajasekarm** [comment]
I'll pick this.

**Comment by VivekNayyar** [comment]
@nicolo-ribaudo I don't a see a PR for this yet. Can I pick this up?

**Comment by rajasekarm** [comment]
@vivek12345 I tried fixing it, But I didn't get the fix. I you want to do a pair programming we can do.

**Comment by vivek12345** [comment]
@rajasekarm I am also struggling on this. Will check with @nicolo-ribaudo for some help here to guide us in the right direction.
@nicolo-ribaudo so far I have understood that the problem could be starting from here
https://github.com/babel/babel/blob/3a7b6e1c22bd844f5e16bffd56938fec93762d5e/packages/babel-parser/src/parser/expression.js#L1683

and somehow the code is not reaching this point
https://github.com/babel/babel/blob/3a7b6e1c22bd844f5e16bffd56938fec93762d5e/packages/babel-parser/src/parser/expression.js#L240

```
else if (failOnShorthandAssign && refShorthandDefaultPos.start) {
```
This condition somehow is not getting satisfied for the above issue.

Any guidance here? Thank you

**Comment by rajasekarm** [comment]
@vivek12345 I struck at the same place.

**Comment by nicolo-ribaudo** [comment]
@vivek12345 The problem is then we reset `refShorthandDefaultPos`:

https://github.com/babel/babel/blob/46c70ad73460606eeb93371776e112f54d2f156a/packages/babel-parser/src/parser/expression.js#L209

We do so when parsing a valid assignment expression. This is probably done because if, after parsing an object, we find the `=` token then it was a pattern and we don't have to throw:
```js
var obj = { foo = 123 } = {};
```

Unfortunately this resets the position even for unrelated assignments. In the original example, when it finds `x = 123` it resets the position of `foo = 123`.
I think that we only need to reset it if `refShorthandDefaultPos.start` is _after_ the beginning of the `AssignmentExpression` node that we are parsing in `parseMaybeAssign`, so that it doesn't hide information about previous invalid properties.

**Comment by vivek12345** [comment]
Understood. That makes it a lot more clear to me now. I had seen that reset but had no clue why was it used.

I will start to think now with this in mind and the approach you mentioned so that we can fix this too :)

**Comment by rajasekarm** [comment]
@vivek12345 we can do a pair programming this week end and try to fix this. Let me know if it works for you.
