### ISSUE TITLE
@babel/plugin-transform-block-scoping throw an error when required

### ISSUE THREAD

**Issue by dmail** [babel/babel#10279]
## Bug Report

**Current Behavior**

Requiring `@babel/plugin-transform-block-scoping` directly throw an error.

**Input Code**

```js
require("@babel/plugin-transform-block-scoping")
```

The code above will fail, you can try it here: https://runkit.com/dmail/block-scoping-missing-babel-core.

I made a screenshot of the output below:

![image](https://user-images.githubusercontent.com/443639/62115665-130fb080-b2b9-11e9-93a6-203a208d6b74.png)

**Expected behavior/code**

It should find `@babel/core`.

**Environment**

Fails in any environment without `@babel/core` inside its package.json `"dependencies"`.

- Babel version(s): 7.5.5
- Node/npm version:  10.16
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: no

**Possible Solution**

It is because `@babel/core` is declared in `"devDependencies"` of package.json here

https://github.com/babel/babel/blob/f08062b1deaf34d28726d0ef825821d060cb8554/packages/babel-plugin-transform-block-scoping/package.json#L21-L22

I think it should be moved inside `"dependencies"`.

**Comment by JLHwung** [comment]
`@babel/plugin-transform-block-scoping` declares `@babel/core` as a peer dependency, (if you are curious, [here](https://nodejs.org/es/blog/npm/peer-dependencies/) is why), which means the user should install `@babel/core` by themselves, otherwise they will get a warning message from the package manager.

If you are experimenting on runkit, I would suggest require `@babel/core` before any babel plugin. Note that the [npm runkit](https://npm.runkit.com/@babel/plugin-transform-block-scoping) will automatically require any peer dependencies for you.

**Comment by dmail** [comment]
I see, thanks for the explanation.

I have a strange file structure after npm install like this:
```
node_modules/
  @babel/
    plugin-transform-block-scoping/
  whatever
    node_modules/
      @babel/
        core/
```

But it's either my fault because I have badly configured some package.json or npm's fault because in some corner cases it does not put @babel/core where it should be.
In any case it's not yours.
Thanks for your rime.
