### ISSUE TITLE
[CLI]: have a dedicated  flag which prints local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [babel/babel#10296]
Presently, the `ISSUE_TEMPLATE` asks the user to provide his local environment information while submitting bug reports. IMO it would be good to have a dedicated flag, `babel --info` which serves the purpose.

**Comment by JLHwung** [comment]
I think we don't have to add a flag to babel cli since there are many issues related to integrations with other devtools. In these cases our users are not supposed to install `@babel/cli`. 

Alternatively we can provide some diagnostic scripts to report babel configuration, os version, node version, package.json, etc. And the user is expected to copy and paste the results instead of manually report on the issue template.

**Comment by jamesgeorge007** [comment]
so, how are we gonna go ahead :thinking:
