### ISSUE TITLE
Issue with `node_modules` ignoring

### ISSUE THREAD

**Issue by julien-f** [babel/babel#1038]
As specified in the documentation, all files which contains the `node_modules` substring in their path are not transpiled.

Unfortunately it causes an issue for my use case: I want to distribute an executable via npm which contains some ES6 code. It does not work because it is installed (via `npm i -g`) in `/usr/lib/node_modules`.

It works neither with `babel-node` or `require('babel/register')`.

One solution could be to set `ignore` to `false` but it seems rather inelegant/inefficient and I think there should be a way to fix this use case otherwise I do not really see the usage of `babel-node` and `babel-register` if they cannot be use in a published package.

**Comment by sebmck** [comment]
Please see the similar discussion in #1026.

**Comment by julien-f** [comment]
So your point is to never use `babel/register` in a published package?

**Comment by sebmck** [comment]
Basically. I know this is basically an "application" since you're distributing an executable but you're going to get at least a seconds worth of overhead just using `babel-node` since it has to initialise itself and load all the required files. The next major is going to have nicer `ignore`/`only` options where you can specify a file path similared to `.gitignore` etc which may fit your use-case.

---

> #### Not suitable for libraries
> The require hook automatically hooks itself into all node requires. This will pollute the global scope and introduce conflicts. Because of this it's not suitable for libraries, if however you're writing an application then it's completely fine to use.

Reference: https://babeljs.io/docs/usage/require/

**Comment by julien-f** [comment]
Thanks for your answer.
