### ISSUE TITLE
Invalid Typescript Types in lib/index.d.ts since 7.6.0

### ISSUE THREAD

**Issue by adamdbradley** [babel/babel#10403]
## Bug Report

**Current Behavior**
`node_modules/@babel/types/lib/index.d.ts` has invalid typescript since the 7.6.0 release: https://unpkg.com/browse/@babel/types@7.6.0/lib/index.d.ts line 2098

```
export function isNode(node: ?object): boolean
```

**Environment**
- Babel version(s): 7.6.0

**Possible Solution**
Move the `?` before the `:`

**Comment by forstermatth** [comment]
We can't move the `?` unless you move the argument order, since the affected arguments are before others that are not optional.

**Comment by milesj** [comment]
@forstermatth Not sure what you mean. The `?<type>` is invalid TS and is crashing any TS apps using Babel 7.6. This PR caused the issue: https://github.com/babel/babel/pull/10098

@tanhauhau

**Comment by forstermatth** [comment]
Yes - the possible solution offered in the report body would be incorrect. See my PR #10404

**Comment by trs** [comment]
@milesj It looks like the `?<type>` syntax is a [flow maybe type](https://flow.org/en/docs/types/maybe/).
Changing these to a typescript optional type would fail in cases such as [`export function isPlaceholderType(placeholderType: ?string, targetType: string): boolean`](https://github.com/babel/babel/blob/master/packages/babel-types/scripts/generators/typescript.js#L158) since non-optional types cannot follow an optional type.
If `null` or `undefined` are also explicitly allowed, then https://github.com/babel/babel/pull/10404 would be correct.

**Comment by starksds** [comment]
fyi, I reverted back to 7.5.5 and the error went away

**Comment by lancegliser** [comment]
Just for clarity. If you're going move back to 7.5.5, you should declare the `@babel/types` dependency directly. I had devDependencies for `@babel/cli`, `@babel/core`, `@babel/preset-env,` all pointing at 7.5.5. but they all allowed the upgraded version causing this issue.

**Comment by dantehemerson** [comment]
I have the same error using Nestjs

**Comment by cperryk** [comment]
For reference/searchability, the precise error on compiling is this: `node_modules/@babel/types/lib/index.d.ts:2098:30 - error TS8020: JSDoc types can only be used inside documentation comments.`

**Comment by nicolo-ribaudo** [comment]
Fixes in `@babel/types` 7.6.1. Thanks @forstermatth!
