### ISSUE TITLE
"Uncaught RangeError: Maximum call stack size exceeded" on Android 2.3 stock browser

### ISSUE THREAD

**Issue by lucaspiller** [babel/babel#1061]
I'm getting this exception when trying to use the Babel 4.7.16 polyfill on the Android 2.3 stock browser. I've cut my code down to the following (running through Webpack):

```es6
alert('Loading...');
import "babel/polyfill";
alert('Success');
```

I get the first alert, but after dismissing it I get this error logged in the ADB console.

I also got the same on the playground with the following URL:

http://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=alert(%22hello%22)%3B

Here is the debug log that Android gives for that page:

```
I/v8      ( 3017): Uncaught RangeError: Maximum call stack size exceeded
E/browser ( 3017): Console: Uncaught ReferenceError: babel is not defined http://babeljs.io/scripts/repl.js?t=2015-03-21T03:00:17+00:00:1
```

**Comment by sebmck** [comment]
Looks like a _possible_ issue with [core-js](https://github.com/zloirock/core-js). Please report it there.

**Comment by zloirock** [comment]
I don't test `core-js` with obsolete mobile platforms and hasn't necessary test environment. IIRC, v8 in 2010 had not fully support ES5, default `babel/polyfill` not contains ES5 polyfill. You can try `core-js/client/shim` + `regenerator/runtime` instead of `babel/polyfill`, but not sure it will help - part of ES5 features are breaking in five-year-old v8, `core-js` ES5 polyfill at first oriented to support old IE. Also you can try `es5-shim`.
