### ISSUE TITLE
iterableToArray transitive usages not polyfilled 

### ISSUE THREAD

**Issue by RobHannay** [babel/babel#10625]
## Bug Report

**Current Behavior**
When spreading a new Set with core-js 'usage', transitive dependencies are not polyfilled which breaks IE11.

We saw this live when it was not polyfilling 'Array.from', but on this repro it fails earlier because Symbol is also not polyfilled. 

If Symbol is added manually it then fails saying it's not an iterable instance, but works fine on Chrome/FF.

Also if you use `Array.from(new Set([]));` it works fine.

**Input Code**
Access the Webpack dev server on Internet Explorer and see console errors.
https://babel-corejs-reproduce-set-spread.robhannay.repl.co

Code
https://repl.it/@robhannay/babel-corejs-reproduce-set-spread

**Expected behavior/code**
Expected the Symbol (or Array.from) 'usage' to be detected from within the iterableToArray method and itself be polyfilled

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [
    ['@babel/preset-env', {
      modules: false, // Module transpilation is handled by Webpack
      corejs: 3,
      useBuiltIns: 'usage',
    }],
    '@babel/preset-react',
  ],
  plugins: [
    '@babel/plugin-transform-strict-mode',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-transform-object-assign',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-transform-modules-commonjs',
    '@babel/plugin-transform-runtime',
    '@babel/plugin-proposal-class-properties',
  ],
}
```

**Environment**
- Babel version(s): v7.6.4
- Node/npm version: Node 12 / npm 6 (the repl.it runs on Node 10 but can see the same issue)
- OS: OSX local / Linux build producted same result
- Monorepo: no
- How you are using Babel: loader

**Additional context/Screenshots**

<img width="407" alt="Screenshot 2019-11-01 at 12 34 12" src="https://user-images.githubusercontent.com/609062/68025117-eeeeb180-fca3-11e9-9faf-bd6a3af9b93e.png">

**Comment by nicolo-ribaudo** [comment]
If you aren't passing a file to Babel (you are excluding it in your webpack config with `exclude: /node_modules/`), Babel can't transform that code.

I usually suggest transforming the specific node_module with Babel, but since `@babel/runtime` is a Babel module itself it's really risky.

I suggest aliasing `@babel/runtime` to `@babel/runtime-corejs3` in your webpack config: https://repl.it/@nicolo_ribaudo/babel-corejs-reproduce-set-spread-1

**Comment by zloirock** [comment]
> I suggest aliasing `@babel/runtime` to `@babel/runtime-corejs3` in your webpack config.

For load both dependencies - `core-js` and `core-js-pure`? -) For proper work, in this case, required a version of `runtime`, compiled with injecting global `core-js` version.

**Comment by dcleao** [comment]
When you use `@babel/plugin-transform-runtime` without any options, the default for the `corejs` is `false`, which, per the [docs](https://babeljs.io/docs/en/babel-plugin-transform-runtime#corejs) means that the babel helpers with require modules from `@babel/runtime`.

The latter implementation of the babel runtime does not safe-guard any of its code, by importing `core-js` shims or by other means.

So, I'd say that this is not a bug, but by design.

If you want to include a version of the babel runtime which is safe for operation in certain browsers, you'll have to include one of the alternative provided builds: `@babel/runtime-corejs2` or `@babel/runtime-corejs3`. You can do this by specifying the value `2` or `3` for the option `corejs` of the `@babel/plugin-transform-runtime` plugin...

Unfortunately, any of the mentioned builds end up depending and delegating on `core-js-pure`. If you have other code which is already using the non-pure `core-js` version, then you'll end up including the "same" core-js code twice.

**Comment by nicolo-ribaudo** [comment]
Another option is to transpile `@babel/runtime` with `@babel/preset-env`.
We have been discouraging it for two reasons:
- `@babel/plugin-transform-runtime` can't be used to transpile `@babel/runtime` because it will inject circular dependencies. This can be solved by excluding that plugin for this package.
- `@babel/preset-env` could have some problems when transpiling the `@babel/runtime/helpers/typeof` helper with `@babel/plugin-transform-typeof-symbol`. At this point, your `@babel/preset-env` targets already exclude that polyfill, otherwise it needs to be explicitly excluded when transpiling this package.

**Comment by nicolo-ribaudo** [comment]
It's now safe to transpile `@babel/runtime}.
