### ISSUE TITLE
Transform regex error in safari

### ISSUE THREAD

**Issue by tbergq** [babel/babel#10699]
## Bug Report

**Current Behavior**
Regex capturing group is not working in safari, but works in chrome

```js
const regExp = /(?<word>[a-z])\w+/;
  return timeDuration
    .split(' ')
    .reduce((acc, item) => {
      if (regExp.test(item)) {
        acc.push(item[0]);
        return acc;
      }
      acc.push(item);
      return acc;
    }, [])
    .join(' ')
    .replace(/(?<=\d)\s/g, '');
```

**Expected behavior/code**
It works in all browsers

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["@kiwicom/babel-preset-kiwicom", "next/babel"],
  "plugins": [
    [
      "react-native-web",
      {
        "commonjs": true
      }
    ],
    "relay",
    [
      "styled-components",
      {
        "displayName": true,
        "preprocess": false
      }
    ]
  ]
}``

**Environment**
- Babel version(s):7.7.2
- Node/npm version: 12.13.0
- OS: OSX
- Monorepo:yes
- How you are using Babel: [e.g. `cli`, `register`, `loader`]: nextjs



**Additional context/Screenshots**
SyntaxError: Invalid regular expression: invalid group specifier name (`replace(/(?<=\d)\s/g, '')`)

**Comment by JLHwung** [comment]
There is a [lookbehind assertion](https://github.com/tc39/proposal-regexp-lookbehind) in `/(?<=\d)\s/g`, which Safari [does not support](https://kangax.github.io/compat-table/es2016plus/#test-RegExp_Lookbehind_Assertions) yet. Babel only allows parsing lookbehind assertion but could not transform since it is an engine feature that could not be polyfilled.
