### ISSUE TITLE
BabelRegExp breaks deepStrictEqual with RegExp

### ISSUE THREAD

**Issue by jeysal** [babel/babel#10703]
## Bug Report

**Current Behavior**
Regexp literals with named capture groups create `BabelRegExp` instances, which Node does not consider to `assert.deepStrictEqual` `RegExp` instances created using the constructor. Their `.source` also differs.

**Input Code**
- REPL or Repo link if applicable:
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBATgRhgXhmApgdxgJXQcwFEAPABwAoByAWnIH4AeMAPgBMBKS9gbgChRIsOACYUMAPS1GLDuL4CIIADboAdEpD5yInryA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cenv&prettier=false&targets=Node-8&version=7.7.3&externalPlugins=
(does not include the assert call of course, but console.log shows `BabelRegExp` instead of `RegExp`)

```js
const r1 = new RegExp('-(?<n>d)');
const r2 = /-(?<n>d)/;
require('assert').deepEqual(r1, r2);
```

**Expected behavior/code**
Does not throw

**Babel Configuration (.babelrc, package.json, cli command)**

See REPL link

**Environment**
- Babel version(s): 7.7.3
- Node/npm version: Node 12
- OS: Linux 5.3.8
- Monorepo: no
- How you are using Babel: `babel-loader`

**Possible Solution**

Not entirely sure because I don't have context on why it is compiled that way and why only for literals, not for `new RegExp`s.
If the subclass and source changes are absolutely necessary, perhaps we can customize deep equality with something like a `valueOf`? I believe [this](https://github.com/epoberezkin/fast-deep-equal) is Node's equality impl.

**Additional context/Screenshots**
-

**Comment by jeysal** [comment]
Found https://github.com/babel/babel/pull/7105 - perhaps the `runtime` flag mentioned there would work, but `preset-env` does not enable it? https://github.com/babel/babel/pull/9345

**Comment by nicolo-ribaudo** [comment]
We have to wrap regexps with our own class to make things like `.groups` work. We can't do it for `new RegExp` because, since the argument is dynamic, we can't handle it at build-time.

There are two possible cases with your original example code:
1) Your engine supports named capturing groups. You can then configure your `preset-env` targets so that it doesn't wrap the syntactic regexp with the custom wrapper.
2) Your engine doesn't support named capturing groups: Babel will wrap your syntactic regexp, but the runtime regexp will throw an error and that test will fail before reaching `assert`.

If for some reason you still want to transpile the regexp even if your browser supports named groups, you can exclude it from `preset-env` using the `exclude` option and then enable `@babel/plugin-proposal-transform-named-capturing-groups-regex` with the `runtime` option.

**Comment by jeysal** [comment]
Sorry, I thought I had tried it with a higher target but apparently the config didn't apply - targeting Node 10 the transform is not applied. In my case this will work, but good to hear that you also expect that `runtime` could be used to work around this otherwise (if someone also needs it to work on old Node versions).
