### ISSUE TITLE
@babel/preset-env adding unnecessary core-js polyfill

### ISSUE THREAD

**Issue by serenader2014** [babel/babel#10758]
## Bug Report

**Current Behavior**
@babel/preset-env is adding unnecessary core-js polyfill, when setting @babel/preset-env 's target options to `chrome 49`, for a quite simple one line code :`window.location.search`, babel will produce a useless core-js polyfill: 

```js
"use strict";

require("core-js/modules/es6.regexp.search");

window.location.search;
```

The weird thing is, when changing the target browsers to `chrome 50`, the polyfill is gone. So why babel will produce this `es6.regexp.search` polyfill for this code under chrome 50 version?

**Input Code**

REPL link: https://babeljs.io/repl#?babili=false&browsers=chrome%2049&build=&builtIns=usage&spec=false&loose=false&code_lz=O4SwdgJg9sB0A2UDGBDALiKZYGcCmKATkgBYDcQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.7.4&externalPlugins=

**Expected behavior/code**

Base on the input from the REPL link, the result should not contain core-js polyfill.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by JLHwung** [comment]
There is two questions here. The first one is why `regexp.search` polyfill is applied. The `regexp.search` polyfill kicks in because `window.location` could be overwritten as RegExp:
```js
(function (window) {
  window.location = /foo/;
  window.location.search("foo");
})({})
```
so when Babel sees a pattern like `foo.bar.search`, it would assume that `foo.bar` may be a RegExp and inject the `regexp.search` polyfill if the browser does not support `regexp.search`.

The other question is why it is applied under `chrome 50`. Babel uses data in [compat-table](https://github.com/kangax/compat-table/blob/00c38de1aa9fe5e53760970ce7d91bb576ef9c6d/data-es6.js#L17766) to determine when the polyfill should apply. However I do notice that `chrome 49` is marked as supported on [browser-compat-data](https://github.com/mdn/browser-compat-data/blob/1c977302563a8be9f48574a98ec2bfb45ca1b94d/javascript/builtins/RegExp.json#L1955), which is conflicted with `compat-table`.

If you have `chrome 49` test environment and confirm it works under `chrome 49`, could you submit a PR to `compat-table`? Then `preset-env` will benefit from this change.

**Comment by zloirock** [comment]
> Babel uses data in compat-table to determine when the polyfill should apply

Wrong.

**Comment by serenader2014** [comment]
> so when Babel sees a pattern like foo.bar.search, it would assume that foo.bar may be a RegExp and inject the regexp.search polyfill if the browser does not support regexp.search.

That sounds weird to me. So how can I use `window.location.search` without having a polyfill? Is there anyway to tell babel not to polyfill a specific file?

**Comment by nicolo-ribaudo** [comment]
Closing since, form Babel's point of view, `window.location.search` could call the `search` method of a regexp and thus need the polyfill.

You can explicitly pass `exclude: ["es.symbol.search"]` to preset-env to exclude it.
