### ISSUE TITLE
classNameTDZError in computed prototype methods with class fields 

### ISSUE THREAD

**Issue by huarse** [babel/babel#10766]
## Bug Report

**Input Code**

```js
class Foo {
  static nickname = 'Tom';

  ['HELLO']() {
    console.log('>>>>', Foo);
  }
}
```

**Output code with babel**

```js
"use strict";

function _classNameTDZError(name) { throw new Error("Class \"" + name + "\" cannot be referenced in computed property keys."); }

class Foo {
  ['HELLO']() {
    console.log('>>>>', (_classNameTDZError("Foo"), Foo));
  }

}

Foo.nickname = 'Tom';
```

However, when I put the `static nickname = 'Tom';` out of the class,  like `Foo.nickname = 'Tom';` or just remove this line, the output code is correct

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```json
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": ["Chrome >= 65", "Firefox >= 55", "Safari >= 11"]
      },
    }],
  ],
  "plugins": [
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
  ]
}
```

**Environment**

```
- Babel version(s): 7.6.4
- Node/npm version: 12.13.0 / 6.12.0
- OS: OSX 10.14.6
- How you are using Babel: cli

**Comment by JLHwung** [comment]
[Here](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1oCMwCcDcLoG0ByAMwHtTCBdACgEpE5oBfJJoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.7.4&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.7.4) is a minimal reproducible example on REPL.
```js
class C {
  bar;
  ['foo']() { C }
}
```

This ClassName TDZ was firstly introduced at #6855. It was supposed to throw reference error when class is referenced in the _key_ of the computed path
```js
class C {
  [C + 42]{};
}
```
However we should not throw when `C` is referenced in the _body_ of the computed path. Here is the code that we should pay attention to
https://github.com/babel/babel/blob/7f732ad0198004a1d31543ddd848e6edc646e771/packages/babel-helper-create-class-features-plugin/src/misc.js#L89-L92

The `computedPath` is the whole computed property definition (i.e. `[C + 42]{}`), instead of traversing from the `computedPath`, we may consider to traverse from `C + 42`.

You may learn the structure of the AST node on [Babel AST Browser](https://lihautan.com/babel-ast-explorer/#?eyJiYWJlbFNldHRpbmdzIjp7InZlcnNpb24iOiI3LjYuMCIsIm9wdGlvbmFsQ2hhaW5pbmciOnsib3B0aW9ucyI6e30sImVuYWJsZWQiOmZhbHNlfSwiZHluYW1pY0ltcG9ydCI6eyJvcHRpb25zIjp7fSwiZW5hYmxlZCI6ZmFsc2V9LCJjbGFzc1Byb3BlcnRpZXMiOnsib3B0aW9ucyI6e30sImVuYWJsZWQiOnRydWV9fSwidHJlZVNldHRpbmdzIjp7ImhpZGVFbXB0eSI6dHJ1ZSwiaGlkZUxvY2F0aW9uIjp0cnVlLCJoaWRlVHlwZSI6dHJ1ZSwiaGlkZUNvbW1lbnRzIjp0cnVlfSwiY29kZSI6ImNsYXNzIEMge1xuICBiYXI7XG4gIFsnZm9vJ10oKSB7IEMgfVxufSJ9)



If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest babel-helper-create-class-features-plugins` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

@huarse Let me know if you want to give it a try. I will tweet this as good first issue tomorrow.

**Comment by nicolo-ribaudo** [comment]
Note that we also must make sure that it still throws when the class binding is used inside the initializer of a static class property.

**Comment by huarse** [comment]
@JLHwung I was trying to understood the code you mentioned , and then I found that even the feature **Implement TDZ for ClassFieldDefinitionEvaluation** has missed some case, eg. 

```js
class C {
  [C] = () => {};
}
``

this code would be add a `_classNameTDZError` wrapper,  but,

```js
class C {
  [C]() {}
}
```
this code would not be wrapped `_classNameTDZError`

**Comment by JLHwung** [comment]
@nicolo-ribaudo I don't think it should throw when the static field initializer references class binding. The initializer definition will be wrapped as function in [`ClassFieldDefinitionEvaluation`](https://tc39.es/proposal-class-fields/#runtime-semantics-class-field-definition-evaluation), which will be executed later in [`DefineFields`](https://tc39.es/proposal-class-fields/#sec-define-field). For static fields, `DefineFields` run _after_ `classScopeEnvRec.InitializeBinding(className, F)` in [`ClassDefinitionEvaluation`](https://tc39.es/proposal-static-class-features/#runtime-semantics-class-definition-evaluation), which means by the time when initializer is executed, the class binding has been initialized. For example,
```js
class C { static P1 = 42; static P2 = (C.P1 === 42) }; C.P2;
// true
class D { static P2 = (D.P1 === 42); static P1 = 42; }; D.P2;
// false
```

@huarse The first example
```
class C {
  [C] = () => {};
}
```
demonstrates a computed class field and it should be processed by `@babel/plugin-proposal-class-properties`. On the other hand, `@babel/plugin-proposal-class-properties` should only take care on the computed class properties and leave computed method untouched.

The second example is computed class methods, and ideally it should be processed by `@babel/transform-classes` only, which means if user does not specified `transform-classes`, we should assume the browser has proper support on ClassNameTDZ on class methods so we don't add artificial check at all. On the other hand, if `transform-classes` is specified, the following code should include `_classNameTDZError`
```js
class C {
  [C]() {}
}
```
Currently it does not throw so it is considered another bug.

**Comment by sidntrivedi012** [comment]
Hi all, I would like to work on this issue. Thanks.

**Comment by sidntrivedi012** [comment]
@JLHwung Was looking into this issue but not able to proceed with how to triage it. Can you please give any directions? Thanks.
