### ISSUE TITLE
Use of `arguments` should be permitted even in a field initializer, if the field is initialized with a class expression.

### ISSUE THREAD

**Issue by Elberet** [babel/babel#10771]
## Bug Report

**Current Behavior**
Any use of `arguments` within a class field initializer leads to `'arguments' is not allowed in class field initializer`, even when such a limitation appears unwarranted - e.g. if the class field is initialized with a class expression and `arguments` appears inside one of the declared class' methods.

**Input Code**
```js
class Voodoo {
  static magic = {
    wizardry: class extends Witchcraft {
      cast() {
        super.cast(...arguments)
      }
    }
  }
}
```
See also [babeljs.io/repl](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEBqD28AmjoG8BQ1oQC5lwEthoBbMAc2OgF50ttoB3QgLzACckOBPALmihIMAKYAPXCIB2SGAHVCuYAAtgHMADNc9Ro2CRcACgCUO3YwgBXAA4iOAOn15D915wqXS03BGMNdAL7-0EHYQQFAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Cstage-2&prettier=false&targets=&version=7.7.4&externalPlugins=)

**Expected behavior/code**
The example code should transpile without error; the class field initializer scope should not prevent use of `arguments` in a field initializer once it has been bound to some scope declared within the initializer and can no longer refer to the original class' constructor arguments.

**Comment by JLHwung** [comment]
[Here](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1oAdoF5qkjZqqAtgBQCUi0ATgKYAuArlQHbRhUDmDRNzdMAXxTQhAoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.7.4&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.7.4) is a minimal reproducible example.

Babel will throw "arguments not allowed" error when checking if an identifier name is a reserved word.
https://github.com/babel/babel/blob/4e774b726475aff9a6a1d2111afec21158979566/packages/babel-parser/src/parser/expression.js#L2197-L2203

As one can see it depends on the parser state `this.state.inClassProperty`. To solve this issue, we may pay attention to the class declaration parser

https://github.com/babel/babel/blob/4e774b726475aff9a6a1d2111afec21158979566/packages/babel-parser/src/parser/statement.js#L1144-L1151

You may notice that the parser state `this.state.strict` is pushed by a new value `true` and then popped after the class declaration has been parsed, so that during the class declaration is being parsed, we are always enforcing a strict mode. We may consider to do some similar maneuvers for `inClassProperty`.

Note that it is upon your discretion to determine _where_ the `inClassProperty` should be pushed a new value, you can place it _before_ `parseClassId` or _before_ `parseClassBody`, which will have subtle behaviour difference.

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated) to `packages/babel-parser/test/fixtures/experimental/class-properties/arguments-in-class`.
1. Update the code!
1. `yarn jest babel-parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

@Elberet Let me know if you want to give it a try or not.

**Comment by Elberet** [comment]
@JLHwung Sure, I can prepare a PR, but I think there are still some questions to discuss and I don't feel sufficiently proficient with the TC39 spec to decide all the answers myself - especially, for which nodes exactly the `inClassProperty` state flag should be reset.

For example, resetting the flag before parsing the class body may permit access to `arguments` within decorator call expressions:
```js
class C {
  p = class {
    @d(arguments)
    m() { }
  }
}
```
This is, IMO quite obviously, wrong. The decorator's value is evaluated at the same time the class expression is evaluated, which happens when the class field is initialized, and in that scope `arguments` should not be accessible.

Gut instinct tells me that the right place to reset the `inClassProperty` flag would be here:
https://github.com/babel/babel/blob/2cd5ad0c8026ecaf55335eb152fb13ab650fd78f/packages/babel-parser/src/parser/expression.js#L1931-L1939
but then if I were to review that code I'd loudly complain that `inClassProperty` is being abused to track whether we have a proper function scope for `arguments` et al - so maybe we should refactor the whole thing and add a new `inFunctionScope` state?

**Comment by JLHwung** [comment]
@Elberet Good point! If we reset `inClassProperty` in `parseFunctionBody`, the following case would be a false negative
```js
class C { P = () => arguments }
```

But I believe you have pointed to the correct direction, we can check if the scope where `arguments` resides is the same scope as we have toggled on `inClassProperty`. However, instead of recording another state points to the `inClassProperty` scope, I guess we can simply _replace_ `this.state.inClassProperties` by `this.scope.inClass` in the `checkReservedWord` condition
https://github.com/babel/babel/blob/4e774b726475aff9a6a1d2111afec21158979566/packages/babel-parser/src/parser/expression.js#L2197

There are two cases when `this.scope.inClass` is true. 1) When `arguments` is within the same scope of class properties, and apparently it should throw. 2) When `arguments` is in a nested class scope, it must be in one of class property or class private property, which should be thrown.

`this.scope.inClass` is not implemented but you can add one, which will be similar to
https://github.com/babel/babel/blob/4e774b726475aff9a6a1d2111afec21158979566/packages/babel-parser/src/util/scope.js#L52
