### ISSUE TITLE
fsevents 1.2.9 and chokidar 2

### ISSUE THREAD

**Issue by createthis** [babel/babel#10822]
seems like the latest version of cli requires chokidar 2 and fsevents 1.2.9, which is deprecated? I can't even install 1.2.9 anymore via npm. is anyone else experiencing this?

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/issues/10684, https://github.com/babel/babel/issues/9981#issuecomment-529808712, https://github.com/babel/babel/pull/10741

TL;DR: We can't upgrade to chokidar 3 because it doesn't support node 6, which we will still support until Babel 8.

Also, `fsevents` is an optional dependency which is only needed in MacOS, and won't be installed in any other OS.

**Comment by createthis** [comment]
@nicolo-ribaudo um. cool. but what is the resolution on MacOS?

**Comment by nicolo-ribaudo** [comment]
Until then, MacOS will use the deprecated version. It hasn't been deprecated for security reasons but only to speed up the upgrade to v2, so it's still safe.

**Comment by createthis** [comment]
The inability to install 1.2.9 turned out to be a local network issue. Thanks for taking the time to respond and sorry for the noise.
