### ISSUE TITLE
Bug: transpiled first argument in tagged template should not be immutable

### ISSUE THREAD

**Issue by wheresrhys** [babel/babel#10845]
## Bug Report

**Current Behavior**
After adding babel to a node project, a template tag that previously worked now errors when trying to mutate the value of the first argument

**Input Code**
```
// simplified test function
const stripEmptyFirstLine = (hardCoded, ...vars) => {
	hardCoded[0] = 'something else';
	return 'some dummy response';
};

const variable = 'a'

const it = stripEmptyFirstLine`
${variable}`
```
Results in this error:
```
  hardCoded[0] = 'something else';
               ^

TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at stripEmptyFirstLine (/Users/rhys.evans/Projects/or/treecreeper/demo/tag.js:2:2)
    at Object.<anonymous> (/Users/rhys.evans/Projects/or/treecreeper/demo/tag.js:8:32)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module._compile (/Users/rhys.evans/Projects/or/treecreeper/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.newLoader [as .js] (/Users/rhys.evans/Projects/or/treecreeper/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Expected behavior/code**
When evaluated in nodejs (version 8 through 12) without babel there is no error, and the argument can be mutated ok. [The spec](https://www.ecma-international.org/ecma-262/6.0/#sec-tagged-templates) is quite dense, so I'm not sure what the spoecced behaviour, but as it's been possible in several versions of node, I presume that the correct behaviour is to have a mutable argument

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
	presets: [
		[
			'@babel/preset-env',
			{
				targets: {
					node: true,
				},
			},
		],
	]
}
```

**Environment**

```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.13.1 - /var/folders/7d/kjy_r2gn4qb2460p_sfhtd7r0000gn/T/fnm-shell-5407513/bin/node
    npm: 6.12.1 - /var/folders/7d/kjy_r2gn4qb2460p_sfhtd7r0000gn/T/fnm-shell-5407513/bin/npm
  npmPackages:
    @babel/cli: ^7.7.0 => 7.7.5
    @babel/core: ^7.7.2 => 7.7.5
    @babel/plugin-transform-react-jsx: ^7.7.0 => 7.7.4
    @babel/preset-env: ^7.7.1 => 7.7.6
    @babel/preset-react: ^7.7.0 => 7.7.4
    @babel/register: ^7.7.0 => 7.7.4
    jest: ^24.8.0 => 24.9.0
```

**Comment by JLHwung** [comment]
I can not reproduce this error on [REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBNBOBLADgUQLbKgTwGKPmgBlEwBTGAXhgAoALAQ3gBMBhEZs5gGhgDoBANyYQAlFQB8MAN4AoGDADyAIwBWZYFD4AzeGTIAvMvSZsOXUQG5ZASEYt2nZgG0ADAF0qMAOQQQ6Mig6UgBzGDIAGwgyb2sbPSgAV3gwHz8AmGZE9HRsGD0IZHBo2NkAX2tZUEhYYSQGZQiKam8Gb1kq4thEWGoEFAwsPAJiUjIAAwASaTrEBqay8aA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=Node-6.0&version=7.7.5&externalPlugins=). Actually according to your configuration, babel does not plug in any transforms since they get native supports on node.js 12

Can you come up with a reproducible example on REPL? It will help us narrow down the issue.

**Comment by nicolo-ribaudo** [comment]
It is specified to be frozen. You can test this in Chrome:

```js
Object.isFrozen((x => x)``)
```

Note that in loose mode frozen objects don't throw but fail silently: maybe you were testing it in loose mode in node, but transpiling modules (which are strict) with Babel?

Spec: Step 14 of https://tc39.es/ecma262/#sec-gettemplateobject, which is the algorithm which given a template literal node, generates the corresponding object.
