### ISSUE TITLE
Babel-node does not transpile files references by workers. Can/should it?

### ISSUE THREAD

**Issue by zachsa** [babel/babel#10972]
I find that using `new Worker(file.js)` (and file.js uses import statements), that babel loads the referenced script fine but babel-node doesn't. Is this a bug or related to how babel-node works (my understanding of these things is not so good)?

I have just posted a StackOverflow question with more detail: https://stackoverflow.com/questions/59662352/how-to-get-babel-node-to-convert-files-referenced-by-workers-to-commonjs-like

**Comment by JLHwung** [comment]
The `Worker` constructor does not invoke `Module` constructor so babel-node could not hook into the loader and apply the transformation. You can use `@babel/register` to hook into any files loaded _inside_ your worker:

file-wrapper.js
```js
require("@babel/register")
require("file.js") // your worker entry
```
main.js
```js
new Worker("file-wrapper.js")
```

**Comment by zachsa** [comment]
thanks - i'm quite new to this and would definitely be interested in knowing more about how the node.js module system works.

what is the Module constructor? I can see that there is no `Module` constructor in JavaScript (at least not in the browser or the Node.js repl)

**Comment by zachsa** [comment]
Another question - when using babel (not babel-node), it does actually work:

```
babel ./src --out-dir dist
```

That does convert the worker to commonjs.

**Comment by JLHwung** [comment]
> what is the Module constructor?

The `Module` constructor is actually the internal implementation of CommonJS module of Node.js: https://github.com/nodejs/node/blob/f9c16b87eff60858efa0b6977fa1d253be538589/lib/internal/modules/cjs/loader.js#L154, when a module is loading, it will call the functions registered in `Module._extensions`: https://github.com/nodejs/node/blob/f9c16b87eff60858efa0b6977fa1d253be538589/lib/internal/modules/cjs/loader.js#L1064. We call them loader hooks.

`babel-node` injects babel transform into loader hooks. For example, let's say you have an `index.js`, in which you are doing `require("lib.js")`. This is what happens when you are using `babel-node index.js`.

```
require("lib.js")
==> new Module("lib.js")
==> module._load 
==> Module._extensions[".js"]("lib.js")
==> babel transform(content of "lib.js")
==> run the transformed module
```

So if you are doing `new Worker("worker.js")`, the babel-transform is not applied like above because the `Worker` constructor does not call `new Module`, so does `Module._extensions["js"]`, so the execution code "worker.js" gets no chance to be transformed.

If you are using `babel-cli` to _precompile_ the code, that means you are doing
```
new Worker(transformed "worker.js")
```
It works because the execution code has been _transformed_.

**Comment by ZachSAEON** [comment]
Ah, thanks. But. the only reason that `babel-cli` knows to transform `worker.js` is that the file is referenced by the `Worker` constructor. Does this mean that `babel-cli` follows all file references whereas `babel-node` only follows module imports? Why is this?

Thank you very much for your answers. Out of interest, I see this line:

```
Module._extensions[extension](this, filename)
```

That looks like there is one loader per file extension. How does Node allow 3rd party code to be executed per module extension? I see the `.js` [extension function](https://github.com/nodejs/node/blob/f9c16b87eff60858efa0b6977fa1d253be538589/lib/internal/modules/cjs/loader.js#L1223-L1236). But I don't see where the babel transform function would be executed.

**Comment by JLHwung** [comment]
`babel-cli` transforms all the JavaScript files inside the `src` folder. It operates on per-file level and does not process the module references.

> How does Node allow 3rd party code to be executed per module extension?

Under the hood `babel-node` uses [pirates](https://github.com/ariporad/pirates), which overwrites `Module._extension[".js"]`. So when a module is loaded, the babel transform defined here will be executed: https://github.com/babel/babel/blob/a0a9c64a470acec77bec1da0b4bceec4ccf7f446/packages/babel-register/src/node.js#L62
