### ISSUE TITLE
TypeError: _typeof2 is not a function

### ISSUE THREAD

**Issue by GEOHOTIOS** [babel/babel#10996]
var _typeof2 = __webpack_require__(/*! @babel/runtime/helpers/typeof */ "./node_modules/_@babel_runtime@7.7.7@@babel/runtime/helpers/typeof.js");

function _typeof(obj) {
  if (typeof Symbol === "function" && _typeof2(Symbol.iterator) === "symbol") {
    module.exports = _typeof = function _typeof(obj) {
      return _typeof2(obj);
    };
  } else {
    module.exports = _typeof = function _typeof(obj) {
      return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : _typeof2(obj);
    };
  }

  return _typeof(obj);
}

module.exports = _typeof;//# sourceURL=[module]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9ub2RlX21vZHVsZXMvX0BiYWJlbF9ydW50aW1lQDcuNy43QEBiYWJlbC9ydW50aW1lL2hlbHBlcnMvdHlwZW9mLmpzLmpzIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4vbm9kZV9tb2R1bGVzL19AYmFiZWxfcnVudGltZUA3LjcuN0BAYmFiZWwvcnVudGltZS9oZWxwZXJzL3R5cGVvZi5qcz9kYjVlIl0sInNvdXJjZXNDb250ZW50IjpbImZ1bmN0aW9uIF90eXBlb2Yob2JqKSB7XG4gIGlmICh0eXBlb2YgU3ltYm9sID09PSBcImZ1bmN0aW9uXCIgJiYgdHlwZW9mIFN5bWJvbC5pdGVyYXRvciA9PT0gXCJzeW1ib2xcIikge1xuICAgIG1vZHVsZS5leHBvcnRzID0gX3R5cGVvZiA9IGZ1bmN0aW9uIF90eXBlb2Yob2JqKSB7XG4gICAgICByZXR1cm4gdHlwZW9mIG9iajtcbiAgICB9O1xuICB9IGVsc2Uge1xuICAgIG1vZHVsZS5leHBvcnRzID0gX3R5cGVvZiA9IGZ1bmN0aW9uIF90eXBlb2Yob2JqKSB7XG4gICAgICByZXR1cm4gb2JqICYmIHR5cGVvZiBTeW1ib2wgPT09IFwiZnVuY3Rpb25cIiAmJiBvYmouY29uc3RydWN0b3IgPT09IFN5bWJvbCAmJiBvYmogIT09IFN5bWJvbC5wcm90b3R5cGUgPyBcInN5bWJvbFwiIDogdHlwZW9mIG9iajtcbiAgICB9O1xuICB9XG5cbiAgcmV0dXJuIF90eXBlb2Yob2JqKTtcbn1cblxubW9kdWxlLmV4cG9ydHMgPSBfdHlwZW9mOyJdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSIsInNvdXJjZVJvb3QiOiIifQ==

**Comment by soryy708** [comment]
Perhaps related?
https://github.com/babel/babel/issues/2954
https://github.com/babel/babel/issues/3737
https://swizec.com/blog/dont-worry-its-a-compiler-bug/swizec/6764

**Comment by aradzie** [comment]
I had the same issue recently. It was because of mis-configured Babel combined with Webpack which caused application of Babel to its own sources. In my case it worked as follows:

- Webpack bundles modules from `node_packages`.
- Webpack uses the `babel-loader` plugin to transpile sources from `node_packages`.
- One of the modules in `node_packages` is a Babel file with the `_typeof` helper function.
- Webpack runs Babel on its own helper function which leads to circular import of `typeof.js` from `typeof.js` and in turn to bug.

**Comment by wolf-benjamin** [comment]
I am experiencing the same problem.
@aradzie how can I disable Babel in the `@babel/runtime package`?
Thx!

**Comment by aradzie** [comment]
@wolf-benjamin Maybe we should create a separate issue for the maintainers of Babel to take care of this problem. I mean to add something like `.babelignore` or `.babelrc.js` directly to package `@babel/runtime` to resolve this bug automatically for all Babel users.

Meanwhile I just excluded anything under the `node_modules` directory from Babel. But this is not an ideal solution because who knows what's in there. There may be external packages which may not work without Babel transpilation. In my case I depend only a handful of packages such as React that I know work well as is.

You can probably play with the [include/exclude](https://babeljs.io/docs/en/options#test) patterns to achieve the similar goal.

**Comment by soryy708** [comment]
In the repro repo https://github.com/soryy708/typeof3.default-repro of https://github.com/babel/babel/issues/11036 node_modules is `ignore`d in `babel.config.js`, but the error still happens.

**Comment by aradzie** [comment]
@soryy708 

Try something like 
```
    ignore: [
        /\/node_modules\//,
    ]
```

in your `babel.config.js` file.

**Comment by soryy708** [comment]
That glob matches only `node_modules` in the root. My repro is a monorepo where there are 2 packages, one in the root level and one inside `subrepo/`. Your glob would ignore `node_modules` in the root but not in `subrepo/`.

**Comment by nicolo-ribaudo** [comment]
Since it's a regular expression and not a glob, it should also ignore nested `node_modules`.
