### ISSUE TITLE
7.8 regression with babel-eslint & dynamic imports

### ISSUE THREAD

**Issue by jdelStrother** [babel/babel#11001]
## Bug Report

**Current Behavior**
When using babel-eslint (10.0.3) with babel >= 7.8 , dynamic imports trigger the no-unused-expression rule.

**Input Code**
```js
import("foo"); // Expected an assignment or function call and instead saw an expression  no-unused-expressions
```

```json
{
  "name": "xxx",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "babel-eslint": "^10.0.3",
    "eslint": "^6.8.0"
  },
  "resolutions": {
    "@babel/parser": "7.8.0"
  }
}
```

The same project with babel @ 7.7.4 does not trigger this error:

```
{
  "name": "xxx",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "babel-eslint": "^10.0.3",
    "eslint": "^6.8.0"
  },
  "resolutions": {
    "@babel/parser": "7.7.4"
  }
}
```

**Expected behavior/code**
Dynamic imports shouldn't be treated as unused expressions

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

None, this is reproducible with the above package.json & running this in your shell:

```sh
echo -e -n "import('foo');\n" | yarn run eslint --parser babel-eslint --stdin --no-eslintrc --rule "no-unused-expressions: 2"
```

**Environment**

```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 11.15.0 - ~/.nix-profile/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  npmPackages:
    babel-eslint: ^10.0.3 => 10.0.3
    eslint: ^6.8.0 => 6.8.0
```

**Additional context/Screenshots**
Possibly this is actually a bug in babel-eslint rather than babel?

**Comment by nicolo-ribaudo** [comment]
This is a bug in ESLint itself, it can also be reproduced without using Babel at all: https://eslint.org/demo#eyJ0ZXh0IjoiaW1wb3J0KFwiZm9vXCIpXG4wID09IDA7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9fSwicnVsZXMiOnsicmVxdWlyZS1qc2RvYyI6MiwidmFsaWQtanNkb2MiOjIsIm5vLWltcGxpY2l0LWdsb2JhbHMiOjIsIm5vLXVudXNlZC1leHByZXNzaW9ucyI6Mn0sImVudiI6e319fQ==

With Babel <7.8.0 you didn't get the warning because we generated an invalid AST for dynamic imports, so ESLint didn't see them as such.

**Comment by nicolo-ribaudo** [comment]
Oh actually I think that it's not a bug, it's a feature. `import()` returns a promise, so you have to use either `await import()` or `import().then(...)`.

**Comment by jdelStrother** [comment]
ohhhhhhhh.  Of course, sorry.  I've been looking at this way too long.
