### ISSUE TITLE
Conversion of large map using _defineProperty

### ISSUE THREAD

**Issue by ralphsol** [babel/babel#11027]
For a given js file, which contains only a large map such as below -
-----------------------‐---------f.js-----------------------‐-------------
module.exports = {"A":"1", "B":"2", "C":"3", ...}
-----------------------‐--------------------------------‐-------------------

And with preset as 'es2015', Babel keeps the file unchanged till some occurrences. But beyond a count, it replaces the latter instances of the map with _defineProperty(_module$exports, "Z", "26");
How can this threshold be adjusted?

**Comment by nicolo-ribaudo** [comment]
Can you provide a reproducible example?

**Comment by chung-leong** [comment]
I think the OP has duplicate entries in his large map. For instance, the following

```javascript
const cow = {
  a: 1,
  a: 2,
};
```
would get transcoded into this:

```javascript
var cow = _defineProperty({
  a: 1
}, "a", 2);
```

**Comment by nicolo-ribaudo** [comment]
I have no idea why it's happening; it seems like a bug :thinking:

**Comment by nicolo-ribaudo** [comment]
Oh, it's a feature!

Some browsers don't support duplicated keys in strict mode: [compat table](https://kangax.github.io/compat-table/es6/#test-miscellaneous_duplicate_property_names_in_strict_mode), check in the `miscellaneous` section.

If your duplicated properties are being transpiled, then it's because it's required by your targets. These are the first browsers versions which support duplicated properties according to compat-table:
```json
{
    "chrome": "42",
    "edge": "12",
    "firefox": "34",
    "safari": "9",
    "node": "4",
    "ios": "9",
    "samsung": "3.4",
    "opera": "29",
    "electron": "0.27"
  }
```

If you still want to disable this behavior (:warning: your code might break in old browsers included in your targets) you can pass `"exclude": ["transform-duplicate-keys"]` to `preset-env`'s options.
