### ISSUE TITLE
v7.8.0 introduces a non-backwards-compatible change

### ISSUE THREAD

**Issue by serhalp** [babel/babel#11052]
Babel design docs claim that [Babel follows semver](https://github.com/babel/babel/blob/master/doc/design/versioning.md). However, Semantic Versioning claims that non-backwards-compatible bug fixes should be released as major versions.

`v7.8.0` included this PR: https://github.com/babel/babel/pull/10887. This PR changes the behavior of the public API, namely `--ignore` combined with `--copy-files`.

`^v7.8.0` breaks all of our apps, and we have Dependabot configured to auto-merge minor/patch bumps, so this has been rather disruptive.

From reading through the history of #6226, it seems like it was pretty well established that this would be a breaking change. It seems like the idea of this even being a bug [was contentious](https://github.com/babel/babel/issues/6226#issuecomment-328660064).

Is my understanding of semver out of line? The way I see it, to maintain previous behavior when upgrading to 7.8.0, I need to add `--copy-ignored`. If I need to make a change to maintain previous behavior, that's a breaking change.

Please consider either:
1. reverting this change and including it in the v8 line instead
2. changing the default for the new `--copy-ignored` flag to `true`, to maintain previous behavior (and possibly changing the default to `false` in the v8 line)

(Note: I didn't submit this as a bug report and I didn't include repro steps because everything seems to be working as expected. The only issue is that this is a breaking change published as a minor. I can provide repro steps if necessary.)

**Comment by serhalp** [comment]
Oh, hmm, it's possible this was introduced in 7.7.7 actually, as it looks like parts of this feature were released in https://github.com/babel/babel/pull/10831 which landed in 7.7.7.

**Comment by nicolo-ribaudo** [comment]
I think that we could change the default if it's not too late.

---

Btw, I don't agree with
> Semantic Versioning claims that non-backwards-compatible bug fixes should be released as major versions.

No bugfix is backward compatible if someone is relying on the bug.

**Comment by STRML** [comment]
Additionally, the code appears to have a bug - or perhaps an intent I don't understand.

Imagine I am compiling a whole project, and I run something like `babel -out-dir build/ --copy-files --ignore '.git/,migrations/,test/' .`, to compile all the files in the project and copy them into `build/`.

With files like the packfiles in `.git`, the file will be marked as `FILE_TYPE.NON_COMPILABLE` (https://github.com/babel/babel/blob/8415065d9904f3e9619793b2ebbd3bb4bd75b937/packages/babel-cli/src/babel/dir.js#L36-L38) then be copied anyway (https://github.com/babel/babel/blob/8415065d9904f3e9619793b2ebbd3bb4bd75b937/packages/babel-cli/src/babel/dir.js#L102-L105), even if ignored & `--copy-ignored` is *not* given.

My intuition here is that the option should have been `--no-copy-ignored` from the outset so that the default behavior didn't change, and that `FILE_TYPE.IGNORED` should take precedence over `NON_COMPILABLE` when determining whether or not to copy. If the team agrees I'm happy to put together a PR.

**Comment by nicolo-ribaudo** [comment]
> FILE_TYPE.IGNORED should take precedence over NON_COMPILABLE when determining whether or not to copy.

I agree: a PR would be appreciated! I'm discussing with the team about the default value of the `copy-ignored` option.

**Comment by nicolo-ribaudo** [comment]
@existentialism @kaicataldo @hzoo Do you have any opinion about this? I'm inclined to change the default value of the option to match the old behavior, but we shouldn't wait too much.

**Comment by kaicataldo** [comment]
I think it makes sense to do a patch release with the non-breaking default value.

**Comment by existentialism** [comment]
Agree
