### ISSUE TITLE
@babel/register write cache fail in node:alpine docker container

### ISSUE THREAD

**Issue by cncolder** [babel/babel#11130]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
In `node:alpine` docker image. The folder `node_modules` create by root. And node server runs by 'node' user. So `node_modules` isn't writeable.

`cache.js` not handle `ENOENT` error. It just throw out and crash node server.

```
/home/node/app/node_modules/@babel/register/lib/cache.js:80
        throw e;
        ^

Error: ENOENT: no such file or directory, mkdir '/home/node/app/node_modules/.cache/@babel/register'
    at Object.mkdirSync (fs.js:856:3)
    at module.exports.sync (/home/node/app/node_modules/make-dir/index.js:97:6)
    at save (/home/node/app/node_modules/@babel/register/lib/cache.js:61:23)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/node/app/node_modules/.cache/@babel/register'
}
```

**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): v7.8.3
- Node/npm version: Node v13.8.0/npm 6.13.6
- OS: Alpine Linux
- Monorepo: no
- How you are using Babel: `register`

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by JLHwung** [comment]
As a workaround, you can disable the register cache via `BABEL_DISABLE_CACHE` env
```Dockerfile
ENV BABEL_DISABLE_CACHE 1
```

If `node_modules` is not writable due to permission errors, it should throw `EACCESS` instead of `ENOENT`. Babel will ignore the `EACCESS` error and produce warnings only.

Per http://man7.org/linux/man-pages/man3/errno.3.html

> ENOENT:  No such file or directory (POSIX.1-2001).
> Typically, this error results when a specified path‐name does not exist, or one of the components in the directory prefix of a pathname does not exist, or the specified pathname is a dangling symbolic link.

In your case, maybe `/home/node/app/node_modules` is a dangling symbolic link mounted by Docker. @cncolder Can you share the reproducing Dockerfile?

**Comment by cncolder** [comment]
@JLHwung @babel/register use find-cache-dir@2. It's not check folder permission.

```
// v2 return '/home/node/app/node_modules/.cache/@babel/register'
// v3 return undefined
findCacheDir({ name: "@babel/register" })
```

https://github.com/babel/babel/blob/31b05060409107caa5737f90bdf79fc3538c0a2d/packages/babel-register/src/cache.js#L9

**Comment by JLHwung** [comment]
@cncolder Babel 8 will use `find-cache-dir@3`. We can not bump `find-cache-dir` to v3 because Babel 7 requires node.js 6 support, which is dropped by `find-cache-dir@3`.

https://github.com/babel/babel/blob/1613418f9b25e56aa511a06f0b0e3c1856f05737/packages/babel-register/src/cache.js#L46
Babel register catches the `EPERM` (Windows) and `EACCES` (Unix) error. If a directory is not writable, it is expected to throw `EACCES` error, in your case the `ENOENT` error is thrown, can you share the Dockerfile or reproducing repo? It will greatly help us investigate the issue.

**Comment by cncolder** [comment]
```Dockerfile
FROM node:alpine as builder

WORKDIR /home/node/app

COPY . ./

RUN echo building... \
    && npm install \
    && npm run build \
    && echo build success


FROM node:alpine

ENV NPM_CONFIG_PREFIX=/home/node/.npm \
    PATH=$PATH:/home/node/.npm/bin \
    NODE_ENV=production \
    CHROMIUM_BIN=/usr/bin/chromium-browser

RUN echo @edge http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && \
    apk add --no-cache \
    wqy-zenhei@edge \
    chromium

WORKDIR /home/node/app

COPY --from=builder /home/node/app/dist ./dist
COPY --from=builder /home/node/app/public ./public
COPY --from=builder /home/node/app/package.json /home/node/app/package-lock.json /home/node/app/.npmrc ./

RUN echo install... \
    && npm install --production \
    && rm -rf .npmrc ~/.npm* ~/.yarn* \
    && find -type f \( -name '*.ts' -o -name '*.tsx' -o -name '*.d.ts' -o -name '*.js.map' \) -delete \
    && echo install success

CMD ["node", "dist/main"]

USER node
```

**Comment by JLHwung** [comment]
@cncolder Thanks for the reproduction Dockerfile. I can confirm this issue can be reproduced and thus I have filed one to the `make-dir` repo: https://github.com/sindresorhus/make-dir/issues/25

`make-dir` is used in `babel-register` to create cache directory. Note that this issue does not affect Babel 8, where `make-dir` has been replaced by native recursive `fs.mkdir` supported on `node>=10.12`.
