### ISSUE TITLE
[@babel/preset-env] Debug doesn't always show

### ISSUE THREAD

**Issue by ctsstc** [babel/babel#11135]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
Sometimes you get the debug output, sometimes you don't. Maybe this is related to caching? I even have the `api.cache(false)` in my `babel.config.js`

**Input Code**

Just running the cli tool or `yarn build` in this case.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

I know it shows `@vue/cli-plugin-babel/preset` but this has happened to me through the years while using the babel preset env.

```js
module.exports = api => {
  api.cache(false);
  return {
    presets: [["@vue/cli-plugin-babel/preset", { debug: true }]]
  };
};
```

**Environment**

```
  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v12.14.1/bin/npm
  npmPackages:
    babel-eslint: ^10.0.3 => 10.0.3 
    eslint: ^5.0.0 => 5.16.0 
    webpack: ^4.41.5 => 4.41.5 
```
- Babel version(s): @babel/core v7.8.4
- Monorepo: no
- How you are using Babel: cli + via vue-cli-service

**Possible Solution**

**Additional context/Screenshots**
Example of it working and then not back to back.
https://gist.github.com/ctsstc/aa350601e8db7aec50a4a10eb20acfc5

**Comment by JLHwung** [comment]
`@vue/cli-plugin-babel` uses `babel-loader` under the hood. `babel-loader` will cache the transformed result to `node_modules/.cache/babel-loader` so the second run `vue-cli-service build` does not actually trigger babel transforms. Therefore, the debug output of preset-env is not shown.

Actually due to cache you can see the second run is much faster than the first run. ( 5825ms vs 16250ms )

Closing this issue as it works as expected.
