### ISSUE TITLE
Browsers not being coerced properly when using `all`

### ISSUE THREAD

**Issue by alan-agius4** [babel/babel#11155]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
Classes are not downlevelled.

**Input Code**
```js
class Something {
  constructor() { }
}
```

**Expected behavior/code**
Input to be converted to es5, but it is not when one of the browsers version is `all`, the problem seems to be the coercion of targets to gather the minimum version of the browser. When removing `opera 66` from the targets the es6 code is converted correctly.

```js
const core_1 = require("@babel/core");
core_1.transformAsync(`
class Something {
    constructor(
    ) {
    }
  }
`, {
  inputSourceMap: false,
  babelrc: false,
  configFile: false,
  presets: [[
    require.resolve('@babel/preset-env'),
    {
      targets: [
        'op_mini all',
        'opera 66',
      ],
      modules: false,
      exclude: ['transform-typeof-symbol'],
      debug: true,
    },
  ]],
}).then(r => console.log(r.code));
```

Output
```
Using targets:
{
  "opera": "66"
}

Using modules transform: false

Using plugins:
  proposal-nullish-coalescing-operator { "opera":"66" }
  proposal-optional-chaining { "opera":"66" }
  syntax-json-strings { "opera":"66" }
  syntax-optional-catch-binding { "opera":"66" }
  syntax-async-generators { "opera":"66" }
  syntax-object-rest-spread { "opera":"66" }
  syntax-dynamic-import { "opera":"66" }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
class Something {
  constructor() {}

}
```

**Environment**

- Babel version(s): 7.8.5
- Node/npm version: Node 12
- OS: [e.g. OSX 10.13.4, Windows 10] Win 10
- Monorepo: [e.g. yes/no/Lerna] No
- How you are using Babel: API

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by JLHwung** [comment]
The `all` keyword is not a valid part in browserslist queries except in `op_mini all`. Therefore, both `chrome all`, `firefox all`, etc. are _not_ valid.

`@babel/preset-env` consumes compatibility data from `compat-table`. However `op_mini` is _not_ supported in `compat-table`. (https://github.com/kangax/compat-table/issues/1057) 

Besides that the `op_mini all` query is still vague because it does not specify an exact version or version range. Technically `op_mini all` can include the first release of Opera Mini which dates back to 2005. As is shown in caniuse: Opera Mini still [does not](https://caniuse.com/#search=es6) support many ES6 features. Given the lack of proper support data, if you really want to support `op_mini all`, please use `forceAllTransforms`:

```json
["@babel/env", {
  "forceAllTransforms": true
}]
```

Note that Babel currently ignores `op_mini all` even if it is in the browserslists defaults configuration.

**Comment by alan-agius4** [comment]
@JLHwung, thanks for your reply, indded you are right that `firefox all`, `chrome all` etc are not a valid browserslist query and `opera_mini all` is a special case and is a valid query.
