### ISSUE TITLE
Live-binding imports

### ISSUE THREAD

**Issue by joliss** [babel/babel#1117]
```js
// ------- foo.js --------
var a = 5;

function update() {
  a = 10;
}

export { a, update };
```

```js
// -------- bar.js -------
export { a, update } from './foo';
```

```js
// --------- baz.js -------
import { a, update } from './bar';

update();

console.log(a);
// This should output 10, not 5.
```

The intermediate re-export in `bar.js` makes this surprisingly tricky to fix.

Esperanto seems to have a correct implementation: In its "bundle" mode, it emits a common variable `a` across module boundaries, and in AMD/CJS mode, it uses `defineProperty` trickery in the `bar.js` output.

Possibly related: #1032.

**Comment by sebmck** [comment]
Whoops, forgot to update this issue. Live bindings were implemented in 25312396a581e74595d4c2782c6ce29861e350a2 but they didn't have default live bindings because I ran into issues with getting a proper reference while also having the CommonJS interop. As of b7a08100a634af41ce7258f867fe37551b94a32c default live bindings are now supported via some trickery.
