### ISSUE TITLE
Transpilation fails when chaining off optionally chained keys that share names with certain reserved keywords (e.g. class and function)

### ISSUE THREAD

**Issue by Vages** [babel/babel#11197]
## Bug Report

- [x] I would like to work on a fix!

**Current Behavior**

I have a statement that goes something like the following: `const a = foo?.class.bar`. This does not transpile, and I'm quite sure I've found the reason why: Because I'm trying to chain `bar` off the optionally chained `class`. 

I've been playing around in the REPL using only `@babel/plugin-proposal-optional-chaining v7.6.0` plugin:
https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhjAvDAZiEB-AdMANnCCLAIzgCcg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.8.6&externalPlugins=%40babel%2Fplugin-proposal-optional-chaining%407.6.0

The following expressions do *not* work in babel (but works fine in the Chrome console, v80):
```javascript
foo?.class.baz
foo?.function.baz
foo?.bar?.class.bar
foo?.function?.baz
```

The following expressions *do* work:
```javascript
foo?.bar.class.bar
foo?.class
foo?.['function'].bar
foo?.['class'].bar
foo.class.bar
foo?.let.bar
foo?.const.bar
foo?.var.bar
```

*From this, I've formed the following hypothesis*: 
- Using the reserved keywords `class` or `function` directly after an optional chaining operator, followed by a regular or optional chain leads to babel being unable to transpile the expression, e.g. `foo?.class.baz`. 
- The effect disappears when using bracket notation around `function` or `class`, e.g. `foo?.['class'].bar`. 
- Using other keywords (e.g. `var`, `let` and `const`) or just not chaining off the `class` or `function` expression also leads to the effect disappearing, e.g. `foo?.let.bar` and `foo.class.bar`. 
- And if there's no optional chaining operator in the first place, it also works fine, e.g. `foo.class.bar`

**Expected behavior/code**
I expect the code to transpile and to behave as if using non-reserved keywords, i.e. the way the non-transpiled code behaves in Chrome

**Comment by nicolo-ribaudo** [comment]
Thanks for the bug report!

This is a parser bug, coming from the `nextToken` function of the tokenizer.

https://github.com/babel/babel/blob/8f281f578db68ef2092ce35b8db003bdb346a9e4/packages/babel-parser/src/tokenizer/index.js#L223-L242

As you can see, in line 225 we handle the case where `curContext` is `undefined`, but we don't do it at line 236 when checking if `curContext.override` is defined. Since `curContext` might be `undefined`, this seems like a perfect use case for optional chaining. :wink: 

Would you like to open a PR?

---



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test at `packages/babel-parser/test/fixtures/es2020/optional-chaining` (only `input.js`; `output.json` will be automatically generated)
1. Update the code!
1. `yarn jest babel-parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.json` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-parser` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by Vages** [comment]
I'll give it a try, @nicolo-ribaudo 😄

**Comment by Vages** [comment]
Here you are, @nicolo-ribaudo 😊
