### ISSUE TITLE
[parser] Async arrow cannot be rhs of binary operator

### ISSUE THREAD

**Issue by JLHwung** [babel/babel#11203]
## Bug Report

Copied from https://github.com/acornjs/acorn/issues/914

```js
4 + async() => 2
```

[REPL](https://babeljs.io/repl#?browsers=node%206&build=&builtIns=false&spec=false&loose=false&code_lz=CwAg1CCGDOCeB2BjAFAShAXgHwgExA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env%2Cenv&prettier=true&targets=Node-13&version=7.8.6&externalPlugins=)

**Comment by vedantroy** [comment]
I'll try this.

**Comment by vedantroy** [comment]
A possible fix is to modify `parseExprOp` inside "expression.js":

```
// example code
 const oldStart = this.state.start
 node.right = this.parseExprOpRightExpr(op, prec, noIn);
 if (op !== tt.pipeline // pipeline operator is a binary operator that allows functions on rhs
     && node.right.type === "ArrowFunctionExpression"
     && !node.right.extra?.parenthesized) { // "4 + (async () => 3)" is allowed
    this.raise(oldStart, "async arrow function cannot be argument for binary operator")
}
```
A benefit is that the error message will be specific/useful.  
A disadvantage is that the error message will be different for async arrow functions vs non async arrow functions. For non async arrow functions, the error message will be a syntax error and for async arrow functions it will be a parse error (I think).

The root cause of the issue is inside `parseExprAtom`, which is called by `parseExprSubscripts`. The `switch` statement matches to `case tt.name:` and returns an Identifier node with name "async" (skipping all the if stmts inside the case). Then, `parseExprSubscripts` will reach `return this.parseSubscripts(expr, startPos, startLoc);`, which parses the rest of the expression and returns an `ArrowFunctionExpression`.

Should I go ahead and submit a PR (after polishing up the code) with the fix I proposed at the top of this comment? It feels a bit hacky, but I haven't thought of anything better at the moment.
