### ISSUE TITLE
@babel/plugin-transform-parameters@7.8.7 throws `Cannot read property 'type' of null`

### ISSUE THREAD

**Issue by gera2ld** [babel/babel#11210]
## Bug Report

- [x] I would like to work on a fix!

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**
- REPL or Repo link if applicable:

```js
const babel = require('@babel/core');

console.log(babel.transform(`
class A {
  a = b => {
    ({ b } = {});
  };
}
`, {
  babelrc: false,
  presets: [
    '@babel/preset-env',
  ],
  plugins: [
    '@babel/plugin-proposal-class-properties',
  ],
}).code);
```

**Expected behavior/code**
The code should be compiled to:

```js
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

var A = function A() {
  _classCallCheck(this, A);

  _defineProperty(this, "a", function (b) {
    var _ref = {};
    b = _ref.b;
  });
};
```

While `@babel/plugin-transform-parameters@7.8.4` worked as expected, `v7.8.7` throws the following error:

```
TypeError: unknown: Cannot read property 'type' of null
    at convertFunctionParams (/path/to/node_modules/@babel/plugin-transform-parameters/lib/params.js:88:24)
    ...
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
No babelrc since I passed `babelrc: false` to make it simple.

**Environment**

```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 13.10.1 - /path/to/node_modules/.bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /path/to/node_modules/.bin/npm
  npmPackages:
    @babel/runtime: ^7.1.5 => 7.8.4
    babel-plugin-macros: ^2.8.0 => 2.8.0
    eslint: ^6.8.0 => 6.8.0
```
- Babel version(s): all latest, @babel/core@7.8.7
- Node/npm version: Node 13/npm 6
- Monorepo: no
- How you are using Babel: directly use `@babel/core` in the minimum reproduction

**Possible Solution**

I did some debugging and found that **the argument of a function as a class property is added to `constantViolations`**, but I'm not sure if this is expected.

**Additional context/Screenshots**
None

**Comment by nicolo-ribaudo** [comment]
This has probably been introduced by 9015fda3c106abda6928cf348797a38f09d4b3e0
---



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest plugin-transform-parameters` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest plugin-transform-parameters` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by JLHwung** [comment]
The minimum config to reproduce this issue is (`@babel/` is removed because it works for `options.json` in our test fixtures).
```json
{
  "plugins": ["proposal-class-properties", "transform-destructuring", "transform-parameters"]
}
```

This issue is tricky! It is an integration issue among three plugins. That is, any two of them can not trigger this error.

> This has probably been introduced by 9015fda

What's happening in 9015fda is that we access `constantViolations` from the binding info to determine if we should wrap the function body inside an iife. In this cases the `constantViolations[0].node` is `null`. That means this information is corrupted.

We start from digging what happens when only `"transform-destructuring", "transform-parameters"` is enabled. (Use "syntax-class-properties" to make parser happy)

=> Scope initializing
All good, the `constantViolations` of the parameter `b` points to `AssignmentExpression` (`({ b } = {});`)

=> transform parameters (Function)
All good.
  
=> transform destructuring (AssignmentExpression)
The expression is replaced by a var declaration and a series of assignments, i.e.
```js
var ref = {};
b = ref.b;
```

https://github.com/babel/babel/blob/1e7ab24bb386f21466dc8c34722cb8c7772d773c/packages/babel-plugin-transform-destructuring/src/index.js#L601

The `AssignmentExpression` is referred by `constantViolations` of the `b` param binding. After it is replaced, the scope info is not updated to the replaced `b = ref.b` assignment. This is where things begin to go wrong. However without `proposal-class-properties`, we are still good because `"transform-parameters"` is _not_ revisited.

So here is why `proposal-class-properties` finally trigger this issue: It will inject the class property initializer into the constructor body
https://github.com/babel/babel/blob/1e7ab24bb386f21466dc8c34722cb8c7772d773c/packages/babel-helper-create-class-features-plugin/src/misc.js#L79

so after destructuring is transformed leaving with incorrect binding infos. The "transform-parameters" are reapplied again because there is a new `Function` node inside the class constructors, i.e.
```js
constructor() {
  this.a = (b) => { ... }
}
```
and because the `constantViolations` points to the assignment _before_ replaced, the error is thrown.

To mitigate this, we can crawl the scope, update the binding infos after the AssignmentExpression is replaced.
```js
path.replaceWithMultiple(nodes);
path.scope.crawl();
```
because the change happens inside `transform-destructuring`, let's add a test case in `transform-destructuring`.

**Comment by gera2ld** [comment]
Thanks for the clear explanation.
So this issue is actually caused by `transform-destructuring`, I've moved the test case to `transform-destructuring` since there isn't another fix yet.
