### ISSUE TITLE
Error: No matching version found for @babel/types@^7.8.7

### ISSUE THREAD

**Issue by Saurabhdataman** [babel/babel#11211]
## No matching version found for @babel/types@^7.8.7

npm install @babel/generator
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.8.7
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/generator'
npm ERR! notarget

**Comment by mickaeldanslenowhere** [comment]
Hi, I have the same issue, seems like that the publish hasn't been going well... ;)

**Comment by nicolo-ribaudo** [comment]
The version is correctly published on npm: https://www.npmjs.com/package/@babel/types

If you are behind a proxy (maybe for work) it's probably its cache that isn't updated.
Otherwise, please report this bug to npm (https://github.com/npm/cli/issues/new/choose) because once there is nothing we can do about it.

**Comment by Thenis** [comment]
Have the same error. Cleaning the cache didn't work

**Comment by nicolo-ribaudo** [comment]
Please report it to npm.

**Comment by munjakarnakar** [comment]
Getting the same error even after **npm cache clean --force**.

**Comment by nicolo-ribaudo** [comment]
That clears your local cache, but it's likely a problem with a server/proxy between you and npm.
