### ISSUE TITLE
Babel core not importable with Node.js native ESM support

### ISSUE THREAD

**Issue by kriskowal** [babel/babel#11247]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**

Babel version 7.8.7

`import * as babelCore from '@babel/core'` from an ESM in Node.js’s experimental support for ESMs produces an object with a `transformSync` accessor but the accessor returns `undefined`. This occurs when the containing package.json has `"type": "module"` set or when the file has the `.mjs` extension. The same module works fine when executed with `node -r esm`: `babelCore.transformSync` is a function. The same also works fine when required with CommonJS conventions.

Unexpected behavior for Node.js ESM support when file has `.mjs` extension:

```js
// node test.mjs
import * as babelCore from "@babel/core";
console.log(babelCore.transformSync);
// (node:25847) ExperimentalWarning: The ESM module loader is experimental.
// undefined
```

Expected behavior: log a defined function object.

```js
// [Function: spec]
```

Unexpected behavior for Node.js ESM support when file has a `.js` extension and module type in package.json:

```js
// package.json
{
  "type": "module"
}
// node test.js
import * as babelCore from "@babel/core";
console.log(babelCore.transformSync);
// (node:25847) ExperimentalWarning: The ESM module loader is experimental.
// undefined
```

As expected, the .mjs extension or module type in package.json are required to use native import.

```js
// node test.js
import * as babelCore from "@babel/core";
console.log(babelCore.transformSync);
// (node:25839) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
// /Users/kris/ses/temp2.js:1
// import * as babelCore from "@babel/core";
// ^^^^^^
```

As expected, `node -r esm` does access a defined function.

```js
// node -r esm test.js
import * as babelCore from "@babel/core";
console.log(babelCore.transformSync);
// [Function: sync]
```

As expected, `node` works fine when importing as CommonJS.

```js
// node test.js
const babelCore = require("@babel/core");
console.log(babelCore.transformSync);
// [Function: sync]
```

It is possible that this behavior is due to aberrant behavior of Node.js’s ESM implementation. It is likely that this is a symptom of an underlying problem.

**Comment by kriskowal** [comment]
@erights recommended that I call upon @jdalton or @bmeck for help with this issue. Time permitting, I’ll attempt to isolate this further. I’m not familiar enough with ESM or Babel at this point to tell whether this is an issue that lies more squarely with Babel or Node.

**Comment by bmeck** [comment]
This is a known issue per how CJS files are only able to generate `default` exports in order to conform to the ECMAScript specification and binding behavior of ESM. Babel ships a CJS build to package managers and is why this behavior exists. [`esm`](https://www.npmjs.com/package/esm) contains a variety of conveniences that hook into a variety of transpilation patterns such as the `_esModule:true` behavior of not creating synthetic module namespaces and otherwise picking properties to form namespaces otherwise.

**Comment by kriskowal** [comment]
@bmeck, I read your statement as “This is not a Node.js bug. Using Babel as it is written today depends on crutches of ESM that will vanish soon. Babel will need to change to accommodate Node.js.” Is this correct? Can you propose a rule that Babel would need to follow to straddle CJS and ESM, like “Avoid default exports.”?

**Comment by bmeck** [comment]
@kriskowal I wouldn't phrase it as such since I don't actually think this is a bug but an integration problem by the nature of the transpilation; note that babel file in question is CJS and CJS does not export named bindings in Node. I wouldn't state that importing CJS is broken on Node's side, nor would I state that babel creating CJS from ESM input is broken. They just don't mix / no solutions have been able to be found. There are *lots* of issues exactly about this topic, from things on [Node trackers](https://github.com/nodejs/modules/issues/480), at [TC39](/tc39/proposal-dynamic-modules), and many more. In general mixing the transpiled ecosystem and spec ESM simply doesn't work as it stands. So, once you cross the transpilation barrier things must adhere to their compilation target expectations (in the case of `@babel/core` that is CJS). I think babel could output ESM instead of CJS like rollup does, but even then more integration issues likely remain.

**Comment by nicolo-ribaudo** [comment]
We might decide to change this in Babel 8, but in the meantime use `import babelCore from "@babel/core"`.

**Comment by kriskowal** [comment]
@nicolo-ribaudo Thank you! That is a fine work-around. Feel free to close if you do not require this task to track.

**Comment by nicolo-ribaudo** [comment]
I'll defer the decision to @JLHwung, since he recently started investigating Node.js's new `export` maps which are related to this.

**Comment by JLHwung** [comment]
I agree on what Bradley has said before: `@babel/core` is shipped in commonjs, if you are looking at the [entry file](https://unpkg.com/browse/@babel/core@7.8.7/lib/index.js), it is like
```js
exports.transformSync = require("./transform").transformSync
```
The ESM named import `import { transformSync } from "@babel/core"` is never expected to work with commonjs `exports.transformSync`.

The `esm` will transform the commonjs exports to analogous esm exports so `node -r esm` works in your case.

We are likely to ship dual cjs/esm builds of babel on Babel 9, which is expected in next year. So in the future it should be valid to do

```js
import * as babelCore from "@babel/core" // the esm entry is imported
```

At this moment the Node.js ES Module API is still experimental and Babel 8 is on the horizon, it is risky to ship esm builds for Babel 8. Before that please use

```js
import babelCore from "@babel/core"
```
since `@babel/core`, although written in ESM, is actually shipped in commonjs format.

I am gonna close that because the current situation is expected.
