### ISSUE TITLE
@babel/core: Upgrade json5 to 2.1.2

### ISSUE THREAD

**Issue by silkfire** [babel/babel#11274]
In `@babel/core` 7.8.7, the current version of `json5` (2.1.1) depends on a version of `minimist` that contains the security vulnerability CVE-2020-7598. Can we update `json5` to 2.1.2 to resolve this?

**Comment by JLHwung** [comment]
Thanks for the report. PR is welcome!

**Comment by nicolo-ribaudo** [comment]
Note that `@babel/core` depends on `^2.1.0`, so you can get the patched `minimist` version even without a Babel upgrade.

**Comment by fernandocanizo** [comment]
How do you do that @nicolo-ribaudo ? I tried `npm audit fix` and it told me manual intervention is required. Didn't fixed it

**Comment by adamu** [comment]
`@babel/cli` has the same `minimist` problem. Output of `npm audit`:

> @babel/cli > chokidar > fsevents > node-pre-gyp > mkdirp > minimist

**Comment by JLHwung** [comment]
> @babel/cli > chokidar > fsevents > node-pre-gyp > mkdirp > minimist

Please update `mkdirp` to version 0.5.3. As it is a deeply nested dependency, Babel can not do much unless every package has a new patch release for its upstream.

**Comment by adamu** [comment]
Unfortunately it seems that `node-pre-gyp` has it pinned to 0.5.1, so I don't think it's possible.
`rc` also has it pinned to `1.2.0`:

> @babel/cli > chokidar > fsevents > node-pre-gyp > rc > minimist

**Comment by silkfire** [comment]
@nicolo-ribaudo Why was this issue closed?

![image](https://user-images.githubusercontent.com/1554615/76947835-7d3b9b00-6906-11ea-8bf8-cca71e110fd6.png)

**Comment by nicolo-ribaudo** [comment]
Bacause we just merged the fix.

It will be released on Friday.

**Comment by nicolo-ribaudo** [comment]
@adamu

> @babel/cli > chokidar > fsevents > node-pre-gyp > rc > minimist

There is a problem here: we can't upgrade to `chokidar` v3 in Babel 7 because it contains breaking changes that would be reflected to our users.

- `@babel/cli` has an _optional_ dependency on `chokidar@^2.1.8`.
- `chokidar@2.1.8` has an _optional_ dependency on `fsevents@^1.2.7`
- `fsevents@1.2.11` bundles all its dependencies, including `minimist@0.0.8`

There are a few solutions:
1. With `yarn`, you could try to force a `chokidar@3` upgrade using the `resolutions` field in `package.json`. Maybe the breaking change doesn't affect you.
2. With `npm`, you can try using [`npm-force-resolutions`](https://github.com/rogeriochaves/npm-force-resolutions) to force a `chokidar@3` upgrade. `npm audit` will still complain, but you won't actually have the unsecure code.
3. You can use `npm --no-optional` to avoid installing `chokidar@2` (you might first have to delete your `package-json.lock`)
4. You can ask to the `fsevents` maintainers to release a `fsevents@1.2.12` version, which would be automatically picked up by `chokidar@2`. Even if the last version is `2.1.2`, it looks like the v1 release line is [still maintained](https://github.com/fsevents/fsevents/releases).

**Comment by paulmillr** [comment]
pushed fsevents 1.2.11

**Comment by nicolo-ribaudo** [comment]
Thanks!

**Comment by JLHwung** [comment]
Closing this as it has been fixed in `@babel/core@7.9.0`.
