### ISSUE TITLE
[transform-parameter] Incorrect IIFE when shadowed variable initialized from parameters

### ISSUE THREAD

**Issue by huanzhiyazi** [babel/babel#11303]
- **First, check a function like this:**

```js
const dateSample = (date, defValue = 0) => {
  var date = new Date(date, defValue);
  return date;
}
```

- **And then transfer it with Babel 7:**

```js
var dateSample = function dateSample(date) {
  var defValue = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 0;
  return function () {
    var date = new Date(date, defValue);
    return date;
  }();
};
```

The input param `date` is discarded for function scope chain.

- **But if you transfer the original code with Babel 6, the output code is:**

```js
var dateSample = function dateSample(date) {
    var defValue = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 0;

    var date = new Date(date, defValue);
    return date;
};
```

Yeah! You can run it perfectly.

I am not sure if it is a bug! But I think the original code is not a good coding habit, which should be processed as an error to warn the developers.

**Comment by JLHwung** [comment]
The Babel 7 behaviour is expected. I would not consider it a bug yet it is indeed sub-optimal.

> The input param date is discarded for function scope chain.

When there is a variable declaration shadowing the function parameter binding, (i.e. `var date` inside `date`-param function), we will wrap the function body inside an [IIFE](https://en.wikipedia.org/wiki/Immediately_invoked_function_expression) so that the scope of the `var`-binding is _always_ up to its function body. That means it should not interfere with the desugared parameter initializer. For example (taken from `packages/babel-plugin-transform-parameters/test/fixtures/parameters/var-same-as-param-closure/exec.js`)

```js
var x = 1
function foo(x, y = function () { x = 2 }) {
  var x = 3
  y()
  expect(x).toBe(3);
}
foo()
expect(x).toBe(1);

```
If we do not wrap `var x = 3; y()` into an IIFE, `x` will be changed to `2` by default `y` implementation.

> I think the original code is not a good coding habit, which should be processed as an error to warn the developers.

True. But babel placed correctness over legibility. The babel processed code is not supposed to be of good readability.

Note that in your case, the IIFE _is_ redundant, and we could definitely improve it a bit using the following heuristics:

Do not wrap function body as IIFE if
1) the parameters contain either Assignment Pattern or Identifier
2) at least one of parameters is Assignment Pattern
3) The initializer of the assignment pattern is a literal (does not refer to any other params)

PR is welcome.

P.S. I assume you intend to use the term "transform" instead of "transfer".

**Comment by huanzhiyazi** [comment]
@JLHwung Thx! Your explanation is very helpful! 

> But babel placed correctness over legibility. The babel processed code is not supposed to be of good readability.

I cannot agree with it any more. Maybe in many cases we should remember this rule `more let or const, less var`. If we  always avoid 'var' in this case, the code would never be accepted at the time of grammar checking, and the error can be discovered in advance.

>  I assume you intend to use the term "transform" instead of "transfer"

That's right! Thx again for pointing it out!  Please feel free to give me more useful advice, my pleasure!!

**Comment by JLHwung** [comment]
@huanzhiyazi Thanks for your [post](https://github.com/huanzhiyazi/articles/issues/9), it is indeed a detailed bug report!

Here is a minimum reproduction on [REPL](https://babeljs.io/repl#?browsers=chrome%2042&build=&builtIns=false&spec=false&loose=false&code_lz=BTCGAIF5wFgRgJRQHzgN4ChzgG6gE7gTQQDU4cA3FuPgKYAuArvgHZHUC-CwCQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=true&targets=&version=7.9.0&externalPlugins=)

```js
((a = 41) => {
  var a = a + 1;
  return a;
})()
// should return 42
```

However after transformed it returns `NaN`, which is incorrect.

This issue was introduced at #11158 .

**Comment by huanzhiyazi** [comment]
@JLHwung Wow!! A clearer [example](https://github.com/babel/babel/issues/11303#issuecomment-602059715)

**Comment by huanzhiyazi** [comment]
@JLHwung Wow! A clearer example:

```js
((a = 41) => {
  var a = a + 1;
  return a;
})()
// should return 42
```
