### ISSUE TITLE
SyntaxError: unknown: Binding 'arguments' in strict mode (2:6)

### ISSUE THREAD

**Issue by RichardHoOoOo** [babel/babel#11385]
Hi I follow the instructions in this [doc](https://babeljs.io/docs/en/babel-plugin-transform-arrow-functions) to transform arrow functions. 

I find an error `SyntaxError: unknown: Binding 'arguments' in strict mode (2:5)` is thrown every time when a variable is named "arguments". For example,
```
var foo = () => {
 var arguments = 1;
};
```

The instruction I use is `require('@babel/core').transform(code, {plugins: ['@babel/plugin-transform-arrow-functions']})` where `code` is the input program like the above example.

So how can I fix it? Is there any options I miss to set?

**Comment by nicolo-ribaudo** [comment]
You can pass `sourceType: "script"` as an option to Babel. The default value is `"module"`, and that code is not valid inside modules.

**Comment by nicolo-ribaudo** [comment]
The second one is a bug!

**Comment by nicolo-ribaudo** [comment]
@RichardHoOoOo If you are interested in fixing this issue you are welcome to help, otherwise it's open for anyone who wants to work on it!

---

The problem is in the utility we have to convert arrow functions to ES5 function expressions. In the [`hoistFunctionEnvironment`](https://github.com/babel/babel/blob/70cc111b357a09034a59f106c798727ae9ed1ca2/packages/babel-traverse/src/path/conversion.js#L161) function, we "extract" `this`, `arguments`, `super` and `new.target` to the outer scope, to preserve the correct semantics in cases like this one:

```js
function f() {
  var g = () => console.log(arguments);
  g();
}

f(1, 2, 3); // should log 1, 2, 3
```

However, when there is a `var arguments;` declaration, `arguments` shouldn't refer to the outer function's `arguments` anymore. [When replacing `arguments`](https://github.com/babel/babel/blob/70cc111b357a09034a59f106c798727ae9ed1ca2/packages/babel-traverse/src/path/conversion.js#L225-L230), we need to check if it was defined as a variable in the local scope using `argumentsChild.scope.hasOwnBinding("arguments")`.

Note that we also need to check `argumentsChild.scope.parent`, `argumentsChild.scope.parent.parent` and so on: we should stop when we reach a non-arrow function scope, which defines the implicit `arguments` binding.

A few test cases:
```js
var foo = () => {
  var arguments = 1;
  return arguments;
};
```

```js
function fn() {
  var arguments = 1;
  var foo = () => {
    return arguments;
  };
}
```

```js
var arguments = 1;
function fn() {
  var foo = () => {
    return arguments;
  };
}
```

---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest plugin-transform-arrow-functions` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest plugin-transform-arrow-functions` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by nicolo-ribaudo** [comment]
@RichardHoOoOo Are you still working on this?

---

@Yokubjon-J If Richard doesn't respond in 3-4 days and if you are interested, you can take this issue. Otherwise we'll need to find another one!

**Comment by Yokubjon-J** [comment]
@nicolo-ribaudo Hello! Sorry for late reply! OK I will take on the issue!

**Comment by Yokubjon-J** [comment]
I have started working on the issue!

**Comment by Yokubjon-J** [comment]
I am having a problem with babel setup on Windows: I navigated to babel repo and ran `make watch`  (I didn't run make bootstrap because I have already run it some days ago) and I get the error:
![Capture](https://user-images.githubusercontent.com/67240021/86507608-05c94300-bdf3-11ea-945d-4925ab6fdc80.PNG)

**Comment by Yokubjon-J** [comment]
> @RichardHoOoOo If you are interested in fixing this issue you are welcome to help, otherwise it's open for anyone who wants to work on it!
> 
> The problem is in the utility we have to convert arrow functions to ES5 function expressions. In the [`hoistFunctionEnvironment`](https://github.com/babel/babel/blob/70cc111b357a09034a59f106c798727ae9ed1ca2/packages/babel-traverse/src/path/conversion.js#L161) function, we "extract" `this`, `arguments`, `super` and `new.target` to the outer scope, to preserve the correct semantics in cases like this one:
> 
> ```js
> function f() {
>   var g = () => console.log(arguments);
>   g();
> }
> 
> f(1, 2, 3); // should log 1, 2, 3
> ```
> 
> However, when there is a `var arguments;` declaration, `arguments` shouldn't refer to the outer function's `arguments` anymore. [When replacing `arguments`](https://github.com/babel/babel/blob/70cc111b357a09034a59f106c798727ae9ed1ca2/packages/babel-traverse/src/path/conversion.js#L225-L230), we need to check if it was defined as a variable in the local scope using `argumentsChild.scope.hasOwnBinding("arguments")`.
> 
> Note that we also need to check `argumentsChild.scope.parent`, `argumentsChild.scope.parent.parent` and so on: we should stop when we reach a non-arrow function scope, which defines the implicit `arguments` binding.
> 
> A few test cases:
> 
> ```js
> var foo = () => {
>   var arguments = 1;
>   return arguments;
> };
> ```
> 
> ```js
> var foo = () => {
>   var arguments = 1;
>   return () => arguments;
> };
> ```
> 
> ```js
> function fn() {
>   var arguments = 1;
>   var foo = () => {
>     return arguments;
>   };
> }
> ```
> 
> ```js
> var arguments = 1;
> function fn() {
>   var foo = () => {
>     return arguments;
>   };
> }
> ```
> 
> If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
> 
> 1. **Write a comment there** to let other possible contributors know that you are working on this bug.
> 2. Fork the repo
> 3. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
> 4. Run `yarn && make bootstrap`
> 5. Wait ⏳
> 6. Run `make watch` (or `make build` whenever you change a file)
> 7. Add a test (only `input.js`; `output.js` will be automatically generated)
> 8. Update the code!
> 9. `yarn jest plugin-transform-arrow-functions` to run the tests
>    
>    * If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
>    * If you prefer, you can run `OVERWRITE=true yarn jest plugin-transform-arrow-functions` and they will be automatically updated.
> 10. If it is working, run `make test` to run all the tests
> 11. Run `git push` and open a PR!

When I am at the 6th step, after running `make watch` I am getting stuck at: 
```
[19:42:42] Finished 'build-no-bundle' after 12 s
[19:42:42] Starting 'watch'...
make: *** [Makefile:85: watch] Error 1
```
Up till this part, many files will have been compiled (it generates a really long list of those files), everything seem works perfectly, but at `[19:42:42] Starting 'watch'...` it takes an indefinite amount of time and I will have had to stop it, then that error is generated. What is your suggestion for me to proceed? Can I overlook this problem and continue?

**Comment by nicolo-ribaudo** [comment]
Could you try running `make build-no-bundle` and then `yarn gulp watch` instead of `make watch`?

**Comment by nicolo-ribaudo** [comment]
That's expected (I should have been clearer): `make watch` never ends. If you modify a file and save it, you'll notice that the `make watch` command that is running will produce new output showing that it re-compiled the updated file.

**Comment by Yokubjon-J** [comment]
> Could you try running `make build-no-bundle` and then `yarn gulp watch` instead of `make watch`?

`make build-no-bundle` worked fine but I am getting (again) stuck after running `yarn gulp watch`, the last 3 lines after which I am stuck are:
```
[20:54:42] Compiling 'packages\babel-types\src\validators\generated\index.js'...
[20:54:45] Finished 'build-no-bundle' after 12 s
[20:54:45] Starting 'watch'...
```
Here I have stopped the process manually but it didn't give `make: *** [Makefile:85: watch] Error 1` error as before.

**Comment by nicolo-ribaudo** [comment]
It's expected that it doesn't stop: it's waiting for you to change some files. I suggest leaving it in the background and opening a new terminal.

**Comment by snitin315** [comment]
Can I work on this issue?

**Comment by JLHwung** [comment]
@snitin315 Sure. It's yours.

**Comment by snitin315** [comment]
Thanks. Work in progress. I will sen a PR soon.

**Comment by taejs** [comment]
I wonder if there's any progress on this issue. Can I take it?

**Comment by nicolo-ribaudo** [comment]
@taejs There is already a PR for this (#12344), but I can look for another "good first issue" for you.
