### ISSUE TITLE
Automatically annotate `React.forwardRef` as PURE

### ISSUE THREAD

**Issue by devongovett** [babel/babel#11399]
## Feature Request

- [x] I would like to work on this feature!

**Is your feature request related to a problem? Please describe.**

When building an app with React, `React.forwardRef` calls prevent tree shaking unused components. This can be fixed by adding a `/*#PURE*/` annotation so terser knows it's safe to remove. I think `@babel/preset-react` could do this automatically.

**Describe the solution you'd like**

Either `@babel/plugin-transform-react-jsx` or a separate plugin could add `/*#PURE*/` comments when `forwardRef` calls are seen.

**Describe alternatives you've considered**

A separate plugin outside the babel monorepo. But then it would be up to individual apps to adopt that plugin rather than getting this for free just by upgrading babel.

**Teachability, Documentation, Adoption, Migration Strategy**

Would happen automagically. 😉

**Comment by nicolo-ribaudo** [comment]
Currently, we only handle `React.createElement` because we do mark it when transpiling JSX elements (if you manually write `React.createElement`, it won't be marked as pure).

Looking at React's source, it seems that there are many pure functions:
- `createElement`
- `cloneElement`
- `forwardRef`
- `createRef`
- `memo`
- ... and basically everything except for hooks.

Maybe it would make sense to have a new plugin, included in the preset, to annotate all of those?
