### ISSUE TITLE
Computed Properties + Object Rest Spread Crashes Babel

### ISSUE THREAD

**Issue by iammerrick** [babel/babel#11416]
## Bug Report

**Current Behavior**
Babel crashes when using a computed property with object spread.

**Input Code**
- REPL or Repo link if applicable: [REPL](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBKC2AHArlApgExgXhgcgAsBLPAbgChRJYMAnIsAaxhxgG8YwBDeNALnwYiaWKEZo8MAL4VK4aDAJoANspCs25FiwDaCFOgwBdAXgBKASQAKeADRbtiNLQjhTAWWf1gjOw5YAdEF0DIwOUkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.9.0&externalPlugins=)

```js
const computed = 'hi';
const drink  = { name: 'diet coke' };

const hello = {
    [computed]: 'RIP',
    person: 'Merrick',
    ...drink
}
```

**Expected behavior/code**
I expect Babel to happily skip over this code.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Using stock REPL configuration.

**Additional context/Screenshots**
/repl.js: Property arguments[1] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got undefined

**Comment by JLHwung** [comment]
The REPL errors because only es2015 preset is enabled while the object spread is ES2018. I can not reproduce this error after `@babel/plugin-proposal-object-rest-spread` is added. [REPL](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBKC2AHArlApgExgXhgcgAsBLPAbgChRJYMAnIsAaxhxgG8YwBDeNALnwYiaWKEZo8MAL4VK4aDAJoANspCs25FiwDaCFOgwBdAXgBKASQAKeADRbtiNLQjhTAWWf1gjOw5YAdEF0DIwOUkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.9.0&externalPlugins=%40babel%2Fplugin-proposal-object-rest-spread%407.9.5).

If your target to browsers which does not have es2015 support, it is highly likely that they does not support ES2018 either. So you have to add `@babel/plugin-proposal-object-rest-spread`. (Or even better just use `@babel/preset-env`)

> I expect Babel to happily skip over this code.

Can you share your use case on applying es2015 transforms but leave ES2018 untranspiled?

**Comment by iammerrick** [comment]
@JLHwung Thanks for the insight on why this is happening! That is also the case for our builds currently.

> Can you share your use case on applying es2015 transforms but leave ES2018 untranspiled?

Great question! We have builds, all with shared code. The various builds have different runtime requirements. Generally, we aim for the lowest common denominator because we want the code that is run in our design tool (we are a website builder) to mirror the code that is going to be deployed (IE11). However, the Designer itself is able to run on more modern browsers! So in this special case, we noticed `objectSpread` helper causing some performance issues. (Death by a thousand paper cuts, switching from spread to assign saved us almost a full second in scripting on application load!) 

This gave us an incentive to basically say "hey let's keep the code as similar as possible but in this one case let's adopt 2018 because the performance benefits outweigh the costs. 

Long term our plan is to go full preset-env (and trust babel on the code shipped by our users being different than what they experience in the Design tool) but we've got to implement some functionality to let users know their browsers are not supported or what have you.

For now, we will just use `loose: true` on the proposal since babel's extends helper uses assign and is much faster than `objectSpread` helper and it contains that IE11 fallback. :-)

Thanks for the reply @JLHwung !
