### ISSUE TITLE
Better parser error when using jsx

### ISSUE THREAD

**Issue by hzoo** [babel/babel#11499]
Was checking https://github.com/babel/babel/pull/11478 and testing out syntax and noticed we don't error with the normal "use this plugin/preset" like we do for proposals with JSX itself. @nicolo-ribaudo mentioned it's probably since jsx is implemented as a normal [plugin](https://github.com/babel/babel/tree/master/packages/babel-parser/src/plugins) so we didn't have `this.expectPlugin("recordAndTuple");`

```sh
unknown: Unterminated regular expression (1:5)

> 1 | <a></a>
    |      ^
```

```sh
unknown: Support for the experimental syntax 'pipelineOperator' isn't currently enabled (1:3):

> 1 | a |> b
    |   ^

Add @babel/plugin-proposal-pipeline-operator (https://git.io/vb4SU) to the 'plugins' section of your Babel config to enable transformation.
```

**Comment by nicolo-ribaudo** [comment]
This bug needs different steps in order to be fixed, but they can be done in the same PR.

1. First, we should make `@babel/parser` throw a developer-friendly error.
   Consider these examples:
   ```js
   require("@babel/parser").parse("<div></div>", {});
   require("@babel/parser").parse("a |> b", {});
   ```
    The first one throws `SyntaxError: Unexpected token (1:0)`, while the second one throws a more actionable `SyntaxError: This experimental syntax requires enabling the parser plugin: 'pipelineOperator' (1:2)`.
    Why this difference? If you search for the `"pipelineOperator"` string in `packages/babel-parser/src`, you'll see that (as @hzoo mentioned above) we are calling the `this.expectPlugin("pipelineOperator")` function [when we find the "pipeline" (`|>`) operator](https://github.com/babel/babel/blob/bb180eba9f3a2d0dc69e62beb788bfb8a9215a47/packages/babel-parser/src/parser/expression.js#L365-L366).

   We can do something similar for JSX, but it's harder. The main problem is that checks for ECMAScript proposals (such as `|>`) are inlined in the parser code, while checks for JSX code are only enabled when the `jsx` plugin is enabled.

   However, we know that JSX elements are _atomic expressions (parsed by the [`parseExprAtom`](https://github.com/babel/babel/blob/bb180eba9f3a2d0dc69e62beb788bfb8a9215a47/packages/babel-parser/src/parser/expression.js#L877) method) and that no other expression can start with `<`.
   That method contains a big `switch` statement, and (at the end) we throw `this.unexpected()` if we don't find any valid token. We could add a new case and, if the token is `<`, call `this.expectPlugin("jsx")`.

   Here are a few possible tests:
   - When the `jsx` plugin is not enabled, this code should throw the "nice" error:
     ```js
     <div /></div>
     ```
   - This is valid JS code, and it should never throw:
     ```js
     "use strict"
     <div
     ```
   - When the `typescript` plugin is enabled, this code shouldn't throw because it's a type parameter:
     ```js
     <div>() => {}
     ```

2. Then, we should make `@babel/core` handle the parser error and suggest the correct `@babel/...` plugin/preset. You can add the syntax plugin and the `react` preset at `packages/babel-core/src/parser/util/missing-plugin-helper.js`.

---



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add some tests: `packages/babel-parser/test/fixtures/jsx/errors/_no-plugin`, `packages/babel-parser/test/fixtures/jsx/errors/_no-plugin-no-jsx` and `packages/babel-parser/test/fixtures/jsx/errors/_no-plugin-ts-type-param`. You can see an example at `packages/babel-parser/test/fixtures/experimental/_no-plugin/import-meta`.
1. Update the code!
1. `yarn jest babel-parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-parser` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by karansapolia** [comment]
I would like to take this up.

**Comment by existentialism** [comment]
@karansapolia it's yours! let us know (here or on slack) if you have any questions!

**Comment by existentialism** [comment]
@karansapolia friendly ping, are you still working on this? no worries if not!

**Comment by karansapolia** [comment]
@existentialism so sorry, I have not been able to work on this yet. In case someone wants to pick this up, please feel free. I really want to start helping out with Babel, will try to chip in where I can next :slightly_smiling_face:

**Comment by existentialism** [comment]
@karansapolia no need to apologize at all!

**Comment by HiMrHu** [comment]
i want to try this.

**Comment by kaicataldo** [comment]
Awesome! Please feel free to reach out if you have any questions.

**Comment by penguingovernor** [comment]
Is this still available to pickup ? (:

**Comment by nicolo-ribaudo** [comment]
There is a PR opened for this: https://github.com/babel/babel/pull/11629 (@HiMrHu I noticed that you haven't responded, to my review: are you still working on it?)

**Comment by iosh** [comment]
I don't have time to resolve this, I'm busy with my new job，just take  it . I am  sorry for this PR.

**Comment by nicolo-ribaudo** [comment]
No problem, thanks for telling us!

**Comment by Yokubjon-J** [comment]
Hello! Can I take it up?

**Comment by nicolo-ribaudo** [comment]
We are working on this at #11722 with @penguingovernor. I'm looking for another issue you could help with.

**Comment by Yokubjon-J** [comment]
Please tell me that issue!
