### ISSUE TITLE
Incorrect variable scoping in switch statement

### ISSUE THREAD

**Issue by angrycat9000** [babel/babel#11509]
## Bug Report

**Current Behavior**

Babel uses a variable defined inside a switch statement block outside of the block. This hides previous definition of the variable.  This results in different code path execution before and after transformation.

**Input Code**

[REPL](https://babeljs.io/repl/#?browsers=ie%20%3E%3D%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABFApgZygCgB4EpEDeAUAJBoDuMUEAFjvsYk8xAIZoqIAMAXEcwMQQEGRNkQBeRAHIARqzAL20gNz9mAXyJaiQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env%2Cenv&prettier=false&targets=&version=7.9.6&externalPlugins=)

```js
function test(x) {
    switch(x) {
      case 0:
        const x = 'bananas';
    }
}
```

**Output**
```js
function test(x) {
  switch (_x) {
    case 0:
      var _x = 'bananas';
  }
}
```

**Expected behavior/code**

```js
function test(x) {
  switch (x) {  //<<<<<< expect the outer scope x instead of inner scope _x
    case 0:
      var _x = 'bananas';
  }
}
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
Here is what my project is using, but I am also able to produce it in the online REPL

```js
presets: ['@babel/preset-env'],
plugins: [
     '@babel/plugin-proposal-class-properties',
    ['@babel/plugin-proposal-decorators', { decoratorsBeforeExport: true } ],
     '@babel/plugin-transform-classes',
            ]
```

**Environment**
    @babel/core: ^7.9.6 => 7.9.6 
    @babel/plugin-proposal-class-properties: ^7.7.4 => 7.8.3 
    @babel/plugin-proposal-decorators: ^7.7.4 => 7.8.3 
    @babel/plugin-transform-block-scoping: ^7.8.3 => 7.8.3 
    @babel/plugin-transform-classes: ^7.7.4 => 7.9.5 
    @babel/preset-env: ^7.9.6 => 7.9.6 
    babel-loader: ^8.0.6 => 8.1.0 
    babel-loader-exclude-node-modules-except: ^1.0.3 => 1.0.3 
    webpack: ^4.39.3 => 4.42.1

**Comment by Valulz** [comment]
Hello @angrycat9000 

I might be mistaken, but you have to surround your case condition with curly braces if you want to declare a scoped variables in it. This is because let/const are block scoped. So, in your example, the const use the lexical binding of the switch, not the case 0. Which leads babel to transform the condition `switch(x)` into `switch(_x)`.

As you can see here : [REPL](https://babeljs.io/repl#?browsers=ie%20%3E%3D%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABFApgZygCgB4EpEDeAUAJBoDuMUEAFjvsYk8xAIZoqIAMAXIUc0GIICDImyIAvIgDkAI1ZhF7GQG4BQgL4am27USA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env%2Cenv&prettier=false&targets=&version=7.9.6&externalPlugins=), 
```js
function test(x) {
  switch(x) {
      case 0: {
        const x = 'bananas';
      }
    }
}
```
becomes :
```js
function test(x) {
  switch (x) {
    case 0:
      {
        var _x = 'bananas';
      }
  }
}
```

The `x` in the switch statement isn't converted.

**Comment by liuxingbaoyu** [comment]
Seems to have been fixed.
