### ISSUE TITLE
Unable to download @babel/helper-replace-supers ver. 7.9.6

### ISSUE THREAD

**Issue by dioufinos** [babel/babel#11503]
Hi,

we are using a Nexus as a proxy. Till now we were able to download all the prior versions of @babel/helper-replace-supers. Today we had the below behavior:

npm ERR! notarget No matching version found for @babel/types@^7.9.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/helper-replace-supers'

Can you please assist if this is a bug, as Nexus is able to use/download other packages with new versions.

Thank you in advance.

**Comment by geoefth90** [comment]
Same issue exists for @babel/traverse@^7.9.6

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/traverse@^7.9.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/helper-replace-supers'
npm ERR! notarget 

and is similar to the error reported in the previous release:
https://github.com/babel/babel/issues/11391#issue-596465139

@nicolo-ribaudo Could you please have a look?

Thank you in advance!

**Comment by nicolo-ribaudo** [comment]
Both `@babel/types` and `@babel/traverse` are correctly published on `npm`:

- https://www.npmjs.com/package/@babel/types/v/7.9.6 ([source code](https://unpkg.com/browse/@babel/types@7.9.6/))
- https://www.npmjs.com/package/@babel/traverse/v/7.9.6 ([source code](https://unpkg.com/browse/@babel/traverse@7.9.6/))

Since it's they are both published, there is nothing we can do about the errors you are getting. It's likely that your proxy has cached the old version of the package and it isn't loading the new one. If you can, try clearing the proxy's cache. Otherwise, you will have to wait until the cache is automatically updated (it might take a few hours, or even days).

If the problem doesn't disappear with a forced cache update, please report the bug to Nexus.

**Comment by dioufinos** [comment]
thanx for your prompt response @nicolo-ribaudo. Problem fixed as you said, this is a bug from Nexus side.

Thanx again!!!
