### ISSUE TITLE
@babel/runtime/helpers are not getting generated during babel rebuild from source

### ISSUE THREAD

**Issue by pravi** [babel/babel#11505]
## Bug Report

We are trying to update babel from 6 to 7 in debian, but @babel/runtime/helpers are not getting generated during rebuild from source (make build with babel-standalone tasks disabled, I'd assume these targets are only for browser build and should not be required for nodejs only builds).

Patch used to skip standalone make targets -> https://salsa.debian.org/js-team/node-babel/-/blob/babel7/debian/patches/skip-babel-standalone.patch

**Current Behavior**

It is not clear how to generate @babel/runtime/helpers from source.

**Environment**

Standard Debian build environment on debian unstable version with some packages from debian experimental.

For bootstrapping, first build is done with npm i and npm run build. https://salsa.debian.org/js-team/node-babel/-/blob/babel7/debian/rules#L27

Some patches are used to make it build on debian https://salsa.debian.org/js-team/node-babel/-/tree/babel7/debian/patches but nothing significant.

```
- Babel version(s): 7.4.5
- Node/npm version: Node 10/npm 5
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

Document how @babel/runtime/helpers are built and include that in make build target.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

Originally reported here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959110

**Comment by pravi** [comment]
The babel package built can rebuild itself and many other packages are rebuilt successfully https://wiki.debian.org/Javascript/Nodejs/Transitions/Babel7 the only failure is for packages that depends on @babel/runtime

**Comment by nicolo-ribaudo** [comment]
You can try `make build-dist`, which is `make build` + build polyfill and runtime. Starting from Babel 7.6.3 (https://github.com/babel/babel/pull/10506), you can use `make build-plugin-transform-runtime-dist`, which only builds `@babel/runtime`).

**Comment by pravi** [comment]
@nicolo-ribaudo thanks! Let me try this.

**Comment by pravi** [comment]
Thanks again, that fixed the issue. Can we replace browserify with rollup or webpack to generate the polyfill? Both rollup and webpack can replace browserify and that can reduce many build dependencies.

**Comment by nicolo-ribaudo** [comment]
In Babel 8 we will probably stop publishing `@babel/polyfill` since it has been deprecated for a long time. We now encourage our users to directly import the polyfill they want to use.

For reference, this is the source of `@babel/polyfill`: https://github.com/babel/babel/blob/master/packages/babel-polyfill/src/noConflict.js

**Comment by pravi** [comment]
@nicolo-ribaudo shouldn't package.json -> scripts -> build say `make build-dist` then? As `npm run build` currently produce an incomplete build and it is not really clear we need to run build-dist unless we get this error and dig deeper into the Makefile.

**Comment by nicolo-ribaudo** [comment]
- https://github.com/babel/babel/issues/11505#issuecomment-622406938 has been fixed (we removed browserify)
- we'll leave https://github.com/babel/babel/issues/11505#issuecomment-622673141 as-is, because the `"build"` script in `package.json` is currently useful while developing (when you almost never need to use `build-dist`). `make build-dist` is documented in CONTRIBUTING.md alongside with the other build commands.
