### ISSUE TITLE
core-js 2 deprecated warning with npm

### ISSUE THREAD

**Issue by Amosss** [babel/babel#11511]
Hi

I got the following

> pm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

```
npm list shows this:
+-- @quasar/app@1.8.3
| `-- @quasar/babel-preset-app@1.1.9
|   +-- @babel/runtime-corejs2@7.9.6
|   | `-- **core-js@2.6.11**
|   `-- babel-plugin-transform-imports@1.5.1
|     `-- babel-types@6.26.0
|       `-- babel-runtime@6.26.0
|         `-- **core-js@2.6.11  deduped**
`-- electron@8.2.5
  `-- @electron/get@1.10.0
    `-- global-agent@2.1.8
      `-- core-js@3.6.5
```

Is/was this addressed or about to be in the future?
Thanks

**Comment by nicolo-ribaudo** [comment]
I see two instances of `core-js` 2 in your dependencies:

- `@babel/runtime-corejs2 > core-js@2.6.11`
  Here it's explicit that `@quasar/babel-preset-app` wants to use `core-js` 3 because of the `@babel/runtime-corejs2` dependency. It can use `@babel/runtime-corejs3` instead.
- `babel-runtime > core-js@2.6.11`:
  This is part of babel 6. In Babel 7, `@babel/runtime` doesn't depend on `core-js` anymore.
