### ISSUE TITLE
Pre-formatted text loses line breaks

### ISSUE THREAD

**Issue by PedroLamas** [babel/babel#11678]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Text inside a `<pre>` block is loosing formatting when the block is converted to `React.createElement` function call.

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DwBwTgpgfAUANgSwHYQAQEZ7LQJhsAenGiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.10.2&externalPlugins=)

**Input Code**

```html
<pre>
line 1
line 2
</pre>
```

**Expected behavior**

The line breaks (and any spacing!) inside a `<pre>` block should be maintained.

I would expect this:

```js
React.createElement("pre", null, "line 1\nline 2");
```

Instead I get this:

```js
React.createElement("pre", null, "line 1 line 2");
```

**Comment by PedroLamas** [comment]
It seems `<code>` tag is also affected by this problem!

https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DwYw9gJgpgfAUAGwJYDsoAICMjUYExzAD040MQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.10.2&externalPlugins=

**Comment by viktor-yakubiv** [comment]
JSX supposed to work so. For any element, all spaces including newlines are replaced by a single line. I think is was desired behaviour by design.

If you pass `<pre>{'line1\nline2'}</pre>` to Babel, it will apprear as expected.

The problem here is that markdown including **MDX should be treated as HTML** at first and as JSX at second. Saying that I mean everything inside lowercased tags (which supposed to be HTML elements) should be parsed in HTML way preserving all the spaces.

Although, we may say that the whitespace should be preserved not for special tags but for the whole MDX since it's an HTML syntax.

I support the idea but it brings incompatibility with common JSX behaviour when the following example will behave as HTML but would be weird according to the common JSX practices.

```mdx
import Button from './button'

<Button>Action 1</Button>
<Button>Action 2</Button>
```

Treating this as HTML would render 2 buttons with a space character in between when JSX strips any spacing between the tags.

**Comment by PedroLamas** [comment]
Ah, I do see your point @viktor-yakubiv (especially after reading [this](https://reactjs.org/docs/jsx-in-depth.html#string-literals-1))

My interpretation was on the basis that HTML inside an markdown (.md file) file is maintained, but the same is not accurate for MDX (.mdx file) as the HTML is treated as JSX (so lines are collapsed and replaced with single space)

**Comment by PedroLamas** [comment]
Closing this issue as it does make sense from a JSX perspective to have the current behavior.
