### ISSUE TITLE
How to correctly remove Flow types in a React Native Web project?

### ISSUE THREAD

**Issue by chichke** [babel/babel#11694]
## Bug Report

**Current behavior**
I was trying to startup a [react-native-web](https://github.com/necolas/react-native-web) project and when i try to add [React Navigation 5](https://reactnavigation.org/docs/web-support/) 
I did try every solution on the web and nothing did work for me...

```
./node_modules/react-native-gesture-handler/DrawerLayout.js
SyntaxError: /Users/chichke/Documents/Work/XXX/node_modules/react-native-gesture-handler/DrawerLayout.js: Support for the experimental syntax 'flow' isn't currently enabled (30:8):

  28 | const SETTLING = 'Settling';
  29 | 
> 30 | export type PropType = {
     |        ^
  31 |   children: any,
  32 |   drawerBackgroundColor?: string,
  33 |   drawerPosition: 'left' | 'right',

Add @babel/plugin-transform-flow-strip-types (https://git.io/vb49g) to the 'plugins' section of your Babel config to enable transformation.
```

**Expected behavior**
Building 😆 

**Babel Configuration**
- Filename: `babel.config.js`

```js
const path = require('path')

module.exports = (api) => {
  api.cache(true);

  return {
    rules: [
      {
        test: path.join(__dirname, "."),
        exclude: /(node_modules)/,
        loader: "babel-loader",
        options: {
          presets: [
            "@babel/preset-env",
            "@babel/react",
            {
              plugins: ["@babel/plugin-proposal-class-properties", "@babel/plugin-transform-flow-strip-types"],
            },
          ],
        },
      },
    ],

    resolve: {
      alias: {
        "react-native$": "react-native-web",
      },
    },
    presets: [
      "react-native-web",
      "module:metro-react-native-babel-preset",
      "@babel/preset-flow",
    ],
    plugins: [
      [
        "@babel/plugin-transform-flow-strip-types",
        {
          loose: true,
        },
      ],
      ["@babel/plugin-proposal-export-default-from"],
      ["@babel/plugin-transform-runtime"],
      [
        "@babel/plugin-proposal-class-properties",
        {
          loose: true,
        },
      ],
      [
        ("module-resolver",
        {
          alias: {
            "^react-native$": "react-native-web",
          },
        }),
      ],
    ].map(require.resolve),
  };
};

```

⚠️  **I have a `webpack.config.js` with same config as babel.config.js**

**Environment**
```
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  npmPackages:
    @babel/cli: ^7.10.1 => 7.10.1 
    @babel/core: ^7.10.2 => 7.10.2 
    @babel/plugin-proposal-class-properties: ^7.10.1 => 7.10.1 
    @babel/plugin-proposal-export-default-from: ^7.10.1 => 7.10.1 
    @babel/plugin-transform-flow-strip-types: ^7.10.1 => 7.10.1 
    @babel/plugin-transform-runtime: ^7.10.1 => 7.10.1 
    @babel/preset-flow: ^7.10.1 => 7.10.1 
    babel-plugin-module-resolver: ^4.0.0 => 4.0.0 
```
- Babel version(s): v7.10.1
- Node/npm version: Node:v12.14.1
- OS: OSX 10.15.4,
- Monorepo: yes
- How you are using Babel: loader

**Package.Json**

```
{
  "name": "XXX",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/core": "^7.10.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/core": "^5.10.0",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "babel-plugin-module-resolver": "^4.0.0",
    "react": "16.11.0",
    "react-dom": "16.11.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.2",
    "react-native-screens": "^2.8.0",
    "react-native-web": "^0.12.3",
    "react-scripts": "3.4.1",
    "typescript": "^3.9.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/cli": "^7.10.1",
    "@babel/plugin-proposal-class-properties": "^7.10.1",
    "@babel/plugin-proposal-export-default-from": "^7.10.1",
    "@babel/plugin-transform-flow-strip-types": "^7.10.1",
    "@babel/plugin-transform-runtime": "^7.10.1",
    "@babel/preset-flow": "^7.10.1"
  },
  "jest": {
    "preset": "react-native-web",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
  }
}

```

- Anything would be greatly appreciated! ❤️

**Comment by existentialism** [comment]
@chichke your babel config doesn't look right:

```
        options: {
          presets: [
            "@babel/preset-env",
            "@babel/react",
            {
              plugins: ["@babel/plugin-proposal-class-properties", "@babel/plugin-transform-flow-strip-types"],
            },
          ],
        },
```

`plugins` should be the same level as `presets`, not an item within it.

**Comment by JLHwung** [comment]
It seems to me that your project is created from `create-react-app` but you are using react native library. 

As is recommended on https://github.com/facebook/create-react-app#react-native, please use `Expo CLI` to initialize your project.

As @existentialism mentioned above, there are also issues in your config file. But I think if you never run `npm run eject`, these config is no-op.

TL;DR

The `react-native-gesture-handler` is in the `node_modules`, which means it is part of dependencies instead of the app code. `react-scripts` will apply an internal preset called
[`babel-preset-react-app/dependencies`](https://github.com/facebook/create-react-app/blob/fa648daca1dedd97aec4fa3bae8752c4dcf37e6f/packages/babel-preset-react-app/dependencies.js) to your dependencies. This preset does not include `@babel/plugin-transform-flow-strip-types` so error is thrown.

**Comment by arelra** [comment]
@chichke  To expand on @existentialism and @JLHwung 

This looks like the result of not transpiling your `react-native` dependencies with the right set of presets/plugins.

When creating a cross platform `react-native` app using `react-native-web` you need to transpile any `react-native` dependencies you may have in `node-modules`.

This is because `react-native` dependencies are not usually published as transpiled or isomorphic browser-friendly versions as normally they'd be piped by `react-native` through [metro-react-native-babel-preset](https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-preset/package.json) to perform any transpilation necessary to run on iOS or Android.

However `metro-react-native-babel-preset` is a very heavy preset and will create very large bundle sizes for the web.

So when targeting the web you need to make sure that you:
1. Add a `babel-loader` loader to your webpack config for any `react-native` dependencies you may be using
1. Add any relevant presets or plugins required by those dependencies

If you used `create-react-app` to create your web application (and have ejected it) then add the following presets to the options of each `react-native` dependency's `babel-loader`:

1. `babel-preset-react-app` which adds in the majority of common plugins you'll need
2. `babel-preset-react-app/dependencies` which forces Babel to detect any non-ES6 modules

So something like this:

```
  {
    test: /(@?react-(navigation|native)).*\.(ts|js)x?$/,
    exclude: [/react-native-web/, /\.(native|ios|android)\.(ts|js)x?$/],
    loader: 'babel-loader',
    options: {
      presets: [
        [
          require.resolve('babel-preset-react-app/dependencies'),
          { helpers: true },
        ],
        ['babel-preset-react-app'],
      ],
      ...
```

If this is a new error and your webpack config was working previously it's also possible that your loader test regexes are not being hit correctly so you might want to take a look at those.
