### ISSUE TITLE
range is not right 

### ISSUE THREAD

**Issue by darknessjs** [babel/babel#11770]
code:
import(``)

in ASTExplorer :
![image](https://user-images.githubusercontent.com/10798107/86225284-98cc6800-bbbc-11ea-9829-2c6a86663e50.png)

or @babel/parser 7.2.3:
![image](https://user-images.githubusercontent.com/10798107/86225367-b4d00980-bbbc-11ea-95dc-1ce0e1ee9df2.png)

but in 7.10.3:
![image](https://user-images.githubusercontent.com/10798107/86225424-cb766080-bbbc-11ea-89c5-f2d0e22def3a.png)

It make eslint have an Error : 
TypeError: Cannot read property 'range' of null

**Comment by darknessjs** [comment]
image upload is not right 。。。
eslint error is:
TypeError: Cannot read property 'range' of null

**Comment by JLHwung** [comment]
The behaviour is expected: `range[0]` is always equal to `start` and `range[1]` for `end`. I believe you are referring to https://github.com/babel/babel-eslint/issues/799, where Roland has gave a thorough explanation: https://github.com/babel/babel-eslint/issues/799#issuecomment-571075247

That issue will be fixed in `@babel/eslint-parser` (currently not yet published).
