### ISSUE TITLE
Create plugin https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-systemjs-modules

### ISSUE THREAD

**Issue by frank-dspeed** [babel/babel#11827]
## Feature Request
transform systemjs to es6+ modules 

- [ ] I would like to work on this feature!

**Is your feature request related to a problem?**
When I want to bundle systemjs modules and re-evaluate the graph for example with rollup and create a new systemjs bundle (new chunked) then I need a way to transpile systemjs=>es6-modules before i generate the output.

i am already working on creating a systemjs loader for rollup and this would ideally get used by it.

**Describe the solution you'd like**
transpile systemjs format to es6 module format
**Describe alternatives you've considered**.
rewrite rollup or create a new app that takes systemjs for graph analyze 

**Documentation, Adoption, Migration Strategy**
They will ideally use that as babel preset systemjs or maybe only directly the plugin to transpile systemjs modules that come from the systemjs loader into es6-modules

**Comment by nicolo-ribaudo** [comment]
Generally Babel is for compiling modern syntax to older one (i.e. es modules to systemjs). It's definitely possible to try writing the opposite plugin, but:
- It isn't something that belongs to this repository. You can try writing your own plugin using, for example, https://astexplorer.net/ to prototype it
- It might be hard because SystemJS is more flexible than es modules, because it doesn't rely on special syntax.

**Comment by frank-dspeed** [comment]
@nicolo-ribaudo are you sure as systemjs is a current formart? There exist cdn's some scripts exist as systemjs only version and it is only the wrapping. Awww but anyway the issue exists and i will move on to the next task :)
