### ISSUE TITLE
Babel corejs3 export and export default issue

### ISSUE THREAD

**Issue by farhan-sauce** [babel/babel#11825]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
Import property doesn't work when using both `export default` and `export` in same file. This issue is visible when I use
"@babel/plugin-transform-runtime, { corejs: 3 }" and "add-module-exports" plugins together. It used to work fine without using `corejs: 3` with `@babel/plugin-transform-runtime`.

Please check [my repo](https://github.com/farhan-sauce/babel-corejs3-test) to reproduce the issue.
Run `npm install && npm start` will print `undefined` but it works fine if you comment out `"corejs": 3,` from plugin "@babel/plugin-transform-runtime" in .babelrc.

**Input Code**

```js
// constants.js
const TYPES = {
  'hello': 'world'
};

export default TYPES;

// index.js
import constants from './constants';

const testDefault = (name, age) => ({
  name,
  age
});

export default testDefault;

export {
  constants,
};

// run.js 
import defFunc, { constants } from './index';

console.log(defFunc('cool', 15))
console.log(JSON.stringify(constants));
```

It prints constants as undefined while using following babel config.

**Expected behavior**
`export` and `export default` from same file should work fine. It works when we comment out `corejs: 3` from "@babel/plugin-transform-runtime".

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```js
{
  "presets": [
    ["@babel/preset-env", {
      "bugfixes": true,
      "useBuiltIns": "entry",
      "corejs": 3,
    }]
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "corejs": 3
    }],
    "add-module-exports"
  ]
}
```

**Environment**

```
 System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.10.4 => 7.10.4
    @babel/core: ^7.10.4 => 7.10.4
    @babel/plugin-transform-runtime: ^7.10.4 => 7.10.4
    @babel/preset-env: ^7.10.4 => 7.10.4
    @babel/runtime-corejs3: ^7.10.4 => 7.10.4
    babel-plugin-add-module-exports: ^1.0.2 => 1.0.2
```

**Comment by JLHwung** [comment]
@farhan-sauce Thanks for the reproducing repo! It is greatly helpful.

The issue comes from integrations between `transform-runtime` and `add-module-exports`: If you remove `add-module-exports`, both `corejs: 3` and `corejs: 2` (the default) produce desired output.

`add-module-exports` relies on the exact shape of `Object.defineProperty`:
https://github.com/59naga/babel-plugin-add-module-exports/blob/e8e5be08d09ff491cf0d83c55f00be1363fd7cea/src/index.js#L123

However if you use `corejs: 3` of `transform-runtime`, `Object.defineProperty` will be replaced to `$ObjectDefineProperty` and thus `add-module-exports` fails to detect that `exports.constants` exists in the transpiled out and it will add `module.exports = exports.default` to `lib/index.js` and thus `exports.constants` is no more accessible.

I am afraid there is not much can be done on Babel side. Please submit an issue at https://github.com/59naga/babel-plugin-add-module-exports
