### ISSUE TITLE
No matching version found for @babel/types@^7.10.5

### ISSUE THREAD

**Issue by lucastrevisan** [babel/babel#11839]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.10.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/helper-builder-react-jsx-experimental'
npm ERR! notarget

**Comment by JLHwung** [comment]
The version is correctly published on npm: https://www.npmjs.com/package/@babel/types

If you are behind a proxy (maybe for work) it's probably its cache that isn't updated.
Otherwise, please report this bug to npm (https://github.com/npm/cli/issues/new/choose) because once there is nothing we can do about it.
