### ISSUE TITLE
.babelrc ignoring env-specific preset settings

### ISSUE THREAD

**Issue by bgp1** [babel/babel#11881]
I am trying to set different preset configurations for modules based on environment. For the “none” environment I’m passing a preset-env modules setting of “commonjs” but all others I’m using the standard default “auto” setting. When I run my code using “none” it’s not overriding and continues to utilize the generic configurations.

**Comment by JLHwung** [comment]
When merging env-specific configs, babel uses `Array#concat` for `presets`, see https://github.com/babel/website/pull/2302/files#diff-76e731333fb756df3bff5ddb3b731c46R197 on how Babel merges config items.

So 
```js
{
  presets: [["@babel/env", { modules: "auto" }]]
  env: {
    none: {
      presets: [["@babel/env", { modules: "commonjs" }]]
    }
  }
}
```
will be merged as
```js
{
  presets: [["@babel/env", { modules: "auto" }], ["@babel/env", { modules: "commonjs" }]]
}
```
So this issue is expected according to the behaviours. I admit it may not matches everyone's expectation. In Babel we use a switch-case to specify different `preset-env` options: https://github.com/babel/babel/blob/4c9929ca2830d7916e7485096269ccdf4e36a251/babel.config.js#L35-L69
