### ISSUE TITLE
change some dependencies?

### ISSUE THREAD

**Issue by jimmywarting** [babel/babel#11925]
https://github.com/babel/babel/blob/a827ca41f3c07a1ffddeaa00998c772a61a60b68/packages/babel-cli/package.json#L25-L37

picomatch seems like it's faster, newer and gaining popularity over glob? don't know about compatibility doe 

chokidar needs a bump to latest version?

**Comment by JLHwung** [comment]
> picomatch seems like it's faster, newer and gaining popularity over glob

`picomatch` is a glob matcher. If we replace `glob`, we still need to wire up the `fs` bits. I am open to explore performant alternatives but currently it is not prioritized because `node-glob` is not the bottleneck.

> chokidar needs a bump to latest version?

`chokidar` has been updated to version 3 in Babel 8. Unfortunately we can not bump chokidar 2 because Babel 7 still supports node 6.
