### ISSUE TITLE
Error with "s" flag when `new RegExp()`

### ISSUE THREAD

**Issue by dojyorin** [babel/babel#11976]
# Bug Report
- [ ] I would like to work on a fix!

**Current behavior**
An error will occur if the "s" flag is specified as the second argument when generating RegExp from the constructor.

In the case of a RegExp literal it worked.

**Input Code**

```js
// Constructor -> Not Worked😟
new RegExp("foobar", "s");

// Literal -> Worked😁
/foobar/s
```

**Expected behavior**
Should be parsed like a RegExp literal.

**Babel Configuration**

```js
window.Babel.transform(src, {
    presets: ["env", "stage-3"]
});
```

**Environment**

- Babel version: v7.11.3
- OS: Windows10 64bit
- Using web browser: Internet Explorer 11
- How you are using Babel: `standalone`

**Possible Solution**

Apply the same processing as for literals (?)
(Sorry, I'm not familiar with babel internals)

**Comment by JLHwung** [comment]
Babel does not transform string arguments inside `RegExp()` because they could be a general expression, whose value may not be available when Babel is compiling the sources. For example,

```js
import { regexString } from "./some-module";
new RegExp(regexString, someFlags);
```

Babel can not transpile it because both `regexString` and `someFlags` are unknown.

```
new RegExp("foobar", "s");
```
Although it is a case where Babel could know the values of each arguments, IMO they should be refactored into regex literals: you can enable the https://eslint.org/docs/rules/prefer-regex-literals rule which should error about the `new RegExp("foobar", "s");` usage.

**Comment by dojyorin** [comment]
Thank you for your response.
I was actually trying to evaluate exactly this kind of unknown string.
(Function to remove the start and end tags from an HTML string.)

```js
function innerText(doc, tag){
    const start = new RegExp(`^<${tag}. *? >`, "is");
    const end = new RegExp(`</${tag}>$`, "is");

    return doc.trim().replace(start, "").replace(end, "").trim();
}
```

As a temporary workaround, I've taken the somewhat tricky step of reversing the string over to match it from behind.

```js
function innerText(doc, tag){
    function rev(text){
        return text.split("").reverse().join("");
    }

    const start = new RegExp(`^<${tag}. *? >`, "i");
    const end = new RegExp(`^>${rev(tag)}/<`, "i");

    return rev(rev(doc.trim().replace(start, "")).replace(end, "")).trim();
}
```

But I understand why can't transpiled.
I guess I was wrong, I'm sorry.
