### ISSUE TITLE
@babel/code-frame assumes location input will contain numbers

### ISSUE THREAD

**Issue by micburks** [babel/babel#11981]
## Bug Report

`@babel/code-frame` assumes location input contains integers. String input can prevent `linesBefore` from truncating output due to unintentional string concatenation on [this line](https://github.com/babel/babel/blob/main/packages/babel-code-frame/src/index.js#L57).

```js
import {codeFrameColumns} from '@babel/code-frame';

const result = codeFrameColumns(
  fs.readFile(filename, 'utf-8'), // file with < 322 lines
  { start: { line: '32' },
  { linesBelow: 2 },
);
```

This is obviously user-error (and would be caught if using static types), but results in confusion rather than an error. It's simple enough to protect against within `@babel/code-frame`.

**Expected behavior**
`@babel/code-frame` should truncate input according to `linesAbove`/`linesBelow`.

**Possible Solution**

Use `parseInt` on location input before using in arithmetic expressions

**Comment by JLHwung** [comment]
I think this issue is more of a document issues: we should specify the `Location`-type in https://babeljs.io/docs/en/babel-code-frame#usage.

TBH the `parseInt` approach makes things unnecessarily complicated: That `@babel/code-frame` implicitly support `start.line` to be a number-like string, and it can be `"42.whatever"`. It is also open-ended: why `{ linesBelow: 2 }` accept only number while `location.start` can be a number-like string?

It makes sense to me that we should type checking the input since `codeFrameColumns` is a public interface. While technically it is a breaking change that won't be shipped in Babel 7. A better document can help reduce such debug pains.
