### ISSUE TITLE
`generate()` produces incorrect output for arrow function expression

### ISSUE THREAD

**Issue by overlookmotel** [babel/babel#12055]
## Bug Report

- [X] I would like to work on a fix!

**Current behavior**
A clear and concise description of the behavior.

`generate()` produces incorrect code for arrow function expression.

```js
const generate = require('@babel/generator').default;
const node = t.arrowFunctionExpression( [], t.objectExpression( [] ) );
console.log( generate( node ) );
```

Output:

```js
() => {}
```

Output should be:

```js
() => ({})
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

No config used. The above is the complete reproduction case.

**Environment**

```
System:
	OS: macOS Mojave 10.14.6
Binaries:
	Node: 14.9.0 - ~/.nvm/versions/node/v14.9.0/bin/node
	npm: 6.14.8 - ~/.nvm/versions/node/v14.9.0/bin/npm
npmPackages:
	@babel/core: ^7.11.6 => 7.11.6 
	@babel/generator: ^7.11.6 => 7.11.6 
	@babel/helper-module-transforms: ^7.11.0 => 7.11.0 
	@babel/parser: ^7.11.5 => 7.11.5 
	@babel/plugin-transform-modules-commonjs: ^7.10.4 => 7.10.4 
	@babel/plugin-transform-react-jsx: ^7.10.4 => 7.10.4 
	@babel/register: ^7.11.5 => 7.11.5 
	@babel/traverse: ^7.11.5 => 7.11.5 
	@babel/types: ^7.11.5 => 7.11.5 
	babel-jest: ^26.3.0 => 26.3.0 
	babel-plugin-dynamic-import-node: ^2.3.3 => 2.3.3 
	eslint: ^7.8.1 => 7.8.1 
	jest: ^26.4.2 => 26.4.2
```

**Comment by JLHwung** [comment]
You can take a look at https://github.com/babel/babel/blob/c8f0b6dc1ecbe99d34f9188863b41582bf55d043/packages/babel-generator/src/node/parentheses.js#L286-L322

In your case, the `printStack` is `Array (2) [ ArrowExpression, ObjectExpression ]`, it seems that the `while`-loop (which will consider arrow functions) is incorrectly skipped because `i == 0`. I believe the condition should be loosen and only applied to the second `if` condition where `i--` is applied.

PR is welcome. If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated) to `packages/babel-generator/test/fixtures/parentheses`
1. Update the code!
1. `yarn jest babel-generator` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by overlookmotel** [comment]
@JLHwung Thanks loads for the swift reply and advice to where to look in the code base.

I will try to put a PR together in next few days. I'll post another comment here when/if I start work on it, so there's no duplicated effort by another contributor.

**Comment by overlookmotel** [comment]
Failing test: https://github.com/overlookmotel/babel/tree/arrow-function-object-expression-fix

I've started work on a fix.

**Comment by overlookmotel** [comment]
PR submitted #12082. @JLHwung please have a look when you get a chance.
