### ISSUE TITLE
[Feature Request][@babel/helper-module-imports]Provide a option to  inject helpers via "require" instead of "import".

### ISSUE THREAD

**Issue by NE-SmallTown** [babel/babel#12162]
## Feature Request

- [ ] I would like to work on this feature!

**Is your feature request related to a problem?**

Yes, see https://twitter.com/lukastaegert/status/1314255655621058563

**Describe the solution you'd like**

Provide a option to make `@babel/helper-module-imports` inject helpers via "require" instead of "import".

**Describe alternatives you've considered**.

I don't know, but I think it seems there is no precedent like the option described above? Maybe `@babel/helper-module-imports` can inject the helper according to the module syntax of the file rahter than always use ESM?

**Documentation, Adoption, Migration Strategy**

That depends on what solution we choose

**Comment by nicolo-ribaudo** [comment]
> Maybe `@babel/helper-module-imports` can inject the helper according to the module syntax of the file rahter than always use ESM?

Yup, that's already how it works:
https://github.com/babel/babel/blob/3e0fa927c09183b0ef9a280b4258f8db673085fc/packages/babel-helper-module-imports/test/index.js#L139-L148

Could you provide an example where it's injecting `import` in scripts? :pray:

**Comment by NE-SmallTown** [comment]
Sure ,you can see https://twitter.com/lukastaegert/status/1314414811669725187 for more details, and see https://twitter.com/Heaven_xz/status/1314186870859821057 for the repro

**Comment by nicolo-ribaudo** [comment]
Hey, sorry for forgetting about this issue.

I cloned your repo and the problem is that `@rollup/plugin-babel` must be put _after_ `@rollup/plugin-commonjs`. ([docs](https://github.com/rollup/plugins/tree/master/packages/babel#using-with-rollupplugin-commonjs)).

I tried doing so, but it seems like `@rollup/plugin-commonjs` doesn't support JSX.

However, I was able to confirm that moving `commonjs` fixes the issue by:
1. Removing JSX from your files
2. Removing `targets` from your Babel config, so that Babel transforms classes and thus injects `import`/`require` for helepers.

The output still contained `require("./bar")`, but as soon as I put the `commonjs` plugin first it correctly worked.

Since this issue is about the interaction between rollup plugins, I suggest reporting it to https://github.com/rollup/plugins where they are both maintained.
