### ISSUE TITLE
babel-traverse: error on install (issue with @babel/parser)

### ISSUE THREAD

**Issue by rajat19** [babel/babel#12179]
Some dependecy of my node project is using @babel/traverse
Getting error 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/parser@^7.12.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/traverse'
npm ERR! notarget 
```

Can someone suggest something or help regarding this ?

**Comment by nicolo-ribaudo** [comment]
`@babel/parser@7.12.0` is correctly published on npm (https://www.npmjs.com/package/@babel/parser/v/7.12.0). For some reason your package manager client doesn't find it, and it's usually due to a proxy. In this case, we won't be able to do anything on our end. :frowning_face: 

If you are using a proxy (Nexus) for the npm registry (maybe it's used by your company, or you are using it because your country blocks the main npm registry), then it's likely that it has cached the old version of the package and it isn't loading the new one. If you can, try clearing the proxy's cache. Otherwise, you will have to wait until the cache is automatically updated (it might take a few hours, or even days).

If you are not using a proxy, or if it isn't a caching problem, please report the issue to npm instead of the Babel repo!
