### ISSUE TITLE
No matching version found for @babel/traverse@^7.12.0

### ISSUE THREAD

**Issue by jabberwo** [babel/babel#12176]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
Build error for unchanged code.  Appears to be result of update of babel 4 hours ago:

No matching version found for @babel/traverse@^7.12.0.

**Expected behavior**

A build that works even when y'all update the library

**Environment**
```
$ npx envinfo --preset babel
npx: installed 1 in 1.375s

  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
```
```
abacus-react-components@0.0.1
├─┬ @babel/core@7.11.6
│ ├─┬ @babel/code-frame@7.10.4
│ │ └─┬ @babel/highlight@7.10.4
│ │   ├── @babel/helper-validator-identifier@7.10.4
│ │   ├─┬ chalk@2.4.2
│ │   │ ├─┬ ansi-styles@3.2.1
│ │   │ │ └─┬ color-convert@1.9.3
│ │   │ │   └── color-name@1.1.3
│ │   │ ├── escape-string-regexp@1.0.5
│ │   │ └─┬ supports-color@5.5.0
│ │   │   └── has-flag@3.0.0
│ │   └── js-tokens@4.0.0
│ ├─┬ @babel/generator@7.11.6
│ │ ├─┬ @babel/types@7.11.5
│ │ │ ├── lodash@4.17.20
│ │ │ └── to-fast-properties@2.0.0
│ │ ├── jsesc@2.5.2
│ │ └── source-map@0.5.7
│ ├─┬ @babel/helper-module-transforms@7.11.0
│ │ ├── @babel/helper-module-imports@7.10.4
│ │ ├─┬ @babel/helper-replace-supers@7.12.0
│ │ │ ├── @babel/helper-member-expression-to-functions@7.12.0
│ │ │ └── @babel/helper-optimise-call-expression@7.10.4
│ │ ├─┬ @babel/helper-simple-access@7.10.4
│ │ │ └─┬ @babel/template@7.10.4
│ │ │   └── @babel/parser@7.11.5
│ │ ├── @babel/helper-split-export-declaration@7.11.0
│ │ └── @babel/template@7.10.4
│ ├─┬ @babel/helpers@7.10.4
│ │ └── @babel/traverse@7.11.5
│ ├── @babel/parser@7.11.5
│ ├── @babel/template@7.10.4
│ ├── @babel/traverse@7.11.5
│ ├── @babel/types@7.11.5
│ ├─┬ convert-source-map@1.7.0
│ │ └── safe-buffer@5.1.2
│ ├── debug@4.2.0
│ ├── gensync@1.0.0-beta.1
│ ├─┬ json5@2.1.3
│ │ └── minimist@1.2.5
│ ├── lodash@4.17.20
│ ├── resolve@1.17.0
│ ├── semver@5.7.1
│ └── source-map@0.5.7

```

**Comment by nicolo-ribaudo** [comment]
`@babel/traverse@7.12.0` is correctly published on npm (https://www.npmjs.com/package/@babel/traverse/v/7.12.0). For some reason your package manager client doesn't find it, and it's usually due to a proxy. In this case, we won't be able to do anything on our end. :frowning_face: 

If you are using a proxy (Nexus) for the npm registry (maybe it's used by your company, or you are using it because your country blocks the main npm registry), then it's likely that it has cached the old version of the package and it isn't loading the new one. If you can, try clearing the proxy's cache. Otherwise, you will have to wait until the cache is automatically updated (it might take a few hours, or even days).

If you are not using a proxy, or if it isn't a caching problem, please report the issue to npm instead of the Babel repo!

**Comment by jabberwo** [comment]
Yes thanks, a few hours later and nexus is getting us the latest and greatest! Sorry to disturb -- I've had a number npm package updates cause problems the last few weeks so jumped to bad conclusion.

**Comment by existentialism** [comment]
@jabberwo no need to apologize, glad it's working
