### ISSUE TITLE
error : Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by cameronbraid** [babel/babel#12201]
## Bug Report

**Current behavior**

Currently my project compiles fine with babel 7.4.5 however when upgrading to 7.12 I get 

```
WARNING in ./src/entry.ts 11:35-45
Critical dependency: the request of a dependency is an expression
```

I extracted an almost minimal reproducer at :

https://codesandbox.io/s/pensive-morse-rmu2t

**Comment by nicolo-ribaudo** [comment]
The problem is that you are compiling esmodules to `commonjs`*, and webpack cannot fully handle dynamic imports compiled to commonjs. You were lucky that it was working, but any (valid) change in the generated commonjs output could break webpack compatibility.

\* **Why?** Because `@babel/preset-env` transiples to commonjs by default, except if the caller (`awesome-webpack-loader`) tells Babel that it supports ES modules (`awesome-webpack-loader` doesn't tell it to Babel, even if webpack supports them).
\* **How to fix it?** Pass the `modules: false` option to `@babel/preset-env`.

**Comment by cameronbraid** [comment]
@nicolo-ribaudo Oh man thats fantastic, spent hours on this.. glad I asked here 👍
