### ISSUE TITLE
[eslint-parser + proposal-private-methods] function name not parsed correctly

### ISSUE THREAD

**Issue by cruzdanilo** [babel/babel#12282]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

when using experimental private methods with `@babel/eslint-parser`, eslint doesn't recognize the method's name. i am not transpiling the code, only using babel for parsing with eslint because node already shipped [class fields](https://github.com/tc39/proposal-class-fields) and [private methods](https://github.com/tc39/proposal-private-methods), which currently are stage 3 proposals.

**Input Code**

```js
class Class {
  #privateMethod() {}
}
```

**Expected behavior**

no errors.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.eslintrc.js`

```js
module.exports = {
  parser: '@babel/eslint-parser',
  parserOptions: {
    requireConfigFile: false,
    babelOptions: {
      plugins: [
        '@babel/proposal-class-properties',
        '@babel/proposal-private-methods',
      ],
    },
  },
  extends: [
    'airbnb-base',
  ],
};
```

**Environment**

```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 15.0.1 - ~/.nodenv/versions/15.0.1/bin/node
    Yarn: 1.22.10 - ~/.nodenv/versions/15.0.1/bin/yarn
    npm: 7.0.5 - ~/.nodenv/versions/15.0.1/bin/npm
  npmPackages:
    @babel/core: ^7.12.3 => 7.12.3 
    @babel/eslint-parser: ^7.12.1 => 7.12.1 
    @babel/plugin-proposal-class-properties: ^7.12.1 => 7.12.1 
    @babel/plugin-proposal-private-methods: ^7.12.1 => 7.12.1 
    eslint: ^7.12.1 => 7.12.1 
```

**Possible Solution**

**Additional context**

another case i found on stackoverflow: https://stackoverflow.com/questions/64542305/func-names-eslint-rule-fails-when-using-private-methods-syntax

**Comment by kaicataldo** [comment]
Can you share what errors you're seeing? The exact output from your terminal would be the most helpful thing here.

**Comment by cruzdanilo** [comment]
```log
$ npx eslint Class.js 

Class.js
  2:17  error    Missing space before function parentheses  space-before-function-paren
  2:17  warning  Unexpected unnamed function                func-names
```

**Comment by kaicataldo** [comment]
If the code being linted is the code shared in the original issue comment, it looks like `func-names` will need a corresponding rule made in `@babel/eslint-plugin` (rules can be found [here](https://github.com/babel/babel/tree/main/eslint/babel-eslint-plugin/src/rules)).

**Comment by Dragiyski** [comment]
> If the code being linted is the code shared in the original issue comment, it looks like `func-names` will need a corresponding rule made in `@babel/eslint-plugin` (rules can be found [here](https://github.com/babel/babel/tree/main/eslint/babel-eslint-plugin/src/rules)) that filters out these errors.

I had a problem with this bug, and it seems that it is a problem within babel parser. Namely, inside `@babel/parser/src/plugins/estree.js`. The plugin converts babylon spec tree into estree spec tree. However inside there is nothing to handle `ClassPrivateMethod` node type and estree does not have such nodes. There should be a converter from `ClassPrivateMethod` to `MethodDefinition` nodes whose `Identifier` in `id` would start with `#` symbol, otherwise the node should not be any different from other `MethodDefinition` nodes. I might create pull request for that, if I have time. For now disabling `space-before-function-paren` seems to be the best option.

**Comment by JLHwung** [comment]
@Dragiyski ESTree has defined class private method as an experimental feature in https://github.com/estree/estree/blob/master/experimental/class-features.md, but acorn has not yet implemented it. 

We could implement this experimental proposal on the `estree` plugin and hopefully it will be merged to ESTree once the class feature ES proposal reached stage 4. But before ESLint supports private methods and class properties, we still have to filter linter reports in `@babel/eslint-plugin`.

**Comment by Dragiyski** [comment]
> acorn has not yet implemented it

I see. That's explains it. However, I disagree that `eslint` needs to do anything for that rule. Check the link you posted. The `MethodDefinition` is now extended to have `key` either `Expression` or `PrivateProperty`. In the `space-before-function-paren` the rule checks only the parent for `MethodDefinition`, so it should work with the new `PrivateProperty` node type:

https://github.com/eslint/eslint/blob/37a06d633d3669f0f43236141dc43465b8bc7ec5/lib/rules/space-before-function-paren.js#L76-L78

The `estree` plugin is supposed to make the tree conforming to the `estree` specification and babel will parse correctly private methods when `classPrivateMethods` plugin is included. Having `ClassPrivateMethod` node type instead of `MethodDefinition` node type is a violation of the `estree` definition. There must be some documentation that `classPrivateMethods` is not compatible with `estree`, or otherwise, this is a bug of `estree` plugin.

**Comment by JLHwung** [comment]
> before ESLint supports private methods and class properties

Rules such as `func-names` will need to adapt to `PrivateIdentifier`: 

https://github.com/eslint/eslint/blob/37a06d633d3669f0f43236141dc43465b8bc7ec5/lib/rules/func-names.js#L118-L122

> Having ClassPrivateMethod node type instead of MethodDefinition node type is a violation of the estree definition. 

Yes. Babel AST is different to ESTree, see https://babel.dev/docs/en/babel-parser#output. The `estree` plugin transforms Babel AST to ESTree but leave those unsupported AST node (experimental features) as-is.

**Comment by halitaydin** [comment]
I have faced same problem. Use arrow function on private method.

`class Class {
  #privateMethod = () => {}
}`

**Comment by Gerjunior** [comment]
Arrow functions have lexical scope, so you can't use `this` to get function methods/properties inside them.

**Comment by Gerjunior** [comment]
> I have faced same problem. Use arrow function on private method.
> 
> `class Class { #privateMethod = () => {} }`

Arrow functions have lexical scope, so you can't use this to get function methods/properties inside them.

**Comment by halitaydin** [comment]
> > I have faced same problem. Use arrow function on private method.
> > `class Class { #privateMethod = () => {} }`
> 
> Arrow functions have lexical scope, so you can't use this to get function methods/properties inside them.

Yes you're right. But everything seemed fine after using arrow function within the eslint rules. 
By the way, I've just tried.
