### ISSUE TITLE
Class properties *sometimes* have a descriptor defined on prototype, sometimes not.

### ISSUE THREAD

**Issue by jayphelps** [babel/babel#1235]
Since class properties are still stage 0, it's understandably unclear, but I wanted to note that if you use a decorator on a class property, it defines a descriptor on the prototype, and uses an `initializer()` but if it isn't decorated it is set directly inside the constructor instead.

[Demo](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20something(target%2C%20key%2C%20descriptor)%20%7B%0A%20%20return%20descriptor%3B%0A%7D%0A%0Aclass%20Foo%20%7B%0A%20%20a%20%3D%20'a'%3B%0A%20%20%0A%20%20%40something%0A%20%20b%20%3D%20'b'%3B%0A%7D%0A%0AObject.getOwnPropertyDescriptor(Foo.prototype%2C%20'a')%3B%0A%2F%2F%20undefined%0A%0AObject.getOwnPropertyDescriptor(Foo.prototype%2C%20'b')%3B%0A%2F%2F%20%7B%20value%3A%20undefined%2C%20writable%3A%20true%2C%20enumerable%3A%20true%2C%20configurable%3A%20true%20%7D&stage=0)

I'm sure @sebmck is aware of the two different transformation paths (duh), but this inconsistency has a few side effects. The one that's urking me is that only class properties that have a decorator on them can be known to exist without creating an instance of the class first; it's very powerful to be able to know what properties a class has pre-defined, but you can't without it being decorated.

Any thoughts @jeffmo?

For reference: [ES7 Class Properties proposal](https://gist.github.com/jeffmo/054df782c05639da2adb)

**Comment by jeffmo** [comment]
As of the last meeting, the way class properties (and their initializers) should be stored is in a descriptor-like object within another object on the prototype keyed by something like Symbol.ClassPropertyDescriptors. It's then up to both decorators and the constructor to read from this MyClass.prototype[Symbol.ClassPropertyDescriptors] object in order to enumerate and initialize each property.

I suspect Babel may have punted on actually storing properties in this reflective way just to simplify things (@sebmck can confirm).

**Comment by sebmck** [comment]
Just an oversight.

**Comment by jayphelps** [comment]
Thanks fellas!

**Comment by sebmck** [comment]
Fixed as of 5.1.0, thanks!
