### ISSUE TITLE
Spreading of empty Set results in results in array with length = 1

### ISSUE THREAD

**Issue by mattford** [babel/babel#12466]
## Bug Report

We recently updated @babel/core in our project from ^7.7.2 to ^7.12.9 and experienced some strange behaviour with the transformation of the spread operator when used with `Set`

**Current behavior**
In 7.12.9 we were able to use:
`[...new Set(Object.values({}))]` and get `[]` however since updating Babel this is now producing an array containing an empty object. I looked into the code and it appears the transformation is: `[].concat(new Set(Object.values({})))` 

- [REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABAcwE4FN1QBQzABxCgEpEBvAKEUQyhFSQG0A6VsdAd0QGUtsB5AEYArdNGYA3AIYAbEOgDO2MgF9ixALoBuCiqA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=&version=7.12.9&externalPlugins=)

**Expected behavior**
I would expect the transformation of the spread behaviour to preserve the original behaviour of the operator

**Babel Configuration (.babelrc)**
```js
{
  "presets": [
    ["@babel/preset-env", {"loose": true}],
    "@babel/preset-react"
  ],
  "plugins": [
    ["@babel/plugin-proposal-class-properties", {"loose": true}],
    [
      "@babel/plugin-transform-modules-commonjs",
      {
        "strictMode": false
      }
    ]
  ]
}
```

**Environment**

System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
  Binaries:
    Node: 10.23.0 - /usr/bin/node
    npm: 6.14.9 - /usr/bin/npm
  npmPackages:
    @babel/core: ^7.12.9 => 7.12.9
    @babel/plugin-proposal-class-properties: ^7.7.0 => 7.7.0
    @babel/polyfill: ^7.7.0 => 7.7.0
    @babel/preset-env: ^7.8.4 => 7.8.4
    @babel/preset-react: ^7.7.0 => 7.7.0
    babel-eslint: ^10.1.0 => 10.1.0
    babel-jest: ^26.2.2 => 26.2.2
    babel-loader: ^8.0.6 => 8.0.6
    eslint: ^5.16.0 => 5.16.0
    eslint-plugin-babel: ^5.3.0 => 5.3.0
    jest: ^26.1.0 => 26.1.0
    webpack: ^4.44.1 => 4.44.1

**Comment by nicolo-ribaudo** [comment]
In general, with `loose` you are opting out from spec compliance.
I'm surprised that it was working before, because I get the same output for 7.7.2: [repl](https://babeljs.io/repl/version/7.7.2#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAcwE4FN1QBQzABxCgEpEBvAKEUQyhFSQG0A6VsdAd0QGUtsB5AEYArdNGYA3AIYAbEOgDO2MgF9ixALoBuCiqA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=es2015-loose&prettier=false&targets=&version=7.7.2&externalPlugins=).

FYI, we are working on https://github.com/babel/rfcs/pull/5 which will make it possible to selectively enable "loose" only for specific features so that you know where you are telling Babel not to be spec compliant.

**Comment by mattford** [comment]
Thanks for the reply @nicolo-ribaudo, I did try with the old version in repl but was unable to get it to transform at all.

Sounds like this is a gap in my knowledge rather than a bug with Babel, so I'll close this issue.

Thanks again

**Comment by nicolo-ribaudo** [comment]
Yeah, for some reason `preset-env` with the old version of the REPL isn't working, I enabled `es2015-loose` instead that has the same behavior on ES6 features like spread.
