### ISSUE TITLE
Typescript plugin doesn't insert `export {}` like tsc does

### ISSUE THREAD

**Issue by mischnic** [babel/babel#12568]
## Bug Report

- [ ] I would like to work on a fix!

tsc makes sure that ESM files remain in ESM mode (by inserting `export {};`). Should Babel do the same?

**Input Code**

```ts
export type Key = string;
```

https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBDAnmYcDSxFwLxwM4xQCWAdgOYDcAUEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=true&targets=Node-13.1&version=7.12.12&externalPlugins=

**Expected behavior**
```ts
export {};
```

**Current behavior**

```js
// (empty)
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

`@babel/preset-typescript`

**Possible Solution**
Insert `export {};` if the input file used ESM Typescript syntax.

**Comment by BPScott** [comment]
This has just bit me also.

I would expect that because the source file is unambiguously in the esm format, then the output should be too, which means it needs an empty `export {}`.

By omiting this export webpack doesn't know if this file should be treated as esm or cjs and it seems to fall back to cjs which results in deoptimizations including stopping tree-shaking (as if it can't prove the file is in the esm format, it can't tell if it is sideEffect free so it errs on the side of caution and assumes this blank file has side effects)
