### ISSUE TITLE
Ideally, each package would have its own LICENSE file

### ISSUE THREAD

**Issue by j-buckland** [babel/babel#12624]
## Bug Report

**Current behaviour**
The individual [packages](https://github.com/babel/babel/tree/main/packages) do not have a license file

**Expected behaviour**

I would expect a LICENSE file at the root of each package ( for example, [here](https://github.com/babel/babel/tree/main/packages/babel-code-frame) ) with the MIT license and attribution.

**Possible Solution**

**Additional context**
See [previous issue](https://github.com/babel/babel/issues/11795) where this was fixed for the preset-modules

**Comment by nicolo-ribaudo** [comment]
There is a [`LICENSE`](https://github.com/babel/babel/blob/main/LICENSE) file in the repository root that applies to the whole repositories, except for packages explicitly containing a different LICENSE.

Since packages published to npm are "extracted" from this repository, they all have their own license that mirrot the license of this repo. For example, the `@babel/code-frame` package on npm (that you used as an example) has the license in its root: https://unpkg.com/browse/@babel/code-frame@7.12.11/LICENSE
