### ISSUE TITLE
Get operation on private accessor without getter should throw

### ISSUE THREAD

**Issue by mkubilayk** [babel/babel#12673]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1oDMD2GAUBKR0ATgKYAuAroQHbSkAWAlhAHQDEARmIQNzQC-KaBDLQOXbGHwIBApFWIB3OHmaYcubkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=%40babel%2Fplugin-proposal-private-methods%407.12.1)

Transpiled code doesn't throw an error in `foo()` and returns `undefined`.

**Input Code**

```js
class C {
  foo() { return this.#bar; }
  set #bar(a) {}
}

new C().foo();
```

**Expected behavior**

`new C().foo();` should throw a `TypeError`. 

- Example from Google Chrome Version 90.0.4393.0 Canary:
  ```
  VM490:2 Uncaught TypeError: '#bar' was defined without a getter
      at C.foo (<anonymous>:2:11)
      at <anonymous>:6:9
  ```
- Related `test262` test: [get-access-of-missing-private-getter.js](https://github.com/tc39/test262/blob/42bf3a9f7aed3790dc1d829f290dee033df41c5b/test/language/statements/class/elements/get-access-of-missing-private-getter.js).

**Babel Configuration:** See the REPL link

**Environment**

- Babel version(s): v7.12.12
- Node/npm version: 10.13
- OS: Using REPL
- Monorepo: Using REPL
- How you are using Babel: Using REPL

**Possible Solution**

`_classPrivateFieldGet` helper should not fallback to returning `descriptor.value` if `descriptor.get` is false-y. If `get` property exists but is `undefined`, it can throw this particular error.

**Additional context**

See `PrivateFieldGet-6.b` from [the spec](https://tc39.es/proposal-private-methods/#sec-privatefieldget):

```
PrivateFieldGet ( P, O )
    1. Assert: P is a Private Name.
    2. If O is not an object, throw a TypeError exception.
    3. If P.[[Kind]] is "field",
        a. Let entry be PrivateFieldFind(P, O).
        b. If entry is empty, throw a TypeError exception.
        c. Return entry.[[PrivateFieldValue]].
    4. Perform ? PrivateBrandCheck(O, P).
    5. If P.[[Kind]] is "method",
        a. Return P.[[Value]].
    6. Else,
        a. Assert: P.[[Kind]] is "accessor".
        b. If P does not have a [[Get]] field, throw a TypeError exception.
        c. Let getter be P.[[Get]].
        d. Return ? Call(getter, O).
```

**Comment by jridgewell** [comment]
Sigh, another difference with normal properties.

**Comment by nicolo-ribaudo** [comment]
We can inject the error in a new helper (we already have [`readOnlyError`](https://github.com/babel/babel/blob/8fcba6eb558d66b98c165c699f439117505a564a/packages/babel-helpers/src/helpers.js#L872), and we can create `writeOnlyError`): it's easy to detect this case at build time, and by doing so we don't unnecessarly increase the helper size for 99.9% of our users.

https://github.com/babel/babel/blob/8fcba6eb558d66b98c165c699f439117505a564a/packages/babel-helper-create-class-features-plugin/src/fields.js#L227-L232

Instead of checking if `isAccessor`, we can:
1. If it's a getter (`if (getId)`), we inject `_classPrivateFieldGet(...)`
1. Otherwise, if it's a setter, we inject `_writeOnlyError("#bar")`.

We need to be careful when introducing a new helper, because it will throw an error if we try to inject it with older `@babel/core` versions. Instead of just doing `file.addHelper`, we should check if `file.availableHelper("writeOnlyError")`

I'm marking this as a good first issue: it's not _easy_, but it should be self-contained enough.
@mkubilayk If you want to work on this it's yours, otherwise it's up for grab in two days!

---



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Update the test at `packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/get-only-setter` (delete `output.js` and it will be automatically generated)
1. Update the code!
1. `yarn jest private-methods` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest private-methods` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by mkubilayk** [comment]
@nicolo-ribaudo `writeOnlyError` sounds good. I don't have the bandwidth to pick this up right now so happy for someone else to take it. 🙂

**Comment by fedeci** [comment]
I'll take this, seems to be a quick fix.
