### ISSUE TITLE
babel/register doesn't work any more in v5.x

### ISSUE THREAD

**Issue by gitawego** [babel/babel#1270]
before, I use babel/register like this:
index.js
```js
require("babel/register")();
require('./test')
```
test.js
```
class Test{
}
```
then I run the app like this:
```
node --harmony index.js
```
but in v5.x, it doesn't compile es6 code to es5 any more, it throws error:
```
class Test {
^^^^^
SyntaxError: Unexpected reserved word
```
I didn't find any example about the change, could you please help me ?
thanks in advance

**Comment by sebmck** [comment]
No reason this shouldn't working. Also as per the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by resistdesign** [comment]
@sebmck I'm building a CLI and I run into this issue too, but NOT if I run `npm link` in my 'working' project for the CLI, only when I install the CLI with `-g` from the registry. Here's my code:

```node
require('babel/register')({
  stage: 0
});

// *** Command Router ***

require('./lib/command-router');
```

`./lib/command-router` is the first file I include that contains ES6 and it fails to compile it right way because of an `import` statement. Again, only if I've installed it like a normal package.

These are the deps and versions I'm using, and as far as I can tell they do get installed when installing normally:
```node
    "babel": "^5.6.3",
    "babel-core": "^5.6.4",
    "babel-loader": "^5.1.4",
```

**Comment by sebmck** [comment]
@resistdesign Have you seen #1889?

**Comment by resistdesign** [comment]
No I had not, thank you!

**Comment by gitawego** [comment]
I've just abandoned this method, using babel-node instead to load script:
```
./node_modules/.bin/babel-node --harmony index.js
```
