### ISSUE TITLE
Unable to create readonly class properties using decorators

### ISSUE THREAD

**Issue by theadam** [babel/babel#1274]
The readonly decorator example from [javascript-decorators proposal](https://github.com/wycats/javascript-decorators/blob/master/INITIALIZER_INTEROP.md#harmony) currently does not work.  When the property is initialized in the constructor, an exception is thrown since the property is read-only.

[Example](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=function%20readonly%28target%2C%20name%2C%20desc%29%20{%0A%20%20desc.writable%20%3D%20false%3B%0A%20%20return%20desc%3B%0A}%0A%0Aclass%20Person%20{%0A%20%20%40readonly%0A%20%20born%20%3D%20new%20Date%28%29%3B%0A}%0A%0A%2F%2F%20TypeError%3A%20%22born%22%20is%20read-only%0Anew%20Person%28%29%3B%0A)

**Comment by bucaran** [comment]
What is the expected behavior here?

If a property is `readonly` should it still be possible to modify it via the constructor?

**Comment by bucaran** [comment]
I looked into this in more depth and here is what I got:

Let's start with the ES6:

```js
function readonly(target, name, desc) {
  desc.writable = false;
  return desc;
}

class Person {
  @readonly
  born = new Date();
}

console.log(Object.getPrototypeOf(new Person()))
```

And here is the generated ES5:

```js
"use strict";

var _classCallCheck = function(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
};

var _createDecoratedClass = (function() {
    function defineProperties(target, descriptors, initializers) {
        for (var i = 0; i < descriptors.length; i++) {
            var descriptor = descriptors[i];
            var decorators = descriptor.decorators;
            var key = descriptor.key;
            delete descriptor.key;
            delete descriptor.decorators;
            descriptor.enumerable = descriptor.enumerable || false;
            descriptor.configurable = true;
            if ("value" in descriptor || descriptor.initializer) descriptor.writable = true;
            if (decorators) {
                for (var f = 0; f < decorators.length; f++) {
                    var decorator = decorators[f];
                    if (typeof decorator === "function") {
                        descriptor = decorator(target, key, descriptor) || descriptor;
                    } else {
                        throw new TypeError("The decorator for method " + descriptor.key + " is of the invalid type " + typeof decorator);
                    }
                }
                if (initializers) initializers[key] = descriptor.initializer;
            }
            Object.defineProperty(target, key, descriptor);
        }
    }
    return function(Constructor, protoProps, staticProps, protoInitializers, staticInitializers) {
        if (protoProps) defineProperties(Constructor.prototype, protoProps, protoInitializers);
        if (staticProps) defineProperties(Constructor, staticProps, staticInitializers);
        return Constructor;
    };
})();

function readonly(target, name, desc) {
    desc.writable = false;
    return desc;
}

var Person = (function() {
    var _instanceInitializers = {};

    function Person() {
        _classCallCheck(this, Person);

        this.born = _instanceInitializers.born.call(this);
    }

    _createDecoratedClass(Person, [{
        key: "born",
        decorators: [readonly],
        initializer: function() {
            return new Date();
        },
        enumerable: true,
    }], null, _instanceInitializers);

    return Person;
})();


console.log(Object.getPrototypeOf(new Person()))

```

The generated ES5 is quite a mouthful, but after you go through it a few times and make sense out of it, here is the culprit `this.born = _instanceInitializers.born.call(this);`. 

When you create a new instance of `Person` using `new Person()` and `this.born` is accessed in the constructor, the property `born` has already being defined as `writeable = false` which causes the runtime error. This is exactly what we want if we were to `person.born = /* trying to set it again */`, but certainly not the expected behavior as we would like to have a constructor initialize the value first.

One way could be to compute the initializer when the `decoratedClass` is created and remove the `this.born = ...` in the constructor:

```js
    var val = function() {
            return new Date();
        }()

    _createDecoratedClass(Person, [{
        key: "born",
        value: val,
        decorators: [readonly],
        initializer: function() {
            return new Date();
        },
        enumerable: true,
    }], null, _instanceInitializers);
```

But this is too limiting, also Babel would have to generated rather an array of `vals` for each of _descriptor_ (in this case there is only one, but there could be many).

Here is another solution:

```js
...
                for (var f = 0; f < decorators.length; f++) {
                    var decorator = decorators[f];
                    if (typeof decorator === "function") {

                        if (descriptor.initializer) {
                            descriptor.value = descriptor.initializer()
                        }

...
```

And then either remove the `this.born = ...` inside the constructor or use a `try..catch` block;

```js
        try {
            this.born = _instanceInitializers.born.call(this);
        } catch (e) {

        }
```

**Comment by sebmck** [comment]
Closing in favor of #1277.
