### ISSUE TITLE
How is babby formed? (Babbel Internals Guide)

### ISSUE THREAD

**Issue by bucaran** [babel/babel#1278]
`CONTRIBUTING.md` already has some important information, but it would be really useful for newcomers to have a guide of what to look out for / details / information about the project internals / structure. 

Like it may not be obvious for a beginner that Babel is actually written in ES6 and mostly resides under `lib/` and transpiles to `src/`, or an overview of what (and where) modules and dependencies are used in the project (going through `package.json` is OK, but it could be friendlier).

Other internals documentation, whether that is more comments or more `.md`s is fine.

__[.](https://www.youtube.com/watch?v=Ll-lia-FEIY)__

**Comment by sebmck** [comment]
> Like it may not be obvious for a beginner that Babel is actually written in ES6 and mostly resides under `lib/` and transpiles to `src/`

You mean the other way around :stuck_out_tongue_winking_eye: 

> or an overview of what (and where) modules and dependencies are used in the project (going through `package.json` is OK, but it could be friendlier).

Not sure how knowing the Babel uses a bit of lodash etc would be relevant to contributors?

I recently gave [this](https://speakerdeck.com/sebmck/babel-facebook-talk) talk that goes over some of the Babel internals that you may find useful.

**Comment by bucaran** [comment]
Opps, yes, I meant resides in `src/` and transpiles to `lib/`, point is Babel itself it's written in ES6 which is so cool!

It's only useful if you say ___why___. In the case of `lodash` is arguably pretty obvious, but in the case of `core-js`, `fs-readdir-recursive` or `estraverse` it is not quite obvious.

You know JS projects often include more dependencies than the average human brain can keep track of :grinning:  and while using small modules to orchestrate a project is the right thing to do, it's difficult to navigate across the sea of dependencies and see what each one does. (That's why I wrote [this safari plugin](http://github.com/bucaran/node-navi) :electric_plug:), but that does not help understanding _intent_ right?.

It's also tough when each module have their own style of documentation (assuming they have docs in the first place).

Anyhow, explaining why you used this here and there helps understand and get contributors up and running in less time.

Thanks for the link!

**Comment by sebmck** [comment]
I'm in the process of moving overseas at the moment so I'm a bit stretched for time which is also why I haven't explained what's required for #1277 so hopefully I'll be able to get some time to produce some quality internal docs once the dust has settled :stuck_out_tongue: 

As for the actual modules that are used, I'll quickly run through them now:

 - `ast-types` This is required to monkeypatch `regenerator`s AST definitions. Otherwise it'll throw up. I **really really** hate that this has to be done at all but there's no other way. This is done in [patch.js](https://github.com/babel/babel/blob/master/src/babel/patch.js).
 - `chalk` This is used for terminal color highlighting for syntax errors.
 - `convert-source-map` Turns a source map object into a comment etc.
 - `core-js` Used for the polyfill.
 - `debug` Used to output debugging information when `NODE_DEBUG` is set to `babel`.
 - `detect-indent` This is used in the code generator so it can infer indentation.
 - `estraverse` The only method on this is `attachComments`. I'd like to implement our own comment attachment algorithm eventually though.
 - `esutils` Various ES related utilities. Check whether something is a keyword etc.
 - `fs-readdir-recursive` Recursively search a directory for.
 - `globals` A list of JavaScript global variables. This is used by the scope tracking to check for colliding variables.
 - `is-integer` Checks if something is a.
 - `js-tokens` This is used to get tokens for syntax error highlighting.
 - `leven` A levenstein algorithm to determine how close a word is to another. This is used to offer suggestions when using the `utility.undeclaredVariableCheck` transformer.
 - `line-numbers` Used to produce the code frames in syntax errors.
 - `lodash` Used for various utilities.
 - `minimatch` This is used to match glob-style ignore/only filters.
 - `output-file-sync` Synchronously writes a file and create its ancestor directories if needed.
 - `path-is-absolute` Checks if a path is absolute. `C:\foo` and `\foo` are considered absolute.
 - `regenerator` This is used to transform generators/async functions.
 - `regexpu` Used to transform unicode regex patterns.
 - `repeating` Repeats a string.
 - `shebang-regex` Literally just a regex that matches shebangs.
 - `slash` Normalises path separators.
 - `source-map` Generates sourcemaps.
 - `source-map-support` Adds source map support to `babel-node`/`babel/register`.
 - `strip-json-comments` Remove comments from a JSON string. This is used for `.babelrc` files.
 - `to-fast-properties` A V8 trick to put an object into fast properties mode.
 - `trim-right` Trims the rightside whitespace.
 - `user-home` Gets the users home directory. This is used to resolve the `babel-node`/`babel/register` cache.

**Comment by bucaran** [comment]
Great @sebmck Thanks! :+1:

**Comment by sebmck** [comment]
No problem :smile: Also PRs fleshing out `CONTRIBUTING.md`, even if it's just adding blank sections would be **extremely** appreciated.

**Comment by bucaran** [comment]
:+1:

**Comment by bucaran** [comment]
:+1:

**Comment by amasad** [comment]
>ast-types This is required to monkeypatch regenerators AST definitions. Otherwise it'll throw up. I really really hate that this has to be done at all but there's no other way. This is done in patch.js.

There is a PR on ast-types that might fix this: https://github.com/benjamn/ast-types/pull/112

**Comment by sebmck** [comment]
Closing in favor of #1347.
