### ISSUE TITLE
TSParameterProperty produces class properties assignment at end of constructor body

### ISSUE THREAD

**Issue by alexandre-cai** [babel/babel#12832]
## Bug Report
... which is different than what `tsc` produces.

- [ ] I would like to work on a fix!

**Current behavior**
Given the following code:
```ts
class Test {
    constructor(private foo: object) { 
    }
    a = {
        b: this.foo
    }
}
```

`tsc` [produces](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=7&pc=2#code/MYGwhgzhAEAqCmEAu0DeAoaXrAPYDtkAnAV2CVyIAoAHIgSwDcwl5oAzXXALmlwCMAVvHIBKNNEzYAvlKxhoAXjRzsWfryQALehAB0nXKtnSgA)

```js
"use strict";
class Test {
    constructor(foo) {
        this.foo = foo;
        this.a = {
            b: this.foo
        };
    }
}
```

but Babel [produces](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=true&code_lz=MYGwhgzhAEAqCmEAu0DeAoaXrAPYDtkAnAV2CVyIAoAHIgSwDcwl5oAzXXALmlwCMAVvHIBKNNEzYAvlKxhoAXjRzsWfryQALehAB0nXKtnSgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.12.18&externalPlugins=%40babel%2Fplugin-transform-runtime%407.12.17)

```js
import _defineProperty from "@babel/runtime/helpers/defineProperty";

class Test {
  constructor(foo) {
    _defineProperty(this, "a", {
      b: this.foo
    });

    this.foo = foo;
  }
}

```
**Environment**
REPL: Enabled `preset-typescript` and `stage-2`.
```

```
- Babel version(s): 7.12.18
- Node/npm version: It’s reproducible in REPL
- OS: N/A
- Monorepo: N/A
- How you are using Babel: N/A

**Possible Solution**

**Additional context**

**Comment by nicolo-ribaudo** [comment]
Note that the current Babel out matches what TS does when targeting ESNext:
https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99#code/MYGwhgzhAEAqCmEAu0DeAoaXrAPYDtkAnAV2CVyIAoAHIgSwDcwl5oAzXXALmnxIC2AI3hEAlGmiZsAX2lYS+ACbx20ALwcuASQgBVZavr54SqkgAW9CGIDc6OenaLy9Alty6DK9sdNVcIQArXjB8AE8JDGxoIngkEiJ8aECggDpOXA11TUUfPyV7RzAQUSQqEwB3OERygCYxNLzVOyA

If you run the output code it will alert `true`, but if you change the target to ES2015 it will alert `false`. I suggest opening an issue in the TS repository to ask which is the expected behavior.

**Comment by nicolo-ribaudo** [comment]
Oh it looks like they already know: https://github.com/microsoft/TypeScript/pull/36425

Since the TypeScript behaviour when using JavaScript class fields and targeting modern code matches Babel, I don't think we should change what Babel does and code relying on the old TS behavior should migrate to the new TS behavior.
