### ISSUE TITLE
@babel/preset-env 7.13.* breaks regenerateRuntime

### ISSUE THREAD

**Issue by broksonic21** [babel/babel#12880]
## Bug Report

We've been working fine on 7.12.17, but tried updating to 7.13.5 - no breaking changes are mentioned and this is the only change we did. It errors out, complaining about regeneratorRuntime is not defined.

We are using `"browserslist": "last 2 Chrome versions"` in package.json, with this babelrc:

```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

**Current behavior**

Previous with 7.12.7, no issues seen.

**Expected behavior**

7.13.5 should continue to work

**Environment**

(Before - Working):

```
 System:
    OS: macOS 11.2.1
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/Cellar/node/15.2.1/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  npmPackages:
    @babel/plugin-proposal-class-properties: ^7.13.0 => 7.13.0
    @babel/plugin-proposal-optional-chaining: ^7.13.0 => 7.13.0
    @babel/preset-env: ^7.12.17 => 7.12.17
    @babel/preset-react: ^7.12.13 => 7.12.13
    @babel/preset-typescript: ^7.13.0 => 7.13.0
    babel-eslint: ^10.1.0 => 10.1.0
    babel-loader: ^8.2.2 => 8.2.2
    eslint: ^7.20.0 => 7.20.0
    jest: ^26.6.3 => 26.6.3
    webpack: ^5.24.0 => 5.24.0
```

(After - broken):

```
 System:
    OS: macOS 11.2.1
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/Cellar/node/15.2.1/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  npmPackages:
    @babel/plugin-proposal-class-properties: ^7.13.0 => 7.13.0
    @babel/plugin-proposal-optional-chaining: ^7.13.0 => 7.13.0
    @babel/preset-env: ^7.13.5 => 7.13.5
    @babel/preset-react: ^7.12.13 => 7.12.13
    @babel/preset-typescript: ^7.13.0 => 7.13.0
    babel-eslint: ^10.1.0 => 10.1.0
    babel-loader: ^8.2.2 => 8.2.2
    eslint: ^7.20.0 => 7.20.0
    jest: ^26.6.3 => 26.6.3
    webpack: ^5.24.0 => 5.24.0
```

**Comment by broksonic21** [comment]
7.13.0 also shows same issue as 7.13.5. 7.12.7 is fine

**Comment by nicolo-ribaudo** [comment]
Could you share a repository I can run to reproduce the bug?

**Comment by Ann40a** [comment]
I have similar issue with `regenerateRuntime` and the fact that babel started to ignore `.browserslistrc`.

As I understand it fails because of this line: https://github.com/babel/babel/blob/main/packages/babel-preset-env/src/index.js#L301
Babel needs your current working directory to resolve the browserslist. But when you don't pass config path explicitly it resolves it automatically and places in `configPath` variable. For some reason the condition uses `opts.configPath` instead of `configPath` and it is empty.

So as a temporary workaround just pass `configPath: process.cwd()` to `preset-env` options. At least this helped for standalone `.browserslistrc`, I believe it should help for `package.json` too.

**Comment by nicolo-ribaudo** [comment]
@Ann40a The goal of that line of code you linked should be to preserve the pre-7.13.0 behavior. Could you provide an example repository where Babel 7.12 loaded the `.browserslistrc` file but Babel 7.13 ignores it? :pray:

**Comment by Ann40a** [comment]
@nicolo-ribaudo you are right, the issue is more complex than it seemed initially. The code should have collected targets even before it hitted that condition with `opts.configPath`. I've created a repo with reproduction, please see readme there: https://github.com/Ann40a/babel-preset-env-12880.

Also, for those who is searching for a solution, the second possible fix of this bug can be removing lock file and `node_modules` from the project and regenerating them from scratch. This solution isn't the same reliable as the solution with explicit `configPath` mentioned above, but it is cleaner, because it doesn't leave any artifacts in your codebase.

**Comment by broksonic21** [comment]
@Ann40a thanks - this also explains my repro, and I was finally able to narrow it down

If you see https://github.com/broksonic21/babel_12880_repro - and run `npm run build` you can see via preset-env `debug:true` that the browser list is read from the package.json. That's using preset-env 7.12.7, and if you look at the package-lock.json: 7.12.16 for @babel/core. But, in this example (and in the private repo we ran into this on), we inadvertently never had @babel/core listed as an actual dependency - it worked because @stylelint/postcss-css-in-js has a dependency on @babel/core, so it was never added directly.

```
> babeltest@0.0.0 build /Users/aaronaverbuch/git/babeltest
> babel src

@babel/preset-env: `DEBUG` option

Using targets:
{
  "chrome": "84"
}
```

Through upgrading preset-env to 7.13.* (we use renovatebot for this), we ran into the incompatibility I originally filed the ticket about. You can see that here: https://github.com/broksonic21/babel_12880_repro/tree/upgrade_broken - where we upgraded preset-env to 7.13.8. But @babel/core stayed on a 7.12.* version in package-lock.json as it wasn't updated.

Now you get:
```
> babeltest@0.0.0 build /Users/aaronaverbuch/git/babeltest
> babel src

@babel/preset-env: `DEBUG` option

Using targets:
{}
```

So there are 3 options to fix this:
* The right fix - we should just add @babel/core as a real devDependency (not implied) and update it like others. We'll do that.
* Package-lock.json recreate so it grabs it later. While it works, it won't clean up future.
* Adding the browser list to babelrc directly and duplicating. That's what I did until I realized the cause and the right fix here.

**Comment by nicolo-ribaudo** [comment]
I'm glad that the workaround is easy (just update `@babel/core`, but I'll look for a fix.
