### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mouse-007** [babel/babel#12887]
![image](https://user-images.githubusercontent.com/26134415/108982224-87464c00-76c8-11eb-892f-9e3849cca7fb.png)

**Comment by nicolo-ribaudo** [comment]
We don't have enough info to understand what is causing the error in your case, but I'm almost 100% sure that it's the same as https://github.com/babel/babel/issues/12888#issuecomment-785016029 or https://github.com/babel/babel/issues/12888#issuecomment-785101019.

Please exclude `.mjs` files from `url-loader` or `file-loader` in your webpack configuration, because they shouldn't be loaded as strings but as normal JavaScript files (which is the default webpack behavior)
