### ISSUE TITLE
`_index.mjs` may not be resolved for some reason in legacy projects

### ISSUE THREAD

**Issue by fengxinming** [babel/babel#12902]
`_index.mjs` of @babel/runtime@7.13.x may not be resolved for some reason in legacy projects, I would like to recommend babel team to rename `_index.mjs` to `index.es.js`, Thanks!

**Comment by afc163** [comment]
https://github.com/babel/babel/issues/12861

**Comment by fengxinming** [comment]
@afc163 I can not change webpack config for some legacy reason，I wish everything is going well like 7.12.18。

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/issues/12900 shows well what is the problem.

I'm sorry that this update broke your project, but it's a problem in you webpack configuration.
I have been trying to think about a fix, but if you need this to be resolved soon you should fix it in your webpack config.

In the meantime, you could pin `@babel/runtime` to ~7.12.0.

**Comment by fengxinming** [comment]
@nicolo-ribaudo 
```js
{
  "resolutions": {
    "@babel/runtime": "7.12.18",
    "@babel/runtime-corejs2": "7.12.18",
    "@babel/runtime-corejs3": "7.12.18"
  },
}
```
I have locked versions by this way, and the problem is not what you think, and webpack configuration can not be changed in our projects, for some legacy reason those configuration be wrapped like `react-scripts`, actually those `@babel/runtime` packages are from dependencies of some third party packages, our projects still use babel6.

**Comment by JLHwung** [comment]
The `.mjs` is not respected in `react-scripts` 0.9

https://github.com/facebook/create-react-app/blob/144f03b114f791f66a7db68ae8bc644c8c30a227/packages/react-scripts/config/webpack.config.prod.js#L124-L157

However it was fixed in `react-scripts` some versions between 1.0.0 and 1.0.17:

https://github.com/facebook/create-react-app/blob/4b55193f0ad479f26b0f5e153bb4b152a1ee03e7/packages/react-scripts/config/webpack.config.prod.js#L133-L182

All of the versions mentioned above are 4 years old, when Node.js 6.13 even does not exist. Babel/runtime 7.13 does not support such config, consider upgrade `react-scripts` to a modern version which correctly handle `.mjs`.

**Comment by fengxinming** [comment]
@JLHwung Thank you for your suggestion that is really useful,  but I did not use `react-scripts` in our legacy projects, my last comment means our legacy build tool kind of like `react-scripts`, there is not a webpack configuration file in the project. I believe the babel team will find a best way to solve it.

**Comment by nicolo-ribaudo** [comment]
Can you share a repository with a similar setup that shows the bug? It's hard to reproduce it otherwise.

**Comment by fengxinming** [comment]
I have known the reason that `_index.mjs` matched the `file-loader` rule, I just can not directly change the webpack configuration, However thanks to @nicolo-ribaudo and @JLHwung
