### ISSUE TITLE
[types] `range` is missing in `BaseNode`

### ISSUE THREAD

**Issue by JounQin** [babel/babel#13027]
## Bug Report

- [x] I would like to work on a fix!

https://github.com/babel/babel/blob/main/packages/babel-types/src/ast-types/generated/index.ts#L34-L43

**Comment by hzoo** [comment]
Yeah feel free to add, generator file is at https://github.com/babel/babel/blob/b360d8d6141984f2912da89349c4689501ba005a/packages/babel-types/scripts/generators/ast-types.js#L38-L47

I'd be  optional since it requires a config opt to the parser, `ranges`. https://github.com/babel/babel/blob/b360d8d6141984f2912da89349c4689501ba005a/packages/babel-parser/src/parser/node.js#L16
