### ISSUE TITLE
[Bug]: Parser can't parse "for await (async of []);"

### ISSUE THREAD

**Issue by Zalathar** [babel/babel#13235]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
async function f() {
    for await (async of []);
}
```

[Babel REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsLwBQEoYDeAUDPOgE4zADuwqyM2oks6cMA2gLq4DcRAXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=&prettier=false&targets=&version=7.14.0&externalPlugins=)

### Configuration

```json
{}
```

### Current and expected behavior

Expected:
- The parser parses a `for await` statement with the identifier `async` as its left-hand-side.

Actual:
```
/repl.js: Unexpected token, expected "=>" (2:22)

  1 | async function f() {
> 2 |   for await (async of []);
    |                       ^
  3 | }
```

### Environment

- Babel 7.14.0
- Current Babel main (b99c4f06d433b04d3f3308838d494d9e50158ea0)

### Possible solution

After `for await (` not followed by `var`/`let`/`const`, the ECMAScript grammar requires a *LeftHandExpression* followed by `of`.

Babel instead parses an arbitrary expression, and then checks that the expression can be converted to a left-hand-side. This *mostly* works, except that when the next two tokens are `async of` the expression parser sees them as the start of an async arrow function with parameter `of` (which is not a *LeftHandExpression*).

The solution I currently have in mind is to explicitly look ahead for `async of` after the  `for await (`, and parse the left-hand-side as an identifier instead of an expression. That will fix this edge-case, and the existing approach of parsing an expression should remain viable in all other cases for now.

### Additional context

https://github.com/babel/babel/pull/13208
https://github.com/prettier/prettier/pull/10781#pullrequestreview-648146981

**Comment by JLHwung** [comment]
The error 'Unexpected token, expected "=>"' is thrown because Babel is parsing `async of` as the start of an UnaryAsyncArrowExpression `async of => {}`:

https://github.com/babel/babel/blob/b99c4f06d433b04d3f3308838d494d9e50158ea0/packages/babel-parser/src/parser/expression.js#L1229

which is called in

https://github.com/babel/babel/blob/b99c4f06d433b04d3f3308838d494d9e50158ea0/packages/babel-parser/src/parser/expression.js#L1035

We can guard it with an extra `=>` lookahead so the `async` here will be eventually returned as an Identifier. We can either check if `lookahead().type` is `tt.arrow`, like V8 [does](https://source.chromium.org/chromium/chromium/src/+/main:v8/src/parsing/parser-base.h;l=1843;drc=fdc0284238bd2838555ccb39052790e240017890?q=ForOfAsync&ss=chromium%2Fchromium%2Fsrc), or we simply check if `lookaheadCharCode()` is `=`, I guess the latter approach is sufficient. It is also more performant than the former approach because it does not clone the tokenizer state, since `async var => {}` is more popular than `(async of [])`, so the lookahead will be executed with high probability.

Note that unlike for await, `for (async of [])` is forbidden . Although Babel current throws, it is thrown because Babel is parsing `async of []` as arrow function like I mentioned before. When we add the extra lookahead, we should specifically throw for `for (async of [])`.
