### ISSUE TITLE
[Bug]: Putting console.log into babel.config.js is breaking typescript auto suggest in vscode

### ISSUE THREAD

**Issue by inspiraller** [babel/babel#13315]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

See example repo to demonstrate this problem - 
https://github.com/inspiraller/vscode-emmet

### Configuration file name

babel.config.js

### Configuration

```js
console.log(1); // <- this console log is breaking vscode emmet auto suggest.
module.exports = {
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ]
};
```

### Current and expected behavior

console.log(1); // <- this console log is breaking vscode emmet auto suggest.
module.exports = {
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ]
};

### Environment

    "@babel/core": "^7.14.2",
    "@babel/preset-env": "^7.14.2",
    "@babel/preset-react": "^7.13.13",

**Comment by nicolo-ribaudo** [comment]
This seems to be a big either with vscode itself or with a vscode plugin you are using.

If you can reproduce this with all the plugins disabled please report it in the vscode repo; otherwise report it to the relevant vscode plugin repository (you'll need to enable them one by one to figure out which one is crashing).

**Comment by inspiraller** [comment]
@nicolo-ribaudo Thankyou. Yes apologies. Its a strange bug. It appeared with stylelint. I have posted the bug there.
