### ISSUE TITLE
[Bug]: @babel/eslint-parser doesn't work with an ESM babel config file

### ISSUE THREAD

**Issue by GitGangGuy** [babel/babel#13352]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

`.eslintrc.json`:
```json
{
  "env": {
    "shared-node-browser": true,
    "es2021": true
  },
  "extends": ["eslint:recommended", "airbnb-base", "prettier"],
  "overrides": [
    // [...]
  ],
  "parser": "@babel/eslint-parser",
  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "impliedStrict": true
    }
  },
  "plugins": ["@babel", "..."],
  "root": true,
  "rules": {
    // [...]
  }
}
```

### Configuration file name

babel.config.js

### Configuration

`babel.config.js` (in a `type=module` project):
```js
export default {
  targets: {
    esmodules: true,
  },
  sourceType: 'module',
  babelrc: false,
  presets: [
    // [...]
  ],
  plugins: [
    // [...]
  ],
};
```

### Current and expected behavior

**Expected behavior**: `@babel/eslint-parser` successfully reads in my ESM config file
**Actual behavior**: Eslint throws an error complaining about the babel config file not being imported asynchronously (`Parsing error: <path>/babel.config.js: Error while loading config - You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously`)

### Environment

- **OS:** Arch GNU/Linux with kernel version 5.12 (rolling release)
- **Package manager**: [pnpm](https://github.com/pnpm/pnpm) (6.4.0) via node v16.2.0
- **Monorepo**: No (single `babel.config.js` file in root)
- **Packages**:
```yml
@babel/cli: 7.13.16
@babel/core: 7.14.2
@babel/eslint-parser: 7.14.2
@babel/eslint-plugin: 7.13.16
eslint: 7.26.0
```

**Comment by nicolo-ribaudo** [comment]
This is a know limitation: ESLint doesn't support asynchronous parsers, so `@babe/eslint-parser` cannot load ESM config files (because ESM can only be loaded asynchronously). Ref: https://github.com/eslint/eslint/discussions/14295#discussioncomment-572517.

We just merged an experimental `@babel/eslint-parser` implementation that will allow us to convert Babel to ESM in Babel 8 while still loading it synchronously in `@babel/eslint-parser` (https://github.com/babel/babel/pull/13199). However, it has some drawbacks: for example you cannot pass a function Babel plugin to `@babel/eslint-parser` without moving it to a Babel config file.

We could add an option in the next minor to allow using that new experimental implementation, it would also help ensuring that it's stable before the Babel 8 release.

**Comment by GitGangGuy** [comment]
@nicolo-ribaudo Sounds interesting! Perhaps you could add a warning about the drawbacks with `@babel/eslint-parser`/ESLint only supporting synchronous parsers once Babel 8 arrives. Until then, I'd be happy to try out the experimental implementation (hoping it will solve my problem). When will it be available? :smile:
