### ISSUE TITLE
[Bug]: `async({ foo33 = 1 })` is parsed without errors

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#13392]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
async({ foo33 = 1 });
```

### Configuration

Default parser config

### Current and expected behavior

`foo33 = 1` is parsed as an `ObjectProperty` whose value is an `AssignmentPattern`. It should throw, since objects cannot have property initializers with `=`.

### Environment

Babel 7.14.4

### Additional context

Reported at https://twitter.com/buzyescayadev/status/1398526884955058181

**Comment by tony-go** [comment]
Hey @nicolo-ribaudo 

As the issue #13399 was just taken. 

Maybe I could give a try on this one ?

**Comment by JLHwung** [comment]
Another related issue:
```js
// should throw duplicate proto keys
async({ __proto__: x, __proto__: y })
```

<details>
  <summary>Spoiler, expand when you need help!</summary>

Babel tracks the pattern `foo33 = 1` in `refExpressionsErrors.shorthandAssign`:

https://github.com/babel/babel/blob/0b29b5c2c03023c6cfedb3fc4b7a97415308bfea/packages/babel-parser/src/parser/expression.js#L1953-L1955

However, this error is not thrown as it should have, because when we don't see an arrow after `async ()`, 

https://github.com/babel/babel/blob/0b29b5c2c03023c6cfedb3fc4b7a97415308bfea/packages/babel-parser/src/parser/expression.js#L804-L806

we lost the access to `refExpressionErrors`, which is created when parsing every call expression arguments:

https://github.com/babel/babel/blob/0b29b5c2c03023c6cfedb3fc4b7a97415308bfea/packages/babel-parser/src/parser/expression.js#L934

We can create the `refExpressionErrors` here 

https://github.com/babel/babel/blob/0b29b5c2c03023c6cfedb3fc4b7a97415308bfea/packages/babel-parser/src/parser/expression.js#L785-L791

and pass down the `refExpressionErros` to `parseCallExpressionArguments`. After we are sure `async()` is a call expression, we should check refExpressionErrors like we did elsewhere. An example is parsing left hand-side expression before `=`:

https://github.com/babel/babel/blob/0b29b5c2c03023c6cfedb3fc4b7a97415308bfea/packages/babel-parser/src/parser/expression.js#L1530

</details>

**Comment by tony-go** [comment]
Hi 👋 guys

I'm hacking around the parser and try to understand the flow for our bug case.

Thanks a lot @JLHwung for your pointers, it helps a lot.

I'll keep you informed.

**Comment by existentialism** [comment]
@tony-go hit us up on slack if you have any questions!

**Comment by tony-go** [comment]
Hey @JLHwung I tried `async({ __proto__: x, __proto__: y })` with the [repl from my pull request](https://babeljs.io/repl/build/46636/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=IYZwngdgxgFA3gAgPpIA4CcD2AXTKBcCAHgDTJpa4EJgIC-AlEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.14.4%2Bpr.13410&externalPlugins=).

It seems to work there, but in the parser test I add a case and I got:

```bash
Expected non-recoverable error message: Redefinition of __proto__ property. (1:22). But instead parsing recovered from errors: [
      {
        "loc": {
          "line": 1,
          "column": 22
        },
        "pos": 22,
        "code": "BABEL_PARSER_SYNTAX_ERROR",
        "reasonCode": "DuplicateProto"
      }
    ]
```

Do you have an idea about why ? (I'll dig it anyway)

**Comment by nicolo-ribaudo** [comment]
It's because we already have the tracking logic for non-async arrow functions, and you are making the parser use the same existing logic also for async arrows.

**Comment by JLHwung** [comment]
> Hey @JLHwung I tried `async({ __proto__: x, __proto__: y })` with the [repl from my pull request](https://babeljs.io/repl/build/46636/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=IYZwngdgxgFA3gAgPpIA4CcD2AXTKBcCAHgDTJpa4EJgIC-AlEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.14.4%2Bpr.13410&externalPlugins=).
> 
> It seems to work there, but in the parser test I add a case and I got:
> 
> ```shell
> Expected non-recoverable error message: Redefinition of __proto__ property. (1:22). But instead parsing recovered from errors: [
>       {
>         "loc": {
>           "line": 1,
>           "column": 22
>         },
>         "pos": 22,
>         "code": "BABEL_PARSER_SYNTAX_ERROR",
>         "reasonCode": "DuplicateProto"
>       }
>     ]
> ```
> 
> Do you have an idea about why ? (I'll dig it anyway)

It should throw, which means you have fixed this issue. The error comes from the fact we are enabling `errorRecovery` for all the parser tests so instead of an error is thrown, Babel parser will recovery from the errors, and record the errors to the AST.

You can try removing `options.json` and re-run the test, the fixture runner will automatically generate `output.json`.

**Comment by tony-go** [comment]
Thanks a lot guys 👏 

I just pushed the new test case ^^

I probably understand that our update allows to catch this error, my misunderstanding was more on the fact in one case we use:
- this.checkExpressionErrors that'll throw
- this.raise (If I understand well 😆 )

Maybe do you guys have an idea ?

**Comment by nicolo-ribaudo** [comment]
Usually use use `this.raise`, which immediately reports the error. However, when parsing `async ({ foo33 = 1 })` there is a problem: when we find `=`, we don't know yet if it's an error or not. `async ({ foo33 = 1 }) => {}` is valid, while `async ({ foo33 = 1 });` is not. For this reason, instead of using `.raise` we record them in `ExpressionErrors` and then, when we are sure that it's not an async function, we throw the errors we recorded.

**Comment by tony-go** [comment]
Hi @nicolo-ribaudo 👋 

Hope you're doing right ^^

I fully understand why we use a ref (`ExpressionErrors`) to store the potential error and raise it only if it's necessary.

But at the end of the day `this.checkExpressionErrors` will:

```js
if (shorthandAssign >= 0) {
  this.unexpected(shorthandAssign); // will throw something
}
if (doubleProto >= 0) {
  this.raise(doubleProto, Errors.DuplicateProto); // will return something
}
```

I think that the REPL handle both of them similarly. But it seems ambiguous for me. But I probably miss something, let me know in case. 

Note: So sorry if my questions are a bit boring 🙏 - I'm just tryin to better understand the code base. Thanks a lot for your time  ^^

**Comment by nicolo-ribaudo** [comment]
Your question is a really good one, actually :wink: 

`@babel/parser` has an `errorReovery` option (which is enabled by default in tests) that makes it push some errors to an `ast.errors` array. We don't push all of these errors because it's not always easy to build a Babel AST after some invalid syntax.

For example, we _could_ parse `({ foo = 2 });` as if it was `({ foo: 2 });` (so we could recover by replacing `=` with `:`), but then what would we do for `({ foo: { x: 3 } = {} });`?
1. When it would be hard to create a valid AST that _probably_ reflects the user intention, we still throw (`this.unexpected()`)
2. When it's easy to still create an AST, we use `this.raise` and continue parsing.

In general, "2" is more similar to linting errors (valid syntax but which is disallowed by the spec via [Early Errors](https://tc39.es/ecma262/#early-error)), while "1" are actual syntax errors (tokens that aren't allowed in that position).

**Comment by tony-go** [comment]
Thanks a lot for this level of detail @nicolo-ribaudo ^^

**Comment by nicolo-ribaudo** [comment]
Thank you for the PR!
