### ISSUE TITLE
[Bug]: Destructuring empty string to array causes runtime error

### ISSUE THREAD

**Issue by xiaody** [babel/babel#13421]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
let [a] = '';
console.log(a);
```

### Current and expected behavior

[repl](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBA2ghguhAvBA5CgUAYwPYDsDO2oAdMNgOYAUMAlEA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=true&targets=Electron-1.8%252CNode-10.13&version=7.14.4&externalPlugins=)

#### current
VM104:58 Uncaught TypeError: _i.call is not a function
    at _iterableToArrayLimit (<anonymous>:47:18)
    at _slicedToArray (<anonymous>:6:5)
    at <anonymous>:69:11

#### expected
Console outputs undefined.

### Environment

  System:
    OS: macOS 11.3.1
  Binaries:
    Node: 14.16.0 - ~/.nvm/current/bin/node
    Yarn: 1.22.10 - ~/.nvm/current/bin/yarn
    npm: 6.14.11 - ~/.nvm/current/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.10
  npmPackages:
    @babel/core: ^7.13.8 => 7.14.3
    babel-loader: ^8.2.2 => 8.2.2
    eslint: ^7.10.0 => 7.27.0

**Comment by nicolo-ribaudo** [comment]
This is really strange. `_i` is `""[Symbol.iterator]`. It _should_ be a function (and thus have a `.call` method) or `undefined` (in old browsers)`.

Can you try adding a `console.log(_i)` in `_iterableToArrayLimit`, right after the variable declaration?

```js
function _iterableToArrayLimit(arr, i) {
  var _i =
    arr &&
    ((typeof Symbol !== "undefined" && arr[Symbol.iterator]) ||
      arr["@@iterator"]);
  console.log("_i is", _i);
  if (_i == null) return;
  var _arr = [];
  var _n = true;
  var _d = false;
  var _s, _e;
  try {
    for (_i = _i.call(arr); !(_n = (_s = _i.next()).done); _n = true) {
      _arr.push(_s.value);
      if (i && _arr.length === i) break;
    }
  } catch (err) {
    _d = true;
    _e = err;
  } finally {
    try {
      if (!_n && _i["return"] != null) _i["return"]();
    } finally {
      if (_d) throw _e;
    }
  }
  return _arr;
}
```

**Comment by xiaody** [comment]
Here you go ([jsbin.com](https://jsbin.com/huwodojike/edit?js,console)). `_i` is an empty string.

`_iterableToArrayLimit` is called with `_iterableToArrayLimit("", 1)`, so `_i = "" && (/* whatever */)` and short-circuit to `""`.

**Comment by yume-chan** [comment]
```js
var _i =
    arr &&
    ((typeof Symbol !== "undefined" && arr[Symbol.iterator]) ||
      arr["@@iterator"]);
```

Here `arr` is `""` which is falsy. So I guess this issue will also happen to other falsy values including `false` and `0`.

**Comment by jridgewell** [comment]
We need to adjust https://github.com/babel/babel/blob/a64d08c101129eb171ca02aa4fc8effb24590580/packages/babel-helpers/src/helpers.js#L906 to explicitly check `arr != null && …`.

**Comment by nicolo-ribaudo** [comment]
I'm marking this as a good first issue, since the fix is quite easy (https://github.com/babel/babel/issues/13421#issuecomment-857333190) but it's an opportunity to clone and setup the Babel repo locally.



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `exec.js` is enough for this kind of bug)
1. Update the code!
1. `yarn jest transform-destructuring` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest [name-of-the-package-to-test]` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by lala7573** [comment]
Can I try this?

**Comment by nicolo-ribaudo** [comment]
Sure, it's your!
