### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fingerpich** [babel/babel#13524]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

rollup-plugin-babel

### Input code

I rollup the following code
```js
function getRandomString(len) {
  let s = ''
  while (s.length < len)
    s += Math.random().toString(36).substr(2, len - s.length)
  return s
}
```
it converted to

```js
  function getRandomString(e) {
    for (var n = ""; n.length < e;) {
      n += Math.random().toString(36).substr(2, e - n.length);
    }

    return s;
  }
```

### Configuration

```js
export default {
  input: './index.js',
  plugins: [
    babel({
      "presets": [
        "@babel/preset-env",
      ],
      "plugins": [
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-proposal-optional-chaining"
      ]
    }),
    // uglify(),
  ],
  output: [
    {file: './dist/bundle.min.js',  name: "Ingrow", format: 'iife'},
    {file: './dist/index.js', exports: "default", format: 'cjs' }
  ]
}
```

### Current and expected behavior

to give something that doesn't make error
now its made Uncaught ReferenceError: s is not defined

### Environment

- "@babel/cli": "^7.14.5",
- "rollup": "^2.52.2",
- node version: v12.18.3

**Comment by nicolo-ribaudo** [comment]
None of the Babel plugins or presets you mentioned (`@babel/preset-env`, `@babel/plugin-proposal-object-rest-spread` or `@babel/plugin-proposal-optional-chaining`) convert `while` loops to `for` :thinking:

**Comment by fingerpich** [comment]
Thanks, you are right I have used rollup
I have edited the issue
As you see in roll up config I have just used babel so I thought its related to babel
but when I tested `babel src -d dist` the result was ok.

Do you think its related to `rollup-plugin-babel` or `rollup`?

**Comment by nicolo-ribaudo** [comment]
I think that the problem is a bug in `babel-preset-minify` (enabled in your config at https://github.com/ingrowco/ingrow-js-sdk/blob/fdf8c594c01c96dbac043a554e1e478ce5aae3f8/.babelrc#L4).

- `babel-preset-minify` is not really maintained, however since you are also using `uglify` you can just remove `babel-preset-minify`
- I strongly suggest not duplicating your Babel config (in `rollup.config.js` and `.babelrc`): choose a single place. Otherwise it's confusing when debugging problems, because you might miss a plugin/preset enabled by the config you are not looking at.

**Comment by fingerpich** [comment]
Yeah I forgot to remove .babelrc file but i didn't know it does affect when I use rollup
Thanks a lot.
