### ISSUE TITLE
Incorrect spread of ...arguments in loose mode

### ISSUE THREAD

**Issue by spicyj** [babel/babel#1354]
In loose mode, `f(2, ...arguments)` compiles to `f.apply(undefined, [2].concat(arguments))`. Similarly, `super(...arguments)` compiles to `_Superclass.call.apply(_Superclass, [this].concat(arguments))`.

Feel free to close if this is intentionally unsupported -- just noticed this in the online playground.

**Comment by sebmck** [comment]
Yeah, this is intentional. With loose mode for the transformer `es6.spread` it assumes that all spreads are arrays. You're meant to toggle each transformer on as listed in the [docs](http://babeljs.io/docs/usage/loose). But the REPL is pretty dumb where you either turn it on for all transformers or none.
