### ISSUE TITLE
[Bug]: Private Brand Check incorrectly allowed as RHS of `in` operator

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#13726]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

Found this while reading https://github.com/evanw/esbuild/releases/tag/v0.12.25 (esbuild continues to have wonderful changelogs):

```
class Foo {
  #a;
  #b;
  constructor(c) {
    #a in #b in c
  }
}
```

Because of the way the `in` operator works, this is parsing the same as `(#a in #b) in c`, which isn't a valid program.

### Configuration

Only default settings are needed.

```
{}
```

### Current and expected behavior

This should throw a parse error.

### Environment

Babel 7.15.3

### Possible solution

This issue is in https://github.com/babel/babel/blob/b335dcc67fa1233ff3a76cd0e8a06922e14c8587/packages/babel-parser/src/parser/expression.js#L1219-L1226. We're not checking whether we're already in the RHS of an `in` expression.

**Comment by nicolo-ribaudo** [comment]
Another test case:
```js
class Foo {
  #a;

  method() {
    x + #a in y;
  }
}
```

**Comment by nicolo-ribaudo** [comment]
Another test case:

```js
class Foo {
  #a;

  method() {
    for (var x = #a in y);
  }
}
```

With `errorRecovery` enabled, this currently just reports the error about the variable initializer in strict mode. We must also report the error about `#a` not being part of an `in` expression. This is important because when we will implement https://github.com/tc39/proposal-private-declarations we will be able to write this code:
```js
private #a;
for (var x = #a in y);
```
which otherwise wouldn't throw because it's not in strict mode.

**Comment by nicolo-ribaudo** [comment]
I was initially going to mark this as a good first issue, but I now prefer to work on it myself since it's more complicated than I expected.
