### ISSUE TITLE
Compiling logic seems twisted if we assign variable same name as method

### ISSUE THREAD

**Issue by syabro** [babel/babel#1375]
Why if we assign variable `a` which equals method name `a()` 
```javascript
var a;
var foo = {
    a() {
        a = 'bar';
    }
}
```

It produces closure?

```javascript

'use strict';

var a;
var foo = {
    a: (function (_a) {
        function a() {
            return _a.apply(this, arguments);
        }

        a.toString = function () {
            return _a.toString();
        };

        return a;
    })(function () {
        a = 'bar';
    })
};
```

If we change it to

```javascript
var a;
var foo = {
    a() {
        z = 'bar';
    }
}
```

it works as expected

```javascript
'use strict';

var a;
var foo = {
    a: function a() {
        z = 'bar';
    }
};
```

Is it compiler bug or ES6 feature?

**Comment by sebmck** [comment]
> Is it compiler bug or ES6 feature?

Neither really. Babel has function name inferrence which is part of the ES6 spec. eg.

```javascript
var foo = function () {};
```

turns into

```javascript
var foo = function foo() {};
```

Since the function name can be inferred. However, this changes the function semantics since function names create an additional binding **inside** the function. This means that `a` would reference the function instead of the variable you defined before. In order to get around this Babel will wrap the function in a function declaration constructor so it's named.

**Comment by jquense** [comment]
additional reading: http://blog.getify.com/es6-concise-methods-lexical-or-not/
