### ISSUE TITLE
Can't pass an array of globs to "only" option.

### ISSUE THREAD

**Issue by greim** [babel/babel#1376]
Can't seem to get this working.

```js
require('babel/register')({
  ignore: false,
  only: [
    '/bar/**/*.js',
    '/foo/**/*.js',
  ]
})
```

I might be reading the code wrong, but it seems to be munging the strings directly to a regex upon detecting an array: https://github.com/babel/babel/blob/master/src/babel/util.js#L72

**Comment by Mark-Simulacrum** [comment]
The code appears to be regex-escaping every element in the passed array, then joining the elements with a `|` (regex OR). Then this is used to create a regex.

What should probably happen is more along the lines of checking each element in the array to determine if it is a regex or a string, and if it is a string, passing it through Minimatch before doing the regex concatenation. The code for something like this is below. This code does not check that the regexps passed do not have additional flags that should be added, because I do not know of a good way to handle this.

```js
if (Array.isArray(val)) {
    val.map(item => {
        if (isString(item)) {
            return regexify(item);
        }

        if (isRegExp(item)) {
            return item;
        }
    });

    return new RegExp(minimatchedRegexes.map(regex => regex.source).join("|"), "i");
}
```

**Comment by sebmck** [comment]
[These lines](https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L79-81) need to be updated to use [util.shouldIgnore](https://github.com/babel/babel/blob/master/src/babel/util.js#L97-111). And [these](https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L147-148) to `util.arrayify(opts.key, util.regexify);`

**Comment by Mark-Simulacrum** [comment]
Posted #1377 with the fix that @sebmck suggested.
