### ISSUE TITLE
[Bug]: @babel/plugin-transform-react-constant-elements transforms non constant element in for loop

### ISSUE THREAD

**Issue by rufman** [babel/babel#13760]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```jsx
function Example(){
  const nodes = []
  
  for (let i = 0; i < 10; i++) {
    const n = i
    nodes.push(<div children={n}></div>)
  }
  
  return nodes;
}
```
### Configuration file name

babel.config.js

### Configuration
```js
module.exports = {
  env: {
    production: {
      plugins: [
        '@babel/plugin-transform-react-inline-elements',
        '@babel/plugin-transform-react-constant-elements',
        ['transform-react-remove-prop-types', { removeImport: true }],
      ],
    },
    test: {
      plugins: [['babel-plugin-webpack-alias', { config: './webpack/path-aliases.config.js' }]],
    },
  },
  plugins: [
    [
      '@babel/plugin-transform-typescript',
      {
        allowDeclareFields: true,
        isTSX: true,
      },
    ],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-nullish-coalescing-operator',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-optional-chaining',
    ['@babel/plugin-proposal-private-methods', { loose: true }],
    ['@babel/plugin-proposal-private-property-in-object', { loose: true }],
    '@babel/plugin-transform-runtime',
    'babel-plugin-generate-i18n-id',
    'react-hot-loader/babel',
  ],
  presets: [['@babel/preset-env', { loose: true }], '@babel/preset-react'],
};
```

### Current and expected behavior

When the code is transformed the element is treated as constant when both `transform-block-scoping` and `transform-react-constant-elements` are used. [incorrect](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKAbwChFEIEBnKRMOAE31sQF5EBtAXUsQDgcAE6JCBBjE6IADAG5E0gDyIAjAqUBqLcUQUqVGmHqMZMAVSataAOmwhaAC0LLmMAG7UnMXMxH4YBykYAC-AHzKAPTuHuHEAqECAgFQICJI1mzy5KFAA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.13.12&externalPlugins=%40babel%2Fplugin-transform-block-scoping%407.15.3%2C%40babel%2Fplugin-transform-react-constant-elements%407.14.5&assumptions=%7B%7D) vs [correct](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKAbwChFEIEBnKRMOAE31sQF5EBtAXUsQDgcAE6JCBBjE6IADAG5E0gDyIAjAqUBqLcUQUqVGmHqMZMAVSataAOmwhaAC0LLmMAG7UnMXMxH4YBykYAC-AHzKAPTuHuHEAqECAgFQICJI1mzy5KFAA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.13.12&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.14.5&assumptions=%7B%7D)

### Environment

```
System:
    OS: macOS 11.4
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  npmPackages:
    @babel/core: 7.15.0 => 7.15.0
    @babel/plugin-proposal-class-properties: 7.14.5 => 7.14.5
    @babel/plugin-proposal-export-default-from: 7.14.5 => 7.14.5
    @babel/plugin-proposal-export-namespace-from: 7.14.5 => 7.14.5
    @babel/plugin-proposal-nullish-coalescing-operator: 7.14.5 => 7.14.5
    @babel/plugin-proposal-object-rest-spread: 7.14.7 => 7.14.7
    @babel/plugin-proposal-optional-chaining: 7.14.5 => 7.14.5
    @babel/plugin-transform-react-constant-elements: 7.14.5 => 7.14.5
    @babel/plugin-transform-react-inline-elements: 7.14.5 => 7.14.5
    @babel/plugin-transform-runtime: 7.15.0 => 7.15.0
    @babel/preset-env: 7.15.0 => 7.15.0
    @babel/preset-react: 7.14.5 => 7.14.5
    @babel/preset-typescript: 7.15.0 => 7.15.0
    @babel/register: 7.15.3 => 7.15.3
    @babel/runtime: 7.15.4 => 7.15.4
    babel-eslint: 10.1.0 => 10.1.0
    babel-jest: 27.0.6 => 27.0.6
    babel-loader: 8.2.2 => 8.2.2
    babel-plugin-generate-i18n-id: 1.4.12 => 1.4.12
    babel-plugin-istanbul: 6.0.0 => 6.0.0
    babel-plugin-transform-react-remove-prop-types: 0.4.24 => 0.4.24
    babel-plugin-webpack-alias: 2.1.2 => 2.1.2
    eslint: 7.32.0 => 7.32.0
    eslint-plugin-babel: 5.3.1 => 5.3.1
    jest: 27.0.6 => 27.0.6
    webpack: 4.44.2 => 4.44.2
```

### Possible solution

Add an exception for this case here: https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-react-constant-elements/src/index.js#L75

**Comment by nicolo-ribaudo** [comment]
> Add an exception for this case here: https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-react-constant-elements/src/index.js#L75

I think a better solution would be in `@babel/traverse`, where we set `binding.constant`: if a `var` declaration is defined in a loop, it's _not_ a constant (it's reassigned as many times as the loop runs).

---



I'm assigning this to you, since you ticked the "Would you like to work on a fix?" bug. If you need any help, or you don't want to work on it anymore, let us know!

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to confirm to other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test in the `constant-elements` package (only `input.js`; `output.js` will be automatically generated)
1. Add a unit test for `@babel/traverse`
1. Update the code!
1. `yarn jest constant-elements` and ``yarn jest traverse` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest constant-elements` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by rufman** [comment]
I've started digging into the code.

**Comment by rufman** [comment]
I was able to set the constantness to false for variables inside a loop, but I'm getting regressions in other packages (like `babel-plugin-proposal-class-properties`) that I'm still confused about:
```
- _this = _super.call.apply(_super, [this].concat(args));
+ _this = _super.call.apply(_super, [this].concat(babelHelpers.toConsumableArray(args)));
```
instead of `[this].concat(args)` there is now an unnecessary transform using a babelHelper.

**Comment by nicolo-ribaudo** [comment]
Could you open a draft PRs? :pray:
It makes it easier to understand if we can/shour:
- Avoid that change
- Accept that change
- Move the fix from `@babel/traverse` to `transform-react-constant-elements`, even if _in theory_ it's better to put it in `@babel/traverse`

**Comment by JLHwung** [comment]
> if a var declaration is defined in a loop, it's not a constant (it's reassigned as many times as the loop runs).

I think whether a binding is constant should only depend on the declaration kind, it should not depend on whether the control flow will be re-entered.

IMO the binding is constant within its scope (defined by the loop body) because we can not re-assign it later:
```js
for (;;) {
  const a = 1;
  a = 2; // error
}
```
The constant binding is re-created within every loop execution, which is not different than
```js
f = (i) => { const a = i };
f(1);
f(2);
```

I think it should be fixed in `transform-react-constant-elements` instead. Specifically

https://github.com/babel/babel/blob/3d1481f36382d0f335eda33e4a45efa930dd3681/packages/babel-plugin-transform-react-constant-elements/src/index.js#L36

we should not hoist the component out of the loop body. Currently we decide that the hoisting scope is from ForStatement, which yields incorrect results.

To fix this we should return the BlockStatement if it is a body of Loop.

**Comment by nicolo-ribaudo** [comment]
@JLHwung When we don't compile `const` to `var`, we already generate correct code. If you check [this repl with `var`](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKAbwChFFg4AnRQgqRGRAXkQAYBuFxAHkQBGHiwDUY4ogpUqAN3T0kHGJVlg4AE3wBnAHTYQOgBaF-mmHMQRjMXJtr4wbUmAC-APn4B6C3I_Eam5qao5QILRIGto63ORuQA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.13.12&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.14.5&assumptions=%7B%7D) you can see that it's broken, while if you switch it to `const` it works.

`var` inside loops are _not_ constants, because they are equivalent to hoisting the `var` to the function scope and reassigning them at every iteration.

**Comment by jridgewell** [comment]
I agree with @nicolo-ribaudo. Because the binding is hoisted to the function-level and can be reassigned in multiple loop evaluations, it's not really constant. Eg,

```js
function test() {
  var foo;
  for (let i = 0; i < 100; i++) {
    foo = i;
  }
}
```

That's effectively the same as `var foo = i`, but we certainly wouldn't call this one constant.

**Comment by JLHwung** [comment]
Oh I see. The traverser incorrectly marks `binding.constant` as `true` for the `var` declaration in for loop.
