### ISSUE TITLE
[Bug]: error parsing typescript assertion signature

### ISSUE THREAD

**Issue by JonathanMEdwards** [babel/babel#13761]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

[this doesn't parse](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAQwM6oKYCcoAoIIAmMsCAXCmAJ4CUFAUGpjqogWMaUgN4C-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.15.6&externalPlugins=&assumptions=%7B%7D) 

but this does:
```
function assert(condition: any): asserts condition {}
```

### Current and expected behavior

parsing should match typescript

### Environment

babel repl

**Comment by fedeci** [comment]
This bug comes from the `tsParseTypePredicateAsserts` function where we check that the `asserts` keyword does not have any line break before it. We should change the behaviour of that function to accept line breaks.
https://github.com/babel/babel/blob/710b3919fae1098e63e7d75535dd0c8597cf695f/packages/babel-parser/src/plugins/typescript/index.js#L1318-L1341

---



If anyone wants to help fixing this bug and it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment here** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.ts`; `output.json` will be automatically generated) in https://github.com/babel/babel/tree/main/packages/babel-parser/test/fixtures/typescript/assert-predicate
   - We need a test for the valid case (the example in the bug report) and for the invalid case `[function]`.
1. Update the code!
1. `yarn jest parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest parser` and they will be automatically updated.
    - New parser tests sometimes fail: don't worry, run `yarn jest parser` again after that 
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by JuniorTour** [comment]
Can i take this?

**Comment by fedeci** [comment]
Sure!
