### ISSUE TITLE
[Bug]: Edge case in TSX: `<T,>(t: T) => t`

### ISSUE THREAD

**Issue by hyrious** [babel/babel#13778]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const { transformSync } = require('@babel/core')

let result = transformSync(`
  const fn = <T,>(t: T) => t;
`, {
  babelrc: false,
  configFile: false,
  parserOpts: {
    plugins: [
      'jsx',
      'typescript',
    ]
  },
})

console.log(result.code)
```

### Current and expected behavior

The current output:
```ts
const fn = <T>(t: T) => t;
```
This is valid in TS, but invalid in TSX, because `<T>` is treated as a tag in TSX context.

Expected output:
```tsx
const fn = <T,>(t: T) => t;
```

### Environment

```
  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.23.0 - /usr/local/bin/npm
```

### Additional context

Original Issue: vitejs/vite#4949.

**Comment by hyrious** [comment]
Possible solution: keep trailing comma in type list:
```js
// in babel-parser/src/plugins/typescript/index.js tsParseDelimitedListWorker:
let comma = false;
// ...for (;;) {...
  if (this.tsIsListTerminator(kind)) {
    result.hasTrailingComma = comma;
    break;
  }
  if (this.eat(tt.comma)) {
    comma = true;
    continue;
  }

// in babel-generator/src/generators/typescript.ts TSTypeParameterInstantiation:
if (node.params.hasTrailingComma) this.token(",");
this.token(">");
```

**Comment by nicolo-ribaudo** [comment]
We can just always unconditionally print a trailing comma.

**Comment by nicolo-ribaudo** [comment]
@hyrious Since you already looked at the `@babel/generator` code, would you like to open a PR? Otherwise I'll mark this as a [good first issue] for anyone who is interested in contributing.

---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest generator` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest generator` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by hyrious** [comment]
@nicolo-ribaudo Thank you for inviting me. However I'll not be able to use *nix system in the next few days.
So I guess you could do the latter.

The "solution" I posted above was just a quick & dirty hack into node_modules, it just passed this single edge case and didn't follow common practices (it stores a value in an array). It's difficult for me to refactor it into a more robust one in such large code base.

Always printing trailing comma in type list seems promising but may break many other things. I don't know it very much. So I'll leave this chance to other experienced programmers.

**Comment by ChaitanyaGadodia** [comment]
Hi! Can I pick this bug?

**Comment by fedeci** [comment]
It's yours!

**Comment by jraoult** [comment]
Just wanted to mention that this is probably the root cause of https://github.com/vitejs/vite/issues/3883 if anyone is looking for it.

**Comment by ozanhonamlioglu** [comment]
> Hi! Can I pick this bug?

If you don't work on this case, can I take this?

**Comment by nicolo-ribaudo** [comment]
Yes :+1:

**Comment by ozanhonamlioglu** [comment]
Hi @nicolo-ribaudo, I have a question

I am planning to put my test input into [babel-generator/test/fixtures/typescript/arrow-function-generic-tsx](https://github.com/babel/babel/blob/main/packages/babel-generator/test/fixtures/typescript/arrow-function-generic-tsx/input.js)
But looks like there is an error, because when I run the `yarn jest generator` it doesn't check the any input.js files inside fixtures folder and it doesn't generate output.js files. What am i doing wrong?

Also any hint that you want to support me is nice for me. Thanks

![Screen Shot 2022-01-05 at 09 56 35](https://user-images.githubusercontent.com/47304816/148173749-09146051-baf8-4ea5-b1dc-8bdec47c973c.png)

**Comment by nicolo-ribaudo** [comment]
Do you have a branch or draft PR I could look at to see why it's not working?

**Comment by ozanhonamlioglu** [comment]
> 

In that screenshot I actually didn't changed or added any files, I just run the jest generator directly, so i can't give you valuable branch name.
Additionally here is [my fork](https://github.com/ozanhonamlioglu/babel ), it has the same hash.

See, nothing is changed.
If you can correct that currently it works on your machine, I can remove and install it again. Maybe something caused issue on my mac.

![Screen Shot 2022-01-05 at 15 31 22](https://user-images.githubusercontent.com/47304816/148218037-390bf89c-8b20-4472-a6ed-5c9aa2899d5a.png)

**Comment by ozanhonamlioglu** [comment]
> Do you have a branch or draft PR I could look at to see why it's not working?

@nicolo-ribaudo I think there is a problem.

When I run `yarn jest generator` it wasn't running any of fixture tests. and also it was throwing this.
![Screen Shot 2022-01-05 at 21 59 29](https://user-images.githubusercontent.com/47304816/148273661-6450d001-d184-4346-b03e-3b30d0b099a5.png)

Then I removed every entry that has a test with t.stringLiteral inside babel-generator/test/index.js
![Screen Shot 2022-01-05 at 22 01 31](https://user-images.githubusercontent.com/47304816/148273749-c7d0dbbd-7f77-4916-8888-04b9f4ef4675.png)

After I run `yarn jest generator` now it started to generating output.js files inside fixtures; But now there are other errors.
![Screen Shot 2022-01-05 at 22 02 58](https://user-images.githubusercontent.com/47304816/148273954-b13253e9-4a13-4a88-8ec5-e243afac0817.png)

I am thinking that babel-generator/test/index.js has an error and because of that this is happening.

**Comment by nicolo-ribaudo** [comment]
Did you run `make bootstrap` before running the tests? Are you working on an outdated fork/branch? 🤔

**Comment by ozanhonamlioglu** [comment]
> 

This is my head hash ddd93b9c61a197711c2e3eae8a8b175783ea6976 which is the current.

And yes I exactly did the steps you specified in here
```
> 2. Fork the repo
> 3. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
> 4. Run `yarn && make bootstrap`
> 5. Wait ⏳
> 6. Run `make watch` (or `make build` whenever you change a file)
> 7. Add a test (only `input.js`; `output.js` will be automatically generated)
> 8. Update the code!
> 9. `yarn jest generator` to run the tests
>    
>    * If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
>    * If you prefer, you can run `OVERWRITE=true yarn jest generator` and they will be automatically updated.
> 10. If it is working, run `make test` to run all the tests
> 11. Run `git push` and open a PR!
```
I am actually able to generate output.js files but the only way to generate them is to remove everything `inside babel-generator/test/index.js` except line 816 `suites.forEach(function (testSuite) {...`

Are you able to run `yarn jest generator` without any error with the current fork/branch?

**Comment by nicolo-ribaudo** [comment]
Yes, `yarn jest generator` works without problems on my machine :thinking:

**Comment by ozanhonamlioglu** [comment]
> Yes, `yarn jest generator` works without problems on my machine :thinking: 

Okay, never mind then, probably it is related to my env.
I actually started to dig in already, and it is going well and will update you soon I hope.
Thanks

**Comment by ozanhonamlioglu** [comment]
Hey @nicolo-ribaudo
I just opened a PR for the issue, and I want to ask one thing. I added a new test code inside an existing input file, because the naming of the parent folder was so right to me. Is that okay? or shall I create another folder and insert my code into it?

Thanks

**Comment by ozanhonamlioglu** [comment]
> Hey @nicolo-ribaudo I just opened a PR for the issue, and I want to ask one thing. I added a new test code inside an existing input file, because the naming of the parent folder was so right to me. Is that okay? or shall I create another folder and insert my code into it?
> 
> Thanks

Anyway, I just separated my test codes, after a while reviewing test folders, it seems using separated folder for this case is fine.
