### ISSUE TITLE
@babel/preset-env does not transform invariant when used with babel-plugin-dev-expression 0.2.2

### ISSUE THREAD

**Issue by leepowelldev** [babel/babel#13848]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBMAdgNwIZWKx8BmUIhwDkAdAPRJoZYxEDcAUAwMYSIDO8w7AaqgDbAAJnAC8cHAPYBTRg0rpM2ABTc-goQBpiAFQAW3BOzhY40qPihEAlHSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Ctypescript&prettier=false&targets=&version=7.15.8&externalPlugins=babel-plugin-dev-expression%400.2.2&assumptions=%7B%7D

### Current and expected behavior

When preset-env is used, the second `invariant(false)` fails to be transformed. I expect this to be transformed as per the first `invariant` call.

Before @babel/preset-env is applied, there are two invariant calls.
```
import invariant from './invariant';

const isValid = false;

!isValid ? process.env.NODE_ENV !== "production" ? invariant(false, 'This is an error') : invariant(false) : void 0;
```
However, after using preset-env:
```
var _invariant = _interopRequireDefault(require("./invariant"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

var isValid = false;
!isValid ? process.env.NODE_ENV !== "production" ? (0, _invariant["default"])(false, 'This is an error') : invariant(false) : void 0;
```
Only the first is transformed, causing the second to throw an error as `invariant` is not a global, or available in the module scope.

### Environment

See repl link.

**Comment by JLHwung** [comment]
Yes, presets are applied after plugins. The issue here is that the plugin generates invalid AST which contains duplicate nodes.

Babel internally maintains a map from the AST node to the NodePath, when the AST contains no duplicate nodes, every part of the AST points to the unique NodePath. The "invariant" replacement is applied to the NodePath. Now after the first `invariant` identifier is transformed, when Babel sees the second `invariant` identifier, it is not transformed because it was _incorrectly_ mapped to a transformed NodePath, so Babel thinks this node is already `_invariant["default"]`, which is not the case. This should never happen if the plugin uses `t.cloneNode` to clone the identifier. The AST node must not be identical if they points to different locations in the source: In you case there are 2 `invariant` identifier but only one identifier node.

Closing this issue now as the fix has been proposed in https://github.com/4Catalyzer/babel-plugin-dev-expression/issues/17#issuecomment-943384090.
