### ISSUE TITLE
[Bug]: Babel turns comments between lines into trailing comments

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [babel/babel#13904]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

Repl link:
https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=EQVwzgpgBGAuBOBLAxrYBuAUJgZiAdqogPb5SwRwAUAlFAN6ZRQD0LUAwsQLbcT6woAQwBGxEINgALaADchSUQBsIAOiZQVg-fAByQvlAC8UAAxZmbTjz4DhYieRlQQAB2Q9E-AOabixVygAdykUKShEMHIQeHwIABMIgWJhcnghRCUvXw9eflh1ZhDM6CodfUMAHigARjpGZkt2Ljy7UXFJZziAD0EsuMLGgGoh8oMICygAXw0rABVQqNzbQUikinx4hPIUkWh4CBV5O1gU6Wgevq81DQ98MGIVVSVibzKFCuhquvRWdgW1ggMv0cjZ8lBXAdZPkoucoJcoKRoDh4DwoHtslBuMRofFBvNFlBluDIvgAOSSGJxRJeU6pIGZTHEgTqKZAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.16.0&externalPlugins=&assumptions=%7B%7D

### Configuration file name

babel.config.js

### Current and expected behavior

Babel turns comments intended to document subsequent lines into trailing comments, sometimes even causing new blank lines to be created.

It would be great if comments between lines could be kept there - even if comments don't have their own AST nodes, it seems odd that they would get moved and leave a blank line behind (or even generate a 2nd blank line).

### Environment

The REPL link is for babel 7.16.0 but older versions produce the same output.

### Additional context

I don't think this is a very important issue - I only noticed it in babel REPL while investigating something else. Normally you would probably look at the original source via a source map (and comments would probably be stripped out entirely). It did surprise me after all the work on comment placement recently though.

**Comment by JLHwung** [comment]
If you check https://astexplorer.net/#/gist/03f767f5dbe210bd68f53a0e841b7d35/ddcf3abd498633acefc578aba4c50478eedb30eb, the comment `"This comment is intended to be relevant to the next line."` is inserted as the trailing comment of WhileStatement and the leadingComment of `console.log`, which is expected. In this case when Babel prints the AST to code, the `trailingComment` wins because whileStatement is printed before `console.log`.

> It would be great if comments between lines could be kept there - even if comments don't have their own AST nodes, it seems odd that they would get moved and leave a blank line behind

Babel does not preserve whitespaces styles, because whitespaces has no semantic meaning in JavaScript. If you have tools that specifically relying preserving the whitespaces, consider trying on `recast`.

For leadingComments/trailingComments, Babel guarantees that they will be placed within its leadingNode and trailingNode, but Babel does not guarantee that the whitespaces (how many whitespaces before and after the comment) are preserved since they are not tracked in AST anyway.

For innerComments, some of them may not be printed at all, we are still fixing the printer but even though they can be printed, they won't be printed in the same slot because Babel does not know where the comments come from.

**Comment by ehoogeveen-medweb** [comment]
Thanks for the response! I don't expect babel to preserve the whitespace style, its decisions here just seem counterintuitive (and unfortunate since Prettier can't restore the comment to its original location).

> the comment `"This comment is intended to be relevant to the next line."` is inserted as the trailing comment of WhileStatement and the leadingComment of `console.log`, which is expected.

It feels strange to me that a single line comment after a newline would still be counted as a `trailingComment`. Is every comment in between two sibling nodes always the `trailingComment` of the preceding node and the `leadingComment` of the subsequent node?

I guess it would be better in this case if the tie was broken in favor of the `leadingComment`, as I think that would be a better match for how humans intend 'infix' comments like these, but I guess the order of operations makes that difficult (without breaking the tie at some earlier stage).

**Comment by nicolo-ribaudo** [comment]
Consider this case:
```js
var a; // this is a
       // variable
a = 2;
```

The comment is on a new line, but for a human it should be clearly treated as a trailing comment. Unfortunately there isn't a clear algorithm to distinguish between the two positions 😕

**Comment by Krinkle** [comment]
See also an older issue from two years earlier: https://github.com/babel/babel/issues/8684
