### ISSUE TITLE
[Bug]: package.json isn't being converted to work for older node versions

### ISSUE THREAD

**Issue by SHESA-AmitBar** [babel/babel#13933]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

Here's a simple GitHub repo that can represent the issue: https://github.com/SHESA-AmitBar/babel-bug

### Configuration file name

babel.config.js

### Configuration

```
export default {
  presets: [
    ["@babel/preset-env", {
      targets: {
        node: "6.14.2"
      }
    }],
  ],
  plugins: [
    "babel-plugin-transform-import-meta"
  ],
  ignore: [
    "./lib",
    // also ignore babel config file
    /babel.config.*/,
    // include lowdb in babel transpilation so we can make it work with node v6
    /[\\/]node_modules[\\/](?!(lowdb))/,
  ],
};
```

### Current and expected behavior

Expected behavior:
`package.json`'s use `exports` key for newer node.js versions but older node versions use the `main` key (both keys are used to specify the "entry point" into the code in their respective node versions). When using the `env` preset in babel, we expect it to transpile everything necessary to the specified environment so it's easy to run. When I specify the node version in the `env` preset to node version 6.14.2, I expect everything to be transpiled to the correct node version, including the package.json in the node_modules packages that I do not ignore. So, for example, `exports` key should be convert to the proper `main` key (since `exports` isn't recognized in node 6).

Current behavior:
The `exports` key is not converted to the proper `main` key. This results in a `Error: Cannot find module '[module-name]'` error, since `exports` isn't recognized by node 6 and node doesn't know the entry point for the module.

### Environment

```
System:
    OS: macOS 11.6
  Binaries:
    Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
  npmPackages:
    @babel/cli: ^7.16.0 => 7.16.0 
    @babel/core: ^7.16.0 => 7.16.0 
    @babel/preset-env: ^7.16.0 => 7.16.0 
    babel-plugin-transform-import-meta: ^2.1.0 => 2.1.0 
```

Note: I use Node 16.12.0 when running babel but use Node 6.14.2 when running the transpiled code.
So to build:
```
nvm use 16
npm run build
```
And to run:
```
nvm use 6
npm run start
```

### Possible solution

Perhaps a plugin to convert `package.json`'s could be added to the `env` preset. If someone has found a workaround for this such as a simple script or something similar, that could work as a temporary workaround.

**Comment by JLHwung** [comment]
The `exports` v.s. `main` are a part of Node.js module API, I think it is out of Babel's scope. Not to mention that Babel does not transform JSON.

For example, Node.js 10 introduced `fs/promise`. If you compile

```js
import fs from "fs/promises"
```

to

```js
const fs = require("fs/promises");
```

and then run the compiled program on Node.js 6, it surely throws `fs/promises` is not found: You have to provide a polyfill for `fs/promises` or do a feature detection instead.

In fact, Node.js recommends package author to [define both `main` and `exports`](https://nodejs.org/api/packages.html#main-entry-point-export).

> a plugin to convert package.json's could be added to the env preset

Since JSON is easy to read. You can come up with your own converter without Babel at all, that automatically reads `exports` and determines a `main` entry.
