### ISSUE TITLE
[Bug]: Destructured symbol fails on IE 10+

### ISSUE THREAD

**Issue by Lcfvs** [babel/babel#14154]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

```js
const symbol = Symbol('desc')

export default ({
  [symbol]: alias = {},
  ...rest
}) => {
  return {
    ...rest,
    symbol: alias
  }
}
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": [
    "@babel/env"
  ],
  "exclude": [
    "node_modules/**"
  ],
  "targets": ["since 2000"]
}
```

### Current and expected behavior

Actually, it throws *"@@toPrimitive must return a primitive value."* which doesn't seems to be catchable.

But the objects passed are pretty fine, since if I extract the parts separately, it works.

```js
const symbol = Symbol('desc')

export default ({
  ...properties
}) => {
  return {
    ...properties,
    [symbol]: properties[symbol]
  }
}
```

### Environment

- Babel version: 7.16.7
- Node: 16.3.0
- npm: 7.18.1
- OS: Windows 10
- Monorepo: no

**Comment by nicolo-ribaudo** [comment]
I think that the problem is that you are using a symbol polyfill that defines `Symbol.prototype[Symbol.toPrimitive]()` and makes it return an object. This is valid if you consider "some objects are polyfilled symbols and should be considered as primitives", but the spec says that `[Symbol.toPrimitive]()` must return a primitive and not an object.

Could you check if adding `delete Symbol.prototype[Symbol.toPrimitive]` to your code "fixes" the problem?

**Comment by Lcfvs** [comment]
Just tested, the results:
* `delete Symbol.prototype[Symbol.toPrimitive]`: seems to work... but the polyfill is provided by core-js (should I report it on their repo?)
* `console.log(typeof symbol)`: `"symbol"`
* `console.log(eval("_toPrimitive")(symbol))`: syntax error, even if your code seems fine

**Comment by nicolo-ribaudo** [comment]
> Since it can work in 2 steps, with the same polyfill, it shouldn't be fixed by Babel itself?

Yeah, I was trying to identify the problem to see if we can do it without spinning up a Windows virtual machine to test IE10 😅 

Are you loading core-js manually, or do you have a more complex Babel config to automatically load it were needed?

**Comment by Lcfvs** [comment]
I just import it like this:

```js
import 'core-js/stable'
import 'regenerator-runtime/runtime'
```

**Comment by nicolo-ribaudo** [comment]
I tried to experiment with this. The problem is that when compiling symbols to work with the polyfill, the Babel helpers need to be "rewired" so that when the runtime helpers use `typeof x === "symbol"`, they also accept polyfilled symbols.

Normally this happens by default, both when using Babel with "inline helpers" or with `@babel/runtime`. It looks like `@rollup/plugin-babel` automatically extract all the helpers and puts them in a separate file, but this file isn't fed back to Babel to adjust the symbol-related helpers.

I suggest:
1. Adding `@babel/runtime` and `@babel/plugin-transform-runtime` to your dependencies, and add `"plugins": ["@babel/plugin-transform-runtime"]` to your Babel config
2. Pass [`babelHelpers: "runtime"`](https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers) to your `@rollup/plugin-babel` config
3. Use `"ignore"` rather than `"exclude"` in your Babel config, so that `node_modules/**` are completely skipped by Babel (rather than transformed with a no-op config) and `@rollup/plugin-babel` doesn't complain about `@babel/plugin-transform-runtime` not being enabled in your `node_modules`

This effectively replaces `@rollup/plugin-babel`'s default helpers handling behavior with `@babel/runtime`, which should also work when polyfilling symbols. I'm sure that there is a way to make Rollup feed the extracted helpers back to Babel, but I'm not a Rollup expert and I don't know how to do it :sweat_smile:

**Comment by nicolo-ribaudo** [comment]
I tested it at https://github.com/nicolo-ribaudo/babel-bug-14154, and it works in IE. If I remove `@babel/plugin-transform-runtime`, I see the `@@toPrimitive must return a primitive value` error you mentioned.

**Comment by Lcfvs** [comment]
Thanks a lot but I tried like you and I have this rollup reporting:

````sh
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
@babel/runtime/helpers/typeof (guessing '_typeof')
@babel/runtime/helpers/defineProperty (guessing '_defineProperty$1')
@babel/runtime/helpers/objectWithoutProperties (guessing '_objectWithoutProperties')
@babel/runtime/helpers/asyncToGenerator (guessing '_asyncToGenerator$1')
@babel/runtime/regenerator (guessing '_regeneratorRuntime')
@babel/runtime/helpers/toArray (guessing '_toArray')
@babel/runtime/helpers/slicedToArray (guessing '_slicedToArray$1')
@babel/runtime/helpers/toConsumableArray (guessing '_toConsumableArray')
```

Am I missing something, please?

**Comment by nicolo-ribaudo** [comment]
What's your rollup config?

**Comment by Lcfvs** [comment]
```js
import commonjs from '@rollup/plugin-commonjs'
import babel from '@rollup/plugin-babel'
import { nodeResolve } from '@rollup/plugin-node-resolve'
import { terser } from 'rollup-plugin-terser'
import { pathToFileURL } from 'node:url'

const url = pathToFileURL('src/../..')

const { href } = url

export default [
  {
    input: `src/js/index.js`,
    output: {
      file: `dist/js/main.min.js`,
      format: 'iife',
      sourcemap: true
    },
    plugins: [
      nodeResolve({
        browser: true,
        dedupe: [
          // private
        ]
      }),
      {
        resolveImportMeta(property, { moduleId }) {
          if (property === null || property === 'url') {
            const path = pathToFileURL(moduleId).href.replace(href, '')
            const url = `new URL('${path}', globalThis.location).href`

            if (!property) {
              return `{ url: ${url} }`
            }

            return url
          }

          return null
        }
      },
      commonjs(),
      babel({
        babelHelpers: 'runtime'
      }),
      terser()
    ],
    external: ['core-js']
  }
]
```

**Comment by nicolo-ribaudo** [comment]
I cannot reproduce the error with your config :thinking: I'd be happy to help but I need a repository which should the problem.

**Comment by Lcfvs** [comment]
Ok, I try to make a minimal repo to share it with you (I just can't share the real one actually, it's a project of my client and it isn't intended to be open source right now)

**Comment by Lcfvs** [comment]
Just done.

I made a repo containing 2 packages (no choice to reproduce one of the report lines):
* [The lib](https://github.com/Lcfvs/babel-bug-14154/tree/main/lib) which defines `lib/selectors/all.js`
* [The project](https://github.com/Lcfvs/babel-bug-14154/tree/main/project) which imports `lib/selectors/all.js` to select something

**Comment by nicolo-ribaudo** [comment]
Thanks for the repository! You can fix the problem by adding [`"absoluteRuntime": true`](https://babeljs.io/docs/en/babel-plugin-transform-runtime#absoluteruntime) to the `transform-runtime` options:
```json
{
  "presets": [
    "@babel/env"
  ],
  "ignore": [
    "node_modules/**"
  ],
  "targets": ["since 2000"],
  "plugins": [
    ["@babel/plugin-transform-runtime", { "absoluteRuntime": true }]
  ]
}
```

**Why?** By default, `@babel/plugin-transform-runtime` injects imports to `@babel/runtime`, like `import _toConsumableArray from "@babel/runtime/helpers/toConsumableArray"`. This generally works well, and it's how it can work if you then want to publish the compiled code to npm (adding a `@babel/runtime` dependency).

However, it does not work if you are also compiling your dependencies: Babel injects a `@babel/runtime` import in `lib/`, but `lib/` does not have a `@babel/runtime` dependency so Rollup cannot find it. I initially didn't think about this case, because due to the `ignore: ["node_modules/*"]` I assumed that you were not compiling any of your dependencies.

`absoluteRuntime: true` fixes the problem by using absolute paths: rather than `import _toConsumableArray from "@babel/runtime/helpers/toConsumableArray"`, it injects something like `import _toConsumableArray from "/home/absolute/path/to/your/project/node_modules/@babel/runtime/helpers/toConsumableArray"`, and then Rollup is always able to resolve it.

**Comment by Lcfvs** [comment]
Thanks to you, for that part, it's ok.

But I have a new problem, probably caused by the `ignore`, it breaks these imports (it worked with the `exclude`):

```js
import 'ace-builds/src-min/ace.js'
import 'ace-builds/src-min/mode-markdown.js'
```

It seems to break some references into the `ace.js`, here the `define`

**Comment by Lcfvs** [comment]
I finally found a solution, using their no-conflict version, then you can close this issue if you want.

But I'm still interested to know why that distinct behavior (`ignore` VS `exclude`) breaks the things or not.

**Comment by nicolo-ribaudo** [comment]
Whops sorry, I forgot about this :sweat_smile: 

I'm only case in which `ignore` and `exclude` have different behaviors is when you have multiple Babel configurations:
- `exclude` means "don't apply this config to these files"
- `ignore` means "don't transform these files with Babel"

If, for example, you enable some plugins A in `babel.config.js` and plugin B by passing it directly to `@rollup/plugin-babel`:
- with `exclude: node_modules`, all the JS files in `node_modules` will be transformed but only with plugin B;
- with `ignore: node_modules`, the JS files in `node_modules` won't be transformed.

**Comment by Lcfvs** [comment]
Oh, I see. :)

Thanks a lot again.
