### ISSUE TITLE
Errors with extending Array

### ISSUE THREAD

**Issue by lukescott** [babel/babel#1424]
Not a high priority for me, but was curious how this worked and found some errors.

This one works in Traceur:
```javascript
class Foo extends Array {}
class Bar extends Foo {}

var f = new Foo();
console.log(f);
var b = new Bar();
console.log(b);
```
Expecting:
```javascript
[]
[]
```
Got:
```
[]
{}
```

ES7 properties don't work:
```javascript
class Foo extends Array {
  foo = "foo";
}

var f = new Foo();
console.log(f.foo);
```
Expecting:
```javascript
foo
```
Got:
```javascript
```
This is what is generated:
```javascript
var Foo = (function (_Array) {
  function Foo() {
    _classCallCheck(this, Foo);
    if (_Array != null) {
      var _this = new (_bind.apply(_Array, [null].concat(_slice.call(arguments))))();
      _this.__proto__ = Foo.prototype;
      return _this; // <--- returns early
    }
    this.foo = "foo"; // <--- should probably be _this in this context, yes?
    return _this;
  }
  _inherits(Foo, _Array);
  return Foo;
})(Array);
```

This version throws an error:
```javascript
class Foo extends Array {
  foo = "foo";
  
  constructor() {
    super();
  }
}

var f = new Foo();
console.log(f.foo);
```
Error:
```javascript
repl: You can't replace this node, we've already removed it
```

**Comment by monsanto** [comment]
I can't actually tell if the first one is a caveat from the [discussion on native subclassing](https://github.com/babel/babel/issues/1172#issuecomment-91262078)....

Anyway, the issue is that `Foo` discards `this` and returns a new array with a modified prototype, but `Bar` assumes that `Foo` is going to mutate `this` and ignores the return value. It is more obvious if you modify your example to assign some properties:

```js
class Foo extends Array {
    constructor() {
        super()
        this.x = "foo"

    }
}
class Bar extends Foo {
    constructor() {
        super()
        this.y = "bar"
    }
}
```

```
[ x: 'foo' ]
{ y: 'bar' }
```

**Comment by lukescott** [comment]
@monsanto This is what Traceur does with the example you provided:
```javascript
[x: "foo"]
[x: "foo", y: "bar"]
```
So it seems possible, at least in Chrome (browsers that support __proto__?), to make this work.

**Comment by sebmck** [comment]
Probably just going to nerf the native builtin extension because it doesn't work very well and it's going to break if an engine adds builtin extension but not classes.

**Comment by sebmck** [comment]
Also I'm fairly confident that the reason it works with Traceur is because Chrome added support for inheriting from builtins like `Array` which the Babel builtin extension support breaks.

**Comment by cybersyntactics** [comment]
I have some code that relies on extensions to extensions to native arrays and I am doing something like this:

```
class Foo extends Array {
    constructor() {
        _this = super()
        _this.x = "foo"
        return _this;
    }
}
class Bar extends Foo {
    constructor() {
        _this = super()
        _this.y = "bar";
        return _this;
    }
}
```

But I don't know if that would work with Babel. I would prefer to use Babel but the code I have written involves several extensions to extensions to native builtins, so otherwise my only choices will be to use Traceur or wait for browsers to implement it. I can try to clean up and post some of the code I have that works in Babel and Traceur tomorrow, but currently I think it all assumes that super() has a return value, modifies the return value, and then returns that return value for further extensions down the chain.

**Comment by lukescott** [comment]
@sebmck If that were true (comment about Chrome) then babel would not be returning two arrays. It is currently returning two objects.

Following code:
```javascript
class Foo extends Array {}
class Bar extends Foo {}

var f = new Foo();
console.log(f);
var b = new Bar();
console.log(b);
```
Now returns:
```javascript
{}
{}
```

@cybersyntactics Here is a work-around:
```javascript
class Foo extends Array {
  foo = "foo";
  constructor() {
    super();
    let _this = new Array();
    _this.__proto__ = this;
    return _this;
  }
}

class Bar extends Foo {
  foo = "bar";
  constructor() {
    super();
    let _this = new Foo();
    _this.__proto__ = this;
    return _this;
  }
}

var f = new Foo();
console.log(f, f.foo);
var b = new Bar();
console.log(b, b.foo);
```
Output is:
```javascript
[] foo
[] bar
```

Ideally that's what babel is doing, which is close to what it was doing. It just needs to use `this` instead of `Foo.prototype` or `Bar.prototype`, and it needs to know a subclass is from an Array/builtin.

My only concern is with normal subclasses `super()` returns `undefined` unless the constructor explicitly returns something. Since extending built-ins is emulated, shouldn't `super()` be returning `undefined`? Any way to make that consistent, perhaps by wrapping the super call?

**Comment by sebmck** [comment]
It'd require adding that long boilerplate to all classes, see #1172 for previous discussion. It's literally impossible to replicate subclassing of built-ins since even with Traceur's implementation (which I assume does the same `__proto__` magic under the hood) calling `slice` on a subclassed array returns a plain array.

**Comment by lukescott** [comment]
@sebmck Good point, hadn't thought about that. Also since `__proto__` is not supported in IE 10 and below, `instanceof` would be broken without `__proto__`. So as you said, impossible, at least to work across all environments.

@cybersyntactics The workaround I posted above will work for your existing code. If possible I wouldn't rely on that, unless you're willing to re-implement every Array function and drop IE 10 support -- not sure what your requirements are. [Iterators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) might be a nice alternative.

**Comment by cybersyntactics** [comment]
Right. I am willing to drop IE 10 support. I'm fine using my own ES5 extension to Array and was planning on re-implementing a number of Array's functions (the ones I planned on using at least) although I hadn't thought of slice. And eventually I did want to implement the iterator protocol for the class as well. 

I was trying to avoid explicitly calling the super class's constructor in the subclass constructor as I currently have a 3 deep chain of subclasses originating from Array which might get a little longer (or shorter once I start worry about performance), and might go through more refactoring (which would mean refactoring the boilerplate in every constructor in the chain). Ideally I don't need this to work:

```
class Foo extends Array {} // Or my ES5 workaround

class Bar extends Foo {}

```

But would expect this to work:

class Foo extends Array {} // Or ES5 workaround

class Bar extends Foo {
  constructor() {
    return super(...arguments); // But yes, this would only work with my ES5 workaround which does explicitly return something. Still I would just need to comment out or detect and not call this when actual extension support is added and my workaround is removed in favor of an actual extension to builtins.
  }
}

which wouldn't need to be changed if class names change, chain order changes, etc. (other than the X extends Y part).

So I think I would be fine with no built in extensions, but last time I checked I was not getting a return value from super() (when it returns something) which was causing my solution to fail in Babel. Looking at it now it appears I am getting a return value, but it's just a regular array, not an array with the sub-subclasses prototype.

My ES5(ish) solution looks something like:

```
function Array2() {
	var arr = new Array();
	arr.foo = "bar";
	arr.__proto__ = this.__proto__;
	return arr;
};

Array2.prototype = Object.create(Array.prototype);

Object.assign(Array2.prototype, {
	bar: function() {
		console.log(this.foo);
	}
});

```

**Comment by cybersyntactics** [comment]
Actually, now that I think about it, if super on returns something if something is explicitly returned those lines above wouldn't need to be changed, I'd just need to change Array2 to return `this` instead of `arr`.

**Comment by cybersyntactics** [comment]
Ok, I think I got it now. I still don't fully understand the discussion in #1172 (I don't understand the internals of how Babel works), but get that Babel isn't calling super() on ES5 "classes" (functions) the way I would expect. But the follow appears to work for me. I can reimplement the Array functions on my own and a possible solution to <IE10 support might be [here](http://www.bennadel.com/blog/2292-extending-javascript-arrays-while-keeping-native-bracket-notation-functionality.htm?) (which I think was the post that lead me to use the approach of returning an array rather than this).

```
class Array2 extends Array {
	constructor() {
		var arr = new Array();
		arr.foo = "bar";
		arr.__proto__ = this.__proto__;
		return arr;
	}

	bar() {
		console.log(this.foo);
	}	
};

class Array3 extends Array2 {
    constructor() {
        return super(...arguments); // Remove when browser support is added.
    }
};

class Array4 extends Array3 {
    constructor() {
        let _this = super();
        _this.foo = "baz" // Change _this to this when browser support is added
        return _this;
    }
}

```
