### ISSUE TITLE
Support TS instantiation expression

### ISSUE THREAD

**Issue by sosukesuzuki** [babel/babel#14322]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

Babel does not support new TS instantiation expression https://github.com/microsoft/TypeScript/pull/47607

```ts
function makeBox<T>(value: T) {
    return { value };
};

const makeStringBox = makeBox<string>;  // (value: string) => { value: string }
const stringBox = makeStringBox('abc');  // { value: string }

const ErrorMap = Map<string, Error>;  // new () => Map<string, Error>
const errorMap = new ErrorMap();  // Map<string, Error>
```

### Describe the solution you'd like

Implement it.

Adds new AST node `TSInstantiationExpression`.

```ts
interface TSInstantiationExpression {
  type: "TSInstantiationExpression";
  expression: Expression;
  typeParameters: TSTypeParameterInstantiation;
}
```

### Describe alternatives you've considered

Nothing.

### Documentation, Adoption, Migration Strategy

https://github.com/microsoft/TypeScript/pull/47607

**Comment by sosukesuzuki** [comment]
What do you think about new AST node `TSTypeParameterInstantiation`? /cc @bradzacher

**Comment by bradzacher** [comment]
TS's AST is done with this:
```
interface InstantiationExpressionType {
  node: ExpressionWithTypeArguments | TypeQueryNode;
}
interface ExpressionWithTypeArguments {
  expression: Expression;
  typeArguments?: TypeNode;
}
```

But in the ts-estree AST we don't have an analogous `ExpressionWithTypeArguments`.
The other places that `ExpressionWithTypeArguments` is used in the TS AST is in class implements and interface heritage.
In ts-estree we convert those cases to [`TSClassImplements`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/ast-spec/src/special/TSClassImplements/spec.ts) and [`TSInterfaceHeritage`](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/ast-spec/src/special/TSInterfaceHeritage) respectively.

Given that we have that precedence, I think we should just add a new node.
I personally don't mind a name like `TSExpressionWithTypeArguments` as it keeps it flexible and is descriptive. Your proposed structure LGTM though.

----

Also, you didn't list one usage of this feature:
```ts
type T = typeof Map<string, string>;
```

ts-estree the AST for `typeof X` is [`TSTypeOperator`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/ast-spec/src/type/TSTypeOperator/spec.ts), and the thing is a [`TypeNode`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/ast-spec/src/unions/TypeNode.ts)

It turns out that we already have an AST for almost identical code already!
```
type T = keyof Map<string, string>;
         ^^^^^^^^^^^^^^^^^^^^^^^^^ TSTypeOperator
               ^^^^^^^^^^^^^^^^^^^ TSTypeReference
```

So we don't need any changes to the AST here - just need to allow `typeof` to have type parameters!

----

So all-in-all (naming aside), the proposed changes would just be:

```ts
type Expression = Expression | NewNode;
interface NewNode {
  type: "NewNode";
  expression: Expression;
  typeParameters: TSTypeParameterInstantiation;
}
```

**Comment by sosukesuzuki** [comment]
Sorry, I have been meaning to work on this, but I am so busy that I don't think I will have enough time.

**Comment by nicolo-ribaudo** [comment]
Don't worry, I can do it!

**Comment by nicolo-ribaudo** [comment]
@bradzacher I ended up re-using `TSExpressionWithTypeArguments`, since apparently we already had that node.
