### ISSUE TITLE
Why is super() in a non-constructor allowed in loose mode?

### ISSUE THREAD

**Issue by callumlocke** [babel/babel#1435]
I was playing around with this [in the REPL](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=true&spec=false&playground=false&code=class%20Foo%20extends%20Bar%20%7B%0A%20%20someMethod()%20%7B%0A%20%20%20%20super.someMethod()%3B%0A%20%20%20%20super()%3B%0A%20%20%7D%0A%7D%0A):

```js
class Foo extends Bar {
  someMethod() {
    super.someMethod();
    super();
  }
}
```

The lines `super.someMethod();` and `super();` both give exactly the same output. MDN's [docs on super](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super) say calling it as a function only calls the parent's constructor, not other methods. Then I noticed if you [turn off loose mode](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=class%20Foo%20extends%20Bar%20%7B%0A%20%20someMethod()%20%7B%0A%20%20%20%20super.someMethod()%3B%0A%20%20%20%20super()%3B%0A%20%20%7D%0A%7D%0A), you get an error: "Direct super call is illegal in non-constructor, use super."someMethod"() instead".

I'm confused... why would `super()` in a non-constructor be a loose mode thing? It's not mentioned on [this page](https://babeljs.io/docs/usage/loose/).

**Comment by sebmck** [comment]
You can only use `super()` in a derived constructor, yes.

December 24, 2014 Draft Rev 30

> Additional early error for super() in non-constructor methods. (Already had an error for new super()).

**Comment by callumlocke** [comment]
But why is it allowed in loose mode? What's the benefit of being able to use `super()` instead of `super.someMethod()`? My understanding of loose mode is it's to enable simpler transformations (that might not cover all edge cases), not to permit non-compliant syntax.

**Comment by sebmck** [comment]
It's also to allow an easier migration path. There was a lot of code written with the old usage. Imports/exports are allowed anywhere instead of only at the top level in loose mode for example. Unsure if the migration path was the reason that you're allowed to use `super()` in non-derived constructors, it's either that or that it was just neglected since the `"Direct super call is illegal in non-constructor, use super."someMethod"() instead"` check isn't even in the same code path since an [entirely different set of methods](https://github.com/babel/babel/blob/master/src/babel/transformation/helpers/replace-supers.js#L37-38) get called for `super` in loose mode.

**Comment by callumlocke** [comment]
Ah ok I didn't realise that was old usage. Makes sense, thanks.
