### ISSUE TITLE
Conflict between local & plugin version of babel

### ISSUE THREAD

**Issue by josephsavona** [babel/babel#1438]
Currently the plugin API checks that the version of babel used by a plugin is *identical* to the one that is running the transformation, [via an `instanceof` check](https://github.com/babel/babel/blob/master/src/babel/transformation/transformer.js#L89-L91):

```
  // validate Transformer instance
  if (!(file instanceof File)) {
    throw new TypeError(messages.get("transformerNotFile", this.key));
  }
```

This makes it difficult to develop reusable plugins that can be shared in different environments. Even when the version numbers are compatible/identical, the plugin will have its own instances of functions/classes. Is there a recommended way around this? 

Using `instanceof` is generally error-prone, as an object from a different VM context (frames, etc) could fail this check. Would duck-typing be sufficient here? I'm happy to work on a PR.

cc @amasad

**Comment by sebmck** [comment]
Yeah, this was an oversight on my behalf. I added an alternate plugin API in the form of:

```javascript
module.exports = function (babel) {
  return new babel.Transformer("foo-bar", {
    // visitors
  });
};
```

The same version of babel needs to be used in order to avoid internal API issues. See #1244 for related discussion.

**Comment by josephsavona** [comment]
That's perfect! thanks @sebmck

**Comment by amasad** [comment]
@DmitrySoshnikov can use this with all transforms?

**Comment by DmitrySoshnikov** [comment]
Hm, yeah, this workaround seems to work, although it seems it will be creating a new instance of the transformer every time :( OK, I can switch for now to this approach.

**Comment by sebmck** [comment]
@DmitrySoshnikov 

> although it seems it will be creating a new instance of the transformer every time

[Nope!](https://github.com/babel/babel/blob/master/src/babel/transformation/file/plugin-manager.js#L8-20)

**Comment by DmitrySoshnikov** [comment]
Ah, that's good, thanks :) Though, the API was probably more clean in the previous approach (since it's hard to explain how and why the babel version you require and the one which is passed as a parameter differ from each other). OTOH, if you're not supposed to require the babel module manually anymore, and just always receive it as a param, then it's fine.

**Comment by sebmck** [comment]
Yeah, I've updated all the plugin docs to use the `babel` argument so it *should* be fine.

**Comment by DmitrySoshnikov** [comment]
BTW: in case it would be creating new transform each time, then the problem of "init time" (for which we currently use handler of the `Program` node) would be solved naturally -- all "per-file" data could be stored as just instance properties of the transformer. Not proposing to change it (since memoizing is actually good for performance), but just an observation :) For now using `Program` to init data per file seems works well.

**Comment by sebmck** [comment]
Yeah, I've been thinking of ways to expose the `TransformerPass` since that's *basically* where file-specific data should be stored. Only problem is how to expose it. Adding it as another argument to the visitor doesn't seem very nice (already up to 4 arguments, `node`, `parent`, `scope` and `file`) and `this` is taken by the `TraversalPath`.

**Comment by DmitrySoshnikov** [comment]
What else can be done with the `TrasnformerPass` instance? Is the actual instance can be useful? For now the most interested for devs is mostly I guess the "init hook/event" where they can init their data. The `Program` works fine for this yet (one potential disadvantage is if by some reason you decide to traverse the `Program` twice with child sub-transforms in the same main transform, this would be already not "per transformer pass", but literally "per program", and would reset your collections. From this perspective, having some simple `onPass` hook would work better (still the `Program` can be used if devs will need exactly "per-program" collections, but not per "full pass").

OTOH, if devs can do something useful with the `TransformerPass` it might worth exposing it, will think about it.

**Comment by sebmck** [comment]
A `TransformerPass` is just a [very simple class](https://github.com/babel/babel/blob/master/src/babel/transformation/transformer-pass.js) that maintains the relationship between a `Transformer` and it's `File`.
