### ISSUE TITLE
[Bug]: Right-Hand Side of 'instanceof' is not an Object

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14406]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
function v1() {
    let v1 = new.target;    
}
var v3 = new v1();
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABANwIwAoCUiDeAoRQxAGwFMoVVEBeRMUgdwDooBDAJwHNyBuIxPAF88yDigDMNOo0pYeQA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=&version=7.17.8&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

Inside the function, this bug will be triggered when the variable name and function name happen to be the same and the variable is a new target. The transpiled code run by node will report the following error:
```shell
 var v1 = this instanceof v1 ? this.constructor : void 0;
                ^

TypeError: Right-hand side of 'instanceof' is not an object
```

### Environment

- babel
- ├── @babel/cli@7.17.0=6
- ├── @babel/generator@7.17.3
- ├── @babel/plugin-transform-runtime@7.17.0
- ├── @babel/preset-env@7.16.11
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by nicolo-ribaudo** [comment]
This can be fixed by copying something like https://github.com/babel/babel/blob/99842ace6e73ec3d2af1a858a816082db11b881a/packages/babel-helper-create-class-features-plugin/src/fields.ts#L192 to https://github.com/babel/babel/blob/99842ace6e73ec3d2af1a858a816082db11b881a/packages/babel-traverse/src/scope/index.ts#L367, and then calling it in https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-new-target/src/index.ts#L57.
