### ISSUE TITLE
[Bug]: path.skip() in enter() skips exit()

### ISSUE THREAD

**Issue by nickpdemarco** [babel/babel#14480]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

Given source code:
```js
const x = {foo:'foo'}
```

And a simple transformer:
```js
export default function (babel) {
  const { types: t } = babel

  return {
    visitor: {
      ObjectExpression: {
        enter(path) {
          //path.skip()
        },
        exit(path) {
          path.node.properties[0].key.name = 'bar'
        },
      },
    },
  }
}
```

We can see that uncommenting `path.skip` will cause the exit function to never be called and manipulate the source code. I think this is incorrect - or at least unintuitive. 

### Current and expected behavior

Current behavior: Babel skips the call to `exit()` if `skip` is called in `enter`. 
Expected behavior: We skip children, but not the current node, when `skip()` is called. 

### Environment

- Babel: 7.16.22, 
- Transformer: babelv7-7.16.12

See the [AST Exporer example here](https://astexplorer.net/#/gist/e92b2e9b819e4eca5816d4135283bea3/8a41016ab41a0ee5ab5b177788b7d819ed1e5c9e)

### Possible solution

Alternatively, Babel could provide a sibling function to `skip` like `skipChildren` which, as named, skips the children but not the current node. 

In general, we need some way to express "skip my children but call my exit visitor".

**Comment by JLHwung** [comment]
The behaviour is expected. `path.skip()` skips `path` in current traversal context, which means:
- Any `enter()` hook registered after this listener will not be invoked
- The path's descendants will not be queued to current traversal context
- All the `exit()` hook will not be invoked

For example, in this case when multiple listeners are registered to an AST node:

```js
{
  ObjectExpression: { enter: function enter1() { path.skip() }, exit: function exit1() {} }
},
{
  ObjectExpression: { enter: function enter2() {}, exit: function exit2() {} }
}
```
After `enter1` is invoked, `enter2`, `exit1` and `exit2` will not be invoked because the `path` has been skipped. This is another use case for `path.skip()` -- to short-circuit other plugins registered after your plugin.

In your case, you can work around this issue by either calling `skipKey()`
```js
path.skipKey("properties");
```
or manually invoke the exit listener to the `path`.

`skipChildren` can be implemented from `skipKey`, so I am not sure whether `@babel/traverse` should provide it.
```js
import { VISITOR_KEYS } from "@babel/types";
function skipChildren(path) {
  for (const key of VISITOR_KEYS[path.type]) {
    path.skipKey(key)
  }
}
```

**Comment by nickpdemarco** [comment]
Interesting! Thanks for taking the time to explain and provide a workaround.

**Comment by JLHwung** [comment]
I am glad that it helps. Closing this issue as the behaviour is intended.
