### ISSUE TITLE
No matching version found for @babel/types@^7.18.2.

### ISSUE THREAD

**Issue by jagadeshlal** [babel/babel#14597]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

[INFO] npm ERR! code ETARGET
[INFO] npm ERR! notarget No matching version found for @babel/types@^7.18.2.
[INFO] npm ERR! notarget a package version that doesn't exist.

### Current and expected behavior

npm link show 7.18.2 is available but i see zero downloads, so our application is unable to download the latest package, even though it shows new version is available.

### Environment

- Babel Version: 7.18.2
- [7.18.2](https://www.npmjs.com/package/@babel/traverse/v/7.18.2)

### Additional context

[INFO] npm ERR! code ETARGET
[INFO] npm ERR! notarget No matching version found for @babel/types@^7.18.2.
[INFO] npm ERR! notarget In most cases you or one of your dependencies are requesting
[INFO] npm ERR! notarget a package version that doesn't exist.
[INFO] npm ERR! notarget 
[INFO] npm ERR! notarget It was specified as a dependency of '@babel/helper-simple-access'
[INFO] npm ERR! notarget

**Comment by kiransnair** [comment]
Same issue we are also facing. Not able to download the latest package even though in the version it shows latest is 7.18.2
@babel/types
@babel/helper-simple-access
@babel/helpers
@babel/helper-replace-supers
Please fix your release cycle. Either do not expose the new release unless it is completely available for all users.

**Comment by nicolo-ribaudo** [comment]
The package is on npm: https://www.npmjs.com/package/@babel/types/v/7.18.2

> npm link show 7.18.2 is available but i see zero downloads

Yeah, the download count is not updated in real time (sometimes it takes up to a day to show something)

If you are using a proxy/cache between you and npm, it's likely that it's cache is stale and thus you cannot see the new package (this is what causes this error 99% of the times). Otherwise, pelase report this bug to npm.

@kiransnair We cannot know or control who has access to public packages on npm, because most companies have buggy proxies or caches between their developers and the npm registry. If that's your case, please fix them.
