### ISSUE TITLE
[Bug]: Argument Name Clash will Only be Detected if There is a Bug in the Following Code

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14614]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
function f(v1, v1) {}
for (let i in []) {
    return false;
}
```
Here is [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABMAFANwIwBpGYJSIDeAvgFDBwBOiKANgKZSIzNIDaAugYaYn4pUYhKSYAENaAZ3oBuUsSA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env%2Cflow&prettier=false&targets=&version=7.18.3&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

Babel has a strange phenomenon in bug detection during translation. At poc.js, there are two bugs. The first is "argument name clash", and the other one is "'return' outside of function". However, it is interesting that the first bug will be reported only when there is a bug in the subsequent program. If we delete return false, the program will be transpiled.

### Environment

- babel 
- - ├── @babel/cli@7.17.6
- - ├── @babel/generator@7.17.7
- - ├── @babel/plugin-transform-runtime@7.17.0
- - ├── @babel/preset-env@7.16.11
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by xiawenqi** [comment]
This is a problem with babel-parser with  "unambiguous" sourceType.

In your example, the exception "argument name clash" is fine with "script" source type(defaults to non-strict mode), but will raise an exception in "module" source type(defaults to strict mode).

The code that cause this issue is here

https://github.com/babel/babel/blob/e8c4b7833075fda0a15ba0eb66dd3e2d0f3718fb/packages/babel-parser/src/index.js#L19-L57

In "unambiguous" mode, babel parser first try to parse the code with "module" source type, when an exception is raised, it try again to parse with "script" source type, if there is still an exception, it throws the exception caught in the first parse(which is in strict mode), therefore the "argument name clash" exception is raised.

A work around might be assign the proper sourceType if possible(in your case, script, maybe).

A possible solution would be detect whether there is import/export in source code, and decide which error to throw. However, it is hard to decide whether it is a "module" since the parsing process is interrupted. Consider the context("unambiguous" source type), I am not sure if it is necessary.

**Comment by nicolo-ribaudo** [comment]
Thanks @xiawenqi for your explanation, it's 100% correct. This is happening due to the "disambiguation" logic:

```js
function f(v1, v1) {}
```
is a valid script, so it's parsed as such.

```js
function f(v1, v1) {}
for (let i in []) {
    return false;
}
```
is neither a valid script nor module, so "module" has the precedence.
