### ISSUE TITLE
[Bug]: More Than One Super Call in the Construction is Incorrectly Allowed

### ISSUE THREAD

**Issue by clhiker** [babel/babel#14652]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
class envs {
    constructor(param, obj) {
        console.log(param)
    }
}
function obj2() {
    return 2;
}
function battlePlayer() {
    return 1;
}
class doSomethingMore extends envs {
    constructor() {
        super(super(), obj2());
        // super(obj2(), battlePlayer());
    }
}
b = new doSomethingMore()
```
[It's the transpiled one](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&corejs=3.21&spec=true&loose=true&code_lz=FAYwNghgzlAECmA7AbnA3sWXYgPaKgBcAnAVxEN2IAoAHCYiAWwBpZcAjAKwEpYNsgnPii4w8AHRhcAczoNmPTNgC-wYGoBmpRBQCW-dtwBM1PgOzF4hUsUSxjAbg3BtuwgfscIhQuIAKkACe8DTmylhWNnawAIzOauDQcAAmuADKuEzWABZ6iDIAslTwCAAehEgpcEio_BHCBCTklGH1QthQpLSh1F09YWycXKY8PM4dWAD0U7D9vcOjbN6-AcG9YxOq6mocsAC8sIjwAO6waZnZhHkFxVZmwEA&debug=false&forceAllTransforms=true&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=env&prettier=false&targets=Node-10.13&version=7.18.4&externalPlugins=&assumptions=%7B%22superIsCallableConstructor%22%3Atrue%2C%22skipForOfIteratorClosing%22%3Atrue%2C%22setSpreadProperties%22%3Atrue%2C%22setPublicClassFields%22%3Atrue%2C%22setComputedProperties%22%3Atrue%2C%22setClassMethods%22%3Atrue%2C%22pureGetters%22%3Atrue%2C%22privateFieldsAsProperties%22%3Atrue%2C%22objectRestNoSymbols%22%3Atrue%2C%22noNewArrows%22%3Atrue%2C%22noDocumentAll%22%3Atrue%2C%22noClassCalls%22%3Atrue%2C%22mutableTemplateObject%22%3Atrue%2C%22ignoreToPrimitiveHint%22%3Atrue%2C%22iterableIsArray%22%3Atrue%2C%22ignoreFunctionLength%22%3Atrue%2C%22enumerableModuleMeta%22%3Atrue%2C%22constantSuper%22%3Atrue%2C%22constantReexports%22%3Atrue%2C%22arrayLikeIsIterable%22%3Atrue%7D)
[It is the report error one](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&corejs=3.21&spec=true&loose=true&code_lz=FAYwNghgzlAECmA7AbnA3sWXYgPaKgBcAnAVxEN2IAoAHCYiAWwBpZcAjAKwEpYNsgnPii4w8AHRhcAczoNmPTNgC-wYGoBmpRBQCW-dtwBM1PgOzF4hUsUSxjAbg3BtuwgfscIhQuIAKkACe8DTmylhWNnawAIzOauDQcAAmuADKuEzWABZ6iDIAslTwCAAehEgpcEio_BHCBCTklGH1QthQpLSh1F09YWycXKY8PM4dWP29w6Ns3r4Bwb1jE6rqahywALywiPAA7rBpmdmEeQXFVmbAQA&debug=false&forceAllTransforms=true&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=env&prettier=false&targets=Node-10.13&version=7.18.4&externalPlugins=&assumptions=%7B%22superIsCallableConstructor%22%3Atrue%2C%22skipForOfIteratorClosing%22%3Atrue%2C%22setSpreadProperties%22%3Atrue%2C%22setPublicClassFields%22%3Atrue%2C%22setComputedProperties%22%3Atrue%2C%22setClassMethods%22%3Atrue%2C%22pureGetters%22%3Atrue%2C%22privateFieldsAsProperties%22%3Atrue%2C%22objectRestNoSymbols%22%3Atrue%2C%22noNewArrows%22%3Atrue%2C%22noDocumentAll%22%3Atrue%2C%22noClassCalls%22%3Atrue%2C%22mutableTemplateObject%22%3Atrue%2C%22ignoreToPrimitiveHint%22%3Atrue%2C%22iterableIsArray%22%3Atrue%2C%22ignoreFunctionLength%22%3Atrue%2C%22enumerableModuleMeta%22%3Atrue%2C%22constantSuper%22%3Atrue%2C%22constantReexports%22%3Atrue%2C%22arrayLikeIsIterable%22%3Atrue%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

In the poc.js, super() in the constructor is called more than once, it is the wrong syntax, but it transpiled by babel.
However, if I add code to constructor:
```js
super(obj2(), battlePlayer());
```

it can report 
```shell
Container is falsy
```

### Environment

- babel 
- - ├── @babel/cli@7.17.0=6
- - ├── @babel/generator@7.17.3
- - ├── @babel/plugin-transform-runtime@7.17.0
- - ├── @babel/preset-env@7.16.11
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

**Comment by nicolo-ribaudo** [comment]
Hi! A shorter reproduction is
```js
class A extends B{
    constructor() {
        super(super());
        super();
    }
}
```

The problem is that we first transform the outer `super()` call, so the nested one gets "detatched". We can fix this bug by first transforming the nested one, and then the outer one. In practice, it means that we should store those calls in reversed orer when we collect them:
https://github.com/babel/babel/blob/facafc3dc3903e780e42aa0656f18cf75a7b3aab/packages/babel-plugin-transform-classes/src/transformClass.ts#L334-L347

We can replace the `bareSupers` set with an array, and use `.unshift` instead of `.add`.

---



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated), for example in `packages/babel-plugin-transform-classes/test/fixtures/regression/14652-nested-super-call`
1. Update the code!
1. `yarn jest transform-classes` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest transform-classes` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by nicolo-ribaudo** [comment]
Note that calling `super()` more than once is valid syntax; the bug is the `Container is falsy` error.

**Comment by dbacarel** [comment]
Hi! I thought I could give it a try.

**Comment by nicolo-ribaudo** [comment]
It's yours! Feel free to ask anything here if you need more help :)

**Comment by dbacarel** [comment]
Thanks!
