### ISSUE TITLE
[Bug]: Missing `plugin-transform-instanceof` from the npm package

### ISSUE THREAD

**Issue by f52985** [babel/babel#14882]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
a instanceof b;
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "script",
  "plugins": [
    "@babel/plugin-transform-instanceof"
  ]
}
```

### Current and expected behavior

> Cannot find package '@babel/plugin-transform-instanceof'

It seems that [plugin-transform-instanceof](https://babeljs.io/docs/en/babel-plugin-transform-instanceof) is simply missing from the npm package.

### Environment

  System:
    OS: macOS 12.4
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    npm: 8.18.0 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.15.4 => 7.18.10
    @babel/core: ^7.15.5 => 7.18.13
    @babel/plugin-proposal-class-static-block: ^7.15.4 => 7.18.6
    @babel/plugin-syntax-import-assertions: ^7.14.5 => 7.18.6
    @babel/plugin-transform-runtime: ^7.15.0 => 7.18.10
    @babel/preset-env: ^7.15.6 => 7.18.10
    @babel/runtime: ^7.15.4 => 7.18.9

**Comment by nicolo-ribaudo** [comment]
When you directly use a plugin you must install it

**Comment by f52985** [comment]
Is there a reason that this specific plugin is not installed by installing babel, unlike other plugins?

**Comment by nicolo-ribaudo** [comment]
The reason is that the hoisting algorithm of package managers does not always hoist dependencies. If you have a dependency `a` that has a dependency `b`, `require("b")` in your app will _often_ work (even if you didn't explicitly install `b` as a dependency), but not always. This is because your package manager could either create this structure:
- `node_modules`
  - `a`
    - `node_modules`
      - `b`

or this structure:
- `node_modules`
  - `a`
  - `b`

probably the other plugins you tested have been hoisted in the second way, while `@babel/plugin-transform-instanceof` in the first way.
