### ISSUE TITLE
Error when compiling lodash-es/lodash

### ISSUE THREAD

**Issue by wesleycho** [babel/babel#1489]
I am seeing this error when compiling with SystemJS via Babel:
```
ReferenceError: path/to/repo/jspm_packages/npm/lodash-es@3.8.0/chain.js: unknown node of type undefined with constructor "Function"
    at CodeGenerator.print (evalmachine.<anonymous>:6490:13)
    at print (evalmachine.<anonymous>:6363:20)
    at CodeGenerator.Property (evalmachine.<anonymous>:6143:5)
    at CodeGenerator.print (evalmachine.<anonymous>:6473:22)
    at print (evalmachine.<anonymous>:6363:20)
    at evalmachine.<anonymous>:6506:7
    at arrayEach (evalmachine.<anonymous>:42046:9)
    at Object.default (evalmachine.<anonymous>:43539:9)
    at CodeGenerator.printJoin (evalmachine.<anonymous>:6505:22)
    at Function.print.join (evalmachine.<anonymous>:6374:20)
    at Function.print.list (evalmachine.<anonymous>:6381:13)
    at CodeGenerator.ObjectExpression (evalmachine.<anonymous>:6117:11)
    at CodeGenerator.print (evalmachine.<anonymous>:6473:22)
    at print (evalmachine.<anonymous>:6363:20)
    at evalmachine.<anonymous>:6506:7
    at arrayEach (evalmachine.<anonymous>:42046:9)
```
It should be noted that I don't see this with Traceur, or any other component with lodash-es.

The only place where the `Function` constructor is used in lodash is in the `string/template` module, which is not a dependency of any component in the chain api, so I am confused by this error.

**Comment by sebmck** [comment]
[I can't seem to replicate this.](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=import%20chain%20from%20'.%2Fchain%2Fchain'%3B%0Aimport%20commit%20from%20'.%2Fchain%2Fcommit'%3B%0Aimport%20lodash%20from%20'.%2Fchain%2Flodash'%3B%0Aimport%20plant%20from%20'.%2Fchain%2Fplant'%3B%0Aimport%20reverse%20from%20'.%2Fchain%2Freverse'%3B%0Aimport%20run%20from%20'.%2Fchain%2Frun'%3B%0Aimport%20tap%20from%20'.%2Fchain%2Ftap'%3B%0Aimport%20thru%20from%20'.%2Fchain%2Fthru'%3B%0Aimport%20toJSON%20from%20'.%2Fchain%2FtoJSON'%3B%0Aimport%20toString%20from%20'.%2Fchain%2FtoString'%3B%0Aimport%20value%20from%20'.%2Fchain%2Fvalue'%3B%0Aimport%20valueOf%20from%20'.%2Fchain%2FvalueOf'%3B%0Aimport%20wrapperChain%20from%20'.%2Fchain%2FwrapperChain'%3B%0A%0Aexport%20default%20%7B%0A%20%20'chain'%3A%20chain%2C%0A%20%20'commit'%3A%20commit%2C%0A%20%20'lodash'%3A%20lodash%2C%0A%20%20'plant'%3A%20plant%2C%0A%20%20'reverse'%3A%20reverse%2C%0A%20%20'run'%3A%20run%2C%0A%20%20'tap'%3A%20tap%2C%0A%20%20'thru'%3A%20thru%2C%0A%20%20'toJSON'%3A%20toJSON%2C%0A%20%20'toString'%3A%20toString%2C%0A%20%20'value'%3A%20value%2C%0A%20%20'valueOf'%3A%20valueOf%2C%0A%20%20'wrapperChain'%3A%20wrapperChain%0A%7D%3B) What version of Babel are you using?

> The only place where the `Function` constructor is used in lodash is in the string/template module, which is not a dependency of any component in the chain api, so I am confused by this error.

Not relevant since it's about one of the AST nodes being a `Function` for some reason.

**Comment by wesleycho** [comment]
I am on 5.2.17 - it occurred on 5.2.15 for me as well.

**Comment by wesleycho** [comment]
Wow, that was fast - thanks a lot!
