### ISSUE TITLE
Unnecessary IIFE created when const/let-created variable is used in a filter

### ISSUE THREAD

**Issue by mzgol** [babel/babel#1498]
The following JS:
```js
{
    let a = 4;
    let l = [1, 2, 6].filter(function (x) {
        return x > a;
    });
}
```
is transpiled to:
```js
"use strict";

{
    (function () {
        var a = 4;
        var l = [1, 2, 6].filter(function (x) {
            return x > a;
        });
    })();
}
```

The function wrapper seems unnecessary as the variable is not modified in the loop. If there was another variable named the same outside of the block, e.g:
```js
let a = 3;
{
    let a = 4;
    let l = [1, 2, 6].filter(function (x) {
        return x > a;
    });
}
```
it could transpile to:
```js
"use strict";

var a = 3;
{
    var a_ = 4;
    var l = [1, 2, 6].filter(function (x) {
        return x > a_;
    });
}
```
instead of what's currently generated:
```js
"use strict";

var a = 3;
{
    (function () {
        var a = 4;
        var l = [1, 2, 6].filter(function (x) {
            return x > a;
        });
    })();
}
```

`babel-core@5.2.16`

**Comment by sebmck** [comment]
It's going to be tricky to handle:

```javascript
{
  let z = 'z1 value';
  f1 = function() { return z; };
}
{
  let z = 'z2 value';
  f2 = function() { return z; };
}
f1();
f2();
```

then.

**Comment by sebmck** [comment]
Actually yeah, it's going to require tracking of sibling/child scopes which is problematic from a memory standpoint since scope instances aren't constant and are repeatedly recreated from cache. Going to close this and mark it as a revisit since this may require significant changes to scope tracking to track child and sibling scopes in order to do it in a very performant way. I'm considering rewriting the scope tracking anyway to be more performant so when/if that happens I'll keep this in mind.

**Comment by mzgol** [comment]
OK, I understand.

Note that @olov's [defs](https://github.com/olov/defs) transpiles this:
```js
var f1, f2;
{
  let z = 'z1 value';
  f1 = function() { return z; };
}
{
  let z = 'z2 value';
  f2 = function() { return z; };
}
f1();
f2();
```
to this:
```js
var f1, f2;
{
	var z = 'z1 value';
	f1 = function() { return z; };
}
{
	var z$0 = 'z2 value';
	f2 = function() { return z$0; };
}
f1();
f2();
```
so it's definitely possible but I understand it might not be easy.

**Comment by sebmck** [comment]
Yeah, it's definently possible. Note that `defs` has a whole lot of other problems where it can't compile let variables inside of closures (it can via the `loopClosures` but then you can't use `return`, `continue` or `break`) among many other things.

**Comment by olov** [comment]
@sebmck the trade-off in defs was that I wanted it to output zero-overhead code whenever possible and lowest-overhead-and-least-surprising code in all the other cases. Already with the introduction of defs inserting IIFE's to handle loop variables captured in inner functions, I was reluctant. I drew the line with allowing the simple cases but not transforming the complex ones (return, continue et all inside the loop with a function-captured loop-variable). But I made sure that defs would detect these cases reliably 100% and inform the user so they could rewrite the code themselves (this happened very infrequently). Just a little background.

I understand that Babel handles the situation different than defs because it wants to be a generic ESx transpiler, rather than ES5 + performant constlet, which makes a whole lot of sense.

But all of this has nothing at all to do with the fact that defs has data structures and code in place to be able to perform static analysis (fast) to output lowest-overhead code. Babel should too be able to detect when an IIFE is not necessary, with little extra static analysis overhead. Regarding your concerns ("problematic from a memory standpoint", "repeatedly recreated"): because lexical scope is static by nature defs does a single analysis pass over the code to setup scope information, links those with functions/blocks, then creates an up-pointer to scopes from all references. The guts is inside `defs-main.js` and `scope.js` and regarding loops and IIFE's or not in https://github.com/olov/defs/blob/master/defs-main.js#L402. The code is not that well documented but I spent quite some time making sure that it is both correct and fast so I'd be happy to help out if there's anything you'd like to discuss. I unfortunately don't have the bandwidth right now to contribute code to Babel, otherwise I would have been happy to do that.

Kudos for Babel!
