### ISSUE TITLE
question to runtime, polyfill and es5shim for ie8 compatibility

### ISSUE THREAD

**Issue by rs3d** [babel/babel#1507]
I'm using gulp with browserify in combination with babelify in the transform section of my package.json file.

``"browserify": {
    "transform": [
      ["babelify", { "optional": ["runtime"] }]
    ]
  }``

My wish is to make my es6 scripts working with ie8 so I activated the runtime transform above, but I'm still getting errors in IE8.

The documentation says following: 'Built-ins such as Promise, Set and Map are aliased to core-js so you can use them seamlessly without having to require a globally polluting polyfill. '

1. Do I have still have to require the polyfill for ie8 support like so: ``require('babel/polyfill');``
2. Is then the runtime transform even necessary or does the polyfill already has everything to work with ie8?
3. Do I still have to include es5shim or are its shims already included in babel/polyfill

Sorry if I'm missing something completely but I'm very new to the topic and I'm working on my initial setup.

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

I'll let this one slide though since the docs are pretty ambiguous and not the best, any contributions improving them is extremely appreciated!

> 1. Do I have still have to require the polyfill for ie8 support like so: ``require('babel/polyfill');``

Nope. You either use the runtime or the polyfill, not both.

> 2. Is then the runtime transform even necessary or does the polyfill already has everything to work with ie8?

The polyfill should. The runtime serves another purpose. It's meant for "polyfilling" in builtins automatically without global pollution.

> 3. Do I still have to include es5shim or are its shims already included in babel/polyfill

No you don't. An ES5 shim is included by default in `core-js`, yes. All `babel/polyfill` does is load in `core-js/shim` and `regenerator/runtime`.

Please see the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a> if you have anymore issues or questions. Thanks!

**Comment by rs3d** [comment]
Thank you very much for your answers! This is helping me for sure!
