### ISSUE TITLE
Infer the type of rest parameters as an array.

### ISSUE THREAD

**Issue by Mark-Simulacrum** [babel/babel#1515]
As far as I know, rest arguments to a function are an array, so the for of loop fast mode that is implemented when using Flow types can be enabled for this case.

```js
function foo(...args) {
    for (let arg of args) { }
}
```

would compile to
```js
"use strict";

function test() {
  for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
    args[_key] = arguments[_key];
  }

  var _arr = args;
  for (var _i = 0; _i < _arr.length; _i++) {
    var arg = _arr[_i];arg;
  }
}
```

as opposed to

```js
"use strict";

function test() {
  for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
    args[_key] = arguments[_key];
  }

  var _iteratorNormalCompletion = true;
  var _didIteratorError = false;
  var _iteratorError = undefined;

  try {
    for (var _iterator = args[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
      var arg = _step.value;
      arg;
    }
  } catch (err) {
    _didIteratorError = true;
    _iteratorError = err;
  } finally {
    try {
      if (!_iteratorNormalCompletion && _iterator["return"]) {
        _iterator["return"]();
      }
    } finally {
      if (_didIteratorError) {
        throw _iteratorError;
      }
    }
  }
}
```

Not sure if this is something that can easily be inferred, but a possible alternative fix would be to allow Flow-like types to propagate through the AST (so that writing `function (...args: Array)` would optimizer all for of loops referencing the `args` into the fast path.

**Comment by sebmck** [comment]
> Not sure if this is something that can easily be inferred, but a possible alternative fix would be to allow Flow-like types to propagate through the AST (so that writing `function (...args: Array)` would optimizer all for of loops referencing the args into the fast path.

This is exactly what the optional `optimisation.flow.forOf` does.

**Comment by sebmck** [comment]
Actually turns out that it wouldn't identify that binding as being an array since it would've been removed by the `es6.parameters.rest` transformer by the time it was ran. I've updated the type inference to work even if nodes are removed by using it's last type instead so you'll be able to use the `optimisation.flow.forOf` transformer (even without explicitly using type annotations).

The main reason it wouldn't be done by default is that at the end of the day you can always do:

```javascript
Array.prototype[Symbol.iterator] = function () {
  // ehehe
};
```

Which completely changes the behaviour. While it's a gross and you'll probably say it's a use-case that shouldn't be supported, it's still a use-case and a lot of stuff is done so you cover all your bases instead of leaving wide gaping holes.
