### ISSUE TITLE
[Bug]: Error in `toString` during dynamic import should result in rejected promise

### ISSUE THREAD

**Issue by f52985** [babel/babel#15261]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
var filename = {
  toString: () => { throw "toString failure"; }
}

import(filename)
.then(obj => {
  console.log("import success");
})
.catch(err => {
  console.log("import failed");
});
```

### Current and expected behavior

[REPL](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=G4QwTgBAZglgNgUwHYgLYIgXggbwFAQQAuA9gMpFgxIDmAXBABQCUWAfLsQBZgkDuEAESkKVWtBDwArmASCA3BAC-eFXhioADiTBFGsRCnTM8AOiJdkjEgCMAVu1wEIAYxJIAziUSm4JGoyCGtq6EB5SLi4IHh6CzPKqJqYuIEQuXIwIYJCYHPiEbp7eCL7-gcE6RBLwCAAmcQlK8UA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=&version=7.20.6&externalPlugins=&assumptions=%7B%7D)

The code above is transpiled into
```js
...
Promise.resolve("".concat(filename))
...
```
which results in throwing "toString failure".

However, since the exception is thrown during `toString`, the original import expression should result in [rejected promise](https://262.ecma-international.org/13.0/#sec-import-call-runtime-semantics-evaluation), and "import failed" should be printed.

### Environment

Tried at REPL (7.20.6)

**Comment by SuperSodaSea** [comment]
[Spec](https://tc39.es/ecma262/#sec-import-call-runtime-semantics-evaluation):
> [ImportCall](https://tc39.es/ecma262/#prod-ImportCall) : import ( [AssignmentExpression](https://tc39.es/ecma262/#prod-AssignmentExpression) )
> 1. Let referencingScriptOrModule be [GetActiveScriptOrModule](https://tc39.es/ecma262/#sec-getactivescriptormodule)().
> 2. Let argRef be ? [Evaluation](https://tc39.es/ecma262/#sec-evaluation) of [AssignmentExpression](https://tc39.es/ecma262/#prod-AssignmentExpression).
> 3. Let specifier be ? [GetValue](https://tc39.es/ecma262/#sec-getvalue)(argRef).
> 4. Let promiseCapability be ! [NewPromiseCapability](https://tc39.es/ecma262/#sec-newpromisecapability)([%Promise%](https://tc39.es/ecma262/#sec-promise-constructor)).
> 5. Let specifierString be [Completion](https://tc39.es/ecma262/#sec-completion-ao)([ToString](https://tc39.es/ecma262/#sec-tostring)(specifier)).
> 6. [IfAbruptRejectPromise](https://tc39.es/ecma262/#sec-ifabruptrejectpromise)(specifierString, promiseCapability).
> 7. Perform [HostImportModuleDynamically](https://tc39.es/ecma262/#sec-hostimportmoduledynamically)(referencingScriptOrModule, specifierString, promiseCapability).
> 8. Return promiseCapability.[[Promise]].

So we should transform `import(source)` into something like:
```js
let _s = source; // `source` itself should be evaluated immediately
Promise.resolve().then(() => require(`${_s}`)}) // `.toString()` evaluated in Promise
```

Notice that we can't just use ```Promise.resolve(source).then(s => require(`${s}`)})```, because if `source` is evaluated to a `Promise`, it should not be resolved and should be convert to string directly, just like `import('[object Promise]')`.

Related code:
https://github.com/babel/babel/blob/f5b52208f05157a348fdfaa0222c07a9a83fb101/packages/babel-plugin-transform-modules-commonjs/src/dynamic-import.ts#L23-L35

**Comment by JLHwung** [comment]
> (s => Promise.resolve().then(() => require(`${s}`)})) // `.toString()` evaluated in Promise

The source should not be evaluated in the promise, because the evaluation order will be affected. consider this example:

```js
var i = 0;
import(`./${++i}`)
++i;
```

If the source were evaluated in the promise, it will be `"./2"` instead of `"./1"`.

We could solve this by replacing `Promise.resolve()` to a new helper, which turns the abrupt completion into a rejected promise. But given that `import()` is a very popular feature and TS is also affected by this issue, a new compiler assumption (tentatively `importModuleNameDoesNotThrow`) to get rid of this helper sounds reasonable to me.

**Comment by SuperSodaSea** [comment]
@JLHwung I mean this:
```js
var i = 0;
(s =>
    Promise.resolve().then(() => require(`${s}`)})
)(++i); // source is ++i
```
The source itself is evaluated outside the promise, only the toString part is inside the promise.

**Comment by JLHwung** [comment]
Good point, but `toString` could execute arbitrary code:

```js
var i = 0;
import({ toString: () => `./${++i}` })
++i;
```

**Comment by SuperSodaSea** [comment]
@JLHwung You are right, the `toString()` should be executed before the `++i;`, but if we evaluate it in `.then()`, it will be after the `++i;`.

We do need a helper like this:
```js
// Maybe we can have a better name for it?
export default function _dynamicImportSpecifier(s) {
  try {
    return Promise.resolve('' + s);
  } catch(e) {
    return Promise.reject(e);
  }
}

_dynamicImportSpecifier(source).then(s => require(s)})
```
