### ISSUE TITLE
Feature Request: Provide CLI option examples in documentation

### ISSUE THREAD

**Issue by CrabDude** [babel/babel#1526]
I am unable to discern from the existing documentation how to use the CLI `--ignore` option. It would be nice to have a real example for each.

For instance, none of the following worked:

```bash
babel --ignore html ./*
babel --ignore .*html ./*
babel --ignore ".*html" ./*
babel --ignore *html ./*
babel --ignore [html] ./*
babel --ignore [.*html] ./* 
babel --ignore [*html] ./*
babel --ignore [**html] ./* 
babel --ignore [**/*html] ./*
babel --ignore ["html"] ./*
babel --ignore [".*html"] ./* 
babel --ignore ["*html"] ./*
babel --ignore ["**html"] ./* 
babel --ignore ["**/*html"] ./*
```

**Comment by sebmck** [comment]
Why are you wrapping it in `[` and `]`?

**Comment by sebmck** [comment]
Also, please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

Thanks!

**Comment by CrabDude** [comment]
@sebmck Is it not obvious from the OP I have no idea how to use the `--ignore` option from either the documentation or `-h`? And seriously, you responded twice, but won't just provide a simple example?

I'm politely assuming I don't know how to use `--ignore`, but it's equally likely that it's broken unless you care to provide me with an example.

**Comment by sebmck** [comment]
@CrabDude I pointed you towards the other repo because this repo is exclusively for Babel bugs and feature requests. The README is very succinct in this and provides all the relevant external links to find support, ask questions and to report issues on the website. I use this issue tracker to delegate my free time (which is what I use to develop Babel) and irrelevant issues are just an extreme amount of noise that I have to filter through.

**Comment by CrabDude** [comment]
@sebmck It would have taken far less of your free time to just provide an example, as noted by #1527, this now appears to be a bug.

**Comment by CrabDude** [comment]
Nm. Figured it out. Thanks.
