### ISSUE TITLE
`--ignore` ignored

### ISSUE THREAD

**Issue by CrabDude** [babel/babel#1527]
`--ignore` is ignored / not working, according to its documented use in `-h`:

```bash
# fails
babel --ignore **/*.html ./*
```

**Comment by CrabDude** [comment]
It seems the issue is `./*` at the end. This still seems like a bug as `.` and `./*` would seem to be equivalent.

**Comment by sebmck** [comment]
What is your directory/file structure? Not entirely sure what it is you're trying to do.

**Comment by CrabDude** [comment]
I have a flat directory with `.html` and `.js` files in it, and I wanted to test the `--ignore` command. As stated, I don't see the difference between `.` and `./*`.

**Comment by sebmck** [comment]
The `/` at the start refers to the root of your file system. In fact, running that command on my computer just hangs because it's too busy crawling my entire hard drive looking for files.

**Comment by CrabDude** [comment]
@sebmck Sorry. Typo. Updated. `./*` fails (not `/*` as previously written in the OP)

**Comment by sebmck** [comment]
```sh
$ babel --ignore ./*.html ./*
```

**Comment by sebmck** [comment]
`**/*.html` not matching `./*.html` is a bug in minimatch (see isaacs/minimatch#30).

**Comment by CrabDude** [comment]
Nope. None of these work (I made sure I updated first):

```bash
babel --ignore ./*.html ./*
babel --ignore **/*.html ./*
babel --ignore ./*.html ./*
babel --ignore ./*.html .
```

Only this works:

```bash
babel --ignore **/*.html .
```

**Comment by sebmck** [comment]
```sh
$ babel --ignore **/*.html .
```

works because you're passing a directory. When crawling a directory only filenames with the filename `.js`, `.es6`, `.es` and `.jsx` are compiled. When you do:

```sh
$ babel --ignore ./*.html ./*
```

Your shell is exploding the last `./*` to a list of filenames matching that pattern and is then passing it on. This behaviour is purely a result of your shell and is not influenced in any way by Babel.

The command `$ babel --ignore ./*.html ./*` does indeed work on my system so it's likely something environment or shell related.

If you need some super complicated pattern matching build system then the CLI is not for you. Integrate an already existing build system such as [grunt](https://github.com/babel/grunt-babel) or [gulp](https://github.com/babel/gulp-babel).

**Comment by CrabDude** [comment]
Interesting. Thanks & noted.
