### ISSUE TITLE
[Bug]: import meta plugin does not exists in @babel/preset-env

### ISSUE THREAD

**Issue by sungwoo91** [babel/babel#15291]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

I can't find `@babel/plugin-syntax-import-meta` plugin in packages directory.

https://github.com/babel/babel/tree/main/packages

### Current and expected behavior

Current:
- @babel/preset-env is not contain `@babel/plugin-syntax-import-meta` plugin. but document has below instruction.
- https://babeljs.io/docs/en/babel-plugin-syntax-import-meta
<img width="588" alt="image" src="https://user-images.githubusercontent.com/36779786/208423087-7d66f605-607a-42b0-9a19-132cdfe50c51.png">
- additionally, if I use the plugin directly, it still not working. 
- 
<img width="366" alt="image" src="https://user-images.githubusercontent.com/36779786/208423568-9dcff931-7ab7-431d-80ec-46b1a5719c79.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/36779786/208423620-ab42ffaa-3cb9-447f-9cef-a9404b6a685d.png">

expected:
- I can use `import.meta.url` with babel.

### Environment

    @babel/cli: ^7.16.7 => 7.19.3 
    @babel/core: ^7.16.7 => 7.19.3 
    @babel/preset-env: ^7.16.7 => 7.19.3 
    @babel/preset-typescript: ^7.16.7 => 7.18.6 
    babel-eslint: ^8.1.0 => 8.2.6 
    babel-jest: ^27.5.1 => 27.5.1 
    babel-loader: ^8.2.3 => 8.3.0 
    eslint: ^7.30.0 => 7.32.0 
    jest: ^29.2.2 => 29.2.2 
    webpack: ^4.46.0 => 4.46.0

**Comment by JLHwung** [comment]
As a syntax plugin, `@babel/plugin-syntax-import-meta` only enables `@babel/parser` to parse `import.meta`. The plugin has been [archived](https://github.com/babel/babel-archive/tree/main/packages/babel-plugin-syntax-import-meta) because the feature `import.meta` has been materialized. In other words, Babel parser always support it as long as you are using a recent version. You can safely remove this plugin.

Babel does not transform `import.meta` because only an import [host](https://tc39.es/ecma262/#host) can provide such information, e.g. browsers or bundlers like webpack. Webpack 4 does not support `import.meta`, please upgrade to webpack 5.
