### ISSUE TITLE
[Bug]: transform error with @babel/plugin-transform-block-scoping@7.20.11

### ISSUE THREAD

**Issue by geekrainy** [babel/babel#15314]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const maxLength = 3;
const arr = []
const colors = {
  white: ['#fff', '#fafafa'],
  black: ['#000', '#333'],
}

for (let i = 0; i < maxLength; i++) {
  const colorItem = []
  Object.keys(colors).forEach(color => {
    const c = colors[color][i]
    if (c) {
      colorItem.push(c)
    }
  })
  arr.push(...colorItem)
}
```

### Configuration file name

.babelrc

### Configuration

{
  "presets": [
    "@babel/preset-env"
  ]
}

### Current and expected behavior

Internal Babel error: path is not in loop. Please report this as a bug.

### Environment

- Babel version: 7.20.11
- Node: Node 16.16.0
- npm version: 8.11.0
- OS: macOS 13.0.1

**Comment by liuxingbaoyu** [comment]
Are you still using other plugins? I tried it in the repl with no errors.

**Comment by geekrainy** [comment]
Problem caused by external plugins, fixed.

**Comment by DmitryLen** [comment]
The issue has gone after I had removed all of the "plugins" and one of the "presets" inside the babel config file `.babelrc` (see screenshot example).

After the issue is gone, I put the removed code of "plugins" and "presets" back.
And everything works fine!

<img width="974" alt="Screenshot 2023-03-01 at 21 46 31" src="https://user-images.githubusercontent.com/101333167/222248678-98d038a1-bbec-42d0-8c65-3b748df103c7.png">
