### ISSUE TITLE
[Bug]: @babel/preset-typescript parses ImportDeclaration as ExportNamedDeclaration

### ISSUE THREAD

**Issue by rhashimoto** [babel/babel#15409]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
// Install @babel/core and @babel/preset-typescript, then execute this file
// with nodejs (I'm not using babel-cli).

const babelOptions = {
  filename: 'main.ts',
  presets: ['@babel/preset-typescript'],
  plugins: [myPlugin]
};

const codeToTranspile = `import foo from 'bar';`;
require("@babel/core").transform(codeToTranspile, babelOptions);

function myPlugin() {
  return {
    visitor: {
      ImportDeclaration(path) {
        console.log('ImportDeclaration');
      },

      ExportNamedDeclaration(path) {
        console.log('ExportNamedDeclaration');
      }
    }
  }
}
```

### Configuration

I'm not using a config file. I'm passing options directly to `transform()`.

### Current and expected behavior

The code I'm passing to Babel is a single import statement. I'm using a plugin that does nothing except output to the console when encountering an ImportDeclaration or an ExportNamedDeclaration.

When I run the script, the output is "ExportNamedDeclaration". Since the input is an import statement, the output is expected to be "ImportDeclaration" instead.

### Environment

 System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 18.13.0 - /usr/bin/node
    Yarn: 3.3.1 - /usr/bin/yarn
    npm: 8.19.3 - /usr/bin/npm
  npmPackages:
    @babel/core: ^7.20.12 => 7.20.12 
    @babel/preset-typescript: ^7.18.6 => 7.18.6 

### Additional context

The problem appears to be in Typescript handling somewhere, because if I comment out the presets configuration, then I get the expected output ("ImportDeclaration").

When I enter that line of code on online AST parsers, like https://astexplorer.net/ and https://ts-ast-viewer.com/, the expected nodes are produced.

**Comment by JLHwung** [comment]
To clarify, the parser is working as expected, it does not parse `import foo from 'bar';` into an `ExportNamedDeclaration`.

What's happening here is that
1. the import declaration `import foo from 'bar';` is removed before the `ImportDeclaration` visitor is invoked, because the imported value is not used.
2. In this case, after all import are removed, Babel emits `export {}`, which is then captured by your plugin visitor.
 
Rationale:
(1) is for backward compatibility to TS < 3.8 when `tsc` will elide unused imports.
(2) is for integration with other tools: So that they will recognize that this file is a module file. This is also the `tsc` behaviour.

Please specify `{ onlyRemoveTypeImports: true }` so that the import is intact and your plugin should work in this case. 

```ts
{
  presets: [
    ['@babel/preset-typescript', { onlyRemoveTypeImports: true }]
  ]
}
```

This is also future-proof as `onlyRemoveTypeImports: true` will be the Babel 8 default.
