### ISSUE TITLE
[Bug]: `export { type <ident> }` doesn't mark `<ident>` as a type

### ISSUE THREAD

**Issue by lucacasonato** [babel/babel#15493]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```ts
import { A } from "./a.js";
export { type A };
```

### Current and expected behavior

Current:

```js
import { A } from "./a.js";
export {};
```

Expected:

```js
export {};
```

### Environment

Repl as of 2023-03-13

### Possible solution

Mark `<ident>` as a type, just like you would with `const a: <ident> = 1;`.

### Additional context

TS has the correct behaviour: https://www.typescriptlang.org/play?isolatedModules=true#code/PTAECMDoBcGcCgCWBbADgewE7VAb1AIKgC+oAZpusqAESTACGkAVrDQNzwCmAHhtnlDQAnqi6ES7IA

SWC has the same bug: https://github.com/swc-project/swc/issues/7076

**Comment by nicolo-ribaudo** [comment]
This is a bug in the logic that `@babel/plugin-transform-typescript` uses to determine if an imported binding is only referenced in type positions, that happens at https://github.com/babel/babel/blob/48089fb29faf9c167c5ef2130f92a2f652b6d378/packages/babel-plugin-transform-typescript/src/index.ts#L676-L691

The problem is probably that, when we introduced the `export { type A }` syntax we consider it in the `isInType` function used above.

If anyone wants to contribute a fix, you can use https://astexplorer.net/ to see the shape of the AST generated by Babel (make sure to select JavaScript as the language, `@babel/parser` as the parser, and to enable the TypeScript plugin in `@babel/parser`'s options!) and add it to the cases in `isInType`.

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test in https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-typescript/test/fixtures/imports, copying one of the existing import elision tests (only `input.ts`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest transform-typescript` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest [name-of-the-package-to-test]` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by magic-akari** [comment]
```TypeScript
// foo.ts
export class Foo {
    static {
        console.log(1);
    }
}
```

```TypeScript
// main.ts
import { Foo } from "./foo";

export { type Foo };
```

**Comment by nicolo-ribaudo** [comment]
TypeScript's behavior here is not affected by the contents of the imported module.

**Comment by magic-akari** [comment]
> TypeScript's behavior here is not affected by the contents of the imported module.

TypeScript with verbatimModuleSyntax
https://www.typescriptlang.org/play?isolatedModules=true&verbatimModuleSyntax=true&ts=5.1.0-dev.20230313#code/PTAEAEDcFMCcCMCGAXAlgWwLIHsAmBXAG2gGUBPAO2UQA8AuUZWfaAKBFHgDpkBnVjAAdssZKADeoAIKgAvqABmsbOlAAiLsERcAVrzUBuVtBrDRExmUHRpcg0A
