### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by daudmalik06** [babel/babel#15559]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

n/a

### Configuration file name

package.json

### Current and expected behavior

n/a

### Environment

current master branch of babel

### Additional context

Hello maintainers,

I wanted to bring to your attention that after installing the package, I ran a vulnerability scan with vulert abom on the yarn.lock(https://github.com/babel/babel/blob/main/yarn.lock) file and discovered that there are over 12 vulnerable dependencies present. As these vulnerabilities can potentially impact the security of the entire project, I am unsure whether to report this under responsible disclosure.

For your reference, here is a link to the report of the package-lock file I scanned: https://vulert.com/vuln-scan/list/06715aab-999f-436f-80ef-ab060a62b172

I recommend that we take immediate action to address these vulnerabilities and ensure the security of the project. Please let me know if you require any further information.

Thank you.

**Comment by nicolo-ribaudo** [comment]
Hi! We check vulnerabilities as we get notified about them, and when we don't update a dependency is because the vulnerability doesn't actually affect us.

Some examples from the report you linked:
- `shell-quote` is in our dependencies three because it's used by `browserify`, which we use in out tests. Browserify only uses that library when it's called through its CLI, but we don't rely on Browserify's CLI.
- `json-schema` is in our dependencies three because it's used by [jsprim](https://github.com/TritonDataCenter/node-jsprim) in its [`validateJsonObjectJS`](https://github.com/TritonDataCenter/node-jsprim/blob/017f74473e55872cf71113bec35ce46de74fbe17/lib/jsprim.js#L529) method. `jsprim` is in our dependencies because it's used by [http-signature](https://github.com/TritonDataCenter/node-http-signature/blob/391fbe4864c2daef0c04345c987e5aa4d44c3ba1/lib/signer.js#L7), but `http-signature` never calls the `validateJsonObjectJS`.

The other vulnerabilities are similar. A PR to update those dependencies in our lockfile would be accepted, but it will have no effect on the security of the project.
