### ISSUE TITLE
[Bug]: Babel generated code using browser babel.min.js only has a comment after return statement so javascript returns null

### ISSUE THREAD

**Issue by danielbradley** [babel/babel#15567]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```
<script type="text/babel">

	function CreateHeading()
	{
		return <h1>Heading</h1>
	}

	var r = document.getElementById( "root" );

	if ( r )
	{
		var page = CreateHeading();
		var root = ReactDOM.createRoot( r );
			root.render( page );
	}

</script>
```

### Configuration

Not relevant

### Current and expected behavior

The above Input Code is currently generating the following Javascript code within Script Element 1:

```html
<script>
"use strict";

function CreateHeading() {
    return /*#__PURE__*/
    React.createElement("h1", null, "Heading");
}
var r = document.getElementById("root");
if (r) {
    var page = CreateHeading();
    var root = ReactDOM.createRoot(r);
    root.render(page);
}
</script>
```

This runs as long as Babel is generating the code.
However, if you move the code to a normal Javascript file, the **return** statement in CreateHeading returns null because there is a newline before the call to React.createElement, which causes Javascript's automatic semi-colon insertion.

See:
[return - Javascript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/return#automatic_semicolon_insertion)

This can be avoided by ensuring that a return is surrounded by parentheses.

```html
<script>
"use strict";

function CreateHeading() {
    return ( /*#__PURE__*/
    React.createElement("h1", null, "Heading") );
}
var r = document.getElementById("root");
if (r) {
    var page = CreateHeading();
    var root = ReactDOM.createRoot(r);
    root.render(page);
}
</script>
```

### Environment

https://unpkg.com/@babel/standalone@7.21.4/babel.min.js
Node is not in use
npm is not in use
OS macOS 13.2.1

Seems to affect both
Safari 16.3 (18614.4.6.1.6)
Chrome 112.0.5615.49

### Possible solution

See above. It is suggested that the return value is surrounded by parentheses.

**Comment by nicolo-ribaudo** [comment]
This has been fixed in the latest releases of Babel, make sure to upgrade to 7.22.0!

https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&corejs=3.28&spec=false&loose=false&code_lz=FASAZgrgdgxgLgSwPZQAQGEBOBTAhnbACTwBMEoBzACgEpQBvUEHOCTNAHgAsBGAPmK4ylDgHpefUAF9goAG65MqJQF5UJJDAgBbbFDgA6CtjgBRADbZd-gEIBPAJIkqqAESYkSOK9Q0A3LIgCGCoLkp0IIwgIApKAA64xqhqWHgEgsLU_kyxyp5wyagASnjwACIA8gCyBjA4-NhF-WG-AdHM-QY4UCTYmC4JSdkgUkA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.22.4&externalPlugins=%40babel%2Fplugin-proposal-explicit-resource-management%407.22.0&assumptions=%7B%7D
