### ISSUE TITLE
[Bug]: inputSourceMap does not accept boolean as parameter

### ISSUE THREAD

**Issue by rgascons** [babel/babel#15772]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

This code does not transpile in TS:
```ts
const { code } = transformFromAstSync(transformedAst, undefined, {
    presets: [presetReact],
    // ts(2322): Type 'boolean' is not assignable to type 'InputSourceMap'.
    inputSourceMap: false
});
```

However, the documentation shows that passing a boolean is possible: https://babeljs.io/docs/options#source-map-options

### Current and expected behavior

- Current:
You can't pass a boolean to inputSourceMap
- Expected:
You can pass a boolean to inputSourceMap

### Environment

- @babel/core 7.16.7
- Node v16.15.0
- Yarn: 3.5.1
- npm: 8.5.5

**Comment by JLHwung** [comment]
TS throws because `@types/babel__core` typed this option as
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8da1784017c4e825b7bc347204446d4cd5c2c585/types/babel__core/index.d.ts#L248

```ts
inputSourceMap?: InputSourceMap | null | undefined;
```

However, this package is not maintained here, please file an issue to https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by rgascons** [comment]
Discussion continues here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/66036
