### ISSUE TITLE
[Bug]: `path.replaceWith()` throws a `RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by lorenzoferre** [babel/babel#15873]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const code = `var a = -"1"; var b = ~1;`
var ast = parse(code);
traverse(ast, {
    UnaryExpression(path) {
        const { confident, value } = path.evaluate();
        if (!confident) return;
        const valueNode = t.valueToNode(value);
        path.replaceWith(valueNode);
    }
});
```
https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAIwIYIKYBs4DMoRHAIgAFk10B6AY2lQIG4AoUSWOAKjiQGc54c9CJFBnIwAnmFRd6TcNHgB9AOaoAdqihIYqbLnzFSIles0xoM6qq7xjGrToC8cZWrvaAdABNUWJAFd0GEYGS2s4am84JwByADckKE4ogD8ARjo4eMSEKLgAWgJUgmjgrM4wp0N0dzAErlQACgjUAEpgqvcYTViNeobuGAAaOABvBjgJuABVVQSxAFEADzAoKS5gCFUG2pgACxbR8cnj0PgR8M2sYG9VIcykdD8dAF9cnd33VHjH-wa2o-OE2AWDgDQAhJYrjcYAdVjA_FBVIxAZNTvdHqgAHIQSJOGDub5PAAqEGx3gahNayJRcHe7lWYHQSEoqAA6sA9hSHk8yVSAXBngxni0GCFNmEIH4YGApblbKZGgNhudqCAQGoYFwAFzYB71AX_UIQdCodzoCBKBqS6VS9zNNpAA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.22.10&externalPlugins=&assumptions=%7B%7D

### Current and expected behavior

Excpted output: `var a = -1; var b = -2;`
`path.evatluate()` and `t.valueToNode(value)` produce the correct output, whereas `path.replaceWith(valueNode)` throws a rangeError exception.

### Environment

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.22.5 => 7.22.10
    @babel/types: ^7.22.5 => 7.22.10

**Comment by JLHwung** [comment]
The behaviour is expected. In the use case, the node `UnaryExpression(-1)` is essentially cloned through `path.evaluate` and `t.valueToNode`. Then `path.replaceWith()` will requeue the new replaced node so that Babel can visit it, which eventually causes an infinite recursion. Note that `path.replaceWith()` will not check deep equality between the old node and replaced node, due to heavy computation costs. 

As a workaround, try to evaluate the argument of the "-" unary expression after cancelling out paired "-":

```js
traverse(ast, {
    UnaryExpression(path) {
        if (path.operator === "-") {
          if (path.get("argument").isUnaryExpression({ operator: "-" }) {
             path.replaceWith(path.get("argument").get("argument"))
          } else {
             // evaluate path.get("argument")
             // ...
             path.get("argument").replaceWith(newNode)
          }
        } else {
          // evaluate path
          // ...
        }
    }
});
```

**Comment by nicolo-ribaudo** [comment]
It causes infinite recursion because it's injecting a new UnaryExpression node in your AST, and that node is thus being traversed again by your `UnaryExpression` visitor.

Another option is to call `path.skip()` after `path.replaceWith`, to tell Babel that it should not continue traversing the newly inserted node.

**Comment by lorenzoferre** [comment]
Thank you very much @nicolo-ribaudo, I got it. Now it works :)
