### ISSUE TITLE
[Bug]: transform-modules-commonjs plugin changes comment placement

### ISSUE THREAD

**Issue by mohd-akram** [babel/babel#15977]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
export const foo = 'bar';
/* istanbul ignore next */
export const baz = true || console.log('never here');
```

### Configuration

`babel --plugins @babel/plugin-transform-modules-commonjs module.js`

### Current and expected behavior

Current:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.foo = exports.baz = void 0;
const foo = 'bar';
/* istanbul ignore next */
exports.foo = foo;
const baz = true || console.log('never here');
exports.baz = baz;
```

Expected:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.foo = exports.baz = void 0;
const foo = 'bar';
exports.foo = foo;
/* istanbul ignore next */
const baz = true || console.log('never here');
exports.baz = baz;
```

### Environment

```  
  System:
    OS: macOS 13.5.2
  Binaries:
    Node: 20.6.1 - /opt/local/bin/node
    Yarn: 1.22.18 - ~/.local/bin/yarn
    npm: 9.8.1 - /opt/local/bin/npm
  npmPackages:
    @babel/cli: ^7.22.15 => 7.22.15 
    @babel/core: ^7.22.19 => 7.22.19 
    @babel/preset-env: ^7.22.15 => 7.22.15 
```

**Comment by JLHwung** [comment]
As a workaround, you can place the `ignore next` comment before the default assignment
```js
export const foo = 'bar';
export const baz = true || /* istanbul ignore next */ console.log('never here');
```

See also https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md#ignore-default-assignments. 
Since the transpiled code will run `const baz = true` anyway, it should not decrease the code coverage.

In Babel, the comment `/* istanbul ignore next */` is attached to both the leading node `export const foo = 'bar';` and the trailing node `export const baz = true || console.log('never here');`. After they are transformed, the comment is attached to `const foo = 'bar';` because the generator visits this node earlier than `const baz = true`.

In this example
```js
export const foo = 'bar'; // eslint-ignore-this-line
export const baz = true || console.log('never here');
```

The current generated result might be preferred as the comment still follows the line `foo = 'bar'`:
```js
exports.foo = exports.baz = void 0;
const foo = 'bar'; // eslint-ignore-this-line
exports.foo = foo;
const baz = true || console.log('never here');
exports.baz = baz;
```

But as a parser, there isn't anyway to differentiate this example with your posted example. So there aren't very much we can do here.

**Comment by nicolo-ribaudo** [comment]
```js
export const foo = 'bar';
/* ^ look, I say something about the line above! */
export const baz = true || console.log('never here');
```
vs
```js
export const foo = 'bar';
/* v look, I say something about the line below! */
export const baz = true || console.log('never here');
```

we might need `@babel/plugin-ai` here :)

**Comment by mohd-akram** [comment]
> As a workaround, you can place the `ignore next` comment before the default assignment

That was just a simplified example. In the actual code it's something like this:

```javascript
let isFunction = function(value) {
  return typeof value === 'function';
};
// fallback for older versions of Chrome and Safari
/* istanbul ignore next */
if (isFunction(/x/)) {
  isFunction = function(value) {
    return (
      typeof value === 'function' &&
      toString.call(value) === '[object Function]'
    );
  };
}
export { isFunction };
```

Your example seems to suggest that the parser does know the difference between a comment on the same line and a comment on the next line, since it didn't transform it to this:

```javascript
exports.foo = exports.baz = void 0;
const foo = 'bar';
// eslint-ignore-this-line
exports.foo = foo;
const baz = true || console.log('never here');
exports.baz = baz;
```

**Comment by mohd-akram** [comment]
@nicolo-ribaudo I did do that, but I don't want to litter the codebase with things just to get a desirable output. This issue would also not be present if Babel did not move the position of the export statement as it does:

```javascript
let isFunction = function (value) {
  return typeof value === 'function';
};
// fallback for older versions of Chrome and Safari
/* istanbul ignore next */
exports.isFunction = isFunction;
if (isFunction(/x/)) {
  exports.isFunction = isFunction = function (value) {
    return typeof value === 'function' && toString.call(value) === '[object Function]';
  };
}
```

**Comment by nicolo-ribaudo** [comment]
Due to how ESM works, `exports....` must be updated every time you assign to one of the exported variables.

It's not necessary in your specific example, but consider this code:
```js
import { something } from "./something"

let isFunction = function(value) {
  return typeof value === 'function';
};
// fallback for older versions of Chrome and Safari
/* istanbul ignore next */
if (something() && isFunction(/x/)) {
  isFunction = function(value) {
    return (
      typeof value === 'function' &&
      toString.call(value) === '[object Function]'
    );
  };
}
```

where `something` is defined in another module like this:
```js
import { isFunction } from "dep";

export function something() {
  return isFunction(() => {});
}
```

here keeping the `exports.isFunction = isFunction` in the same place as where you have `export { isFunction }` would make `something()` throw with "undefined is not a function".

Unfortunately there is no a one-size-fit-all solution for this, because comment attachment is heavily dependent on the _meaning_ of the comment, and an automated tool cannot understand it.

**Comment by mohd-akram** [comment]
@nicolo-ribaudo Thanks for the explanation.

> Unfortunately there is no a one-size-fit-all solution for this, because comment attachment is heavily dependent on the meaning of the comment, and an automated tool cannot understand it.

I don't think this is as intractable as you present. Comments precede what they explain. There is no `eslint-disable-previous-line` or  `istanbul ignore previous`. Comments on the same line as a statement seem to already be preserved by Babel, so that part is solved.
