### ISSUE TITLE
[Bug]: @babel/transform-export-namespace-from is not included after v7.23.3

### ISSUE THREAD

**Issue by BrooklynKing** [babel/babel#16155]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

Babel v7.23.2 - [Link](https://babeljs.io/repl#?browsers=node%2014&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAKjgQwM5wAoEszLgMyggFs4ByAOgHowdkyBuIA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.2&externalPlugins=%40babel%2Fplugin-transform-class-properties%407.23.3&assumptions=%7B%7D)
Babel v7.23.5 - [Link](https://babeljs.io/repl#?browsers=node%2014&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAKjgQwM5wAoEszLgMyggFs4ByAOgHowdkyBuIA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.5&externalPlugins=%40babel%2Fplugin-transform-class-properties%407.23.3&assumptions=%7B%7D)

### Current and expected behavior

After `7.23.3` version plugin `transform-export-namespace-from` is not included in config, provided by `@babel/preset-env`.

I belive it's because of changes in https://github.com/babel/babel/pull/15988/
Explicitly this [line](https://github.com/babel/babel/pull/15988/files#diff-bb38565ade744da31005fed35f391279a176bb8cbc960bc43b316ba10714cf37R399)
before that plugin included if `module !== "auto"`, but now it require `module === "auto"` to be included. Looks like a typo, since other part of that condition are changes properly (`api.caller?.(supportsExportNamespaceFrom)` into `!api.caller(supportsExportNamespaceFrom)` )

### Environment

Babel REPL

**Comment by JLHwung** [comment]
The change is expected, according to our compat data

https://github.com/babel/babel/blob/380d186b77d32734c595652a40cbda5e4e109c5c/packages/babel-compat-data/data/plugins.json#L749-L762
The namespace export has been supported natively since Node.js 13.2. So this plugin is not enabled giving Node.js 14 as a target. Previously this procedure is only applied when `modules` is `false`. After 7.23.3, it is applied to other `modules` options except `auto`, which uses the caller support data instead of the compat data.

Is this change breaking your website?

**Comment by JLHwung** [comment]
If you specify `modules: false` with `Node.js 13.1` as a target, the namespace export will be enabled because Node.js 13.1 does not support namespace export: Babel 7.23.5 [Link](https://babeljs.io/repl#?browsers=node%2013.1&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAKjgQwM5wAoEszLgMyggFs4ByAOgHowdkyBuIA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.5&externalPlugins=%40babel%2Fplugin-transform-class-properties%407.23.3&assumptions=%7B%7D)

Thanks for digging the codebase, 

https://github.com/babel/babel/blob/380d186b77d32734c595652a40cbda5e4e109c5c/packages/babel-preset-env/src/index.ts#L397-L408

specifies the only _exception case_ where we should load `transform-export-namespace-from` when the compat data says otherwise. 

In Babel 7.23.3, the `export-namespace-from`, like any other normal plugins, is _also_ determined by the `filterItems` utility:

https://github.com/babel/babel/blob/380d186b77d32734c595652a40cbda5e4e109c5c/packages/babel-helper-compilation-targets/src/filter-items.ts#L76-L104

which goes through the [`compat-data`](https://github.com/babel/babel/blob/main/packages/babel-compat-data/data/plugins.json) and filter a list of plugins that should be enabled by `preset-env`.

We consider this change a patch because `preset-env` is now better at excluding plugins users don't actually need as it is supported natively.

**Comment by BrooklynKing** [comment]
Thank you for explanation.

So if it's expected that for node >13.1 I should explicitly add that plugin if I'm not using `modules: "auto"` - we will do it.

**Comment by JLHwung** [comment]
@BrooklynKing 

> So if it's expected that for node >13.1 I should explicitly add that plugin

Actually quite the opposite, Node >= 13.2 already supports `export * as ns from "./module"`, it is expected that this plugin should not be enabled. 

If you want to force enabling this plugin, please specify the `include` option
```json
{
  "presets": [["@babel/preset-env", { "include": ["transform-export-namespace-from"] }]]
}
```
So you don't have to rely on the `modules` implementation details.

**Comment by BrooklynKing** [comment]
Yeah, thanks again for the explanation, I think now I understand better in what part of our flow we don't have a proper sequence. I will close issue.

**Comment by mareolan** [comment]
@JLHwung 
I might be misinterpreting something here, but the doc states that [modules](https://babeljs.io/docs/babel-preset-env#modules) option is "Enable transformation of ES module syntax to another module type.". So if I have e.g. `modules="commonjs"`, I assumed that the end result should use commonjs syntax (and the source code could still be using ES module syntax) - shouldn't the plugin transform-export-namespace-from still be automatically used too so that `export * as Xyz from ...` syntax is still parsable? In 7.23.3 it isn't so transformation fails.

Your suggestion of force-including the plugin works in my case too, though I kind of expected it to work without having to do that.

**Comment by nicolo-ribaudo** [comment]
Babel parses `export * as Xyz from ...` by default, it doesn't need a plugin for that. `@babel/transform-export-namespace-from` is only necessary when not compiling to CommonJS _and_ targeting some platform that supports ESM but not `export * as ...`.

Do you have a complete stack trace for the error you are seeing?

**Comment by mareolan** [comment]
The stack trace is:

```bash
mareolan@LAPTOP:~/tmp/tst-babel$ ./node_modules/.bin/babel src --out-dir lib
SyntaxError: /home/mareolan/tmp/tst-babel/src/index.js: Export namespace should be first transformed by `@babel/plugin-transform-export-namespace-from`.
> 1 | export * as Extra from "./extra.js";
    |        ^^^^^^^^^^
  2 |
    at File.buildCodeFrameError (/home/mareolan/tmp/tst-babel/node_modules/@babel/core/lib/transformation/file/file.js:205:12)
    at NodePath.buildCodeFrameError (/home/mareolan/tmp/tst-babel/node_modules/@babel/traverse/lib/path/index.js:98:21)
    at assertExportSpecifier (/home/mareolan/tmp/tst-babel/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:98:16)
    at /home/mareolan/tmp/tst-babel/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:191:9
    at Array.forEach (<anonymous>)
    at /home/mareolan/tmp/tst-babel/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:190:31
    at Array.forEach (<anonymous>)
    at getModuleMetadata (/home/mareolan/tmp/tst-babel/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:137:27)
    at normalizeModuleAndLoadMetadata (/home/mareolan/tmp/tst-babel/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:47:7)
    at rewriteModuleStatementsAndPrepareHeader (/home/mareolan/tmp/tst-babel/node_modules/@babel/helper-module-transforms/lib/index.js:92:54) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

It can be simulated by creating simple project in an empty folder:
```bash
npm init -y
npm i -D @babel/core @babel/cli @babel/preset-env
mkdir src
echo 'export * as Extra from "./extra.js";' > src/index.js
echo 'export const A = 10;' > src/extra.js
cat > babel.config.js <<EOF
module.exports = {
  sourceType: "unambiguous",
  presets: [
    [
      "@babel/preset-env",
      {
        modules: "commonjs",
        targets: "node 16",
        bugfixes: true,
      },
    ],
  ],
};
EOF
```
And then just run
```bash
./node_modules/.bin/babel src --out-dir lib
```

There seems to be an issue with `targets` - if it's left out, it works, and output looks like ES5. If it's there then it doesn't work (and the value of `targets` doesn't seem to matter).

Adding `include: ["transform-export-namespace-from"]` makes it work even with `targets`.

**Comment by JLHwung** [comment]
@mareolan Thanks for the reproduction, reopen the issue.
