### ISSUE TITLE
[Bug]: hasOwn is not handled properly

### ISSUE THREAD

**Issue by akimd** [babel/babel#16195]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

The setup is available [here, on babeljs.io](https://babeljs.io/repl#?browsers=since%202019&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAlhAggEwG4EMzAKbIKoAOANiOsjALwwDyARgFbbBQB0AFuhNQO5gAU3OGGQhuAGhgByAGIgATgFsAIuijpJAShgAybTQZNWHLrwFCR4qdLhFsAJWxlsczQG4AUDCA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.6&externalPlugins=&assumptions=%7B%7D)

```js
const isAdvancedUpload = Object.hasOwn(window, 'FormData') && Object.hasOwn(window, 'FileReader');
```

### Current and expected behavior

I'm targeting "since 2019", and AFAICT hasOwn was introduced in ES2022.  Firefox 89 does not support it, and it was released in June 2021 (https://www.mozilla.org/en-US/firefox/89.0/releasenotes/) which is way after "since 2019".

But babel does not translate it.

Thanks!

### Environment

babeljs.io

**Comment by andersk** [comment]
You need to turn on [`useBuiltIns`](https://babeljs.io/docs/babel-preset-env#usebuiltins). For example, here’s [your demo with `useBuiltIns: "usage"`](https://babeljs.io/repl#?browsers=since%202019&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAlhAggEwG4EMzAKbIKoAOANiOsjALwwDyARgFbbBQB0AFuhNQO5gAU3OGGQhuAGhgByAGIgATgFsAIuijpJAShgAybTQZNWHLrwFCR4qdLhFsAJWxlsczQG4AUDCA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.6&externalPlugins=&assumptions=%7B%7D).
