### ISSUE TITLE
[Bug]: toPrimitive() does not use the typeof() function

### ISSUE THREAD

**Issue by DiFuks** [babel/babel#16219]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

[Correct](https://babel.dev/repl#?browsers=chrome%2022%2C%20last%2012%20years&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAECCAeBLA9hAEgUzAEwwJxgG8AoaaAbQGUBPAWwCNkQA6RAF3zDeTwF0AKAJTQSZMngxsArngB2AblLQAvsVVA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.8&externalPlugins=&assumptions=%7B%7D)

[Correct - modules false](https://babel.dev/repl#?browsers=chrome%2022%2C%20last%2012%20years&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUAXAngB1iAZgAQBuAhtAK6yEC8dhARCAEYBWsw6DAlANwBQ_YNFIQIhAIIAPAJYgIACVikAJrABO4gN79ChANoBlTAFtmMeDPQbS6EOoC6qboR16962OgrqwAvQC-_EFAA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.8&externalPlugins=&assumptions=%7B%7D)

[Incorrect - modules systemjs](https://babel.dev/repl#?browsers=chrome%2022%2C%20last%2012%20years&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUAXAngB1iAZgAQBuAhtAK6yEC8dhARCAEYBWsw6DAlANwBQ_YNFIQIhAIIAPAJYgIACVikAJrABO4gN79ChANoBlTAFtmMeDPQbS6EOoC6qboR16962OgrqwAvQC-_EFAA&debug=false&forceAllTransforms=false&modules=systemjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.8&externalPlugins=&assumptions=%7B%7D)

### Configuration

```json
{
	"presets": [
		[
			"@babel/preset-env",
			{
				"targets": ["chrome 22", "last 12 years"],
				"modules": "systemjs"
			}
		]
	]
}

```

### Current and expected behavior

For SystemJS, Babel does not replace the typeof operator with the @babel/helpers typeof function in toPrimitive in certain scenarios.

At the same time, in the browser, I get the error '@@toPrimitive must return a primitive value' because the Symbol from the polyfill is treated as an object, not as 'symbol'

### Environment

   "@babel/cli": "7.23.4",
   "@babel/core": "7.23.7",
   "@babel/preset-env": "7.23.8",
    OS: macOS 14.2.1
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 4.0.2 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm

**Comment by nicolo-ribaudo** [comment]
If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand:
1. Update the `toPrimitive` helper to use the `typeof` helper when checking the type of `input`:
   https://github.com/babel/babel/blob/87a67bf81281fa8a114b7c8e1f635efae906e53c/packages/babel-helpers/src/helpers/toPrimitive.ts#L4-L17
1. Normally you can just run `make watch` to compile the code as you write it, but helpers compilation is a little bit buggy so you probably need to run `make build` instead (and you might need to run it twice 😅 The first time it will generate a `helpers-generated.ts` file that you need to commit, and the second time it will compile that file to `.js` to be used while running tests)
1. Add a test in `packages/babel-plugin-transform-classes/fixtures/misc` (since `@babel/plugin-transform-classes` the main package using `toPrimitive`). Testing this might be difficult, because Node.js natively supports symbols. You might try with an `exec.js`-style test (look for other `exec.js` files in the test folder), doing the following:
    - `delete globalThis.Symbol;`, so that the polyfill will inject its own version
    - `require("core-js/modules/es.symbol.js")`
    - assert that `typeof Symbol()` is `"object"`, to make sure that we are using the polyfilled version
    - assert that `class X { [Symbol()]() {} }` does not throw, so that we know that `toPrimitive` is accepting that `Symbol()` even if it's technically an object.
1. `yarn jest babel-plugin-transform-classes` to run the tests
    - If some existing test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
    - If you prefer, you can run `OVERWRITE=true yarn jest babel-plugin-transform-classes` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by liuxingbaoyu** [comment]
@nicolo-ribaudo 
I tried this issue.
The reason why `amd` and `umd` are different is that we replace the nodes in different ways. umd's wrapper is traversed again and `typeof` is converted, while amd's wrapper is not.
Is it possible for us to fix this by making `amd` just a `requeue` node?
I'm not sure how this works in `transform-runtime`.

**Comment by nicolo-ribaudo** [comment]
We should just fix it manually in the helper, so that it works even for people using `@babel/runtime` without transpiling it. Given that `toPrimitive` is for an ES6 feature, it should work in ES5 environments directly without needing to be further transformed by users.

**Comment by nicolo-ribaudo** [comment]
Oh actually the `toPrimitve` helper we publish in `@babel/runtime` already uses `typeof`: https://unpkg.com/browse/@babel/runtime@7.23.8/helpers/toPrimitive.js

So changing it in the helper directly is an easy fix for the "inlining" case, without affecting users that already use external helpers :)

**Comment by liuxingbaoyu** [comment]
Amazing, thank you! It seems that the logic of modifying amd is the same as umd, which is fine. We can avoid modifying `setFunctionName`, `toPropertyKey`, `toPrimitive` at the same time to use the `typeof` helper.

**Comment by YBhatta2058** [comment]
I would love to try this problem.
!assign

**Comment by liuxingbaoyu** [comment]
@YBhatta2058 
Thank you!
Sorry I just opened a PR with another fix. :)

**Comment by nicolo-ribaudo** [comment]
@YBhatta2058 It seems like my description was completely wrong (it was just hiding suggesting to workaround the underlying problem) and @liuxingbaoyu opened a PR with a different fix. Let me find a different issue for you :)

**Comment by DiFuks** [comment]
You all are awesome! I didn't expect such a quick response and fix. Thank you!

**Comment by YBhatta2058** [comment]
> @YBhatta2058 It seems like my description was completely wrong (it was just hiding suggesting to workaround the underlying problem) and @liuxingbaoyu opened a PR with a different fix. Let me find a different issue for you :)

Ok Thank you
