### ISSUE TITLE
_interopRequireWildcard will change this pointer

### ISSUE THREAD

**Issue by welefen** [babel/babel#1626]
```
import * as mime from 'mime';
```
compiled code is:

```
var _interopRequireWildcard = require('babel-runtime/helpers/interop-require-wildcard')['default'];
var _mime = require('mime');
var mime = _interopRequireWildcard(_mime);

```

`mime` module is not compiled by babel, then `mime` object has no `lookup` method.

**Comment by loganfsmyth** [comment]
@welefen This is a place where the distinction between CommonJS modules and ES6 modules is leading to some confusion. I'd recommend you do

    import mime from 'mime';

Your current code requires the mime module to export object that is a bag of functions, since by doing `* as mime` you as asking for all of the named exports of the module, but `mime` actually exports an instance of the Mime object, with the `lookup` method stored on the object's prototype. Since the method is on its prototype, it is not picked up by an import like `import * as mime`

**Comment by sebmck** [comment]
Yep, exactly as @loganfsmyth describes. Intentional behaviour I guess. The CommonJS interop can only go so far.

**Comment by welefen** [comment]
@loganfsmyth  @sebmck  thx
