### ISSUE TITLE
[Bug]: Generator functions cannot be converted using only @babel/plugin-transform-runtime

### ISSUE THREAD

**Issue by cp3hnu** [babel/babel#16260]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
function* foo() {}
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "helpers": true,
        "regenerator": true,
        "version": "^7.23.8"
      }
    ]
  ]
}
```

### Current and expected behavior

https://babeljs.io/docs/babel-plugin-transform-runtime#regenerator-aliasing said, it can transform generator functions
```js
"use strict";
var _regenerator = require("@babel/runtime/regenerator");
var _regenerator2 = _interopRequireDefault(_regenerator);
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj };
}
var _marked = [foo].map(_regenerator2.default.mark);
function foo() {
  return _regenerator2.default.wrap(
    function foo$(_context) {
      while (1) {
        switch ((_context.prev = _context.next)) {
          case 0:
          case "end":
            return _context.stop();
        }
      }
    },
    _marked[0],
    this
  );
}
```

### Environment

  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 9.1.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @babel/cli: ^7.23.4 => 7.23.4 
    @babel/core: ^7.23.7 => 7.23.7 
    @babel/plugin-transform-runtime: ^7.23.7 => 7.23.7 
    @babel/preset-env: ^7.23.9 => 7.23.9 
    @babel/runtime: ^7.23.8 => 7.23.8 
    @babel/runtime-corejs3: ^7.23.8 => 7.23.8 

### Possible solution

Does @babel/plugin-transform-runtime not translate generator functions? But it's not in the document

**Comment by cp3hnu** [comment]
The .browserslistrc is
```json
ie >= 8
```

**Comment by nicolo-ribaudo** [comment]
This plugin only causes Babel to compile generators to that code you posted rather than the one in the "the following is generated:" section of that docs page, but you still need `@babel/plugin-transform-regenerator` or `@babel/preset-env` to transform it.

**Comment by cp3hnu** [comment]
Thank you for your reply.
"This plugin only causes Babel to compile generators to that code you posted"
What does that mean?

The input code is 
```js
function* foo() {}
```js

The output code is still 
```js
function* foo() {}
```js

It is not change

**Comment by nicolo-ribaudo** [comment]
This plugin transforms this input code:
```js
"use strict";

var _marked = [foo].map(regeneratorRuntime.mark);

function foo() {
  return regeneratorRuntime.wrap(
    function foo$(_context) {
      while (1) {
        switch ((_context.prev = _context.next)) {
          case 0:
          case "end":
            return _context.stop();
        }
      }
    },
    _marked[0],
    this
  );
}
```

to this output code:
```js
"use strict";

var _regenerator = require("@babel/runtime/regenerator");

var _regenerator2 = _interopRequireDefault(_regenerator);

function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj };
}

var _marked = [foo].map(_regenerator2.default.mark);

function foo() {
  return _regenerator2.default.wrap(
    function foo$(_context) {
      while (1) {
        switch ((_context.prev = _context.next)) {
          case 0:
          case "end":
            return _context.stop();
        }
      }
    },
    _marked[0],
    this
  );
}
```

If you want to compile `function* foo() {}`, you have to use `@babel/plugin-transform-regenerator`.

**Comment by cp3hnu** [comment]
This is the role of `{"helper":true}`, not `{"regenerator":true}`.
It seems that whether `regenerator` is `true` or `false`, the result does not change.

For example, the following two configurations
```json
{
  "plugins": [
    "@babel/plugin-transform-regenerator",
    [
      "@babel/plugin-transform-runtime",
      {
        "helpers": false,
        "regenerator": true,
        "version": "^7.23.8"
      }
    ]
  ]
}
```

```json
{
  "plugins": [
    "@babel/plugin-transform-regenerator",
    [
      "@babel/plugin-transform-runtime",
      {
        "helpers": false,
        "regenerator": false,
        "version": "^7.23.8"
      }
    ]
  ]
}
```

**Comment by nicolo-ribaudo** [comment]
Sorry for the late reply. The `regenerator` option now does... basically nothing 😅 

In the past, the transform for generator functions would inject usage of a `regeneratorRuntime` global, and `transform-runtime { regenerator: true }` this global would then be replace this global with an import statement. Now we directly inject an import statement without going through the `regeneratorRuntime` global anymore.

`regenerator: true` is still useful when you are compiling some third-party code that relies on this `regeneratorRuntime` global, and you want to replace it with an import to `@babel/runtime`.

**Comment by cp3hnu** [comment]
@nicolo-ribaudo 
Thanks for your answer in details.

**Comment by nyngwang** [comment]
@nicolo-ribaudo

> Sorry for the late reply. The `regenerator` option now does... nothing 😅

No. I think his example is incorrect. The `regenerator` option seems to do nothing because he also included the plugin `@babel/plugin-transform-regenerator` right above the `@babel/plugin-transform-runtime`:

```json
{
  "plugins": [
    "@babel/plugin-transform-regenerator",
    [
      "@babel/plugin-transform-runtime",
```

 Since the option `regenerator: true` will do the same job as `@babel/plugin-transform-regenerator`, setting it `true`/`false` doesn't matter. But this doesn't mean the option does nothing. The intent of `regenerator: true` is to save you from adding one more plugin, i.e. `@babel/plugin-transform-regenerator` explicitly. It's clear if you see its package.json:

1. It depends on `babel-plugin-polyfill-regenerator`, [ref](https://github.com/babel/babel/blob/2a313fa24b13a6d1e8e4283aabaf2348c7cb3557/packages/babel-plugin-transform-runtime/package.json#L27C6-L27C39)
2. It depends on `@babel/plugin-transform-regenerator`, [ref](https://github.com/babel/babel-polyfills/blob/599f7c459b396efa560a714b0cd909959cb8864a/packages/babel-plugin-polyfill-regenerator/package.json#L34)

@cp3hnu you should take a look, as you provided a misleading example above.

As a bonus, let me prove it with my case debugging for #16310. With `regenerator: false`, I got: (and this causes an error: `regeneratorRuntime is not defined`)

<img src="https://github.com/babel/babel/assets/24765272/8e561b34-fc0a-4fa4-a59f-3f626fd3c8bb" width="700">


With `regenerator: true`, I got:

<img src="https://github.com/babel/babel/assets/24765272/34471674-34a1-4831-8bcf-090c15e5082e" width="700">

**Comment by nyngwang** [comment]
@nicolo-ribaudo

> Sorry for the late reply. The `regenerator` option now does... nothing 😅

No. I think his example is incorrect. The `regenerator` option seems to do nothing because he also included the plugin `@babel/plugin-transform-regenerator` right above the `@babel/plugin-transform-runtime`:

```json
{
  "plugins": [
    "@babel/plugin-transform-regenerator",
    [
      "@babel/plugin-transform-runtime",
```

 Since the option `regenerator: true` will do the same job as `@babel/plugin-transform-regenerator`, setting it `true`/`false` doesn't matter. But this doesn't mean the option does nothing.

---

@cp3hnu you should take a look, as you provided a misleading example above.

The intent of `regenerator: true` is to save you from explicitly adding one more plugin, i.e. `@babel/plugin-transform-regenerator` for conciseness. It's clear if you see its package.json:

1. It depends on `babel-plugin-polyfill-regenerator`, [ref](https://github.com/babel/babel/blob/2a313fa24b13a6d1e8e4283aabaf2348c7cb3557/packages/babel-plugin-transform-runtime/package.json#L27C6-L27C39)
2. It depends on `@babel/plugin-transform-regenerator`, [ref](https://github.com/babel/babel-polyfills/blob/599f7c459b396efa560a714b0cd909959cb8864a/packages/babel-plugin-polyfill-regenerator/package.json#L34)

As a bonus, let me prove it with my case debugging for #16310. With `regenerator: false`, I got: (and this causes an error: `regeneratorRuntime is not defined`)

<img src="https://github.com/babel/babel/assets/24765272/8e561b34-fc0a-4fa4-a59f-3f626fd3c8bb" width="700">


With `regenerator: true`, I got:

<img src="https://github.com/babel/babel/assets/24765272/34471674-34a1-4831-8bcf-090c15e5082e" width="700">

**Comment by nyngwang** [comment]
@cp3hnu 

> This is the role of {"helper":true}, not {"regenerator":true}.

This is not correct. The `generatorRuntime` itself is not a segment of inlined Babel helper that can be extracted. So `helper: true` does NOT cover the case when Babel sees `generatorRuntime`. It's therefore handled by another plugin.

**Comment by cp3hnu** [comment]
@nyngwang 
If I don't use `@babel/plugin-transform-regenerator`, the `@babel/plugin-transform-runtime` can not transform generator functions in the description of my question.

**Comment by nyngwang** [comment]
@cp3hnu But it can in my case. I think you have something wrong with your configs. On the other hand, I suggest you rethink what you should expect by "transform generator functions". The job of the plugin `@babel/plugin-transform-runtime`, which is very clear by its name, is to move everything inlined into a `@babel/runtime` or its variants. I have provided my real case above. Did you see the difference?

**Comment by nyngwang** [comment]
@cp3hnu Can you be clear about what's your current input and output? You provided nothing in your OP. Can you provide a reproducible example for me to test for you?

**Comment by nyngwang** [comment]
@cp3hnu I don't know how to help you. I can't reproduce it.

**Comment by nyngwang** [comment]
@cp3hnu The option `regenerator: true` is like saying: "Should we extract inlined usage of `generatorRuntime ` into `@babel/runtime`?". Yes, it did in my case. Because I have used `@babel/preset-env` to transform:

```js
function* foo() {}
```

into

```js
"use strict";

var _marked = [foo].map(regeneratorRuntime.mark);

function foo() {
  return regeneratorRuntime.wrap(
    function foo$(_context) {
      while (1) {
        switch ((_context.prev = _context.next)) {
          case 0:
          case "end":
            return _context.stop();
        }
      }
    },
    _marked[0],
    this
  );
}
```

Does this help?

**Comment by cp3hnu** [comment]
@nyngwang 
`@babel/preset-env` incudes `@babel/plugin-transform-regenerator`, I think this is `@babel/plugin-transform-regenerator` to transform generator functions not `@babel/plugin-transform-runtime`. 
Extract inlined usage of generatorRuntime  into @babel/runtime is option `{helper: true}` not `{regenerator: true}`

**Comment by nyngwang** [comment]
@cp3hnu Hi, I'm sorry. Now I realize that my first comment above is incorrect. I'm looking into the problem again.

**Comment by nyngwang** [comment]
@cp3hnu Please check my updated comment. Let's do some simple logic: 

1. Assume you're correct. Then I should see no difference given `regenerator: true` or `false`.
2. I see difference.

What's the conclusion?

**Comment by cp3hnu** [comment]
@nyngwang 
I'm sorry for the trouble. First of all, I just asked what function `regenerator` has. If I make a mistake, you can correct me. If I am right, I can help you modify it

**Comment by nyngwang** [comment]
@cp3hnu Sorry, I was doing something else. I tried your case, and now I don't understand why `regenerator: true/false` makes a difference in my usecase.

**Comment by cp3hnu** [comment]
@nyngwang 
Yes, I need to set `regenerator: true` when removing `version`
