### ISSUE TITLE
Add polyfill.js to babel-runtime

### ISSUE THREAD

**Issue by ooflorent** [babel/babel#1629]
When building an application compiled using babel, lots of developer use the `runtime` transformer but still requires the polyfills for ES6+ definitions. The application's package is generally similar to:

```js
{
  "dependencies": {
    "babel-runtime": "^5.0.0"
  },
  "devDependencies": {
    "babel": "^5.0.0"
  },
  "scripts": {
    "build": "babel -d lib src"
  }
}
```

Unfortunately the polyfills are located at `babel/runtime` which requires the developer to specify `babel` as dependencies (not a dev one) if he want to use it. Adding the polyfills to `babel-runtime` would solve this issue.

**Comment by Nyalab** [comment]
:+1:, would be better regarding `dependencies` and `devDependencies`

**Comment by loganfsmyth** [comment]
@ooflorent Do you have an example of a part of the polyfill that isn't automatically added when using `runtime`? The only things that come to mind are the prototype overrides like `Array.prototype.fill` and such.

At the moment at least, the objective of the `runtime` transform and `babel-runtime` is to make code that is 100% self-contained, which is at odds with globally polyfilling things like `Array.prototype.fill`.

If you want a fully polyfilled global ES6 environment, at the moment I wouldn't use `babel-runtime` at all, I'd install `babel` in `devDependencies` and `babel-core` in `dependencies` and then `require('babel-core/polyfill');` and `require('babel-core/external-helpers');` and pass `externalHelpers: true` when compiling. Obviously as you said that loads more code, but if you're bundling, it won't bundle any of the transpiler itself, and server-side, it's still a much faster install than `babel` with all the CLI tools.

I just wanted to make sure all that was clear. It's up to @sebmck if this is something he's up for changing, since I could see a world where `babel-runtime` is seen more as "everything that might be needed when the transpiler itself isn't needed" and exposed both polluting and non-polluting pieces. At the moment however, it's meant specifically to pair with the `runtime` transform, which explicitly exists to avoid polluting globals.

**Comment by ooflorent** [comment]
Thanks for you answer. I was thinking about ES6 and ES7 prototype additions (such as `Array#includes`). It seems really odd to me to add `require('babel/polyfill')` into my codebase since babel should be kept as a `devDependency`.

I will try what you're suggesting. Seems really interesting. Maybe a side note could be added to Babel's doc. I'd submit a PR once everything is fine. :+1:

**Comment by sebmck** [comment]
Having the polyfill be available in the packages: babel, babel-core AND
babel-runtime is going to be extremely confusing.

On Tuesday, 26 May 2015, Florent Cailhol <notifications@github.com> wrote:

> Thanks for you answer. I was thinking about ES6 and ES7 prototype
> additions (such as Array#includes). It seems really odd to me to add
> require('babel/polyfill') into my codebase since babel should be kept as
> a devDependency.
>
> I will try what you're suggesting. Seems really interesting. Maybe a side
> note could be added to Babel's doc. I'd submit a PR once everything is
> fine. [image: :+1:]
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1629#issuecomment-105564279>.
>


-- 
Sebastian McKenzie

**Comment by ooflorent** [comment]
I tried to add `babel-core/polyfill` and `babel-core/external-helpers` to the required modules and everything worked fine. I think I'll go with this but I'm still fighting myself accepting `babel-core` as a non-development dependency.

**Comment by ooflorent** [comment]
One last concern: many library authors use the `runtime` transformer. 
Requiring `babel-core/external-helpers` would duplicate code.

**Comment by loganfsmyth** [comment]
You wouldn't use both. You cannot use any prototype-level globals when using `runtime` because the objective of it is to avoid polluting the global objects. Instead of doing `[1,2,3,4].includes(3)`, which requires polluting the global array prototype, if you are using `runtime` the expectation is that you'd use the non-standard location at `Array.includes([1,2,3,4], 3)`

If you are using external helpers and the polyfill, there is nothing gained by using `runtime`.

**Comment by ooflorent** [comment]
@loganfsmyst well the gain is avoiding the duplication babel's helpers if you consume a lib that uses the runtime. Using non standard core-js functions is not quite a good since you are no longer writing spec compliant code but vendor specific. 

Maximize shared code between core and runtime seems to be the best option... Any thoughts on that?
