### ISSUE TITLE
Spread syntax on Uint8Array incorrectly transpiled to ES5

### ISSUE THREAD

**Issue by mobapedia** [babel/babel#16298]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

let a = [1, ...new Uint8Array(3)]

### Current and expected behavior

When transpiling this es6 code to es5, babel uses .concat which gives `var a = [1].concat(new Uint8Array(3));`
es6 output: [1, 0, 0, 0]
es5 output: [1, Uint8Array(3)]

### Environment

babel v7.23.10

**Comment by JLHwung** [comment]
It is possible you have enabled the `loose` mode, please check for `loose: true` in your Babel config. If so, please specify:
```js
{
  assumptions: { iterableIsArray: false }
}
```
in your Babel config.

**Comment by mobapedia** [comment]
The same thing happens as before. I'm using the online repl btw.

**Comment by mobapedia** [comment]
With the spec mode it works fine, but it doesn't work with loose.

**Comment by JLHwung** [comment]
The loose mode is _not_ spec compliant, it makes assumptions on the input so that Babel can output more compact code. When those assumptions does not cover the actual code usage, the output will break.

If you want to still use the `loose` mode but would like to make `let a = [1, ...new Uint8Array(3)]` as expected, please migrate to the `assumptions` option, and set `iterableIsArray` to `false`.

See https://babel.dev/docs/assumptions#migrating-from-babelpreset-envs-loose-and-spec-modes
