### ISSUE TITLE
[Bug]: babel compile `proposal-explicit-resource-management` different from `tsc`

### ISSUE THREAD

**Issue by loynoir** [babel/babel#16435]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

https://github.com/microsoft/TypeScript/issues/58234

```js
import { deepStrictEqual } from 'node:assert'
import process from 'node:process'

let i = 0
/** @type {any} */
let err
try {
  await using _x1 = {
    async [Symbol.asyncDispose]() {
      throw [1, ++i]
    }
  }

  await using _x2 = {
    async [Symbol.asyncDispose]() {
      throw [2, ++i]
    }
  }

  await using _x3 = {
    async [Symbol.asyncDispose]() {
      throw [3, ++i]
    }
  }

  await using _x4 = {
    async [Symbol.asyncDispose]() {
      throw [4, ++i]
    }
  }

  throw [5, ++i]
} catch (e) {
  err = e
}

switch (process.env['TRANSPILER']) {
  case 'tsc':
    deepStrictEqual(err.error, [1, 5])
    deepStrictEqual(err.suppressed.error, [2, 4])
    deepStrictEqual(err.suppressed.suppressed.error, [3, 3])
    deepStrictEqual(err.suppressed.suppressed.suppressed.error, [4, 2])
    deepStrictEqual(err.suppressed.suppressed.suppressed.suppressed, [5, 1])
    break
  case 'swc':
    deepStrictEqual(err.suppressed, [1, 5])
    deepStrictEqual(err.error.suppressed, [2, 4])
    deepStrictEqual(err.error.error.suppressed, [3, 3])
    deepStrictEqual(err.error.error.error.suppressed, [4, 2])
    deepStrictEqual(err.error.error.error.error, [5, 1])
    break
  case 'babel':
    deepStrictEqual(err.suppressed, [1, 5])
    deepStrictEqual(err.error.suppressed, [2, 4])
    deepStrictEqual(err.error.error.suppressed, [3, 3])
    deepStrictEqual(err.error.error.error.suppressed, [4, 2])
    deepStrictEqual(err.error.error.error.error, [5, 1])
    break
  default:
    // break
    throw new Error()
}

// export { err }
```

### Current and expected behavior

Currently, `tsc` and `swc` and `babel` does not have same runtime behavior.

Expect `tsc` and `swc` and `babel` have same runtime behavior.

### Environment

7.24.1 (@babel/core 7.24.4)

**Comment by nicolo-ribaudo** [comment]
If anybody wants to fix this, the problem is in the order we pass errors to the `SuppressedError` constructor in https://github.com/babel/babel/blob/33d8d7d54e1d2eb2d55c455a3ff34a73b55bd569/packages/babel-helpers/src/helpers/usingCtx.ts. After fixing that, we probably need to update some tests that are asserting the wrong thing.

This would be a good first contribution for anybody interested :)



If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
   - NOTE: When changing helpers code, `make watch` is not always reliable so you should run `make build`
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest explicit-resource-management` to run the tests
    - You will probably need to update some assertions in failing tests
    - If some snapshot test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
      - If you prefer, you can run `OVERWRITE=true yarn jest explicit-resource-management` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by sossost** [comment]
hello! @nicolo-ribaudo  I am sossost, a new contributor. I would like to solve this problem. Is it possible?

**Comment by nicolo-ribaudo** [comment]
Yes! Feel free to ask here if you need any help :)

**Comment by sossost** [comment]
thank you! If there is anything I need help with along the way, I will ask. have a good day

**Comment by sossost** [comment]
@nicolo-ribaudo Thanks for your help. as you mentioned, I modified the order of sending errors to SuppressedError and modified related tests.
Am I doing it right?

**Comment by sossost** [comment]
Thank you @nicolo-ribaudo . Although it is a small task and I received a lot of help, this is a great motivation and accomplishment for me. I will grow into a better developer. Thank you again.
