### ISSUE TITLE
Not removing module extensions

### ISSUE THREAD

**Issue by ben-ng** [babel/babel#1653]
```
~/Documents/test cat .babelrc
{
  "keepModuleIdExtensions": false
}
 ~/Documents/test cat script.js

require('./filepath.jsx')

 ~/Documents/test babel script.js
'use strict';

require('./filepath.jsx');
```

It seems like the extension `.jsx` in the require should be removed. Am I misunderstanding this option?

**Comment by loganfsmyth** [comment]
You are misunderstanding that option unfortunately. It is used when choosing names for exported modules wrapper, but CommonJS modules don't really have names internally. For example System modules come out like

    System.register('somename', [], function(export){
        // Transpiled stuff
    });

instead of

    System.register('somename.js', [], function(export){
        // Transpiled stuff
    });

Feel free to come onto [gitter](https://gitter.im/babel/babel) if you want to chat about whatever you're trying to accomplish.
