### ISSUE TITLE
The Decorators for Function and object literal element

### ISSUE THREAD

**Issue by Groupguanfang** [babel/babel#16581]
### 💻

- [ ] Would you like to work on this feature?

### What problem are you trying to solve?

TC39 team created this repository 5 months ago：[proposal-function-and-object-literal-element-decorators](https://github.com/tc39/proposal-function-and-object-literal-element-decorators)，and the current stage is still very early (stage0).

### Describe the solution you'd like

Does babel have any plans to do it in `@babel/plugin-decorators`？Or make another plugin?

### Describe alternatives you've considered

No description provided.

**Comment by nicolo-ribaudo** [comment]
Hey! We will eventually create a new plugin for that proposal. However, we usually wait until when the proposal has some clearly defined semantics (usually, late stage 2), so that we know what to implement.

That proposal has not been presented in a TC39 meeting yet, so it will probably take a few years :)
