### ISSUE TITLE
Class method definition clobbers imports

### ISSUE THREAD

**Issue by mjackson** [babel/babel#1664]
Using version 5.4.7, this code:

```js
import { a } from './a';

class Foo {
  _a() {
    a();
  }  
}
```

compiles to this:

```js
'use strict';

var _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ('value' in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }

var _a = require('./a');

var Foo = (function () {
  function Foo() {
    _classCallCheck(this, Foo);
  }

  _createClass(Foo, [{
    key: '_a',
    value: function _a() {
      (0, _a.a)();
    }
  }]);

  return Foo;
})();
```

First off, what in the world does `(0, _a.a)` do in the above code?!

Secondly, it's apparent that the reference to the module-level `_a` variable is being clobbered by the class method of the same name (i believe only inside the method body?), so this code doesn't work.

**Comment by mjackson** [comment]
AFAICT `(0, _a.a)` evaluates to `_a.a`, so this likely isn't the source of the problem. Still, I'd love to know why you believe it's necessary.

**Comment by zpao** [comment]
My understanding is this: `(0, _a.a)(arg)` is about scoping. `_a.a` has its `this` scoped to `_a`. But the comma operator will give you just the function `a`, so the context will be the global. The transformed code is equivalent to what would happen if you did `a = require('./a').a`. It's subtly different but important (and the same reason why you should never use `this.foo` in a singleton and instead refer to itself by name)

**Comment by mjackson** [comment]
@zpao whoa, thanks for dropping some knowledge! That sounds about right.

BTW, I tried the `{ blacklist: [ "spec.functionName" ] }` workaround, but it didn't help. AFAICT that was supposed to instruct babel to use an anonymous function instead of a named one, but it still keeps the name.

**Comment by zpao** [comment]
Oh, I guess this case might be being inserted outside of that transform and instead done directly with the class transform.

**Comment by fkling** [comment]
See https://github.com/babel/babel/issues/1514

**Comment by sebmck** [comment]
@mjackson 

> Still, I'd love to know why you believe it's necessary.

The `(0, x)` in:

```javascript
(0, _a.a)();
```

is a [`SequenceExpression`](https://github.com/estree/estree/blob/master/spec.md#sequenceexpression) or a [comma operator](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-comma-operator). It evaluates a list of expressions and returns the value of the last one. This is handy since `foo.bar()` will call `foo.bar` with the `foo` context while `(0, foo.bar)()` calls `foo.bar` with the `undefined` context. This is to retain semantics as otherwise the context will be `exports`. It's also good for performance since it can be JIT'd much better since the engine doesn't have to worry about contexts (which is a feature of JavaScript that is apparently fairly difficult to optimise).

@zpao 

> Oh, I guess this case might be being inserted outside of that transform and instead done directly with the class transform.

Yep, `nameMethod` is called directly in the classes transformer.

**Comment by mjackson** [comment]
@sebmck Awesome, thanks for the explanation :)
