### ISSUE TITLE
[Bug]: Wrong ASI after `get` in class body

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#16713]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
class A2 {
  get
  *a(){}
}
```

### Configuration

n/a

### Current and expected behavior

Babel inserts a semicolon after `get`, parsing that class as containing a field named `get` and a generator method.

This is wrong, and Babel should report an error for that code.

### Environment

Babel 7.25.0

**Comment by JLHwung** [comment]
I think the current behaviour is correct and the parser works as-is.

`get *a(){}` is never allowed in the [MethodDefinition](https://tc39.es/ecma262/#sec-method-definitions) production, so the token `*` becomes the offending token per [rules of ASI](https://tc39.es/ecma262/#sec-rules-of-automatic-semicolon-insertion), since `*` is separated from the previous token by a line break, ASI is applied and therefore `get` becomes `get;` which is then parsed as a class property.

**Comment by liuxingbaoyu** [comment]
```
class A2 {
  get
  *a(){}
}
const a2 = new A2();
console.log(a2.a);
console.log("get" in a2);
```
The browser seems to accept the form like this, whereas TypeScript complains about it.

**Comment by nicolo-ribaudo** [comment]
Oh and Firefox rejects that code. I'll investigate a bit more and report the appropriate bugs.

**Comment by nicolo-ribaudo** [comment]
I submitted a test262 test: https://github.com/tc39/test262/pull/4189
