### ISSUE TITLE
.babelrc examples

### ISSUE THREAD

**Issue by bucaran** [babel/babel#1675]
I don't know if this was already brought up before, but it would be useful to have a list of `.babelrc` samples. Several. The more the better.

:+1: ?

**Comment by sebmck** [comment]
Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

Also see issue babel/babel.github.io#279. Thanks.

**Comment by bucaran** [comment]
I was unable to find the list of `.babelrc` files. Maybe you can reopen this and people could post their `babelrc` files. This is an almost self-resolving issue.

**Comment by loganfsmyth** [comment]
@bucaran As @sebmck pointed out, this was not closed because it was invalid, it was closed because this repo is for tracking issues and features of Babel. There is a separate repo for tracking issues and features of the documentation website. Feel free to comment on the other bug he pointed you too and ask for example babelrc files.
