### ISSUE TITLE
Const is accidentally hoisted

### ISSUE THREAD

**Issue by tel** [babel/babel#1680]
The following code should be an error in ES6 (to my understanding)

```javascript
function foo() {
  return x;
}

const x = 3;
console.log(foo());
```

The reason it should fail is because `const`s are unhoisted. However, babel compiles this to

```javascript
"use strict";

function foo() {
  return x;
}

var x = 3;
console.log(foo());
```

and since the `const` is realized as a `var` it gets accidentally hoisted and the code prints `3`.

**Comment by sebmck** [comment]
I know. This is because it's extremely hard to accurately implement TDZ (which is what this is) in ES5 because of function declaration hoisting. You can enable the optional `es6.spec.blockScoping` transformer which will shift TDZ checks to the runtime but every single reference will be replaced with a check which is bad for performance.

See #563 for more discussion.

Usage:

**.babelrc

```json
{
  "optional": ["es6.spec.blockScoping"]
}
```

**CLI**

```sh
$ babel --optional es6.spec.blockScoping script.js
```

**Node API**

```javascript
require("babel-core").transform("code", { optional: ["es6.spec.blockScoping"] });
```

**Comment by tel** [comment]
That makes sense. Is there a page in the documentation anywhere where these spec inconsistencies are labeled?

**Comment by loganfsmyth** [comment]
Is that example actually invalid though? Since foo is only is only called after the `x` binding is initialized, I wouldn't expect it to error.

**Comment by tel** [comment]
I'm actually unclear on that point. My thought is that the name shouldn't be in scope during definition... but javascript has such weird scoping rules it's hard for me to say what's properly scoped at all.
