### ISSUE TITLE
[Bug]: A couple of babel packages don't include type definitions even though package.json has it

### ISSUE THREAD

**Issue by longlho** [babel/babel#16898]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

I'm looking at `helper-plugin-utils` and it's written in TS, its [package.json](https://github.com/babel/babel/blob/main/packages/babel-helper-plugin-utils/package.json#L47) also includes types but when published it's not there. Can we fix this across the board? I think `@babel/traverse` has the same issue.

### Current and expected behavior

Published npm package should include type def

### Environment

{
"@babel/core": "^7.25.8",
    "@babel/helper-plugin-utils": "^7.25.7",
    "@babel/plugin-syntax-jsx": "7",
    "@babel/preset-env": "^7.13.9",
    "@babel/preset-react": "^7.12.13",
    "@babel/traverse": "^7.25.7",
    "@babel/types": "^7.12.11",
}

**Comment by nicolo-ribaudo** [comment]
We are only publishing types in the Babel 8 pre-release (that you can find on npm), because doing so breaks all users that currently get types from DefinitelyTyped.

You can see by reading the package.json file at https://www.npmjs.com/package/@babel/helper-plugin-utils?activeTab=code that Babel 7 published packages do not point to type definitions in their package.json.
