### ISSUE TITLE
[Bug]: Why need to define @babel/plugin-syntax-dynamic-import in package.json now?

### ISSUE THREAD

**Issue by lcliusir** [babel/babel#16901]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
it's a webpack-npm-run-build problem
```

### Configuration file name

.babelrc

### Configuration

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false,
        "useBuiltIns": "usage",
        "corejs": 3
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties"],
    ["@babel/plugin-syntax-dynamic-import"],
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": 3
      }
    ]
  ],
  "sourceType": "unambiguous"
}
```

### Current and expected behavior

my project can build rightly two days ago, but as of yesterday, it can't build anymore, an Error express i need defined @babel/plugin-syntax-dynamic-import in the package.json
![build-error](https://github.com/user-attachments/assets/48f93227-043d-4452-a689-cd3e59c1f892)

### Environment

node: 14.18.1
"@babel/core": "^7.10.4",
"@babel/plugin-proposal-class-properties": "^7.10.4",
"@babel/plugin-proposal-decorators": "^7.0.0",
"@babel/plugin-proposal-export-namespace-from": "^7.0.0",
"@babel/plugin-proposal-function-sent": "^7.0.0",
"@babel/plugin-proposal-json-strings": "^7.0.0",
"@babel/plugin-proposal-numeric-separator": "^7.0.0",
"@babel/plugin-proposal-throw-expressions": "^7.0.0",
"@babel/plugin-transform-runtime": "^7.23.6",
"@babel/preset-env": "^7.10.4",
"@babel/preset-react": "^7.10.4",
"@babel/runtime-corejs3": "^7.23.6",
"babel-eslint": "^10.1.0",
"babel-loader": "8.1.0",
"babel-plugin-dynamic-import-webpack": "^1.1.0",
"babel-plugin-react-transform": "^2.0.2",
"babel-plugin-transform-react-remove-prop-types": "^0.4.20",

### Possible solution

when I added "@babel/plugin-syntax-dynamic-import": "7.8.3" in package.json, my project can build fine.

### Additional context

I wanna know why need define "@babel/plugin-syntax-dynamic-import" in package.json now?

**Comment by lcliusir** [comment]
There are no issues with local building, but there are errors when building in Jenkins

**Comment by nicolo-ribaudo** [comment]
In general, all packages that you rely on should be included in your package.json. Babel plugins and prserts are like other dependencies that you use at build time, so you need to specify all of them.

In the previous version you had `@babel/plugin-syntax-dynamic-import` out of luck: it was a transitive internal dependency of `@babel/preset-env`, npm was hoisting it at the top-level of your `node_modules` making it available as if it was one of your dependencies.

I recommend trying to install dependencies with [install strategy](https://docs.npmjs.com/cli/v10/commands/npm-install#install-strategy) "nested" or (better) "linked", so that npm will stop hoisting and you will surface this type of mistakes immediately, ratger than when other packages you depend on change their internal deps. Other packages managers have similar options.

---

In this specific case, you can also just remove that plugin from your Babel config: since Babel 7.8.0, that syntax is enabled by default so the plugin does nothing.

**Comment by lcliusir** [comment]
Thanks, Looks like it's the same problem as issues-16899.

**Comment by kabaros** [comment]
this, likely, used to work because it was a transitive dependency of @babel/preset-env but was removed after this [PR](https://github.com/babel/babel/pull/16824) so it has to be added explicitly once the minor upgrade happens.
