### ISSUE TITLE
some transformations use arguments, some the actual argument

### ISSUE THREAD

**Issue by lukeapage** [babel/babel#1690]
More of a query / possible small improvement. Thanks for the great project btw!

With the following code
```
const a = (b = 1, {c}) => {
};
```

it is transpiled to

```
"use strict";

var a = function a(_x, _ref) {
  var b = arguments[0] === undefined ? 1 : arguments[0];
  var c = _ref.c;
};
```

how come `_a` is assigned using `arguments[0]` instead of `_x`, but destructing is done with the arg itself ?

It seems using the arg itself would be slightly less code and more compatible if in the future you didn't convert arrow functions to full functions ?

**Comment by sebmck** [comment]
The arity of a function is done up to the last non-default. The `es6.parameters.default` transformer replaces all default parameters with `_x` UIDs in order to retain the parameter position. The behaviour is just consequent of how the transformations are being handled independently. This could possibly be handled as a separate edgecase in the `es6.parameters.default` transformer however it is not a priority by any means. I'll leave this open for a few days but I may close it as it's not really that big of an issue and I'd be open to a PR.
