### ISSUE TITLE
[Bug]: Uncaught Error: Cannot access 'Object' before initialization 

### ISSUE THREAD

**Issue by BleedingDev** [babel/babel#16943]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Use Typebox inside Expo with `t.Object`.

### Configuration file name

.babelrc.js

### Configuration

```js
module.exports = function (api) {
  api.cache(true)
  return {
    presets: [
      'babel-preset-expo'
    ],
    assumptions: {
      'enumerableModuleMeta': true
    },
    plugins: [
      '@babel/plugin-transform-class-static-block',
    ]
  }
}
```

### Current and expected behavior

# Current
Uncaught ReferenceError: Cannot access 'Object' before initialization

# Expected
Do not fail with the following error.

### Environment

  System:
    OS: Windows 11 10.0.26120
  Binaries:
    Node: 20.17.0 - ~\.proto\shims\node.EXE
    npm: 10.9.0 - ~\.proto\shims\npm.EXE
    bun: 1.1.32 - ~\.proto\shims\bun.EXE
  npmPackages:
    @babel/core: ^7.25.8 => 7.26.0
    @babel/plugin-transform-class-static-block: ^7.26.0 => 7.26.0
    @babel/preset-react: ^7.25.7 => 7.25.9
    babel-preset-expo: ~12.0.0-preview => 12.0.0-preview.1
    react-native: 0.76.0 => 0.76.0

### Additional context

Already closed issue (not solved):
https://github.com/babel/babel/issues/10807

Expo issue:
https://github.com/expo/expo/issues/31167

Metro issue:
https://github.com/facebook/metro/issues/1331

**Comment by JLHwung** [comment]
> Use Typebox inside Expo with t.Object.

Can you provide an example of the input code? The posted issues all give examples like `const Object = ...`, which is not supported by Babel due to shadowing of global builtin variables.

**Comment by JLHwung** [comment]
> Cannot access 'Object' before initialization

This is a classica TDZ error, when `const Object = ... ` is defined somewhere in this module, any `Object` reference used earlier than `export const Object` will result to this runtime error. When transforming `.mjs` to common js, Babel depends on the `Object.defineProperty` call, for example [here](https://babel.dev/repl#?browsers=chrome%2084&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgYSgUwIYzQFQJ5hpwC-cAZlBCHAOQB0dA9AMbpZqMwFp0gBWAZxoBuAFChIsRHADSwAHYATEuUrV6TAXhAAjCABsBjBYrQAPXoJGjGjOAFpHT5y9dv3Hz15t38hAOIArhhQij4OXpFR0THi4NDwSACSAgDyYDDAEPIY-ioUVLQMjADmwaGMANYmlkJiZIHyzJnZcABKaACOgcDoijJoeAIAFGCUhLDAaAIAlIiicItwzNkC8JWDAnAAvHAA2gC6Ykvk0HDD-mjrg3AKcGMQE5nTcwgLJ0vAZOcAhCnpLRy-lG4zQk2mew2eAOMxm7w-HyhAjoYECAgAFsMoTNjktiPC4OgYIEoPI4EixPjGAAqalwAAGewAUgJsgd6Sg2NgthgyakdHw0M04FxCHBqYxRA0moC4AB9fmC5ogx5g54CAA0cEegNm8xOK3ka0JXR6fR27VNvTQ_U2KqeU1muMWhuNAmY6LQICwwGYFvQ3Wtijol3kJRg6LgAD44AAGOAAfmkezkSgOAC5aIqhTAaFrRWhMzQIAKc3n7qDwZqTYHzaRM0gUyYM1nS81ywWiyWlbmtQ8HdMSM6TcTSZzMNg_Ghhu7Pd7MswtTqskacaIqbSGczWfJ2eP2Dy-W34AXxZLzJJ4K74NnhbsFcfhHBbHAADwRRz3CACATAHSXCsS0uahPXQIA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.26.2&externalPlugins=&assumptions=%7B%7D) is the transpiled output of the typebox source

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Object = void 0;
var _type = require("../create/type.mjs");
var _index = require("../symbols/index.mjs");
var _kind = require("../guard/kind.mjs");
...
```

For typebox authors: If you insist to shadow the global builtin `Object`, please use `export var`, so that `Object.defineProperty` will still works.

```diff
--- export const Object = _Object;
+++ export var Object = _Object;
```

**Comment by liuxingbaoyu** [comment]
Maybe use `export { _Object as Object };`.

**Comment by liuxingbaoyu** [comment]
@itsyoboieltr Since `globalThis` doesn't exist in all environments, one possible check might be `"undefined"!=typeof globalThis?globalThis:"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{}`, which does more harm than good.
