### ISSUE TITLE
Babel v5.5.11 async/await calls are broken because it uses ~v0.8.20

### ISSUE THREAD

**Issue by mostafaeweda** [babel/babel#1697]
The latest push to the `regenerator@0.8.28` is breaking babel `v5.5.11`
Can we freeze that to `regenerator@0.8.27` at a new npm push of `babel-core@5.1.14` to fix the issue?

/cc @bolinfest @cbosuna @sebmck 

related: https://github.com/facebook/regenerator/issues/205

**Comment by sebmck** [comment]
I'm not sure what you're asking? Why are you using Babel 5.1.x?

**Comment by mostafaeweda** [comment]
I'm asking for an npm push with a new tag: `5.1.14` that has the `regenerator` strictly specified to `0.8.27` not `~0.8.20` because `0.8.28` doesn't work for the 5.1.x branch.

Nuclide & Atom uses babel `5.1.x`, but will probably move to more recent version, but need this minor push to unblock us - thanks.

**Comment by mostafaeweda** [comment]
https://github.com/atom/atom/blob/f850750707950cf7d022e467cd5079c75cdf0f4d/package.json#L25
https://github.com/facebook/nuclide/blob/b0ee9136778bde6b259c1ded58743655effa979e/pkg/nuclide/node-transpiler/package.json#L12

**Comment by sebmck** [comment]
I don't have access to Nuclide. The Atom version is a `^` range so the newest version of `babel-core` will be installed each time. I'm not against pushing a new 5.1.x patch version but I'd like to avoid it if possible because it's a massive hassle and I'd rather not set a precedence of backports, especially when there's literally no reason for you not to be on 5.5.x.

**Comment by sebmck** [comment]
Closing for the aforementioned reasons. Feel free to suggest reopening if this is somehow still a blocker and for some reason you can't upgrade to 5.5.x.
