### ISSUE TITLE
ASI incorrect for async arrow functions

### ISSUE THREAD

**Issue by nmote** [babel/babel#1711]
var async = 5
    var x = async
    (x) => x + 1;

    console.log(x);

By my reading of the [current spec](http://tc39.github.io/ecmascript-asyncawait/#async-function-definitions) for async arrow functions, this arrow function should not be treated as async, since there is no line terminator allowed between "async" and the arrow function arguments. Instead, there should be a semicolon inserted at the end of the second line, and the output should be 5. As it stands, the output is `[Function: x]`

Tested against 55ad88fe4e62444f11ba9ddd29f05c4c44a40bab using babel-node --stage 1

**Comment by sebmck** [comment]
Actually, that code should syntax error.

```javascript
var x = async
(x)
```

should be being parsed as a call and then it should be throwing a syntax error on the arrow.

**Comment by gabelevi** [comment]
As written, [11.9.1 Rules of Automatic Semicolon Insertion](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-rules-of-automatic-semicolon-insertion) states 3 rules. Each rule is structured as "If condition P holds then insert a semicolon".

Considering the code

```JavaScript
var x = async
(x) => x + 1;
```

1. Rule (1) does NOT apply. The "offending token" (the first token that is not allowed by any production) is the `=>`. This token is not preceded by a line terminator, the token is not `)`, and the do-while rule doesn't apply.
2. Rule (2) does NOT apply, since it deals with the end of the token stream
3. Rule (3) DOES apply. The expression is allowed by a restricted production (the [AsyncArrowHead supplemental syntax](http://tc39.github.io/ecmascript-asyncawait/#async-function-definitions)) and has a line terminator exactly where it is forbidden. Therefore a semicolon is inserted.

I do not know what the desired behavior is. But unless I'm misreading something, it does seem like the ES6 spec and the async/await draft spec would insert a semicolon.

Why is this happening to us? Well, this seem to be the first case of an ambiguous restricted production. That is, when you see `async` followed by an `(`, you don't know if it is a call expression or an async arrow function expression. With other restricted productions, I believe there is no ambiguity given the tokens before the `[no LineTerminator here] ` and the single token following.

If the specified behavior is not the desired behavior, maybe the ASI rules should be tweaked, such rule (3) only applies if there is an "offending token" - that is if there are no productions that allow the following production EXCEPT for restricted productions.

It's also possible, I suppose, that the async/await draft spec is breaking some subtle rules around spec'ing grammar, and that's causing this trouble.

**Comment by gabelevi** [comment]
The solution from the [twitter conversation](https://twitter.com/lbljeffmo/status/608014162690772993) that supplemental syntax is not used for ASI would also seem to solve this issue and indicate that

```JavaScript
var x = async
(x) => x + 1;
```

should be a `CallExpression` followed by a syntax error at the `=>`
