### ISSUE TITLE
Decorators without the class transform produce invalid code

### ISSUE THREAD

**Issue by ide** [babel/babel#1713]
I have es7.decorators enabled and es6.classes disabled since my target platform is io.js, which natively supports the class syntax (same deal with Safari 9). This code:
```js
class X {
  @autobind
  method() {}
}
```
turns into:
```js
class X {
  @autobind_method() {}
}
```

**Comment by sebmck** [comment]
You can't blacklist the `es6.classes` transformer if you want to use decorators. It should force the classes transformer to be on. It's counter intuitive to use native class **with** decorators since you need to desugar classes in order to get proper decorator semantics which means you'd get... the same behaviour.

**Comment by ide** [comment]
Ah thanks for the explanation. Will close since this doesn't make much sense.

**Comment by sebmck** [comment]
Actually, there's still a bug here :weary: There's no newline after the decorator. Doesn't really matter much though since no native environment supports decorators.
