### ISSUE TITLE
References to loose-mode module imports not rewritten

### ISSUE THREAD

**Issue by benjamn** [babel/babel#1760]
One of the benefits of using `{ loose: ["es6.modules"] }` is that `import` statements don't have to appear at the top level.

However, references to variable bindings created by nested `import` statements appear not to be rewritten:
```js
function test() {
  import x, {y as z} from "some/module";
  console.log(x, z);
}
```
becomes
```js
"use strict";

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

function test() {
  var _someModule = require("some/module");
  var _someModule2 = _interopRequireDefault(_someModule);
  console.log(x, z);
}
```

I would expect this code to become something like
```js
function test() {
  var _someModule = require("some/module");
  var _someModule2 = _interopRequireDefault(_someModule);
  console.log(_someModule2["default"], _someModule.y);
}
```

**Comment by sebmck** [comment]
This will likely change in the next major. It's far too forgiving and there's no reason to justify the use of module syntax there instead of just using CommonJS.

I'm not quite sure how to support this behaviour since right now the module remapping is global and it'd likely require implementing it in the scope tracking which isn't very reliable since scopes are regularly created/recreated/destroyed as the AST changes.

**Comment by benjamn** [comment]
Here's a justification: what if `some/module` uses ES6 export syntax, so the only way to consume it reliably is to `import` it using ES6 syntax.

Other justifications for nested `import`s, generally: maybe you don't want to `require` the module until it is actually used, to save on page load / startup time; or maybe you want to `import` different modules based on some dynamic condition.

"Too forgiving" is vague language. I hope I've managed to suggest that these imagined use-case restrictions might instead be "too strict." Maybe?

**Comment by benjamn** [comment]
> I'm not quite sure how to support this behaviour since right now the module remapping is global

I think it's acceptable for users who need nested `import` statements to take whatever (small?) performance hit that incurs. I am one of those users, so I'm speaking for myself, at least!

**Comment by sebmck** [comment]
I used far too strong language :stuck_out_tongue:  It's mainly just that there's already enough confusion about how "static" the ES6 module syntax is that some people blindly set `loose` to `"all"` and don't really the consequences and become misinformed on the correct semantics.

> Here's a justification: what if `some/module` uses ES6 export syntax, so the only way to consume it reliably is to `import` it using ES6 syntax.

Well since that file is compiling to CommonJS then the other file(s) you're importing would have to be CommonJS too right? 

> Other justifications for nested `import`s, generally: maybe you don't want to `require` the module until it is actually used, to save on page load / startup time; or maybe you want to `import` different modules based on some dynamic condition.

The main argument that I've had is that why not just use the CommonJS way? If you're against mixing then surely it's just as bad to use invalid syntax?

**Comment by benjamn** [comment]
> Well since that file is compiling to CommonJS then the other file(s) you're importing would have to be CommonJS too right?

The problem is that, while `some/module` compiles ES6 `export` syntax to CommonJS, it compiles to a style of CommonJS that requires things like `babelHelpers.interopRequireDefault` to consume, which is a pain to write by hand—not to mention you'd probably prefer to think of things like `exports.__esModule` and `exports["default"]` as implementation details, and not a public API.

**Comment by sebmck** [comment]
Alright, so I think I can add/fix this behaviour fairly cleanly. It'll require an entire traversal to sweep for module declarations since we can't just assume they're top level which is generally bad for performance (this would only happen if loose mode was turned on for `es6.modules`).

**Comment by benjamn** [comment]
That sounds good to me. I know this is one of those things that would be a lot easier if every transformation had its own full-AST pass, but I fully recognize the importance of all the performance work you've done to collapse the passes, too.

Let me know if I can help with anything!

**Comment by sebmck** [comment]
Alright, I'll need to add some more tests to make sure all bases have been covered. Feel free to come up with some edgecases that can be added as tests to ensure this is as stable as possible. The only caveat is that I've made the following illegal:

```javascript
if (true) {
  import foo from "foo";
} else {
  import bar from "foo";
}
```

ie. duplicate declarations with the same source but in different scope. This is because the second `bar` import will try and reference the `foo` `require` (files are only imported once for simplification) which is out of scope.

> I know this is one of those things that would be a lot easier if every transformation had its own full-AST pass, but I fully recognize the importance of all the performance work you've done to collapse the passes, too.

Yeah, it's definently far easier to use a ton of isolated traversals. It sucks for performance though and the additional maintenance is worth it for the performance boost.

**Comment by benjamn** [comment]
Great! I'll take a look today.

**Comment by benjamn** [comment]
Belated update: this is working very nicely now!

**Comment by sebmck** [comment]
Awesome!
