### ISSUE TITLE
Using variable name as last key of object literal with more than one key doesn't work

### ISSUE THREAD

**Issue by codefox421** [babel/babel#1778]
Working: [(try it out)](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=const%20KEY_NAME%20%3D%20'foo'%3B%0Alet%20myObj%20%3D%20%7B%0A%20%20%5BKEY_NAME%5D%3A%20'blah'%2C%0A%20%20bar%3A%20'baz'%0A%7D%3B)

````javascript
const KEY_NAME = 'foo';
let myObj = {
  [KEY_NAME]: 'blah',
  bar: 'baz'
};
````

Also working: [(try it out)](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=const%20KEY_NAME%20%3D%20'foo'%3B%0Alet%20myObj%20%3D%20%7B%0A%20%20%5BKEY_NAME%5D%3A%20'blah'%0A%7D%3B)

````javascript
const KEY_NAME = 'foo';
let myObj = {
  [KEY_NAME]: 'blah'
};
````

Not working: [(try it out)](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=const%20KEY_NAME%20%3D%20'foo'%3B%0Alet%20myObj%20%3D%20%7B%0A%20%20bar%3A%20'baz'%2C%0A%20%20%5BKEY_NAME%5D%3A%20'blah'%0A%7D%3B)

````javascript
const KEY_NAME = 'foo';
let myObj = {
  bar: 'baz',
  [KEY_NAME]: 'blah'
};
````

**Comment by codefox421** [comment]
@dxprog – You mentioned you wanted to track this.

**Comment by sebmck** [comment]
Your not working example [works](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=const%20KEY_NAME%20%3D%20'foo'%3B%0Alet%20myObj%20%3D%20%7B%0A%20%20bar%3A%20'baz'%2C%0A%20%20%5BKEY_NAME%5D%3A%20'blah'%0A%7D%3B%0Aconsole.log(myObj%5BKEY_NAME%5D)%3B%0Aconsole.log(myObj.bar)%3B&stage=0)? Can you be more specific/detailed about what the issue is?

**Comment by codefox421** [comment]
Never mind. That's my bad. The different syntax of the compiled output threw me off.
