### ISSUE TITLE
Object.defineProperty not used correctly

### ISSUE THREAD

**Issue by romeovs** [babel/babel#1785]
I was trying to get flowtype to work on my code when I spotted this inconsistency.

I had some es code like this:
```js
// example.js
export { FileAdapter } from './persistance';
```

And this gets transpiled into:
```js
// example.js (transpiled)
'use strict';

var _Object$defineProperty = require('babel-runtime/core-js/object/define-property')['default'];

_Object$defineProperty(exports, '__esModule', {
  value: true
});

var _persistance = require('./persistance');

Object.defineProperty(exports, 'FileAdapter', {
  enumerable: true,
  get: function get() {
    return _persistance.FileAdapter;
  }
});
```
I used `babel --stage 0 --optional runtime --blacklist flow` to transpile this code.

Notice how `_Object$defineProperty` is being imported correctly but is then not used. The 
code just uses `Object.defineProperty` instead of `_Object$defineProperty`.

Am I missing something here? Flow says `defineProperty` is not found in `Object` (that's why we polyfill it
using `babel-runtime`).

So either I'm mistaken, or flow is...

**Comment by sebmck** [comment]
Depends. There's no real reason any of those `Object.defineProperty` calls need to use `core-js` (AFAIK) because they are all strings and no browser normalisation would have to be done. I don't think the sourced export declarations will be able to have `Object.defineProperty` rewritten to `babel-runtime` because by the stage they're converted the `runtime` transformers has already ran.

**Comment by zloirock** [comment]
Currently, wrapper for `Object.defineProperty` in runtime uses only for correct work with `Symbol` shim, for this helper it's not required. It's required if will be added ES3 runtime.
