### ISSUE TITLE
WARN optional dep failed, continuing fsevents@0.3.6

### ISSUE THREAD

**Issue by ggd543** [babel/babel#1804]
when `npm install -g babel`, I got the following error: 
>
npm WARN optional dep failed, continuing fsevents@0.3.6
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall" "-g" "babel"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code E404
>
npm ERR! 404 Not Found: babel-plugin-react-display-name
npm ERR! 404
npm ERR! 404 'babel-plugin-react-display-name' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'babel-core'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ggd543\npm-debug.log

Environment: 
OS: Window 7 32 bit
Node: 0.12.4

**Comment by sebmck** [comment]
You can ignore the first error message since as it says, it's an optional dependency and is only required for faster file watching. The second error message is outright wrong and you're likely on an outdated npm mirror as [here](https://www.npmjs.com/package/babel-plugin-react-display-name) the package is listed.
