### ISSUE TITLE
switch...case duplicate declaration warning

### ISSUE THREAD

**Issue by drepo** [babel/babel#1812]
```javascript
function switchCaseWarn(arg) {
  switch(arg) {
    case 'A':
      let name = 'Apple';
      break;
    case 'J':
      let name = 'Jackfruit';
      break;
  }
}

Line 7: Duplicate declaration "name"
````

At any given time only one `case` statement will be executed and therefore `name` is not likely to be duplicated.

Is the warning accurate? I imagine every `case` block has its own scope and variable declared inside it cannot leak to outer scope. Or am I missing something?

**Comment by loganfsmyth** [comment]
switch statements introduce a new block scope around the whole switch body (the parens). Imagine for instance:

```
function switchCaseWarn(arg) {
  switch(arg) {
    case 'A':
      let name = 'Apple';
    case 'J':
      let name = 'Jackfruit';
      break;
  }
}
```
would be invalid because `let name` is declared twice. There no block scope introduced by individual `case` statements.

You can however do so manually if you want, just like you can anywhere else:

```
function switchCaseWarn(arg) {
  switch(arg) {
    case 'A': {
      let name = 'Apple';
      break;
    }
    case 'J': {
      let name = 'Jackfruit';
      break;
    }
  }
}
```

**Comment by drepo** [comment]
Ok! Thanks!
