### ISSUE TITLE
Class method transformations breaking other tools

### ISSUE THREAD

**Issue by talltyler** [babel/babel#1869]
Because Class methods are transformed into an Array of Objects, tools like JSDocs become confused about what is happening. It ends up thinking that every function is called value.

    _createClass(ClassName, [{
      key: 'method',
      value: function method() {}
    }])

Also are there notes about why these transformations need to be formatted this way? I wonder why the transformation isn't just putting methods on a prototype? This seems like it could be solved and optimized by eliminating the _createClass functions.

**Comment by loganfsmyth** [comment]
Sorry, there is no guarantee that the output code from Babel will at all correspond to your input code. If you run processing tools on the output, you do so at your own risk.

The `_createClass` function is needed because `ClassName.prototype.method = function method(){}` would make an enumerable properly, and class properties are not enumerable.

**Comment by sebmck** [comment]
You can use loose mode to get your desired prototype output.

On Monday, 29 June 2015, Logan Smyth <notifications@github.com> wrote:

> Closed #1869 <https://github.com/babel/babel/issues/1869>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1869#event-343311045>.
>


-- 
Sebastian McKenzie
