### ISSUE TITLE
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/class-call-check'

### ISSUE THREAD

**Issue by ruben1** [babel/babel#1872]
Here's my code 
`class Person {
      constructor(name) {
          this.name = name;
      }
}
var person = new Person('Ruben');`

I'm using Webpack with babel-core "^5.6.15" and babel-loader "^5.2.2". It throws an error when transpiling. Module not found: Error: Cannot resolve module 'babel-runtime/helpers/class-call-check'

**Comment by loganfsmyth** [comment]
Did you install `babel-runtime`?

**Comment by sebmck** [comment]
Did you follow the [babel-loader](https://github.com/babel/babel-loader) README and install `babel-runtime`?

```sh
$ npm install --save babel-runtime --save
```

**Comment by ruben1** [comment]
Thanks. Sorry guys, missed that!

**Comment by divyanshupathak** [comment]
Sorry for commenting in closed issue.
I install babel-runtime (v6.20.0), but still got the same error.
Please advice.

**Comment by hkjpotato** [comment]
For anyone still having the same issue, I think u might encounter this problem when u want to bundle babel-runtime into either common chunk or webpack DLL. It is not going to work because babel-runtime does not have a 'main' in their package json, it is exposed as several utilities function, not as a module. Thus it can not be resolved.
