### ISSUE TITLE
Unterminated JSX contents reports as a different error sometimes

### ISSUE THREAD

**Issue by lukekarrys** [babel/babel#1885]
**test.js**
```js
var Component = React.createClass({
  render() {
    return <div>;
  }
});

function () {
  return;
}
```

If I attempt to compile the above file with `babel-node` I get the following incorrect error.
```
./node_modules/.bin/babel-node test.js
SyntaxError: /Users/lukekarrys/Desktop/test/test.js: Unexpected token (8:2)
   6 |
   7 | function () {
>  8 |   return;
     |   ^
   9 | }
  10 |
```

If the `function` is removed then the error type and position are reported correctly as:

```
SyntaxError: /Users/lukekarrys/Desktop/test/test.js: Unterminated JSX contents (3:16)
  1 | var Component = React.createClass({
  2 |   render() {
> 3 |     return <div>;
    |                 ^
  4 |   }
  5 | });
  6 |
```

**Comment by hzoo** [comment]
You shouldn't be able to do 

```js
function () {
  return;
}
```
I think. You can make it a function declaration `function a () {}` or `export default function () {}` though

**Comment by lukekarrys** [comment]
@hzoo I was trying to make the simplest test case I could. But the same thing happens if I make the function

```js
function a () {
  return;
}
```

**Comment by loganfsmyth** [comment]
@lukekarrys As far as I can tell, this isn't actually a bug, it's just that reading JSX is kind of a pain and non-obvious. 

```
var Component = React.createClass({
  render() {
    return <div>;
  }
});

function () {
  return;
}
```

from the parser standpoint is actually:

```
var Component = React.createClass({
  render() {
    return <div>;}});function() {return;}
```

so from the standpoint of JSX, it is seeing

    Opening tag:<div>
    Text: ";}});function()"
    Expression: "return"

Just like if you tried to do

    <div>{return;}</div>

it is throwing an error because of the return in a place where it expects an expression, not because it found an unclosed JSX element.

Potentially you could say that it should throw an error on the unclosed `}` much earlier, but I have no idea how that would compare to other JSX implementations.

**Comment by lukekarrys** [comment]
@loganfsmyth Interesting, and now that I'm seeing it that way it seems obvious. :smile: Thanks for the explanation.

I opened this because I saw it in some actual code today, only the JSX was much larger and the `return` expression didn't occur until further down in the file within some nested fat arrow functions so it made it pretty hard to debug at first site.

I'm gonna close this since it I don't think this is fixable in a standard way, but hopefully this issue will be found by anyone else getting an error like this.
