### ISSUE TITLE
async/await transpiled to callbacks

### ISSUE THREAD

**Issue by thr0w** [babel/babel#1967]
Hi guys, i need less memory consuming and more faster execution on my NodeJS applications.  Use of promises or regenerator it's not a option to me because I do very hard use of async programming.

Than I started work in a babel plugin that transpile async/await to node callbacks: https://github.com/thr0w/asynccbn

I need ideias, criticisms, suggestions... If you can please send me in https://github.com/thr0w/asynccbn/issues

If you can help with tests cases, documentation or coding, you are welcome.

Thanks!

**Comment by sebmck** [comment]
Hi @thr0w, cool plugin :smile: This looks very similar to [nodent](https://github.com/MatAtBread/nodent). There are various issues associated with it that have been discussed in depth in tc39/ecmascript-asyncawait#38. The crux of the issue is that the overhead of Promises is insignificant and if you care about intangible performance like that then you _probably_ shouldn't be using JavaScript. I'd be interesting in seeing how your implementation handles loops and other nested data structures since currently regenerator has to do [a lot](https://github.com/facebook/regenerator/blob/master/lib/emit.js#L382-793) to handle exploding of those constructs.

Also, in the future please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thank you! :blush:

**Comment by thr0w** [comment]
Hi @sebmck , thanks for you help. Sure about create that issue in wrong place.

About overhead of promises, what you think about that: http://thanpol.as/javascript/promises-a-performance-hits-you-should-be-aware-of/

**Comment by sebmck** [comment]
See the top of that article:

> **BEWARE** This article is old, it's 2013 old. Since then things have changed and a winner has prevailed, Bluebird is a Promises Library build with performance in mind and when actually tested with the benchmarks of this article it did even better than Async!

**Comment by matAtWork** [comment]
Old thread I know, but yes, Promises create a small overhead compared to callbacks (in my tests between about 30% and 50%), but generators (early days) are MUCH slower - averaging 3-4 times slower than callbacks.
