### ISSUE TITLE
Babel doesn't support flow number enums

### ISSUE THREAD

**Issue by nmn** [babel/babel#2067]
Flow recently added the awesome disjoint unions feature. As such, it is possible to define enums of string values.

For example, for a typical eventEmitter, you can define an enumeration of supported event names:

```
type EventNames = 'event1' | 'event2' | 'even3' | 'event4'
type MyEventEmitter = {
  on(type: EventNames, hander: () => void): void
  off(type: EventNames, hander: () => void): void
}
```

However, the same doesn't work if the value of the type is an enumeration of numbers:

```
type MyLevels = 1 | 2 | 3 | 4 | 5
```
This throws an error with babel.

**Comment by sebmck** [comment]
Number literal support was added in #2035 so you're likely jsut on an old version. The reason your first example doesn't work is because you're missing a separator between your two properties. See [this](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=type%20EventNames%20%3D%20'event1'%20%7C%20'event2'%20%7C%20'even3'%20%7C%20'event4'%3B%0Atype%20MyLevels%20%3D%201%20%7C%202%20%7C%203%20%7C%204%20%7C%205%3B%0Atype%20MyEventEmitter%20%3D%20%7B%0A%20%20on(type%3A%20EventNames%2C%20hander%3A%20()%20%3D%3E%20void)%3A%20void%2C%0A%20%20off(type%3A%20EventNames%2C%20hander%3A%20()%20%3D%3E%20void)%3A%20void%0A%7D%3B&stage=0) example in the REPL where everything parses/compiles correctly. Thanks :blush:

**Comment by nmn** [comment]
Awesome. Thanks!
