### ISSUE TITLE
Method definition in object initialize with computed property name does not follow spec

### ISSUE THREAD

**Issue by awalGarg** [babel/babel#2080]
In the spec, section 12.2.6.9:

> c. If hasNameProperty is false, perform SetFunctionName(propValue, propKey).

But right now, it doesn't happen: http://bit.ly/1JHWHkM, name of the function is not being set.

Also, the function is defined with the normal `PropertyName: AssignmentExpression` syntax, which would makes it writable not configurable. It should be compiling to something like:

```js
Object.defineProperty(obj, key, {
    value: function <fn name here> { ... },
    configurable: ...
});
```

**Comment by benjamingr** [comment]
I think this is an acceptable and a known limitation. Function names cannot be set in ES5 outside of eval.

**Comment by benjamingr** [comment]
Smaller reproduce case: https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&playground=true&code=let%20name%20%3D%20%22abc%22%3B%0Alet%20abc%20%3D%20function()%7B%7D%3B%0Alet%20o%20%3D%20%7B%0A%20%20%5Bname%5D()%20%7B%7D%0A%7D%0A%0Aconsole.log(%22computed%3A%22%2C%20o%5Bname%5D.name%2C%22with%20var%3A%22%2C%20%20abc.name)%3B

**Comment by sebmck** [comment]
> In the spec, section 12.2.6.9:
> > c. If hasNameProperty is false, perform SetFunctionName(propValue, propKey).

This is impossible to implement with ES5 semantics. I can't even find a reference to `Function.name` in either the ES5 or ES5.1 spec so I'm going to take a stab in the dark and assume that it was some pseudo standard behaviour that's only now standardised with ES6. The ES5 era browsers that did support it had the property set as non-configurable and non-writable too so it can't be overwritten.

> Also, the function is defined with the normal `PropertyName: AssignmentExpression` syntax

This is because you've got loose mode turned on. Turn it off and you get [this](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20memoizer%20(fn%2C%20hasher)%20%7B%0A%20%20let%20cache%20%3D%20Object.create(null)%3B%0A%20%20return%20%7B%0A%20%20%20%20%5Bfn.name%5D(...args)%20%7B%0A%20%20%20%20%20%20let%20id%20%3D%20hasher(...args)%3B%0A%20%20%20%20%20%20if%20(id%20in%20cache)%20%7B%0A%20%20%20%20%20%20%20%20return%20cache%5Bid%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20return%20cache%5Bid%5D%20%3D%20fn(...args)%3B%0A%20%20%20%20%7D%0A%20%20%7D%5Bfn.name%5D%0A%7D%0A%0Alet%20mf%20%3D%20memoizer(function%20foo%20(a%2Cb)%20%7B%0A%20%20return%20a%2Bb%3B%0A%7D%2C%20JSON.stringify)%3B%0A%0Aconsole.log('Name%3A%20'%2C%20mf.name)%3B&stage=0). You can read more about loose mode [here](babeljs.io/docs/usage/loose).

Thanks! :blush:

**Comment by benjamingr** [comment]
@sebmck your stab in the dark is correct, originated here: http://wiki.ecmascript.org/doku.php?id=harmony:function_name_property

**Comment by bergus** [comment]
Since `<fn name here>` is a dynamic expression, it would actually need to be
```js
obj[key] = Object.defineProperty(function() {…}, "name", {value: key}),
```
For static names, this does already work.

Notice that method definitions in object literals produce enumerable properties. Non-enumerability seems to missing for class methods however. See [this repl demo](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=true&playground=true&code=var%20pr%20%3D%20%22x%22%3B%0Avar%20o%20%3D%20class%20%7B%0A%20%20static%20%5Bpr%5D()%7B%7D%0A%7D%0Aconsole.log('Name%3A%20'%2C%20o.x.name)%3B%0Aconsole.log('Enumerability%3A%20'%2C%20Object.getOwnPropertyDescriptor(o%2C%20pr).enumerable)%3B) (expected result would be `x` and `false`, not empty and `true`). This enumerability thing would be a separate issue, though.

**Comment by sebmck** [comment]
@benjamingr Ah cool, thanks for the link!

@bergus

> Since `<fn name here>` is a dynamic expression, it would actually need to be

You'll need to wrap that in a `try-catch` because it'll break on old browsers that have `configurable: false`.

> This enumerability thing would be a separate issue, though.

This was bought up earlier in the thread and it's because you've got loose mode on. Turning it [off](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=true&playground=true&code=var%20pr%20%3D%20%22x%22%3B%0Avar%20o%20%3D%20class%20%7B%0A%20%20static%20%5Bpr%5D()%7B%7D%0A%7D%0Aconsole.log('Name%3A%20'%2C%20o.x.name)%3B%0Aconsole.log('Enumerability%3A%20'%2C%20Object.getOwnPropertyDescriptor(o%2C%20pr).enumerable)%3B&stage=0) does in fact produce the correct result.

**Comment by awalGarg** [comment]
@sebmck ah that makes sense. thanks.

**Comment by bergus** [comment]
@sebmck Ah right I actually knew that it was not configurable in current browsers, I made myself confused by checking [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) who have updated their docs to ES6 already. Need to fix the compatibility section there.

Re enumerability: I couldn't believe that this was not implemented, but somehow thought that enabling "high compliancy" would give me the closest-to-spec possible behaviour. What was the difference to "loose mode", again?

**Comment by sebmck** [comment]
@bergus Loose mode just enables different behaviour and ignores "edge cases". "High compliancy" mode doesn't even exist outside of the REPL and it just enables all the `es6.spec` transformers listed on [this](https://babeljs.io/docs/advanced/transformers/) page.

**Comment by bergus** [comment]
@sebmck Ah, thanks. A help-tooltip might be nice.
