### ISSUE TITLE
ArrowFunction: expression body generates invalid return

### ISSUE THREAD

**Issue by DmitrySoshnikov** [babel/babel#2108]
This generates invalid code:

```js
({
  foo: (/*string*/ x) => /*object*/
    10
});
```

Returns implicit `undefined`:

```js
"use strict";

({
  foo: function foo( /*string*/x) {
    return /*object*/
    10;
  }
});
```

**Comment by sebmck** [comment]
Duplicate/similar to #2106 which was fixed via 4d846e368676fe66cf9649b2fee1dc511e3913eb. Will push out a new release now.

**Comment by DmitrySoshnikov** [comment]
OK, thank you!

**Comment by sebmck** [comment]
Published 5.8.16, thanks!

**Comment by DmitrySoshnikov** [comment]
npm says still 5.8.14 for me

**Comment by sebmck** [comment]
@DmitrySoshnikov Weird, it doesn't appear to have worked. Git tag exists, will look into it.

**Comment by sebmck** [comment]
npm is borked on my machine because I'm using the 3 beta. My fault for using unstable builds I guess, changed my node install to 0.12.7 and npm 2 so I can get consistent reliable builds. Pushed out 5.8.19. Sorry for the trouble, publish process is still unfortunately a little rough. I've been running into environment issues with it meaning that versions aren't being released when they should be, and there's no way to revert so some are just left missing on npm :/ (Although I'm working on rolling back from broken deploys mid-publish)

**Comment by keithamus** [comment]
@sebmck can I suggest setting up travis to automatically deploy new versions? You can set it up so that if it builds on a git-tag it'll release that as the version in npm. [Here's how chaijs does it](https://github.com/chaijs/chai/blob/master/.travis.yml#L16-L25). Makes for a repeatable environment and painless deploys :smile:

**Comment by sebmck** [comment]
@keithamus Already tired that with #1847. Babel isn't a single package now and instead consists of multiple packages. Travis has no support for running arbitrary commands for `deploy` that would facilitate this. It would also sometimes take too long and waiting 15 minutes for a new release is not acceptable.

**Comment by DmitrySoshnikov** [comment]
Yeah, it's OK now, thanks again!
