### ISSUE TITLE
Rest arguments

### ISSUE THREAD

**Issue by zloirock** [babel/babel#211]
Last versions 6to5 use `_argumentsToArray` helper for rest arguments. If we need get all arguments as array, it's a bit faster then `slice.call`, but for `(x, ...args)` see test: http://jsperf.com/njnjnjnjn

All passes `arguments` object to function deopt function https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments
Maybe better inline args2array conversion?

``` javascript
// for (...VAR_NAME):
for(var _l = arguments.length, VAR_NAME = Array(_l), _i = 0; _i < _l;)VAR_NAME[_i] = arguments[_i++];

// for (SOME, ARGS, ...VAR_NAME):
for(var _l = arguments.length, VAR_NAME = Array(_l - NUM_ARGS), _i = NUM_ARGS; _i < _l;)VAR_NAME[_i - NUM_ARGS] = arguments[_i++];
```

**Comment by phpnode** [comment]
Sorry to nag about this, but this is still a problem, and actually the issue is not restricted to V8, SpiderMonkey also exhibits a similar issue, [although to a lesser extent](http://jsperf.com/leaky-arguments).

The code @sebmck pointed to is not relevant to this, that makes the `Array.prototype.slice()` function faster when it's called with an `arguments` context, great, but unfortunately the function that is making the call to `slice` is getting deoptimised - in that jsperf it shows a 20x performance difference, for a very trivial function, for some real world code this could be a 1000x difference. [This gist](https://gist.github.com/phpnode/c4f218c1a4391c93cce9) shows the deopts happening in V8.

I think mitigating the potentially massive performance hit is worth an extra couple of lines in the output.

**Comment by goto-bus-stop** [comment]
See also: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments

**Comment by sebmck** [comment]
As of 2.6.0, 6to5 now uses a for loop instead of `Array.prototype.slice`.

**Comment by phpnode** [comment]
@sebmck awesome!
