### ISSUE TITLE
Published version of babel-runtime does not match babel-core

### ISSUE THREAD

**Issue by bolinfest** [babel/babel#2110]
At this moment, `babel-core` is at 5.8.14 while `babel-runtime` is at 5.8.12.

**Comment by sebmck** [comment]
It's not meant to. Releases of new packages are only made when there are changes.

**Comment by sebmck** [comment]
Closed for the aforementioned reason. All of the Babel packages operate on one version line and if there are changes made to a package since the last release then it's released again with the main version. You can see the main version [here](https://github.com/babel/babel/blob/master/VERSION). The main version doesn't guarantee a release for any specific package only that at least one of them has been released with that version. One main version line makes things much easier to manage and if all the packages use a stable public API then there's no risk of breaking due to version mismatches.
