### ISSUE TITLE
Babel/JSX produces wrong output when backslashes are used in DOM attributes

### ISSUE THREAD

**Issue by quozd** [babel/babel#2114]
Hello guys. Recently I faced an issue with using Regex-like strings in JSX when updated my babel package. JSX compiler should replace `\` with `\\` in attributes. But newer versions of Babel don't do it.

Test code:
```
var Test = React.createClass({
  render: function() {
    return <div pattern="^([\w\.\-]+\s)*[\w\.\-]+\s?$"></div>;
  }
});
```

Babel output:
```
"use strict";

var Test = React.createClass({
  displayName: "Test",

  render: function render() {
    return React.createElement("div", { pattern: "^([\w\.\-]+\s)*[\w\.\-]+\s?$" });
  }
});
```

React tools output:
```
var Test = React.createClass({displayName: "Test",
  render: function() {
    return React.createElement("div", {pattern: "^([\\w\\.\\-]+\\s)*[\\w\\.\\-]+\\s?$"});
  }
});
```

Compare `pattern: "^([\w\.\-]+\s)*[\w\.\-]+\s?$"` (babel) and `pattern: "^([\\w\\.\\-]+\\s)*[\\w\\.\\-]+\\s?$"` (official jsx).
Babel 5.4.0 worked as expected. Newer versions produce invalid response. 

I think Babel should produce the same code as React tools. Thank you

**Comment by sebmck** [comment]
I'm not sure why jstransform is transforming JSX attributes like that. I'm fairly confident that it's not the expected behaviour. Do you have any other reasoning besides it just being the behaviour of jstransform? It's not entirely unreasonable for this to just be the new behaviour if it's deemed more appropriate (if indeed this is an inconsistency between implementations).

**Comment by sebmck** [comment]
This does appear to be a bug in `esprima-fb`, JSX attribute literals should behave the same as normal JS ones.

**Comment by quozd** [comment]
Well, Babel's behavior feels more natural for me. But Babel stands to be fully compatible with JSXTransform IIRC. If you want to keep current behavior, it should be at least documented, because it may produce unexpected bugs which are not so easy to detect sometimes (like in my case).

**Comment by sebmck** [comment]
jstransform is effectively dead and parity with it isn't a requirement anymore. Deviations can be made if they're deemed appropriate.

**Comment by quozd** [comment]
In this case it would be great to mention such deviations at least for some time. There are plenty of folks who still use jstransform and such undocumented differences will make migration painful.

**Comment by mAiNiNfEcTiOn** [comment]
@sebmck so in other hands, before it was working, now it is not... And your reaction was:

"Oh it changed... Well I don't know why, but I guess it is ok because the other project that we said that we were completely supporting is now deprecated..."

And btw, the JSXTransform was deprecated in favor of your implementation, now you're breaking it

#letsGetBackToThePreviousVersionAndGetStuckToIt ...

Tell me... are you planning to do other "not known" changes on deprecated projects that you are supporting?

**Comment by sebmck** [comment]
@mAiNiNfEcTiOn 

> so in other hands, before it was working, now it is not

No. This is an inconsistency between two projects. Babel has always worked this way.

> And btw, the JSXTransform was deprecated in favor of your implementation, now you're breaking it

As I said before, this is likely an oversight on jstransform/esprima-fbs behalf.

> #letsGetBackToThePreviousVersionAndGetStuckToIt ...

It's not as simple as this. You're suggesting that I make a **breaking change** to the way **Babel** behaves. This will break more existing users rather than those migrating from jstransform.

> Tell me... are you planning to do other "not known" changes on deprecated projects that you are supporting?

I don't like what this is trying to imply. Babel will **not** have any breaking changes between patches/minors and if there is then it's clearly an oversight that needs to be fixed immediately.

**Comment by quozd** [comment]
Babel already made a breaking change between 5.4 and 5.8. So, this change should be either documented or considered as a bug.

**Comment by sebmck** [comment]
@quozd Please describe your upgrade path. Your original issue only describes an inconsistency between jstransform and Babel. Not a breaking change between Babel versions.

**Comment by quozd** [comment]
@sebmck 3 days ago we upgraded Babel from 5.4 to the latest and some code became broken.

**Comment by sebmck** [comment]
Thanks for the clarification, the references to jstransform had me confused, my apologies. Regression due to f0994f106eb5270508bf523601a827fcf77f6fe5, related #2078.

**Comment by mAiNiNfEcTiOn** [comment]
/me apologizes for the _rude_ approach. Thank you for your comprehension.

**Comment by ScottDowne** [comment]
I'm hitting this. Not sure why this is closed, did it get resolved?

I have an input for credit card expiry date that has a pattern like this:

`pattern="\d{2}"`

which is being converted to:

`pattern="d{2}"`

5.4 doesn't do this.

**Comment by sebmck** [comment]
@ScottDowne Yep, see the attached commit.
