### ISSUE TITLE
babel-node script doesn't handle children dieing well without kexec module (should handle child proce's error event)

### ISSUE THREAD

**Issue by jhford** [babel/babel#2137]
Relevant code: https://github.com/babel/babel/blob/b9dde49ab6c3c86674713894b6c2eec665e8c1c5/packages/babel-cli/src/babel-node.js#L433-L434

I have an application that uses babel.  We're currently using the babel-node script instead of doing a static compile for simplicity.  I recently spent time over the last two weeks trying to debug an issue where the application would just stop doing things.  I had a `setTimeout` that makes sure that the process never goes more than 10 minutes without doing work, but it wasn't firing.  The application just sat there with the machine having a  0.00 load average.  It was unfortunately only reproducing when deployed to Heroku, which doesn't offer very much in the way of live debugging.

We eventually realised that what must have been happening was that the child `node` process was dieing, but because the parent `babel-node` process didn't handle this situation properly, it didn't really know that it should have quit.   Because Heroku does monitor for the process staying around, and because the parent process is the one being tracked, Heroku didn't know to restart the process.

This was the only part of our project that was using babel-node but didn't have kexec installed, once we installed kexec, the problems went away.

I don't know whether this is an issue that you want to handle, but I would think that it's undesirable.

**Comment by sebmck** [comment]
It was previously listed in `optionalDependencies` but was removed in 14e92e9e3f4742899ea2946e78b978a308cf63a8 because there was a constant barrage of issues about "babel wont install on X" because npm doesn't suppress the errors when optional dependencies fail to install which confuses an awful lot of people. IIRC there was a note about this in the FAQ or the babel-node docs page, if it's not then can you please open an issue on the [babel.github.io](https://github.com/babel/babel.github.io) repo to add it?

I've been pretty vocal in the past about that you really shouldn't be using `babel-node` in production as it's unnecessarily heavy. Your memory usage is going to very high on large apps since the cache is always stored in memory. You'll also always have that startup performance penalty as the entire app needs to be compiled on the fly.
