### ISSUE TITLE
Arrow functions in Promise chain using bind(), set `this` to `undefined`

### ISSUE THREAD

**Issue by datfinesoul** [babel/babel#2141]
Hi,

Based on everything I have read about arrow functions I would have assumed that the following two Promise chains would produce the same results:

```javascript
import * as P from 'bluebird'

P.bind({ hello: 'world'})
.then ((result) => {
  console.log(this);
});

P.bind({ hello: 'world'})
.then (function (result) {
  console.log(this);
});
```

but it seems like the `this` in the arrow function call is turning into `undefined`

```javascript
'use strict';

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newOb

var _bluebird = require('bluebird');

var P = _interopRequireWildcard(_bluebird);

P.bind({ hello: 'world' }).then(function (result) {
  console.log(undefined);
});

P.bind({ hello: 'world' }).then(function (result) {
  console.log(this);
});
```

Using babel-core 5.8.20, iojs v2.5.0 and bluebird for promises.

**Comment by sebmck** [comment]
This is expected behaviour. Please see the [FAQ](https://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-) as well as issues #1988, #1700, #1667, #1573, #562, #814, #730 and #733. The context that an arrow function is called with has no effect and instead the outer `this` is used. In ES2015 module code this is `undefined` and not the global like in scripts.

**Comment by datfinesoul** [comment]
Thank you so much for the awesome response, and sorry for missing the notes in the FAQ.
