### ISSUE TITLE
Parentheses around comments

### ISSUE THREAD

**Issue by Jigarsolanki** [babel/babel#2150]
Why does Babel remove inline parentheses after a comment and adds it around it? 

```javascript 

function test () {
 return /** @type {Object} */ ({});
};
```
converts to 

```javascript
"use strict";

function test() {
  return (/** @type {Object} */{}
  );
};
```

Is this intentional? If yes, why so?

**Comment by sebmck** [comment]
It's due to the way the code generator works. The code generator has no idea what comes after a bit of code once it's pushed to the buffer. It needs to be wrapped in parens to ensure that if there's line terminators that it wont break semantics. The newline before the last `)` probably shouldn't be there, I'll see what can be done about it I guess.

**Comment by sebmck** [comment]
If you have any further questions please don't hesitate to use one of the resources located in the [README](https://github.com/babel/babel#readme):

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks! :blush:
