### ISSUE TITLE
import * as lib from 'lib' in multiple files throws duplicate declaration error on compilation

### ISSUE THREAD

**Issue by davismj** [babel/babel#2153]
So, we have various files that are being compiled into a single library, many of which depend on core-js. The syntax `import core from 'core-js'` is invalid because core-js does not export default. However, compiling `import * as core from 'core-js'` in multiple files throws an error: Duplicate declaration "core".

**Comment by sebmck** [comment]
Can you provide some code to reproduce? It's hard to understand what you mean.

**Comment by jmm** [comment]
@davismj How are they being compiled -- not just concatenation, right?

**Comment by davismj** [comment]
So, in [this repo](https://github.com/davismj/binding/tree/master/src) both `property-observation.js` and `map-observation.js` depend on core-js, and as such include `import * as core from 'core-js'` at the beginning of the file. However, running the [build task](https://github.com/davismj/binding/blob/master/build/tasks/build.js) in this repo  throws the error message: 
> Duplicate declaration "core".

**Comment by sebmck** [comment]
That error is correct then, there are duplicate declarations which isn't allowed.

**Comment by davismj** [comment]
So there is no way for us to import all exports from core-js in both `property-observation.js` and `map-observation.js` and then compile them into a single library?

**Comment by jmm** [comment]
@davismj You can't just concatenate the files. I'm guessing your build task is supposed to be extracting the `import` declarations from each module and inserting them all at the beginning of the concatenated file, but I'm not sure.

**Comment by davismj** [comment]
We're just using gulp-babel, with [these compiler options](https://github.com/davismj/binding/blob/master/build/babel-options.js). Ideally, the behavior of the import all will mimic the behavior of the specific imports, where specifying `import {Class} from 'lib'` multiple times does not throw a Duplicate declaration error.

**Comment by EisenbergEffect** [comment]
This issue can be closed. We have some custom build code that should handle this. It's not a Babel issue.

**Comment by jmm** [comment]
@davismj I suspect the problem is in your `build-index` task. You appear to be [concatenating](https://github.com/davismj/binding/blob/76fac6a455a70ed5c517f6979d6c225eda7c681a/build/tasks/build.js#L56) the files. There are some transforms before and after that I'm guessing are supposed to remove `import` declarations from individual files and prepend them all to the beginning of the concatenated code and I'm guessing that's failing. If that's the case then babel is going to choke on that input because it's invalid. I suggest you make a copy of your `build-index` task that just includes the 2 files you named and check the output from it.

I see this is your first time here on the babel issue tracker. Welcome! For future reference, this problem isn't a good fit for the issue tracker. Per the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

So far to me it sounds like this is going to turn out to be providing bad input to babel. It'd actually be ideal to continue this discussion on slack. In either case, a minimal repro will speed identification of the problem and make other people more likely to be able to help you debug it.

**Comment by sebmck** [comment]
@davismj 

> Ideally, the behavior of the import all will mimic the behavior of the specific imports, where specifying `import {Class} from 'lib'` multiple times does not throw a Duplicate declaration error.

You're concatenating those files together, there's no way to tell where they came from.

@EisenbergEffect Noted, thanks! :blush:
