### ISSUE TITLE
Arrow functions and flow tags

### ISSUE THREAD

**Issue by blainekasten** [babel/babel#2170]
Frankly, I'm not sure who's bug this is. If you think it's facebook's flow library's bug, I'll throw it to them. Essentially this is erroring out:

```js
() => : number 1
() : number => 1
```

Doesn't seem possible to document return value on arrow functions.

**Comment by sebmck** [comment]
What's your Babel version? Your first example doesn't compile while the second does.

**Comment by blainekasten** [comment]
`^5.8.20`

**Comment by sebmck** [comment]
Are you sure? Your [first example fails](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=()%20%3D%3E%20%3A%20number%201), while the [second one works](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=()%20%3A%20number%20%3D%3E%201). Return types for arrow functions were added in #1991. Can you explain your issue exactly? I'm not sure I understand what the problem is.

**Comment by blainekasten** [comment]
well.. I'm no longer able to reproduce. So I'll just assume I did something wrong. Thanks
