### ISSUE TITLE
Extending null throws "Derived constructor must call super()"

### ISSUE THREAD

**Issue by marijnh** [babel/babel#2203]
When I do something like

```javascript
class Foo extends null { hello() { return 10 } }
let x = new Foo
```

Babel 5.8.22 generates a constructor that contains the line `_ref.apply(this, arguments);`, which will crash  when `_ref` is null. Maybe change the output to `_ref && _ref.apply(...)`?

**Comment by zloirock** [comment]
Looks like it's correct behavior. See, for example, https://github.com/kangax/compat-table/issues/436, [this article](http://www.2ality.com/2015/02/es6-classes-final.html#allocating_and_initializing_the_instance_object) or try in Chrome
```js
new (function(){'use strict';return class extends null{}}())
// and
new (function(){'use strict';return class extends null{constructor(){return {}}}}())
```
 Yep, it looks strange.

**Comment by marijnh** [comment]
I'm not saying that extending null shouldn't be allowed. I'm saying that it is currently broken.

**Comment by zloirock** [comment]
Extending `null` allowed, but class should contains constructor and constructor should return object. Or you propose ignore spec? :)

**Comment by marijnh** [comment]
Can you show me a piece of code that extends null and works with current Babel? I wasn't able to find one.

I did notice that the problem only exists in loose mode.

**Comment by zloirock** [comment]
Hmm, yes, I see problem with extending `null` in loose mode. And in default too - my second example from first comment not compiled. But your example compiled and throws error correct :)

**Comment by motiz88** [comment]
Closing this since the final ES2015 spec now seems to allow `extends null` with an implicit constructor, and as we have [multiple][1] [tests][2] [covering][3] Babel's current `extends null` behavior.

[1]: https://github.com/babel/babel/blob/4c371132ae7321f6d08567eab54a59049e07f246/packages/babel-preset-es2015/test/fixtures/esnext/es6-classes/extends-null.js
[2]: https://github.com/babel/babel/blob/4c371132ae7321f6d08567eab54a59049e07f246/packages/babel-preset-es2015/test/fixtures/traceur/Classes/DefaultConstructor.js
[3]: https://github.com/babel/babel/blob/4c371132ae7321f6d08567eab54a59049e07f246/packages/babel-preset-es2015/test/fixtures/traceur/Classes/ExtendStrange.js
