### ISSUE TITLE
toJSON on Map and Set prototypes 

### ISSUE THREAD

**Issue by sonnyp** [babel/babel#2217]
Running in babel, Map and Set prototypes have a toJSON function property.

test.js
```javascript
"use strict"
console.log(Map.prototype.toJSON);
```

```node test.js``` outputs "undefined" all good
```babel-node test.js``` outputs "[Function: toJSON]"
```babel test.js``` outputs the same content as ```test.js```

babel 5.8.21
Node.js 0.12.7

**Comment by zloirock** [comment]
It's [ES7 proposal](https://github.com/zloirock/core-js#ecmascript-7). Any problems?

**Comment by sonnyp** [comment]
Well I wrote a JSON serializer that supports Map and Set although it doesn't serialize Map the way the proposal toJSON does. I added toJSON support and got surprised by the behavior as the toJSON property on the prototype would override my default behavior.

**Comment by zloirock** [comment]
Discussion about `Map` serialization behavior see [here](https://github.com/DavidBruant/Map-Set.prototype.toJSON/issues/1).

Now it's only stage 0 proposal, if you uses your serializer only in personal projects, instead of usage `babel-node` or `babel-polyfill` you can [include](https://github.com/zloirock/core-js#commonjs) `core-js` w/o this module.
