### ISSUE TITLE
package.json hopelessly limited in content

### ISSUE THREAD

**Issue by ronkorving** [babel/babel#2273]
Hi guys and girls,

I noticed that https://www.npmjs.com/package/babel-core shows no readme. I'm still not sure why, but when I opened up package.json I was a bit shocked with how many fields were missing. Is it me, or is something weird going on here? Also, what is up with the package [being set to private](https://github.com/babel/babel/blob/8c98386434090eeaf345e720961b5a125e3908d3/package.json#L2)?

**Comment by sebmck** [comment]
Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

The root `package.json` is bare because it just includes the dependencies for the entire project itself. Babel consists of multiple modules available in the [packages](https://github.com/babel/babel/tree/master/packages) directory, you can likely find the `package.json` files you're looking for there. Thanks! :blush:
