### ISSUE TITLE
Plugin visitor order

### ISSUE THREAD

**Issue by KnisterPeter** [babel/babel#2318]
Hi there,

I think the plugin visitors don't respect the source/ast order.
I have a jsx-visitor registering JSXOpeningElement, JSXClosingElement, JSXExpressionContainer and the call order in my case (example given below) is JSXOpeningElement, JSXClosingElement, JSXExpressionContainer instead of JSXOpeningElement, JSXExpressionContainer, JSXClosingElement.
How to deal with this?

    <div>{someexpression}</div>

Is this expected behaviour?

**Comment by sebmck** [comment]
This is expected behaviour. It's how the visitor keys are defined. I do agree that `closingElement` after `children` makes the most sense though. I've made this change in the `development` branch and it will be released in 6.0.0. Technically changing the visitor key order is a breaking change and would require a major release but I doubt this would break anything, but it's better to be safe than sorry.

**Comment by KnisterPeter** [comment]
Okay, I agree with you on this.
Since I could not wait for 6.0 I have to traverse the AST on my own then.
Thanks for your clearification.
