### ISSUE TITLE
New babel-runtime release?

### ISSUE THREAD

**Issue by taion** [babel/babel#2371]
The new React v0.14.0-rc1 optional optimizations currently aren't compatible with the `runtime` option. This appears to be because the current `babel-runtime` release is still v5.8.20, which lacks some of the new helpers.

Would it be possible to cut a new `babel-runtime` release, or am I doing something incorrectly?

**Comment by taion** [comment]
Specifically these failures are due to e.g. `typeof-react-element` being missing in the current NPM release of `babel-runtime`.

**Comment by sebmck** [comment]
Should have been released when I pushed 5.8.24 but apparently not. I've just pushed 5.8.24 of `babel-runtime` to npm.

**Comment by taion** [comment]
Thanks! For whatever reason it hasn't been updated since 5.8.20, so something might be getting missed in the deploys.

**Comment by sebmck** [comment]
A new version is only released when a new helper is added/changed.

**Comment by dtothefp** [comment]
@taion thanks for this issue. I'm also using the runtime and was having the same problem. Once updating to `5.8.24` for the runtime I'm getting a different issue, I think related to es6 compilation of the `typeof-react-element` helper.

```js
"use strict";

var _Symbol = require("babel-runtime/core-js/symbol")["default"];

exports["default"] = typeof _Symbol === "function" && _Symbol."for" && _Symbol."for"("react.element") || 60103;
exports.__esModule = true;
```

@sebmck Looks like the `for` property from the `Symbol` object is being converted to a string from the following source:

https://github.com/babel/babel/blob/ade747eb9c9d4a0224d683140784e9da9b8beef5/packages/babel/src/transformation/templates/helper-typeof-react-element.js

Assuming this isn't intentional?

**Comment by loganfsmyth** [comment]
@dtothefp Since your issue is separate and this has been closed, please report it as a new issue.

**Comment by dtothefp** [comment]
@loganfsmyth thanks for the response, reported here https://github.com/babel/babel/issues/2377
