### ISSUE TITLE
node 4.0 babel  es6.modules

### ISSUE THREAD

**Issue by Pana** [babel/babel#2407]
When i use babel on node4.0 i want only use three transform ['es6.destructuring', 'es6.parameters', 'es6.modules'], but it will throw an error

```js
let path = require('path');
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

Does anybody know why and how to solve this.

**Comment by Pana** [comment]
My code ha 'use strict' in the top, and node4.0 support let, const

**Comment by Pana** [comment]
when i add 'es6.blockScoping' everything got worked, but node 4.0 has support let yet, i don't want use babel blockScoping transformer

**Comment by sebmck** [comment]
If your target environment doesn't support block scoping then you need to enable the transformer for it. Babel desugars some ES2015 features into other ES2015 features for simplicity and correctness.

**Comment by loganfsmyth** [comment]
@Pana Are you using a whitelist of transforms? You should enable `useStrict` and this issue should go away.

**Comment by Pana** [comment]
@loganfsmyth  Yeah i am using whitelist, what do you mean by enable `strict`, all my code file has `use strict` do you mean this ?

**Comment by loganfsmyth** [comment]
@Pana Babel has a `strict` transform that you'd use alongside `es6.destructuring` and anything else that adds `use strict` for you automatically. It is on by default but you have disabled it because you are using a whitelist. Seems like you'd be better off blacklisting transforms you don't want, rather than whitelisting the ones you don't, that way you avoid the issue of potentially disabling something that you didn't realize should have been enabled (like this).

**Comment by Pana** [comment]
Got it, thanks very much
