### ISSUE TITLE
browser.js can not be interpreted in Nashorn

### ISSUE THREAD

**Issue by elennaro** [babel/babel#2444]
Hello.
I'm trying to run browser.js in Nashorn, to use babel.transform in the library for some Isomorphic Webapp.
But Nashorn claims that he can't evaluate browser.js:

````
javax.script.ScriptException: <eval>:1:1 Expected ; but found error
﻿
 ^ in <eval> at line number 1 at column number 1
java.lang.Error: javax.script.ScriptException: <eval>:1:1 Expected ; but found error
﻿
 ^ in <eval> at line number 1 at column number 1
````

For details see [StackOverflow Question](http://stackoverflow.com/questions/32818826/how-to-run-browser-js-from-babel-in-nashorn).

I use browser.js from **babel-core**, installed by *npm*.

**Comment by thejameskyle** [comment]
Babel does not support JavaScript platforms other than Node/io.js, and the browser bundle is only targeting modern browsers. If it works elsewhere, great, but otherwise we're not going to actively support anything else.

As for Nashhorn, I don't know anything about her so I can't tell you what that error is.

Closing as wontfix.
