### ISSUE TITLE
Error while importing from a variable module path

### ISSUE THREAD

**Issue by jatins** [babel/babel#2475]
I have multiple levels of nested folders and to import a module I have to something like
```js
import { test } from '`../../../src/query`'
```
Instead of that, I wanted to do something like
```js
import { test } from ROOT + '/src/query'
```
where I, say, somehow get the `ROOT` constant.

However, Bable throws a parse error when I try to do that?
Is this the expected behavior? Any other way to use variable module paths?

**Comment by jmm** [comment]
Hello @jatins, welcome to the Babel community! As explained in the README, the issue tracker isn't used for questions and general support, and suggests other places for that:

> 
<p align="center">
  For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
</p>

Re: your question, yes, that's expected behavior, because this isn't valid syntax:

> 
```js
import { test } from ROOT + '/src/query'
```

You can use the `resolveModuleSource` option. For example, you can write your code like:
```js
import { test } from 'ROOT/src/query'
```

Then replace `ROOT` in a `resolveModuleSource` function. If you happen to be using browserify you could alternatively use my [`pathmodify`](https://github.com/jmm/pathmodify) plugin. If you want to try `resolveModuleSource` and need more help, please ask at one of the places suggested by the README. Thanks!
