### ISSUE TITLE
Throw on bad import

### ISSUE THREAD

**Issue by jacobp100** [babel/babel#2486]
Should an error be thrown when attempting to import variables that are non-existent (even if it’s a runtime error)? Or is there an option for this?

``` js
// a.js
import { c } from ‘./b’;
```

``` js
// b.js
export const d = 4;
```

**Comment by forivall** [comment]
Correct me if I'm wrong, but throwing an error isn't party of the spec: http://www.ecma-international.org/ecma-262/6.0/index.html#sec-exports-runtime-semantics-evaluation

**Comment by loganfsmyth** [comment]
This was discussed a little bit in https://github.com/babel/babel/issues/2392. I'll probably try to see if I can get this to work at some point, but there are a few other changes that'd need to land first. It's not as easy as it sounds, since Babel doesn't do  any cross-file processing, so it'd have to be more runtime code.

@forivall That spec link is incorrect since it's about export statements, not import. The part of the spec that defines this is http://www.ecma-international.org/ecma-262/6.0/index.html#sec-moduledeclarationinstantiation, specifically `12.d.iii` states

> If resolution is null or resolution is "ambiguous", throw a SyntaxError exception.

**Comment by sebmck** [comment]
Throwing a SyntaxError seems weird, wonder why it's not a ReferenceError.

**Comment by jacobp100** [comment]
I'd say runtime is poeticall probably the right thing. If people are using script tags as modules, there would be no way to check across files.

**Comment by hzoo** [comment]
We can probably add this as an option, and turn it on in development or something?

**Comment by Kovensky** [comment]
That was one part of the spec mode patch

**Comment by jharris4** [comment]
Any news on this? Our team keep getting burned by typos in imports and we'd love to see a way to make babel warn about this. Otherwise I guess eslint would be another option... https://github.com/eslint/eslint/issues/6541

**Comment by loganfsmyth** [comment]
I think most people end up using https://www.npmjs.com/package/eslint-plugin-import

**Comment by jharris4** [comment]
yeah, we'll look into that if we start using `eslint`. But in the meantime, we're now using this babel plugin which seems to do the job: https://github.com/dozoisch/babel-plugin-import-asserts
