### ISSUE TITLE
Destructuring in function arguments leads to invalid handling of other arguments

### ISSUE THREAD

**Issue by ochrons** [babel/babel#2488]
How to reproduce:
```
function sumProduct(s) {
  return s.reduce(([sum, product], x) => 
    [sum + x, product * x], 
    [0, 1]
  );
}
```

Babel REPL in high compliancy (and loose mode) mode generates following:
```
"use strict";

var _temporalUndefined = {};

function _temporalAssertDefined(val, name, undef) { if (val === undef) { throw new ReferenceError(name + " is not defined - temporal dead zone"); } return true; }

function sumProduct(s) {
  return s.reduce(function (_ref, x) {
    var sum = _temporalUndefined;
    var product = _temporalUndefined;
    var x = _temporalUndefined;
    sum = _ref[0];
    product = _ref[1];
    x = arguments.length <= 1 || arguments[1] === undefined ? undefined : arguments[1];
    return [(_temporalAssertDefined(sum, "sum", _temporalUndefined) && sum) + (_temporalAssertDefined(x, "x", _temporalUndefined) && x), (_temporalAssertDefined(product, "product", _temporalUndefined) && product) * (_temporalAssertDefined(x, "x", _temporalUndefined) && x)];
  }, [0, 1]);
}
```

This does not work on Chrome because `var x = _temporalUndefined;` actually overwrites  `arguments[1]`. Changing the name of the `var` fixes the issue, so Babel should not reuse function parameter names as variables.

**Comment by loganfsmyth** [comment]
That sample seems to work in the Babel REPL for me: http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=true&playground=true&code=function%20sumProduct(s)%20%7B%0A%20%20return%20s.reduce((%5Bsum%2C%20product%5D%2C%20x)%20%3D%3E%20%0A%20%20%20%20%5Bsum%20%2B%20x%2C%20product%20*%20x%5D%2C%20%0A%20%20%20%20%5B0%2C%201%5D%0A%20%20)%3B%0A%7D%0A%0A%0Aconsole.log(sumProduct(%5B1%2C%202%2C%203%2C%204%2C%206%5D))%3B

Strict mode detaches the `x` argument binding from `arguments` so as long as the `use strict` is there, this should work fine in Chrome.

You are correct though that this code will break in non-strict code. This has been discussed in  https://github.com/babel/babel/issues/2374 among other places and will be fixed in Babel 6.x.

**Comment by sebmck** [comment]
What @loganfsmyth said.
