### ISSUE TITLE
The whole runtime gets included with `--optional runtime` instead of the used parts

### ISSUE THREAD

**Issue by polkovnikov-ph** [babel/babel#2511]
Why does the whole `babel-runtime/core-js` get included when using `--optional runtime`? I see `babel-runtime/core-js/symbol` and `babel-runtime/core-js/object/create` in the generated code, while the only thing I need is `Promise`.

In case there's some way to properly mention `babel-runtime` parts in command line, shouldn't it be at least linked at https://babeljs.io/docs/usage/runtime/?

UPD. By the way, what's with the title? Seems to be a misclick.

**Comment by loganfsmyth** [comment]
Please show us some of the code you were building, since it's impossible to say otherwise.

**Comment by profencer** [comment]
I think it's pretty obvious, because it's written in the linked documentation. Will `new Promise(function () {});` be enough as code example?

**Comment by loganfsmyth** [comment]
`Promise.all` takes an iterable as an argument, and iterables are defined in terms of `Symbol.iterator` so it needs to be loaded. It's impossible to know if you're going to pass it something that is iterable or not.

I'm not sure what more there is to do here, since this isn't really in Babel's control anyway, it is a fact of `core-js`. If you're using a feature that depends on something else, it'll load both. It seems unrealistic to expect every dependency in core-js to be documented.
