### ISSUE TITLE
react.inlineElements breaks on older browsers when ignoring node_modules

### ISSUE THREAD

**Issue by STRML** [babel/babel#2517]
Generally, when using babel / `babel-loader` it is common to ignore `node_modules` for faster compilation speed.

The definition of the `$$typeof` attribute we're looking for is:

```js
var REACT_ELEMENT_TYPE = typeof Symbol === 'function' && Symbol['for'] && 
                         Symbol['for']('react.element') || 0xeac7;
```

And this is pushed into a shared module that exports it when using the `react.inlineElements` transform.

Here's the problem:

On older browsers that don't support `Symbol`, like Safari 7 / Chromium 30, `Symbol` is polyfilled by the core-js runtime. But the same definition of `REACT_ELEMENT_TYPE` is present inside `node_modules/react/lib/ReactElement.js`, and this is *not* polyfilled by oore-js and therefore equals `0xeac7`.

This causes the element test to fail on render (comparing a shimmed Symbol to `0xeac7`) and breaks the render on those browsers.

I propose, rather than redefining `REACT_ELEMENT_TYPE` directly so it can be used in the inline elements (and thus having it break if upstream ever changes it), let's just instantiate an element and export its `$$typeof`.

**Comment by syranide** [comment]
To me it seems trivial for React to just export `React.REACT_ELEMENT_TYPE` instead, allows anyone to create these objects without duplicating internals. But perhaps that's a bad idea for other reasons.

I'm also curious if the babel-plugin could simply generate code that isn't interpreted by babel (and thus not polyfilled by core-js) or alternatively generate `window.Symbol`, etc instead so that only the global implementation is used, if it is available.

**Comment by sebmck** [comment]
Except then you need to have a way to get access to `React`. It's silly to have an opinion on module loader to "get at it" too. You can't use `window.Symbol` either as that'll break on the serverside. I'd be more concerned about this issue if there wasn't a solution, but there is. Just use the global polyfill. You want global state and that's exactly what the polyfill gives you. cc @sebmarkbage

**Comment by STRML** [comment]
Given that the inlineelements optimization works from JSX, and JSX requires React in scope in order to do `React.createElement()` in the first place, it seems reasonable to assume that `React.REACT_ELEMENT_TYPE` or `React.elementFromObject()` would be accessible.

**Comment by syranide** [comment]
> Except then you need to have a way to get access to React.

@sebmck Considering it's normally translating to `React.createElement()` I would assume `React` already has to be in scope, so it shouldn't be a problem?

> You can't use window.Symbol either as that'll break on the serverside.

`global.Symbol` should be fine right?

**Comment by sebmck** [comment]
@syranide 

> Considering it's normally translating to `React.createElement()` I would assume `React` already has to be in scope, so it shouldn't be a problem?

Helpers shouldn't rely on any sort of variables being in scope. They're very isolated and need to be this way as they're split into separate files for the [runtime](http://babeljs.io/docs/usage/runtime) and are all included in a separate file together for [external helpers](babeljs.io/docs/usage/external-helpers).

> `global.Symbol` should be fine right?

`global` doesn't exist in the browser. You also can't rely on `typeof window === "undefined" ? global : window` either since neither of those exist in web workers etc.

@STRML 

> Given that the inlineElements optimization works from JSX, and JSX requires React in scope in order to do `React.createElement()` in the first place, it seems reasonable to assume that `React.REACT_ELEMENT_TYPE` or `React.elementFromObject()` would be accessible, so long as we didn't use a helper to do so (and risk the access being moved inside the runtime, where it would then have to get access to `React` somehow).

Helpers and compiled code are very different in behaviour, see my response to @syranide.

**Comment by STRML** [comment]
Not sure if I understand @sebmck, so long as it's not a helper (but instead handled like the `jsxPragma`), it should work just fine.

**Comment by sebmck** [comment]
No matter where it appears in the file it's still going to be transformed by the runtime transformer and will have the same effect.

**Comment by syranide** [comment]
> Helpers shouldn't rely on any sort of variables being in scope. They're very isolated and need to be this way as they're split into separate files for the runtime and are all included in a separate file together for external helpers.

Right, I meant literally `$$typeof: React.REACT_ELEMENT_TYPE`, which should be safe right?

> global doesn't exist in the browser. You also can't rely on typeof window === "undefined" ? global : window either since neither of those exist in web workers etc.

`global` references `window` in my builds, but perhaps helpers can't hook into that logic?

**Comment by sebmck** [comment]
> Right, I meant literally `$$typeof: React.REACT_ELEMENT_TYPE`, which should be safe right?

Oh right. Yeah that should work really well actually. It'll abstract out the actual typeof logic too. cc @sebmarkbage @spicyj Can we get this into React? Probably way too late now that React 0.14 has shipped...

> `global` references `window` in my builds, but perhaps helpers can't hook into that logic?

That's just a node/browserify/webpack thing. Babel is pretty generic and binding to a specific environment is too opinionated.

**Comment by STRML** [comment]
Thanks @syranide, that's what I meant as well but it appears I wasn't communicating it effectively. Glad to see we're all on the same page now.

**Comment by sebmarkbage** [comment]
The point of structuring it this way in React is so that multiple versions or instances of React can work on a single context.

Ideally, we should not require React to be in scope or anything else. The idea is to make the ReactElement type totally stand-alone so that it easier for other libraries to consume. The only thing blocking us from doing this full scale, is because of string refs.

This seems like a babel / core-js issue to me, since `Symbol.for` is intended to be a way to share symbols across realms and environments. If best practice causes the `Symbol` implement to not be shared, then it is more of a sham than a shim, so maybe it is better to leave it out? Or polyfill it at the global object level so that both can pick it up?

**Comment by STRML** [comment]
I fail to see any benefits we gleam from using `Symbol.for('react.element')` versus the magic num, and a number of downsides, such as an inability for the objects to be JSON stringified, and most notably the polyfill complexity that we're now experiencing.

**Comment by spicyj** [comment]
@STRML It's a security feature. The goal was to make it so you can't interpret a JSON blob as an element accidentally. See https://github.com/facebook/react/issues/3473.

**Comment by sebmck** [comment]
> This seems like a babel / core-js issue to me, since `Symbol.for` is intended to be a way to share symbols across realms and environments.

Yeah it is. One of the possible solutions is to modify React although I can understand the hesitiation.

> If best practice causes the `Symbol` implement to not be shared, then it is more of a sham than a shim, so maybe it is better to leave it out? Or polyfill it at the global object level so that both can pick it up?

Yeah that's what I pointed out earlier. Going to close this as a wontfix. If you want global state then use the polyfill, it's what it's there for.

**Comment by STRML** [comment]
If this is a wontfix, please put a note in the docs, as users are going to break their applications if they use the optimization without the global polyfill.

**Comment by sebmck** [comment]
Feel free to send a PR or open an issue on the docs repo.
