### ISSUE TITLE
es5.properties.mutators and enumeration order

### ISSUE THREAD

**Issue by zloirock** [babel/babel#2560]
In all modern engines, string keys enumerates in the order of addition. `es5.properties.mutators` replaces getters / setters in object literal to `Object.defineProperties` call and it [creates problems](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&playground=true&code=var%20O%20%3D%20%7Ba%3A%201%2C%20get%20b%28%29%7B%7D%2C%20c%3A%203%7D%3B%0A%0Aconsole.log%28Object.keys%28O%29%29%3B) with enumeration order. This transformer enabled by default, but I do not see any benefit of that - we can't add accessors with `Object.defineProperties` polyfill too, only some possible V8 optimisations. So I propose disable it by default.

**Comment by jmm** [comment]
I don't think anyone should be relying on unspecified enumeration order in general. ES2015 does specify enumeration order in certain cases though. I'd suggest that [`Object.getOwnPropertyNames()`](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=var%20O%20%3D%20%7Ba%3A%201%2C%20get%20b()%7B%7D%2C%20c%3A%203%7D%3B%0A%0Aconsole.log(Object.getOwnPropertyNames(O))%3B&playground=true&stage=0) makes for a better example (though I wouldn't actually go by the REPL output from it).

**Comment by zloirock** [comment]
@jmm by ES6, `Object.keys` should use the same internal operation like `Object.getOwnPropertyNames`. `EnumerableOwnNames` -> `[[OwnPropertyKeys]]` -> `in property creation order`. Note about `for-in` enumeration order here - just note. All actual engines has orrect order here. `Object.getOwnPropertyNames` has incorrect order, for example, in Node 0.12-.

**Comment by jmm** [comment]
@zloirock 
> by ES6, `Object.keys` should use the same internal operation like `Object.getOwnPropertyNames`. `EnumerableOwnNames` -> `[[OwnPropertyKeys]]` -> `in property creation order`.

They do both end up depending on `[[OwnPropertyKeys]]`, but according to the spec the `EnumerableOwnNames` path (and therefore `Object.keys()`) essentially throws away the order data from it and does not guarantee order (except for it being the same as for `for-in`). See step 6 of [`EnumerableOwnNames`](http://www.ecma-international.org/ecma-262/6.0/#sec-enumerableownnames):

> 6. Order the elements of *names* so they are in the same relative order as would be produced by the `Iterator` that would be returned if the `[[Enumerate]]` internal method was invoked on `O`.

[`[[Enumerate]]`](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-enumerate) says:

> The mechanics and order of enumerating the properties is not specified...

See also:
https://mail.mozilla.org/pipermail/es-discuss/2015-August/043995.html
https://mail.mozilla.org/pipermail/es-discuss/2015-August/043998.html
http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order/32149345#32149345

> But `Object.getOwnPropertyNames` has incorrect order, for example, in Node 0.12-

So that's just a bug, right?

> (like `Object.assign` in modern V8).

Sorry, what's that?

**Comment by zloirock** [comment]
I added example, with this example enumeration incorrect in modern V8 too %)

**Comment by jmm** [comment]
> I added example, with this example enumeration incorrect in modern V8 too %)

Oh, yeah, I think I've seen that example in a Chrome issue. (I'm not sure what you mean about `Object.assign()` though.)

> All actual engines `Object.keys` has correct order here. But `Object.getOwnPropertyNames` has incorrect order

That's ironic, since the spec doesn't guarantee order for `Object.keys()`, while it does for `Object.getOwnPropertyNames()`.

**Comment by jmm** [comment]
Oh sorry, if the `Object.assign()` example was there after your edit I must have just missed it at first. I see what you mean about that.

**Comment by hzoo** [comment]
not even sure I remember what `es5.properties.mutators` corresponds too, going to close for inactivity.
