### ISSUE TITLE
Class async method, 'this' is null?

### ISSUE THREAD

**Issue by aforty** [babel/babel#2579]
Am I doing something wrong? Why is `this` null?

```
class Class {
  async method () {
    console.log(this); // null
  }
}
```

**Comment by loganfsmyth** [comment]
It's not?

http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&playground=true&code=class%20Class%20%7B%0A%20%20async%20method%20()%20%7B%0A%20%20%20%20console.log(this)%3B%20%2F%2F%20null%0A%20%20%7D%0A%7D%0A%0Avar%20c%20%3D%20new%20Class()%3B%0Ac.method()%3B

I'm closing this, since it's a question. Please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

I'd be happy to help you figure out your issue in Slack if you like. Perhaps you are calling `method` incorrectly?

**Comment by aforty** [comment]
My apologies for the question, I'll get on Slack.
