### ISSUE TITLE
export default not working as intended anymore

### ISSUE THREAD

**Issue by sunjay** [babel/babel#2724]
Let's say we have the following very simple code:

    const a = 3;
    export default a;

Pre babel 6, it would compile into this:

    "use strict";
    
    Object.defineProperty(exports, "__esModule", {
      value: true
    });
    var a = 3;
    exports["default"] = a;
    module.exports = exports["default"];

Note the last line.

Now in Babel 6, the default export isn't assigned properly. This may be related to: https://github.com/babel/babel/issues/2694

    "use strict";
    
    Object.defineProperty(exports, "__esModule", {
      value: true
    });
    var a = 3;
    exports.default = a;

**Comment by loganfsmyth** [comment]
This functionality has been removed as part of Babel 6.x, sorry.

**Comment by davidbonnet** [comment]
I don't see why this behaviour has been removed in `babel-plugin-transform-es2015-modules-commonjs`. Perhaps an alternate version of this plugin should be made available that restores the old behaviour.

The issue is that a module compiled with `browserify` now has to be imported like this:
```js
var module = require('module').default;
```
…instead of:
```js
var module = require('module');
```

**Comment by pascalduez** [comment]
Hi,

I just figured this out as well.
Are we back at adding this `.default` thing everywhere again ?

**Comment by loganfsmyth** [comment]
Because people were incorrectly doing

    export default {foo: 'bar'};

and 

    import {foo} from './mod';

which is totally invalid ES6.

Using `.default`, or writing your module with an entry point that does `module.exports = require('./module').default` is the expected approach.

**Comment by sunjay** [comment]
This breaks a lot of code. My usecase is for classes:

    export default class A {
        ...
    }

That simple piece of code no longer works and modules that rely on default being set to module.exports are completely non-functional. Can there be a plugin or plugin option added to fix this?

**Comment by dgreensp** [comment]
The way I see it, Babel can put anything in `module.exports`, subject to two constraints:

* The correct ES2015 named exports can be retrieved, with no weird crosstalk (such as properties of a default export becoming named exports)
* The quality of the interop experience with CommonJS (i.e. the rest of Node)

There's no such thing as "not doing interop," contrary to what some past discussions have said.  Choosing to set `exports` to a dictionary of ES2015 name exports is still a choice about interop, since the `exports` object is primarily what's seen by CommonJS modules, and secondarily a place for Babel to store data.

For example, another interop choice would be: if the default export is a non-primitive, Babel would hang a property called `__esModuleExports` off of it and put the ES2015 named exports there.

**Comment by sebmck** [comment]
See #2212. This is a bikeshedding topic as the reasons for not using `module.exports` are clear. Please see those related issues.
