### ISSUE TITLE
Preset Options

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2756]
Re: https://github.com/babel/babel/issues/2746#issuecomment-153136727

In 6.0 options have been moved down to plugins. The presets that contain the plugins aren't configurable, so it's not hard to imagine we'll end up with presets that are very similar to one another with just simple options changed.

For example, `babel-preset-es2015` and `babel-preset-es2015-loose`. This could either be two separate presets or be handed as options like this:

```js
export default function({ loose = false } = {}) {
  return {
    plugins: [
      [require("...", { loose }],
      [require("...", { loose }],
      ...
    ]
  };
};
```

**Comment by loganfsmyth** [comment]
This seems reasonable to me, otherwise it definitely seems like it could be a pain to manage the possible permutations of plugins.

**Comment by jmm** [comment]
Since this is being discussed again, I'm going to mention again the idea of presets just being part of the plugin mechanism for the benefit of those that didn't see the original discussion on slack (ignoring for the moment BC issues now that v6 has launched). I feel like it might be simpler to just have one mechanism that serves both of these use cases, and they'd already be converging even more by adding options to presets. A plugin could just be a function that returns an options hash (possibly whitelisted to certain keys, even just `plugins` if that's all it should be) -- or a function or object with `visitor` key as shorthand for the singular plugin case.

A regular (singular) plugin:

```js
export default function (b, opts = {}) {
  return {
    plugins: [[plugin, opts]]
  };
}

function plugin ({types: t}, opts) {
  return {
    visitor: {
    }
  };
}
```

A preset plugin:

```js
export default function (b, opts = {}) {
  return {
    plugins: [
      require("x"),
      require("y"),
      require("z"),
    ]
  };   
};
```

As a convenience for the singular plugin case, it's easy to detect that the return value is a function instead of an object, or an object with a `visitor` key, so you could just have:

```js
export default function () {
  return plugin;
}

function plugin ({types: t}, opts) {
  return {
    visitor: {
    }
  };
}
```

or just:


```js
export default function ({types: t}, opts) {
  return {
    visitor: {
    }
  };
}
```

**Comment by developit** [comment]
Couldn't plugins just be given access to look at top-level configuration values?  So a user could define `{loose:true}` if they so pleased, and any plugins with a loose mode could use that value.

**Comment by RReverser** [comment]
@developit That sounds like the simplest and reasonable way to solve this instead of creating lot of presets / changing presets model.

**Comment by developit** [comment]
@RReverser Yup, I think this would avoid what might be a large amount of "config" plugins that just add configuration to a preset, which would be a bit black box for end-users (not for the plugin authors, but I think that might be a different group of people).

**Comment by loganfsmyth** [comment]
Having plugins read from a central place seems like it could lead to more confusion though, since there would no longer be one single place to look to understand how something is configured, and if it's a global config store, it's be much easier for plugins to do bad things like mutate global configuration.

I agree that it may be easier for very global things like `loose` but if we allow one flag, we end up having to allow everything, and things get hard very quickly. If it's the easiest way to configure a plugin, people will use it, and that will lead to issues where people make global flags that conflict and overlap.

If we want Babel to be a general framework, centralized global config seems like it would be very problematic.

**Comment by developit** [comment]
Doesn't babel throw errors for unknown top-level configuration keys? If that is retained, then white listing generally applicable things like `loose` could be controlled. 

Still, II am wondering if this is one of those cases where the options both have gains and losses. At least with specific configuration there is a _path_ to single flag freedom (presets / meta plugins),so maybe that's a solid reason to keep going forward with only that setup.
