### ISSUE TITLE
export * as x from 'y' is not exporting any symbols

### ISSUE THREAD

**Issue by mdouglass** [babel/babel#2852]
I've put together a small sample project at https://gist.github.com/mdouglass/9515f7439949b5d2cc17

In that project if you look at the transpiled code for main.js, the export * as x from 'y' syntax generates code to import 'y', but does not place the imported object back into main.js' exports.

**Comment by loganfsmyth** [comment]
You almost certainly mean to enable `transform-export-extensions`, not `syntax-export-extensions`. If you change that, it'll fix your issue I'll bet. I do agree that the issue is hidden a little by Babel's behavior here though. Seems like perhaps the commonjs module formatter is being too aggressive in picking up the extension and converting them even when it shouldn't be?

**Comment by mdouglass** [comment]
Doh, thanks for the advice - clearly still getting used to which plugins do what in the new system.  I'll give it a whirl in the morning and come back and update.

**Comment by mdouglass** [comment]
Yep, you were correct sir. Thanks!
