### ISSUE TITLE
6.x arrow functions with bind syntax error

### ISSUE THREAD

**Issue by AndrX** [babel/babel#2878]
After updating to 6.x I got syntax errors: `[SyntaxError: ./file.js: Unexpected token (497:13) while parsing file`.

I see that I have there arrow function with the `bind`:

	let startFn = () => {
            this.map = this.createMap();
            this.marker = this.createMarker();
        }.bind(this);

To fix this I wrapped it in parentheses like this.

	let startFn = (() => {
            this.map = this.createMap();
            this.marker = this.createMarker();
        }).bind(this);
		
Just a question if this is an intentional change?
Thanks

**Comment by hzoo** [comment]
I see unexpected token for esprima, espree, shift parser so it's probably intentional then (pasting into http://astexplorer.net/)? Yeah I think you'll have to wrap it like in other cases.

I'm not sure why you are using `.bind(this)` with an arrow function - you usually use an arrow function to avoid having to use `.bind(this)` in the first place?

**Comment by AndrX** [comment]
No, I understand that. It was just one case in the code. Was curious. Thanks!

**Comment by hzoo** [comment]
Ok cool closing then
