### ISSUE TITLE
make bootstrap error

### ISSUE THREAD

**Issue by amasad** [babel/babel#2909]
```
cd packages/babel-runtime; \
	node scripts/build-dist.js
module.js:338
    throw err;
    ^

Error: Cannot find module 'babel-plugin-transform-runtime/lib/definitions'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/amasad/code/babel/packages/babel-runtime/scripts/build-dist.js:5:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
make: *** [bootstrap] Error 1
```

**Comment by amasad** [comment]
cc @sebmck @thejameskyle

**Comment by hzoo** [comment]
Oh that's the current travis error

**Comment by amasad** [comment]
Can you please look into it. I can't figure this out and it's blocking me

**Comment by hzoo** [comment]
Since this after the other steps in make boostrap: `cd packages/babel-runtime; node scripts/build-dist.js`

@amasad As a temporary thing (if you haven't already done this), can you try going to `packages/babel-runtime`, running `npm install babel-plugin-transform-runtime` manually and then running `node scripts/build-dist.js` in the directory?

**Comment by hzoo** [comment]
Looks like it started after https://github.com/babel/babel/commit/9d43776fbebf862e56d059dff117e55823f662b5

**Comment by sebmck** [comment]
It was because npm 3 was shitting the bed whenever you tried to run `npm install` in a directory with symlinked modules. I'll look into an alternative way to make this work now.

**Comment by sebmck** [comment]
I'll get Travis completely passing too by fixing the remaining old node bugs.

**Comment by sebmck** [comment]
I've now fixed the remaining bugs in old Node versions that were causing failures. I've also reenabled Node 0.10 since it's not that hard to support and it doesn't support any ES6 which is good as some of the exec tests were accidentally working even though their transform hadn't ran due to engine support.

Travis is now green. Pull requests should only be merged once CI passes and I will now revert back to using my `development` branch which is automatically merged into `master` when it passes. This means that `master` should always be passing and if it's not then an issue should be created and it should be considered high priority to get it fixed.
