### ISSUE TITLE
Unnecessary closure around class definition

### ISSUE THREAD

**Issue by mstijak** [babel/babel#2920]
Can someone help me understand why a closure wrapper is required in transpiled (sub)class code?
```
class B extends A { }
```
loosly transformed becomes
```
var B = (function (_A) {
  _inherits(B, _A);

  function B() {
    _classCallCheck(this, B);

    _A.apply(this, arguments);
  }

  return B;
})(A);
```
instead of 
```
function B() {
    _classCallCheck(this, B);

    A.apply(this, arguments);
  }

_inherits(B, A);
```
Unnecessary closures hurt readablily of generated code. It would be great to simplify the result when possible.

**Comment by Skalman** [comment]
If `A` is changed later on, your version does something different than the version with a closure.
Your version

**Comment by sebmck** [comment]
Class ids are lexically scoped to their class body and we need to always have a reference to the original class in order to do the `classCallCheck`. Doing this just adds more problems than it's worth and will dramatically increase the complexity of the transform while just making the generated code more flakey.
