### ISSUE TITLE
babelCore.transform fails without filename in jsx

### ISSUE THREAD

**Issue by gabor** [babel/babel#3013]
(version 6.1.4)

this works:
`require('babel-core').transform('<div></div>;', {filename:'something', presets:['es2015','react']});`

this fails:
`require('babel-core').transform('<div></div>;', {presets:['es2015','react']});`

with this error:

    TypeError: unknown: Cannot read property 'toString' of null
        at node_modules/babel-preset-react/node_modules/babel-plugin-transform-react-jsx-source/lib/index.js:40:47

**Comment by jmm** [comment]
@gabor It's because of this: https://github.com/babel/babel/pull/2963#issuecomment-155814773 and is already fixed on the `development` branch.

For now you can work around it by either:

* Pass `filename` to `transform()`.
* Run in some environment (`BABEL_ENV` or `NODE_ENV`) other than `development`.

**Comment by jmm** [comment]
Actually it's fixed in `master`, but it's not yet in the latest release, `babel-preset-react@6.1.4`.

**Comment by gabor** [comment]
thank you for the quick response. could you estimate how long until the next release?

**Comment by jmm** [comment]
@gabor No, unfortunately there's no way for me to know.

**Comment by gabor** [comment]
i'll just workaround it with setting a dummy filename then i guess :) thank you for your help.
