### ISSUE TITLE
Allow `babel-plugin-transform-es2015-function-name` to name anonymous IIFE functions.

### ISSUE THREAD

**Issue by vjpr** [babel/babel#4526]
Allow `babel-plugin-transform-es2015-function-name` to name anonymous IIFE functions.

### Input Code

```js
let foo = (() => {})()
```

### Babel Configuration (.bablerc, package.json, cli command)

```js
{
  "presets": ["es2015"]
}
```

### Expected Behavior

```
var foo = (function foo() {})();
```

### Current Behavior

```
var foo = function () {}();
```

### Workaround

Currently you must use a named function where you have to name the function and the variable which you will usually want to be the same. It is not very DRY.

```javascript
// a.
var foo = (function foo() {})()

// b.
function getFoo() {}
var foo = getFoo()

// c.
const getFoo = () => {}
var foo = getFoo()
```

### Context

The goal of this feature is to improve stack traces and when using a CPU profile.

When debugging performance issues using a flame chart, IIFE's are great for naming a section of code which can then have its stats aggregated when using Chrome dev tools.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  ^6
| node             |  ^6
| npm              |  ^3
| Operating System | OSX

**Comment by DrewML** [comment]
Current behavior with native ES6 in `Chrome` + `Firefox`:

**Firefox**:
![image](https://cloud.githubusercontent.com/assets/5233399/19413971/018ad7b8-9304-11e6-97d7-301fd1410663.png)

**Chrome**:
![image](https://cloud.githubusercontent.com/assets/5233399/19413972/0d5c2b32-9304-11e6-929d-1a91f48aa51d.png)

**Comment by loganfsmyth** [comment]
You could certainly make a plugin to do this yourself, but `transform-es2015-function-name` is following the ECMAScript spec here, IIFEs do not get an automatic name property in this case.

**Comment by DrewML** [comment]
Adding for future reference (still learning to grok the spec, but I think these are the right spots) based on @loganfsmyth's comment.

- Anonymous function expressions (which can be an arrow or a `function`, I believe, based on `IsAnonymousFunctionDefinition`), when used as the RHS of an assignment, are assigned the `name` property as outlined in [12.14.4](http://www.ecma-international.org/ecma-262/6.0/#sec-assignment-operators-runtime-semantics-evaluation), under 1 >> e >> iii.

- In the case of an arrow function inside of an IIFE, since the arrow function itself is not the RHS value (a `CallExpression` is), only the normal runtime evaluation semantics outlined in [14.2.16](http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions-runtime-semantics-evaluation) are applied, which do not include running `SetFunctionName`.

**Comment by DrewML** [comment]
@vjpr I threw together a quick `Babel` plugin for you that you can use to accomplish this for both ArrowFunctionExpressions and FunctionExpressions. This will work for either, when in an IIFE, as the RHS of a variable declarator.

```javascript
export default function ({types: t}) {
  return {
    visitor: {
      "ArrowFunctionExpression|FunctionExpression"(path) {
		const directParentIsCallExpr = path.parentPath.isCallExpression();
        const callExprParent = path.parentPath.parentPath;
        if (!callExprParent.isVariableDeclarator()) return;

        if (callExprParent.isVariableDeclarator() && directParentIsCallExpr) {
          const identifier = callExprParent.node.id.name;
          path.node.id = t.Identifier(identifier);
        }
      }
    }
  };
}
```

Written to be used in conjunction with the arrow function plugin (part of ES2015 preset).

**Comment by loganfsmyth** [comment]
I threw together a reference here a while back if others are curious: http://stackoverflow.com/a/32830772/785065
