### ISSUE TITLE
[Bug] Block Scoped variables not renamed when concating to file

### ISSUE THREAD

**Issue by subhaze** [babel/babel#4537]
**Babel Version:**  6.11.4 (babel-core 6.11.4)

**Code**

``` js
// one.js
{
    let one = 1;
    let two = 2;
}

{
    let one = 1;
    let two = 2;
}
```

``` js
// two.js
{
    let one = 1;
    let two = 2;
}

{
    let one = 1;
    let two = 2;
}
```

`babel --preset es2015 one.js two.js --out-file out.js --no-babelrc`

**Expected behavior:**

``` js
// out.js
{
  var one = 1;
  var two = 2;
}
{
  var _one = 1;
  var _two = 2;
}
{
  var _one2 = 1;
  var _two2 = 2;
}
{
  var _one3 = 1;
  var _two3 = 2;
}
```

**Actual behavior:** 

``` js
// out.js
{
    var one = 1;
    var two = 2;
}
{
    var one = 1;
    var two = 2;
}
{
    var one = 1;
    var two = 2;
}
{
    var one = 1;
    var two = 2;
}
```

**Comment by loganfsmyth** [comment]
Using the CLI's concat logic is not a good idea, I honestly don't know why we even support it. We're unlikely to fix this, you'd be much better off using a module bundler to give each file a wrapper function.

**Comment by bdkjones** [comment]
That seems a little strange. The Babel CLI says, "Give me multiple files and I'll combine them and create a single output." If that feature is offered, the combined output should be correct, no?

**Comment by loganfsmyth** [comment]
Yeah, I know what you mean and I'm sorry it is frustrating. We don't document the multi-file ability on the site AFAIK: https://babeljs.io/docs/usage/cli/ I'm curious, where is that message you mentioned? You are right the feature is there, but as with many things in the Babel codebase, they are there are haven't been removed, but it's debatable what things are officially supported.

The JS community as a whole doesn't really do concatenation anymore in general, since it's a great way to run into scoping problems, with or without Babel. Unfortunately I wouldn't expect this to be a feature we'd support moving forward.

I'm open to hearing and argument for keeping it, I'm honestly curious about your motivations, since modules are extremely common, concatenating JS honestly scares me.

**Comment by bdkjones** [comment]
Well, in my case the reason I rely on Babel to concatenate files rather than combining them myself and piping the input to the CLI is that when I just throw the files at Babel, source maps tend to "just work". If I combine things myself, then source maps become a black hole of sadness and despair.

I'm not sure what the concatenation logic is, but if you take the example code in this issue and throw it into a single file, Babel produces correct output. I'm assuming that Babel is transpiling each input file on its own and THEN concatenating the output. Would it be a worthwhile to change that so that the input files are concatenated FIRST and THEN transpiled?

**Comment by hzoo** [comment]
Yeah we don't really support/recommend using babel with concatenation, babel transforms per file and assumes modules and a bundler (like https://webpack.js.org) is recommended.
