### ISSUE TITLE
Code hags on async/await Nodejs

### ISSUE THREAD

**Issue by khotey** [babel/babel#4588]
Method:
```
export const signup = async (req, res, next) => {
  const credentials = req.body;

  try {
    let user = await User.create(credentials);
    console.log(user); // show created user, but code hangs there
  } catch ({ message }) {
    return next({
      status: 400,
      message
    });
  }

  return res.json(user);
};
```

Problem in try block, user creates success but code hangs in try block, if error in try block, code go to catch block and all work, what is the problem

**Comment by loganfsmyth** [comment]
You should add a `process.on('unhandledRejection',` event handler to your app. It is almost certainly just throwing an exception there because you try to access `user` at the very bottom, but you have only defined it inside the `try` block. Because you don't have an even handler, the error is swallowed by the async function promise.

**Comment by khotey** [comment]
thank you very match !
```
  let user;

  try {
    user = await User.create(credentials);
  } catch ({ message }) {
    return next({
      status: 400,
      message
    });
  }
```
