### ISSUE TITLE
transform-class-properties not working using stage-2

### ISSUE THREAD

**Issue by FezVrasta** [babel/babel#4628]
In the documentation of the `stage-2` preset, the `transform-class-properties` plugin is listed.
When I try to use class properties though, ESlint throws an error complaining about the class properties.

I'm not sure if this is a bug of ESlint or of Babel... I'd say Babel because ESlint will work fine if I manually enable the plugin.

### Input Code

```js
class Foo extends Component {
  static bar = {
    foobar: 1,
  }
}
```

### Babel Configuration (.bablerc, package.json, cli command)

```js
{
    "presets": ["stage-2", "es2015", "react"]
}
```

### Expected Behavior
The build should work fine and compile everything without throwing errors.

### Current Behavior
ESLint complains about class properties.
```
Module build failed: SyntaxError: Missing class properties transform.
```

### Your Environment
Reproduced on CentOS on a Vagrant/VirtualBox virtual machine.

| software         | version
| ---------------- | -------
| Babel            |  babel-core@6.14.0
| node             | v6.2.1
| npm              | 3.9.3
| Operating System | CentOS

**Comment by danharper** [comment]
With ESLint, you need to use babel-eslint as the parser.

https://github.com/babel/babel-eslint

**Comment by FezVrasta** [comment]
@danharper I'm already using it.

**Comment by goto-bus-stop** [comment]
Which version of `babel-preset-stage-2` are you using? Class properties were moved to stage 2 in 6.13.0, so earlier versions do not include it.

**Comment by FezVrasta** [comment]
```
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.16.0",
```

**Comment by goto-bus-stop** [comment]
Ohh. I see now.

![Failing](http://i.imgur.com/PAm3A9G.png)

What's happening is the `es2015` preset is trying to transform classes, but the `stage-2` preset hasn't yet transformed class properties. To fix, flip the order so that class properties are transformed _before_ classes are:

![Success](http://i.imgur.com/tkZnwlM.png)

See https://babeljs.io/docs/plugins/#pluginpreset-ordering

**Comment by FezVrasta** [comment]
Thanks @goto-bus-stop it works in this way 🙃

**Comment by sergiotapia** [comment]
@goto-bus-stop @FezVrasta This is happening to me using Rails and Webpacker on a fresh app. My .babelrc file looks like this:

```
{
  "presets": ["env", "es2015", "stage-2", "react"]
}
```

Would love some ideas!

```
21:05:02 hot.1  | ERROR in ./app/javascript/packs/components/example/example.jsx
21:05:02 hot.1  | Module build failed: SyntaxError: Missing class properties transform.
21:05:02 hot.1  |
21:05:02 hot.1  |   11 |   }
21:05:02 hot.1  |   12 |
21:05:02 hot.1  | > 13 |   handleDayClick = (day, { selected }) => {
21:05:02 hot.1  |      |   ^
```

**Comment by JDutil** [comment]
I'm also experiencing this migrating to webpacker for rails with the following .babelrc if anyone has any ideas:
```
{
  "presets": ["es2015", "stage-2", "react"],
  "plugins": [
    "transform-object-assign",
    "transform-object-rest-spread",
    "inline-react-svg",
    "transform-class-properties"
  ]
}
```

**Comment by hzoo** [comment]
The original issue was about ESLint not babel, you' need to use https://github.com/babel/babel-eslint for that atm.

> ESLint complains about class properties.

Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

I would ask in slack, hard to know what the issue is because there seem to be different problems.

You don't need "env" + es2015
