### ISSUE TITLE
transform-es2015-parameters: remove unnecessary `+ 0`

### ISSUE THREAD

**Issue by hzoo** [babel/babel#4692]
Ref https://github.com/babel/babel/pull/4674/files#r82056317

Producing code that has `index++ + 0` which is unnecessary.

If the index of the rest `(...a)` is 0 then don't do the `+ 0`

**Comment by gyandeeps** [comment]
Was trying to work on this. But contributing is so difficult when working from a windows machine :cry: . Cant run test. Started fixing one issue at a time but then realized that a lot of modules which help to run test have been made to have path manipulation without using path module. Lets see if i can make some progress on it.

**Comment by hzoo** [comment]
Ah what are your problems on windows? Is it the makefile and all that?

**Comment by gyandeeps** [comment]
* makefile but i can around it by executing the command directly.
* test-runner module path resolution is not cross OS. It is string concat to construct path at some places. I think `path` resolve should be used.

These are the 2 things which i have found so far. Second one is worse because its at lot of places. I am trying to solve that.

**Comment by Daniel15** [comment]
> It is string concat to construct path at some places. 

This should work fine, Windows accepts both `\` and `/` in paths. It's path *parsing* code that normally gets tripped up. In any case, using the `path` module is the best practice for this.

**Comment by hzoo** [comment]
Thanks @existentialism! https://github.com/babel/babel/pull/4738
