### ISSUE TITLE
babel-traverse, var declarations not included in binding references

### ISSUE THREAD

**Issue by kentcdodds** [babel/babel#4694]
### Input Code

``` js
var a = 32
var {c: b} = obj

console.log(a, b)
```
### ASTExplorer.net example

https://astexplorer.net/#/jUTCWsdHdx/3
### Description of Behavior

The `VariableDeclarator` `a` should be included in it's own `path.scope.getBinding(path.node.name).referencePaths`, just like the `VariableDeclarator` `b` which is an `ObjectProperty` in an `ObjectPattern`.
### Possible Solution

I'm not sure what is causing this, but for some reason, [this code](https://github.com/babel/babel/blob/33eb56ab09e5dcabbd135f3f34fc707c5ea3fbb9/packages/babel-traverse/src/scope/binding.js#L84-L91) isn't called for the `VariableDeclarator`'s `Identifier`.
### Context

I'm writing a tool that removes unused variables. For example:

``` js
function sortRankedItems(a, b) {
  var {rank: aRank} = a
  var bRank = b.rank

  var same = aRank === bRank
  return 'blah'
}
```

With my tool, would result in:

``` js
function sortRankedItems(a, b) {
  return 'blah'
}
```

Based on the order the plugins are running, when the visitor comes across `aRank` and `bRank`, it looks like those variables are in use, but when the visitor gets to `same`, it removes the node. Then it searches for the references that were used by `same` and determines whether it is safe to now remove those as well. Because of this bug, `bRank` is not able to be removed because it's not in the referencePaths, so I can't find it from the `same` node. Hopefully that makes sense.

**Comment by danharper** [comment]
It's only `ObjectPattern` including itself in it's own `referencePaths`. [`ArrayPattern` also doesn't](https://astexplorer.net/#/jUTCWsdHdx/4).

It looks like it's intentional: https://github.com/babel/babel/blob/03d772c2ecedc95f87493e293977e69c3db94d56/packages/babel-types/src/validators.js#L156-L159. But `ObjectPattern` doesn't seem to be used in that link as [the parent](https://github.com/babel/babel/blob/03d772c2ecedc95f87493e293977e69c3db94d56/packages/babel-traverse/src/path/lib/virtual-types.js#L18) of the `Identifier` is `ObjectProperty`, not `ObjectPattern`).

So it looks it's actually a bug that `b` has 2 reference paths? Although I don't know much about this part of the code.

**Comment by liuxingbaoyu** [comment]
Fixed in https://github.com/babel/babel/pull/9492
