### ISSUE TITLE
run ES6 code on ES5 browsers, problems with babel-runtime and babel-polyfill

### ISSUE THREAD

**Issue by cvlmtg** [babel/babel#4695]
### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.17
| node             | 6.7
| npm              | 3.10.3
| Operating System | macOs 10.12

### Problem

We have developed two apps with babel and browserify. since we use a lot of ES6 features and we need to support old ES5 browsers (which is the point of using babel...), we added the babel-polyfill. however there's a situation where we need to have both apps on the same page, and this breaks everything because of the problem with the two polyfills being included...

I believe polyfills should not break when a feature they are polyfilling already exists, but anyway... the babel docs suggests to use babel-runtime for such situations, however babel-runtime doesn't cover all the class methods that have been added in ES6 like *.includes()*, *.startsWith()* etc..

so what's the "right" way to develop an ES6 app that can run on old ES5 enviroment? bundling babel-polyfill with the app is handy but won't work when you need two bundles... babel-runtime is useless because some ES6 features are not supported... including babel-polyfill separately isn't really optimal imho...

does anybody know some other polyfill that can be used instead of babel-polyfill? maybe alongside babel-runtime if needed?

**Comment by hzoo** [comment]
babel-polyfill is just an option and it's actually just core-js + regeneratorRuntime. you can do individual polyfills yourself as well. And you shouldn't need to use polyfill + runtime since you'll only need 1 polyfill at the top level app and everything else just assumes the polyfill. Or as a library you can use the runtime.
---

Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
