### ISSUE TITLE
Future of Versioning

### ISSUE THREAD

**Issue by hzoo** [babel/babel#4950]
https://github.com/babel/notes/blob/master/2016-07/july-31.md#future-of-babels-release-process-and-its-ecosystem

- Independent/Fixed mode in Lerna
- What to do about breaking changes?
- How to help plugins/users update (codemods?)
- How to communicate breaking changes
- How to manage experimental syntax in the parser
- How to manage experimental plugins
- How to do canary builds/prereleases

**Comment by xtuc** [comment]
I would like to help with my thought about this. I might not have the full context.
Please correct me if I'm wrong.

#### Independent/Fixed mode in Lerna
- I don't know Lerna much but each plugin should be indepedent from Babel.

#### What to do about breaking changes?
- We need BC to be able to add new features or fix bugs
- Document changes

#### How to help plugins/users update (codemods?)
- Babel should expose its version to plugin implementors
  - Example
    ```js
    if (babel.VERSION > 5) {
      // a
    } else {
      // b
    }
    ```
- Documentation about BC should be explicit
- I like Flowtype, we could provide definition for specific version?
- Node provides nan (Native Abstractions for Node) which abstract the v8 API (had BC quite a lot)
  - I think Babel does need this because we are talking about Babel's org.
- Babel-types could expose multiple versions
  ```js
  import t from "babel-types/v4"
  ```

#### How to communicate breaking changes
- CHANGELOG
- Document how to bump to version X
- We could in test environnement log deprecated behaviors

#### How to manage experimental syntax in the parser
- Flags to Babel, like c++11 does to enable lambda `-std=c++11`

#### How to manage experimental plugins
- Create a seperate repo with experimental plugins
  ```sh
  babel --plugins experimental-scala-syntax
  ```
  - Once the plugin stable, it could be exported and renamed to the main repo (babel/babel)
    - Works also with legacy plugins (babel/babel-archives)

#### How to do canary builds/prereleases
- Built the release with specific flag/version
- Don't publish it to npm

#### Aside notes
- symfony/symfony is a very good example.
  - The promise of backward compatibility
  - Good documentation about BC
  - Internal components doesn't conflicts
  - Bundle are registered and accessed using services which are less impacted with BC
