### ISSUE TITLE
Do expressions transform incorrectly for `if` inside `while` statements 

### ISSUE THREAD

**Issue by b123400** [babel/babel#5022]
### Input Code

```js
let a = do {
  while (1) {
    if (a) {
      a
    } else {
      b
    }
  }
};

```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "es2015",
    "stage-0"
  ]
}
```

### Expected Behaviour
```js
let a = function () {
  var _ret;

  while (1) {
    if (a) {
      _ret = a;
    } else {
      _ret = b;
    }
  }
  return _ret;
}();
```

### Current Behaviour
```js
let a = function () {
  var _ret, _ret2;

  while (1) {
    if (a) {
      _ret = a;
    } else {
      _ret2 = b;
    }
  }
  return _ret;
  return _ret2;
}();
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.19.0
| node             | 6.9.2
| npm              | 3
| Operating System | Mac OS X 10.11

**Comment by doug-wade** [comment]
seems do expressions are in a pretty tough spot -- see also #3872 and https://twitter.com/RReverser/status/811204413683630080

**Comment by xtuc** [comment]
I can reproduce it in the [online REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=stage-0&code=let%20a%20%3D%20do%20%7B%0A%20%20while%20(a)%20%7B%0A%20%20%20%20if%20(a)%20%7B%0A%20%20%20%20%20%20a%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20a%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) with only `stage-0` preset.

The issue is in `babel-plugin-transform-do-expressions`.
