### ISSUE TITLE
[7.0] Consider removing browser.js from babel-core

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#5108]
Given that it is essentially only used in babel-standalone, I wonder if we gain anything by keeping this logic in `babel-core`. All it does is provide the "text/babel" handling for scripts essentially.

@Daniel15 Any thoughts on this?

---

- [ ] check https://github.com/babel/babel/blob/master/CONTRIBUTING.md
- [ ] remove https://github.com/babel/babel/blob/master/packages/babel-core/src/api/browser.js and associated files
- [ ] https://github.com/babel/babel/blob/master/packages/babel-core/test/_browser.js

**Comment by Daniel15** [comment]
>  it is essentially only used in babel-standalone

`babel-standalone` doesn't actually use browser.js at all, it just uses "core" Babel. It's got its own handling for `text/babel` tags: https://github.com/babel/babel-standalone/blob/master/src/transformScriptTags.js. In fact, the whole reason babel-standalone was build was because browser.js is very broken. I'd be totally fine getting rid of it.

**Comment by loganfsmyth** [comment]
Oh nice, even better then, I didn't realize that.

**Comment by Daniel15** [comment]
For historical context: https://github.com/babel/babel/issues/3710

**Comment by Pr0x1m4** [comment]
Seems great for my first PR to babel. I'll give this a shot.

**Comment by hzoo** [comment]
Closed via https://github.com/babel/babel/issues/5124
