### ISSUE TITLE
Error on 'new ArrayBuffer();'

### ISSUE THREAD

**Issue by shaibam** [babel/babel#5140]
We've noticed that when babel-polyfill is loaded it overides the ArrayBuffer constructor.
an error occurs when creating a new ArrayBuffer without arguments

> new ArrayBuffer();
> polyfill.min.js:2 Uncaught RangeError: Wrong length!
>     at $ (polyfill.min.js:2)
>     at new ArrayBuffer (polyfill.min.js:2)
>     at <anonymous>:1:1

### Input Code

```js
 new ArrayBuffer();
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### Current Behavior

polyfill.min.js:2 Uncaught RangeError: Wrong length!
at $ (polyfill.min.js:2)
at new ArrayBuffer (polyfill.min.js:2)
at :1:1

### Your Environment
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=

| software         | version
| ---------------- | -------
| Babel            |  6.2.4
| node             | 
| npm              | 
| Operating System |

**Comment by DrewML** [comment]
Thanks @shaibam! `babel-polyfill` is _mostly_ just the excellent [`core-js`](https://github.com/zloirock/core-js/) project, aliased to make it easier for Babel users to import it. It looks like, at one point in time, this was explicitly put in because the spec required it (although it may have been a spec bug that they later corrected).

[The test case with details is here](https://github.com/zloirock/core-js/commit/0fc9507984fa9d4ee4a6b0c411597998212bff72#diff-5be00e3315019b59fc07ed6fa22f8e0bR12). I'd ask that you please report this [as a new issue on the `core-js` repo](https://github.com/zloirock/core-js/issues/new), so they can determine if this is still spec-compliant, or if it should be updated.

Thanks again!.
