### ISSUE TITLE
babel-plugin-transform-typescript-strip-types

### ISSUE THREAD

**Issue by graingert** [babel/babel#5201]
It would be great to create a typescript version of babel-plugin-transform-flow-strip-types especially as the type annotations are so similar (TypeScript adds interfaces)

**Comment by graingert** [comment]
See here for the issue in TypeScript: https://github.com/Microsoft/TypeScript/issues/11441

**Comment by graingert** [comment]
I think this might have been what https://github.com/babel/babel/issues/3968 was about, but it's not clear if that was asking for something like https://github.com/codemix/babel-plugin-typecheck/issues/163

**Comment by danez** [comment]
Feel free to create it, also doesn't necessarily have to be in the babel repo. :)

**Comment by graingert** [comment]
@danex it's actually quite difficult because that plugin relies on the built in babylon support for flow.

**Comment by mkusher** [comment]
the first thing that should be done is typescript plugin in babylon. There is already issue for that https://github.com/babel/babylon/issues/320

**Comment by danharper** [comment]
As TS has language additions (e.g. enums, constructor param visibility), something as simple as `flow-strip-types` wouldn't work.

**Comment by graingert** [comment]
enums could not just be stripped, but they don't look that hard to convert.
constructor param visibility doesn't effect the resulting JS in TypeScript, so I don't see how that could not be stripped.

**Comment by mkusher** [comment]
> constructor param visibility doesn't effect the resulting JS in TypeScript

it means that this:
```ts
class A {
   constructor(public a: number, protected b: string, private c: boolean) {}
}
```
should be transpiled to es2015 as:
```js
class A {
  constructor(a, b, c) {
    this.a = a;
    this.b = b;
    this.c = c;
  }
}

**Comment by graingert** [comment]
hmm, strip is probably a misnomer then.

**Comment by graingert** [comment]
I mean it in terms of a transpile without checking types.

**Comment by mkusher** [comment]
maybe `babel-plugin-transform-typescript` will be enough?

**Comment by danharper** [comment]
Doesn't TS also add runtime information for types, decorators etc.?

Adding support to the parser & generator (i.e. no transpilation) would be a great first step, e.g. a `babel-plugin-syntax-typescript`.

**Comment by graingert** [comment]
@danharper I'm pretty sure the types are erased https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-type-erasure

**Comment by xtuc** [comment]
Yes, there are no types at runtime, TS remove them at compilation ([example](http://www.typescriptlang.org/play/index.html#src=interface%20SomeInterface%20{%20}%0D%0A%0D%0Avar%20x%3A%20SomeInterface%3B))

**Comment by graingert** [comment]
@danharper you might be thinking of ATScript

**Comment by danharper** [comment]
I'm thinking of `emitDecoratorMetadata`: TS outputs reflection metadata for types etc. when a decorator is used. afaik Angular relies on this:

```ts
var x: string = '3';

class Foo {}

@Blahh
class Bar {
    constructor(private x: Foo, readonly y: string) {}
}
```

```js
var x = '3';
var Foo = (function () {
    function Foo() {
    }
    return Foo;
}());
var Bar = (function () {
    function Bar(x, y) {
        this.x = x;
        this.y = y;
    }
    return Bar;
}());
Bar = __decorate([
    Blahh,
    __metadata("design:paramtypes", [Foo, String])
], Bar);
```

**Comment by danharper** [comment]
> ATScript

Now there's a blast from the past*

_* where "past" is like 2 years ago ha_

**Comment by aluanhaddad** [comment]
@danharper And yet, the Angular team has indeed managed to create a bastardized, incompatible, non-ES-compliant dialect of TypeScript that they are pushing as Ahead of Time Compilation (AOT) to improve performance. 

While it does not have runtime type information, it actually resembles @Script in some ways.

It is interesting to recall that @Script had not Decorators but rather a syntactically identical feature called Annotations. Annotations could only create metadata, they had no runtime behavior. This is vaguely ironic considering the language's other distinguishing feature was reified types. Annotations were proposed to TC39 but rejected in favor of Decorators as the latter can do all of what the former can, but much more.

Well in Angular's Ahead of Time Compilation, which wraps `tsc`, framework decorators do not execute at runtime and their contents are instead transformed into static data stored in JSON format. This breaks the semantics of Decorators (I know there is churn in that proposal but not concerning this), as proposed for ECMAScript and implemented in TypeScript and previously implemented in Babel. 

For example, since they do not execute under this mode, code which wrapped Angular Decorators, e.g. with other decorators, or code that relied on the runtime presence of Angular Decorators, does not work correctly.

**Comment by hzoo** [comment]
PR by @andy-ms is https://github.com/babel/babel/pull/5899, moving to there

**Comment by graingert** [comment]
see also https://github.com/babel/babylon/issues/320

**Comment by probitlabs** [comment]
When I want to use—let's say—`@babel/stage-1#7.0` syntax together with TypeScript typings (like in `const a: X = b |> lib.map(c)`—which is *not* syntactically supported by `tsc#2.7`); is there a way to **keep** the type information—instead of stripping—in order to pass it over to TypeScript's checker is such cases? (An `*.d.ts` typing export option seems profitable to me.)

**Comment by andy-ms** [comment]
@probitlabs It *might* be possible to apply just those experimental plugins, compile to `.ts` files, then pass that into the TypeScript compiler. But it wouldn't be easy, and it's likely that babel will emit non-typecheck-able code. And you wouldn't get editor support while editing your original files.
