### ISSUE TITLE
transform-class-properties: Static arrow functions are bound to `undefined` rather than the class

### ISSUE THREAD

**Issue by natevw** [babel/babel#5222]
When using babel-plugin-transform-class-properties, it turns out that extending the https://babeljs.io/docs/plugins/transform-class-properties/ example to include a "boundStaticFunction" fails:

```
  class Bork {
    static staticProperty = "babeliscool";
    static staticFunction = function() {
      return Bork.staticProperty;
    }
    static boundStaticFunction = () => {
      return this.staticProperty
    }
  }

  //Static function exists on the class.
  console.log(Bork.staticFunction()); // > "babelIsCool"
  
  // BUG: static functions cannot be bound to class!
  let fn = Bork.boundStaticFunction
  console.log(fn())
```

## Expected behavior

Calling `(Bork.boundStaticFunction)()` should behave the same way as `Bork.boundStaticFunction()`.

Babel would emit code either like

```
Bork.boundStaticFunction = function () {
  return this.staticProperty;
}.bind(Bork);
```

or:

```
Bork.boundStaticFunction = function () {
  return Bork.staticProperty;
}
```

## Actual results

Calling `(Bork.boundStaticFunction)()` results in an error:

> Cannot read property 'staticProperty' of undefined

Babel has output this code (literally):

```
Bork.boundStaticFunction = function () {
  return undefined.staticProperty;
};
```

## Related behavior

Binding an *instance* property in a similar fashion does work as desired.

**Comment by loganfsmyth** [comment]
Whoops, misclick sorry. 

We should verify with the spec, but I think this is the expected behavior? Instance-level arrow functions are executed as if they are in the constructor, so they get `this` as the instance, but I don't think there's any special behavior around static properties, so the `this` is lexical based on the  whatever `this` is outside the class, not the class constructor itself.

**Comment by hzoo** [comment]
cc @littledan

**Comment by littledan** [comment]
I agree with the reporter here. Static field declarations have the constructor as the receiver when they execute. See [this part of the spec](https://tc39.github.io/proposal-class-fields/#sec-define-field), which is called from [that part](https://tc39.github.io/proposal-class-fields/#initialize-public-static-fields). The behavior is observable in other ways as well--for example, you should be able to read other public static fields as `this.fieldName`. You should also be able to do super property access within a static field initializer.

**Comment by jridgewell** [comment]
@littledan: Can you desugar the following? I can't find test262, and it's making my brain hurt.

```js
class Sub extends Base {
  direct = super.field;
  arrow = () => super.field;

  static direct = super.field;
  static arrow = () => super.field;
}
```

After your comment, I think it should be something like:

```js
class Sub extends Base {
  constructor() {
    super();
    this.direct = Sub.prototype.__proto__.field;
    this.arrow = () => Sub.prototype.__proto__.field;
  }
}

Sub.direct = Sub.__proto__.field;
Sub.arrow = () => Sub.__proto__.field;

**Comment by loganfsmyth** [comment]
@littledan I can clarify the part that is tripping me up, since I think it will help.

I 100% agree that the _receiver_ is set to the class constructor inside the field, but since this is arrow functions we're talking about, it's not the receiver that affects the `this` value, it's the `[[ThisValue]]` field of the environment record.

Since non-static fields execute in the constructor, the field is absolutely the instance, but for static fields, I don't see how that ends up being the case.

`InitializeStaticFields(F)` never establishes its own type of EnvironmentRecord type, so the `GetThisEnvironment()` done inside the arrow function would access the `this` value from outside the class declaration.

I'm all for the behavior described in this issue, but I don't feel like the current spec backs that up.

Does that make sense?

**Comment by littledan** [comment]
@jridgewell I believe your desugaring there is accurate (modulo if someone overwrote `Sub.prototype` of course). In particular, see [ClassDefinitionFieldEvaluation](https://tc39.github.io/proposal-class-fields/#runtime-semantics-class-field-definition-evaluation), which calls MakeMethod and gets those super calls to work.

@loganfsmyth Thanks for your help debugging the spec. My intention in writing the spec text was that initializers work like methods. I thought somewhere in the Call (from DefineField, from InitializeStaticFields), the right environment record would be set up. But I guess what's missing is a call to FunctionDeclarationInstantiation from EvaluateBody on initializers. Does that seem right to you?

**Comment by loganfsmyth** [comment]
Alright, this is definitely a bug. I was misunderstand the part of the spec that does indeed cover setting up the execution wrapper logic for the field initializers.

**Comment by natevw** [comment]
Thanks folks, for looking into this more deeply! (TBQH I wasn't even 100% sure whether the spec supported me here or not, but of course glad it does after all ;-)

**Comment by dgreensp** [comment]
I'm using React Native (`babel-preset-expo`) and this code:

```
class Foo {
  static BAR = 1;
  static BAZ = Foo.BAR + 1;
}
```

is being output as:

```
var Foo = (_temp3 = _class4 = function Foo() {
  _classCallCheck(this, Foo);
}, _class4.BAR = 1, _class4.BAZ = Foo.BAR + 1, _temp3);
```

...which throws an error that Foo is not defined in Foo.BAR.

It seems to me that `Foo.BAR` and `this.BAR` should both work in a static property initializer of class Foo, based on this paragraph explaining the intent of the semantics (if it is current):

> Define an own property on the constructor which is set to the value of the initializer expression. The initializer is evaluated in a scope where the binding of the class is available--unlike in computed property names, the class can be referred to from inside initializers without leading to a ReferenceError. The this value in the initializer is the constructor.

By the way, in the Babel REPL, I must not have found the right combination of plugins to trigger the bug, because the same code transpiles as:

```
var Foo = function Foo() {
  _classCallCheck(this, Foo);
};

Foo.BAR = 1;
Foo.BAZ = Foo.BAR + 1;
```

...which of course works.

Anyway, is this a bug and considered part of the bug under discussion here?

**Comment by littledan** [comment]
@dgreensp I'm not sure if that's the same root cause as this or a different one, but the behavior you describe doesn't match the current specification. Instead, the class name should be defined before evaluating those initializer expressions. It looks like the current output takes special measures to make sure that the class isn't visible; this might reflect an earlier version of the specification.

Another issue with the output is that it should use `Object.defineProperty` rather than `=` to define static fields (unless you enabled loose mode). The difference is observable if the superclass has a static setter by the same name.
