### ISSUE TITLE
[7.0] Proposal to drop regenerator

### ISSUE THREAD

**Issue by thymikee** [babel/babel#5238]
### Expected Behavior
Removing `regenerator-runtime` entirely.

### Current Behavior
Regenerator is used because of Node 0.10 support. Since Babel7 drops it, maybe it's time to drop that dependency?

### Possible Solution
I'm working on a PR, but I'd like to be sure if that's desired change.

**Comment by hzoo** [comment]
> Removing regenerator-runtime entirely.

Not sure what this means? I don't know why we would remove the package if that's what you mean since Babel is used not just node.

We don't use generators in Babel either so we wouldn't need to remove it from Babel itself since it doesn't use it anyway.

**Comment by thymikee** [comment]
Meh, of course I didn't check well. Thought ES2015 generators were entirely supported in Node 4 and we could get rid of unnecessary transforming them with `regenerator` in Babel, but [that's not true](http://node.green/#generators).

Sorry about that!

**Comment by hzoo** [comment]
All good, but my point is that we can't drop anything just because it's supported in Node since you can use Babel in the browser (more likely) for things like IE etc. If you are using Node 4 you probably are going to use generators anyway even though its not fully supported. https://github.com/babel/babel-preset-env is more conservative though

**Comment by thymikee** [comment]
Thanks for the clarification, appreciated.
