### ISSUE TITLE
Setting sourceMaps option only works for inline SMs

### ISSUE THREAD

**Issue by pronebird** [babel/babel#5261]
This is my .babelrc

```
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": ["transform-decorators-legacy", "transform-runtime"],
  "sourceMaps": true,
  "retainLines": true
}
```

However when running babel source maps are not being generated:

```babel app/ --copy-files --out-dir build```

Adding `--source-maps true` to CLI tool forces SMs to be generated. Is it a bug?

**Comment by chitchu** [comment]
I don't think it's a bug. Based from the [api docs](https://babeljs.io/docs/usage/api/), setting the `sourceMaps` to `true` means that `babel.transform` will return the generated code along with a `map` property.

**Comment by pronebird** [comment]
@chitchu so `--source-maps true` behaves different from corresponding option in `.babelrc`?

**Comment by chitchu** [comment]
Not entirely. Setting `--source-map (true|inline|both)` overwrites the `sourceMaps` config you set in your `.babelrc`. But only through the cli can you have external source maps (Not sure why).

For reference here's are the files responsible for writing sourcemaps:
* `--out-dir` [dir.js](https://github.com/babel/babel/blob/bda0d5cc68146b15f99ab91e69326df802bc726c/packages/babel-cli/src/babel/dir.js#L23-L27)
* `--our-file` [file.js](https://github.com/babel/babel/blob/bda0d5cc68146b15f99ab91e69326df802bc726c/packages/babel-cli/src/babel/file.js#L71-L75)

**Comment by LoveIsGrief** [comment]
This is a bug or at least a required feature, since generating files from grunt by passing `sourceMaps: true` doesn't generate any sourcemap files.

**Comment by pronebird** [comment]
The CLI ignores `sourceMaps` from `.babelrc` and that seems to me like a bug.

**Comment by pronebird** [comment]
Is this still happening?

**Comment by toonvanvr** [comment]
It does for me

**Comment by dineshselvantdm** [comment]
It's still happening.

**Comment by alasarr** [comment]
Same issue here

**Comment by rhpijnacker** [comment]
Also here... took me a few hours to figure out this was a known bug

**Comment by goosewobbler** [comment]
Can confirm this is still an issue.  

sourceMaps: 'inline' => inline sourceMap (correct behaviour)
sourceMaps: 'both' => inline sourceMap, no file sourceMap (incorrect behaviour)
sourceMaps: true => no inline sourceMap, no file sourceMap (incorrect behaviour)

**Comment by rhpijnacker** [comment]
I've been debugging this for a while and came to these conclusions:

* adding the inline sourceMap line for the `'inline'` and `"both"` parameters are handled by `babel-core/src/transformation/file/generate.js`
* adding the map-file sourceMap line is handled by `babel-cli\src\babel\dir.js` and `babel-cli\src\babel\file.js`
* `dir.js` and `file.js` do not have access to the full config as read from `babel.config.js`, which is why they only work when it is passed from the command-line.

I'm willing to create a patch for this, but I do not see a proper solution to this, other than moving the adding of the map-file sourceMap line to `babel-core/src/transformation/file/generate.js` and writing the actual map-file based on whether this line is present. 
Does this make any sense?

**Comment by rhpijnacker** [comment]
I've encountered one additional inconsistency:

Using `'inline'` or '`both`' will _not_ write the sourceMap line when the source-file is in the exclude list, and thus the source-file is not transformed.
However, since the cli package that writes the .map file is not aware of this, it will write the source map anyway.

We rely on the excluded files _not_ to get a sourceMap, which means we cannot currently use `--source-maps true` from the command line.

**Comment by goosewobbler** [comment]
I'm wondering if the map-file creation should be extracted to `babel-core` where it can have access to config and passed overrides for config when invoked by `babel-cli`.  IMO this functionality is not a CLI thing, but it should be accessible by the CLI code.

**Comment by imbillow** [comment]
same issue even now.

**Comment by BenGale** [comment]
Am I correct in understanding this is the expected behaviour? That in the config that option only half works, and that you need to pass it to the cli if you want to use the 'true' option?

This seems like an unusual decision...

**Comment by rhpijnacker** [comment]
Well... not expected by any of the users, but apparently so by the authors ;)

**Comment by aminya** [comment]
This still happens to me. I even set sourceMap to inline by default in babel-preset-atomic:
https://github.com/atom-ide-community/babel-preset-atomic/

**Comment by luckymore** [comment]
so...what's the next

**Comment by william-will-angi** [comment]
+1 Would also like to see this addressed

**Comment by niklasholm** [comment]
Any reasonable persons expectation would be that the .babelrc option and the cli option has the same effect, so this is definitely a bug to me. Wasted a lot of time on this, thanks.
