### ISSUE TITLE
after update, babel ignores typescript files in local src/node_modules,.

### ISSUE THREAD

**Issue by jacobbogers** [babel/babel#5277]
Typescript files in local node_modules is not compiled anymore after an npm update, why is that?

I submitted this issue first with typescript (see link below) but they have proven it is not a tsc problem it is a babel problem
https://github.com/Microsoft/TypeScript/issues/13929

The project to reproduce the issue is  (npm install and 'gulp ts')
https://github.com/jacobbogers/donorfind

### Input Code

```js
var your => (code) => here;
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  
| node             | 
| npm              | 
| Operating System |

**Comment by loganfsmyth** [comment]
This seems unlikely to be a Babel bug. You don't even have `babelify` loaded in your Browserify config.

My guess would be it is because of your weird setup with `src/node_modules`, why are you putting files inside a `node_modules` directory? `tsify` is probably skipping that file entirely because it is inside a folder named `node_modules`.

**Comment by loganfsmyth** [comment]
You can verify by changing

    .plugin(tsify)

to

    .plugin(tsify, {global: true})

since that will tell Browserify to process files inside node_modules folders.
