### ISSUE TITLE
babel-cli doesn't use .babelrc when the source code are given from stdin

### ISSUE THREAD

**Issue by kt3k** [babel/babel#5297]
### Input Code
```js
const a = () => 1;
```

### Babel Configuration (.babelrc, package.json, cli command)
```json
{"presets":"es2015"}
```

### Expected Behavior
```js
"use strict";

var a = function a() {
  return 1;
};
```
### Current Behavior
When passing filename as a cli arg, it uses .babelrc and it's transpiled as expected, but when passing the source code as stdin to babel-cli, then it doesn't use the settings of .babelrc.

What I did is like the following:
```
$ mkdir test-dir ; cd test-dir
$ yarn add babel-cli babel-preset-es2015 --dev
$ echo '{"presets":"es2015"}' > .babelrc
$ echo 'const a = () => 1' > test.js
$ ./node_modules/.bin/babel test.js
"use strict";

var a = function a() {
  return 1;
};

$ ./node_modules/.bin/babel < test.js
const a = () => 1;
```

### Context
Making temporary files works as a workaround, but it's incovenient when one wants to use babel-cli in combination with other cli tools.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.22.2
| node             | 6.4.0
| npm              | 3.10.3
| Operating System | macOS Sierra

**Comment by xtuc** [comment]
Yes, i can reproduce it.

workaround you can use temporary:
```sh
babel --presets es2015 < test.js
```

**Comment by loganfsmyth** [comment]
See previous discussion in https://github.com/babel/babel/issues/3808.

To me this seems like expected behavior because the `.babelrc` is resolved relative to the file being compiled, so if there is no file, it has no way of knowing where to look. Take for example

    .babelrc
    src/.babelrc
    src/index.js

If a user runs

    babel src/index.js > lib/out.js

we use the `.babelrc` inside `src`. If they run

    babel < src/index.js > lib/out.js

it has no way of knowing to look in `src`.

We could make it look in the current working directory, but that might not be the right config, like in this case where it'd use the one in the repo root instead.

**Comment by kt3k** [comment]
Thanks for the clarification and the reference.

Personally I prefer babel-cli to look up the config from cwd in that situation, but I understand this is intended behaviour.

**Comment by kt3k** [comment]
By the way, I got a better result by passing `--filename` option to cli, which triggers looking up of .babelrc based on the given virtual filename and which worked well with my use case.
