### ISSUE TITLE
babel-runtime changes global behavior on Magento websites

### ISSUE THREAD

**Issue by brunops** [babel/babel#5518]
Hello, I've been trying to debug babel core for two days now, but I'm not being able to identify the exact problem in the code. Here's a repo that reproduces it https://github.com/brunops/bug-babel-runtime

The issue:
Whenever code cointaining something that gets polyfilled, like `typeof obj === 'object'` or `new Promise` is transpiled with `babel-plugin-transform-runtime` enabled, if the resulting bundle is run on a page that has `prototype.js` (version <= 1.7.2), it leaks global behavior.

More detailed information can be found in the repo linked above.

### Expected Behavior
No leaked global behavior, no matter what library is currently loaded on the page.

Example:
`Object.prototype.toString.call([])` => `[object Array]`

### Current Behavior
After the files are loaded, `Object.prototype.toString.call([])` returns `[object Array Iterator]` instead of just `[object Array]`

### Possible Solution
I have no idea what the implications are, but I've found that changing this line in `core-js`

`var TAG        = NAME + ' Iterator'`
to
`var TAG        = NAME// + ' Iterator'`

Makes the problem go away. Definitely not a solution, but hopefully might be helpful for someone with more context.

### Context
It may sound very specific, but I'm under the impression that this problem might happen on all Magento websites, as it uses `prototype.js` 1.7.0. 

It gets even more specific, as the leaked issue propagates problems on how google tag manager works.

I'm also under the impression that the example above is not the only behavior leaked.

### Environment

https://github.com/brunops/bug-babel-runtime

| software                          | version
| --------------------------------- | -------
| babel-cli                         | 6.23.0
| babel-core                        | 6.23.0
| babel-loader                      | 6.4.0
| babel-preset-es2015               | 6.22.0
| babel-preset-stage-0              | 6.22.0
| babel-runtime                     | 6.23.0
| babel-plugin-transform-runtime    | 6.23.0
| node                              | 4.5.0
| npm                               | 3.10.9
| Operating System                  | OSX 10.11.6

**Comment by loganfsmyth** [comment]
The polyfill we use in `babel-runtime` is `core-js`. This has been reported also in https://github.com/zloirock/core-js/issues/278. There must be a bug in that prototype.js version. 

I don't know if that's something that they'd want to pursue fixing given that it's a bug in an unrelated library. Would you be able to upgrade `prototype.js`?

**Comment by hzoo** [comment]
This sounds unrelated to babel itself?

**Comment by brunops** [comment]
Might be unrelated then, sounds like the problem is in `core-js`, feel free to close this.

Will try to follow up on the linked issue.

thanks!

**Comment by brunops** [comment]
Hey, sorry to revive this, but this problem got me thinking about a couple more questions..

First, the problem does seem to be in `core-js`, and I agree that this might be a very specific scenario.

But then again, doesn't this problem show a use case where `babel-runtime` creates the very error that it claims to solve (sandboxed environment)? Are there more things that can possibly be leaking because it relies on `core-js`? Any ideas of what can be done to make sure the sandbox is solid no matter what script was previously loaded? 

would love to hear your thoughts, thanks

**Comment by loganfsmyth** [comment]
> But then again, doesn't this problem show a use case where babel-runtime creates the very error that it claims to solve (sandboxed environment)?

It's definitely a bug in something, I don't disagree there. I don't think there is anything we could do from inside `babel-runtime` to change that though.

> Any ideas of what can be done to make sure the sandbox is solid no matter what script was previously loaded?

JavaScript doesn't really make that possible. At the end of the day anything can touch a global somehow.

Given that this is fixed in Prototype 1.7.3, I'm tempted to say that Prototype did something to mutate the global environment that was bad. At the end of the day I'm sure there are any number of things that people could do to the global environment that would break core-js unfortunately. JS doesn't make preventing that an option really. So the question ends up being, is `core-js`'s job to homogenize the API exposed by various target engines, or is it responsible for normalizing all possible things, and it seems unrealistic to expect that it would cover all possibilities.

The answer here would be to figure out just what prototype was doing, and then either core-js can work around it or it can't.

**Comment by curtiscook** [comment]
I ran into this same issue while debugging yesterday and today.
 
The issue only seems to occur in Magento if you have an extension that includes babel. If you don't introduce an outside version of babel, the objects align, which suggests to me that the new implementation is still leaky. 

As stated above, prototype.js pre 1.7 chokes on the update object shape from post 1.7. I'm concerned that opening a pr against Magento to update the prototype version will just kick this down the road

Our temporary solution was to remove babel until this issue is resolved

**Comment by astericky** [comment]
I too am working on a library integration with Magento 1 and this seems like this could be the reason for the conflicts I am seeing on the invoke function.

**Comment by bvarga** [comment]
Hello,

I think babel-runtime should not state that:

> Externalise references to helpers and builtins, automatically polyfilling your code without polluting globals. (This plugin is recommended in a library/tool)


since it can happen in certain scenarios like this.  I thought it's confidently easy to state something like this if you simply don't change global things, but seems like not this is the case.

Best regards

**Comment by Kovensky** [comment]
My guess is that this is caused by *prototype* running before core-js is initialized and adding an `entries` method to the `Array.prototype` that does not behave like the ES2015 `entries` method.

Calling `[].entries()` should return an object whose `@@toStringTag` should be "Array Iterator", as can be seen by running `[].entries()[Symbol.toStringTag]` in any modern browser. core-js is trying to correct for engines whose array iterator prototype does not have the correct tag, but in this case, `Array.prototype.entries` appears to be returning an actual array instead of an iterator.

**Comment by zloirock** [comment]
@Kovensky seems so.

**Comment by bvarga** [comment]
@Kovensky 

> Also, as much as some people seem to like this dream of polyfilling without "pollution", it's just not possible, in particular for things related to symbols. Applications should just require babel-polyfill / core-js / whatever ES2015 environment polyfill you prefer as the first code that ever runs, and libraries that need it should just require that applications provide it.

It would be nice to know what's possible without pollution, and what's without. If you are building a library, it's important to not break other things on the page, If the page is already ruined by some other lib it's an another thing. If I know that I can't use iterators, or symbols because it's not possible without "pollution", I simply won't use it. We should have control on this. In this case it's happening when you are trying to use Promises, not even Symbols or iterators.

Anyway, there's a LIBRARY flag which seems like indicating should we polyfill or not, and we could use that to make this tag correction. 

thanks for digging into this problem. 

regards
Balazs

**Comment by danielpgross** [comment]
This issue is breaking RequireJS as well, see my report here for more details: https://github.com/zloirock/core-js/issues/289#issuecomment-295860850
