### ISSUE TITLE
Need --delete-dir-on-start or --delete-file-when-src-file-deleted  option for babel --watch flag

### ISSUE THREAD

**Issue by landyu** [babel/babel#5636]
### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "flow",
    ["env", {
      "targets": {
        "node": true
      }
    }]
  ],
  "retainLines": true
}
```

### Watch Script

```js
"watchToBuild": "babel app_flow --watch --out-dir app"
```

### Expected Behavior
when i delete some files or directories in app_flow directory, i hope these related files or directories would be deleted at same time. But actually these related files and directories still remain in the output directory app!

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1
| node             | 5.12.0
| npm              | 3.8.6
| Operating System | MacOS

**Comment by landyu** [comment]
thanks a lot!

**Comment by landyu** [comment]
if babel add `--delete-dir-on-start` or `--delete-file-when-src-file-deleted`  option for babel `--watch` flag, will make the workflow better.

purpose: to make the source directory has the same files and directories as the output directory.
`--delete-dir-on-start` : when we restart the babel script, babel delete the output directory first.
`--delete-file-when-src-file-deleted`: start babel build script with `--watch` flag, babel could delete the output files or directories which were deleted from the source directories.

**Comment by loganfsmyth** [comment]
I think my preference would be a `--delete-dir-on-start` that is allowed when `--out-dir` is used, and would ensure that the directory is empty when compilation starts.

Open to suggestions for alternate names for that option since I'm not totally in love with the verbosity of that one.

`--delete-file-when-src-file-deleted` seems like it doesn't need an option. If we end up implementing it, having it be the default behavior seems fine to me.

**Comment by keshcode** [comment]
i would like to work on this issue

**Comment by xtuc** [comment]
@keshcode good news :+1:. You can join our Slack if you need some help.
