### ISSUE TITLE
Babel mangles class names, breaking IDE code-complete

### ISSUE THREAD

**Issue by cowwoc** [babel/babel#5660]
Babel version 6.23.1
Webstorm IDE version 2017.1.1

1. When Babel processes ES6 modules, it mangles the class names.
2. If the mangled classes are referenced by JSDoc, then the IDE is unable to locate the referenced classes and as a result code-complete does not work.

Testcase: https://github.com/cowwoc/babel-mangles-class-names

1. Build the project by running `gulp default`
2. Load Good.js, notice that code-complete works.
3. Load Bad.js, notice that code-complete fails (IDE does not suggest `childMethod()`).

If you dig into `build/es5/Main.js` you will notice that the JSDoc references `Parent` but Babel mangled the class to `_Parent` so the IDE can't find it.

Is this related to https://github.com/babel/babel/issues/2597 and as such is unfixable? Or is there a workaround?

If there is no workaround, are you saying that library authors should publish babel output to their users? Meaning, if users want to use a library that uses ES6 code, then they must use a newer version of node that support ES6 directly?

**Comment by loganfsmyth** [comment]
I'm not sure there's much we can do here. Generally if you want effective autocomplete you'd want to use Typescript or Flowtype so that your dependency modules have clearly defined APIs. The transforms Babel needs to do to make code spec-compliant can end up creating code that isn't statically analysable. This isn't so much an issue with classes as it is with ES6 module syntax transformation. To make it work we have to rewrite some variable names.

> If there is no workaround, are you saying that library authors should publish babel output to their users? Meaning, if users want to use a library that uses ES6 code, then they must use a newer version of node that support ES6 directly?

I think Flow or Typescript would be worth exploring. I honestly don't have a sense for how much of the JS community uses IDE-based workflows without using those. It wouldn't surprise me if it's a comparatively small percentage.

**Comment by cowwoc** [comment]
If I understand correctly, both Flow and Typescript separate programming languages that compile into Javascript. While I appreciate that these languages allow for clearer API definition, are you saying that it is normal for users of pure Javascript libraries not getting IDE code-complete? When people code against node libraries, written in pure Javascript, are they coding blind?

Alternatively, are you saying that if I want to stick to pure Javascript, I should avoid the use of babel and require my library users to use a newer version of node which support ES6 out-of-the-box?

**Comment by cowwoc** [comment]
Filed https://youtrack.jetbrains.com/issue/WEB-26724. I am hoping that we can use sourcemaps to work around this problem.

**Comment by cowwoc** [comment]
Solved by https://youtrack.jetbrains.com/issue/WEB-26724. Closing this issue.
