### ISSUE TITLE
[enhancement] exclude options for presets

### ISSUE THREAD

**Issue by Andarist** [babel/babel#5662]
Would be super cool if presets like 2015 would get `exclude` option like https://github.com/babel/babel-preset-env already has. 

Is this something interesting to u? Would u accept PR with such enhancement?

Also - wouldnt it make sense for `babel-plugin-transform-runtime` to accept passtrough options to other transforms instead of only booleans?

**Comment by hzoo** [comment]
Hey @Andarist! Thanks for the suggestion. I don't think we want to add an exclude/include and all that for presets since then I would ask why not just use preset-env anyway? It already does what es2015 and more. I can't really think of a reason not to since it takes the same options in. We were planning on deprecating es2015 or at least moving everyone towards preset-env anyway so that's my reasoning.

**Comment by Andarist** [comment]
Ok, I'll look into `preset-env` more. Thanks for the suggestion
