### ISSUE TITLE
It takes 380ms to print the version string

### ISSUE THREAD

**Issue by kevinburke** [babel/babel#5702]
I'm running Babel 6.24.1 on a Retina MacBook Pro, with a 2.9 GHz Intel Core i5 processor and 16 GB of RAM.

It takes 380ms to print the version string:

```
$ time ./node_modules/.bin/babel --version
6.24.1 (babel-core 6.24.1)
./node_modules/.bin/babel --version  0.34s user 0.05s system 102% cpu 0.381 total
```

"Print the version string" is probably the simplest thing you can ask Babel to do and serves as a good proxy for start up cost. This seems a little excessive. Roughly, this is the same amount of time it takes to bounce a packet [from us-east-1 to Turkmenistan and back](https://datapath.io/resources/blog/aws-network-latency-map/).

Node takes about 13ms.

```
$ time node --version
v7.9.0
node --version  0.00s user 0.00s system 45% cpu 0.013 total
```

I'm wondering what steps could be taken to optimize the start up time as Babel is usually not a long-running application.

**Comment by loganfsmyth** [comment]
I'm all for speeding this up, if someone wants to look into it I certainly won't complain. That said, for

> I'm wondering what steps could be taken to optimize the start up time as Babel is usually not a long-running application.

I think does vary by usecase. The majority of users of the `babel` CLI command are using it to compile whole directories, rather than running the CLI command one at a time on a bunch of files, so in the context of processing a whole directory, the startup time isn't as critical usually.

Similarly, people generally use `-w` for local dev, so there is no startup time to worry about for incremental builds.

**Comment by joeattardi** [comment]
I did a bit of looking into this, and it seems like this slowness is being caused by some combination of the imports at the top of the file in `babel-cli/index.js`.

The ones that seem to contribute most to it are:

    import { version } from "babel-core";
    import dirCommand from "./dir";
    import fileCommand from "./file";

The slowness only seems to go away when all three of these are commented out.

It needs to show the babel-core version in the `--version` flag output, so I don't see how the `import { version } from "babel-core"` can be removed. And I don't know enough about how `babel-cli` is designed or how `commander` works to see how the other two could maybe only be required/imported if a command other than `--version` was given. But you'd still need the `import { version } from "babel-core";`.

**Comment by hzoo** [comment]
If someone wants to investigate this, please do! Can use `node --inspect-brk ./node_modules/.bin/babel src lib` to measure and do some profiling.

**Comment by hzoo** [comment]
Not sure what actionable thing to take here, the start perf could be improved.
