### ISSUE TITLE
TypeError instead of JSX SyntaxError, when adding HTML parentheses

### ISSUE THREAD

**Issue by Domiii** [babel/babel#5822]
I replicated the error in [this codepen](https://codepen.io/Domiii/pen/YQzdEM?editors=0010). Feel free to test it yourself there.

The following syntax is invalid, but it generates a wrong (and confusing) error message:

```js
class TestComponent extends PureComponent {
  BroccoliOnTheSandwich() {
    return (
      <span>foo</span> (<span>bar</span>)
    ); 
  }

  render() {
    return (
      <div>
        { this.BroccoliOnTheSandwich() }
      </div>
    );
  }
}
```

This generates the following error:

> TypeError: React.createElement(...) is not a function

Once you remove the parentheses in the `span`s (i.e.: `<span>foo</span> <span>bar</span>`), you get the correct error:

> SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag

(NOTE: Codepen seems to insist that there is some problem with regular expressions, but I get the correct error in my local environment.)

It seems to interpret the parentheses as `JSX` syntax elements, even though they are (supposed to be) pure `HTML text`. Maybe I have just hit an ambiguous construct here?

Note that the correct version of the code would be more akin to this (which works as expected):

```js
class Test extends PureComponent {
  BroccoliOnTheSandwich() {
    return (
      <span> <span>foo</span> (<span>bar</span>) </span>
    ); 
  }

  render() {
    return (
      <div>
        { this.BroccoliOnTheSandwich() }
      </div>
    );
  }
}
```

**Comment by goto-bus-stop** [comment]
```js
<span></span> (<span></span>)
```
is interpreted as a function call. See the output:

```js
➜  cat index.js 
var a = <span></span>(<div></div>);

➜  babel --presets react index.js 
var a = React.createElement("span", null)(React.createElement("div", null));
```

This is because JSX elements are defined to be a [PrimaryExpression](https://facebook.github.io/jsx/#syntax), and PrimaryExpressions can be called in a CallExpression ([CallExpression](https://tc39.github.io/ecma262/#prod-CoverCallExpressionAndAsyncArrowHead) » [MemberExpression](https://tc39.github.io/ecma262/#prod-MemberExpression) » [PrimaryExpression](https://tc39.github.io/ecma262/#prod-PrimaryExpression)). So this behaviour is correct, but definitely a bit confusing!

**Comment by Domiii** [comment]
Wow @goto-bus-stop, thanks for the very swift reply!

I am a bit rusty on my formal grammars. So, a JSX element can be a "callable"?

Does that mean that the above might actually work, if `render` returned a function?

I tried, and yet, no dice: `<A/> (<span>bar</span>)`, where:

```js
class A extends React.PureComponent {
  render() {
    return () => { console.log('hi'); };
  }
}
```

Is it the spec that needs fixing here, or is there actually a use-case for this particular interpretation?

**Comment by goto-bus-stop** [comment]
> I am a bit rusty on my formal grammars. So, a JSX element can be a "callable"?

It can be callable in syntax, but in the React case you can't actually call them because they are not functions (hence why you get a TypeError at runtime and not a syntax error at compile time).

Your example doesn't work because `React.createElement` returns an object that represents the component, not the result of the `render()` method. `React.createElement(A)` returns an object that looks like `{ type: A, props: {} }` regardless of what the `render()` method does. React later calls `render()` internally when it deems it necessary.

**Comment by Domiii** [comment]
From what I understand, the error actually happens after translating JSX to JS, and the JSX specs missed to (forcibly) interpret the parentheses as HTML element.

Maybe the grammar could be changed to account for this particular odd case like so:

* JSXChild
  * JSXText
  * `{` AssignmentExpression_opt `}`
  * JSXElement
  * JSXElementWithParentheses

* JSXElementWithParentheses
  * JSXElement OpenParenthesisHTML JSXElement_opt ClosingParenthesisHTML -> `produce four elements, where the parentheses are interpreted as HTML text`

* OpenParenthesisHTML
  * `(` -> `produce the corresponding HTMLElement
 
* ClosingParenthesisHTML
  * `)` -> `produce the corresponding HTMLElement

However:

1. I'm not sure if that would introduce ambiguity with actual function calls.
1. Also, just to make sure we stay on topic: Where would one go to debate the JSX specs though? Is this the right place?


One other solution would be to show the JSX version of the element in the error message somewhere, prior to transformation:

So in case of:

```js
<span>foo</span> (<span>bar</span>)
```

we could see an explanation of the odd JSX context:

> TypeError: React.createElement(...) is not a function (trying to interpret "<span>foo</span>" as a function because it is followed by a pair of parentheses)

**Comment by nicolo-ribaudo** [comment]
Babel is following the JSX spec here. Any code in the form `AnyExpression ( AnyExpression )` has this "problem"; it's not JSX-specific.

**Comment by Domiii** [comment]
I guess I could raise this issue with the JSX specs community instead then.

Thanks for taking the time nevertheless! :)
