### ISSUE TITLE
List the aliases separately as available types?

### ISSUE THREAD

**Issue by sarupbanskota** [babel/babel#5846]
### Problem
Maybe it's just me, but I struggled trying to work with the Babel Types docs. I was trying to make an [`objectProperty`](https://github.com/babel/babel/tree/master/packages/babel-types#objectproperty), which expected at least a `key` (`Identifier`) and `value` (`Expression`). While I could locate how to create an [`Identifier`](https://github.com/babel/babel/tree/master/packages/babel-types#identifier), I couldn't wrap my head around how to create an `Expression`. I could locate that there's a thing as [`ExpressionStatement`](https://github.com/babel/babel/tree/master/packages/babel-types#expressionstatement), which in turn needed an `expression` (`Expression`).

For my purposes I just made another `Identifier` instead of `Expression` seeing that `Expression` was listed as an alias under `Identifier`, and it works, but maybe it could have been more clear?

### Possible Solution

List the aliases separately as available types?

------

PS - I'm new around here so if this didn't make any sense, feel free to ignore 😜

**Comment by hzoo** [comment]
We didn't even have docs really so the types ones are generated automatically https://github.com/babel/babel/blob/7.0/scripts/generate-babel-types-docs.js - yeah there's a difference between the aliases and actual node types since you can't make an alias node (even though you can check against one). Not sure the solution, we can modify the script if it makes it easier though.

**Comment by sarupbanskota** [comment]
ok lemme do some research on this, and I'll come back with more suggestions

**Comment by hzoo** [comment]
closed the pr, may need to just rethink our types docs?
