### ISSUE TITLE
Can't use babel.transform in file that will be bundled by webpack

### ISSUE THREAD

**Issue by GavinQ1** [babel/babel#5874]
`var babel = require("babel-core");` 
Requiring it is fine but still got warnings which i guess is why i can't use transform.
Warnings:
```
./~/babel-core/lib/transformation/file/options/option-manager.js
Critical dependencies:
178:19-37 the request of a dependency is an expression
296:16-34 the request of a dependency is an expression
 @ ./~/babel-core/lib/transformation/file/options/option-manager.js 178:19-37 296:16-34
./~/babel-core/lib/transformation/file/index.js
Critical dependencies:
500:24-39 the request of a dependency is an expression
699:16-34 the request of a dependency is an expression
 @ ./~/babel-core/lib/transformation/file/index.js 500:24-39 699:16-34
```

Originally, there is module not found errors, but i think i may solve it by adding 
```
node: {
    fs: "empty",
    module: "empty",
    net: "empty"
  }
``` 
to my webpack.config. I don't know if that is the right thing to do.

**Comment by hzoo** [comment]
If you are trying to use babel.transform in your webpack bundle it sounds like you are trying to transpile on the fly? I would just use babel-standalone for that (or copy it)

It does look like that's what is done there https://github.com/babel/babel-standalone/blob/cc20089f4a50df7b2fc0fd7aaa2397352ab4a07e/gulpfile.js#L32 (maybe babel v7 alpha will help because I believe we moved out those calls in the browser version or something)
