### ISSUE TITLE
babel-traverse: wrong Expression validation

### ISSUE THREAD

**Issue by droooney** [babel/babel#5972]
babylon version: **6.17.4** (the same for v7).
babel-traverse version: **6.25.0** (the same for v7).

```js
const { parse } = require('babylon');
const { default: traverse } = require('babel-traverse');

const ast = parse(`const { foo } = 123;`);

traverse(ast, {
  Identifier(path) {
    if (path.isExpression()) {
      console.log(path.node);
    }
  }
});
```

outputs `foo` identifier, though it's pretty clear that it's a part of the variable declaration and is not an expression.

I think the problem is that when `ObjectProperty` is a part of `ObjectPattern` (which is a part of `VariableDeclarator`) its value is not an `Expresssion`.

**Comment by maurobringolf** [comment]
If you check the [AST specification](https://github.com/babel/babylon/blob/master/ast/spec.md#identifier) and [babel-types documentation](https://babeljs.io/docs/core-packages/babel-types/#apiidentifier) you can see that `Identifier` is a subtype of `Expression `. Wherever an `Expression` fits, an `Identifier` will do but not the other way around (like in this example). Therefore checking whether an `Identifier` is an `Expression` will always return true, because it simply is an expression. The variable declaration is a separate node which has the identifier as a child node.

**Comment by jridgewell** [comment]
Yah, this one isn't going to change anytime soon.

**Comment by droooney** [comment]
Even in the specs (https://github.com/babel/babylon/blob/master/ast/spec.md#identifier) it is said that an identifier may be an expression OR an object pattern (which is the case here. though these two do not even cover all the usages of identifier).

In my case I need to check if an identifier really is an expression. And in case of identifier there are plenty usages of it that I need to filter out (object destructuring, object keys, function declaration names, and the list goes on). And it would be sweet if `babylon` gave me this information "for free", since it already knows if an identifier is a real expression or not :)
