### ISSUE TITLE
Support async generators as an experimental feature

### ISSUE THREAD

**Issue by benjamingr** [babel/babel#602]
This proposal basically: https://github.com/jhusain/asyncgenerator

It introduces useful syntax and it would be immensely useful to have it work so we can provide feedback for the specification process.

If you find time to implement it I would be grateful :D

**Comment by jaydson** [comment]
Hey, this is already implemented.
https://6to5.org/docs/usage/experimental/

**Comment by Dashed** [comment]
@jaydson It's entirely different.

This isn't supported by 6to5:

```js
// data producer
async function* nums() {
  yield 1;
  yield 2;
  yield 3;
}

// data consumer
async function printData() {
  for(var x on nums()) {
    console.log(x);
  }
}
```

**Comment by topaxi** [comment]
@Dashed but it works almost the same way:
https://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&code=%2F%2F%20data%20producer%0Aasync%20function*%20nums%28%29%20{%0A%20%20await%201%3B%0A%20%20await%202%3B%0A%20%20await%203%3B%0A}%0A%0A%2F%2F%20data%20consumer%0Aasync%20function%20printData%28%29%20{%0A%20%20for%28var%20x%20of%20nums%28%29%29%20{%0A%20%20%20%20console.log%28x%29%3B%0A%20%20}%0A}

**Comment by fkling** [comment]
@topaxi:See the discussion here: https://github.com/facebook/regenerator/issues/163

The *syntax* is supported, but the *functionality* is not.

**Comment by jaydson** [comment]
Oh, that's true @Dashed 
Thanks for the link @fkling

**Comment by Dashed** [comment]
@topaxi Glancing at the spec proposal, the `for...of` loop with generators is supposedly synchronous. The proposed `for...on` loop with generators is, I think, the async version.

**Comment by benjamingr** [comment]
I was writing a long response but @fkling came with a better link as usual :D

**Comment by topaxi** [comment]
@Dashed yeah got that one, thanks. @fkling's link cleared that one up :)

**Comment by sebmck** [comment]
Probably shouldn't parse at all until 6to5 can support it. It originally wasn't able to parse until I was incorrectly told that regenerator supported async generators.

**Comment by fkling** [comment]
@sebmck: That was me :-/ With "support" I mean that regenerator is able to parse the syntax.... But looking at https://github.com/lukehoban/ecmascript-asyncawait, the proposal doesn't actually mention generators (I guess it was not clear back then what it means to have an async generator).

However, it will come. If you decide to disable support for it, I'd ask you to at least leave an option for it in acorn-6to5. I'm using a custom transform for async functions, and I depend on that.

**Comment by sebmck** [comment]
@fkling Ah, sorry, didn't mean to place any blame! I'll leave it in as-is since it's technically valid syntax.

**Comment by fkling** [comment]
No worries and thanks! :)

**Comment by benjamingr** [comment]
@sebmck not to be a burden but could you please explain to me what steps would have to happen in order for support to come? Who do I need to ---bug--- help?

**Comment by sebmck** [comment]
@benjamingr It'll need to be added upstream in regenerator. There's currently an open issue tracking this (which you've already commented on) facebook/regenerator#163. Either @benjamn or someone familiar with the regenerator codebase will have to add it.

**Comment by benjamingr** [comment]
Thanks, I'll try to bark at that tree then :)

**Comment by domenic** [comment]
FWIW I would prefer this proposal instead https://github.com/zenparsing/async-iteration/

**Comment by sebmck** [comment]
Closing in favor of facebook/regenerator#163 or until some sort of consensus about the direction of async generators at the TC39 is reached.

**Comment by donaldpipowitch** [comment]
Could this be added with an Babel plugin or does it rely soly on facebook/regenerator#163.

**Comment by sebmck** [comment]
@donaldpipowitch Any of the built-in transformers can be overridden with plugins so, basically. Although if you were going to write a plugin for it I dunno why you wouldn't just add support for it to regenerator since you're going to have to go through more effort as you'd have to also write your own vanilla generator implementation.

**Comment by donaldpipowitch** [comment]
Yeah, it would probably be easier to just add this to regenerator, but as far as I understand it they don't want to add it yet, because there are two rivaling specs, right? https://github.com/jhusain/asyncgenerator and https://github.com/zenparsing/async-iteration/. So a Babel plugin is maybe less intrusive.

**Comment by benjamn** [comment]
I'd be willing to prototype https://github.com/jhusain/asyncgenerator in Regenerator, even though the spec is far from finalized. Right now, `await` is simply translated to `yield`, which is problematic if there can be `yield` expressions in the `async` function that were not originally `await` expressions. The solution I have in mind is to translate `await arg` into something like `yield regeneratorRuntime.await(arg)`, so that `await`able `yield`ed values can be distinguished from normal `yield`ed values. That distinction could be useful regardless of whether `async` generator functions are supported, though they provide the most compelling reason for it.
