### ISSUE TITLE
babel-node doesn't support object rest spread with Node.js v8.3.0 (both babel v6.9.0 and v7.0.0-alpha.19)

### ISSUE THREAD

**Issue by kyrylkov** [babel/babel#6084]
Node.js v8.3.0 REPL with V8 6.0 ([supporting object rest/spread properties](https://v8project.blogspot.com.ee/2017/06/v8-release-60.html)):

```
> process.versions.node
'8.3.0'
> process.versions.v8
'6.0.286.52'
> const { key1, ...rest } = { key1: 1, key2: 2, key3: 3 };
undefined
> rest
{ key2: 2, key3: 3 }
> const copy = { key1: 1, ...rest };
undefined
> copy
{ key1: 1, key2: 2, key3: 3 }
```

`babel-node` REPL with Node.js v8.3.0:

```
> process.versions.node
'8.3.0'
> process.versions.v8
'6.0.286.52'
> const { key1, ...rest } = { key1: 1, key2: 2, key3: 3 };
SyntaxError: repl: Unexpected token (1:14)
> 1 | const { key1, ...rest } = { key1: 1, key2: 2, key3: 3 };
    |               ^
```

https://github.com/nodejs/node/pull/14594#issuecomment-321492982

**Comment by dnalborczyk** [comment]
Not sure if this is the solution, but as an interim you could use the plugin: _babel-plugin-syntax-object-rest-spread_

That way Babel can parse the syntax, but doesn't transpile.

**Comment by hzoo** [comment]
@kyrylkov you didn't specify your config?

@dnalborczyk yeah thats the workaround + solution. The issue is that babylon doesn't parse object rest spread by default because we don't parse anything that isn't spec by default. The only "solution" I can think of is adding the syntax plugin to preset-env for stage 3 proposals that are actually in browsers.

**Comment by kyrylkov** [comment]
@hzoo Config is only:

```
{
  "plugins": [
    "transform-flow-strip-types"
  ]
}
```

**Comment by hzoo** [comment]
@kyrylkov No it doesn't because it works as intended, object rest spread isn't officially in JS so its not on by default as I said above. However you can use `babel-plugin-syntax-object-rest-spread` as mentioned ^, and otherwise you should just use https://github.com/babel/babel-preset-env which handles this. Currently preset-env doesn't do stage 3 because the point is to not compile anything that is supported natively however we'll make an exception for stage 3 proposals that are native https://github.com/babel/babel-preset-env/pull/384

**Comment by dnalborczyk** [comment]
@kyrylkov not sure if you know about this. what @hzoo is referring to is that the TC39 committee (responsible for EcmaScript/JavaScript) advances language features in stages. *Object rest/spread* is currently in _stage 3_, and Babylon apparently only implements fully supported features (_stage 4_ I believe). So you'll have to use a plugin for that reason, until the language feature advances to step 4, and Babylon implements it.

the TC39 process is explained quite well here:
http://2ality.com/2015/11/tc39-process.html
more info here:
https://tc39.github.io/process-document/

**Comment by kyrylkov** [comment]
@dnalborczyk Thanks.  Yes I know about TC39 and stages.  What I didn't know is that babylon supports only latest current spec (ES2017 today).

**Comment by hzoo** [comment]
@kyrylkov to clear up anything misunderstandings, it's not that is only supports the current spec, it just doesn't do anything else by default (else you would output syntax that doesn't work anywhere inherently)

I would read the readme: https://github.com/babel/babylon

![screen shot 2017-08-10 at 1 15 31 pm](https://user-images.githubusercontent.com/588473/29182734-fb6df878-7dcd-11e7-938e-9b182778e1f9.png)

**Comment by bevacqua** [comment]
@hzoo any way to get `@babel/preset-env` to understand object spread syntax but leave it untranspiled? This kind of annoyance bugged me a bunch of different ways, have you guys considered having a `parseOnly` option for plugins where they don't apply any transforms, but just parse the syntax? (Just fishing here, not familiar with Babel internals)
