### ISSUE TITLE
Unexpected token with "env" preset on "spread" operator

### ISSUE THREAD

**Issue by alex-shamshurin** [babel/babel#6162]
**Bug**

Babel failed to parse spread operator with 'ENV' preset enabled (for target 'node')

### Input Code

```js

SyntaxError: server/config/routes.js: Unexpected token (148:10)
  146 |       if (activeRoute) {
  147 |         req.session.activeRoute[sessId] = {
> 148 |           ...activeRoute,
      |           ^
  149 |           lockedSeats: false,
  150 |           ticketsBooked: false,
  151 |           bookingNumber: null,
```

### Babel Configuration (.babelrc, package.json, cli command)

```json
  {
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "current"
        },
        "debug": true,
        "useBuiltIns": true
      }
    ]
  ],
}

```

### Expected Behavior

I think it must understand that NodeJs 8 support ... spread operator

### Current Behavior

Syntax error

### Possible Solution

add "plugins": ["transform-object-rest-spread"] with this one works fine

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.1
| node             | 8.4.2
| npm              | 5.03
| Operating System | Windows 10 x64

**Comment by existentialism** [comment]
@alex-shamshurin currently, `babel-preset-env` [doesn't handle any stage syntaxes/transforms](https://github.com/babel/babel-preset-env#support-all-plugins-in-babel-that-are-considered-latest). In your case, since your target understands the spread operator, you _don't_ need the transform, but you will need to include `babel-plugin-syntax-object-rest-spread`, which enables the syntax in our _parser_.

We're hoping to take care of this "just enable parser syntax if my targets support it, otherwise enable transform" behavior when we land https://github.com/babel/babel-preset-env/pull/384.
