### ISSUE TITLE
Babel 7 alpha 20 break decorators with class properties.

### ISSUE THREAD

**Issue by lixiaoyan** [babel/babel#6181]
Babel: 7.0.0-alpha.20

### Input Code

``` javascript
class X {
  @decorator x;
}
```

### Babel Configuration (.babelrc, package.json, cli command)

``` shell
babel --presets stage-0
```

### Expected Behavior

Babel: 7.0.0-alpha.19

``` javascript
  constructor() {
    _initDefineProp(this, "name", _descriptor, this);
  }
```

### Current Behavior

``` javascript
  constructor() {
    Object.defineProperty(this, "x", {
      configurable: true,
      enumerable: true,
      writable: true,
      value: _initializerWarningHelper(_descriptor, this)
    });
  }
```

It will throw a error when try to instantiate it.

[REPL](https://babeljs.io/7#?evaluate=true&lineWrap=false&presets=stage-0&code_lz=MYewdgzgLgBAJgU1AJwIZRMmBeeCLDICWADhltgHx4HFmYDcMAUM8ADaoQQwAaMAb2YwYAAUQp0mGAA8GzAL6swCAO58AFAEoGQA)

**Comment by loganfsmyth** [comment]
This is likely because of https://github.com/babel/babel/pull/6076. The old decorator-legacy didn't work with spec mode class props.

**Comment by hzoo** [comment]
cc @peey although you are already working on the new decorators anyway so may ask someone else to do this

**Comment by kedromelon** [comment]
i'm interested in trying to figure this out if @peey isn't working on it!

**Comment by hzoo** [comment]
He's working on decorators stage 2 so probably not 😛

**Comment by hzoo** [comment]
Not sure exactly how involved this will be, so feel free to ask questions on slack, and make a WIP pr whenever

**Comment by kedromelon** [comment]
sounds good, will do!

**Comment by kedromelon** [comment]
after sitting down and thinking about this a bit: 

since the current "legacy" decorators are being replaced soon anyway, perhaps it doesn't make sense to be _too_ concerned with fully fleshed out support for this

instead, we could add a note in the current decorators readme mentioning that only loose mode of class-properties is supported by decorators. the stage 1 preset also could then override class properties to loose mode?

here's a PR for something along these lines: (truthfully, i probably should have just had these changes in https://github.com/babel/babel/pull/6076) https://github.com/babel/babel/pull/6196

still down to actually try to figure out compatibility with legacy decorators, but this would give us a route to get some at least form of "support" in ASAP

**Comment by hzoo** [comment]
Yeah that probably be a good idea, less work for us given stage 2 anyway

**Comment by hzoo** [comment]
Ok it doesn't seem worth updating a spec/transform that is out of date and is going to be superseded by the Stage 2 transform that @peey is working on so we will update the error message in this case. Closed by https://github.com/babel/babel/issues/6181

Thanks everyone!
