### ISSUE TITLE
Handle syntax errors from babylon that need a plugin

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6205]
Ref https://github.com/babel/babylon/pull/658

Need to check the error message from babylon and then throw a new error or something cool.

![screen shot 2017-08-03 at 5 00 49 pm](https://user-images.githubusercontent.com/588473/28943599-61931d1a-786d-11e7-9ae7-c97dad2a3190.png)

Could do a mapping between the syntax plugin in babylon and the transform/preset to turn on for babel for the user, or even do a prompt to install, etc.

**Comment by maaz93** [comment]
@hzoo I would like to take this up. Can you give me a starting point to start off?

**Comment by nicolo-ribaudo** [comment]
I think you need to try/catch around the parser call (https://github.com/babel/babel/blob/c87cc1858658b58fcb851667eba45e175003e641/packages/babel-core/src/transformation/normalize-file.js#L40), and have an hardcoded list which, given the parser plugin name, returns the name of the correct Babel plugin.

**Comment by maaz93** [comment]
@nicolo-ribaudo Thanks for your input. 😄 I've figured I need to use `TEST_DEBUG=true TEST_ONLY=babel-core make test-only` to run the subset of tests that might use the file that you've mentioned. Probably, I can narrow down a `TEST_GREP` as I continue. I'll add `debugger;` inside the `if` and first see what it's doing. I'll do some debugging and get back.

I'm new to the `babel` code and I'd love to poke around a bit more before I propose/make any changes.

**Comment by maaz93** [comment]
Hi @nicolo-ribaudo ! It's taken me a looong time to respond. I understood what you pointed me to. While trying to create a _map_ of parser plugin name to Babel plugin, I realised that when new plugins are added/removed/renamed, someone would need to update this _map_ always. So, I started thinking of another probable solution. Hear me out and let me know what you think:

- All the babel plugin folders in the repo have a strict naming convention, i.e, `babel-plugin-[proposal/syntax/transform]-hyphenated-plugin-name` and also every plugin's `package.json` has a `babel-plugin` keyword. And the way `parserOpts.plugins` are specified is `hyphenatedPluginName`
- So, what if I write a utility that greps the child folders of `packages` and generates a sort of _plugin metadata_ that I will use in `normalize-file`?

The utility would follow an algorithm like this

  1. Find all the folders with the `babel-plugin` prefix or even better, folders whose `package.json` has `babel-plugin` as a keyword
  1. Classify each into `proposal` or `syntax` or `transform` and also keep the `hyphenatedPluginName` and the `name` property from `package.json`
  1. Dump this metadata somewhere it can be accessed from. Maybe the `babel-core` package

How I would consume it

  1. Find the `missingPlugin` from the error generated by the parser
  1. Use that to match `hyphenatedPluginName` in the metadata
  1. Then, I would have conditional checks and find a required Babel plugin name (from the generated metadata) and probably even link to the required `README.md`
  1. Throw this as the error from babel, making it much more intuitive and user-friendly 

This way, nobody has to worry about maintaining a map to check how `babel` handles errors from `babylon` due to missing plugins.

If you think this is an overkill, and maintaining a hardcoded map makes more sense, I'd still be happy to do it. :smile:

**Comment by nicolo-ribaudo** [comment]
The naming convention isn't enforced in any way, so I'd prefer not rely on it.
We can start with the hardcoded map and later, if we see we can't keep it up-to-date, make it automatic.

**Comment by maaz93** [comment]
Alright! I'll create a hardcoded map. I'll use the below format

```json
{
  "dynamicImport": {
    "syntax": "..."
  },
  "classProperties": {
    "syntax": "...",
    "proposal": "..."
  }
}
```
If there is only `syntax`, I'll suggest they need to install a third-party `transform` along with this, else I'll suggest an existing `proposal` or `transform`. Sounds good?

**Comment by nicolo-ribaudo** [comment]
Usually if there is just the syntax plugin is because it can't be transformed by Babel (for example, `import()` must be handled by a module bundler and not by a Babel plugin). You can differentiate syntax-only and transform by reporting something like `Use the syntax-... plugin to enable parsing` and `Use the proposal-... plugin to enable transformation`.

**Comment by maaz93** [comment]
I created an exhaustive list using the [README](https://github.com/babel/babel/blob/master/packages/babylon/README.md#plugins) from babylon. I have questions about a few plugins. What do I do about them?

1. `bigInt`, `classPrivateMethods`, `classPrivateProperties`, `estree` and `importMeta` don't have any syntax or transform plugins.
1. `exportExtensions` has two transforms, namely `@babel/plugin-proposal-export-namespace` and `@babel/plugin-proposal-export-default`, linked to it. Though the babel [docs](https://babeljs.io/docs/plugins/transform-export-extensions/) talk about a transform, I can't find it. Looks like it was split into 2 proposals.
1. `flow` doesn't really have a transform. It has a stripping plugin (`@babel/plugin-transform-flow-strip-type`) and a commenting plugin (`@babel/plugin-transform-flow-comments`)

**Comment by nicolo-ribaudo** [comment]
1. `estree` doesn't enable any syntax, it modifies the AST to be compatible with the `estree` specification. It is only used by packages which use Babylon directly, so you don't need to handle it in your pr. For the other plugins, you can throw something like `this syntax isn't supported by Babel yet` and maybe give a link to the corresponding issue in https://github.com/babel/proposals.
2. Since it hasn't been split yet in Babylon (https://github.com/babel/babel/issues/6678), you can suggest both plugins.
3. I think suggesting `@babel/plugin-transform-flow-strip-type` is ok.

**Comment by nicolo-ribaudo** [comment]
> `exportExtensions` has two transforms, namely `@babel/plugin-proposal-export-namespace` and `@babel/plugin-proposal-export-default`, linked to it. Though the babel [docs](https://babeljs.io/docs/plugins/transform-export-extensions/) talk about a transform, I can't find it. Looks like it was split into 2 proposals.

@maaz93 https://github.com/babel/babel/pull/6920
