### ISSUE TITLE
Async function hoisting is overly aggressive

### ISSUE THREAD

**Issue by houli** [babel/babel#6206]
## Bug Report
The transformation of `async function x` to `var x = function () { var _ref = _asyncToGenerator(... ` means that x must be hoisted. This is to avoid issues where `x` is referred to before it is defined. The problem is that the hoisting is overly aggressive and async functions appear before other statements in the code such as requires and imports. This is immediately noticeable if you try to write an async function in a module that sets up `babel-polyfill`/`regenerator-runtime` as a global using a side-effectful require/import. The result is broken code that fails as `regeneratorRuntime` will be undefined.

### Input Code

[Example using `import`](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&circleciRepo=&code_lz=JYWwDg9gTgLgBAcigUwObIHbKgQxtAWigFcMZRkB6EsihAKHpwGcBPDAYzgDNSPyIGOAA84ACgCUcAN704cFDGJQhARnoBfRsMlA&debug=false&evaluate=false&lineWrap=true&presets=env&prettier=false&showSidebar=true&targets=&version=6.26.0)
[Example using `require`](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&circleciRepo=&code_lz=E4UwjgrglqAUDkoDmIB2JgEMAuB7YAtMBKtlALYgD0xpFI8AlAFDOYDOAnqgMYAEAMxI8yuVHwAefWIz4BvZnz6hsEYOICMzAL6sJMoA&debug=false&evaluate=false&lineWrap=true&presets=env&prettier=false&showSidebar=true&targets=&version=6.26.0)

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["env"]
}
```

### Expected Behavior
The order of statements is preserved in a way that async functions are hoisted only as high as they need to be.

### Current Behavior
Async functions are hoisted to the top of the module including to the point where they break the semantics of the `import` statement by appearing before it.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | 8.4.0
| npm              | 5.3.0
| Operating System | macOS

**Comment by loganfsmyth** [comment]
Currently this is the suggested approach: https://github.com/babel/babel/issues/4487#issuecomment-245842828

We don't really have any way of knowing where to put the function. We could technically special-case `babel-polyfill`, but you could just as easily do `import "./my-polyfills";` with `babel-polyfill` in another file and it would still break.

The best we could do is leave it as a function declaration and just rewrite it to remove the `async` instead, which would still break if you managed to call the function before the polyfill had executed. We may well do that at some point, but it hasn't happened yet because the recommendation above works for all cases and is easy to do.

**Comment by loganfsmyth** [comment]
This should be fixed in 7.x
