### ISSUE TITLE
ReferenceError: this hasn't been initialised - super() hasn't been called

### ISSUE THREAD

**Issue by dthai92** [babel/babel#6212]
See [repo](https://github.com/dthai92/babel-bug-super) to reproduce issue.

### Reference error from this code

```js
import React, { Component } from 'react';
import ReactDOM from 'react-dom';

class App extends Component {

  state = {
    text: 'Hello World!'
  }

  render() {
    return <h1>{this.state.text}</h1>;
  }
}

ReactDOM.render(
  <App/>,
  document.getElementById('root')
);
```

### Babel Configuration (package.json)

```js
{
  "name": "babel-bug-super",
  "scripts": {
    "start": "node_modules/.bin/webpack-dev-server --config webpack.config.js -p"
  },
  "dependencies": {
    "react": "^15.5.4",
    "react-dom": "^15.5.4"
  },
  "devDependencies": {
    "babel-core": "7.0.0-alpha.20",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-class-properties": "7.0.0-alpha.20",
    "babel-plugin-transform-es2015-classes": "7.0.0-alpha.20",
    "babel-plugin-transform-es2015-modules-commonjs": "7.0.0-alpha.20",
    "babel-plugin-transform-optional-chaining": "7.0.0-alpha.20",
    "babel-plugin-transform-runtime": "7.0.0-alpha.20",
    "babel-preset-env": "2.0.0-alpha.20",
    "babel-preset-es2015": "7.0.0-alpha.20",
    "babel-preset-react": "7.0.0-alpha.20",
    "babel-preset-stage-0": "7.0.0-alpha.20",
    "html-webpack-plugin": "^2.30.1",
    "webpack": "^3.5.5",
    "webpack-dev-server": "^2.7.1"
  }
}
```

### Expected Behavior

babel-plugin-transform-class-properties should handle transforming class to ES5.

### Current Behavior

Not adding a constructor class causes a reference error.

`Uncaught ReferenceError: this hasn't been initialized - super() hasn't been called`

### Context

This issue came up when I was in the process of utilizing the [transform-optional-chaining](https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-optional-chaining) babel plugin. I upgraded the babel library versions to 7.x from 6.x and came across this issue.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-alpha.20
| node             |  8.1.0
| npm              |  5.0.4
| Operating System |  macOS Sierra v10.12.5

**Comment by jridgewell** [comment]
Ok, this is due to the inserted constructor (which you figured out), using `babel-runtime` helpers. Explicitly:

```js
return super();

// Transforms into (roughly)
var _this;
return _possibleConstructorReturn(_this, _this = _possibleConstructorReturn(this, Component.call(this))
```

Notice the two calls to `_possibleConstructorReturn`. The outer one throws the error, the inner works fine. If we consult source code in `babel-runtime@7.0.0-alpha.20`, we see:

```
exports.default = function (self, call) {
  if (!self) {
    throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
  }

  return call && ((typeof call === "undefined" ? "undefined" : (0, _typeof3.default)(call)) === "object" || typeof call === "function") ? call : self;
};
```

That outer call passes `undefined` for self, which throws the error.

- - -

This usecase was actually fixed indirectly with https://github.com/babel/babel/pull/5885 in alpha.15. Why wasn't runtime's code updated? @hzoo

**Comment by hzoo** [comment]
Good investigation @jridgewell 

It might be because it wasn't "changed"  itself but it's dependencies did so it didn't publish again (lerna does a deps check)? This has been an issue before, so we may want to force a publish for that pkg specifically when releasing then. Although I thought I turned on force publish so dono

**Comment by dthai92** [comment]
That makes sense @jridgewell. This explains how the reference error could be avoided by removing the babel-plugin-transform-runtime from the babel-loader in the webpack.config.js.

**Comment by hzoo** [comment]
Ok I downloaded the repo, and see the runtime helpers code ^. In node_modules the version is still v6 for some reason. The alpha.20 version is correct it's just resolving to the old version still for some reason.

```
  "_from": "babel-runtime@^6.18.0",
  "_id": "babel-runtime@6.26.0",
  "_requiredBy": [
    "/babel-plugin-transform-unicode-property-regex/babel-helper-regex",
    "/babel-plugin-transform-unicode-property-regex/babel-types",
    "/regenerator-transform",
    "/regenerator-transform/babel-types"
  ],
```

Looks like we really need those updates from regenerator/unicode-property, neither of which are in this repo?

**Comment by hzoo** [comment]
Oh of course, you are using transform-runtime but don't have babel-runtime as a dependency. Because those 2 packages ^ include it, it uses v6 instead of just erroring asking you to use v7.

solution: add babel-runtime@7.0.0-alpha.20 as a dep (you always need it if you are using the transform-runtime plugin).
