### ISSUE TITLE
[bug] Generating leadingComments in called CallExpressions

### ISSUE THREAD

**Issue by Andarist** [babel/babel#6298]
**bug report**

### Input Code
```js
// index.js
fn()()()
```

### Babel Configuration (.babelrc, package.json, cli command)
```js
// plugin.js
exports.default = function () {
  return {
    CallExpression(path) {
      path.addComment('leading', 'foo')
    }
  }
}
```

### Expected Behavior
```js
// index.js
/*foo*/fn()/*foo*/()/*foo*/()
```
### Current Behavior
```js
// index.js
/*foo*//*foo*//*foo*/fn()()()
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  latest
| node             | irrelevant
| npm              | irrelevant
| Operating System | irrelevant

**Comment by nicolo-ribaudo** [comment]
I think this works as intended:

In `foo()()()` the call expressions are `foo()`, `foo()()` and `foo()()()`. Since leading comments are added before the node, thei should all go before `foo`.

If you want the comment to be placed between the callee and the parentheses, you may do something like this:

```js
exports.default = function () {
  return {
    CallExpression(path) {
      path.get("callee").addComment('leading', 'foo')
    }
  }
}
```

**Comment by loganfsmyth** [comment]
I agree. I see this as expected behavior.

**Comment by Andarist** [comment]
Thanks for the clarification guys, I've misunderstood how nodes are structured here. It makes sense that it gets printed like this :)
