### ISSUE TITLE
Flow: `import { type X }` compiles differently from `import type { X }`

### ISSUE THREAD

**Issue by TiddoLangerak** [babel/babel#6300]
### Bug

Named type imports are stripped differently based on which syntax is used. `import { type X } from 'X'` results in `import 'X'`, while `import type { X } from 'X'` is stripped completely. As a result, the two statements are not equivalent. 

### Input Code

```js
import { type X } from 'X';
import type { Y } from 'Y';
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets" : ["babel-preset-flow"]
}
```

### Expected Behavior

At the minimum I expect both imports to be treated equally, i.e. either both are stripped or both result in an import. My intuition says that it should be the empty output, since I don't expect types to have runtime behaviour, but flow itself currently doesn't seem to have a stance on this (ref: https://github.com/facebook/flow/issues/4935).

### Current Behavior

Output:
```
import 'X';

```

### Possible Solution

Strip `import { type X }` statements completely.

### Context

I ran into this issue while trying to resolve a circular dependency, where an `import { type X }` completed the circle (to my surprise). After a long debugging session I noticed that this circle got broken by just replacing `import { type X }` with `import type { X }`, something which isn't documented anywhere nor very intuitive.

(The actual context for the circular dependency is quite complicated. If necessary I can still provide it on request)

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  v6.26.0
| babel-preset-flow | v6.23.0
| node             | v8.4.0
| npm              | v5.3.0
| Operating System | Linux (Fedora 25 64-bit)

**Comment by loganfsmyth** [comment]
This is expected behavior, but I definitely sympathize with your confusion. We don't have much control over what syntax Flow supports though.

```
import type { Foo } from '';
```
is explicitly an import declaration that only imports types. It is impossible for an `import type` statement to import anything but a type, so it has no runtime behavior and cannot cause a circular dependency.

```
import { type Foo } from '':
```
was explicitly added _because_ it has runtime behavior. You can add `type` to a specific imported name because it's super nice to be able to do things like
```
import Foo, { type Bar } from '';
```
instead of having to do
```
import Foo from '';
import type { Bar } from '';
```
as two separate declarations.

In your specific case, it's just that it essentially breaks down into
```
import '':
import type { Foo } from '':
```
where the first part's only goal is to load the file, without pulling in any variables from it.

**Comment by TiddoLangerak** [comment]
Thanks for the explanation! This is also what the flow maintainers explained in the mean time, so I think this issue can be closed.
