### ISSUE TITLE
do-expression support for catch

### ISSUE THREAD

**Issue by graingert** [babel/babel#6331]
Choose one: is this a bug report or feature request? bug

I expect this to work:
```js
const foo = () => do { throw new Error('foo'); };
const bar = () => 3;
const res = do {
  try { foo(); } catch (e) { bar(); }
}
console.log(res); // 3;
```

But I get `undefined`;

babel transpiles to:
```js
const foo = () => function () {
  throw new Error('foo');
}();
const bar = () => 3;
const res = function () {
  try {
    return foo();
  } catch (e) {
    bar();
  }
}();
console.log(res); // 3;
```

but I expected:

```js
const foo = () => function () {
  throw new Error('foo');
}();
const bar = () => 3;
const res = function () {
  try {
    return foo();
  } catch (e) {
    return bar();
  }
}();
console.log(res); // 3;
```

an alternative that works is:
```js
const foo = () => do { throw new Error('foo'); };
const bar = () => 3;
const res = do { try { foo(); } catch (e) {} } || bar();
console.log(res); // 3;
```

see https://github.com/tc39/proposal-do-expressions/issues/6

**Comment by xtuc** [comment]
I have a fix [there](https://astexplorer.net/#/gist/d2fabd373c1b9da9adee9468c8e4db46/ed9bf499a022de21c257bcee30994efc94661d62) which could be added to the existing transformation plugin.

The source of this issue comes from `path.replaceExpressionWithStatements`
https://github.com/babel/babel/blob/0e432f0e0dc4b275ffa6948c3495c5cc5bcf52d5/packages/babel-traverse/src/path/replacement.js#L209-L254

I was not able to fix the issue in the `replaceExpressionWithStatements` function.
