### ISSUE TITLE
Issue with reusing AST nodes

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6375]
Just want to write this down since we're seeing the same kind of fix for issues and we should look into solving this generally.

Immutable asts would be a larger change, so maybe https://github.com/babel/babel/pull/5971 or infra in our unit tests to check uniqueness would help

https://github.com/babel/babel/pull/6046
https://github.com/babel/babel/pull/6054
https://github.com/babel/babel/pull/6374

**Comment by xtuc** [comment]
I can work on this tomorrow, I would like to have a quick prototype to measure the perf impact (if any).

**Comment by Andarist** [comment]
closed by accident with a fat finger :<

**Comment by xtuc** [comment]
It's more complicated than I thought , the traverse algorithm is not easy to understand.

I wanted to use Immutable.js with a tree datastructure.

I don't know what we would do with mutations like: `path.node.id.name = "a";`, it would have a big perf impact to allow that (since it would bypass the partial copy optimization). Only `path.Insert*`, `path.remove` or `path.replace*` would be possible.

I've looked into OCaml and GHC, both compiler are self-hosted and uses an immutable tree. They are fast enough to not need to merge visitors and only use `passPerPreset`-like behavior.

**Comment by hzoo** [comment]
@loganfsmyth had ideas a long time ago: https://github.com/babel/notes/blob/master/2016/2016-08/august-01.md#potential-api-changes-for-traversal around this.

And yes we would have to prevent assignment and only allow path methods

**Comment by hzoo** [comment]
Happening more so we really need a fix

https://github.com/babel/babel/pull/6517
https://github.com/babel/babel/pull/6657

**Comment by nicolo-ribaudo** [comment]
Related: https://github.com/babel/babel/pull/3428
