### ISSUE TITLE
babel-core not recognizing jpg (or other image) imports

### ISSUE THREAD

**Issue by Always-Sunny** [babel/babel#6443]
When trying to import a photo: 

`import img from '../public/photo.jpg';`

babel-core throws this error:

> /Users/ryan/Desktop/Df/Coding/bare-minimum/node_modules/babel-core/lib/transformation/file/index.js:590
>       throw err;
>       ^
> 
> SyntaxError: /Users/ryan/Desktop/Df/Coding/bare-minimum/public/photo.jpg: Unexpected character '�' (1:0)
> > 1 | ����

I made a bare-minimum app to reproduce this error, as it was occurring in a another app I was working on. To reproduce, clone: https://github.com/Always-Sunny/bare-minimum/tree/fileloader and npm start. 

Node 8.6.0
file-loader: 1.1.5
webpack 3.6
babe-core 6.26.0

**Comment by loganfsmyth** [comment]
This isn't a Babel issue really. Your code is loading a JPEG, and Node doesn't know what you want it to do. For browser-side, you've configured Webpack to handle images, but Node can't handle it.

What is it you'd expect your Node code to do for your images? I don't know off the top of my head what a normal approach here would be, but this probably isn't the place to have that conversation.

**Comment by Always-Sunny** [comment]
But the error is being thrown from inside babel-node? I'm using express to serve static files, and I've already posted an issue in file-loader's repo. Don't know where else to address this issue. (I have a stack exchange going too). Any advice on where else to go or what else to do?

**Comment by loganfsmyth** [comment]
> But the error is being thrown from inside babel-node

Yes, but you'd also get the same error in Node without `babel-node`. Babel doesn't know what it should do with a JPEG and neither does Node.

> I'm using express to serve static files

That may be where this misunderstanding is coming from? Your code isn't serving static files at all. You are explicitly importing the image in your JS code. That means webpack itself will include the binary content if the image inside your final JS file. This same behavior means Node will try to load the JPEG as if it were JavaScript code, since it doesn't know what a JPEG is. 

> Any advice on where else to go or what else to do?

You need to figure out what you actually expect this to do. If you're running this code on Node, how is the JPEG loaded? Probably importing it doesn't make sense. If it's a static file, then you should just be referencing the file URL in your JSX and the browser will handling loading it, and since that means it wouldn't be imported anymore, this error would vanish.

**Comment by tsheaff** [comment]
In my case I have the same issue. @loganfsmyth I'm attempting to move my images from being hosted by the web server to being uploaded and served from a CDN. Thus my webpack output publicPath is pointing to a CDN.

I'm expecting the import to essentially rewrite the URL to be, essentially, `my-cdn.foo.com/md5-of-image.png`

**Comment by tsheaff** [comment]
Was a problem with babel-register for me. See my solution here: https://github.com/webpack-contrib/file-loader/issues/271
