### ISSUE TITLE
(transform-es2015-function-name) Scripts root function variable is renamed

### ISSUE THREAD

**Issue by tenbits** [babel/babel#6456]
Hello Team, 

initially I got the issue with `es2015` preset, but lately I have narrowed it to the `function-name` plugin.  Consider this setup:
```json
{
    "devDependencies": {
        "babel-cli": "6.26.0",
        "babel-plugin-transform-es2015-function-name": "6.24.1"
    },
    "scripts": {
        "build": "babel file.js -o file-compiled.js"
    },
    "babel": {
        "sourceType": "script",
        "plugins": [
            "transform-es2015-function-name"
        ]
    }
}
```
```js
var obj_clone;
(function(){  
  obj_clone = function () {
    obj_clone();
  };
}());
```
> The function sample is simplified for demo purpose

The source file is expected to be transpiled as a script, so that `obj_clone` method is available in scripts scope, but the plugin, or babel internals, renames the variable `obj_clone` to `_obj_clone` and the output is:
```js
var _obj_clone;
(function () {
  _obj_clone = function obj_clone() {
    _obj_clone();
  };
})();
```

This behaviour occurs only if the variable is declared outside the **IIFE** and on **recursive** functions. The snippets below are transpiled as expected:
```js
// root var is not renamed
var obj_clone;
(function(){
    var obj_clone_local = function () {
        obj_clone_local();
    };
    obj_clone = obj_clone_local;
}());
```
```js
// root var is also not renamed
var obj_clone = function () {
    obj_clone();
}
```

Cheers, Alex

**Comment by Andarist** [comment]
Could u write down ur expected result for your example and justify ur reasoning? I think the behaviour is quite good, because it:
- acts as with [inferred function names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name#Inferred_function_names)
- allows u to use correct identifier from the outer scope, consider similar input:
```js
var obj_clone;
(function(){  
  obj_clone = function () {
    obj_clone = someOtherFn;
    obj_clone();
  };
}());
```
if babel would not change outer scope variable you would end up with reassigned local function name, because the output would be
```js
var obj_clone;
(function(){  
  obj_clone = function obj_clone() {
    obj_clone = someOtherFn;
    obj_clone();
  };
}());
```
And the outer `obj_clone` would effectively not get reassigned

**Comment by Andarist** [comment]
If the behaviour of inferred function names is one u don't rely upon, you can always switch to using recommended `babel-preset-env` and leverage its [`exclude option`](https://github.com/babel/babel/tree/fcdfc61bdbf8898c9cf872fa4f615bddd4cd3548/experimental/babel-preset-env#exclude) to "ban" `function-name` plugin

**Comment by loganfsmyth** [comment]
Generally Babel assumes that each file it processes is a module (ES6 or CommonJS), rather than a general script, so renaming things like that is safe in that context because variables declared at the top level of the file are module-scoped, not global.

This behavior definitely happen with function-name like you've described, but there may be other cases that will make it happen too.

I'd recommend using a module bundler like Webpack to avoid global variables entirely really. Then if you want to create a global, do it explicitly.

**Comment by tenbits** [comment]
@Andarist The expected behaviour is such when the root variable name is not renamed.
```js
var obj_clone;
(function(){  
  obj_clone = function () {
    obj_clone();
  };
}());
```

Root variable `obj_clone` should be `obj_clone` after transpiling.

@loganfsmyth Does `"sourceType": "script",` in options has no influence on source type?

>  create a global, do it explicitly

Actually I don`t want it to be global, it should be in the root scope of the script, and how and where the script is executed is beyond the topic. 

Is it not more possible safly to transpile the javascript "script" files? What for is then the "sourceOption:script"? So that, to be sure root variable names are not renamed? 

Thanks.

**Comment by Andarist** [comment]
@tenbits you have not used `transform-es2015-function-name` semantics in ur expected output. I believe the output **is** exactly what you have proposed **when** not using the mentioned plugin. The real question was - what is expected output when **using** `transform-es2015-function-name`?

**Comment by loganfsmyth** [comment]
> Does "sourceType": "script", in options has no influence on source type?

Not in this case. `sourceType` controls parsing of content based on JavaScript's parsing targets, but CommonJS modules are also really `script`s. Babel essentially assumes you're always in a module separately.

> Actually I don`t want it to be global, it should be in the root scope of the script

That comment was based on

> The source file is expected to be transpiled as a script, so that obj_clone method is available in scripts scope

So we're on the same page, there is no "scripts scope". Variables declared in the root scope of a non-modular script are globals. If `obj_clone` isn't global or isn't going to be used outside the file, then renaming is a safe operation because Babel is guaranteed to have access to all of the places that access the variable. 

Module systems have become the general norm for JS development these days, so that is the usecase that Babel is most targeted at.

**Comment by tenbits** [comment]
@Andarist ups, sorry, it was the source, the expected output would be:
```js
var obj_clone;
(function () {
  obj_clone = function obj_clone() {
    obj_clone();
  };
})();
```
And as I have already mentioned right now
```js
var obj_clone = function(){
	obj_clone();
};
```js
gets transpiled, _as expected_, to:
```
var obj_clone = function obj_clone() {
	obj_clone();
};
```

**Comment by loganfsmyth** [comment]
> gets transpiled, as expected, to:
```
var obj_clone = function obj_clone() {
    obj_clone();
};
```

The reason that isn't done, which I admit isn't strictly necessary in this case, is that if the code was something like
```
var obj_clone;
(function () {
  obj_clone = function() {
    obj_clone();
  };
})();
obj_clone = function(){};
```
then
```
var obj_clone;
(function () {
  obj_clone = function obj_clone() {
    obj_clone();
  };
})();
obj_clone = function(){};
```
would behave differently, because now the reassigned function doesn't apply to the recursive call.

Again though, it would dramatically help the readability of your code to explicitly create a global, which would avoid this issue entirely. e.g.

```
(function(){  
  var obj_clone = window.obj_clone = function () {
    obj_clone();
  };
}());
```

**Comment by loganfsmyth** [comment]
I'll also add that doing
```
var obj_clone = function obj_clone() {
    obj_clone();
};
```
is only possible if we can statically ensure that the variable is _never_ reassigned, which is impossible if the file is executed as a standard browser script since things in other files could reassign it. And if it _isn't_ global, then the output we already give doesn't have any external sideeffects.

**Comment by loganfsmyth** [comment]
Also I should be clearer, I'm not trying to argue against having a general flag for distinguishing real language-level scripts from CommonJS modules. In fact I've raised the issue before out of concern for top-level variable mangling for `babel-minify`. It is just that we don't have that now, so I'm trying to illustrate why things behave the way they do at this moment. It's also unlikely something that we'd get to in the near term.

For now, the easiest thing you can do is treat your file like a module, and explicitly create globals by assigning global properties.

**Comment by tenbits** [comment]
Yes, the re-assigment at runtime within the recursive loop itself is the only one edge case. But even with the renaming: Why should the **variable** be renamed and not the new **function** name should be different? The output would be then:
```
var obj_clone;
(function () {
  obj_clone = function _obj_clone() {
    obj_clone();
  };
})();
```

Thanks, @loganfsmyth, but the workaround is not possible in my case, as the script is executed not in the global scope, therefor the variable is not global.

**Comment by loganfsmyth** [comment]
> Why should the variable be renamed and not the new function name should be different?

Because we're trying to make the code as spec-compliant as possible, and the spec doesn't add underscores to the start of the function name.

If we had a flag to say files were scripts and not modules, then I think that'd be reasonable behavior to opt into, but we're trying to make our defaults as spec-compliant as we can.

> the workaround is not possible in my case, as the script is executed not in the global scope

Ah okay. How are you executing it exactly? Perhaps there are other alternatives I can recommend if we have more info.

**Comment by tenbits** [comment]
@loganfsmyth Which spec doesn't allow underscores in function names?

As a workaround I have just added the name of the function manually, so that it is not anonymous anymore.  Now the function name and the variable name stay intact.

> It is a legacy script. It is used after transpiling in 2 scenarios: unit testing by injecting in a sandbox and bundling with simple concatenation with other scripts. Sure modules are much better, but it was developed long before es modules and babel itself, so some time needed to rewrite the things.

**Comment by loganfsmyth** [comment]
> Which spec doesn't allow underscores in function names?

The goal of `transform-es2015-function-name` is to cover the following ES6 behavior:

```
var obj_clone;
(function(){  
  obj_clone = function () {
    obj_clone();
  };
}());

obj_clone.name === "obj_clone" // true
```
so if we rewrote it to

```
var obj_clone;
(function(){  
  obj_clone = function _obj_clone() {
    obj_clone();
  };
}());

obj_clone.name === "obj_clone" // false
```
the result of that changes.

**Comment by tenbits** [comment]
@loganfsmyth Thanks again for the clarification.  It is really sad that babel doesn't aim to support "script" modules, and that "function-name" plugin has higher priority. Though it seems, it doesn't always support it.

<table>
<tr><td>Source</td><td>Output</td></tr>
<tr>
<td><pre lang="js">
var foo = function () {
    foo();
};
foo = function(){}
console.log(foo.name)
</pre></td>
<td><pre lang="js">
var _foo = function foo() {
    _foo();
};
_foo = function _foo() {};
console.log(_foo.name);
</pre></td>
</tr>
</table>

Prints `_foo`.

Thanks again for your time @loganfsmyth, closing the issue.

**Comment by loganfsmyth** [comment]
Fair enough. Like I said, if you expand on your usecase it's still entirely possible we can give you suggestions. Running Babel on general scripts just isn't very common. You may very well be able to get your code to work with the addition of a custom plugin or something, but we can't say if we don't know your usecase.

**Comment by Andarist** [comment]
@loganfsmyth well, the use case got mentioned - he runs this script as part of some larger script, so probably other part needs to know the identifier beforehand, because the 2 scripts get concatenated

Anyway the behaviour could get polished I think because as you have mentioned the renaming in the given example was not necessary. Also the [latest code example](https://github.com/babel/babel/issues/6456#issuecomment-335595135) is a little bit troubling.
