### ISSUE TITLE
Quoted and unquoted properties are represented too differently in the AST

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel#6507]
Choose one: is this a bug report or feature request?  **Bug report?**

### Input Code
```js
export type Test = {
  hello: string,
  world: string,
}

export type Test2 = {
  "hello": string,
  "world": string,
}
```

### Expected Behavior
Since `Test` and `Test2` are functionally equivalent and a property name is a property name regardless of whether it's in quotes, I expected the AST to use the same type of node for quoted and unquoted property names.

### Current Behavior
`Test`'s properties get parsed as `Identifier`s in the AST.
`Test2`'s properties get parsed as `Literal`s.

### Possible Solution
Perhaps both could be parsed as `Identifier`s (or some new type like `PropertyName`) with an optional `quoted: true` property to tell ` babel-generator` to output the property name in quotes even if it doesn't need to be.

### Context
I just discovered a bug in `babel-plugin-flow-runtime` (https://github.com/codemix/flow-runtime/issues/159) that must be due to the fact that they didn't handle the `Literal` case properly.  Using the same type of node for all object literal property names would eliminate the possibility of bugs like this in the future.

### Your Environment
```
├─┬ babel-cli@6.24.0
│ └── babel-core@6.24.0  deduped
├── babel-core@6.24.0 
├── babel-plugin-flow-runtime@0.11.1 
├── babel-preset-es2015@6.24.0 
├── babel-preset-stage-1@6.22.0 
└─┬ babel-register@6.24.0
  └── babel-core@6.24.0  deduped
```

**Comment by loganfsmyth** [comment]
I understand that this is an case that may not always be taken into account, but it seems like something to be addressed by the individual transforms. `StringLiteral` nodes have a well-defined set of expectations. The are wrapped in quotes, and have a broader set of characters that are allowed in them. It's not just toggling a `quoted` flag.

Object properties take many forms already, I think it would be a mistake to conflate these two cases. Take for example
```
{
    // `key` is a NumericLiteral, neither a StringLiteral or an Identifier
    4: "",

    // `key` is an `Identifier`, but it's not the same as your example
    [hello]: ""

    // Has no `key` at all.
    ...hello
}
```

JavaScript as a language has lots of cases. Babel's AST generally leaves it up to the transforms to ensure that these cases are covered, rather than try to make the AST itself try to standardize syntactic structures.

In a perfect world we'd have clear type definitions for all of this that transforms could rely on to make sure they are covering all the branches they need to cover, but we're not there yet.

**Comment by jedwards1211** [comment]
@loganfsmyth I agree that those other cases should not be conflated, but they are semantically different, whereas `{foo: "bar"}` and `{"foo": "bar"}` are semantically the same, are they not?

Also it's ironic that some older version of babylon (whatever is just "babylon" on AST explorer) conflated numeric and string literals with one type of node.

**Comment by loganfsmyth** [comment]
I agree that they are semantically equivalent, but I disagree that it's an argument in favor of changing this. Standardizing semantically equivalent structures into matching AST nodes has never been a goal of Babylon's AST in particular.

> Also it's ironic that some older version of babylon (whatever is just "babylon" on AST explorer) conflated numeric and string literals with one type of node.

Babel 5's parser was closer to [`ESTree`](https://github.com/estree/estree) which merges all primitive literals, but they were split apart in 6.x. Not all literals are usable in the same places, so it seems super misleading to say "all `Literal` nodes can be keys" because that just isn't true.

```
{ true: "bar" }
```
for instance is an `Identifier` key and not a `BooleanLiteral`, so it's helpful to be able to say it is `Identifier`, `StringLiteral` or `NumericLiteral` separately. Otherwise we'd have to say it's `Identifier` or `Literal` but then have other sub-logic to check the type of the literals.

**Comment by jedwards1211** [comment]
I wish there were a way we could prevent bugs like this in the future, but it seems like you're pretty set on this.
