### ISSUE TITLE
Duplicate definitions of variables should throw syntax error

### ISSUE THREAD

**Issue by babel-bot** [babel/babel#6722]
> Issue originally reported by @danez in babel/babylon#78

According to the spec when defining multiple variables with the same name, the parser should throw and SyntaxError when using `let` or `const`:

`let foo, foo;`
or
`let foo; let foo;`

From [13.2.1.1](https://tc39.github.io/ecma262/#sec-let-and-const-declarations-static-semantics-early-errors):

> It is a Syntax Error if the BoundNames of BindingList contains any duplicate entries.

V8 trows an error for `let` and `const`, but not vor `var`.

**Comment by gmmorris** [comment]
I think this can be closed, in the REPL I see a "Duplicate declaration "foo"" error, as expected.

**Comment by Jamesernator** [comment]
Well it's supposed to be an early error like other such errors for example `babylon.parse` correctly throws an early error on generator `constructor` (:

```js
class Foo {
    *constructor() {}
}
```

Which is defined in [14.5.3](https://tc39.github.io/ecma262/#sec-static-semantics-constructormethod). The same should apply to this as it's also an early error, so this:

```js
babylon.parse(`
    let foo, foo
`)
```

Should throw a `SyntaxError` rather than create an invalid AST.

**Comment by DrewML** [comment]
Maybe it makes sense for us to just open a discussion issue for whether we want to implement early error tracking at all in `Babylon`.

If we did do that, we'd probably want it to be configurable on/off (like the `shift` parser), since some tools that use `Babylon` wouldn't want to pay the cost during parse

**Comment by gmmorris** [comment]
The question is where do we draw the line between valid JS syntax vs custom syntax?

My thinking is that if we want the parser to ignore syntax which is invalid as per the spec in order to allow developers to utilise "invalid" syntax (which they would then correct on transform) then presumably we don't want to throw any early parsing errors - if we can tokenize it, let it through. No?
