### ISSUE TITLE
cloning object without one entry not working in babel in some cases

### ISSUE THREAD

**Issue by bjg2** [babel/babel#6762]
Following code does not remove an item, even though it should have.
Code works as expected in chrome console, but not when compiled with babel (for example, [here](https://repl.it/NtFF/1)).
If "removeItem(obj, 2)" is replaced with "removeItem(obj, '2')", it works in babel as well.

Code:
const addItem = (obj, key, val) => ({...obj, [key]:val});

const removeItem = (obj, key) => {
  let {[key]:removedItem, ...restCol} = obj;
  return restCol;
};

let obj = {};
obj = addItem(obj, 1, 'one')
obj = addItem(obj, 2, 'two')
obj = addItem(obj, 3, 'three')

removeItem(obj, 2)

**Comment by nicolo-ribaudo** [comment]
Fixed in Babel 7: https://babeljs.io/repl/build/master#?babili=false&browsers=chrome%2060&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhgEwQSSgUwLYwLwwBQgBGAVgDQwDWaAnuQG5wA2AlDgHz4DeAdL0WTADaVagF0AXA0YBfZgG4AUAtCRYAJ0wg6aVJhz5-5Ea2wdOCxmlidhNCRoxa0KdBnK9uG6AGEQM_fyKGlAArmpgMF5QvoyK0ooWVjD8-pzxCim4iC6YBCTkAIzkAOTgaMXMGST62boYeQIATCVQAO4gFVXENUh1DeQAzC0AFhrllcrgEH5o3MCWcGp48pOQM9yMIADmeA5OfYYwjczyQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-2%2Cenv&prettier=true&targets=Node-6&version=7.3.4
