### ISSUE TITLE
Path.ensureBlock does not set ArrowFunctionExpression's "expression" flag

### ISSUE THREAD

**Issue by hansonw** [babel/babel#6772]
### Input Code

In the following snippet, calling `path.ensureBlock()` does not properly unset the "expression" flag on the ArrowFunctionExpression. This causes problems for other plugins, which may rely on the accuracy of the flag (notably, istanbul-lib-instrument).

```js
export default function (babel) {
  const { types: t } = babel;
  
  return {
    name: "ast-transform", // not required
    visitor: {
      ArrowFunctionExpression(path) {
        path.ensureBlock();
        if (path.node.expression) {
          throw Error("Should no longer be an expression");
        }
      },
    }
  };
}
```

https://astexplorer.net/#/gist/0bd0506d529ed4c59a4ab10ffc2bd105/c23cb1d08aed3b721a53142b4d3bc6fb14d2af7b

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

See ASTExplorer link.

### Expected Behavior

The "expression" flag should be set to false.

### Possible Solution

It sounds like it would be enough to add a `path.set("expression", false)`  in https://github.com/babel/babel/blob/master/packages/babel-traverse/src/path/conversion.js#L26 if the node type is an ArrowFunctionExpression? I'm not sure if there are other cases like this in the AST spec.

**Comment by loganfsmyth** [comment]
What a strange flag. I didn't even know that existed, and my vote would just be to remove it. If you need to know what type of body the function has, just check `t.isBlockStatement(fn.body)`.

**Comment by hansonw** [comment]
It is part of the spec after all :) https://github.com/babel/babylon/blob/master/ast/spec.md#arrowfunctionexpression
The only reason I care is because istanbul's instrumenter relies on it: https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/src/visitor.js#L346

I can follow up with a PR over there to stop using it I guess; that's easy enough :)

**Comment by loganfsmyth** [comment]
Yeah I agree that it's in the spec. Babel almost certainly just copied it from ESTree. It seems like a case where it's a nice-to-have if you have a static tree, but if you have to do transformations like we do, it's a duplicate data source that always needs to be in sync with `fn.body`, and if that's the case, why have it in the first place.

If you want a fix for the instrumenter case I'd recommend making a PR there, because we're trying to stay focused on 7.x, and it's unlikely that we'd get a fix out in 6.x either way. Given that, I'll probably file a bug to just remove that flag in 7.x since it's just annoying duplication of state.

**Comment by hansonw** [comment]
Sounds good to me. Thank you for the quick response! :)
