### ISSUE TITLE
Issue with loose mode export { x } from 'x';

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6805]
From https://github.com/babel/babel/pull/6742, tried to upgrade Babel itself

https://github.com/babel/babel/blob/23626fc6ad0cbeb1a6141c2b0c9d6d3f15e478ab/packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop-loose/export-from-2/expected.js

```
exports.foo = _foo.foo;
var _foo = require("foo");
```
since it gets required after @existentialism

**Comment by loganfsmyth** [comment]
Marking as a good first issue because this should be a self-contained fix to `helper-module-transforms`.

This but is because of a change in semantics that loose move introduces. With non-loose, we explicitly define all named exports up front so that the names all exist on the `exports` object before any of the `require()` calls run. This was fine on non-loose because
```
Object.defineProperty(exports, 'foo', {
  get(){ return _foo.foo; };
  // ...
});
var _foo = require("foo");
```
doesn't actually access `_foo.foo` at declaration time. Since loose mode removes the wrapper, that breaks.

What we probably want for a fix here is to make it
```
exports.foo = undefined;

var _foo = require("foo");
exports.foo = _foo.foo;
```

There's similar logic in there already for other types of exports, so hopefully adding logic for this case should be reasonable.

**Comment by daft300punk** [comment]
I'll be working on this.

**Comment by existentialism** [comment]
@daft300punk thanks! join us in slack if you have any questions!

**Comment by existentialism** [comment]
@daft300punk friendly ping! any updates?
