### ISSUE TITLE
@babel/core required even when using old babel-core (7.0.0-beta.3)

### ISSUE THREAD

**Issue by mcongy** [babel/babel#6824]
Hello,

Today I came to work, reinstalled my dependencies, and ran into a strange problem.

I'm using older beta-version of babel (7.0.0-beta.3). 
When trying to build my (react) project as usual, I get this error:
`Cannot find module '@babel/core'`

Seems like something is requiring the new version of babel-core, even tho I haven't installed any new library.
None of the libraries I'm using are using @babel/core directly.

I've absolutely no idea what to do. Anyone has a clue why suddenly babel started using @babel/core even tho I haven't made any change? I can't migrate to @babel/ packages, since I'm using some of the plugins/presets that aren't fully-compatibile with babel-7 (namely babel-plugin-direct-import and babel-preset-react-optimize).

Thanks

**Comment by exsilium** [comment]
Hi! @mcongy! I feel the pain... Seems this change was implemented in a disruptive manner. All the 7.0 betas of core and presets were moved to @babel namespace. And as you mention, not all the deps are requiring the core in the new manner (including grunt-babel 7.0).

Basically, as you are requiring babel-core of 7.0.0-betaX but it no longer can be satisfied in the global namespace, @babel/core is fetched instead.

I Ended up going back to ~6.26.0 and also moving the presets back to 6.x. Maybe this is an option for you as well?

Cheers! 🍻

**Comment by hzoo** [comment]
@mcongy @exsilium first off thanks for using the v7 betas 🙌!

A few comments:

Are you using this in production already? That is fine (I am as well), but I've mentioned a few times before and in general you should be pinning your dependencies with a lockfile and at least using exact versions. This means you shouldn't be doing `"babel-core": "^7.0.0-beta.0"` or anything like that because that would automatically get any beta we release. Because this is beta the next version may or may not have a breaking change that you are automatically opting into. It's not our intention for it to be compatible yet so not sure why that is surprising?

> Anyone has a clue why suddenly babel started using @babel/core even tho I haven't made any change

You haven't provided enough information (especially for using a beta release) so I have no way to debug or know how to help you other than guessing? We moved to scoped packages in `7.0.0-beta.4` and have always used pinned dependencies like in https://github.com/babel/babel/blob/v7.0.0-beta.4/packages/babel-core/package.json.

You should ping the plugin authors that v7 is coming out so they can make a patch version that is backwards compatible with v6 and v7.

> Seems this change was implemented in a disruptive manner

It's a name change, meaning it's unrelated to semver and totally opt-in. We have been planning on using scoped packages for a whole year and not sure when else we would do this? I honestly don't see what else we need to do doing because this is a beta, and we also have limited time to figure out how to make it easy to transition between betas (this is the time period where it's fine to do so). Going to add more info in here: https://github.com/babel/website/pull/1453

**Comment by mcongy** [comment]
Thank you for your answers. A college of mine deleted the package.lock file, and after re-installing dependencies I apparently installed the 7.0.0-beta.4 which uses scoped @babel packages.

I guess I'm gonna be using the exact package versions (e.g. 7.0.0-beta.3, not ^7.0.0-beta.3) when using beta versions.

Problem solved. Thank you for ur time and the awesom babel-7 which dropped 80kB of polyfills from my bundle ;)

You can close this.

**Comment by exsilium** [comment]
> It's a name change, meaning it's unrelated to semver and totally opt-in. We have been planning on using scoped packages for a whole year and not sure when else we would do this?

Makes sense. I ran into the issue because I needed to update my lock. I was using babel-core 7.0 beta but then I checked npm and the 7.0 versions had moved to @babel and the previous babel-core latest seems all 6.x.

**Comment by hzoo** [comment]
> "An associate of mine deleted the package.lock file, and after re-installing dependencies"

Ah that makes sense! This shouldn't be an issue on scoped packages because we will publish to the latest dist tag only and keep the pinnedDeps before release

Cool thanks everyone.

**Comment by loganfsmyth** [comment]
Sorry for the confusion here. We've made other breaking changes between beta versions before, and may well again, so we decided it was acceptable to introduce this change in a breaking way as well. We absolutely assume our users are either setting exact versions, or are using lockfiles.

For this specific case, I can elaborate. We published a new `7.0.0-bridge.0` package that links to `@babel/core` to allow packages that have a peerDependency on `babel-core` to keep it by using it. See https://github.com/babel/babel-bridge for mode details. Users using a general `^7.0.0-beta.3` will end up with the bridge package because the bridge package has higher priority than the beta in npm's sorting of packages, which I think is a good thing, but does end up being a little painful if you use it by mistake.
