### ISSUE TITLE
"useBuiltIns" option in env preset is confusing compared to spread plugin

### ISSUE THREAD

**Issue by rtsao** [babel/babel#6830]
For context, this is how the object spread plugin currently works:

https://babeljs.io/docs/plugins/transform-object-rest-spread/#optionsuse-built-ins

| useBuiltIns | Result                        |
|-------------|-------------------------------|
| false       | `extends` helper (don't use the built-in)   |
| true        | `Object.assign` (use the built-in) |

This makes sense. Setting `useBuiltIns: true` means we turn off adding extra code in favor of the built-in functionality.

### Expected Behavior
**How the env preset should work**
I think using a different name for this option might lead to less confusion, for example `polyfills`

| polyfills (or some other name) | Result                                                |
|----------|-------------------------------------------------------|
| usage    | Add individual polyfills in every file based on usage |
| entry    | Replace top-level polyfill with individual polyfills  |
| false    | Never apply polyfills                                 |

### Current Behavior

**How the env preset currently works**

| useBuiltIns | Result                                                |
|----------|-------------------------------------------------------|
| usage    | Add individual polyfills in every file based on usage |
| entry    | Replace top-level polyfill with individual polyfills  |
| false    | Never apply polyfills                                 |

In a sense, this is the opposite of how `useBuiltIns` works in the spread plugin, where `false` means adding the `extend` ponyfill.

### Possible Solution
- Use a different name for `useBuiltIns` option in the env preset?

**Comment by yavorsky** [comment]
@rtsao Good point! Since it's beta, we have time to change the API painlessly.

> Use a different name for useBuiltIns option in the env preset

We can take `usePolyfills` to fit the current logic or `polyfill`, like we [have for runtime transform](https://babeljs.io/docs/plugins/transform-runtime/#optionspolyfill).

If we don't want to change the API for preset-env, the additional possible solution could be reverse logic for `transform-object-rest-spread`. Then we would accept, that builtIn, linguistically, is just a synonym for polyfill. (According to the current plugin's state, it's obviously antonym).

**Comment by hzoo** [comment]
I can see how `useBuiltIns: false` is "confusing" but you would never specify that as an option?

It's not that it applies polyfills or not because it expects you to add an import babel-polyfill statement in your code to do anything. If you do false and don't include the polyfill then it won't do anything, it's the same behavior as omitting it entirely (undefined) or an "entry" without a polyfill import.

I wanted to just make entry the default since it won't do anything if you don't specify import babel-polyfill anyway but don't know how to force that without adding a peerDependency which I'm not sure we want

**Comment by the-spyke** [comment]
Super confusing indeed. It should be named like `applyToBabelPolyfill`

**Comment by ishitatsuyuki** [comment]
We should surely remove/rename this option while we're still in beta. There is an option named `useBuiltIns` in the stage-x presets which **assumes the polyfill installed**, unlike the "smart" polyfilling in env preset. Can you raise the priority?

**Comment by existentialism** [comment]
@billyjanitsch wrt to object rest spread, we'd probably just turn it on since we know that `Object.assign` exists (whether natively or via polyfill)?

**Comment by ishitatsuyuki** [comment]
@hzoo Can you provide an update on this? The whole point of this issue is to align the behaviour of env preset to other transform plugins. To provide the "polyfill based on usage" functionality, we can just use a different option name.

**Comment by rtsao** [comment]
As a follow up to this, I've created a comprehensive proposal regarding configuration of the env preset: https://github.com/babel/babel/issues/8195. One area addressed in the proposal is polyfilling.

For those interested, please leave feedback!

**Comment by nicolo-ribaudo** [comment]
You can now use one package from https://github.com/babel/babel-polyfills instead of the `useBuiltIns` option, to make it clear that it's about polyfills.
