### ISSUE TITLE
Bug - SyntaxError on Object rest spread with node 8.9.1

### ISSUE THREAD

**Issue by rgranger** [babel/babel#6832]
Choose one: is this a bug report or feature request?

Bug.

NodeJS 8.9.1 is now the current LTS. Thus I tried to remove every babel plugins I was previously using on NodeJS 6.9.1 and that are no longer needed : http://node.green/

When I run this code with node, it works as expected. When I use babel-register with 0 plugin, I got a syntaxError.

### Input Code

```js
// test-file.js
const objA = {
  foo: 'foo',
  bar: 'bar'
}

const objB = { ...objA }

console.log('objB.foo', objB.foo)
```

```js
// main.js
require('babel-register')
require('./test-file')
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": [
  ]
}
```

### Expected Behavior

```shell
node main.js // should work like running 'node test-file.js'
```

### Current Behavior

```shell
node test-file.js // works
node main.js // throws SyntaxError
```

### Context

Node 8.9.1 is now the active LTS. I expected to be able to use the fewer babel-plugins possible.
Since Object rest spread works natively on Node 8.9.1, I don't want to include the babel-plugin-transform-object-rest-spread.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.32
| node             | 8.9.1
| npm              | 4.6.1
| Operating System | Windows 7

**Comment by existentialism** [comment]
@rgranger you will need to include @babel/syntax-object-rest-spread (which the transform automatically enables) so that our parser will be able to parse the code.

As a sidenote, this is automatically handled for you if you use @babel/preset-env with the node target and the `shippedProposals` option!

**Comment by hzoo** [comment]
> I expected to be able to use the fewer babel-plugins possible.

If you don't specify anything then it won't do anything either? We can't make the default contain object rest spread because it's not native to node 8 and below. Might be another reason for making https://twitter.com/left_pad/status/930215775088103424. Also the point of having preset-env is so that you don't have to manually remove plugins in the first place? It does it for you.

**Comment by rgranger** [comment]
@existentialism Thanks for the @babel/syntax-object-rest-spread !

Can you tell me if @babel/preset-env is really stable ? It is marked as experimental, and i'm currently using babel-core v6.x. I'll have to wait for babel-core 7.x to be marked stable before I can upgrade and use @babel/preset-env ?

**Comment by existentialism** [comment]
Oh, I thought you were on babel@7.0.0-beta.32 since that's what the "Your Environment" entry states :)

FWIW, @babel/preset-env comes with the same caveats as `@babel/core` et all: that things may continue to churn/change during the remaining betas; and it turns out @hzoo and I just picked a poor name for the folder :)
