### ISSUE TITLE
Transpile specified folder

### ISSUE THREAD

**Issue by Alecell** [babel/babel#6837]
I have the .babelrc in a vendor folder, but I want to transpile some files that is outside that folder, I don't find any solution to this without moving the .bablerc to the parent folder. Is there anyway to do this by .babelrc?

**Comment by nicolo-ribaudo** [comment]
Does the `--config-file` option work for your use case?
e.g.
```
babel --config-file ../vendor/.babelrc ...
```

**Comment by loganfsmyth** [comment]
We're working make things like this a little more configurable in 7.x, but things haven't quite landed yet. That said, it is also hard to say confidently without a clearer example of your directory structure.

Going to close this though since I think we're already on the right track for fixes in the future.
