### ISSUE TITLE
[bug] babel-node uses polyfills of JSON.stringify with ES6 Set support

### ISSUE THREAD

**Issue by jzastrow** [babel/babel#6870]
### Input Code
babel-node uses different (maybe from polyfil) impl of JSON.stringify with support for ES6 Sets. 
This looks nice first, but is actually wrong and won't work on the server.

```js
console.log(JSON.stringify({foo: new Set(['a', 'b'])}));
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
	[
	  "env",
	  {
		"targets": {
		  "node": 8
		}
	  }
	]
  ],
}
```

### Expected Behavior
When running the above code in plain node or in a browser it prints:
```
{"foo":{}}
```
### Current Behavior
Execution with babel-node gives:
```
{"foo":["a","b"]}
```
This looks good first locally, but results on the server in very subtle bugs as:

```
JSON.stringify({foo:new Set([1,2,3])}) === JSON.stringify({foo:new Set([4,5,6])}) 
```
is `true` on the server and `false` locally.

### Possible Solution
It is actually wrong to use JSON.stringify on ES6 Sets/Maps, so do not add such a feature in babel.

### Context
Using babel-node for local development and transpile with babel to run server with nodejs 8

### Your Environment
Node 8.9.0
Babel 6.5 / 7-beta (both versions are affected)

**Comment by yavorsky** [comment]
Thanks for the issue!

Seems like it happens because of we are evaluating targeted script in the context of `_babel-node`, which [requires `@babel/polyfill`](https://github.com/babel/babel/blob/master/packages/babel-node/src/_babel-node.js#L8)
and as a result, it's overriding Map/Set `toJSON` instance methods:
https://github.com/zloirock/core-js/blob/master/modules/_collection-to-json.js
https://github.com/zloirock/core-js/blob/master/modules/es7.set.to-json.js

So, we need at least to use standalone methods, instead of override prototypes for runtime stuff like that.

**Comment by loganfsmyth** [comment]
@zloirock Will `core-js@3` still have that `toJSON` implementation?

**Comment by zloirock** [comment]
@loganfsmyth nope https://github.com/zloirock/core-js/pull/325/commits/bb11e5d260810e36fa92d71ac676bdc421dbb692

**Comment by loganfsmyth** [comment]
Perfect, thanks!

**Comment by zloirock** [comment]
Seems should be closed since `@babel/polyfill` is deprecated in favor of `core-js` and this polyfill was removed from `core-js@3`.
