### ISSUE TITLE
Option for auxiliary comment within UMD

### ISSUE THREAD

**Issue by onury** [babel/babel#6901]
Choose one: is this a bug report or feature request?
**Feature request**

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "env": {
    "development": {
      "auxiliaryCommentBefore": "istanbul ignore next",     // <———
      "presets": [
        "@babel/preset-env"
      ],
      "plugins": [
        "@babel/plugin-transform-modules-umd"               // UMD
      ]
    }
  }
}
```

### Expected Behavior

What I need to achieve is, make istanbul ignore UMD declaration for test coverage.
As noted in istanbul docs [here](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md#ignore-a-umd-wrapper) the ignore comment needs to be placed before the `if` statement:
```js
(function (global, factory) {
  /* istanbul ignore next */                             // <———— here
  if (typeof define === "function" && define.amd) {
    define([], factory);
  } else if (typeof exports !== "undefined") {
    factory();
  } else {
    var mod = {
      exports: {}
    };
    factory();
    global.index = mod.exports;
  }
})(this, function () {
  // user code here...
});
```

### Current Behavior

`auxiliaryCommentBefore` places the comment at the very top which is expected.  But with this option, we cannot make istanbul ignore the `if` block. (Both `istanbul ignore next` and `istanbul ignore if` will not work).
```js
/* istanbul ignore next */
(function (global, factory) {
  if (typeof define === "function" && define.amd) {
    define([], factory);
...
```
### Possible Solution

An option like `auxiliaryCommentInFactory` could be added that would place the comment right after `(function (global, factory) {` line.

### Context

What I need to achieve is, make istanbul ignore UMD declaration for test coverage. To do this, you need to add a comment (`/* istanbul ignore next */`) to the generated/transformed code. So it has to be done through babel. Existing options (`auxiliaryCommentBefore` and `auxiliaryCommentAfter`) cannot achieve this.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.32
| node             | 6.11.2
| yarn              | 1.3.2
| Operating System | macOS 10.13.1

**Comment by loganfsmyth** [comment]
If you need coverage, you'd be much better off using https://github.com/istanbuljs/babel-plugin-istanbul. `auxiliaryCommentBefore` is extremely lacking, as you're seeing.

**Comment by onury** [comment]
@loganfsmyth, I already use [Jest](https://facebook.github.io/jest) for tests and coverage which already uses istanbul under the hood.

Besides, I don't see a way to ignore UMD with [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) either.

**Comment by loganfsmyth** [comment]
Istanbul should already ignore the UMD stuff because the plugin will inject its annotations into the file before the UMD headers are added by `@babel/plugin-transform-modules-umd`.

**Comment by onury** [comment]
Well, tried babel-plugin-istanbul and it doesn't ignore it:

<img width="568" alt="coverage" src="https://user-images.githubusercontent.com/3665990/33225629-d07de86c-d183-11e7-8713-b46556ed376b.png">

> `auxiliaryCommentBefore` is extremely lacking, as you're seeing.

It does what's expected. There is no problem with `auxiliaryCommentBefore`. 
I meant to say an additional option for this kind of thing would be very handy.

`ignore` comment should be injected to the generated code. There's no way of doing it without babel config (since we cannot touch a generated file).

**Comment by loganfsmyth** [comment]
> It does what's expected. There is no problem with `auxiliaryCommentBefore`.

I promise that's not the case once you know the implementation, though I certainly which that weren't the case. `auxiliaryCommentBefore` is a standalone feature that essentially guesses where new code might have been injected. The UMD plugin isn't deciding to put the `/* istanbul ignore next */` in the wrong place, it literally doesn't even know the comment exists. The `auxiliaryCommentBefore` injection logic is seeing "oh some new code got added here, I should put the comment before it" and that is that. There is no clean way for us to fix this because the entire architecture that drives `auxiliaryCommentBefore` and its approach to deciding where to put comments is broken by design as far as I'm concerned. I'd remove it entirely in a perfect world, because it's never going to behave the way people expect it to. I've essentially just left it in so that people who have already been using it as a good-enough solution don't get broken for no reason.

I don't know a ton about how Jest does things. I'm surprised the output code (with the UMD header), rather than the input core (with ES6 modules) is even showing up in your coverage report to begin with. Generally the logic you want covered is the code you wrote, not the code Babel injected. The `babel-plugin-istanbul` config usually runs very early on in the process and essentially injects coverage reporting logic into your file, based on your actual code, so I'd probably expect _none_ of the UMD header to have coverage , but I'd expect the coverage processing tools to have taken that into account based on the sourcemap and original sourcecode.

**Comment by onury** [comment]
Fair enough @loganfsmyth. 
Well, Jest has its own [issues with babel](https://github.com/facebook/jest/issues/4954). Tooling should ease things but sometimes it does the opposite...

**Comment by loganfsmyth** [comment]
Per https://github.com/facebook/jest/issues/4954#issuecomment-346910205, if you're building with Babel _first_ then that is likely why your coverage is getting confused by the UMD. Jest will be running `babel-plugin-istanbul` automatically as part of its instrumentation process, which means it will run _after_ you've manually run and injected the UMD wrapper. If you were letting Jest run babel normally, you'd likely be better much better coverage reports.

**Comment by onury** [comment]
Thanks!! You've been very helpful. I'll also try that.

Closing this now.
