### ISSUE TITLE
reduce code generated of plugin-proposal-decorators 

### ISSUE THREAD

**Issue by simonjoom** [babel/babel#6965]
plugin-proposal-decorators create for each component using decorator same function template:

applyDecoratedDescriptor
and 
initDefineProp

so the code ended is much more bigger, 
i propose to create only this once in global what do you think?
(It s what i did inside babelHelper ...)

same this plugins use the function ensureInitializerWarning who create no useful bit for each component too:
function NAME(descriptor, context){ throw new Error(    'Decorating class property failed. Please ensure that proposal-class-properties is enabled and set to use loose mode.  To use proposal-class-properties in spec mode with decorators, wait for he next major version of decorators in stage 2

will be better to add it in global too ...

**Comment by xtuc** [comment]
Could you please use our [ISSUE_TEMPLATE](https://raw.githubusercontent.com/babel/babel/master/.github/ISSUE_TEMPLATE.md)?

**Comment by simonjoom** [comment]
It's not really an issue, but an improvement to reduce bundle code result.

The things are very simple to understand with what i explained.

**Comment by xtuc** [comment]
This is an issue to me because we could do something better than we currently do. 

In the template there is an input code and your  possible proposition, this would help us better understand your issue.

**Comment by simonjoom** [comment]
I give more info:

here my babel config
```
"babelproduction": {
    "presets": [
      [
        "es2015",
        {
          "modules": false,
          "loose": true
        }
      ],
      "react",
      "flow"
    ],
    "plugins": [
      "babel-plugin-root-import",
      "babel-plugin-syntax-dynamic-import",
      "babel-plugin-transform-async-to-generator",
      "babel-plugin-proposal-object-rest-spread",
      "babel-plugin-proposal-optional-catch-binding",
      "babel-plugin-proposal-unicode-property-regex",
      "babel-plugin-transform-exponentiation-operator",
      "babel-plugin-proposal-decorators",
      [
        "proposal-class-properties",
        {
          "loose": true
        }
      ],
      "proposal-export-namespace-from",
      "proposal-export-default-from",
      "babel-plugin-external-helpers",
      "babel-plugin-dual-import"
    ]
```

**Comment by simonjoom** [comment]
if i do something like
@inject("appstate") @observer
class Component1 extends Component {
//blabla blab
}

@inject("appstate") @observer
class Component2 extends Component {
//blabla blab
}


Babel insert 
applyDecoratedDescriptor template
initDefineProp template
and the ensureInitializerWarning template in each component. 

So it will be better to add only one time on global (as the function of babelHelpers) 

hope it will help more

**Comment by nicolo-ribaudo** [comment]
The correct fix for this bug is moving the decorators helpers (https://github.com/babel/babel/blob/6fe7f77eb4ae08f65290b51d03a740e2ae84d27b/packages/babel-plugin-proposal-decorators/src/index.js#L29-L83) to the `babel-helpers` package.

**Comment by simonjoom** [comment]
yes i guess

**Comment by perinikhil** [comment]
Hi guys,
I would like to make a contribution here. Could someone help me with what i'm supposed to do to resolve this issue?

**Comment by xtuc** [comment]
@perinikhil as far as I understand, since the "runtime" for decorator is in the plugin it will be injected for each run. We need to move them into our Babel helpers because we can dedupe them.

Maybe @nicolo-ribaudo can tell you more about that.

**Comment by nicolo-ribaudo** [comment]
@perinikhil As you can see in the code included in my previous comment, in the `decorators` plugin are defined some "helpers".

Babel inserts this kind of helpers for many features, for example classes (As you can see in the [repl](http://babeljs.io/repl#?babili=false&browsers=ie%2010&build=&builtIns=true&code_lz=MYGwhgzhAECC0G8C-Q&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.0.0-beta.4), it injects the `_classCallCheck` and `_instanceof` functions).
The helpers injected for decorators look similar ([repl](http://babeljs.io/repl#?babili=false&browsers=ie%2010&build=&builtIns=true&code_lz=MYGwhgzhAECC0G8BQ1oAEAmBTYB7aAtlgC4AWuGAFAJSIC-SdQA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=stage-1&prettier=false&targets=&version=7.0.0-beta.4)), but there is a difference: the helpers used by the classes plugin can be "removed" using `babel-plugin-transform-runtime` or `babel-plugin-external-helpers`. It works because they aren't defined directly in the plugin, but in the [`babel-helpers` package](https://github.com/babel/babel/tree/master/packages/babel-helpers).

To make these two plugins correctly work with `babel-plugin-proposal-decorators`, you need to remove the helpers from the plugin itself and add then to `babel-helpers/src/helpers.js`.

If you need any help, ping me on slack (https://babeljs.slack.com)

**Comment by simonjoom** [comment]
Me i resolved this and move these helper by hand in global in my code .. 
waiting for the correct update with babelhelpers

**Comment by perinikhil** [comment]
So i'm guessing this issue has already been claimed? :(
Anything else i could do as my first PR then guys? :D

**Comment by nicolo-ribaudo** [comment]
@perinikhil I think that @simonjoom only worked around this issue by manually editing Babel's output

**Comment by simonjoom** [comment]
yes it is what i did is hacky

**Comment by nicolo-ribaudo** [comment]
@perinikhil Then you can work on this ☺️

**Comment by perinikhil** [comment]
@nicolo-ribaudo 
can you please add me to the babeljs slack channel?
My email id is - peri.nikhil10@gmail.com

**Comment by xtuc** [comment]
@perinikhil sent

**Comment by perinikhil** [comment]
@xtuc I need some help while moving the functions to `babel-helpers/src/helpers.js` as they cannot contain any placeholders...simply moving them won't work 😮

**Comment by nicolo-ribaudo** [comment]
Since the only placeholder used is the function name, you can hardcode it (like is is done for the other helpers)

**Comment by simonjoom** [comment]
i tried to compile the last babel  7 code, this update break the compilation. 
There is something to test ...
