### ISSUE TITLE
babel-preset-env: generated polyfill output 

### ISSUE THREAD

**Issue by Alphapage** [babel/babel#6990]
Hello,

I'm trying babel-preset-env and I like the concept.

Previously, I bundled my js files by adding babel-`polyfill.min.js` at the beginning of the bundle, then I added all the transformed files using `babel-preset-es2015`.
With babel-preset-env, it doesn't seem possible to add only the necessary polyfills.

Is there a way to get the necessary polyfills sources from `babel-core` to be able to replace the `polyfill.min.js` or should I have to always embed the whole polyfill ? (I don't use webpack)

Thank you in advance for your help.

**Comment by hzoo** [comment]
Awesome, thanks for trying it out.

> Is there a way to get the necessary polyfills sources from babel-core

I think you may be confused by how to use the polyfill?

We totally do have a way to add necessary polyfills: https://github.com/babel/babel-preset-env/tree/1.x#usebuiltins i'l link you to 1.x version since you are probably using babel v6. You need to do a import/require though and thus you will need to use a bundler like webpack.
