### ISSUE TITLE
[TypeScript] "assert and assign" syntax fails to compile

### ISSUE THREAD

**Issue by clarkdave** [babel/babel#7068]
Choose one: bug report

When performing an assertion and assignment at the same time, which is supported by the TypeScript compiler, the Babel TypeScript transformer throws an error.

### Input Code

```typescript
interface ResponseBody {
  name: string
  age: number
}

let response
;(response as ResponseBody) = {
  name: 'Alice',
  age: 23,
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```json
{
  "plugins": ["@babel/plugin-transform-typescript"]
}
```

### Expected Behavior

Running the TypeScript compiler against the above input code yields the following output, and it seems reasonable to expect Babel to output something similar.

```js
var response;
response = {
    name: 'Alice',
    age: 23
};
```

### Current Behavior

Compilation fails with an `Invalid left-hand side in assignment expression` error:

```
./test.ts: Invalid left-hand side in assignment expression (7:2)
   5 |
   6 | let response
>  7 | ;(response as ResponseBody) = {
     |   ^
   8 |   name: 'Alice',
   9 |   age: 23,
  10 | }
error Command failed with exit code 1.
```

### Possible Solution

It should be supported by the transformer, or listed as an unsupported feature in the documentation and a more appropriate error can be thrown (as with `import = is not supported`) during compilation.

### Context

This syntax can be useful with frameworks like `koa` where you set a body like so:

```js
ctx.body = { name: 'Alice' }
```

With the "assert and assign" syntax this can be:

```typescript
;(ctx.body as ResponseBody) = { name: 'Alice' }
```

### Your Environment

| software                    | version(s)
| ----------------            | -------
| Babel                       | 7.0.0-beta.35
| plugin-transform-typescript | 7.0.0-beta.35
| typescript                  | 2.6.2
| node                        | 9.2.1
| npm                         | 5.5.1
| Operating System            | macOS 10.12.6

**Comment by nicolo-ribaudo** [comment]
Thank you for testing Babel's typescript implementation!

---

If anyone wants to take a look at this issue, here are the parts of Babylon (Babel's parser) which check the left node of an assignment expression:
- In the `parseAssignmentExpression`, you can see that there is a call to the `checkLVal` method.
 https://github.com/babel/babel/blob/5f8a1a2613eccc81a2b06e5758b003ce830f0171/packages/babylon/src/parser/expression.js#L162
 It is defined in https://github.com/babel/babel/blob/master/packages/babylon/src/parser/lval.js.
- `checkLval` checks that the left node is a node that can be assigned to.
  e.g. in `(NODE as Type)` it should `checkLVal` `NODE`.

Since the typescript grammar is defined as an internal Babylon plugin, that methods shouldn't be modified directly, but it should be overwritten in https://github.com/babel/babel/blob/master/packages/babylon/src/plugins/typescript.js to work with `TSAsExpression`

Before starting working on this bug, please leve a comment here! Also, if you need any additional help, feel free to contact me on [slack](https://slack.babeljs.io/)

**Comment by maaz93** [comment]
@nicolo-ribaudo I'd like to take this up!

**Comment by existentialism** [comment]
@maaz93 go for it!
