### ISSUE TITLE
[@babel/generator] Why to keep single quotes behind private APIs?

### ISSUE THREAD

**Issue by avesus** [babel/babel#7138]
https://github.com/babel/babel/blob/3956b3ee0e92f24890155a6734c5d2658afe2843/packages/babel-generator/src/index.js#L49

**Comment by loganfsmyth** [comment]
We historically made any guarantees about formatting in the output code from Babel beyond that it execute the way the spec dictations, and quotes were kind of an odd one where we actually exposed it. If specific formatting is important for you, you could for instance consider running Prettier on the code after it compiled.

**Comment by loganfsmyth** [comment]
Made a quick typo there haha, fixed.

**Comment by hzoo** [comment]
Reference issue I made earlier https://github.com/babel/babel/issues/5139, we decided to remove formatting options because it's a compiled code and didn't seem necessary? It didn't make sense to be a formatter when there are actual options for that (ideally we could combine the codebases though if that is possible)

**Comment by xtuc** [comment]
@avesus what is your use case?

Note that you can use https://github.com/benjamn/recast with Babel to preserve original formatting.
