### ISSUE TITLE
Transform calls to `babel-template` at compile time

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#7171]
Templates take away from the developer the responisbility of manually cloning nodes nodes, so they should be encouraged.
They are slower than using the builders provided by `babel-types`, so we could make a plugin that transforms them.

e.g.
```js
// Input
const buildEnumAssignment = template(`
  ID[ID[NAME] = VALUE] = NAME;
`);

// Output
const buildEnumAssignment = ({ ID, NAME, VALUE }) =>
  t.expressionStatement(
    t.assignmentExpression(
      "=",
      t.memberExpression(
        ID,
        t.assignmentExpression(
          "=",
          t.memberExpression(t.cloneNode(ID), NAME, true)
          VALUE
        ),
        true
      ),
      t.cloneNode(NAME)
    )
  );
```

I don't know if this is actually possible :thinking:

**Comment by loganfsmyth** [comment]
I think I'd want to see some benchmarks to see how much of an improvement this would actually be. In Babel 6 it was definitely slower because we re-traversed each template every time a template function was called, but in Babel 7 we only traverse once up front to decide what to replace, and the only time spent after that is cloning the AST and doing the replacement, which shouldn't be _too_ much slower than using `t.XXX` directly, I'd hope.

**Comment by nicolo-ribaudo** [comment]
Closing since in v7 templates are cached anyway.
