### ISSUE TITLE
undefined is compiled as function name by using template literal as method name.

### ISSUE THREAD

**Issue by sixwinds** [babel/babel#7199]
## BUG REPORT

As metioned on the title I give an example:

```javascript
var methodName = 'test';
var json = {
  [`${methodName}`]: function (){
    
  }
}
```
is compiled to following code:
```javascript
var methodName = 'test';
var json = _defineProperty({}, '' + methodName, function undefined() {}); // function name is undefined

```

Commonly it's ok, but if I use object deconstruction in method, the compiling result will cause undefined overwriting. For example:

### Current Behavior
```javascript
var methodName = 'test';
var json = {
  [`${methodName}`]: function (){
    let o = {};let {a='2'}=o
    console.log( a )
  }
}
```
is compiled to following code:
```javascript
var methodName = 'test';
var json = _defineProperty({}, '' + methodName, function undefined() {
  var o = {};var _o$a = o.a,
      a = _o$a === undefined ? '2' : _o$a; // undefined in this line is referred to current function

  console.log(a);
});

```

In above code, variable "a" will not be assigned to 2, because _o$a is not equal to "undefined", which is referred to current function; I think following Expected Behavior is proper behavior.

### Expected Behavior
```javascript
var methodName = 'test';
var json = _defineProperty({}, '' + methodName, function () { // no undefined name
  var o = {};var _o$a = o.a,
      a = _o$a === undefined ? '2' : _o$a; 

  console.log(a);
});

```

### Babel Configuration (.babelrc, package.json)
```js
{
  "presets": ["env","react"],
  "plugins": ["syntax-dynamic-import"]
}
```

```js
{
  "name": "dynamic-import",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "start": "webpack-dev-server --open"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "clean-webpack-plugin": "^0.1.17",
    "html-webpack-plugin": "^2.30.1",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.7"
  },
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}

```

### Environment
| software         | version(s)
| ---------------- | -------
| Babel            | see above Babel Configuration part ,
| node             | v8.9.1
| npm              | 5.5.1
| Operating System | macOS Sierra v10.12.6

**Comment by Axnyff** [comment]
It indeed looks like a bug with computed property and template literals, the name of the function cannot be computed properly.

[Reproduction in REPL](
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBAtgpgLgCwPYBMByJYQLwQORwwDOceA3AFCiQBWRSAdjhAN4UQQDaABiNwLoAuCADMArgwDGcAJaMIACgCUbDgF8KaoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)

I am very willing to try and fix this issue

**Comment by xtuc** [comment]
Yes that's a bug.

@Axnyff It seems that nobody is working on it, you can go ahead! Thanks

**Comment by Axnyff** [comment]
The problem seems to be that [that line](https://github.com/babel/babel/blob/master/packages/babel-helper-function-name/src/index.js#L171) is getting executed for TemplateLiterals however, they do not have a value so the function name is set to `undefined`.

I'm not sure what is the best way to fix it though
* Check on the condition before that the value is not undefined ( or is not falsy)
* Don't generate an id for a template literal by modifying [that condition](https://github.com/babel/babel/blob/master/packages/babel-helper-function-name/src/index.js#L137)

We could also try to compute a value for some computed template literals but it seems almost useless as it will only work when template literals could be changed with regular single quotes or double quotes.

I'm also not really sure where / how to add a test for that bug, should it go in the babel-helper-function-name or in the babel-plugin-transform-function-name ( in the first case I can't manage to make fixtures work)
