### ISSUE TITLE
concatenating files in self invoked anonymous functions

### ISSUE THREAD

**Issue by kasperpeulen** [babel/babel#7211]
At work we use the babel cli to compile multiple files into one output file. All our files look like this:

```js
(() => {
    // import
    const {sw} = window;

    class MyModel extends sw.model.Model {
        constructor() { }
    }

    // export 
    sw.model.MyModel = MyModel;
})();
```

I was wondering if it would be possible to tell babel somehow to wrap all concatenated files into self invoked anonymous functions. It would save boilerplate and indentations. I didn't see this option, so in that case, this would be a feature request.

**Comment by loganfsmyth** [comment]
You can explore using a plugin like https://github.com/TrySound/babel-plugin-iife-wrap if you're already doing this, but concatenation is really not a good idea in JS, since relying on file ordering can be problematic. Declarative imports and Webpack would alleviate your need for concatenation and be more in line with what most people do these days.
