### ISSUE TITLE
[Questions] Will Babel deprecate stage 0/1/2/3 proposals if they don't make it to stage 4?

### ISSUE THREAD

**Issue by rajaraodv** [babel/babel#7606]
Will Babel deprecate stage 0/1/2/3 proposals if they dont make it to stage 4? Is there a way to get warnings if we are using such proposals?

**Comment by xtuc** [comment]
I'm not sure to quite understand your question. Currently the `stage-*` presets includes the plugins that are in that particular stage, if they are going futher, we move them from the preset.

You won't get any warnings about that.

But we also recommend you relying directly on the proposal plugins themselves instead of the yearly presets because they are really hard to maintain for us and would likely break some code.

**Comment by jridgewell** [comment]
I believe he’s askin if we will deprecate proposals that become [inactive](https://github.com/tc39/proposals/blob/master/inactive-proposals.md) or withdrawn.

So far, we haven’t deprecated these proposals from the presets.

**Comment by hzoo** [comment]
We're planning on removing the Stage presets anyway since it inherently is unstable and no one really knows what's in it. https://github.com/babel/babel/issues/7770 so in the end it makes more sense to ask everyone to opt into each thing explicitly.
