### ISSUE TITLE
add source maps support for babel-node

### ISSUE THREAD

**Issue by magres** [babel/babel#7694]
--inspect-brk works well, but --source-maps not. It makes no sence to debug ES6 code on ES5 engine without source maps.

**Comment by edsrzf** [comment]
Hi, I'm just doing a bit of issue triage. Could you please describe what you're expecting, but not seeing? Perhaps with a reproduction case?

`@babel/node` does create source maps internally. It's built upon `@babel/register` which supports source maps via [node-source-map-supporrt](https://github.com/evanw/node-source-map-support). When an exception is thrown, the stack trace references the original source rather than the compiled source.
