### ISSUE TITLE
babel-node doesn't use .babelrc

### ISSUE THREAD

**Issue by caub** [babel/babel#7731]
From my project dir (where there is a `.babelrc` and my `package.json`):

## failing commands:
    npx babel-node index.spec.js (.babelrc not found, see outputs below)
    ./node_modules/.bin/babel-node index.spec.js
    npx babel-node --presets @babel/env index.spec.js (passing the preset name is not enough, it needs options)
    node_modules/.bin/babel-node --presets "/home/caub/dev/color-octree/node_modules/@babel/preset-env" /home/caub/dev/color-octree/index.spec.js (fails too)

## working commands:
    npx babel-node --presets ~/.npm-global/lib/node_modules/@babel/preset-env index.spec.js
    node_modules/.bin/babel-node --presets ~/.npm-global/lib/node_modules/@babel/preset-env index.spec.js

So it works when passing the preset-env located in my npm globals

I'd like to understand why this works fine (it uses successfully my `.babelrc`), but not when using locally (to the project) node_modules

### versions: 
```
"@babel/core": "^7.0.0-beta.44",
"@babel/node": "^7.0.0-beta.44",
"@babel/preset-env": "^7.0.0-beta.44",
```

[package.json](https://github.com/caub/color-octree/blob/424e661f2ec265fe5e3eb3a43b68ee110fb9c431/package.json)
[.babelrc](https://github.com/caub/color-octree/blob/424e661f2ec265fe5e3eb3a43b68ee110fb9c431/.babelrc)

### outputs
```
$ npx babel-node index.spec.js
/home/caub/dev/color-octree/index.spec.js:1
(function (exports, require, module, __filename, __dirname) { import assert from 'assert';
                                                              ^^^^^^

SyntaxError: Unexpected token import
```
```
$ npx babel-node --presets @babel/env index.spec.js
/home/caub/dev/color-octree/node_modules/@babel/core/lib/transformation/normalize-file.js:175
    throw err;
    ^

SyntaxError: /home/caub/dev/color-octree/index.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled (134:12):

  132 |     }
  133 |   });
> 134 |   return { ...best, d: minDist ** 0.5 };
      |            ^
  135 | };
  136 | 

Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.
```

Other infos, I have the same babel repos installed globally with npm:

```
$ ls ~/.npm-global/
bin  etc  lib  share
$ ls ~/.npm-global/lib/node_modules/
@babel  prettier
$ ls ~/.npm-global/lib/node_modules/@babel/
cli  core  node  preset-env

$ cat ~/.npmrc 
//registry.npmjs.org/:_authToken=xXXx
prefix=/home/caub/.npm-global

$ npm -v
5.8.0
$ node -v
v8.11.1
```

**Comment by caub** [comment]
@Tauka I'd say yes, because it's said that it behaves like babel-cli and babel-cli uses it https://babeljs.io/docs/usage/cli/

**Comment by Tauka** [comment]
@caub I'm not sure, it definitely says that is behaves like Node CLI, but there is no mention of `babel-cli`

**Comment by caub** [comment]
I think it's an issue since babel7 and scoped repos

    "test": "babel-node --presets env index.spec"

probably works (using babel6's babel-preset-env)

    "test": "babel-node --presets @babel/env index.spec"

doesn't work as shown in the travis output and in first comment

**Comment by loganfsmyth** [comment]
@caub Your `.babelrc` specifically says `"modules": false,`. Given that,

```
/home/caub/dev/color-octree/index.spec.js:1
(function (exports, require, module, __filename, __dirname) { import assert from 'assert';
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

is expected, because you've told it not to compile module syntax. If you remove `modules: false` from your config, it should work fine.

> I'd like to understand why this works fine (it uses successfully my .babelrc), but not when using locally (to the project) node_modules

Babel 7 has configuration merging logic that is different from Babel 6. Babel 6 made no effort to merge configs, and instead just used everything passed to it. That means that if you had one instance of `env` that set `modules: false`, and passed another one, the first would probably compile everything except modules, and the second would end up compiling the module syntax.

In Babel 7, instead of just using both, if the same preset is passed with different options, the later one overrides the options of the first one. That means that when you did `--presets @babel/env` in your CLI arguments, you're essentially enabling a version of `preset-env` with the default options, and since CLI arguments are higher priority, this essentially behaves like your config was _only_ that, meaning that `modules: false` is removed (avoiding that error), but so is `shippedProposals: true` (causing an error if you use shipped proposal syntax like object spread).

It "works" when you pass the globally-installed preset, because Babel has no way to know that the global one and the one local to your project are similar presets. Since it doesn't know, it can't merge them, meaning that you essentially end up with two instances of `preset-env` again, like you would have in Babel 6.

**Comment by loganfsmyth** [comment]
If you want to avoid putting it in the rollu[ config, you can set `envName: "rollup"` in the rollup Babel arguments, then you could do

```
{
  "presets": [
    [
      "@babel/env",
      {
        "shippedProposals": true,
        "targets": {
          "browsers": ["last 2 versions", "not ie > 0", "not Android > 0"],
          "node": "8.10"
        }
      }
    ]
  ],
  env: {
    rollup: {
      "presets": [
        [
          "@babel/env",
          {
            "modules": false,
            "shippedProposals": true,
            "targets": {
              "browsers": ["last 2 versions", "not ie > 0", "not Android > 0"],
              "node": "8.10"
            }
          }
        ]
      }
    }
  ]
}
```
