### ISSUE TITLE
[Bug Report] The `break;` statement inside `switch` breaks outside `for` loop in `@babel/preset-env`

### ISSUE THREAD

**Issue by ryerh** [babel/babel#7765]
Choose one: is this a bug report or feature request?
**This is a bug report**

### Input Code

```js
for (const item of [1, 2, 3, 4]) {
  console.log(">", item);

  switch (item) {
    case 2: {
      setTimeout(() => {
        console.log(">", item);
      }, 0);
      break;
    }
  }
}
```

### Babel/Babylon Configuration (.babelrc)

```js
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      }
    }]
  ]
}
```

### Expected Behavior

```bash
$ npm install @babel/core @babel/preset-env @babel/cli
$ ./node_modules/.bin/babel src.js -o compiled.js
$ node compiled.js
> 1
> 2
> 3
> 4
> 2
```

### Current Behavior

```bash
$ npm install @babel/core @babel/preset-env @babel/cli
$ ./node_modules/.bin/babel src.js -o compiled.js
$ node compiled.js
> 1
> 2
> 2
```

### Possible Solution

```js
"use strict";

var _arr = [1, 2, 3, 4];

var _loop = function _loop() {
  var item = _arr[_i];
  console.log(">", item);

  switch (item) {
    case 2:
      {
        setTimeout(function () {
          console.log(">", item);
        }, 0);
        return "break"; // <-- look at here !
      }
  }
};

for (var _i = 0; _i < _arr.length; _i++) {
  var _ret = _loop();

  if (_ret === "break") break; // <-- this breaks the `for` loop
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |   7.0.0-beta.44 (@babel/core 7.0.0-beta.44)
| Babylon          | 
| node             |  8.11.1
| npm              | 5.6.0
| Operating System | macOS 10.13.4 (17E199)

**Comment by franktopel** [comment]
This is still present in 7.0.1: https://github.com/babel/babel/issues/8709

**Comment by franktopel** [comment]
https://stackoverflow.com/questions/52310227/using-switch-case-the-break-inside-a-case-ends-the-outer-for-of-loop-iteration

**Comment by soletan** [comment]
Thanks @babel-bot, but as a matter of reputation management on behalf of BabelJS as a eligible backbone of today's Javascript development economy I'd rather would like to see an experienced collaborator taking care of this pretty essential flaw on transpiling basic Javascript. This issue isn't about supporting yet another fancy drafted feature for "ES2020+".

**Comment by nicolo-ribaudo** [comment]
I'm closing this issue in favor of #8709.

@soletan Do you want to open a PR?

**Comment by soletan** [comment]
Oh, nice, sarcasm. Let me adopt that: Do you want a BabelJS noob like me to fix **this** issue? Who's going to validate my PR if there is so little time to investigate this issue in the first place?

I was taking a glimpse in the file you've referenced in related issue. Even that part of BabelJS is pretty hard to read (which I admit might be due to the complexity of the issue's context). It's not that I'm demanding anything or urging anyone to do fix this by tomorrow. But this "just do it yourself" argument isn't helping either. I highly appreciate any collaboration and I've been interested in participating with own transformations for more than a year now, too. I see and really appreciate the huge amount of work invested in crearing BabelJS. But just like most other developers I haven't found the time to ever start studying BabelJS in more detail. I'm aware of most collaborators working on BabelJS during their spare time, too. I have to manage my worktime with 60-80 hours per week of commercially coding as well. And from an economic point of view I'd rather refactor my code for now to prevent this scenario than starting to participate in another open source project that would take days to understand the code, learn how to debug it, optimize ways to adjust it and implement assurances to validate my modifications ... time any "experienced collaborator" wouldn't have to spend anymore, but might start with analysing the issue itself right away. 

It took me an hour to find proof for BabelJS being the culprit. It took me minutes to fix the issue by refactoring my code. Case closed for me for now.it 

Eventually, I was stumbling over this GitHub issue and was confused about priorities as expressed by your bot, yes I know, it's a bot ... this issue affects basic code structures as supported by early versions of Javascript. It's not about supporting arrow functions, async/await, spread operators or some experimental stuff to become standard in 2019. And there seemed to be little progress for months. It looks like focusing on revising a car's media system to support Dolby surround sound while the wheels are tending to break loose.

**Comment by hzoo** [comment]
FYI @soletan I don't believe @nicolo-ribaudo was being sarcastic at all: https://github.com/babel/babel/issues/8709#issuecomment-425756284 in this he was providing some guidance. But yes we can try to look at the issue again (there are a lot of issues).

**Comment by soletan** [comment]
Ok, sorry for that. I might have misinterpreted his intentions without putting his comment into relation with his note in the referenced issue first.

**Comment by nicolo-ribaudo** [comment]
@soletan Sorry for being hasty in answering to you, I didn't mean to be sarcastic.

In these weeks I don't have access to a PC, so I'm trying to be as helpful as possible by offering my help to people who are trying to fix Babel bugs. If for some reason you (or anyone else) change your mind and decide to give a try and fix this issue, feel free to contact me on Slack.

Since this issue can be worked around I have not given it an high priority, but if it will still be unfixed when I'll have my PC back I will open a PR.
