### ISSUE TITLE
Should we remove Stage 0 - 2 presets, leaving only stage 3?

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#7770]
EDIT: PR at https://github.com/babel/babel/pull/8293
Stage-0 Readme: https://github.com/babel/babel/blob/48fe688a10d83486defdda223ac8d8d88057975d/packages/babel-preset-stage-0/README.md#babelpreset-stage-0

I think there's a reasonable argument to be made for stage 3 features being easily toggle-able, and by that point they are less likely to have major breaking changes, so I'm not as against it. We've had occasional conversations, but I think we should decide.

The stage < 3 presets are likely to change over time, making versioning difficult for them, and the community has grown to overactively enable stage-0 which I see as a dangerous precedent. To me it seems like we should remove these presets and instead use documentation to encourage people to enable experimental plugins on a case-by-case basis for the ones they _actually_ want, rather than just enabling everything for the sake of it.

I just want to make sure we have this conversation while we have the easy opportunity of dropping them before `7.x`.

**Comment by loganfsmyth** [comment]
I'll add that the new `decoratorsLegacy` option for `stage-2` to toggle decorator behavior is a good example of why they are annoying right now. If people aren't even using decorators in the first place, we still currently force them to choose which version of decorators they will want.

**Comment by nicolo-ribaudo** [comment]
Also, people shouldn't be required to know what stages are and which stage a particular feature is.

**Comment by ljharb** [comment]
Nobody should be using anything prior to stage 3 in production, so i think removing them would be excellent.

Those who want to help proposals advance, and experiment, can handle whatever configuration burden ends up being necessary.

**Comment by ljharb** [comment]
The year-specific presets match what's actually in the spec, and are still useful (altho using `env` is better).

**Comment by jridgewell** [comment]
We definitely should keep yearly presets, though you should be using `env`.

👍to killing Stage 0-2.

**Comment by NullDivision** [comment]
I understand the motivation behind this discussion, however I think what most of the people who are calling to remove stages 0 through 2 (most likely because of an inability to manage project specs) fail to realize is that stages are not code switches.

Stage-X is a preset. A group of plugins. They are not a part of Babel but of TC39 specs. All Babel is doing is creating a copy of plugins for that spec.

Removing the presets doesn't prevent usage of the underlying plugins. It prevents visibility. Say you remove stages 0-2. A startup comes along and feels like using non-standards plugins is fine. They will use it.

At least with stages it's managed by a trusted source instead of ~/npm/awesome-babel/babel-preset-latest

**Comment by loganfsmyth** [comment]
> Removing the presets doesn't prevent usage of the underlying plugins. It prevents visibility. Say you remove stages 0-2. A startup comes along and feels like using non-standards plugins is fine. They will use it.

That's pretty much the goal I'm aiming for. I want people to be able to use things, but I also want them to think about what they are using.

> At least with stages it's managed by a trusted source instead of ~/npm/awesome-babel/babel-preset-latest

If they want to use an alternative preset, they are totally free to do so. The fact that the name isn't `@babel/` and therefor a "trusted source" is specifically what I'd like, because if people want to use experimental proposals, it's much better if they opt into them specifically. If they want to use a random other preset, this makes it easier to see that it's not something we recommend.

**Comment by NullDivision** [comment]
But the issue is that developers are people. More precisely very lazy people. Meaning that they will always choose the shortest route. They'll use a plugin made by "that one guy on GitHub" instead. And if "that guy" makes a kitchen sink preset then that's what they'll use.

**Comment by loganfsmyth** [comment]
I don't necessarily see that as a problem.

**Comment by ljharb** [comment]
The issue is that basically nothing in stage 0 or 1 is anywhere *close* to being ready to experiment with, because it's still subject to massive change. The best thing is for the majority of devs to *not use these at all* until they're at least at stage 2; ideally at stage 3. Experimenting with early-stage things should be hard, because it's not intended for casual use.

**Comment by hzoo** [comment]
Oh I didn't update this thread but we are going to remove the Stage 0-2 presets. I'm planning on writing something long form to explain. It's not worth having them anymore or updating them (even with my previous fear of community driven one) because each one is breaking/unstable, and people don't understand what "stage-0' means as a string (no one even bothers to read the package.json) so opting in explicitly is better.

**Comment by robertrossmann** [comment]
As an external observer, I agree with removing the stage 0-2 presets as it would seem that using early-stage code features should really be done only after careful evaluation.

Aside from that, it sounds that the main motivation for removing these presets stems from the feeling that many developers do not bother to understand what they are bringing in to the language by installing a transform/plugin and that these new language features may change drastically in the future - in that case, I would recommend **adding a warning** when a stage 0-2 plugin is installed:

> WARNING: This plugin allows you to use syntax which may change drastically before being accepted as part of the language, use at your own risk ⚠️

Now the developer has been warned properly and they will have the opportunity to "think twice" before using this preset/plugin.

**Comment by hzoo** [comment]
Ok as of https://github.com/babel/babel/releases/tag/v7.0.0-beta.52, I ran `npm deprecate` on the yearly/stage presets. Will be annoying for anyone using `^` which we have recommended against while in pre-release but that's why we are just doing it for the latest release to give people time if you are already on v7. If someone wants all the plugins, or the equivalent, you are always able to make your own preset.

Can remove in the next release, https://github.com/babel/notes/blob/master/2018/2018-07/july-02.md#rc

**Comment by hzoo** [comment]
Made https://github.com/babel/babel/pull/8293

**Comment by crrobinson14** [comment]
Usage of a Babel preset now directs users to this thread. But this thread doesn't contain a specific instruction or recommendation to users on what to change. This is just going to invite "please guide me" requests into what seems to me to be a dev-oriented discussion.

Shouldn't the command line warning redirect to a page like https://new.babeljs.io/docs/en/next/v7-migration.html with some instructions added on how to make the change?

**Comment by hzoo** [comment]
Oh sorry about that, we didn't merge the PR yet but I added some links at the top of thread. The instructions are to replace the use of the preset and to opt in to using the specific proposals you desire to use, which we've listed in https://github.com/babel/babel/blob/48fe688a10d83486defdda223ac8d8d88057975d/packages/babel-preset-stage-0/README.md#babelpreset-stage-0.

**Comment by hzoo** [comment]
Ok after merging https://github.com/babel/babel-upgrade/pull/69, [`babel-upgrade`](https://github.com/babel/babel-upgrade#usage) should do this for you (although it copies every proposal in the Stage and should figure out if you want to use all of them).

And you may want to create a preset on your own instead of duplicating the same thing in each project as well.
