### ISSUE TITLE
Change the name to something that doesn't clash with another, well-established, open source project

### ISSUE THREAD

**Issue by sfermigier** [babel/babel#782]
Cf. <http://babel.pocoo.org/>.

**Comment by sebmck** [comment]
We had this discussion extensively before see #596 and #568. I highly doubt someone is going to confuse a JavaScript transpiler with a Python internationalisation library.

**Comment by sfermigier** [comment]
OK you've had this discussion, but have you had this discussion **with the people that are developing the Babel project** ? (If so, I don't see it documented in the two issues you are mentioning).

If yes, fine by me, sorry to have disturbed you.

If not, then that's rude.

**Comment by thejameskyle** [comment]
I understand your frustration @sfermigier, but as much as the Hacker news community likes to think name clashes are a huge issue, that's largely not true. The two projects exist not only independently but in entirely different spaces.

We did not reach out to the maintainers (who haven't touched their repo in over a year) because we did not think it mattered. 

It might also be good to note that we were not ready for this name change to happen, someone paying attention to @sebmck's activity on GitHub decided to start posting things in order to be first to break the news. He's now working his fastest at 2am to migrate everything, and I woke up super early this morning to help out.

**Comment by sfermigier** [comment]
"We did not reach out to the maintainers (who haven't touched their repo in over a year)"

-> The fact that the repo hasn't moved in one year doesn't mean that the project is dead. I just means that the project is done. I can assure you that a great many Python web projects *are* using the Babel project.
It's roughly the 50th most downloaded Python project, according to <https://python3wos.appspot.com/> .


"somebody decided to start posting things in order to be first to break the news"

-> Actually I got the news yesterday from a tweet by someone affiliated with the Pocoo project (home of the Babel project). So I guess someone there at least is pissed off by this.

**Comment by thejameskyle** [comment]
If we ever start touching python code we'll let you know.

**Comment by sebmck** [comment]
@sfermigier Sorry if you think this will cause any confusion between the two projects, I just think that the projects are far too different for there to be any possibility for confusion. It's hard to come up with a unique name, especially once that's memorable. "Babel" is pretty generic and obviously has roots in languages and translations so it's not farfetched for multiple projects to have the same name. There are 617 repos with the name babel on [GitHub](https://github.com/search?utf8=%E2%9C%93&q=babel) so we're hardly the first to choose it or at least a variation of it. Again, sorry for any potential confusion you think this may cause.

**Comment by billychappell** [comment]
@sebmck I'd just like to bring up one more point for this discussion: search results. When I Google Babel, none of the top results are in any way related to ANY programming project -- there's songs, historical facts, movies and TV shows.

As a result, people seeking information on your project are going to be forced to Google for "Babel JS" or "Babel javascript," etc. -- this is a problem you didn't run into with 6to5 and may not have considered yet.

Without a de facto standard, articles and tutorials/references on Babel will be fragmented across a myriad of search terms, making it more difficult to find community-based documentation or how-tos, whereas if either "JS", ".js" or some other identifier is included in the project name, you can be relatively sure that anything relating to this specific project will reference it as such and, thus, help consolidate all relevant information into a single search term, which keeps users from having to filter out irrelevant search results and/or using more than one search term to find fragmented results.

This isn't just an identification or aesthetic issue, it's a UX issue.

(PS. Sorry again for beating a dead horse! I just want to make sure all the impacts of the name choice are considered, and am more than willing to respect your decision whether this alters it or not.)

**Comment by sebmck** [comment]
@billychappel Choosing a name is extremely hard, I think #596 is a testament to that :stuck_out_tongue_winking_eye: Picking one that is also relevant to the project instead of a randomly chosen name even moreso. The two names that we were primarily considering were Babel and Rosetta, and when I found out that Rosetta means anus in German it really only left one.

. The domain is babeljs.io and it'll probably be referred colloquially as babeljs as it seems to roll off the tongue so I don't really see an issue with the official use of the project name being conservative and not using the js suffix. A similar example would be [Ember](http://emberjs.com/) (although they still use ember and ember.js).

**Comment by billychappell** [comment]
@sebmck Fair enough. I would at the very least, follow Ember's lead and refer to Babel as Babel/BabelJS inside the website and documentation interchangeably -- "Babel, sometimes referred to as BabelJS" isn't the most consistent naming convention in the world, but it would alleviate a lot of the concerns listed here and give a nod to those who are vehemently for a more specific name, hopefully quelling their complaints so we can all finally turn our attention to more pressing issues!

**Comment by abritinthebay** [comment]
Lets face is - it'll be referred to in the community as Babel JS... JS suffix or not. There's about 20 different OSS projects called "Babel" so the ship has already sailed in terms of user confusion. The python library wasn't the first to call itself Babel (by a long shot) so they hardly have any more ownership of the name that this project.
