### ISSUE TITLE
Babel-core module requires filename in order to read .babelrc (even if filename is just jibberish)

### ISSUE THREAD

**Issue by nickmanning214** [babel/babel#7867]
**Current Behavior**
Babel module doesn't read `.babelrc` without providing a filename, even if the filename is jibberish. I don't see anything in the docs about needing a filename. 

**Input Code**

I have my .babelrc file in the same folder as this script.

```js
var babel = require("babel-core");

var js = `var x = { catch: 4, bar: 7 };`;

var transformedjs = babel.transform(js).code;

console.log(transformedjs);
//var x = { catch: 4, bar: 7 };
//nothing was changed


var usingBabelRc = babel.transform(js,{
    filename: "asdfasdfs"//you need this filename for some reason, even if jibberish
}).code

console.log(usingBabelRc);
//var x = { "catch": 4, bar: 7 };
//The code was transformed successfully

```
**Expected behavior/code**

I expect the code to transpile without needing a filename, but if a filename is required, I expect that the filename would need to be real and not jibberish (and I would expect this to be explained in the docs).

## Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "plugins":["transform-es3-property-literals"]
}


```

**Environment**
- Babel version(s): v6.23.6
- Node/npm version: v8.6.0
- OS: OSX 10.12.6

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by loganfsmyth** [comment]
This isn't the best, but it is expected. `.babelrc` files are specifically loaded relative to a given path's directory, so if you don't pass a filename, we assume that there isn't a `.babelrc`.

We now support a `configFile` option, which will auto-populate with a `babel.config.js` file from the working directory if not otherwise assigned, which may be more applicable in cases where you want to use a config file, but don't have a specific filename for the file being compiled.

**Comment by nickmanning214** [comment]
Okay that's good about the `configFile` option. Thanks for that! With `configFile` is there any reason to support `fileName` at all when you are compiling a string of code and not a file of code?

**Comment by loganfsmyth** [comment]
The primary usage of the filename is

* Filename is included in some error messages
* Filename is used to resolve `.babelrc` files
* Filename is used in config files if they want to use `ignore/only` or `test/include/exclude` to apply configuration to specific files
* Some plugins might want to use the name of the file during transformation, but depends on what plugins you use.

If you're not compiling a real file, it's reasonable to not pass a filename since, if it's not a real file, none of those are likely to make sense anyway.

**Comment by loganfsmyth** [comment]
We've also got some better docs now that we did when I last posted. See http://babeljs.io/docs/en/options#filename and http://babeljs.io/docs/en/config-files#file-relative-configuration

**Comment by nickmanning214** [comment]
Thanks for following up! Docs look great!
