### ISSUE TITLE
Combination of two runtimes cause unexpected errors

### ISSUE THREAD

**Issue by drcmda** [babel/babel#7882]
## Bug Report

I have a lib ([react-spring](https://github.com/drcmda/react-spring)) which declares `"@babel/runtime": "^7.0.0-beta.46"` in its dependencies.

A project in which i use it relies on `"@babel/runtime": "7.0.0-beta.36"`, all babel packages are pinned to 36 due to babels decorator bug that isn't fixed yet.

But the two runtimes together seem to cause the strangest errors, suddenly the imports don't have a render method any longer for instance, it's just not there. 

```jsx
import React from 'react'
import { render } from 'react-dom'
import { Spring } from 'react-spring'

console.log(Spring.prototype)

render(
    <Spring native from={{ width: 0 }} to={{ width: 525 }}>
        {props => <div>hello</div>}
    </Spring>,
    document.getElementById('root'),
)
```

<img width="593" alt="screen shot 2018-05-08 at 11 01 17" src="https://user-images.githubusercontent.com/2223602/39748007-37c2bc80-52af-11e8-93e1-8cd300f5c3f3.png">

Then i tried to copy [the libs export](https://unpkg.com/react-spring@5.1.2/dist/react-spring.es.js) into a local file, now it says:  

`Error: Can't resolve '@babel/runtime/helpers/builtin/es6/objectSpread'`.

It works when i use @babel/runtime@latest in my project, but the problem is, i keep getting these complaints from users of my lib, and i start to think that every time they have a different runtime it'll cause issues. 

Is there anything i can do on my side, or should i not distribute with that particular runtime?

**Environment**
- Babel version(s): v7.0.0-beta.36-46
- Node/npm version: 10
- OS: macos
- Monorepo no
- How you are using Babel: webpack

**Comment by drcmda** [comment]
@nicolo-ribaudo for sure but is this the official recommendation? I though i could save some bytes not having to do that by referring to babel-runtime, i think i've been doing it for a long while now.

**Comment by loganfsmyth** [comment]
Using `^` while on a beta version is an incredibly bad idea. We are still making breaking changes, that's the whole reason it is still beta. You're essentially telling the runtime transform to build with it's current knowledge of what helpers exist, but they pointing it at a runtime packages that may or may not have that helper at all.

**Comment by drcmda** [comment]
But the root has a lower runtime, so even if I would pin it in the lib, wouldn’t the result be the same? 

Is it generally considered unsafe atm to rely on balbel/runtime?

**Comment by loganfsmyth** [comment]
Yeah sorry, I should clarify I wasn't saying that will fix your issue, just that using `^` with the beta is _super_ dangerous, because you're distributing a library that depends on something that specifically _will_ break in the future, so anyone depending on `react-spring` will be broken when we make breaking changes in the beta, and not have a way to fix it until you release a new version and they upgrade to it. `transform-runtime` injects imports for `@babel/runtime`, and if the imports it injects stop pointing to files that exist, users will start getting errors like the `Error: Can't resolve '@babel/runtime/helpers/*` one you posted.

If you can create a repository that reproduces the issue, I'd be happy to take a look at it. It is hard to say from just the information given what the problem might be.

**Comment by drcmda** [comment]
Closing this as i fail to be able to reproduce a clear cut testcase, it seems to be caused when too many factors come together and i can't put my finger on what exactly goes on.
