### ISSUE TITLE
Files in node_modules are not transformed in 7.0.0-beta.45 and later

### ISSUE THREAD

**Issue by kevinfahy** [babel/babel#7970]
# v7 Regression

**Potential Commit/PR that introduced the regression**
Working in `7.0.0-beta.44`, broken in `7.0.0-beta.45`.

**Describe the regression**
Files in `node_modules` directories are not transformed.

**Input Code**

```js
// Any file that lives in `node_modules` will suffice. One real world example is
// `copy-text-to-clipboard@v1.0.4`, which returns an arrow function:
'use strict';
module.exports = input => {
	const el = document.createElement('textarea');

	// ...
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
// .babelrc.js:
module.exports = {
  presets: ['@babel/env'],
};
```

**Expected behavior/code**
Expected:
```
$ npx babel node_modules/copy-text-to-clipboard/index.js | sed -n '3p'
module.exports = function (input) {
```

Actual:
```
$ npx babel node_modules/copy-text-to-clipboard/index.js | sed -n '3p'
module.exports = input => {
```

**Environment**
- Babel version(s): v7.0.0-beta.45, v7.0.0-beta.47
- Node/npm version: Node 9.11.1/npm 5.6.0
- OS: OSX 10.13.4
- Monorepo: yes
- How you are using Babel: `cli` (also tested in `loader`)

**Comment by loganfsmyth** [comment]
This was an intentional breaking change that we made in `beta.45` to limit the scope of `.babelrc` files to

1. Only apply to files in the package they are inside of
2. Only search for them at all when loading files in the root package, requiring opt-in for any other packages

To define overall configuration that applies across packages, we're now recommending you create a `babel.config.js` file in your project root that exports the global Babel config you'd like to use.

We're currently exploring allowing a flag in the root `.babelrc` to make it behave as one of these "global" configs, but that is not complete yet, so `babel.config.js` is the way to go if you are compiling `node_modules` content and trying to use a config file.

**Comment by kevinfahy** [comment]
Thanks for the help! Confirming that simply renaming `.babelrc.js` to `babel.config.js` was sufficient for our case.

**Comment by augbog** [comment]
For others who ran into this, this PR discussion was enlightening :)
https://github.com/babel/babel/pull/7358

Also relevant documentation on the config file is scheduled in this issue: https://github.com/babel/website/issues/1628
