### ISSUE TITLE
Error: Cannot use decorators and decorators2 plugin together

### ISSUE THREAD

**Issue by Hugale12** [babel/babel#8012]
## Bug Report

**Decorators conflict**

I have a probleme on my vue.js project with babel. 

**Code**
.Babelrc

```js
{
  "presets": ["@vue/app"],
  "plugins": ["transform-decorators-legacy", "transform-class-properties"]
}
```
I have see that babel decorator stage change but i don't find how resolve this !

**Environment**
- Babel core: V7.0.0.0
- Node  version: v10.1.0
- NPM 6.0.1

**Comment by nicolo-ribaudo** [comment]
`@vue/app` already has decorators and class-properties support because it includes the stage-2 preset, so you need to remove `transform-decorators-legacy`.
You get that error because you are using both the new decorators proposal (with the preset) and the old one (with the plugin).

Then you need to pass the `"decoratorsLegacy": true` option to the preset, because Babel doesn't support the new decorators proposal yet.

Your babelrc should look like this:
```json
 {
  "presets": [
    ["@vue/app", { "decoratorsLegacy": true }]
  ]
}
```

**Comment by Hugale12** [comment]
@nicolo-ribaudo  Thank you very much !  can i remove : ```  "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",``` on my  `"devDependencies"` ?

**Comment by nicolo-ribaudo** [comment]
Yes
