### ISSUE TITLE
Dependency on braces, which suffers from security vulnerabilities

### ISSUE THREAD

**Issue by annyhe** [babel/babel#8034]
Vulnerability report: https://snyk.io/vuln/npm:braces:20180219

To reproduce this error: run 
```
snyk test babel-cli

Testing babel-cli...
✗ Low severity vulnerability found on braces@1.8.5
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: babel-cli@6.26.0 > chokidar@1.7.0 > anymatch@1.3.2 > micromatch@2.3.11 > braces@1.8.5
Upgrade direct dependency chokidar@1.7.0 to chokidar@2.0.0 (triggers upgrades to anymatch@2.0.0 > micromatch@3.1.4 > braces@2.3.1)
```
Solution: update chokidar@1.7.0 to chokidar@2.0.0.
Can PR if needed.

**Comment by annyhe** [comment]
It seems the babel-cli's braces is up to date in package.json https://github.com/babel/babel/blob/master/packages/babel-cli/package.json
But the latest npm package still uses the the old braces dependency

```
babel-cli@7.0.0-beta.3 > chokidar@1.7.0 > anymatch@1.3.2 > micromatch@2.3.11 > braces@1.8.5
babel-cli@7.0.0-beta.3 > babel-core@7.0.0-beta.3 > micromatch@2.3.11 > braces@1.8.5
```

When will the next release with the updated chokidar be released?

**Comment by loganfsmyth** [comment]
`micromatch@2.3.11 > braces@1.8.5` is the important part. The most recent micromatch is `3.x` but it's probably reasonable to see if they'll publish a new `2.3.x` version with an updated braces. Since it's a major version change for `braces` that would be the main potential sticking point, but the new `micromatch@3` already uses the new braces version, so it might not be too bad to ask that the `2.x` branch also get an update. Hard to say though.

**Comment by eivinhb** [comment]
This is picked up by `npm audit` now and this block your build pipeline since we use `verify:audit` as part of you release process.

https://nodesecurity.io/advisories/786

It's quite a long way down (`babel-cli > chokidar > anymatch > micromatch > braces`) but babel is using older version of chokidar. The latest version of `chokidar` is using a patched version of braces now.

**Comment by nicolo-ribaudo** [comment]
@imjacobclark Does https://github.com/babel/babel/pull/9550 fix this?
