### ISSUE TITLE
Input Sourcemap Annotation gets removed

### ISSUE THREAD

**Issue by digitalkaoz** [babel/babel#8070]
## Bug Report

**Current Behavior**
if my Input Sourcecode has a sourcemap annotation, babel will remove it (if it cant find/parse the sourcemap annotation), even if i pass an input sourcemap object to babel.

**Input Code**

```js
const foo = "bar"
//# sourceMappingURL=/some/path/that/not/exists/yet/myfile.js.map
```
**Babel Call**
```js
const babel = util.promisify(require("@babel/core").transform);

let { code, map } = await babel(inputCode, { ...babelConfig,
    inputSourceMap: inputMap ? JSON.parse(inputMap) : undefined
});
```

**Output Code** 

```js
var foo = "bar"
```

**Expected behavior/code**
the sourcemap annotation should remain in the file. it gets removed [here](https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/normalize-file.js#L20)

**Expected Code**
```js
var foo = "bar"
//# sourceMappingURL=/some/path/that/not/exists/yet/myfile.js.map
```
> and transformed sourcemap object

**Babel Configuration**

```js
 { extends: 'base/.babelrc',
  babelrc: false,
  compact: false,
  plugins: [],
  presets:
   [ [ '@babel/preset-env/lib/index.js',
       [...] ] ],
  sourceType: 'script' }
```

**Environment**
- Babel version(s): [v7.0.0-beta.49]
- Node/npm version: [Node 8.11]
- OS: [OSX]
- Monorepo [e.g. yes]
- How you are using Babel: [programmatically]

**Possible Solution**

* it worked with v7.0.0-beta.46
* dont fiddle around with the sourcemap annotation if the inputSourcemap is already a sourcemap object

**Comment by loganfsmyth** [comment]
Could you elaborate on your usecase where preserving the comment would be desirable? After the code passes through Babel, any existing map will no longer match up with Babel's input.

**Comment by digitalkaoz** [comment]
its, ok, the new sourcemap ist generated correctly, but the annotation is gone after babel is done. remember the file is not written, so the convertSourceMap module removes the comment (because it cant load the sourcemap from the input code, but we gave it to babel as input)

**Comment by loganfsmyth** [comment]
The assumption is that the comment would point to an old incorrect sourcemap for the input file. If you want the output to include a map comment, you can either set `sourceMap: "inline"` for Babel to append a new comment with a `data:` URL containing the JSON for `map`, or you'd have to add the comment on yourself.

Leaving the comment would mean that the output JS would contain a comment pointing at the old inputSourceMap, which would no longer have the correct mappings.

**Comment by loganfsmyth** [comment]
My question for you is, the file doesn't exist yet, why is the comment there in the first place?

**Comment by digitalkaoz** [comment]
we have some legacy files (that dont use a module system), so we use uglifyjs to concat them whil generating a sourcemap (everything in memory), then we pipe both (concatted code & sourcemap) through babel to get the final bundle. its not uncommon to have everything in memory, but that shouldnt roll away sourcemap annotations

**Comment by loganfsmyth** [comment]
Would you be able to spell things out step by step? My reading of your description is

1. Concat all files with uglify generating maps
2. Pass files through Babel
3. Write files to disk

My expectation is that step 3 would take `code` and `map`, choose whatever filename, and then write them to disk while adding an appropriate comment.

What you're describing sounds like step 1 produces code that already has the sourcemap comment, but the file it points at doesn't exist. I don't understand why it would produce a comment pointing at a non-existent file.

**Comment by digitalkaoz** [comment]
ok,

1. Concat all files with uglify generating maps and code (not written yet), but already with sourcemap annotation (because we can tell uglify so, so we can write the files ourself)
2. Pass code string & sourcemap object through Babel, and get modified code string and sourcemap object back (but the annotation was removed)
3. Write files untouched to disk (code & map)

it worked with beta-46 (but not with beta-49)

we use this approach: https://github.com/mishoo/UglifyJS2#source-map-options

**Comment by loganfsmyth** [comment]
> it worked with beta-46 (but not with beta-49)

Babel 100% ignored filepath sourcemap comments until we landed #7980, which is what changed your behavior.

Alright, thanks for explaining. Personally, I think that it's reasonable for Babel to see the comment and strip it out, because as you've said it explicitly points at a file that isn't there. Babel has no way to know that you'll create this file eventually. I'd also personally be concerned because there's no guarantee that some transform plugin running in Babel won't move the comment around making it not at the end of the file anymore.

In my view, the correct approach would be for Uglify to not insert the comment, and for you to do it when you write the `.map` file to disk.

**Comment by digitalkaoz** [comment]
Personally i think that would make the in memory capabilities of babel (regarding sourcemaps) useless. :(

If i am passing a sourcemap into babel it shouldnt try to scrape it from the sourcecode (its already known to babel), and if it can find it, babel shouldnt f*ckup my sourcemap annotation. 

If i folllow your thoughts, whats the matter of passing an sourcemap explicitly then?

#7980 is completely wrong in my eyes, this whole thing should be skipped if babel already has a sourcemap explicitly given.

Sorry to be so mean :/

what can we do to make all of us happy? fiddling around with my sourcecode and readding the sourcemap annotation feels wrong to me... #7980 should be optional somehow

**Comment by loganfsmyth** [comment]
> #7980 is completely wrong in my eyes

I think that's a bit of a strong reaction. That PR just does for files what we already did for data URIs. Having it be consistent makes tons of sense. Whether the behavior for `data:` URIs is a reasonable question though.

> If i am passing a sourcemap into babel it shouldnt try to scrape it from the sourcecode

I think it's reasonable to say, if you pass in an object as the input map, that we skip parsing `sourceMappingURL` to try to get the input map. I actually nearly asked to have that done in #7980, but since that PR didn't change the ordering at all, I didn't.

That said, I consider it pretty unclear whether Babel should strip off the comments when it receives an object. As far as Babel is concerned, any `sourceMappingURL` comment in its input will, by definition, be wrong in the output. You're sidestepping that by essentially misleading Babel by telling it that there is a file when there isn't.

Think of it another way, if it was a `data:` URI instead of a `file` one, would it be reasonable to keep the comment? If you pass an object `inputSourceMap` and also pass it a file with `//# sourceMappingURL=data:application/json;base64,...`, shouldn Babel's output code really still contain that? It would mean that Babel was outputting a file containing a source map that was objectively wrong, in the sourcecode, while returning the correct map in `result.map`. Having both would be super confusing.

> babel shouldnt f*ckup my sourcemap annotation.

Please respect that while you may disagree with the way something is done, it doesn't make your feelings on it absolute. The inverse is also the case. I don't think the comments should be left untouched, but I'm doing my best to understand your usecase so we can both be happy. Let's avoid derailing the discussion.

**Comment by digitalkaoz** [comment]
sorry for my harsh language. im constantly bugged by the 80:20 rule these days, and im far to often on the 20% side...

when i said "completely wrong" i meant, i dont think that sourcemap cleanup shouldnt belong into `@babel/core`, a plugin would make more sense in my eyes. but im not the one in charge here for those architectual decisions, so its ok for me.

but as i said before, this patch made in-memory handling for code+sourcemaps unusable (at least for our use-case). sure babel changed the sourcemap, but babel (if used programatically) returns the sourcemap for writing/further processing, so its up to me if im going to overwrite the file (which is referenced from my sourcemap annotation), or not, but please leave the sourcemap annotation untouched then.

we have different opinions on this but lets try to find a solution we are all happy with!

can we make the sourcemap cleanup conditional for sourcemaps passed as object? im happy to provide a PR, if we can agree on this solution?!

and again sorry for my harsh words @loganfsmyth
