### ISSUE TITLE
Module not found: Error: Can't resolve 'core-js/modules/es7.symbol.async-iterator'

### ISSUE THREAD

**Issue by timc13** [babel/babel#8095]
I'm using babel `preset-env` with the following config:
```
  "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "browsers": [
              ">1%",
              "last 4 versions",
              "Firefox ESR",
              "not ie < 9"
            ]
          },
          "modules": false,
          "useBuiltIns": "usage",
          "debug": true
        }
      ]
    ]
  }
```

During the webpack build, I'm getting the following error :
```
Module not found: Error: Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/my_src_dir'
```

**Comment by timc13** [comment]
I believe the last time this worked was `beta.41`

https://github.com/babel/babel/pull/7548

**Comment by zloirock** [comment]
You install `core-js@2.5.x` where this file [exists](https://unpkg.com/core-js@2.5.7/modules/es7.symbol.async-iterator.js).

**Comment by timc13** [comment]
@zloirock sorry, maybe I'm missing something, but I don't see anyhting in the docs about installing `core-js@2.5.x`.  

Also, this used to be bundled with `preset-env`, no ?  Can you point me to the discussion or reasoning as to why this has to be installed now?

**Comment by existentialism** [comment]
@timc13 preset-env has never bundled core-js directly, it transforms a babel-polyfill/core-js import (if found) into individual transforms when used with the `useBuiltIns` option.

If you're using babel-polyfill, you might want to see what version of core-js was installed alongside it (since it's a dep).

**Comment by marcofugaro** [comment]
Happened to me also, it's because of react depending on an older version
![image](https://user-images.githubusercontent.com/7217420/41241569-91e4bc78-6d9d-11e8-9694-1487c0b97c9a.png)

[Yarn's resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) might help.

I filed an issue with react: https://github.com/facebook/react/issues/13018

**Comment by timc13** [comment]
@marcofugaro thanks - i'm willing to bet this is the root cause of my problem
