### ISSUE TITLE
Add other syntax plugins in the typescript preset

### ISSUE THREAD

**Issue by mquandalle** [babel/babel#8098]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When replacing the `ts-loader` with babel and `@babel/preset-typescript` there are syntax errors. It seems that the `@babel/preset-typescript` only includes `@babel/plugin-transform-typescript` whose role is to remove TS type annotations.

**Describe the solution you'd like**
Include other plugins to handle TS features. In my code base I needed:

* `@babel/plugin-proposal-numeric-separator`
* `@babel/plugin-proposal-class-properties`

I think are are stage-3 proposals that are supported by typescript and that should be included in the TS preset.

**Describe alternatives you've considered**
Leave the preset unchanged and let the user add plugins on a per-feature basis, but IMHO this defeats the point of a typescript preset.

**Teachability, Documentation, Adoption, Migration Strategy**
Non breaking change

**Comment by brainkim** [comment]
This would be nice. I assume typescript support presets includes support for all supported typescript features...

**Comment by hzoo** [comment]
Thanks for the issue, understandable that you might think it would include other transforms!

So this would be a breaking change if you are using preset-env and are intending to not compile a plugin if it's supported natively eventually. I suggested we had plugins before as well but we would have to add these as TS is updated and even remove them if they are added to preset-env (this is a similar issue to the stage-3 preset since removing a plugin would actually be a breaking change. I also talked to the TS team about this and @DanielRosenwasser suggested we leave it as is as well. We could make a separately named preset that does this but the current behavior is intentional. The flow preset and the ts preset do the same things - both just remove types and include the 1 plugin. It's just a convenience thing since you can just use the individual plugin as well

**Comment by mquandalle** [comment]
I certainly haven't investigated this issue as much as you have, but the current structure isn't very intuitive to me. As you said, if we just want to remove type annotations and don't want to support any other typescript feature we can use the appropriate plugin `@babel/plugin-transform-typescript`. For me, the idea of a typescript preset is to include a list of plugins so that a typescript project (that compiles with the typescript compiler) will also just work with babel, and if it doesn't I think people will be confused.

About the idea that eventually you may want to not compile a particular feature and keep it natively, maybe this need a separate API? Because this is not an issue specific to the typescript preset, but it occurs in all presets and even simple plugins. For example if at some point we don't want to compile `numeric-separator` we might want to keep the plugin in the babel config (either directly or via a preset) to indicate that the project uses this feature and have a separate configuration to indicate that we don't want to transform it. This would simplify things like creating different bundles for different browsers with different level of native support, without having to tweak the plugin list. Is there already an issue/discussion open about this idea?
