### ISSUE TITLE
ES7 Promise Finally on Microsoft Internet Explorer 11 and Microsoft Edge 

### ISSUE THREAD

**Issue by HyP3r-** [babel/babel#8111]
## Bug Report

**Current Behavior**
We want to support Microsoft Internet Explorer 11 and Microsoft Edge in out Project. In our Project we have used the ECMAScript 7 feature of [Promise Finally ](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally) a lot of times. In a talk with @existentialism he told me to use this little trick to make this thing working:

1. Create a new File (e.g. polyfill.js):
```js
import "babel-polyfill";
import "core-js/modules/es7.promise.finally";
```
2. Update the webpack.config.js entry Points:
```js
entry: {
    app: [
        "./frontend/pages/polyfill",
        "./frontend/pages/index"
    ],
}
```

**Expected behavior/code**
This solution is working for Microsoft Internet Explorer 11 pretty good but does not work for Microsoft Edge:
```
Unhandled promise rejection TypeError: Object doesn't support property or method 'finally'
```
How can I solve this problem?

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module: {
    rules: [
        {
            test: /\.js$/,
            include: path.join(__dirname, "frontend"),
            exclude: /(node_modules|bower_components)/,
            use: [
                {
                    "loader": "babel-loader",
                    "options": {
                        "cacheDirectory": true,
                        "metadataSubscribers": [ReactIntlPlugin.metadataContextFunctionName],
                        "plugins": [
                            "lodash",
                            "react-bootstrap",
                            "recharts",
                            "transform-runtime",
                            ["react-intl", {"enforceDescriptions": false}],
                        ],
                        presets: [
                            ["react"],
                            ["env", {
                                "useBuiltIns": "entry",
                                "targets": {
                                    "browsers": [
                                        "chrome >= 61",
                                        "edge >= 15",
                                        "firefox >= 52",
                                        "ie >= 11",
                                    ]
                                }
                            }]
                        ]
                    }
                },
            ]
        }
}
```

**Environment**
- Babel version(s): babel-core ^6.24.1, babel-loader ^7.0.0, babel-plugin-lodash ^3.3.2, babel-plugin-react-bootstrap ^0.0.2, babel-plugin-react-intl ^2.3.1, babel-plugin-recharts ^1.1.1, babel-plugin-transform-runtime ^6.23.0, babel-polyfill ^6.24.1, babel-preset-env ^1.6.1, babel-preset-react ^6.24.1
- Node/npm version: Node 6.11.2/npm 3.10.10
- OS: Windows 10
- Monorepo: yes
- How you are using Babel: loader

**Comment by HyP3r-** [comment]
Update to this issue:

If I write this in the **polyfill.js**
```
import "babel-polyfill";
import "core-js/modules/es7.promise.finally";
```
it is working on **Microsoft Internet Explorer 11** and not on **Microsoft Edge** and if I write this in the **polyfill.js**
```
import "core-js/modules/es7.promise.finally";
import "babel-polyfill";
```
it is working on the current version **Microsoft Edge** but not on **Microsoft Internet Explorer 11**.

The reason for that is following: The **Microsoft Internet Explorer 11** has no **Fetch API** and no **Promise Object** and the **Microsoft Edge** (or older Versions of the Mozilla Firefox or Google Chrome) has a **Fetch API** and a **Promise Object** but no **finally function**.

So in the first case **import "babel-polyfill"** is polyfilling the **Promise Object** and **import "core-js/modules/es7.promise.finally"** is polyfilling the **finally function** on the new created Promise Object. Thats the reason why it is working on **Microsoft Internet Explorer 11**, but not on **Microsoft Edge** because the native **Fetch API** is returning a non polyfilled (native) Promise Object without the **finally function**.

And in the second case **import "core-js/modules/es7.promise.finally"** is polyfilling on the existing **Promise Object** the **finally function** on **Microsoft Edge** and is unable to polyfill this functon on **Microsoft Internet Explorer 11** because there is no Promise Object.

**So the Problem or Question is**: why does **import "babel-polyfill"** Polyfill (overwrite) the Promsie Object though it shouldn't do that in this case?

**Comment by kyoukhana** [comment]
Did this ever get resolved

**Comment by stalkerg** [comment]
Same problem with old Firefox 46.

**Comment by aprilandjan** [comment]
Encountered this problem on IE10/Edge, too. Had to use `async` function to solve it temporarily.

**Comment by xtuc** [comment]
Maybe @zloirock would have any input on this?

**Comment by zloirock** [comment]
It's already explained in many other places. https://github.com/zloirock/core-js/issues/371, https://github.com/zloirock/core-js/issues/332, https://github.com/zloirock/core-js/issues/178, etc.

**Comment by rjgotten** [comment]
This type of issue can be resolved via a variation of how C# implements extension methods.

You can have a transform plugin which turns anything that looks like `foo.finally( fn )` into `promise_finally( foo, fn )` and then have this `promise_finally` function:

1. Check if `typeof foo.finally === "function"` and if so, call that implementation directly; otherwise
2. Check if `foo` is a native or polyfilled promise without `finally` and if so; call a pollyfilled `finally` implementation; otherwise
3. Throw a `TypeError` indicating that `finally` is undefined on `foo`.


In browsers that support the native method, performance will still be quite good. It just adds a wrapping function call and a simple `typeof` check.

In browsers that do not support the native method and need the polyfill, the type check in 2. will almost never be the bottle-neck. The actual polyfill implementation itself will outweigh it.

Ofcourse, even browsers that _do_ support the native implementation could end up in 2. when the method is called on the 'wrong type'. But still: that's the exception and not the norm.

---

I'm currently using a homebrewen transform plugin that implements this pattern to solve the larger more general problem of polyfilling instance methods  across `Array`, `Date`, `String` etc. built-ins without affecting the native prototypes. It works _really_ well.

**Comment by zloirock** [comment]
@rjgotten this way of polyfilling instance methods will be added to `babel-runtime` with `core-js@3`, see #7646.
