### ISSUE TITLE
[decorators] react propTypes of "decorated component" are being applied to "enhanced component" returned by HOC

### ISSUE THREAD

**Issue by damianobarbati** [babel/babel#8223]
`propTypes` of "decorated component" are somehow applied at runtime to "enhanced component".

Here a basic repro: https://github.com/damianobarbati/babel-hoc-bug

PropTypes is complaining about prop-types defined in wrapped components just as if they were defined in class returned by the decorator.

Is there something I'm missing here?

Babel config and dependencies versions:
```
"babel": {
   "presets": [
       [
           "@babel/preset-env",
           {
               "modules": false,
               "useBuiltIns": "usage",
               "debug": true
           }
       ],
       [
           "@babel/preset-stage-2",
           {
               "decoratorsLegacy": true
           }
       ],
       "@babel/preset-react"
   ],
   "plugins": [
       "transform-strict-mode",
       "@babel/plugin-proposal-class-properties",
       "@babel/plugin-proposal-export-default-from",
       "lodash"
   ]
},
"devDependencies": {
   "@babel/core": "^7.0.0-beta.51",
   "@babel/plugin-proposal-class-properties": "^7.0.0-beta.51",
   "@babel/plugin-proposal-export-default-from": "^7.0.0-beta.51",
   "@babel/polyfill": "^7.0.0-beta.51",
   "@babel/preset-env": "^7.0.0-beta.51",
   "@babel/preset-react": "^7.0.0-beta.51",
   "@babel/preset-stage-2": "^7.0.0-beta.51",
   "babel-eslint": "^8.2.1",
   "babel-plugin-lodash": "^3.3.2",
   "babel-plugin-transform-strict-mode": "^6.24.1",
   ...
}
```

**Comment by damianobarbati** [comment]
Did anybody have the chance to verify this? 😔

**Comment by dnalborczyk** [comment]
hey @damianobarbati 

I looked into this and it seems odd. I noticed when you change the hoc2 `decorator` to be just a wrapper function it works as you probably expect without an error message.

```javascript
@HOC2
export default class Component2 extends React.Component {
  ...
```


```javascript

class Component2 extends React.Component {
  ...
}

export default HOC2(Component2)
```

that being said, I'm not sure if trying to find out where and what the problem is might be worth pursuing, `PropTypes` are pretty much `deprecated` https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings and the `decorator proposal` changed significantly. so, even this is a bug, I can hardly imagine it's worth fixing.

**Comment by damianobarbati** [comment]
PropTypes are not deprecated! They were just moved to independent package 😅

**Comment by dnalborczyk** [comment]
`prop types` are pretty much super seeded by `flow` or `typescript` and the likes. just saying that the `near deprecation`, plus, the more important fact that the `decorator proposal` changed significantly, make a good point of not spending too much time on the issue -- if it is one.

obviously, this is just my opinion, and not my call to make.

**Comment by damianobarbati** [comment]
@dnalborczyk both `flow` and `typescript` are intended for `compile-time type-checking` while prop-types are intended for `runtime type-checking`. 
And not everyone is willing to add the flow/ts typechecking layer in their codebase!

Can you please share any link or resource mentioning their near deprecation?

Thanks for the help!

**Comment by damianobarbati** [comment]
@nicolo-ribaudo could you give a look at this? 🙏🏻

**Comment by nicolo-ribaudo** [comment]
I have investigated a bit (sorry for the long delay), and I think that this is a misconfiguration problem.
The documentation [says](https://babeljs.io/docs/en/next/babel-plugin-proposal-decorators.html#note-compatibility-with-babel-plugin-proposal-class-properties) that the decorators plugin should come before the class properties one, but in your repo they are run in the opposite order.
Here is why it is needed:
```js
// WRONG:

@hoc
class Foo {
  static propTypes = {};
}

// transform class properties
@hoc class Foo {}
Foo.propTypes = {}; // <-- propTypes is attached to the decorated class

// transform decorators
let Foo = hoc(class Foo {});
Foo.propTypes = {}; // <-- still wrong
```
```js
// CORRECT:

@hoc
class Foo {
  static propTypes = {};
}

// transform decorators
let Foo = hoc(class Foo {
  static propTypes = {};
});

// transform class properties
let Foo = hoc((_foo = class Foo {}, _foo.propTypes = {}, _foo));
```

You can fix it either by removing `proposal-class-properties` from the plugins list (since plugins are run before presets, and the decorators plugin is included in the preset) or by adding the decorators plugin in your plugin lists before the class properties one.

**Comment by damianobarbati** [comment]
Hell yeah, it was that. Thanks @nicolo-ribaudo 🙏🏻
