### ISSUE TITLE
Parser allows spaces between # and identifier

### ISSUE THREAD

**Issue by ramin25** [babel/babel#8225]
## Bug Report

**Current Behavior**
First identified in: [Class Fields (Stage 3) #12](https://github.com/babel/proposals/issues/12#issuecomment-398758818)
The parser currently allows spacing between the private name symbol `#` and the identifier. 

However, it seems to violate the [lexical grammar](https://tc39.github.io/proposal-class-fields/#sec-new-syntax) in the spec proposal:
```
PrivateName:: #IdentifierName
```

**Input Code**
```js
class Foo {
    #    p = 0;
    constructor() {
        this.#   p   ++;
    }

    print() {
        console.log(this   .   #    p);
    }
}
```

**Expected behavior/code**
Babel should communicate the parser error, e.g: "Spaces not permitted in private field name"

**Babel Configuration (.babelrc, package.json, cli command)**
```js
const presets = [
  ["@babel/env", {
    targets: {
      node: "6"
    },
    useBuiltIns: "usage"
  }]
];

module.exports = { presets,
    "plugins": ["@babel/plugin-proposal-class-properties"]
 };
```

**Environment**
- Babel version(s): [v7.0.0-beta.34]
- Node/npm version: [e.g. Node 6/npm 3.10.10]
- OS: [Windows 7]
- Monorepo [no]
- How you are using Babel: [cli]

CC'ing @rricard @mheiber and @littledan who were part of the conversation regarding this in  [Class Fields (Stage 3) #12](https://github.com/babel/proposals/issues/12#issuecomment-398758818).

I would also like to volunteer to fix this.

**Comment by loganfsmyth** [comment]
This may well make sense logically, but does the spec actually say that? Since `#` and `IdentifierName` are two separate tokens, it seems like having whitespace between them would actually be allowed, the same way whitespace is optional between other tokens.

It seems like this would require new logic in the syntactic grammar itself to assert a lack of whitespace/comments.

**Comment by nicolo-ribaudo** [comment]
See https://github.com/babel/proposals/issues/12#issuecomment-399756043: white spaces should be disallowed. I don't know how the proposal spec handles this, but if it doesn't it's a bug with the proposal.

**Comment by loganfsmyth** [comment]
Alright, then is there a spec bug tracking that? I don't see anything in the spec text actually backing this up.

**Comment by littledan** [comment]
It's subtle, but because the [PrivateName](https://tc39.github.io/proposal-class-fields/#prod-PrivateName) production uses two :: rather than one :, it is part of the token grammar, and no whitespace is permitted. We have discussed whether whitespace should be permitted here in TC39 and the decision to treat it as one token with no whitespace was an explicit one.

**Comment by loganfsmyth** [comment]
@littledan Perfect, that's all I was missing. Like I said, seems like the right thing to do, I just wanted to make sure it was actually specified fully.
