### ISSUE TITLE
export * gets pushed to top

### ISSUE THREAD

**Issue by simonseyock** [babel/babel#8230]
## Bug Report

**Current Behavior**

if a normal `import` statetement is used before a `export * from 'somwhere'` statement, the latter gets pushed to the top. This causes all code in `'somwhere'` to be executed before the code from the import.

**Input Code**
```js
import 'first';
export * from 'second';
```
becomes

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _second = require('second');

Object.keys(_second).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _second[key];
    }
  });
});

require('first');
```

**Expected behavior/code**

I expect the second statement to happen second.

**Babel Configuration (.babelrc, package.json, cli command)**

'try it out' section on babeljs.io

**Possible Solution**

The generated `export *` code does look like it might be possible to just move it at the right position. I think it is not allowed to export the same name twice in es2015, so no name could be overridden in the `exports`  object.

**Additional context/Screenshots**

**Comment by existentialism** [comment]
@simonseyock thanks for the issue! This is actually fixed in babel 7:

http://babeljs.io/repl#?babili=false&browsers=last%201%20Chrome%20versions&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAcgGbCgZxgg3AKAKYAekscAVHElBCImngMYQB2AJtkA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&sourceType=module&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.0.0-beta.50&envVersion=

**Comment by loganfsmyth** [comment]
Yeah, duplicate of #4356. Unlikely to be fixed in 6.x at this point.

**Comment by simonseyock** [comment]
Thanks, I did not see that issue
