### ISSUE TITLE
Add sourceMapIn option

### ISSUE THREAD

**Issue by bryanburgers** [babel/babel#827]
babel/grunt-babel#14 suggests using [grunt-contrib-concat][concat] to concatenate multiple files before compiling with Babel.

However, then the outputted source maps reference the file that was created by concat, not the original files. It would be awesome if Babel could take in an existing source map while it does its transforms, so that the outputted source maps reference the original files rather than an intermediate file.

* Many CSS-processor libraries deal with this by looking in a standard place for a map file (when loading style.css, look for original source maps at style.css.map).
* Uglify deals with this using a [sourceMapIn][uglify] option.

[concat]: https://github.com/gruntjs/grunt-contrib-concat
[uglify]: https://github.com/gruntjs/grunt-contrib-uglify#sourcemapin

**Comment by sebmck** [comment]
Available as of 4.7.0, thanks! You can either set the `inputSourceMap` option with a source map object or it'll look for a source map comment in the input file.

**Comment by bryanburgers** [comment]
Yay! Thank you so much.

**Comment by Rich-Harris** [comment]
Is it possible to disable this option? For some reason I'm getting wonky sourcemaps as a result and I've had to downgrade to 4.6.6 (the sourcemap generated by babel references files that don't exist - the bug is probably something external to babel, and if not I'll raise an issue if I can track it down).

Because I typically have transformations after babel in any case (bundling, minification etc) I prefer to merge sourcemaps as a single step at the end of the build. If I comment out [these lines](https://github.com/babel/babel/blob/master/src/babel/transformation/file.js#L481-L493) everything works okay again.

**Comment by sebmck** [comment]
@Rich-Harris Attached commit should do the trick. If you set `inputSourceMap` to `false` it wont try and find the sourcemap comment. I'll push out a new release in a bit.

**Comment by sebmck** [comment]
@Rich-Harris Available as of 4.7.9, let me know if it does the trick.

**Comment by Rich-Harris** [comment]
@sebmck Thanks for the rapid response as ever, though I think the condition is the wrong way round? Installing 4.7.9 fixed our issue but we didn't expect it to! Adding `inputSourceMap: false` caused the bug to reappear. PR inbound
