### ISSUE TITLE
"The pipeline operator requires a proposal set error" during compile

### ISSUE THREAD

**Issue by Mati365** [babel/babel#8276]
My build crashes with: ` The pipeline operator requires a proposal set. You must pass the 'pipelineProposal' option to @babel/preset-stage-0` error. I modified webpack.config.js by adding that flag to presets but it still not work.

```presets: [
              ['@babel/stage-0', {
                pipelineProposal: true,
                decoratorsLegacy: true,
              }],
              '@babel/react',
              '@babel/preset-env',
            ],
```

Anyone know how to fix it?

**Comment by Mati365** [comment]
passing `minimal` to `pipelineProposal` fixed the problem. Can you provide more info in error log about it?

**Comment by mAAdhaTTah** [comment]
@nicolo-ribaudo Sure. I'll also revisit the error message for the core plugin itself (#8277).

**Comment by bradennapier** [comment]
So this is now required all the sudden?  I am not using pipeline but just using stage-0 requires this or errors.... seems stupid - just dont expect it if it is not provided.

**Comment by mAAdhaTTah** [comment]
Stage presets are being removed (#8293). Stage-0 means "all proposals Stage 0 and above", so 0+, which includes the pipeline operator, which is Stage 1.

**Comment by hzoo** [comment]
> just using stage-0 requires this or errors.... seems stupid

I understand you think it's stupid, but this is how the Stage presets have always worked. Stage 0 includes Stage 1, and thus we would have to pass all the options down if we make it required.

Since this is frustrating, this is also why we are going to remove the Stage presets since it's clear either users include proposals they don't need/use/know about and everyone can always make their own instead. Especially since proposals are going to have breaking changes.
