### ISSUE TITLE
Using `>=`  only seems to target minimum version for browsers 

### ISSUE THREAD

**Issue by ankurkaushal360** [babel/babel#8305]
## Bug Report

**Current Behavior**
Targeting browsers with greater than or equal to only seems to target the minimum browser version.

For example if I want to target `ie >= 10`, it should include 10 and as well as 11 but only seems to target 10.

Here's the output:

```js
{
  "chrome": "66",
  "android": "4.4.3",
  "edge": "16",
  "firefox": "59",
  "ie": "10",
  "ios": "11",
  "safari": "11"
}
```

**Input Code**

`N/A`

**Expected behavior/code**
If I have a `>=10` for a browser version (In case it is IE), it should target both 10 & 11.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{"babel": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "browsers": [
              "last 2 versions",
              "ie >= 11"
            ]
          }
        }
      ],
      "react"
    ],
    "plugins": [
      "babel-polyfill"
    ]
  }
```

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: Node 8
- OS: OS X 10.13.6
- Monorepo: No
- How you are using Babel: `register`

**Possible Solution**

**Additional context/Screenshots**
N/A

**Comment by hzoo** [comment]
Thanks for making an issue! This is intentional though,  https://babeljs.io/docs/en/next/babel-preset-env.html#determine-the-lowest-common-denominator-of-plugins-to-be-included-in-the-preset

I think about what it means to target a browser and to target 2 would mean to use the LCD unless you are going to output multiple files, otherwise it would potentially fail on the other? If you support a browser you are essentially saying you support the one with the least support unless you use Babel to create a separate one for IE (which is not a bad idea)
