### ISSUE TITLE
how to use Babel 7 babel-register to compile files outside of working directory

### ISSUE THREAD

**Issue by helios1138** [babel/babel#8321]
v7 migration guide mentions that

> @babel/register will also now only compile files in the current working directly (was done to fix issues with symlinking).

but it doesn't mention a way to get around this behavior

in v6, a setup like this was working:
```
foo
  someLib.js
  .babelrc
bar
  index.js // import 'someLib.js'
  run.js // require('babel-register'); require('index');
  .babelrc
```
now if you do `cd bar && node run` it only compiles what is in `bar` but not in `foo`

is there a way around this or is it something that is just impossible to do in Babel 7?

**Comment by helios1138** [comment]
ok, I've figured it out. in case someone needs it, the solution is
```js
require('@babel/register')({
  extends: './.babelrc',
  ignore: [/node_modules/],
})
require('./src/index')
```

**Comment by 2Pacalypse-** [comment]
Can we get some clarification on this issue from someone who is familiar with Babel's internals?

I can't believe it's not possible anymore to import a file outside your "working" directory (the one with the `package.json` in it, I assume?) and have it be compiled by babel. This worked perfectly fine in Babel 6, so I'm wondering why it doesn't anymore. I know the explanation was given to fix some issues with symlinking, but this seems to be a pretty big loss in functionality to be given such a vague explanation and no alternative.

Btw, the "solution" posted above (though it seems more like a hacky workaround to me), doesn't work anymore.

**Comment by simlu** [comment]
We would love to see a workaround for this as well.

@helios1138 @2Pacalypse- I'm not even sure why that workaround would have worked in the first place?

**Comment by 2Pacalypse-** [comment]
I actually came to the bottom of this yesterday, but I was so mentally exhausted by this, and upgrading to babel 7 in general, that I didn't have energy to post here what I found :d.

In any case, after digging through source code and the commit history of babel, I've found the offending PR that changed this: https://github.com/babel/babel/pull/5590. Reading the PR description, it seems like it was a conscious decision by babel team to stop compiling anything outside of the working directory, but very little explanation is given on why. Am I the only one who thinks that babel should compile everything that's required by default, except the stuff inside the `node_modules` folder(s)?

This is an example of a project structure that babel 7 doesn't support by default anymore.
```
my_project/
  babel.config.js
  common/
    common-file1.js
  package1/
    package.json
  package2/
    package.json
```
Note that `common` folder is just a folder, not a package. Now if you try to import something from `common` folder in `package1` or `package2`, it won't get compiled. I think it's quite sensible to expect it would compile by default, but maybe I'm missing something?

Anyway, a "proper" workaround for this issue is not really a workaround at all. You must manually set which paths you want to compile with the `only` option, which means you must also exclude the `node_modules` stuff manually (with `ignore` option). Thankfully, and I haven't dug deep through the `babel-core`'s source code, but it seems like you can just put the root folder in the `only` option and it will include all of the subfolders as well.

In my particular project, this is how I must use `babel-register` now inside one of the packages (still looking for a better way):
```js
const path = require('path')

const rootPath = path.join(__dirname, '..')

require('@babel/register')({
  root: rootPath, // This tells babel where to look for `babel.config.js` file
  ignore: [/node_modules/],
  only: [rootPath],
})
require('@babel/polyfill')
require('./app.js')
```
I would be really happy if someone from the babel team shed more light on this, preferably by giving deeper insight as to why the default behaviour was changed to only compile stuff inside the working directory.

**Comment by 2Pacalypse-** [comment]
Slight correction on my above post; you don't need the `only` directive. Which means that the solution posted by @helios1138 actually works. Not sure why it didn't work for me the first time. The reason why that works is because `babel-register` checks if [both the `ignore` *and* `only` options are `undefined`](https://github.com/babel/babel/blob/d35563ee1a7c3d8a69b5bc1b87fc8d6d883f00ea/packages/babel-register/src/node.js#L140), and only in that case it compiles things only inside the working directory. But it also ignores `node_modules` in that case, so as soon as you break that condition, you have to ignore `node_modules` manually. Very weird, I know.

But again, it would be very disingenuous to call this a "solution". It's a hacky workaround at best, which is why I'm still waiting on a reply from babel team on why this isn't a default behaviour anymore. Or at least provide an official way to achieve this functionality without having to rely on implementation details.

**Comment by PashaTurok** [comment]
@helios1138 If it is not difficult for you, could you give the code you posted
```
require('@babel/register')({
  extends: './.babelrc',
  ignore: [/node_modules/],
})
require('./src/index')
```
according to the project structure you had mentioned:
```
foo
  someLib.js
  .babelrc
bar
  index.js // import 'someLib.js'
  run.js // require('babel-register'); require('index');
  .babelrc
```
and explain in what file you use the code and from what file you import. I am sorry, but I can't make your code work. Please, help.

**Comment by helios1138** [comment]
@PashaTurok 
my file structure is something like
```
root/
  core/
    src/
      index.js
    .babelrc
    package.json
  project1/
    src/
      index.js
    .babelrc
    package.json
    run.js
  project2/
    src/
      index.js
    .babelrc
    package.json
    run.js
```
where `run.js` in `project1` and `project2` is
```js
require('@babel/register')({
  extends: './.babelrc',
  ignore: [/node_modules/],
  extensions: ['.js', '.ts'], // not relevant
})
require('./src/index')
```
and files inside `project1/src` or `project2/src` can import files from `core/src` like
```js
import { Server } from '../../core/src/Server'
```

**Comment by PashaTurok** [comment]
@helios1138 Thank you very much for your explanation. And could you say, in `run.js` can you have `import/export`?

**Comment by helios1138** [comment]
@PashaTurok no, `run.js` is the entry point, `import`/`export` are available after babel takes over in `index.js` and onwards

**Comment by PashaTurok** [comment]
@helios1138 Thank you very much again. You know, the code you provided seems the be the only full example in internet.

**Comment by PashaTurok** [comment]
@helios1138 Could you take a look at the following question, maybe you can suggest something: https://stackoverflow.com/questions/54620465/how-to-import-to-gulpfile-babel-js-from-js-file-that-is-located-in-root-project

**Comment by tjunnone** [comment]
@2Pacalypse- Thank you for your explanation, I though I was going crazy debugging this after upgrading to Babel 7. It does seem to me that setting `root` to a shared parent would be the logical solution but alas that does not work.

**Comment by nicolo-ribaudo** [comment]
`@babel/register` by default ignores everything outside of your cwd. You can prevent it by setting a custom ignore pattern, e.g.:

```js
require("@babel/register")({
  ignore: [/node_modules/]
});
```

**Comment by omarsafwany** [comment]
@helios1138 so I need to have `.babelrc` & a `run.js` file in each package I am importing from the `node_modules` in order to make it work? or do I need to just ignore in the current working directory?

I am mainly trying to load a package, run some tests against it using mocha but have been stuck with an error stating:
```
import components from "./components";
       ^^^^^^^^^^
SyntaxError: Unexpected identifier
```

**Comment by nicolo-ribaudo** [comment]
You need only one `run.js` (which first reauires `babel/register` and the your app), and one Babel config file.

**Comment by omarsafwany** [comment]
@nicolo-ribaudo 
Here's `.babelrc`:
```
{
    "presets": ["@babel/preset-env", "@babel/preset-react"],
}
```

Here's the `run.js`:
```
require("@babel/register")({
    ignore: ["node_modules"]
});
```

When I run `./node_modules/.bin/mocha config.js test/`, I get the following:
```
import components from "./components";
       ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Module._compile (/var/code/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (/var/code/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/var/code/test/renderSpec.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (/var/code/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (/var/code/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /var/code/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/var/code/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/var/code/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/var/code/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

What else is missing?

**Comment by nicolo-ribaudo** [comment]
What is the path of that file? Are there multiple package.json files?

**Comment by omarsafwany** [comment]
@nicolo-ribaudo Just one `package.json`.
I added a new file `config.js` as follows:
```
require("@babel/register")({
    extends: './.babelrc',
    ignore: [],
});
```
and called it before running and it finally worked.

**Comment by nicolo-ribaudo** [comment]
Closing as solved.
