### ISSUE TITLE
Incorrect associativity of exponentiation operator

### ISSUE THREAD

**Issue by poldridge** [babel/babel#8325]
## Bug Report

**Current Behavior**
Parenthesis used to override the right-associative behaviour of the exponentiation operator are lost when compiling to a target that has the exponentiation operator. This is reproduceable in preset-env with a target of node >= 7 and in preset-es2017.

**Input Code**
- REPL link: https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUACVAWAVDgjAJR4BM6hA3OgPTXoCiAHgA6zAAuAXOvgGwA06AOKx26LAChQkGAiRpMuAsRyp81EoXJVaDFmy7oSgkYaxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=Node-8.9&version=6.26.0&envVersion=1.6.2

```js
console.log( (4**1)**2 );
console.log( (4**1)**(1/2) );
```

**Expected behavior/code**
Expect the above code to transpile to something that logs `16` then `2`. Instead it transpiles to code that outputs `4` twice.

**Comment by hzoo** [comment]
Thanks for the report, seems like the printer is removing the parentheses! Looks like this should be fixed in v7 though (we haven't really done many backports and are trying to release an RC soon): https://babeljs.io/repl/build/master/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUACVAWAVDgjAJR4BM6hA3OgPTXoCiAHgA6zAAuAXOvgGwA06AOKx26LAChQkGAiRpMuAsRyp81EoXJVaDFmy7oSgkYaxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2017&prettier=false&targets=Node-8.9&version=7.0.0-beta.53&envVersion=7.0.0-beta.53

**Comment by poldridge** [comment]
Thanks for the quick reply! I'm glad to know it is fixed in v7 beta.

**Comment by loganfsmyth** [comment]
If you'd like to post a backport PR, I'd be up for landing it since this is certainly a bug that could frustrate people as more people adopt the exponential operator.

**Comment by poldridge** [comment]
@loganfsmyth I'm not sure if [this](https://github.com/babel/babel/pull/8333) is the correct way to make a Backport PR or if this should be backported to 5.x as well.

I confirmed that the added test fails without the fix and all tests pass with the fix included.

**Comment by existentialism** [comment]
Closing this as the PR has landed. We'll update when the next v6 version ships, thanks again @poldridge!
