### ISSUE TITLE
Incorrect placement of JSDoc comments

### ISSUE THREAD

**Issue by zavr-1** [babel/babel#8437]
## Bug Report

**Current Behavior**
The JSDoc for a function is moved to a random place.

**Input Code**

```js
/**
 * Pretend this works.
 */
const makeMarker = () => {

}

/**
 * Make a rule for initial replacement of markers.
 * @param {Marker} marker A marker used to cut and paste portions of text to exclude them from processing by other rules.
 * @returns {Rule} A rule to cut matched chunks.
 */
const makeCutRule = (marker) => {
  const { re, map, getReplacement, name } = marker
  const rule = {
    re,
    replacement(match) {
      const { lastIndex } = marker
      map[lastIndex] = match
      marker.lastIndex += 1
      const m = getReplacement(name, lastIndex)
      return m
    },
  }
  return rule
}

/**
 * Make a rule for pasting markers back.
 * @param {Marker} marker A marker used to cut and paste portions of text to exclude them from processing by other rules.
 * @returns {Rule} A rule to paste previously replaced chunks.
 */
const makePasteRule = (marker) => {
  const { regExp: re, map } = marker
  const rule = {
    re,
    replacement(match, index) {
      const m = map[index]
      delete map[index]
      return m
    },
  }
  return rule
}

export { makeMarker as default, makeCutRule, makePasteRule }
```

**Output Code**

```js
"use strict";

exports.__esModule = true;
exports.makePasteRule = exports.makeCutRule = exports.default = void 0;

/**
 * Pretend this works.
 */
const makeMarker = () => {};
/**
 * Make a rule for initial replacement of markers.
 * @param {Marker} marker A marker used to cut and paste portions of text to exclude them from processing by other rules.
 * @returns {Rule} A rule to cut matched chunks.
 */


exports.default = makeMarker;

const makeCutRule = marker => {
  const {
    re,
    map,
    getReplacement,
    name
  } = marker;
  const rule = {
    re,

    replacement(match) {
      const {
        lastIndex
      } = marker;
      map[lastIndex] = match;
      marker.lastIndex += 1;
      const m = getReplacement(name, lastIndex);
      return m;
    }

  };
  return rule;
};
/**
 * Make a rule for pasting markers back.
 * @param {Marker} marker A marker used to cut and paste portions of text to exclude them from processing by other rules.
 * @returns {Rule} A rule to paste previously replaced chunks.
 */


exports.makeCutRule = makeCutRule;

const makePasteRule = marker => {
  const {
    regExp: re,
    map
  } = marker;
  const rule = {
    re,

    replacement(match, index) {
      const m = map[index];
      delete map[index];
      return m;
    }

  };
  return rule;
};

exports.makePasteRule = makePasteRule;
//# sourceMappingURL=markers.1.js.map
```

**Expected behavior/code**
I expect JSDoc comments to remain attached to the functions. 

**Babel Configuration (.babelrc, package.json, cli command)**

```json5
{
  "plugins": [
    "@babel/plugin-syntax-object-rest-spread",
    ["@babel/plugin-transform-modules-commonjs", { "loose": true, "noInterop": true }]
  ],
}
```

**Environment**
- Babel version(s): [7.0.0-beta.56]
- Node/npm version: [e.g. Node v8.11.3]
- OS: [e.g. OSX 10.11.6]
- Monorepo [e.g. no]
- How you are using Babel: [e.g. `cli`]

**Additional context/Screenshots**

<table>
<tr><td>

![test](https://user-images.githubusercontent.com/21156791/43832236-ab873a46-9afe-11e8-944f-eeea29a83095.png)
</td></tr>
</table>

<table>
<tr><td>

![test](https://user-images.githubusercontent.com/21156791/43832294-e194c9fa-9afe-11e8-8f0e-9ef27f6f8b77.png)
</td></tr>
</table>

<table>
<tr><td>

![test](https://user-images.githubusercontent.com/21156791/43832334-05ec60d8-9aff-11e8-9020-f59d759deec8.png)
</td></tr>
</table>

**Comment by demurgos** [comment]
Your previous issue was closed because its tone was insulting. This one is too: the only improvement is that you don't use all-caps. Babel is used by thousands of production-grade projects, many of which use doc comments to generate their documentation. With a bit of humility, you may have recognized that maybe you are missing something instead of immediately calling the maintainers incompetent.

Now, to answer you issue: the output you see is expected behavior. Output generated by Babel is no longer source code (by definition, it's generated content): it is **not** intended to be editable source code. Comments are emitted in a best effort basis to help readability when debugging the output file. Babel output should be treated similarly to machine code: you do not generate documentation from machine code but from the source.
The input you pass to your documentation generation tool should be the the source code with ES-next syntax, not the lowered Babel output.

A [related issue](https://github.com/babel/babel/issues/8407#issuecomment-409183626) was opened last week. It contains more technical information about the reasons why Babel has this behavior currently. This is related to the way classicals parsers store trivia nodes such as comments and is an assumed choice to enable Babel to deliver all its features in a timely fashion.

This also a reminder that Babel is supported by a small team of volunteers. If you want to improve things, you can help and send PRs. You are not entitled to free support.

**Comment by zavr-1** [comment]
@demurgos I was not calling the maintainers incompetent but everyone who uses this software but fail to see the problem with JSDoc. It is exactly for the reasons that babel is used by thousands that the problem here is insulting to me -- babel is taken up as a religion and all religions are evil because they belong to masses who blindly follow their faith and don't even know what they are doing. What is more insulting is that you fail to understand the problem as well -- you propose I pass the code to documentation generation, which is not the point. The point is that developers use IDEs which is just as important as documentation generator. Babel brakes all the documented functions' highlighting which is what the screenshots are there for. The fact that you don't understand that makes you incompetent and you can't argue with that.

**Comment by demurgos** [comment]
Thanks for clarifying your issue: you're right that I misunderstood that you wanted to use doc generation. Instead the issue is related to the IDE's inline doc (from a consumer module). I still think that stating your use case clearly in your first message would have been more useful (IDEs cannot display documentation for my lib from consumer code).

I agree that the situation could be improved, probably by playing with leading/trailing trivia (the doc is treated as trailing trivia instead of leading trivia apparently).

**Comment by jjwtay** [comment]
I'm still seeing this in 7.4.3

**Comment by jjwtay** [comment]
Here's a little further explanation for what I'm seeing. I added using typescript doc comments to provide some ts feedback in a project I am working on. What I am noticing after running babel is all the comments are being moved up by 1 function so for example if I had

`/** @type { (payload: string) => { type: 'foo', payload: string }} */
export const foo = payload => ({ type: 'foo', payload })

/** @type { (a: number, b: number) => number } */
export const add = (a, b) => a + b`

After transpiling the type def for add will be moved up to foo so wherever I try to use this suddenly foo has an incorrect type definition.

**Comment by lipedeitos** [comment]
Still happening in 7.5.0 
I would love to give intellisense to our dev using only JSDOC.The "cleanest workaround" I'v found  was to move all components to TS, installing some packages, creating interfaces, changing the build process, .

**Comment by lipedeitos** [comment]
In my scenario, i have a bunch of React components and a dev team that uses them to build some applications and I would love to give intellisense to our dev using only JSDOC.The "cleanest workaround" I'v found was to move all components to TS, installing some packages, creating interfaces, changing the build process, .

**Comment by lipedeitos** [comment]
7.5.0 and this still happening, any prediction?

**Comment by lipedeitos** [comment]
7.5.0 and this still happening, any prediction?

Our scenario here is that we'v build a bunch of React Componentes, that I would love to give our dev team intellisense using only some JSDOC comments and the IDE understanding them.

The  "cleanest workaround" I'v found to give them that intellisense was to move all components to typescript generating a .d.ts (Seriously, It gave me a hell lot of work, changing build process, providing interfaces and a bunch of other stuff).

**Comment by rhendric** [comment]
I got sick of this myself and wanted to do something about it, but the parser code responsible for assigning comments to nodes is a little too arcane for me. On the other hand, it turns out to be very easy to write a plugin that patches this, at least for my project:

```js
const visitBlockLike = ({ node }) => {
  for (let i = 0, iMax = node.body.length - 1; i < iMax; i++) {
    const child = node.body[i];
    if (
      child.trailingComments
      && child.trailingComments[0].loc.start.line > child.loc.end.line
    ) {
      const nextChild = node.body[i + 1];
      if (nextChild.leadingComments) {
        nextChild.leadingComments.unshift(...child.trailingComments);
      } else {
        nextChild.leadingComments = child.trailingComments;
      }
      delete child.trailingComments;
    }
  }
};

const plugin = {
  visitor: {
    BlockStatement: visitBlockLike,
    Program: visitBlockLike,
  },
};

module.exports = () => plugin;
```

I have no idea if this helps with anyone else's use cases, so I'm not packaging it up as a fix (and I still would hope that someone who understands the Babel parser better can fix this at the source instead), but anyone who wants to give it a spin is welcome to it. Just paste the code in a file, put the path to the file first in your Babel config's plugins array, and see if that makes your life better.

**Comment by fabian-michael** [comment]
Hi, any news on this?
