### ISSUE TITLE
modules "common": interopRequireWildcard

### ISSUE THREAD

**Issue by christophehurpeau** [babel/babel#845]
Hello,

For a reminder here the current implementations of `interopRequire` and `interopRequireWilcard`

```
var _interopRequire = function (obj) { return obj && obj.__esModule ? obj["default"] : obj; };
var _interopRequireWildcard = function (obj) { return obj && obj.__esModule ? obj : { "default": obj }; };
```
However in the case of interopRequireWildcard it doesn't make sense to me

If I import a non compiled with babel lib with several functions in it, they all would be accessible through the property default...

Could you please clarify this ?

**Comment by sebmck** [comment]
It's a part of the CommonJS interop. It's following correct ES6 semantics and we've taken liberty with the CommonJS interop to ensure that it's as seamless as possible as it's not a 1:1 mapping because of how default exports work.

I can't really tell you easily *why* it's this way as there has been a lot of discussion that's lead up to it. See #95 #224 #493 #587 #673. Happy to answer any specific questions.
