### ISSUE TITLE
project root .babelrc not used when compiling a node module.

### ISSUE THREAD

**Issue by jhicken** [babel/babel#8452]
So this may not actually be a bug. It may be something I have done wrong. However, I'm not entirely sure. 

## Bug Report

**Current Behavior**
When transpiling a file in node_modules babel is not including my projects root .babelrc. In my case specifically, I am using babel-jest and the module I'm trying to transpile is `lodash-es/get`.

**Environment**
- babel-jest 23.4.2
- babel-core 7.0.0-rc.1
- Node 10.8.0 /npm 6.2.0
- OS: OSX 10.13.6
- How you are using Babel: babel-jest

**Possible Solution**
I have a fork that adds the root path to the directory structure when It is not there. Meaning every file that is transpiled with babel will have the chance to check for a .babelrc in your projects root folder. 

See
https://github.com/jhicken/babel/blob/fix-node-module-with-local-babelrc/packages/babel-core/src/config/files/package.js#L37

**Comment by loganfsmyth** [comment]
This is expected behavior. The scope of `.babelrc` files is been specifically limited to individual packages. If you want a project-wide configuration, you can use `babel.config.js` file. I'd recommend taking a look at https://babeljs.io/docs/en/next/configuration#what-s-your-use-case and https://babeljs.io/docs/en/next/babelconfigjs
