### ISSUE TITLE
Unneeded polyfills included in the bundle

### ISSUE THREAD

**Issue by astagi** [babel/babel#8454]
## Bug Report

**Current Behavior**
I tried to create a library with some reusable components using Vue CLI. A default Vue CLI project uses @vue/babel-preset-app, which uses @babel/preset-env and the browserslist config to determine the Polyfills needed for your project. By default, it passes useBuiltIns: 'usage' to @babel/preset-env which automatically detects the polyfills needed based on the language features used in your source code. In my index.js entry point I have the following code to register my components

```js
import Vue from "vue";
import HelloWorld from "./HelloWorld.vue"

const Components = {
    HelloWorld
}

Object.keys(Components).forEach(name => {
    Vue.component(name, Components[name])
});
```

**Expected behavior/code**
Targeting modern browsers I expected to not require a polyfill for Object.keys, but babel loads a polyfill for that increasing the bundle size, even targeting only chrome 68 (that should support it natively). I wonder if it's the expected behavior.

**Babel Configuration (only package.json, but tried with .babelrc as well)**

```js
{
    "browserslist": [
    "chrome 68"
  ]
}
```

**Environment**
- Babel version(s): 7.0.0-beta.47
- Node/npm version: 8.9.3
- OS: MacOS Sierra 10.12.6

**Comment by zloirock** [comment]
@astagi sorry, I can't reproduce it. Most likely this issue was fixed for a long time ago. With `corejs: 2`, `Object.keys` will be polyfilled for [those engines](https://github.com/babel/babel/blob/1f5444e96a6918cff28be929c00040887721ed4f/packages/babel-preset-env/data/corejs2-built-ins.json#L902-L912), with `corejs: 3` - for [those](https://github.com/zloirock/core-js/blob/4ad27a940371a915d5c7f87950413a3ea9560e75/packages/core-js-compat/src/data.js#L627-L632).

@Fuzzyma it's an absolutely different issue. Most likely the problem in your config. If it's still a problem for you, could you create a separate issue?
