### ISSUE TITLE
Extending Array swallows super class methods

### ISSUE THREAD

**Issue by Badestrand** [babel/babel#8467]
## Bug Report

**Current Behavior**
Extending from Array doesn't let you call the super class's methods anymore.

**Input Code**
```js
class CustomList extends Array {
	fun() {return 1}
}
const test = new CustomList()
console.log(test.fun())
```
yields `TypeError: test.fun is not a function` when compiled with Babel but executes when run in browser.

**Expected behavior/code**
It should output "1" like it does when not compiled via Babel (e.g. run like that in the latest Chrome).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
	entry: ['./app.js'],
	output: {
		filename: './out.js',
		path: __dirname
	},
	mode: 'development',
	module: {
		rules: [{
			loader: 'babel-loader',
			test: /\.js$/,
			query: {
				presets: ['env']
			}
		}]
	}
}
```

**Environment**
- Babel version(s): babel-core 6.26.3
- Node/npm version: Node v8.6.0, npm 5.3.0
- OS: macOS High Sierra
- Monorepo [e.g. yes/no/Lerna] ?
- How you are using Babel: via webpack

**Possible Solution**
-

**Additional context/Screenshots**
-

**Comment by nicolo-ribaudo** [comment]
Fixed in Babel 7 :tada: 

https://babeljs.io/repl/build/master#?babili=false&browsers=chrome%2068&build=&builtIns=usage&spec=false&loose=false&code_lz=MYGwhgzhAEDCCuEAuB7AtgGQJbOgUwA8k8A7AExgEEAnasAT2gG8AoASADN4SAKASmbU8SeNRLQAjAF8WM4ChK5iuALzQSeAO5xEqTDiT8WYEHmqHlSAHRdefPkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&sourceType=module&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.0.0-rc.1&envVersion=7.0.0-rc.1

**Comment by Badestrand** [comment]
Perfect, thanks!
