### ISSUE TITLE
Class property initializers works strange

### ISSUE THREAD

**Issue by shuvalov-anton** [babel/babel#847]
```js
class A {
  x = 5;
}

class B extends A {
  x = 0;
}

let b = new B();

console.log(b.x); // 5
```

**Comment by sebmck** [comment]
Actually totally just realised that this specific issue is detailed in the [gist](https://gist.github.com/jeffmo/054df782c05639da2adb#inheritance-hazards). There's no current way to handle inherited properties with ease due to the way properties are initialised.

**Comment by shuvalov-anton** [comment]
@sebmck thank you for the gist with explanation

**Comment by jeffmo** [comment]
Actually I think this should still work -- the gist describes semantics where child class properties will always overwrite parent class properties. The inheritance problems it mentions are just that child class properties cannot reference 'this' or 'super' in order to support any inheritance combination.

Specifically, child class initialization (per the gist) calls super.initializeProps() before then initializing its own props (overriding the parent class's props)

**Comment by sebmck** [comment]
@jeffmo Yeah, there's ways around it but I'm avoiding doing anything elaborate for the time being until things are more solidified.

**Comment by zloirock** [comment]
This desugaring [contrary to ES6](http://www.2ality.com/2015/02/es6-classes-final.html#super-constructor_calls). Assignment to `this` properties should be omitted below a `super` call. Then the problem will disappear.

```js
class A extends B {
  x = 42;
  costructor(){
    super();
    this.x++;
  }
}
// now:
class A extends B {
  costructor(){
    this.x = 42;
    super();
    this.x++;
  }
}
// correct:
class A extends B {
  costructor(){
    super();
    this.x = 42;
    this.x++;
  }
}
```
