### ISSUE TITLE
Why '7.0.0-rc.1' commit update all packages ?

### ISSUE THREAD

**Issue by zygeilit** [babel/babel#8475]
I don't quite understand how to use ‘learn’  in my project,  until I saw the upgrade of babel version, the link is [7.0.0-rc.1](https://github.com/babel/babel/commit/0a958861c9fcca8ae54ce158d1e9aec044c3c7c1#diff-e918bc613bd1a4e122e36dcda10c7cb4
)

Meanwhile, I also have some questions about the babel’s commits, seek for answers.

* Whatever which module in packages was updated, the totall modules that in packages will also be updated at the same time?  ( e.g. the 7.0.0-rc.0 version commit ) ？

* The ‘learn publish’ command executed by developer or Jenkins after ‘git push’ ?

* How babel project use ‘lerna bootstrap [—hoist]’ command？If use ‘learn bootstrap’ directly maybe need wait  much longer. (many modules, many dependencies). So I want to know more details about using ‘lerna bootstrap [—hoist]’

**Comment by xtuc** [comment]
Yes we use Lerna in fixed mode which bumps every package at the same version at once, that avoids having to deal with incompatibilities etc.

Currently the core team used to publish locally.

I'm closing this since it's not related to Babel, feel free to open an issue on Lerna's repo (or email me some questions).
