### ISSUE TITLE
@babel/plugin-transform-runtime: use `supportsStaticESM` for `useESModules` by default

### ISSUE THREAD

**Issue by lixiaoyan** [babel/babel#8516]
## Feature Request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

According to <https://github.com/babel/babel/pull/8485>, `@babel/plugin-transform-runtime` should use `supportsStaticESM` as the default value of `useESModules`.

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**

**Comment by loganfsmyth** [comment]
The main difficulty here, which is what puts me on the fence about it, is this. If a user does

```
preset: [
  ['@babel/env', { modules: "commonjs"}],
],
plugins: [
  '@babel/transform-runtime'
]
```
in an environment where `supportsStaticESM` is set (and this useESModules = true automatically), their code will end up doing
```
require("@babel/runtime/helpers/esm/classCallCheck")
```
which could technically fail, because there is no guarantee that `require` will ever be able to import an ES6 module, and even if it does, the injection logic currently assumes that `require` will return the helper function itself, and the require above would return an object with a `.default` property.

So it's not just that we want to know `supportsStaticESM`, we want to know that the ESM _won't_ be compiled to CommonJS.

**Comment by loganfsmyth** [comment]
I've posted https://github.com/babel/babel/pull/8520 with this as an opt-in behavior. I'm not sure I'm comfortable with it being the default though.

**Comment by loganfsmyth** [comment]
@lixiaoyan With the opt-in behavior, would you be alright closing this? We can always see how it goes and consider making it default in a future major release, but I think it's too soon for it to be default.
