### ISSUE TITLE
Nested output folder generated on each babel-cli command.

### ISSUE THREAD

**Issue by kumarrk5** [babel/babel#8548]
## Bug Report

**Current Behavior**
Nested output folder generated on each babel-cli command.

**Input Code**
- babel -d ./server/build ./server -s
- In package.json ,
```js

	"scripts": {
		"start": "nodemon --watch server --exec babel-node server/server.js",
		"build-server": "babel -d ./server/build ./server -s",
		"build-client": "webpack --progress --config ./webpack.config.prod.js",
		"start-server": "node ./server/build/server.js"
	},

```

**Expected behavior/code**
babel-cli need to clear the output folder before it executes.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
	"presets": [ "es2015", "stage-1" ],
	"env": {
		"test": {
			"plugins": [ "istanbul" ],
			"presets": [ "es2015", "react", "stage-0" ]
		},
		"production": {
			"plugins": [ "transform-remove-console" ]
		}
	}
}
```

**Environment**
- Babel version(s): v6.26.0
- Node/npm version: v8.11.1
- OS: Windows 10
- Monorepo [ yes/no/Lerna]
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
![nested output folder](https://user-images.githubusercontent.com/8487243/44651873-0afe1f80-aa1d-11e8-915b-566ab1acf92c.PNG)
![babel-cli command](https://user-images.githubusercontent.com/8487243/44652236-fec69200-aa1d-11e8-9f9b-9bf3fad433ef.PNG)

**Comment by loganfsmyth** [comment]
I think at the end of the day, compiling from a source directory into a subdirectory of that same source is always going to be a very edgecasey.

> babel-cli need to clear the output folder before it executes.

Even with we did that, we'd still have weirdness when running the CLI with `-w` because it'll be creating a new file, then it'll see that new file, and compile it.

We could technically exclude the output directory when computing input files, but it seems like it'd be a lot simpler rely on users to not output into the same directory they are compiling from, unless they really want to. For instance, you could imagine someone doing

```
mod/
  index.jsx
```
and doing `babel mod -d mod` and relying on Babel to create `mod/index.js` by stripping the extension. If we indiscriminately deleted the content of the output directory, it could be quite dangerous.

**Comment by loganfsmyth** [comment]
Babel has no way to differentiate between a folder create by someone else and a folder created by Babel. When Babel starts, it's just a folder.

**Comment by milesj** [comment]
Don't build babel into the same source directory.

**Comment by kumarrk5** [comment]
Now I Understand.
Thanks @milesj.
