### ISSUE TITLE
Name collision when re-processing transpiled code

### ISSUE THREAD

**Issue by haggholm** [babel/babel#8571]
## Bug Report

**Current Behavior**

This is a very confusing bug, and I want to say first that I’m not sure where the bug is (in Babel or elsewhere), so I am hoping for feedback in order to refine this bug report and possibly move it. (Is it more likely a Babel bug, a Webpack bug, a minifier bug?)

The problem: Our project uses https://www.npmjs.com/package/clipboard, which is published to NPM in transpiled form. As such, it contains the `_typeof` helper:

```js
 var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
        return typeof obj;
    } : function (obj) {
        return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;
    };
```

After transformation via Webpack (4.17.1), Babel (6.26.3) `uglifyjs-webpack-plugin` or (currently) `terser-webpack-plugin` (1.0.2, `terser` 3.8.2), it seems that the `typeof Symbol.iterator` part has been transformed a second time, and resulted in a name collision. The minified code, reformatted for legibility:

```js
r = "function" == typeof Symbol && "symbol" === r(Symbol.iterator) ?
	function (e) {
		return void 0 === e ? "undefined" : r(e)
	} :
	function (e) {
		return e && "function" == typeof Symbol && e.constructor === Symbol && e !== Symbol.prototype ?
			"symbol" :
			void 0 === e ? "undefined" : r(e)
	}
```

Since *both* `typeof` instances were minified, presumably via the `_typeof` helper, to the same name (here: `r`), the expression fails to evaluate because the `r` in `r(Symbol.iterator)` isn’t initialized yet.

**Input Code**

Unfortunately, I have been unable to reproduce this in a minimal repro case. Importing the same library (`clipboard`) in a minimal sample and minifying it with the same options did not reproduce the behaviour.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": ["babel-preset-env", {
    "browsers": [
	">5%",
	"IE >= 11",
	"last 2 Chrome versions",
	"last 2 ChromeAndroid versions",
	"last 2 Edge versions",
	"last 2 Firefox versions",
	"last 2 iOS versions"
    ]
  }],
  "plugins": [
	"babel-plugin-lodash",
	"babel-plugin-syntax-dynamic-import",
	"babel-plugin-transform-decorators-legacy",
	"babel-plugin-transform-class-properties",
	"babel-plugin-transform-flow-comments",
	"babel-plugin-transform-object-rest-spread",
	"babel-plugin-transform-react-jsx"
  ]
}
```

**Environment**
- Babel version(s): 6.26.3
- Node/npm version: Node 8.11.1/npm 6.4.0
- OS: Ubuntu 18.04
- Monorepo: No
- How you are using Babel: `babel-loader`/Webpack

**Comment by nicolo-ribaudo** [comment]
Can you try to disable the minifier and see if the problem is still there? Babel should generate the helper the second time with a different name, to avoid conflicts (https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=AQNwhgTsD6AuCeAHApgewGbALzASjwAyvALYBGqANtljgEToCuAdgMawCWqzdwAZH1xI0mYuSoA6DrGQQwsVFFr0AzqQqVeAfmBM2nbsAAUqMgCsAlMADeAKGAPHDiMliMIzIfkymzAbntHAF9gAC5dFnYuTxNzKzsnJxc3D2BffkE8ESJ1Khp6PSjuXgE08wlWbhVYCEZ2RXyc8WpS9IBCWiaNCUQIVAUs4B06NWbecKyCXwCnIICgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.0.0&envVersion=7.0.0%2Bpr.8584)

**Comment by haggholm** [comment]
It only happened when minified, so it may well be a minifier bug. I was not able to reproduce it in a minimal scenario even *with* a minifier, though.

**Comment by nicolo-ribaudo** [comment]
Are you working on a private application? If not, can you share it?

**Comment by haggholm** [comment]
Unfortunately, yes, it’s proprietary.

**Comment by nicolo-ribaudo** [comment]
I'm sorry but I don't think that we can help very much without being able to reproduce the issue 😔
Last thing to check: what is the unminified output of the code you posted?

**Comment by elado** [comment]
I also have this issue. And it's hard to isolate.
Looks like this isn't consistent either.

I have a module which contains a typescript transpiled code with 

```js
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ?
 function (obj) { return typeof obj; } : function (obj) { return obj && typeof 
Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? 
"symbol" : typeof obj; };
```

then babel turns it into (incorrect):

```js
  var _typeof = typeof Symbol === "function" && _typeof(Symbol.iterator) === "symbol" ? function (obj) {
    return _typeof(obj);
  } : function (obj) {
    return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : _typeof(obj);
  };
```

and sometimes into (correct):

```js
  var _typeof = typeof Symbol === "function" && _typeof2(Symbol.iterator) === "symbol" ? function (obj) {
    return _typeof2(obj);
  } : function (obj) {
    return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : _typeof2(obj);
  };
```

The issue isn't consistent; if I manually go to the file and add some lines of code above that `var _typeof` it suddenly works, then comes back later on.
I tried to disable `cacheDirectory`, but it doesn't help.

Also tried to add `@babel/plugin-transform-runtime`, hoping it wouldn't inject the helper inline, but that didn't do anything either.

I'm on latest versions of babel, babel-loader, webpack etc.

**Comment by cipater** [comment]
Having the same issue. I don't have much to add beyond the other two... Though my experience does seem to differ insofar as minification had no effect—which is say the issue was still present when disabled. And, annoyingly, the issue only occurs in production. I was able unable to reproduce the issue locally with webpack-dev-server.

And like @haggholm, it's occurring in a large private app, and I've been unable to reproduce the issue in a smaller test case.

My unminified output looks like @elado's; a mix of `_typeof` and `_typeof2`. Having only the `_typeof2` function defined in the output ... so the calls to `_typeof` (or `r` in the minified version) throw the error. Unlike @elado, there is zero inconsistency for me.

Occurring with Babel 7.2.2 and Webpack 4.29.3
Reverting to Babel 6.26.3 and Webpack 3.12.0 fixes the problem.

**Comment by 1st8** [comment]
Did you find a way to solve this without downgrading Babel & Webpack?

I am having the exact same issue and can't find solution... also in a larger private project so I can't share anything to reproduce it now.

**Comment by cipater** [comment]
If I recall correctly, this issue ended up being a result of my upgrading http://github.com/rails/webpacker from 3.x to 4.0. One of changes introduced in 4.0 was a decision to have `babel-loader` transpile the `node_modules` folder, which it previously was not doing. 

Excluding the `node_modules` folder fixed the issue for my setup:

https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md#excluding-node_modules-from-being-transpiled-by-babel-loader

Though as @elado stated, it doesn't really solve the root problem.

**Comment by nicolo-ribaudo** [comment]
Cam you try to isolate the node module which is giving problems?

**Comment by 1st8** [comment]
Yes!!!

It was a package which caused this, yanking it from our codebase fixed it.

This is the offending code: https://github.com/AllenFang/react-bootstrap-table/blob/master/dist/react-bootstrap-table.js#L4403

**Comment by nshoes** [comment]
@cipater that solution worked for me too! Thanks.
