### ISSUE TITLE
Lerna changed to non-FLOSS license

### ISSUE THREAD

**Issue by curiousdannii** [babel/babel#8579]
Just a heads up that Lerna has changed to a non-FLOSS license: https://github.com/lerna/lerna/pull/1616

I haven't seen any indication of whether the Lerna devs intend to change the license of version 2 as well. Pinning to 2.11.0 or 3.2.1 may be wise anyway, unless/until someone commits to maintaining a FLOSS licensed fork.

**Comment by xtuc** [comment]
Does it means that Lerna's licence is now incompatible with Babel's one? Lerna is not user facing in Babel so I guess it's fine, none of us are coming from those banned companies (yet?).

There's nothing actionable here, closing for now.

**Comment by StoneCypher** [comment]
I am, actually, using Babel directly.  Unfortunately someone incorrectly closed my issues both here and at lerna without letting me say so, even though my original text makes that clear.

I am currently of the belief that building Babel from scratch on Travis is illegal because of the lerna license change.  I am worried the thing I've been building is scrapped, and the people making this change are responding to something very different than what I'm saying and not honoring my actual questions

This is really unfortunate `:(`

**Comment by loganfsmyth** [comment]
@StoneCypher Could you clarify what you mean by building Babel from scratch? 

> I am worried the thing I've been building is scrapped

Is this something built on top of Babel's monorepo, or an independent project using Babel? It's not clear what you're doing, so it is hard to evaluate how licensing might affect you.

**Comment by StoneCypher** [comment]
@loganfsmyth - the other ticket, which is incorrectly closed as a duplicate, then locked so that I can't respond, is about my attempt to use babylon, the parser underneath of babel, to build a custom language that works in tandem with the rest of babel stuff.

In order to work with babylon, yes, you must build babel from scratch.  My current understanding is that no continuous integration provider is currently legal under this license change, and since my testset is so large, that means that I need to find out whether what I'm doing is illegal.

**Comment by loganfsmyth** [comment]
The license is granted to the users of the code. IANAL, but it doesn't seem likely that the provider of the execution environment would affect the legality of licensing for your own usage.

**Comment by dougrich** [comment]
@xtuc While it might not be actionable, @jamiebuilds (the person who changed Lerna's license) is currently asking the companies listed to also not use Babel.

Quoting from https://github.com/palantir/tslint/issues/4132

> Also, stop using my tools (such as Babel), I don't support you, and I don't want my work to benefit your awful company.

I came here for this same question as this issue - Lerna has changed, Lerna has ties to Babel's build system, Babel is being cited in issues by the person who made the change, what will happen to Babel?

**Comment by StoneCypher** [comment]
oh, i see

so i just can't ever do business with or sell my work to the various companies that this one individual suddenly decided they didn't like one day, because i relied on something a different person did that they took over a couple years ago?

**Comment by StoneCypher** [comment]
who is jamiebuilds and why is he claiming babel as his own?

i thought sebastien made babel?

**Comment by dougrich** [comment]
@StoneCypher @jamiebuilds is the one who changed Lerna's license. See https://github.com/lerna/lerna/pull/1616

**Comment by StoneCypher** [comment]
wait this guy isn't even listed on the babel team

why does he get to tell people to not use "his" babel?

https://babeljs.io/team

**Comment by curiousdannii** [comment]
@StoneCypher While Babel uses lerna@2.11.0 everything is fine. My concern was if the lerna devs should publish 2.11.1 with the license change and Babel still uses ^2.11.0 which would pick up the new version.

**Comment by StoneCypher** [comment]
well, if babel intends to permanently pin lerna below this change, or exit lerna, maybe there's no problem

**Comment by shirbr510** [comment]
Everything is ok, see https://github.com/lerna/lerna/pull/1633
