### ISSUE TITLE
Import of plain text

### ISSUE THREAD

**Issue by hkjels** [babel/babel#860]
I wasn't able to find it in the spec, but importing plaintext as javascript strings is quite a regular task that really should be supported.

```javascript
@import * as template from './template.html';
```

**Comment by sebmck** [comment]
Since babel just compiles the module syntax to a module loader format it's up to the module loader to support what type of imports it wants. For example [stringify](https://github.com/JohnPostlethwait/stringify) for browserify and [html-loader](https://github.com/webpack/html-loader) for webpack allow you to import html.

**Comment by AlexLeung** [comment]
So how is this done in babel then? What's the equiivalent to `html-loader` or `stringify`?

**Comment by danez** [comment]
There is no equivalent. It is not babels task to do things like this. Babel is a compiler to compile modern Javascript syntax (Es201X) to ES5, but it does not add runtime features or in any way interprets the code.
Use webpack, rollup, browserify or any of the other bundlers.

**Comment by AlexLeung** [comment]
The explanation makes sense. Unfortunate though that I'll need to add in an entire webpack setup now instead of just being able to use nodemon and babel-cli.

**Comment by smeijer** [comment]
Old issue; but [`babel-plugin-inline-import`](https://www.npmjs.com/package/babel-plugin-inline-import) is doing fine for me.
