### ISSUE TITLE
[TypeScript]: Type reexport show "type was not found" warning.

### ISSUE THREAD

**Issue by kalekseev** [babel/babel#8639]
## Bug Report

**Current Behavior**
If module reexport type from another module like `export { ItemType } from './Item'` the following warning is printed "export 'ItemType' was not found in './Item'"

**Expected behavior/code**
The warning should not be printed or should be a way to disable such warnings.

**Babel version**
`@babel/core` and `@babel/preset-typescript` version 7.0.0

**Comment by nicolo-ribaudo** [comment]
Can you show the full output? Babel doesn't print that warning (https://github.com/babel/babel/search?q=%22was+not+found%22&unscoped_q=%22was+not+found%22)

**Comment by kalekseev** [comment]
```
WARNING in ./frontend/common/utils/index.ts 4:0-68
"export 'Action' was not found in './actions'
 @ ./frontend/features/routes/Router.tsx
 @ ./frontend/app/App.tsx
 @ ./frontend/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./frontend/index
```

**Comment by nicolo-ribaudo** [comment]
Ok, that warning is generated by your bundler because Babel doesn't remove the export.
Since Babel works on a per-file basis (like TypeScript with the `--isolatedModules` option), it can't remove that export because it doesn't know that it is a type-only export.

As a workaround, you can use
```js
export { ItemType as t_ItemType } from './Item'
export type ItemType = t_ItemType;
```

I'm closing this, since it is already tracked at https://github.com/babel/babel/issues/8361.
