### ISSUE TITLE
Comments starting with //= moved to previous line

### ISSUE THREAD

**Issue by fabien-michel** [babel/babel#8684]
# v7 Regression

**Describe the regression**
A comment line starting with "//=" is moved at the end of the previous code line without comment
This is a problem for some process/macro relies on theses specifics comments lines to act.
This doesn't occur with pre 7 version of babel

**Input Code**

```js
var toto = 1;
//= my comment

var truc="bidule";
// my comment
```

Compile to :

```js
var toto = 1; //= my comment

var truc="bidule";
// my comment
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  { compact: false, presets: ["@babel/env"] }
}
```

**Expected behavior/code**
```js
var toto = 1;
//= my comment

var truc="bidule";
// my comment
```

**Environment**
- Babel version(s): v7.0.0
- Node/npm version: Node 7

**Comment by loganfsmyth** [comment]
Weird. It's certainly strange, and I'm happy to leave this in case someone wants to look into it. That said, Babel hasn't generally made much of a guarantee about comment placement, so this is likely going to be a low priority.

**Comment by fabien-michel** [comment]
I can have a look into the code, just if someone can spot me the part where the problem most probably occur.

**Comment by shixish** [comment]
This is a bummer

**Comment by loganfsmyth** [comment]
@shixish Mind if I ask your usecase for specific comment placement? Like I said, if someone wants to try to address this, I'm not against it.

**Comment by phifa** [comment]
Struggling with this too. I need comments in the compiled code (also not minifying) and this makes it hard to read.

**Comment by mrtnzlml** [comment]
Seems like the behavior changed a  little bit from the first post: all comments are now moved to the previous line (not only `//=`). Input code:

```js
var toto = 1;
//= my comment

var truc="bidule";
// my comment
```

Compiles to:

```js
var toto = 1; //= my comment

var truc = "bidule"; // my comment
```

I have a similar case where I need to preserve the position of the comment for Flow suppress annotations. For example this code:

```js
const aaa = 1;

// $FlowExpectedError
const bbb: string = aaa;
```

Turns into:

```js
const aaa = 1; // $FlowExpectedError

const bbb = aaa;
```

Which changes the meaning. Consumers of such package are getting errors because of this. I found out that option `retainLines` can fix the issue but the rest of the code looks very bad.

Could you maybe give me a hint in what part of Babel should be this fixed?
