### ISSUE TITLE
'--experimental-worker' unknown option

### ISSUE THREAD

**Issue by cosat20** [babel/babel#8726]
## Bug Report

**Current Behavior**
`babel-node --experimental-worker app.js`
Using this command for start my project in development mode. Output is
 
`  error: unknown option `--experimental-worker'`

config .babelrc:
`{
  "presets": [
    ["env", {
      "targets": {
        "node": "current"
      }
    }],
    "stage-0",
    "flow"
  ],
  "plugins": [
    "transform-decorators-legacy",
    "transform-flow-strip-types"
  ]
}
`

this flag is need for use `worker threads`

**Comment by liamrathke** [comment]
I'm getting this error as well, using Node v11.4.0

**Comment by liamrathke** [comment]
@nicolo-ribaudo I don't think that's necessary, I was able to find a workaround. 

I was using [Nodemon](nodemon.io), and it turns out that there's an option to include environment variables as `NODE_OPTIONS` in the `nodemon.json` file. This did the trick for me: 

```
{
  "watch": ["server"],
  "ext": "js",
  "env": {
    "NODE_OPTIONS": "--experimental-worker"
  },
  "exec": "babel-node server/server.js"
}
```

How to integrate Nodemon + `worker_threads` into a normal NodeJS app:

1. Set up [Nodemon](nodemon.io)
2. Add a `nodemon.json` file to the root folder (example [here](https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md))
3. Add this to `nodemon.json`: 
 ```
"env": {
    "NODE_OPTIONS": "--experimental-worker"
  }
```

If you're setting up Nodemon for the first time, I found [this](https://alligator.io/workflow/nodemon/) tutorial very helpful.

**Comment by guanzo** [comment]
I'm creating a worker thread for a file that contains decorators that need to be transpiled by babel. Originally, my app was a single process that was run with `nodemon --exec babel-node index.js`, and the decorators were correctly transpiled. Now, when I try to create the Worker, node complains about an "unrecognized token" (the decorator's @ symbol). Is there anyway to start a worker with `babel-node`?
