### ISSUE TITLE
Support destructuring keyed collections such as `Map`

### ISSUE THREAD

**Issue by tgecho** [babel/babel#877]
It would be great to allow object destructuring to work on keyed collections in addition to plain objects.

`let {foo} = new Map([['foo', 'bar']]);`
`let {foo} = Immutable.Map({foo: 'bar'});`

At least Map and Immutable.Map have `keys`, `values` and `get` methods, so in theory they should be generically detectable.

I can't find anything about the ES6 spec intending to support this combination, so I'm wondering if anyone has any thoughts before I take a stab at adding this.

**Comment by sebmck** [comment]
This isn't a part of the spec and will significantly slow down object destructuring if it's added.

**Comment by tgecho** [comment]
Fair enough, which is why I asked first :)

Is there a reasonably straightforward way to create a standalone addition without maintaining a fork? Could this be palatable as a playground addition with an alternate syntax such as `#=`?

I don't mean to be a bother, I'm just trying to reconcile my love of destructuring with my use of Immutable.js.

Thanks either way!

**Comment by sebmck** [comment]
> Is there a reasonably straightforward way to create a standalone addition without maintaining a fork? Could this be palatable as a playground addition with an alternate syntax such as #=?

Not really. Related would be the planned transformer API #607 but it wont allow you to do syntax modifications, see the discussion in #568 on why that's not viable.

**Comment by tgecho** [comment]
Well, I'm afraid you did not make my day. However, 6to5/babel already made my week, so I still owe you many thanks!

Now I'm off to talk to he TC39 folks ;)

**Comment by AlexeyFrolov** [comment]
+1 for that feature. I think, we need to make it more general case interface is the same. At least in Clojure it is.

**Comment by hleumas** [comment]
I have written simple benchmark to evaluate performance cost of implementing more general destructuring:

```js
var Benchmark = require('benchmark').Benchmark;

var suite = new Benchmark.Suite;

function get(obj, key) {
  return obj.get ? obj.get(key) : obj[key]
}

var object = {
  a: [1,2,3],
  b: "here",
  c: "who knows"
}

var result = suite.add('key access', function() {
  var a = object['a']
  var b = object['b']
  var c = object['c']
}).add('get access', function() {
  var a = get(object, 'a')
  var b = get(object, 'b')
  var c = get(object, 'c')
}).run()

console.log(result)

```

Results:
**key access**:  (10.0 +- 0.6)e-5 ms / cycle
**get access**: (19.0 +- 0.9)e-5 ms / cycle

or
**key access**:  (3.3 +- 0.2)e-5 ms / assignment
**get access**: (6.3 +- 0.3)e-5 ms / assignment

or
**key access**: 30000 +- 2000 assignments per millisecond
**get access**: 16000 +- 2000 assignments per millisecond

Now, it is hard to believe for me, that this would be bottleneck in any real world scenario. Even in the tiny promile of situations where this is a bottleneck, you can simply improve performance by doing destructuring manually.

On the other hand, implications of having **extensible** destructuring are huge. This is not only about supporting es6 Map, or some Immutable Map (which is currently huge pain to use just because of lack of destructuring). It is about empowering authors of new data structure libraries so their data structures don't have to be second class citizens.

The implementation would be pretty straightforward and backward compatible. It would be huge help for rapidly growing community of https://github.com/facebook/immutable-js/ users and dev-stacks that rely on immutable data structures like https://github.com/este/este

One of the biggest pain of using immutable js these days is its verbosity. And this would help it a lot.

What about enabling it as an experimental feature? What harm would it cause?

Thank you very much @sebmck for reading this huuge comment of mine and thinking about it:) Also, @leebyron and @sebmck, what do you thing about this?

**Comment by hleumas** [comment]
Anyone interested in the extensible destructuring, see my proposal here:
https://github.com/vacuumlabs/es-proposals/blob/master/extensible-destructuring.md

**Comment by sebmck** [comment]
@hleumas This would be a breaking change and so is unfortunately very unlikely to make it into JavaScript.

**Comment by hleumas** [comment]
@sebmck Why would it be a breaking change?

**Comment by sebmck** [comment]
@hleumas 

```javascript
var foo = {
  get(key) {
    return key + "bar";
  },
  bar: "foo"
};
var { bar } = foo;
assert.equal(bar, "foo"); // not "barbar"
```

For that reason it would have to use a symbol. If this makes it to a stage 0 proposal then I'd be more than happy to add it but for the moment it's equivalent to a non-standard feature.

**Comment by hleumas** [comment]
@sebmck Ok, I see. What about using `@@get` (similar to `@@iterator`) instead ?

**Comment by sebmck** [comment]
@hleumas Yeah, that's a symbol.

**Comment by hleumas** [comment]
@sebmck thanks for your feedback! I will update the proposal accordingly.

**Comment by hleumas** [comment]
@sebmck Thank you very much! Please, take a look to the current proposal:
https://github.com/vacuumlabs/es-proposals/blob/master/extensible-destructuring.md

I would appreciate any feedback you have!

**Comment by sebmck** [comment]
@hleumas No problem :blush: Might also be worth asking esdiscuss for feedback as I have a feeling that this exact behaviour may have been discussed before for some specific reason.

**Comment by hleumas** [comment]
@sebmck @AlexeyFrolov @tgecho Check this out:

https://www.npmjs.com/package/babel-plugin-extensible-destructuring

:)
