### ISSUE TITLE
Plugin options do not overwrite the same plugin option inherited from a Preset

### ISSUE THREAD

**Issue by ivosabev** [babel/babel#8799]
## Bug Report

**Current Behavior**
I am using `babel-preset-react-app` which uses the plugin `@babel/plugin-transform-runtime` with an option `useESModules: true`. Later in my config I include the same plugin with option `useESModules: false`, but my value does not overwrite the preset value as expected and it stays as `true`.

**Babel Configuration (babel.config.js)**

```js
module.exports = {
  presets: ['@babel/env', 'react-app'],
  plugins: [
    [
      '@babel/plugin-transform-runtime',
      {
        corejs: 2,
        helpers: true,
        regenerator: true,
        useESModules: false,
      },
    ],
  ],
};```

**Environment**
- Babel version(s): 7.1.2
- How you are using Babel: `babel-node`

**Comment by mbrowne** [comment]
This is indeed an issue, but fortunately I found a workaround for this specific case. There is an undocumented option, `useESModules`:

`['react-app', { useESModules: false }]`

I posted more details here:
https://stackoverflow.com/a/57315637/560114

**Comment by nicolo-ribaudo** [comment]
While I understand that in this case it is unfortunate, this is working as intended.
Babel allows you to run the same plugin multiple times, because with different options they can do two different compatible things. For example:

```json5
{
  plugins: [
    ["rename-vars", { from: "cat", to: "mouse" }, "rename cat to mouse"],
    ["rename-vars", { from: "fish", to: "cheese" }, "rename fish to cheese"],
  ]
}
```

```js
// input
var cat = new Animal();
var fish = new Food();

cat.eat(fish);
```

```js
// output
var mouse = new Animal();
var cheese = new Food();

mouse.eat(cheese);
```

If a preset wants to allow you to configure a plugin, it should either accept its options and then forward them, or allow disabling that plugin so that you can manually re-enable it with custom options.
