### ISSUE TITLE
CDN support for @babel/core

### ISSUE THREAD

**Issue by rbiggs** [babel/babel#8827]
## Feature Request

Currently there is no CDN version of Babel7. There is for 6.x.

Is it possible to create a CDN version that can be used in online code editors like Codepen?

**Comment by hzoo** [comment]
I'm kind of confused by the question here? We don't provide a cdn version for Babel 6 either (at least ourselves), usually some other service already does it like unpkg: https://unpkg.com/babel-core@6.26.3/, https://unpkg.com/@babel/core@7.1.2/

If you mean a standalone version (webpack'd) then it's just `@babel/standalone` instead of `babel-standalone` https://babeljs.io/docs/en/babel-standalone which should work for you. And I would assume code-pen would eventually update 😁

**Comment by rbiggs** [comment]
That's right, I was looking for a 7 version of the one mentioned in the docs for using Babel in the browser: https://babeljs.io/setup#installation
But the browser version is: https://unpkg.com/babel-standalone@6/babel.min.js
I'm curious where the link to that is. I've searched thorough in all the 7.1.0 doc pages and haven't seen that link. It would probably be good to make the link a bit more obvious.

**Comment by hzoo** [comment]
oh ok we can just update that link then!

**Comment by rbiggs** [comment]
Perfect.
