### ISSUE TITLE
Architecture overhaul

### ISSUE THREAD

**Issue by sebmck** [babel/babel#883]
Ticks do not necessarily mean completed and may refer to deferration or reduction in scope.

 - Type inference
 - Dynamic scope tracking
 - Replace nodes and retain traversal position
 - Inherit string quotes
 - Pluggable parser
 - Transformer API
 - Better comment attachment
 - Split up CLI
 - Self host
 - Possibly switch to the Shift AST (???)
 - Contribution guide

**Comment by sebmck** [comment]
Please email me if you're interested in helping out.

**Comment by sebmck** [comment]
Unlocking this since I'd like some collaboration on this. Is anyone interested in maintaining a `babel-cli` package? I'm looking at spinning it out so someone else can "own" and maintain 

/cc @matthewrobb @gsklee You guys both emailed me looking to help, thanks!

**Comment by hawkrives** [comment]
I'd be willing to help maintain a `babel-cli` – I don't know if I could take the entire thing on, but I'd love to help.

**Comment by chicoxyzzy** [comment]
count me in

**Comment by gsklee** [comment]
@sebmck I'm most interested in the transformer API and all kinds of internal optimizations. Let me know when I can be of help :)

**Comment by swirlycheetah** [comment]
I'd be interested in helping out maintaining the CLI too.

**Comment by neVERberleRfellerER** [comment]
I would like to help with this overhaul. However, I won't have time till ~15th March.

**Comment by swirlycheetah** [comment]
@sebmck What are your thoughts in terms of splitting out the CLI? Would be good to chat around what's required and see how other projects do it.

**Comment by coreh** [comment]
Some questions about this and retro-compatibility: Would the new external CLI inherit the existing command name, and accept the same arguments as `babel(1)`? Would the new package also be responsible for `babel-node`?

Also with this architecture overhaul, would we essentially be then on 5.x?

**Comment by Naddiseo** [comment]
I've been playing around with the pluggable parser idea at home. I have a general idea on how to implement one, but I'm currently struggling with what the interface to it would look like. And there is the issue of what happens when two pluggins conflict.

**Comment by bvalosek** [comment]
@sebmck can you elaborate on how you see type inference playing a part in babel? 

The tern project had some great type inference for editors/IDEs but ES6 process on that is non-existent and will not be tackled anytime soon.

**Comment by sebmck** [comment]
@swirlycheetah

> What are your thoughts in terms of splitting out the CLI? Would be good to chat around what's required and see how other projects do it.

Just abstract it out into another package and then alias the `bin` scripts in `babel` to them and log a deprecation message whenever you'd run them telling people to install/use `babel-cli`.

@coreh

> Some questions about this and retro-compatibility: Would the new external CLI inherit the existing command name, and accept the same arguments as babel(1)?

Yep, ideally the `babel` package would install `babel-cli` for the remainder of 4.x for backwards compatibility and log a deprecation message.

> Would the new package also be responsible for babel-node?

Yep.

> Also with this architecture overhaul, would we essentially be then on 5.x?

Not unless it introduces breaking changes which is highly unlikely.

@Naddiseo

> I've been playing around with the pluggable parser idea at home. I have a general idea on how to implement one, but I'm currently struggling with what the interface to it would look like. And there is the issue of what happens when two pluggins conflict.

Check out marijnh/acorn#212.

@bvalosek

> can you elaborate on how you see type inference playing a part in babel?

No.

**Comment by chocolateboy** [comment]
Re: "Expressive node manipulation": I was investigating this a while back and spotted these:

* [AST Query](https://github.com/SBoudrias/AST-query)
* [ESQuery](https://github.com/estools/esquery)
* [jsstana](https://github.com/phadej/jsstana)

**Comment by chocolateboy** [comment]
Re: "Pluggable [ AKA [adaptive](https://en.wikipedia.org/wiki/Adaptive_grammar) ] parser"

Probably not going to be integrated into Acorn any time soon, but the best approach I've seen to this is [Katahdin](http://www.chrisseaton.com/katahdin/).

**Comment by sebmck** [comment]
@chocolateboy 

> Re: "Expressive node manipulation": I was investigating this a while back and spotted these:

Yeah, I've already looked into them and I don't think they're an appropriate API by any means, probably something more akin to `ast-types.

> Probably not going to be integrated into Acorn any time soon, but the best approach I've seen to this is Katahdin.

What are you basing this on?

**Comment by chocolateboy** [comment]
> What are you basing this on?

Which part? :-)

The "not going to be integrated into Acorn" is just a hunch since, IMO, making a parser extensible needs to be taken into consideration from the start rather than added as an afterthought. Obviously, I'd love to be mistaken about this :-)

The "best approach" bit is based on (what I consider to be) the ease of use (for developers). IMO, a high-level declarative approach is much easier to work with than low-level "hooks". Support for [adaptive grammars](http://web.cs.wpi.edu/~jshutt/adapt/top.html) is a bit of a holy grail, and the [last](http://journal.stuffwithstuff.com/2011/02/13/extending-syntax-from-within-a-language) [promising](http://journal.stuffwithstuff.com/2011/03/19/pratt-parsers-expression-parsing-made-easy/) thing I read along these lines seems to have been [abandoned](https://github.com/munificent/magpie).

Also this:

> technically there is research on adaptive/extensible grammars but that way leads to madness! -- [tim disney](http://disnetdev.com/blog/2012/12/20/how-to-read-macros/) 

:-)

**Comment by Naddiseo** [comment]
@sebmck is there a design document/whiteboard/wiki I can share ideas on? I want some help breaking the problem down into smaller parts. The acorn PR seems a little restrictive, and I was going for a more general approach.

@chocolateboy, this isn't exactly "adaptive grammars" since we know ahead of source compilation time what the grammar will be, but it is definitely related. Not saying it's an easy problem, but likely easier than a grammar which can change itself at runtime (à la Perl).

**Comment by chocolateboy** [comment]
@Naddiseo: I think it depends on the [scope](https://github.com/babel/babel/issues/568) of the "pluggable parser" proposal.

If the plan is to allow something like the [mallet operator](https://github.com/babel/babel/pull/516) to be implemented as a third-party plugin (i.e. a self-contained syntax extension which doesn't interact adversely with other productions) without seeking approval from the Babel team, then I can see how that might be doable by adding hooks to Acorn.

If the plan is for everyone to [stop](http://jlongster.com/Stop-Writing-JavaScript-Compilers--Make-Macros-Instead) [reinventing](http://babeljs.io/blog/2015/02/15/not-born-to-die/) the lexer/parser/transformer/emitter wheel and for people to be able to implement languages [like CoffeeScript](https://github.com/chrisseaton/katahdin/blob/master/library/indentation.kat) (rather than ES5+ extensions) on top of Babel, then I don't think that's a good fit for Acorn, or for anything else that's out there at the moment.

@sebmck is nothing if not pragmatic, so I expect the goal is the former, but I'd love to see Babel gravitate towards the latter.

Either way, I recommend taking a look at the Katahdin papers/language. There are a lot of good ideas there :-)

**Comment by sebmck** [comment]
@Naddiseo 

> is there a design document/whiteboard/wiki I can share ideas on? I want some help breaking the problem down into smaller parts. The acorn PR seems a little restrictive, and I was going for a more general approach.

Not really. If you feel as if it's restrictive though I'd recommend raising suggestions in marijnh/acorn#212 before it's too late as once it's merged, `acorn-babel` is going to use it and most likely all the parser modifications will be separated.

@chocolateboy 

> If the plan is to allow something like the mallet operator to be implemented as a third-party plugin (i.e. a self-contained syntax extension which doesn't interact adversely with other productions) without seeking approval from the Babel team, then I can see how that might be doable by adding hooks to Acorn.

Yep, this is the direction that I want.

> If the plan is for everyone to stop reinventing the lexer/parser/transformer/emitter wheel and for people to be able to implement languages like CoffeeScript (rather than ES5+ extensions) on top of Babel, then I don't think that's a good fit for Acorn, or for anything else that's out there at the moment.

That's **definently** not what I'm proposing. I don't even know how this would work because supporting something like CoffeeScript would be such a shitfight that nothing would work together because the grammar would be so different.

**Comment by chocolateboy** [comment]
> I don't even know how this would work 

Katahdin

**Comment by sebmck** [comment]
@chocolateboy I only see additive syntax being practical.

**Comment by chocolateboy** [comment]
Fair enough, and I totally don't know C#, but what I got from spelunking the code/papers is:

* a way to define rules/productions whose precedence is relative to (lower than/higher than) other rules
* a way to swap in a new (scoped) lexer (e.g. for offside rule/Python/CoffeeScript &c. support)
* a way for multiple syntaxes to interoperate
* (often overlooked/wrong) support left recursion
* declarative (rather than imperative)

**Comment by yuchi** [comment]
A new opponent has arrived! Did you have a look at [sweetjs](http://sweetjs.org/)?

**Comment by sebmck** [comment]
@yuchi Yep, there was discussion about potential integration in #568.

**Comment by Naddiseo** [comment]
@sebmck 
Regards marijnh/acorn#212, after reading through the PR again it does look like it's probably flexible enough, but it only generates an AST, no CST

>> is there a design document/whiteboard/wiki I can share ideas on? I want some help breaking the problem down into smaller parts.

> Nope, only thing is this issue :stuck_out_tongue_winking_eye:

Okay, I'll start a [repo/wiki](https://github.com/Naddiseo/plugger/wiki) with my ideas so that this issue doesn't get polluted.

@chocolateboy 
> If the plan is for everyone to stop reinventing the lexer/parser/transformer/emitter wheel and for people to be able to implement languages like CoffeeScript (rather than ES5+ extensions) on top of Babel, then I don't think that's a good fit for Acorn, or for anything else that's out there at the moment.

Aren't they the same problem? If you solve the latter, then you've solved the former.

**Comment by chocolateboy** [comment]
@Naddiseo

> Aren't they the same problem? If you solve the latter, then you've solved the former.

Implementation/effort-wise, I don't think providing a framework on top of which every AltJS language can be built is remotely the same as providing parser hooks so that something like the mallet operator can be implemented as a plugin, but -- like I say -- I'm eager to be proven wrong :-)

**Comment by sebmck** [comment]
Splitting this up into the follow issues:

 - Transformer API #987
 - Split up CLI #988
 - Better comment attachment #989
 - Contribution guide #992
 - Infer string quotes #991
