### ISSUE TITLE
Wrong behaviour in "for...of" statement

### ISSUE THREAD

**Issue by macabeus** [babel/babel#8839]
## Bug Report

**Current Behavior**
Throws this exception:
```
TypeError: undefined: Duplicate declaration "i"
  1 | 
  2 | for (let i of 'foo') {
> 3 |   let i = 'a';
    |       ^
  4 |   console.log(i);
  5 | }
  6 | 
```

**Input Code**
```js
for (let i of 'foo') {
  let i = 'a';
  console.log(i);
}
```

**Expected behavior/code**
Should prints `'a'` three times instead of throws this exception.
This is the behaviour in Node and Safari, for example.

**Babel Configuration (CLI command)**

```js
const output = require('@babel/core').transform(`
for (let i of 'foo') {
  let i = 'a';
  console.log(i);
}
`, {
  presets: ['@babel/preset-env']
});
```

**Environment**
- Babel version(s): lastest
- Node/npm version: Node 9
- OS: macOS High Sierra
- Monorepo: yes
- How you are using Babel: `cli`

**Comment by krovc** [comment]
This error have no connection with for...of. At least I think it's expected behaviour. So you can remove let from second line.

**Comment by nicolo-ribaudo** [comment]
It's a bug, similar to https://github.com/babel/babel/issues/8498

**Comment by macabeus** [comment]
@nicolo-ribaudo Yeah, I found this new bug when I was trying to resolve this another issue, but I could not resolve 😞

Do you have any idea how to resolve it? I'm not sure, but I think that this bug happens because [this line](https://github.com/babel/babel/blob/6b8261bbb7ebb8d2980cb30c3b3369678fd99835/packages/babel-plugin-transform-block-scoping/src/index.js#L736 ) not to extend correctly when it have two variables with the same name, or because [this function](https://github.com/babel/babel/blob/6b8261bbb7ebb8d2980cb30c3b3369678fd99835/packages/babel-plugin-transform-block-scoping/src/index.js#L691) should also to add declarations at `node.init` if the node is a `ForStatement` and make more changes at function `updateScopeInfo`.

**Comment by byronluk** [comment]
So it seems like TypeError that you're running into is coming from [this line](https://github.com/babel/babel/blob/b5246994b57f06af871be6a63dcc4c6fd41d94d6/packages/babel-traverse/src/scope/index.js#L349).
`@babel/core.transform` will call` babel-traverse` and `babel-traverse` will call `checkBlockScopedCollisions`, which is throwing that exception. Seems like it's intentional if there is a function that's explicitly throwing that error... but I'm not entirely sure.

 If you comment out [these lines](https://github.com/babel/babel/blob/b5246994b57f06af871be6a63dcc4c6fd41d94d6/packages/babel-traverse/src/scope/index.js#L348-L350) in babel-traverse, the initial transform call will run as expected and 
**output the code below** ⬇️ which gives me the expected behavior when I run it in the console.
```
"use strict";

var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;

try {
  for (var _iterator = 'foo'[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    var i = _step.value;
    var i = 'a';
    console.log(i);
  }
} catch (err) {
  _didIteratorError = true;
  _iteratorError = err;
} finally {
  try {
    if (!_iteratorNormalCompletion && _iterator.return != null) {
      _iterator.return();
    }
  } finally {
    if (_didIteratorError) {
      throw _iteratorError;
    }
  }
}
```

Hope that helps! 😬

**Comment by openorclose** [comment]
Tried the first example out and still resulted in the same error on v7.8.4

```js
for (let i of 'foo') {
  let i = 'a';
  console.log(i);
}
```

I would like to work on this if still needed!

**Comment by nicolo-ribaudo** [comment]
It's yours!

**Comment by openorclose** [comment]
Thanks!

**Comment by liuxingbaoyu** [comment]
Seems to have been fixed, feel free to open an issue if the problem persists.
