### ISSUE TITLE
[plugin-transform-typescript@7.1.0] Combination of 'this' parameter and rest parameters goes wrong

### ISSUE THREAD

**Issue by joostlubach** [babel/babel#8840]
## Bug Report

**Current Behavior**

I have a function that both has a `this` parameter, and a spread / rest parameter pattern, such as:

```
function logEmit(this: Socket, event: string, ...args: any[]) {
  console.log('given arguments:', args)
}
```

When I call this function, the value of `args` is missing the first given argument.

**Input code**

```
logEmit.call(socket, 'message', 1, 2, 3, 4, 5)
```

Yields: `given arguments: [2, 3, 4, 5]`

**Expected behavior/code**

I expect the above call to yield `given arguments: [1, 2, 3, 4, 5]`

**Babel Configuration (.babelrc, package.json, cli command)**

I use React Native's `module:metro-react-native-babel-preset`, which uses `@babel/plugin-transform-typescript@7.1.0` under the hood.

**Environment**
- Babel version(s): v6.26.3
- Node/npm version: v10.8.0
- OS: OSX 10.13.6
- How you are using Babel: not sure, through React Native's metro bundler

**Possible Solution**

Inspecting the generated code of my `logEmit` function learns why this happens: the (virtual) `this` parameter is taken into account in the argument extraction algorithm.

```
function logEmit(event) {
    for (var _len = arguments.length, args = new Array(_len > 2 ? _len - 2 : 0), _key = 2; _key < _len; _key++) {
      args[_key - 2] = arguments[_key];
    }

    //...
}
```

The solution would be to ignore the `this` parameter, so that the number 2 would become 1 instead.

**Comment by alamothe** [comment]
I'm facing the same issue... This is a huge bug with compilation.

**Comment by nicolo-ribaudo** [comment]
Does putting the typescript preset first solve your issue?

**Comment by alamothe** [comment]
I can't be sure because I'm using Create React App (for web) and Expo (for native), and they both come pre-configured.

My workaround is to use `arguments` directly instead of the rest parameter syntax. The compiler is making less fuss about `arguments` being untyped than `this` being untyped.

**Comment by Danoha** [comment]
@nicolo-ribaudo [Here](https://babeljs.io/repl#?browsers=edge%2017&build=&builtIns=false&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsI2ACmQC1RAC4YB5AIwCsBTKZAGhgDpXgAnAcxAEoYBvAFABIdjWQJ2WOBGbAADvIA2YPIRBMO3HgG5BAXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript%2Cenv&prettier=false&targets=&version=7.7.7&externalPlugins=) is a repro case in the Babel repl.

The `es2015` preset works correctly - `this` parameter is simply ignored, but the `env` preset does not.

If this was caused by incorrect order of presets, wouldn't the repl have it right?

Let me know what you think. If it's bug in Babel, I'd try to create a PR.
