### ISSUE TITLE
'jsonStrings' parser plugin does not increment line count

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#8865]
## Bug Report

I realized that https://github.com/babel/babel/pull/7985 should also have a `++this.state.curLine;` in there along with the `++this.state.pos;`, since otherwise the location information isn't quite right.

cc @jridgewell

**Comment by byronluk** [comment]
Hi @loganfsmyth , is it okay if I work on this?

**Comment by loganfsmyth** [comment]
Go for it! It should be adding that line and then deleting the tests so they regenerate when you re-run the tests.

**Comment by byronluk** [comment]
@loganfsmyth Thank you for the opportunity to contribute! I regenerated the output.js file in the tests and there were no changes. Not sure if that's the intended behavior.

**Comment by loganfsmyth** [comment]
Hmm, I'm not sure. I was expecting the test from https://github.com/babel/babel/pull/7985/files#diff-fc5abbbd6419713542e1e54abc6c31aaR55 to at least be on a new line.

**Comment by jridgewell** [comment]
😳. Thanks for fixing @byronluk

**Comment by byronluk** [comment]
Whoops, dug deeper and it seemed like an issue with my local build. After I ran "make build" and ran the tests after that, the output.js files updated. Which is weird because running "make bootstrap" also runs "make build".

Anways, np! @jridgewell looking forward to contributing more in the future!
