### ISSUE TITLE
Ruby-Bablel-Transpiler has been Abandoned

### ISSUE THREAD

**Issue by BookOfGreg** [babel/babel#8893]
Posting issue here as there is no point posting in ruby-babel-transpiler.

The gem https://github.com/babel/ruby-babel-transpiler hasn't been updated since 2016.

I'm the maintainer of react-rails, I am willing to take on small dependency updates to ruby-babel-transpiler if an org member of babel wants to add me to it.

https://github.com/reactjs/react-rails/issues/944

**Comment by xtuc** [comment]
Since Rails 5 has the support for Webpack, why do we need a custom babel integration?

**Comment by BookOfGreg** [comment]
Rails 5's default is still Sprockets. As the maintainer of React-Rails I need this gem in order to provide React to the Rails community, unfortunately I currently depend on Babel-Transpiler, and because it's my dependency I'll be happy to take it on for small patches and triageing other people's PRs onto it if this organisation is willing. Otherwise I'll probably need to fork it into the ReactJS organisation to keep it maintained.

**Comment by loganfsmyth** [comment]
If you're willing to tackle this as a project, I'm not necessarily against it, but I do think it's not obvious how easy it'll be. The main questions from me are

1. How configurable are you expecting this to be?
2. What execution environments do we aim to support?

Babel 5, the most recent version supported by the Ruby package, was the last to include the majority of plugins by default. Would this want to bundle in `preset-env` and `preset-react`? What if users want to enable other plugins? Babel's config file system assumes Node is the execution environment, so supporting config files would require Node unless you want to define your own custom config system for the gem.

Babel 7 has also dropped support for environments older than Node 6, and while we provide the `@babel/standalone` package as an easy package to drop into a browser, I'm actually not sure it's  100% safe on ES5 environments because it's always hard to tell what features our dependencies might be using. I see that the old gem used `execjs`, so if you didn't support config files and went with `@babel/standalone`, you'd still potentially have to spot-check every transform on every `execjs` platform.

If at all possible, it seems like it would be safest and most consistent with our documentation if any Ruby build logic still passed the code through Node for compilation. Do you think that would be feasible?

**Comment by BookOfGreg** [comment]
To answer 2 first:
`execjs` is a bit of a red herring, it just provides bindings to call other available JS environments. React-Rails dropped support for the JS runtime `the-ruby-racer` as it was stuck on `lib-v8` V3. I will have to go check which NodeJS runtime lib-v8 v3 maps onto but it did not support ES6. Therefore we swapped onto `miniracer` for MRI and `rubyrhino` for Jruby which both support new-enough versions of lib-v8 for ES6.

I plan on supporting everything that React-Rails supports for sprockets, which is any ES6 compatible libv8 through miniracer/rubyrhino on Rails 4+. If people need to support older syntax then the JS runtime should automatically support that anyway and the babel-transpiler should effectively be a no-op.

About 1:
I apologise but I'm not sure what you're asking for. I haven't spent enough time investigating babel-transpiler at this time to know what is and isn't sensible to configure. Primarily I'm a ruby developer rather than a JS developer. My skill is mostly around pluming together code, such as in react-rails you can use every feature of Webpack/Webpacker as it's directly exposed with the gem only acting as a thin layer. My intentions would be to allow anything configurable in babel to remain configurable in react-rails by not attempting to modify config at all and allowing complete pass-through of all existing options.

**Comment by loganfsmyth** [comment]
> Therefore we swapped onto miniracer for MRI and rubyrhino for Jruby which both support new-enough versions of lib-v8 for ES6.

Alright, it would be good to verify if that maps to roughly Node 6 compatibility. That would at least allow you to use `@babel/standalone` without too much trouble.

> If people need to support older syntax then the JS runtime should automatically support that anyway and the babel-transpiler should effectively be a no-op.

I'm not sure I 100% follow this statement.

> My intentions would be to allow anything configurable in babel to remain configurable in react-rails by not attempting to modify config at all and allowing complete pass-through of all existing options.

At it's core, Babel is a framework for performing transformations, so the question essentially comes down to what transformations are available. Babel users on Node can for instance write their own custom transforms, or install any plugins that are available from npm. Since those will rely on Node's module system, I would not expect that installation mechanism to be available if you're executing Babel in a non-Node V8 environment. When Babel 5 existed, the community of third-party plugins was nearly non-existant, so it wasn't an issue at the time.

For non-Node environments, I'd expect you to be limited to only the plugins that are pre-bundled into `@babel/standalone`, which cover all of Babel's first-party code transformations for ES20XX. I think for your usecase that may well be totally fine, but wanted to mention it.

**Comment by BookOfGreg** [comment]
@loganfsmyth Thanks for your thoughtful comment. In all honesty I'm not totally up to speed in all that will be involved in getting the ruby babel-transpiler up to scratch so your knowledge of the functioning and potential limits is really handy.

If you're willing to engage with me on it, would you be happy for me to file PRs onto it, and for you merge and release the gem? That way I would not need any new privilege or membership to babel if that was any barrier to getting the gem from being abandoned.

To reply:

> Alright, it would be good to verify if that maps to roughly Node 6 compatibility.

I actually have a task independently on react-rails [here](https://github.com/reactjs/react-rails/issues/948) to document which runtimes are supported there which could conveniently port back onto ~node compatibility so I can await the outcome of that.

> I'm not sure I 100% follow this statement.

I was meaning if you have babel transpile normal JS, I believe the output is no different.  This was in reply to this previous comment:
> I'm actually not sure it's 100% safe on ES5 environments because it's always hard to tell what features our dependencies might be using. I see that the old gem used execjs, so if you didn't support config files and went with @babel/standalone, you'd still potentially have to spot-check every transform on every execjs platform.

Though it's entirely possible I got the wrong end of the stick :)

**Comment by BookOfGreg** [comment]
Github is being rather annoying at the moment. This is my 3rd attempt at replying to you so I'll keep it short this time.

If you're willing to approve PRs and deploy the gem then I can get working on it.
Very good point about supporting community extensions, it will be a priority of mine to try not interfere with the underlying deps such as babel/standalone so anything that it supports will be supported in the gem if possible.

There is an open issue claimed by someone on React-Rails to document non-supported JS runtimes which will help us see which ones the babel-transpiler gem will support.

**Comment by mashedkeyboard** [comment]
Sorry for bumping a relatively old topic - did this come to anything in the end?

I strongly prefer Sprockets to Webpack because JS doesn't form the main part of my app, and I don't want to have to rewrite the way the JS is written in order to change it into packs to switch over. Whilst babel-transpiler works, it concerns me that it seems to be abandoned still. Are any updates planned at all?

**Comment by BookOfGreg** [comment]
I'd class this repo as dead.
Honestly changing from Sprockets to Webpacker 3.x is pretty trivial as long as you don't use too much custom JS-gems.
It should be as easy as add Webpacker gem, generate the webpacker files, mv app/assets to app/javascripts/src and adding a app/javascripts/packs that references it, then swap to javascript_pack_tag.
At a high level that should do 95% of all the coversion you need.

Webpacker becomes the default in Rails 6 so I think it's safe to reckon Sprockets and it's Gem ecosystem is likely to see severe abandonment and rot in the next 5 years.

**Comment by liuxingbaoyu** [comment]
Because this issue is out of date, I will close it.
