### ISSUE TITLE
@babel/polyfill eventLoop not current on IE10

### ISSUE THREAD

**Issue by ihet** [babel/babel#8975]
My code：

```
console.dir("start");
setTimeout(()=>{
    console.dir("setTimeOut1");
},0);

Promise.resolve(true).then( ()=>{
    console.dir("Promise1");
});

console.dir('end');
```

the current result is:

```
"start"
"end"
"Promise1"
"setTimeOut1"
```

but only  use @babel/polyfill on IE10 the result is:

```
"start"
"end"
"setTimeOut1"
"Promise1"

```

I think something wrong with microtask & macrotask on IE10

##### Environment

- Babel version(s): [v7.1.2]
- Babel Polyfill version(s): [v7.0.0]
- Node/npm version: [Node 8.9.0/npm 5.51]
- OS: [windows 10]
- Browser: [Internet Explorer 10]
- How you are using Babel: [ loader]

**Comment by zloirock** [comment]
`babel` uses for polyfilling `core-js`, so, please, create issues about polyfilling in the [`core-js` repo](https://github.com/zloirock/core-js)!

`setTimeout` should use task queue, `Promise` - microtask queue, because of this by the spec promise tasks should be called before `setTimeout`. Microtasks can be implemented by [usage of `MutationObserver` and some other ways](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/microtask.js), but no one of them available in IE10. So in IE10- `Promise` uses tasks instead of microtasks and you have this output.
