### ISSUE TITLE
ERROR in Cannot find module 'babel-runtime/helpers/interop-require'  @ multi main webpack: Failed to compile.

### ISSUE THREAD

**Issue by abdullah0ahmed** [babel/babel#8977]
I just started using react, I kept following a course from lynda.com. I did try to setup sass and css loaders. however, when I tried to compile using: npm start 
I faced this issue that I couldn't solve even after searching and following different solutions:

```
ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ multi main
webpack: Failed to compile.
```

**Comment by abdullah0ahmed** [comment]
Still waiting for a solution..

**Comment by nicolo-ribaudo** [comment]
@abdullah0ahmed Having a response in 2 hour is rare for paid software developer by big companies. We are a bunch of volunteers working in our free time, so please be patient.

**Comment by nicolo-ribaudo** [comment]
What are your package.json, webpack configuration and Babel configuration?

**Comment by joseds** [comment]
Hi, I just registered at CodeTriage and this is my first assigned issue to help with. I hope my contributions will be useful, please tell me if I can improve anything.

I suspect some version conflict to be the source for the current problem, but without at least a package.json, I don't think the problem can be reproduced to decide if it's just a bad combination of package versions or really a problem with the library.

Since 3 months have passed, I recommend closing this issue for now.
