### ISSUE TITLE
Object.assign should be transpiled when browserslist includes IE11

### ISSUE THREAD

**Issue by macgyver** [babel/babel#8998]
## Bug Report

**Current Behavior**
Maybe i'm just using these web tools wrong but it seems like `Object.assign` is not polyfilled for IE11

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/repl/#?babili=false&browsers=%3E%202%25%2C%20ie%2011&build=&builtIns=usage&spec=true&loose=true&code_lz=MYewdgzgLgBAHjAvDA3gXwFCkrAnk1TAeQCMArAU2CgDoBDCCASwHMwAKOAGhlwEoA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

**Expected behavior/code**
According to [kangax](http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;) `Object.assign` is not supported by IE11 and it should be transpiled in the REPL when IE11 is included in the browsers list.

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/1163/48211612-dc1ef680-e347-11e8-9a84-9b2618d7a22d.png)

**Comment by existentialism** [comment]
@macgyver 

> Maybe i'm just using these web tools wrong but it seems like Object.assign is not polyfilled for IE11

preset-env@1.6.2 will _replace_ `import "babel-polyfill"' with the necessary _polyfills_ for your targets.

For example:

https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=usage&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAIgEYEMkFMA2BaSmCeAZsJpggFDkDGEAdgM7wAecAvHAN4C-1djc-Npx4B5JACt0VGADoU9esADmtABRMANPgCUQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

> According to kangax Object.assign is not supported by IE11 and it should be transpiled in the REPL 

It won't actually _transpile_ it, since it's including a polyfill for it.

**Comment by macgyver** [comment]
Ah... that makes sense. I guess I would have expected to see the polyfill code inserted in the REPL?

**Comment by existentialism** [comment]
@macgyver 

It's imported as:

```
require("core-js/modules/es6.object.assign");
```

**Comment by macgyver** [comment]
Right on - I was hoping to get a sense of the cost of transpiling new syntax, but the REPL is not the right tool to answer this question, thanks for your help!
