### ISSUE TITLE
Why is @babel/preset-env named with "env"?

### ISSUE THREAD

**Issue by harrysolovay** [babel/babel#9036]
This isn't an issue, I'm just curious about something / need advice. I'm currently working on a dev tool that can accept presets (similarly to babel), and I'm trying to name the main/recommended preset. I see the vast majority of babel projects using the env preset. I'm wondering why the team decided to name it "env"? Any considerations (or alternative names debated) would be greatly appreciated!!!

Thanks :)

Kind regards,

Harry

**Comment by hzoo** [comment]
It's a great question! Real quick but I created the initial PR here: https://github.com/babel/babel/pull/3476. `env` was supposed to stand for environment since we wanted to turn on/off plugins based on the environment. There's a lot more context and other issues linked there but I just decided to go with that although it could of been called targets or something else (I was thinking target env).
