### ISSUE TITLE
Whitespace issue with exports when not using es6.modules.

### ISSUE THREAD

**Issue by rwjblue** [babel/babel#906]
Using the following script:

```javascript
var babel = require('babel-core');

var input = 'export function foo() {\n\n}\n\n' +
            'export function bar() {\n\n}\n';

var output = babel.transform(input, {
  whitelist: ['es6.templateLiterals', 'es6.parameters.rest', 'es6.arrowFunctions']
}).code;

console.log(output);
```

Results in the following output:

```javascript
export { foo as foo };

export { bar as bar };
function foo() {}function bar() {}
```
---

* Why are the exports changed from their original format when `es6.modules` transformer is not enabled?
* The lack of semi-colons or newlines causes uglifier to throw parse errors in some scenarios (specifically  [this file](https://github.com/emberjs/ember.js/blob/3aea9e01ec07eb58a82d84daa95ec8fb1bd4a942/packages/ember-metal/lib/watch_key.js) in Ember).

**Comment by sebmck** [comment]
> Why are the exports changed from their original format when es6.modules transformer is not enabled?

It'd be because of [this](https://github.com/babel/babel/blob/master/src/babel/transformation/transformers/internal/modules.js) transformer that splits up exports. See the comment at the top for information on why this happens. It should only be ran when `modules` is enabled so that's a bug.

> The lack of semi-colons or newlines causes uglifier to throw parse errors in some scenarios (specifically this file in Ember).

Sounds like a bad parser. Should be able to fix this by forcing there to be at least one newline in statement lists. Right now newlines are retained by comparing the starting token of the current node to the previous token, once each line is printed it then registers that newline as "consumed" and no other node can consume it. It's probably the case where `export` is "consuming" that newline.

**Comment by rwjblue** [comment]
> It'd be because of this transformer that splits up exports.

That is an awesome explaination, thank you.

> Sounds like a bad parser.

Yes, agreed completely. Once I tracked down the issue, the "fix" was to add a `;` between the two exports (which is obviously annoying).

Thank you for the quick response!

**Comment by sebmck** [comment]
Actually, if I disable the internal modules split transformer then exporting generator functions will break. Would just fixing the whitespace issue be acceptable? esperanto should handle it just fine.

**Comment by rwjblue** [comment]
Yes, the only actual thing to "fix" (even though it is a bug in uglifier's parser most likely) is the missing whitespace, I think I was mostly curious about why modules would be changed when modules were not enabled (and was not sure if that was a factor in the whitespace issue).

**Comment by rwjblue** [comment]
:heart: - Thanks @sebmck!

**Comment by sebmck** [comment]
@rwjblue No problem! I'm planning on rewriting the current code generator (#883) since there's some quirky behaviour associated with the retention of newlines (such as the one that caused this issue). Thanks!
