### ISSUE TITLE
Using ES6 module in `src/babel/api/node.js` makes `isparta` broken

### ISSUE THREAD

**Issue by meoguru** [babel/babel#908]
Since `isparta` uses `babel` to transpile its source code also, this line:

```js
import babel from 'babel-core';
```

will be transformed to:

```js
var _interopRequire = function (obj) { return obj && obj.__esModule ? obj["default"] : obj; };
var babel = _interopRequire(require("babel-core"));
```

Because we already had ES6 module used in `src/babel/api/node.js` file, `babel` will be exported with property `__esModule` set to `true`.

But `exportedValueOrBabel["default"]` is `undefined`, so `isparta` will see `babel` as `undefined` value and will be broken.

I believe this is a critical issue and should be fixed very soon. Thank you.

**Comment by neVERberleRfellerER** [comment]
`src/babel/api/node.js` does not have default export. Use

    import * as babel from 'babel-core';

**Comment by meoguru** [comment]
In the past,

```js
import babel from 'babel-core';
```

worked.

Of course I know it is not mentioned anywhere in official API (the case when requiring an ES6 module from another ES6 module like `isparta` to `babel` is rare) but it is natural for people to import `babel` like that.

If thinking that way, this issue should be consider as a non-backward compatible change.

**Comment by neVERberleRfellerER** [comment]
Disclaimer: following text expresses my personal believs and the part with interops might not be even correct.

This is semantical problem. Official API docs use require.

    var babel = require('babel-core');

which is now, after transition to ES6 modules, equivalent to this

    import * as babel from 'babel-core';

In both cases you really want all exported values and not some magical default object.

This

    import babel from 'babel-core';

was not semantically correct usage. You were never referencing some default object but only separately exported values -- the task for which

    import * as babel from 'babel-core';

exists.

The reason it worked in the past is, that require interops were introduced to handle default object assinged to `module.exports`, so this did the right thing:

    import SuperClass from 'super-class';

Also, since you are using only one property - the transform, another semantically correct import is

    import {transform} from 'babel-core'; // with this, nothing would break

So, the problem you are reporting may not be neccessarily caused by babel. Just something to think about.

**Comment by meoguru** [comment]
I think you are right.

**Comment by developit** [comment]
When I ran into this problem in a slightly different case, I wondered why Babel's `interopRequire` didn't try falling back from `exports.default` to `exports` when `.default` is not defined.  My guess was that it was intentionally avoiding a behaviour that the spec will never support, which is understandable.

**Comment by sebmck** [comment]
Yes @neVERberleRfellerER is correct. Use:

```javascript
import * as babel from 'babel-core';
```

instead.
