### ISSUE TITLE
Flow type parameters are not stripped out

### ISSUE THREAD

**Issue by FezVrasta** [babel/babel#9100]
## Bug Report

**Current Behavior**
Babel + babel-plugin-flow-strip-types doesn't strip Flow type parameters.

It used to work fine before.

**Input Code**
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=C4TwDgpgBAwg9gO2BAHsAysAhsqBeKAbwCgooAzOOAfgC4oBnYAJwEsEBzfAPigDc4rACYAaYgF8A3MVRg4zYFADGiJrETI0-Zcwg4I8JKmAAeQ5ozZk3ABQkylOPQCuCIRHLsIoiQEpJQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=react&prettier=false&targets=&version=6.26.0&envVersion=

```js
type ContextState = {
  foo?: string => void,
};
export const Context = createContext<ContextState>({
  foo: undefined,
});

```

**Expected behavior/code**
The type parameter should be stripped out.

**Babel Configuration (.babelrc, package.json, cli command)**

See REPL

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: 11.1.0
- OS: macOS High Sierra
- Monorepo: no
- How you are using Babel: webpack & REPL

**Comment by danez** [comment]
That is a tough one as it is ambiguous. Right now it is not parsed as flow as the code snippet can either be interpreted as flow or as binary expressions. As it is not parsed as flow it is also not removed by the transform:

```js
(createContext) < (ContextState) > ({});
```

@samwgoldman @mroch How are you making sure in flow you are not interpreting binary expressions as type parameters? Would it work if we just try to parse as type param and if it works we go for it otherwise we roll back and parse as binary expression? Is this what the flow parser does?

**Comment by mroch** [comment]
iirc, we parse it as an annotation if the file has @flow, and as binary if not. on my phone right now so I can’t double check, sorry!

**Comment by FezVrasta** [comment]
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEAEDMBsHsHcBQAXAngBwKagMKwHbKYAeyAysgIZGgC8oA3oqKJLLAPwBcoAzsgCcAlvgDmdAHygAbrCEATADSIAvgG5EJdLAHJQAYwL9cBIqToGBmapjyESyADx2z5KkQkAKJizaweAK748piQIphKqgCUakA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=react&prettier=false&targets=&version=6.26.0&envVersion=

it doesn't change anything if I add `// @flow` (which I have in my project and I did forgot to add in the REPL)

**Comment by nicolo-ribaudo** [comment]
I has been fixed in Babel 7. (the repl still uses Babel 6). I suggest you to [upgrade to Babel 7](https://babeljs.io/docs/en/next/v7-migration)

https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEAEDMBsHsHcBQAXAngBwKagMKwHbKYAeyAysgIZGgC8oA3oqKJLLAPwBcoAzsgCcAlvgDmdAHygAbrCEATADSIAvgG5EJdLAHJQAYwL9cBIqToGBmapjyESyADx2z5KkQkAKJizaweAK748piQIphKqgCUakA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=flow&prettier=false&targets=&version=7.1.6&envVersion=

**Comment by existentialism** [comment]
For reference: https://github.com/babel/babel/pull/7934

**Comment by FezVrasta** [comment]
Anyway as a workaround, for now, I'm using the Flow comment syntax in this place.

```js
/*::
type ContextState = {
  foo?: string => void,
};
*/
export const Context = createContext/*:: <ContextState> */({
  foo: undefined,
});
```

this way Flow still type checks and the code is still valid JS

**Comment by nicolo-ribaudo** [comment]
Since Babel 7 has been released three months ago, I don't think that we will ever release a new Babel 6 version, unless there is a critical security problem.
