### ISSUE TITLE
looks like leading comments wrong when var decls not ends with semi

### ISSUE THREAD

**Issue by HairyRabbit** [babel/babel#9102]
## Bug Report

Bugs maybe

**Current Behavior**
See the below astexplorer.net screenshots, the second var decl haven't leading comments:

![image](https://user-images.githubusercontent.com/5752902/49273519-29f2ce80-f4b0-11e8-9435-f1c9eec5c6a3.png)
![image](https://user-images.githubusercontent.com/5752902/49273593-7807d200-f4b0-11e8-8065-84d1a4ce764e.png)

If the first decl ends by semi, it works fine

**Input Code**
- REPL or Repo link if applicable:

I write a plugin to transform my code, it works with the leading comments

```js
var s = `
/**
 * @test
 */
const a = {
  b: 42
}

/**
 * @test
 */
const c = 42
`
require('@babel/core').transform(s, { plugins: [
  function plugin(path) {
    return {
      visitor: {
        VariableDeclaration(path) { console.log(path.node.leadingComments, path.toString()) }
      }
    }
  }
]})
```

output:

![image](https://user-images.githubusercontent.com/5752902/49273900-7d195100-f4b1-11e8-9eac-51ad371fbac4.png)

**Environment**

![image](https://user-images.githubusercontent.com/5752902/49273955-9fab6a00-f4b1-11e8-91b5-3bb349df03bd.png)

**Comment by coreyfarrell** [comment]
I've encountered this as well as it effects nyc ignore hints.  From what I can tell the issue occurs to any comment following an object-literal assignment with no trailing semi-colon.  I can only reproduce the error if the object-literal has at least one key.
```js
obj = {a: 1}
/* istanbul ignore else */
if (true) {}
```
Using `const`, `var` or `let` to declare instead of assign `obj` makes no difference.  The comment is recorded under `tailingComments` for the `ObjectProperty` representing the `a` property as well as the `ExpressionStatement` or `VariableDeclaration`, it is not recorded under `leadingComments` for the `IfStatement`.

Adding the semi-colon after `{a: 1}` fixes this.  The comment is no longer recorded under `tailingComments` for the `ObjectProperty`, it is still recorded for the `ExpressionStatement` or `VariableDeclaration` and it is recorded under `leadingComments` of the `IfStatement`.

**Comment by nicolo-ribaudo** [comment]
Might be fixed by https://github.com/babel/babel/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by coreyfarrell** [comment]
@nicolo-ribaudo I can confirm this fixes the issue both for my example code and for the code posted by @HairyRabbit.
