### ISSUE TITLE
[TypeScript] Typescript plugin overwrites parent class properties when the child narrows that property's type

### ISSUE THREAD

**Issue by arilotter** [babel/babel#9105]
## Bug Report

**Current Behavior**
When a class (B) extends another class (A) and includes a type definition to narrow the type of something specified in class A, it will set the narrowed property's value to undefined. This diverges from the TSC behavior.
The output from the below code under babel is `a, undefined`.
**Input Code**
```typescript
  class A {
    value: any
    constructor(value: any) {
      this.value = value
    }
  }

  class B extends A {
    value: string
  }

document.write(`${new A('a').value}, ${new B('b').value}`)
```

**Expected behavior/code**
The output from the code should be `a, b`.

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc: 
```js
{
  "presets": [
    "@babel/env",
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
```

**Environment**
- Babel version(s): 7.1.6
- Node/npm version: Node 10 / NPM 6
- OS: Any OS
- Monorepo: doesn't matter
- How you are using Babel: loader

**Possible Solution**
It seems like babel is setting `value = undefined` in the class property - it needs to check if that value is defined in the parent before overwriting it.

**Comment by ryami333** [comment]
This issue seems to be blocking a `tsc`->`@babel/preset-typescript` migration we're trying to perform. In our case, we're extending Immutable's `Record` like this:
```
import { Record } from 'immutable';

const defaults = { foo: 'foo' };
class Thing extends Record(defaults) {
   foo: string;
}

**Comment by loganfsmyth** [comment]
This is expected behavior with Babel, because Typescript does not conform to the class field proposal's behavior and Babel does. If a parent class is responsible for defining a type, you should not be re-declaring it on the child class, because that means you are explicitly taking responsibility for making sure the value is correct.

You'd either need to do `legCount: number = this.legCount;` to explicitly reuse the value defined by the parent class, or leave it out entirely because it can already infer the type of `legCount` from the argument to `Record`.

**Comment by buschtoens** [comment]
I've opened https://github.com/Microsoft/TypeScript/issues/28823 to raise awareness about this issue.

While I really appreciate that Babel is pretty much 100 % spec compliant, I also would like it to be able to process TypeScript files correctly. I don't have high hopes for TS fixing the issue upstream, so I think a solution in Babel-land would be in order.

If the [`@babel/plugin-transform-typescript`](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-typescript) is run _before_ [`@babel/plugin-proposal-class-properties`](https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-class-properties), it works, because the empty declarations are just stripped. However, this then breaks this subtle behavior:

```ts
class TestClass {
  // we shouldn't encourage folks to write code like this, but tsc ensures
  // that constructor param fields are set before field initializers run
  field = this.constructorParam;
  constructor(private constructorParam: string) {}
}

let instance = new TestClass('hello');
assert.equal(instance.field, 'hello');
```

From [`ember-cli-typescript`](
https://github.com/typed-ember/ember-cli-typescript/blob/v2.0.0-beta.3/tests/unit/build-test.ts#L31-L41).

So not matter how you order the two plugins, one or the other thing breaks.

Ideas for possible solutions:

- Optional third transform to be run before `@babel/plugin-proposal-class-properties` that strips `ClassProperty` without a `value`.
- Make `@babel/plugin-proposal-class-properties` configurable to strip `ClassProperty` without a `value`.
- Inline `@babel/plugin-proposal-class-properties` into `@babel/plugin-transform-typescript` and ensure correct behavior through some clever changes.

**Comment by nicolo-ribaudo** [comment]
Thank you! Lets see what the TS team says.

**Comment by galdebert** [comment]
One solution worth noting that I used to migrate from tsc to babel is declaration merging:

```ts
  interface A {}
  interface B {}

  class Base {
    prop: A | B | null = null;
  }

  class Sub1 extends Base {
    prop!: A | null; // type narrowed
  }

  // using declaration merging
  interface Sub2 {
    prop: A | null; // type narrowed
  }
  class Sub2 extends Base {
  }

  console.log("without declaration merging");
  console.log(`${new Sub1().prop}`); // tsc: null, babel: undefined
  console.log("with declaration merging");
  console.log(`${new Sub2().prop}`); // tsc: null, babel: null
```

**Comment by imhangoo** [comment]
Thanks for @galdebert 's idea, I have done the same thing using Declaration Merging:
```
class Base {
   constructor(value: string) {
       this._value = value;
   }
    _value: string;
}

class A extends Base {
    constructor(value: string) {
        super(value;)
    }

    _value: string;
    public get value() {
        return this._value;
    }
}
const a = new A("abc");
console.log(a.value); // undefined
```
But if we use the declaration merging like this:
```
class Base {
   constructor(value: string) {
       this._value = value;
   }
    _value: string;
}

interface A {
    _value: string;
}

class A extends Base {
    constructor(value: string) {
        super(value;)
    }

    public get value() {
        return this._value;
    }

}
const a = new A("abc");
console.log(a.value); // "abc"
```

**Comment by nicolo-ribaudo** [comment]
You can now use `declare` with class fields (TS 3.7, Babel 7.7)
