### ISSUE TITLE
Support @babel/template Placeholders at the Syntax Level in @babel/parser

### ISSUE THREAD

**Issue by tolmasky** [babel/babel#9112]
## Feature Request

**Problem**

Currently `@babel/template` allows you to supply a `placeholderPattern` that is applied *after* the successful parse of the template string. What this means is that it is impossible to create a pattern to unambiguously separate placeholders from common identifiers and string literals. This is fine if you are creating a template literal yourself, but makes things difficult if the templating is happening on user input where you have to communicate these restrictions. If you try a pattern like `/^@[a-z]+@$/` the parse will simply fail before it even gets to the replacement phase since `@x@` is not valid JavaScript syntax.

To concisely state the problem and its implications:

1. It is not currently possible to construct placeholder patterns that unambiguously separate placeholders from normal JavaScript identifiers.
2. The default pattern is too loose and too often catches cases not intended to be Placeholders.
3. The current state leads to a "forever maintenance" burden for either maintainers or users as new valid global identifiers are introduced to JavaScript runtimes that can be inadvertently caught by the matcher. The new `URL` constructor is a perfect example of this. While one could safely assume `URL` is a replacement in the past, it is now built-in on the web and on node. This means that something like `const NAME = new URL()` would surprisingly throw an error. The API then becomes immediately harder to use as you have to look through documentation to fix this. You have no option but to employ a very verbose solution for this very simple snippet because you *need* to use the full capital constructor. The options are: 1) provide a whitelist containing URL, 2) come up with a new pattern, or 3) pass in URL for URL. All three significantly increase the noise of the operation for a built-in type.
4. Strings are particularly confusing to deal with in this implementation [as seen here](https://github.com/babel/babel/issues/8067).
5. This often leads to fracturing of templating patterns in the community as people try to solve the above problems by coming up with their own more restrictive `placeholderPattern`s.
6. **It makes it hard (impossible?) to use babel templates for arbitrary user input as opposed to a developer's static templates.**

**Placeholder AST Nodes Solution**

It would be nice to add a new node type,`Placeholder`, to `@babel/parser` with the following shape:

```javascript
interface Placeholder {
    type: "Placeholder";
    name: string;
}
```

This node can appear anywhere an `Expression`, `Statement` (and possibly `Pattern`?) can. A more rigorous version would have a specific `Placeholder${Type}` analog for each specific subtype of `Expression` and `Statement` (for example, `PlaceholderBlockStatement` to represent placeholders where `BlockStatement`s are expected, etc.). However, this is largely an (IMO) unnecessary implementation detail as the given replacement can be validated against the parent's `NODE_FIELDS`. So for example:

```javascript
function replace(nodePath, field, node)
{
    if (NODE_FIELDS[nodePath.node.type][field].validate(node)) {
        nodePath.node[field] = node;
    }
}
```
I imagine this is probably how the current templating system handles this anyways.

Similarly, we would extend the Statement and Expression, etc. parse rules to support a new, currently invalid, JavaScript syntax. For example:

```
Placeholder ::
    @ IdentifierName @

Expression ::
    ...
    Placeholder
```

We then would create an additional option in `@babel/parse` called `allowsPlaceholders` which would turn on support for Placeholder parsing. Placeholders would then of course be parsed into `Placeholder` AST Nodes, which can then be easily identified in the AST and replaced. I am not tied to the @@ syntax, just throwing it out as a quick example.

**With a system like this, you get the following benefits**

1. A templating system that is not dependent on the input template like the current one. Instead the entire community can standardize against one placeholder pattern since it works with any JavaScript source.
2. As in my case, it allows to safely rely on `@babel/template` as my templating system without worrying about user input or having to specify rules to the user.
3. There is no longer any need to handle string contents, which currently surprises people, like in [this bug](https://github.com/babel/babel/issues/8067). This should also simplify the implementation because strings don't need to be special cased. The reason for this is that `Placeholders` can naturally be used with template literals to achieve the same effect syntactically:

   ```javascript
   const message = `Hi ${@name@}!`;
   ```

   As you can see, the feature naturally supports the string case, and is much clearer to boot.
4. We can support more expressive templating. For example, the string `class A DEFINITION` with the expectation of a block would work fine, which currently does not. We *may* decide we don't want to support this of course, but that decision would be based entirely on our specific desires and not merely a side-effect of the fact that the string `class A DEFINITION` doesn't pass initial parse.

**Teachability, Documentation, Adoption, Migration Strategy**

I think the documentation would be greatly simplified with this solution. A lot of the documentation currently revolves around options like `placeholderWhitelist` and `placeholderPattern` that have little use outside of accounting for the short comings of the valid identifier-name string matching strategy currently employed.

**Comment by loganfsmyth** [comment]
I'd definitely be in favor of supporting an official placeholder syntax as a plugin for the parser and having `@babel/template` use it. I don't personally prioritize user-provided template code via `@babel/template` so I'd be curious to hear more about your exact usecase, but it does seem like something that could be addressed as a side effect of this effort, if you wanted to set `placeholderPattern: false` yourself and rely on these new placeholder nodes instead.

> This node can appear anywhere an Expression, Statement (and possibly Pattern?) can.

If we're going through the effort of supporting this, I'd probably want to make this as broad as possible. One case that motivated the addition of string patterns is `import foo from 'FOO';` so I'd probably want to support `import foo from @FOO@;` for instance.

> A more rigorous version would have a specific Placeholder${Type} analog for each specific subtype of Expression and Statement (for example, PlaceholderBlockStatement to represent placeholders where BlockStatements are expected, etc.).

It seems like as long as you have the context of parent nodes, you'd be able to know what type it should be. On the other hand, it could be nice to have these specific types so that tooling could have rough type information without needing intimate knowledge of ancestor structure.

> Similarly, we would extend the Statement and Expression, etc. parse rules to support a new, currently invalid, JavaScript syntax. For example:

One difficulty that we'd have to decide here is how to handle `@FOO@ ;`. Is that an placeholder statement followed by an empty statement, or an ExpressionStatement with a `.expression` placeholder node. I'm not sure if we'd want to have slightly different grammars for expression-like and statement-like patterns.

> We can support more expressive templating.

I find this example particularly compelling, especially taking into account using something like what you mentioned on Slack as pattern-matching an existing AST, e.g.

```
var { NAME: name, BODY: body } = match(ast, `class @NAME@ @BODY@;`);
```
as a way to pull the body metadata out of an AST without manually walking the AST.

**Comment by nicolo-ribaudo** [comment]
I have started studying this feature.
First of all, the `@foo@` syntax doesn't work because it is incompatible with decorators:

```js
@deco1@
deco2
class Foo {}

// Could be both
@deco1 @deco2 class Foo {}

// Or
@deco1@;
deco2;
class Foo {}
```

This are the possible alternatives I have considered:

| **Syntax** | **Description**                                                                                                                                                      | **Disadvantages**                                                                                                                                                                                                                                                          |
|------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `@@foo@@`  | This the first thing I came up with after realizing that `@foo@` doesn't work. It is as placeholder-ly as the original proposal.                                     | It is incompatible with Flow's `@@iterator`. If we use this, placeholders won't work with types.                                                                                                                                                                           |
| `{%foo%}`  | (Mentioned by @tolmasky on Slack)                                                                                                                                    | https://github.com/keithamus/proposal-object-freeze-seal-syntax is a Stage 1 proposal which introduces two new syntaxes: `{#`  `#}` and `{|` `|}`. `{%` `%}` (or any other brace-sigil syntax) would look tightly related to it but it has a completely different meaning. |
| `%%foo%%`  | Inspired by the two previous alternative. It has the advantage over `{%` that is slighlty easier to type and doesn't conflict with any existing feature or proposal. | It is really ugly, but probably it is the same for any other placeholder syntax we could think of?                                                                                                                                                                         |

---

> ```js
> interface Placeholder {
>     type: "Placeholder";
>     name: string;
> }
> ```

Probably it would be more like
> ```js
> interface Placeholder {
>     type: "Placeholder";
>     name: Identifier;
>     expectedType: "Expression" | "Statement" | "Identifier" | ...
> }
> ```

similarly to how we generate the node for private names (which are sigil+name, like placeholders).

---

> One difficulty that we'd have to decide here is how to handle `@FOO@ ;`. Is that an placeholder statement followed by an empty statement, or an ExpressionStatement with a `.expression` placeholder node. I'm not sure if we'd want to have slightly different grammars for expression-like and statement-like patterns.

I think that we don't need to over-complicate it: `%%FOO%%;` is an expression statement and `%%FOO%%` is a statement. No-one writes empty statements in their code.

Anyway, I think that we could/should support this placeholders:
- `Expression`
- `Statement`
- `Pattern`
- `Identifier`: this is only for function and class IDs and for import/export bindings. Other identifiers are either `Expression`s or `Pattern`s
- `ClassBody`
- `Block`: this is only for function bodies, other blocks are `Statement`s
- `StringLiteral`: this is only needed for imports. Other strings are `Expression`s

**Comment by tolmasky** [comment]
Nicolo and I discussed a bit offline, providing a summary of additional ideas and constraints here:

1. We would like non-present subsitutions to no longer throw an error: https://runkit.com/tolmasky/allow-non-present-substitutions

2. After a bit of discussion, we realized that different use cases could benefit from varying levels of flexibility in the kind of nodes you can replace. For example `class X %%body%%` might be suitable for static cases, but for our user-provided code use-case we'd want to limit the replacable nodes to expressions for example. We came up with the `allowedPlaceholderPositions` option, where you can specify this:

    ```javascript
    // This allows a placeholder to be placed *anywhere* in the source.
    parse(source, { allowedPlaceholderPositions: [Node] });

    // This limits placeholders to just Statement and Expression positions
    parse(source, { allowedPlaceholderPositions: [Statement, Expression] });

    // This is equivalent to not passing allowedPlaceholderPositions at all:
    // placeholders are not allowed.
    parse(source, { allowedPlaceholderPositions: [] });
    ```

4. In order to maintain parity with what is currently possible with templates, we'd want to expose the mechanics of this feature up through babel-transform. That is to say, we should be able to do something like:

    ```javascript
    const { parse, transform } = require("@babel/core");
    
    const AST = parse(source, { allowedPlaceholderPositions: [Statement, Expression] });
    const transformed = transform(AST, { plugins:[...] });
    ```

    We would expect placeholders to "survive" through the transform (or be handled appropriately). To allow for this, it certainly supports the idea of a PlaceholderStatement vs. PlaceholderExpression, such that `isExpression()` and `isStatement()` work fine in such transforms. This sort of thing is actually *currently* possible as a result of the fact that placeholders are just capitalized identifiers, and thus they "pass through" transforms as desired.

    As such, the actual templating can just be implemented as a normal babel plugin with no additional special features:

    ```javascript
    export default function ({ types: t }) {
        return {
            visitor: {
                Placeholder(path, state) {
                    const identifier = path.node.identifier;
                    const substitution = state.opts.substitutions[identifier];
        
                    if (!substitution)
                        throw new ReferenceError(`No substitution found for ${identifier}`);
        
                    path.replaceWith(substitution);
                }
            }
        }
    }
    ```

    This way, the `template` function can just be:

    ```javascript
    function template(source, substitutions)
    {
        return transform(source, { plugins: [
            "@babel/plugin-transform-placeholder-substitutions", { substitutions }
        ]
    }
    ```

    However, critically, **if you have additional transforms you want to run, you can do it all in one pass**:

    ```javascript
    const { parse, transform } = require("@babel/core");
    
    const AST = parse(source, { allowedPlaceholderPositions: [Statement, Expression] });
    const transformed = transform(AST, { plugins: [
        "@babel/plugin-transform-async-to-generator",
        "@babel/plugin-transform-placeholder-substitutions", { substitutions: ... }
        ]
    });
    ```
    
    Cases where these might conflict would naturally error. For example, say you provide a placeholder in the body position, but also want to transform classes:
    
    ```javascript
    const AST = parse(source, { allowedPlaceholderPositions: [Statement, Expression] });
    const transformed = transform(AST, { plugins: [
        "@babel/plugin-transform-classes"
        ]
    });
    ```
    
    Here `@babel/plugin-transform-classes` would *probably* just throw when it reaches a `PlaceholderClassBody` instead of a `ClassBody`.

5. We'd like to support member expressions in the templates. For example, something like `{%env.x%}`. Working from the example above, we could make a minor modification to the plugin to support "scoped" substitutions:

    ```javascript
        Placeholder(path, state) {
            const keyPath = path.node.keyPath; // just pseudo-code, not sure how we'd want to represent it.
            const substitution = keyPath.reduce(function (value, key)
            {
                if (!hasOwnProperty(value, key))
                    throw new ReferenceError(`${keyPath.join(".")} not found in substitutions`);
                
                return value[key];
            }, state.opts.substitutions);

            // Here I'm being strict about keeping to scalar values.
            if (!isNode(substitution) && typeof substitution === "object")
                throw new TypeError("Cannot substitute in an object.");

            path.replaceWith(substitution);
        }
    ```

    Now, you can pass in an object for substitutions:
    
    ```javascript
    template(`x = {%person.name%}`, { person: { name: "Francisco" } });
    ```

**Comment by matt-subroot** [comment]
Is there a workaround for this in the meantime? I'd like to place @keyframes animation on a placeholder.

**Comment by danez** [comment]
This is now done?

**Comment by nicolo-ribaudo** [comment]
Not fully, but I think that many things in this issue don't need to be done. I'll close it after discussing with @tolmasky.
