### ISSUE TITLE
Bug with labeled for-of loops

### ISSUE THREAD

**Issue by humanchimp** [babel/babel#913]
I ran into a couple of bugs while porting a project from traceur to babel. There seems to be some weirdness related to labeled for-of loops.

First example is pretty simple:
```javascript
function *c() {}

a: for (let b of c()) { continue a } // runtime error: Undefined label 'a'
```

Second example, this time inside a generator method:
```javascript
({ *a() { b: for (let c of d()) { continue b } }}) // compile time error: invalid completion record: {"type":"continue","target":null}
```

**Comment by sebmck** [comment]
This is a regression since a9db70b60dbdca5c70ce7b1a49d41f0c52b18c3b. FYI `for...of` loops are extremely slow in both Traceur and Babel due to spec compliancy. You can however use [loose mode](http://babeljs.io/docs/usage/loose/#es6-for-of). More information [here](http://babeljs.io/docs/faq/#why-is-the-output-of-for-of-so-verbose-and-ugly-).

**Comment by humanchimp** [comment]
I am aware of the abstraction overhead of the for..of loops since seeing Mr. Ashkena's [tweet](https://twitter.com/jashkenas/status/568511800209063936) the other day. My project is pretty far away from production at this moment, and I am not overly worried about performance, but I did note that the overall performance of this code running under traceur is not good. I've been more annoyed about other modularity nits with traceur. Thanks for the tip about the loose mode, I'll look into it.
