### ISSUE TITLE
Cannot parse yield expression in pipeline

### ISSUE THREAD

**Issue by thiagoarrais** [babel/babel#9178]
This is a problem in the current parser (master version) for pipeline operators with yield expressions. In order to reproduce it, the pipeline proposal mode needs to be set to "smart" (see `options.json` below).

**Current Behavior**
Yield expressions inside pipelines do not parse (see input code below). Instead the parser spits the following error message:

```
Unexpected token, expected "," (4:12)

      2 |   const value = -5.9
      3 |   |> Math.abs
    > 4 |   |> (yield #);
        |             ^
      5 | }
```

**Input Code**
```js
function *myGenerator() {
  const value = -5.9
  |> Math.abs
  |> (yield #);
}
```

**Expected behavior/code**
Babel Parser should be able to parse.

**Babel Configuration (.babelrc, package.json, cli command)**

options.json
```js
{
  "plugins": [
    ["proposal-pipeline-operator", { "proposal": "smart" }],
    "syntax-async-generators"
  ]
}
```

**Environment**
- Babel version(s): master
- Node/npm version: Node 11/npm 6 (should reproduce in any version)
- OS: Ubuntu/docker node:11 (should reproduce in any version)
- How you are using Babel: `make test`

**Additional context/Screenshots**

Running tests on [this branch](https://github.com/thiagoarrais/babel/tree/cannot-parse-yield-expression-in-pipeline-9178) should reproduce the error: https://github.com/thiagoarrais/babel/tree/cannot-parse-yield-expression-in-pipeline-9178

**Comment by js-choi** [comment]
I think I isolated the problem. `parseYield` uses token objects’ `beforeExpr` property to determine whether it should attempt to consume a subexpression. (This unique to `yield` because it needs to check for `*`; `parseAwait` for instance needs no such check.) Currently `tokenizer/types`’ `types.hash` lacks `beforeExpr`, which causes the bug. I’ll make a pull request fixing this soon.
