### ISSUE TITLE
Error with Dynamic key and object rest spread

### ISSUE THREAD

**Issue by isacjunior** [babel/babel#9180]
## Bug Report

**Current Behavior**
Object rest spread don't work with dynamic key 

**Input Code**
- REPL or Repo link if applicable:
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhgEwQS2FZ44BsYF4YDeAvgFCiSxQCeADgKYR6HwBcMA5HOzKedDACc6CAK7A6AxvgIwA2tXoQAdHAC6bTuwA0MGEv2IUaDGGw8SQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

```js
const addictional = {}
const types = { a: 'a' }
const reducers = { [types.a]: 'a',  ...addictional } // Error
```

**Expected behavior/code**
In Chrome, for example, I have this code working

```js
const addictional = {}
const types = { a: 'a' }
const reducers = { [types.a]: 'a',  ...addictional } // {a: "a"}
```

**Environment**
Babel repl
Chrome Version 70.0.3538.110

**Comment by existentialism** [comment]
@isacjunior IIRC this is fixed in 7.x:

https://babeljs.io/repl#?babili=false&browsers=&build=master&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhgEwQS2FZ44BsYF4YDeAvgFCiSxQCeADgKYR6HwBcMA5HOzKedDACc6CAK7A6AxvgIwA2tXoQAdHAC6bTuwA0MGEv2IUaDGGw8SQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=false&targets=&version=7.2.0&envVersion=7.2.0

**Comment by isacjunior** [comment]
Thank you.
