### ISSUE TITLE
Uncaught Reference Error: exports is not defined

### ISSUE THREAD

**Issue by taoqf** [babel/babel#9187]
## Bug Report

**Current Behavior**

After build, it will throw an error: 'Uncaught Reference Error: exports is not defined'.
there is something in bundle file like this:

```
Object.defineProperty(exports,"__esModule",{value:!0})
```

babel v6 is OK.

which cause this exception.

**Input Code**
- <https://github.com/taoqf/demo>

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
	"presets": [
		"@babel/preset-env"
	],
	"plugins": [
		"@babel/plugin-transform-runtime",
		"@babel/plugin-proposal-object-rest-spread"
	]
}
```

**Environment**
- Babel version(s): [ v7]
- Node/npm version: [Node v11]
- OS: [Debian 4.9.130-2]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [`loader`]

**Possible Solution**

back to v6
**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by danez** [comment]
I think the problem in your case is that typescript is already transforming imports and exports. Try changing the modules option of typescript to `es2015` or an other appropriate option.

Or otherwise try to use one of these solutions: https://github.com/webpack/webpack/issues/3974#issuecomment-369260590

**Comment by taoqf** [comment]
Thanks. but is this is a bug and would it be fixed later? because my project is much more difficult than the demo.

**Comment by loganfsmyth** [comment]
Since you are compiling a CommonJS module you need to tell Babel that, because otherwise it assumes that input files are ES modules. The way to do that is with the `sourceType` options: https://babeljs.io/docs/en/options#sourcetype

The easiest thing would be to add `sourceType: 'unambiguous'` to your Babel config.

**Comment by taoqf** [comment]
But after I downgrade to v6, it went fine.

**Comment by loganfsmyth** [comment]
Yep, Babel 6 handles modules a bit differently, which caused a different set of issues.

**Comment by taoqf** [comment]
Thanks.
