### ISSUE TITLE
Couldn't find any versions for "@babel/helper-replace-supers" that matches "^7.2.3"

### ISSUE THREAD

**Issue by aaronplanell** [babel/babel#9269]
## Bug Report

**Current Behavior**
It's impossible to install the last version of @babel/helper-replace-supers (7.2.3). It doesn't exist.

**Input Code**
```
create-react-app test-storybook
cd test-storybook
npx -p @storybook/cli sb init
```

**Expected behavior/code**
I expected that it will be installed normally, but:
```
➜  test-storybook git:(master) npx -p @storybook/cli sb init

npx: installed 423 in 33.632s
[BABEL] Note: The code generator has deoptimised the styling of /Users/aplanell/.npm/_npx/9912/lib/node_modules/@storybook/cli/node_modules/lodash/lodash.js as it exceeds the max of 500KB.

 sb init - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
 • Adding storybook support to your "Create React App" based project. ✓
 • Preparing to install dependencies. ✓

yarn install v1.9.4
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "@babel/helper-replace-supers" that matches "^7.2.3"
? Please choose a version of "@babel/helper-replace-supers" from this list: (Use arrow keys)
❯ 7.1.0
  7.0.0
  7.0.0-rc.4
  7.0.0-rc.3
  7.0.0-rc.2
  7.0.0-rc.1
  7.0.0-rc.0
```

**Babel Configuration (.babelrc, package.json, cli command)**
Don't apply

**Environment**
- Babel version(s): 7.2.3
- Node/npm version: Node 8.12.2/npm 6.4.1
- OS: OSX 10.12.2
- How you are using Babel: [`loader`]

**Possible Solution**
Generate de package @babel/helper-replace-supers for the version 7.2.3.

**Additional context/Screenshots**
I saw the original commit: https://github.com/babel/babel/commit/0bb720401bc73c99b6326fe8c61710803dc4d3fd and mentioned @nicolo-ribaudo .

**Comment by aaronplanell** [comment]
Same problem if you run:
```
yarn add @babel/helper-replace-supers --dev
```

**Comment by danez** [comment]
This works fine for me. http://registry.npmjs.org/@babel/helper-replace-supers

Might be a problem on your side. Do you have a npm proxy in place?

**Comment by aaronplanell** [comment]
Sorry everybody, specially to @danez . In my home works perfectly. I guess it's a problem of the Nexus of my enterprise. Obviously it's not a bug. Sorry again.

**Comment by loganfsmyth** [comment]
Unfortunately, as far as I'm aware, Nexus' cache invalidation logic just doesn't handle interdependent packages well at all. Say we have

* `@babel/helper-replace-supers@7.1.0`
* `@babel/plugin-transform-classes@7.1.0` which depends on `@babel/helper-replace-supers@7.1.0`

and you have both of these in your cache.

Nexus seems to just cache based purely on time, so if we then publish new `7.2.0` versions of both of these packages, what happens if the cache for `@babel/plugin-transform-classes` expires first? Your cache would update to have `@babel/plugin-transform-classes@7.2.0`, but still have `@babel/helper-replace-supers@7.1.0`, which means that `@babel/plugin-transform-classes` can't be installed, because it requires `@babel/helper-replace-supers@7.2.0`, which isn't found yet because the cache for it hasn't been invalidated.

This is based on my understanding anyway, but it's hard to be 100% sure.
