### ISSUE TITLE
module syntax not compatible with output concatenation?

### ISSUE THREAD

**Issue by ondras** [babel/babel#928]
Disclaimer: I am new to babel, so this might be just me not understanding stuff properly.

Say I have these two files:

```js
// a.js
export var a1 = 5;
var a2 = 3;

// b.js
import * as a from "a";
alert(a.a1);
```

Babel's output (all defaults) is:

```js
"use strict";

var a1 = exports.a1 = 5;
var a2 = 3;
Object.defineProperty(exports, "__esModule", {
  value: true
});
"use strict";

var _interopRequireWildcard = function (obj) { return obj && obj.__esModule ? obj : { "default": obj }; };

var a = _interopRequireWildcard(require("a"));

alert(a.a1);
```

Apart from multiple "use strict" declarations, the result is not really usable. There is no module-level isolation (i.e. wrapping the contents inside a anonymous function) and the whole export/import/require machinery does not work at all.

So,

1. am I using the stuff correctly?
1. am I required to use different tools for proper concatenation/packing?
1. why is "use strict" present multiple times?
1. are there plans to provide the relevant functionality (anonymous wrapping, require/define implementation) in the future, not relying on other tools?

**Comment by sebmck** [comment]
> 1. am I using the stuff correctly?

Most likely.

> 2. am I required to use different tools for proper concatenation/packing?

Yeah, see 4.

> 3. why is "use strict" present multiple times?

Because the result is just getting concatenated together as the files are being transpiled separately.

> 4. are there plans to provide the relevant functionality (anonymous wrapping, require/define implementation) in the future, not relying on other tools?

Anonymous wrapping could easily be added as an additional optional transformer. Require/define implementation, no. Conflating a transpiler with a module bundler is a slippery slope and it's a massive undertaking which is pointless when there's already browserify and webpack that work great. Modules wont work unless you use browserify with [babelify](https://github.com/babel/babelify) or webpack with [babel-loader](https://github.com/babel/babel-loader).

**Comment by ondras** [comment]
> 2. am I required to use different tools for proper concatenation/packing?
> 
> Yeah, see 4.

I see, thanks @sebmck for explanation. So, why exactly is there the option to concatenate output, when this creates - in most scenarios - a sub-optimal code (even if I was not using ES6 modules, there will be multiple strict declarations). What is the use-case for the `-o` feature?

**Comment by sebmck** [comment]
Makes more sense to allow support for multiple input files for `--out-file` when `--out-dir` can accept multiple too.
