### ISSUE TITLE
NO syntax highlighting in my IDE

### ISSUE THREAD

**Issue by yuri2peter** [babel/babel#9338]
Transcoded code does not get syntax highlighting in my IDEs.

This maybe because the transcoded code becomes more difficult to parse for IDEs.

![image](https://user-images.githubusercontent.com/23306626/51154544-127c7300-18af-11e9-9675-65e222e68dfe.png)

The methods getLocaleType && setLocaleType can not be autocompleted.

**I sincerely look forward to your answer.**

PS:
- My favorite IDE is webstorm.
- SourceMap is not working in this situation.

**Comment by nicolo-ribaudo** [comment]
Does webstorm support arrow functions?

Anyway, this is a bug with your IDE, not with Babel

**Comment by loganfsmyth** [comment]
We don't generally keep issues open unless they are explicitly actionable items. We can absolutely continue the discussion here, but since there isn't really anything for us to do here, there isn't any reason to have the issue open.

> The only problem is the loss of syntax highlighting.

We have absolutely zero control over how one editor may choose to highlight a given piece of code.

> Is there any similar solution for transcoded code syntax highlighting ?

This is entirely up to the editor. Seems like a bug that I would raise with them, ideally with a reproducible example.

**Comment by yuri2peter** [comment]
> We have absolutely zero control over how one editor may choose to highlight a given piece of code.

Yes, you are right. 

Just for confirm, am I the only one who has encountered this kind of problem?

If there is no way to influence IDE behavior right now, does that mean that we need to propose a specification (similar to sourceMap)?

**Comment by nicolo-ribaudo** [comment]
The specification is already there: it's ECMAScript, and IDEs should support it.
