### ISSUE TITLE
class properties transform

### ISSUE THREAD

**Issue by lifeiscontent** [babel/babel#9347]
## Bug Report

**Current Behavior**
class properties get set before constructor, not after.

**Input Code**
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=usage&spec=true&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oDNHQLzQBcALASwgDoAjMAJwG51ph4A7CAmgV2APhoApqNAJQpGGYmSq080IQwwBfVMtTM2BLDnwsApgHc4ifgHJJLAOYQTwhmtYR4IXeRDwL_bPFtA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript%2Cenv&prettier=true&targets=&version=7.0.0-beta.53&envVersion=7.0.0-beta.52

```js
class Foo {
  constructor(bar) {
    this.bar = bar;
  }
  foo = this.bar;
}

const foo = new Foo('things');

console.log(foo.foo); // undefined
```

**Expected behavior/code**

class properties should run after constructor code.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

not sure yet

**Additional context/Screenshots**

if class properties ran after, the code would read more simply. I'm not sure if this is something that is by design, but any context on where I can propose this change would be helpful.

Thanks for your consideration.

**Comment by loganfsmyth** [comment]
> Expected behavior/code
> class properties should run after constructor code.

That's definitely not the current spec behavior. All class properties are evaluated before the constructor's function body executes (for base classes), and just before `super()` finishes evaluating (for subclasses).

> any context on where I can propose this change would be helpful.

The spec is developed at https://github.com/tc39/proposal-class-fields.

> if class properties ran after, the code would read more simply.

I think you'll find a lot of disagreement with that statement. To clarify, since for me it's not super clear from your example, are you saying that should be the case for all class properties, or saying it should be the case for all properties placed after the `constructor`? I'd recommend bringing this to the spec repo for discussion, but I'd personally find it very surprising if class properties behaved differently depending on where they were placed relative to methods that are otherwise, in my mind at least, conceptually unrelated.

**Comment by lifeiscontent** [comment]
@loganfsmyth I agree with you, it should be **always** not based on position. the point here would be you could specify dependencies of a class in a constructor, and then for class properties, you could then use anything you've previously assigned in the constructor saving a lot of time writing `this.methodName` for all the properties and just write `methodName`

**Comment by nicolo-ribaudo** [comment]
This is the expected behavior, and matches the proposed specification.
