### ISSUE TITLE
path.replaceWith causes stack overflow

### ISSUE THREAD

**Issue by FireCubez** [babel/babel#9413]
## Bug Report

**Current Behavior**
A stack overflow.

**Input Code**
[ASTExplorer](https://astexplorer.net/#/gist/243c656ea765d443e9329bfe9e424250/f8e708b959e8789ec2d8b689afa2fa25e505a4d5)

```js
a + 1

// Replace binary operators
module.exports = function({ types: t }) {
  return {
    visitor: {
      BinaryExpression(path) {
        path.replaceWith(
          t.binaryExpression("**", path.node.left, t.numberLiteral(2))
        );
      }
    }
  };
};
```

**Expected behavior/code**
Expected output of `a ** 2`

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": ["./myplugin.js"]
}
```

**Environment**
- Babel version(s): v7.2.2
- Node/npm version: Node v10.15.0/npm 6.4.1
- OS: Windows 10 64 bit
- Monorepo: ??
- How you are using Babel: Programmatically (`babel.transform`)

**Comment by motiz88** [comment]
I don't know that there's much Babel could do in the general case here. You could trivially modify your visitor function to check whether the node needs transforming, and then call `replaceWith` only as needed rather than unconditionally.

**Comment by FireCubez** [comment]
Do you mean this isn't a bug? In the [babel handbook](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#replacing-a-node), this is given as a working example, yet it doesn't work and throws an error.

**Comment by motiz88** [comment]
That's a good point. I'm not sure whether that particular snippet was meant to be runnable on its own, and that might be useful to clarify in the handbook. Personally I think the intention was to show _how_ and _in what context_ to use `replaceWith`. A similar but runnable example might look something like this:

```js
BinaryExpression(path) {
  if (path.node.operator === '**') return;
  path.replaceWith(
    t.binaryExpression("**", path.node.left, t.numberLiteral(2))
  );
}
```

**Comment by FireCubez** [comment]
So I make sure I understand correctly, path.replaceWith calls the handler of the node it replaces? This is my code:
```js
Expression(path) {
  var callee = path.node.callee;
  if (t.isMemberExpression(callee) && t.isIdentifier(callee.object, {
    name: "shup"
  })) return
  path.replaceWith(
    t.callExpression(
      t.memberExpression(
        t.identifier("shup"),
        t.identifier("expression")
      ),
      [
        path.node
      ]
    )
  )
}
```
But that also causes a stack overflow. If I add `path.skip()` before the return statement it works, but skips traversing some of the nodes. For example for an input of `a().b.c` I would expect an output of:
```js
shup.expression(shup.expression(shup.expression(a()).b).c)
```
but instead get:
```js
shup.expression(a().b.c)
```

**Comment by nicolo-ribaudo** [comment]
This is what your code does, because `shup` is itself an expression:

| **Current code** | **Current visited node** | **Should replace?** | **Replace with** | **Output** |
|------------------|--------------------------|------------------|------------|-|
| `a().b.c` | `a().b.c`	| Yes | `shup.expression(a().b.c)` | `shup.expression(a().b.c)` |
| `shup.expression(a().b.c)` | `shup.expression` | No | | |
| `shup.expression(a().b.c)` | `shup` | Yes  | `shup.expression(shup)` | `shup.expression(shup).expression(a().b.c)` | 
| `shup.expression(shup).expression(a().b.c)` | `shup.expression` (the left one) | No | | |
| `shup.expression(shup).expression(a().b.c)` | `shup` (the left one) | Yes | `shup.expression(shup)` | `shup.expression(shup).expression(shup).expression(a().b.c)` |
| ... |

**Comment by FireCubez** [comment]
Ah, thanks. I fixed this by adding a special "__shupIgnore__" property to the replacement and adding a check for that.
