### ISSUE TITLE
Can you please stop shipping this plugin and remove it?

### ISSUE THREAD

**Issue by trusktr** [babel/babel#9451]
It goes against inheritance (it uses `[[Define]]`); honestly it is not intuitive and will cause problems.

Furthermore, [private fields were bumped from stage 1 to stage 3 in less than 2 months](https://github.com/tc39/proposal-class-fields/issues/203#issuecomment-451777597), which is not  fair to the JavaScript community that largely dislikes the proposal.

Please! Thanks!

**Comment by trusktr** [comment]
[This thread](https://github.com/tc39/proposal-class-fields/issues/100) summarized the huge amount of community opposition to private fields back in May. The numbers are even higher now.

**Comment by trusktr** [comment]
It would be great for Babel to have weight in the standards process (because it can) and prevent something from being prematurely released.

**Comment by nicolo-ribaudo** [comment]
No, we won't do it.

1) https://www.npmjs.com/package/@babel/plugin-proposal-class-properties
  4 millions of weekly downloads. And it is not in a preset: people are explicitly using it. It doesn't mean that 4 millions of developers are using this proposal: many downloads come from CI servers, and many enterprises have npm proxies so they don't increase the downloads count. But even if the "real downloads" were only 100k, the numbers you linked are nothing in comparison.

2. Many people worked really hard on this plugin: the public-fields+private-fields+private-methods combo required an enormous amount of work. @tim-mc opened a new PR yesterday (#9446): we are going ahead. We are not throwing away our work because a small number of developers doesn't like it.

3. We don't have this kind of veto power you are asking us to apply, and we don't want to have it. We can help TC39 folks in their decisions. We might not implement a stage-1 proposal because no one of us doesn't like it and thus no one opens a PR, but we would welcome any external contribution about it anyway. We can't definitely refuse to implement a stage-3 proposal. One of Babel's goal is to allow people to use those proposal: implementing them is exactly what we want, even if someone doesn't like it.

**Comment by trusktr** [comment]
> 4 millions of weekly downloads.

From people already using class fields, before private fields got shoehorned in, with all its problems. Please don't disguise things.

**Comment by trusktr** [comment]
I'm also willing to bet people install all the plugin indirectly, not knowing about the issues, because they just want all the "cool" latest features, so they install presets, etc.

I bet MANY people install that plugin just to have the convenient syntax around public properties, and have no ideas about the shoehorned private problems.

**Comment by trusktr** [comment]
I also know for fact, that the vast majority of people who care to be involved, are the ones who go vote on things, and the votes are negative in large part due to private fields.

Stop twisting facts like they are a disguise for a monster.

**Comment by trusktr** [comment]
Honestly saying, most people don't GAF about language decisions. Most people just care about the bottom line: will they be able to make money-making apps now, or even later if some feature might be useful in some case?

Yeah? Then good: they'll continue installing ALL the upcoming language features, and move on. It does NOT mean they know they actually **like** the feature. You know this as well as I do.

**Comment by nicolo-ribaudo** [comment]
Ok then read point 3 again: for us it's a good enough reason to implement class fields.

If you are ok with the syntax of the proposal but not with the semantics, you can create your own Babel plugin which transpiles the proposed syntax to lowclass.
