### ISSUE TITLE
"Invalid left-hand side in assignment": incorrectly reported as SyntaxError

### ISSUE THREAD

**Issue by getify** [babel/babel#9487]
## Bug Report

**Current Behavior**
Code like `2++` or `3 = 2` result in a `SyntaxError` ("Invalid left-hand side assignment"), when they should be resulting in an error of type `ReferenceError`.

According to the spec, they are not invalid syntax, but are rather runtime errors. In fact, you could make the case the parser shouldn't error on them at all, but if it's going to error, it would be helpful if it was correctly labeled to be consistent with what is reported in Chrome devtools console, for instance.

**Input Code**

```js
2++;
3 = 2;
```

**Expected behavior/code**
Either no parsing exception at all, or a `ReferenceError` reported.

**Environment**
- Babylon version: 6.18.0
- Node/npm version: Node 10.15.0
- OS: OSX 10.14

**Additional context/Screenshots**

<img width="689" alt="screen shot 2019-02-10 at 12 34 33 pm" src="https://user-images.githubusercontent.com/150330/52537807-3c9b4680-2d30-11e9-8101-5e53537313d5.png">

**Comment by nicolo-ribaudo** [comment]
According to your screenshot those aren't runtime errors: the functions aren't called.

**Comment by getify** [comment]
Yes sorry I misspoke. This issue should stay focused on the wrong error type.

**Comment by oliverdunk** [comment]
Link to spec: https://www.ecma-international.org/ecma-262/9.0/index.html#sec-update-expressions-static-semantics-early-errors

My naive guess is that we could just add an empty case to the `checkLVal` (https://github.com/babel/babel/blob/master/packages/babel-parser/src/parser/lval.js#L330) function, for `NumericLiteral`.

Is that a good solution? I'd be happy to PR this if so.

**Comment by nicolo-ribaudo** [comment]
No, that would disable the error: it should be thrown, but it should be a `ReferenceError` instead of a `SyntaxError`. You should update the `raise` function (https://github.com/babel/babel/blob/master/packages/babel-parser/src/parser/location.js#L13) to accept another option (e.g. `ErrorClass`), which defaults to `SyntaxError` but can be set to another error.

I'm not 100% sure that it would be a backward compatible change (error kinds are often considered as part of the public interface). 
If others think that it would be breaking, we could instead add a `kind: "SyntaxError" | "RuntimeError"` property to the thrown error object.

**Comment by getify** [comment]
@nicolo-ribaudo that should "ReferenceError" not "RuntimeError".

I would find it weird to receive an error object of SyntaxError type but ReferenceError kind... that's strangely ambiguous, as one is not a subset of the other.

Also, that would still "break" things in that apps/tools would still have to update to start looking at the extra property, for them to be adherent anyway. They could keep being broken-but-working without change.

**Comment by nicolo-ribaudo** [comment]
> that should "ReferenceError" not "RuntimeError".

Yeah sorry, I meant ReferenceError.

Internally, we `try/catch` to disambiguate different syntaxes (e.g. `<foo>() => {}` vs `<foo>() => {}</foo>` and check that the thrown error is a `SyntaxError`, so that is why I brought up the possible problem: when the internal usage of a public api needs to be changed, it isn't a good sign.
Now that I'm thinking about it, those `ReferenceError`s are thrown when the code has been parsed correctly, but it does something wrong: they aren't needed to disambiguate between different syntaxes. Changing the error type might be safer than I initially tought.

**Comment by nicolo-ribaudo** [comment]
The spec now matches Babel's behavior: https://github.com/tc39/ecma262/pull/1527
