### ISSUE TITLE
Have `babel-runtime` depend on `core-js` instead of bundling?

### ISSUE THREAD

**Issue by coreh** [babel/babel#965]
Hi there,

I searched for existing issues on this matter but couldn't find anything... I would like to know: would it be feasible to add `core-js` as a dependency of `babel-runtime` and just have `babel-runtime` re-export its code, instead of bundling it like it's currently done?

Right now I have a library that is compiled from ES6 using babel, and I'm using the `runtime` transform so that the polyfills don't get duplicated when using it along with other babel-compiled ES6 libraries.

So far so good, however an ES5 project that uses my library also uses `core-js` directly, and this is causing the `core-js` code to be duplicated during the final Browserify build step, increasing the build size.

I assume there might be a reason for bundling `core-js`, if so, is there another way I can work around this?

Thanks.

**Comment by sebmck** [comment]
>  however an ES5 project that uses my library also uses core-js directly

Is it using `core-js/library`?

**Comment by zloirock** [comment]
@sebmck I think, be better add it as dependence for automatic update at patch releases.

**Comment by sebmck** [comment]
Yup I agree. I recall there being a specific reason but I'm not sure, if I
can't think of anything I'll switch it over. I'm looking into overhauling
the runtime transformer so it uses specific files for each helper so it'll
probably wait until that. I'm currently enforcing babel-runtime versions be
the same as their babel version so "breaking changes" can happen in
minors/patches.

On Saturday, 7 March 2015, Denis Pushkarev <notifications@github.com> wrote:

> @sebmck <https://github.com/sebmck> I think, be better add it as
> dependence for automatic update at patch releases.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/965#issuecomment-77679903>.
>


-- 
Sebastian McKenzie

**Comment by TooTallNate** [comment]
>  I'm currently enforcing babel-runtime versions be the same as their babel version so "breaking changes" can happen in minors/patches.

Please learn [semver](http://semver.org/). This statement is really unacceptable for the npm community…

**Comment by TooTallNate** [comment]
Apologies, that sounded overly aggressive. I didn't intend that.

Let me explain how we're using babel in more detail, and you'll understand why we need semver compliance, especially when trying to use babel on the browser via a bundler like browserify.

We've been writing lots of modules intended for browser use, for example: [`node-iterator`](https://github.com/webmodules/node-iterator). Babel works great on the browser and we've been loving using ES6, so thank you for enabling that for our team! The Babel project historically has moved very quickly, already at version 4+. It's been entertaining trying to keep our many modules up-to-date with babel on a pretty-much weekly basis. To try to minimize that maintenance burden, we've been pinning the `babel-runtime` dep to it's latest major version (i.e. [`4`](https://github.com/webmodules/node-iterator/blob/f2a7a48b44db49a0b1d1f4da51bdb354ea157e8c/package.json#L30)), since by semver rules there should be no breaking changes in this time.

So my main concern is that an npm module, precompiled with `babel` compiler v4.0.0, and depending on any `babel-runtime@4`, will always be guaranteed to work with the latest `babel-runtime` (i.e. v4.7.3). Can we get that kind of guarantee?

**Comment by coreh** [comment]
> Is it using core-js/library?

Yep. TBH I'd rather use `babel` and `babel-runtime` for everything but this project already has a build pipeline set up, and unfortunately that can't really be changed right now.

> I recall there being a specific reason but I'm not sure, if I can't think of anything I'll switch it over.

:smile: Awesome. Thanks for considering this.

> > I'm currently enforcing babel-runtime versions be the same as their babel version so "breaking changes" can happen in minors/patches.
>
> Please learn semver. This statement is really unacceptable for the npm community…

So, I do understand the advantages of having `babel-runtime` and `babel` version numbers being in sync, for example being able to know which version to use on `package.json` at a glance. However, I also have to agree with @TooTallNate in the sense that that having the possibility of breaking changes/incompatibility between `babel` and `babel-runtime` on minor or patch versions is kinda scary.

> I'm looking into overhauling the runtime transformer so it uses specific files for each helper so it'll probably wait until that. 

Hmm... This is one of the changes that could quite possibly break compatibility between `babel` and `babel-runtime` of different versions.

Right now publishing ES6 modules on npm, precompiled down to ES5, that depend on `babel-runtime` is a bit of a catch-22: If you pin a specific version in `package.json`, your user will get multiple versions of `babel-runtime` installed unless every single module uses the same version of `babel-runtime` (unlikely given how fast this project is moving). If you don't pin a specific version, the user gets whatever version they're already using, or the latest version out. This puts compatibility at risk since breaking changes might happen at any time.

The need for a strict correspondence between whatever `babel-runtime` exposes and what the code generated by `babel` expects, and the fact that the generated code might change in the future for any given input program, even on minor or patch versions, makes this an ABI compatibility issue.

One viable approach would be to keep matching `babel` and `babel-runtime` versions, but then bump the major version of `babel` whenever ABI compatibility is broken on the `babel-runtime` side.

**Comment by sebmck** [comment]
@coreh 

> However, I also have to agree with @TooTallNate in the sense that that having the possibility of breaking changes/incompatibility between babel and babel-runtime on minor or patch versions is kinda scary.

`babel` and `babel-core` will check if a version of `babel-runtime` is installed and throw an error if it's not the same version.

```javascript
try {
  var runtimePackage = require("babel-runtime/package");
  var version = require("../../package").version;
  if (runtimePackage.version !== version) {
    throw new ReferenceError(`The verison of babel-runtime of ${runtimePackage.runtime} that you have installed does not match the babel verison of ${version}`);
  }
} catch (err) {
  if (err.code !== "MODULE_NOT_FOUND") throw err;
}
```

> One viable approach would be to keep matching babel and babel-runtime versions, but then bump the major version of babel whenever ABI compatibility is broken on the babel-runtime side.

Everyone seems to underestimate the amount of work that actually bumping a major version of babel actually is :smile: I don't particularly like bumping majors, especially when **I** have to go and update the following plugins, submit a PR or hassle the maintainer to update:

 - `babelify`
 - `babel-connect`
 - `babel-jest`
 - `babel-library-boilerplate`
 - `babel-loader`
 - `accord`
 - `atom`
 - `atom-shell-starter`
 - `broccoli-babel-transpiler`
 - `brunch-babel`
 - `cogs-transformer-babel`
 - `grunt-babel`
 - `duo-babel`
 - `ember-cli-babel`
 - `ember-cli`
 - `es6-module-loader`
 - `espower-babel`
 - `gobble-babel`
 - `gulp-babel`
 - `isparta`
 - `kake-babel`
 - `publicist-babel`
 - `sails-hook-babel`
 - `jade-babel`
 - `jspm`
 - `JSXLint`
 - `karma-babel-preprocessor`
 - `kraken-devtools-babel`
 - `metalsmith-babel`
 - `mimosa-babel`
 - `sprockets-es6`
 - `ruby-babel`

There's plenty more but can't be bothered going through the entire npm dependents list.
 
@TooTallNate 

It's not unreasonable to force people to use the same version of `babel` with `babel-runtime`. If I bumped on any helpers changes then I **cannot** remove, modify or add additional helpers to the generated output and you're grossly underestimating how restricting that is. The helpers are used extensively and I make changes to them on a regular basis to improve spec compliancy, make them smaller etc.

> So my main concern is that an npm module, precompiled with babel compiler v4.0.0, and depending on any babel-runtime@4, will always be guaranteed to work with the latest babel-runtime (i.e. v4.7.3). Can we get that kind of guarantee?

No, see the aforementioned reasons.

**Comment by sebmck** [comment]
Just so I'm crystal clear, bumping majors on **any** helper changes which is what you're proposing (it's also quite insulting) means:

 - No new features (since most of them rely on small helpers)
 - No helper optimisations (sometimes I change the names/arguments for better output/performance)
 - An enormous amount of work when I want to make trivial internal changes

**Comment by coreh** [comment]
> Everyone seems to underestimate the amount of work that actually bumping a major version of babel actually is :smile: I don't particularly like bumping majors, especially when I have to go and update the following plugins, submit a PR or hassle the maintainer to update:
> * *[huge list]*

Oh wow, okay, I didn't know that.

> Just so I'm crystal clear, bumping majors on any helper changes which is what you're proposing. [...]

Oh, I only proposed bumping it if the change was backwards incompatible. Not every time! But now that I have an idea of how many things you'd have to update, I can see how this would get cumbersome very fast, and how it could hinder progress with the compiler.

I think maybe shipping precompiled modules is really not the way to go then, at least for now while the compiler is moving so fast and the helpers are still subject to a lot of changes.

@sebmck Thanks for taking the time to reply this to us on a sunday, btw. :smile:

**Comment by sebmck** [comment]
> Oh, I only proposed bumping it if the change was backwards incompatible.

Any additional helpers would be backwards incompatible because they wouldn't exist in `babel-runtime`. I dislike being limited by external APIs, especially ones that I've created :stuck_out_tongue: Hence restricting the `babel-runtime` version to the same as the `babel` version that compiled it.

**Comment by TooTallNate** [comment]
I just hope you know that by making this decision (of _actively_ not playing the semver :baseball: game), you're adding the additional maintenance burden of constantly (i.e. weekly) explicitly checking if a new babel version has been released and manually updating all modules that depend on it.

Honestly, I just can't imagine it being that hard to add backwards-compatible polyfills when necessary. This is JavaScript after all…

**Comment by sebmck** [comment]
@TooTallNate 

> I just hope you know that by making this decision (of actively not playing the semver :baseball: game), you're adding the additional maintenance burden of constantly (i.e. weekly) explicitly checking if a new babel version has been released and manually updating all modules that depend on it.

No you don't. You just have to keep the `babel` and `babel-runtime` versions in tandem. It's not that much of a stretch to encourage the use of the same version, especially for modules that expose internal APIs that are so tightly integrated.

Insulting me by saying "please learn semver" and repeatedly pushing the semver mantra is absurd. I follow semver religiously (I do not consider this a violation of semver) and constantly get people rolling their eyes saying "wow 4.0.0 was just released and a week later they're on 4.x, ugh". Have you been biten by this? If so I'd like to hear how so I can avoid it happening in the future. As I said previously I'm enforcing that `babel` and `babel-runtime` versions be equivalent so I think I've got all bases covered.

I'm not willing to have this bikeshedding semver discussion in this issue as it isn't even relevant to it so I don't even know why it was bought up. Sorry for the bitterness, I just don't appreciate personal attacks like "learn semver" that show a complete ignorance for the development practices that I've put in place as well as the work and commitment that I have.

> Honestly, I just can't imagine it being that hard to add backwards-compatible polyfills when necessary. This is JavaScript after all…

Now you're just being ridiculous.

I recently changed the output of:

```javascript
class Foo { foo() {} }
```

from

```javascript
var Foo = (function () {
  function Foo() {
    _classCallCheck(this, Foo);
  }

  _prototypeProperties(Foo, null, {
    foo: {
      value: function foo() {},
      writable: true,
      configurable: true
    }
  });

  return Foo;
})();
```

to

```javascript
var Foo = (function () {
  function Foo() {
    _classCallCheck(this, Foo);
  }

  _createClass(Foo, {
    foo: {
      value: function foo() {}
    }
  });

  return Foo;
})();
```

How do you propose that **ever** be done in a backwards compatible way? ie. the helper `prototypeProperties` was renamed to `createClass`, the repeated descriptor properties have been removed and instance descriptors are the second argument instead of the third. You seem to be conflating backwards compatibility with forwards compatibility which is an impossible problem to solve.

**Comment by sebmck** [comment]
I'm going to lock this issue as I don't see this discussion being very productive and is completely derailing. I've said all I need to on the matter.

In the next patch/minor `core-js` will be aliased in `babel-runtime`. Thanks for the suggestion @coreh!
