### ISSUE TITLE
Add option to preset-react / transform-react-jsx to output object spread syntax

### ISSUE THREAD

**Issue by Jessidhia** [babel/babel#9652]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, transform-react-jsx either outputs uses of the `extend` helper or calls to `Object.assign` for handling spread props (any attribute with `{...Expression}`).

**Describe the solution you'd like**
An option to instead convert such instances to an inline object with spread elements.

This would still allow `@babel/preset-env` to further transform the inline object if the allowed targets don't support object spread.

**Teachability, Documentation, Adoption, Migration Strategy**
If it wasn't a semver-major change I'd be as bold as to say that it's safe to make it enabled by default -- I suspect almost no project runs `@babel/preset-react` without also using `@babel/preset-env`, and native object rest spread has been supported by it even without requiring the `shippedProposals` option. It has also been shipping on browsers and node (LTS, even) for over a year.

**Comment by nicolo-ribaudo** [comment]
Hi :wave:
If anyone wants to take a look at this issue, here are a few hints:
- That option can be named `useSpread`, similarly to `useBuiltIns`
- This option also needs to be documented in the `babel/website` repo!
- The transform isn't actually implemented in `@babel/plugin-transform-react-jsx`, but in `@babel/helper-builder-react-jsx`. Since this helper doesn't have any tests, it's ok to put them in the `babel-plugin-transform-react-jsx/tests` folder.

---

If it is the first time that you contribute to Babel, follow these steps: (you need to have `make` and `yarn` available on your machine)
1. **Write a comment there** to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest plugin-transform-react-jsx` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again.
    - If you prefer, you can run `OVERWRITE=true yarn jest plugin-transform-react-jsx` and they will be automatically updated.
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by ivandevp** [comment]
I have contributed in 1 issue before but I'd like to help with this if nobody else want to take it :sweat_smile:

**Comment by nicolo-ribaudo** [comment]
Since your other issue was in a completely different part of Babel, let's do like this: if someone comments in 5 minutes you two can try working on this bug together (you can coordinate using our Slack), otherwise I'll assign this issue to you :+1:

**Comment by biddwan09** [comment]
Hi @nicolo-ribaudo can i work on this issue with @ivandevp . I am really interested to start contributing on this project
