### ISSUE TITLE
Core-JS imports are duplicated between core-js@3 and core-js-pure@3

### ISSUE THREAD

**Issue by renchap** [babel/babel#9728]
## Bug Report

**Current Behavior**
I upgraded to Babel 7.4.0 and core-js 3.
I need to include some global Polyfills due to dependencies requiring them (for example React requires `Symbol`).
I am using `useBuiltIns: "usage"` in my `env` config.

Many polyfills end up being duplicated in my Webpack bundle because they get imported once from `core-js@3` due to my globally-polluting imports, and once again from `core-js-pure@3` from the `preset-env` imports.

![image](https://user-images.githubusercontent.com/42070/54722378-b232d780-4b64-11e9-816b-28681d402c56.png)

**Expected behavior/code**
I am not really sure what the expected behaviour would be here, but I expect my bundle to now grow in size because I am using `core-js@3`.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
presets = [
  "@babel/preset-typescript",
  "@babel/preset-react",
  [
    "@babel/preset-env",
    {
      useBuiltIns: "usage",
      corejs: 3,
    },
  ],
]

plugins = [
  "@babel/plugin-syntax-dynamic-import",
  "@babel/plugin-proposal-object-rest-spread",
  "@babel/plugin-proposal-class-properties",
  ["@babel/plugin-transform-runtime", { regenerator: false, corejs: 3 }],
]

module.exports = { presets, plugins }
```

**Environment**
- Babel version(s): 7.4.0
- Node/npm version: 11.11.0 / 6.7.0
- OS: OSX 10.14.2
- Monorepo: no
- How you are using Babel: `loader`

**Comment by zloirock** [comment]
It's the problem of your config. You should use one - `useBuiltIns: "usage"` or `runtime` with `corejs` option. In your case, you don't need `corejs` `runtime` option - use it only for helpers.

**Comment by renchap** [comment]
Woops, I am very sorry, I missunderstood this config and thought it needed to be configured to use CoreJS 3 as well. 
It works as expected now, thanks!

**Comment by radum** [comment]
So if I have this config:

```
const presets = [
    [
        '@babel/preset-env',
        {
            modules: false,
            useBuiltIns: 'usage',
            debug: false,
            corejs: 3
        },
    ],
];

const plugins = [
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-transform-runtime'
];
```

and these packages installed:

```
"dependencies": {
    "@babel/runtime": "7.4.2",

"devDependencies": {
    "@babel/core": "7.4.0",
    "@babel/plugin-proposal-class-properties": "7.4.0",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/plugin-transform-runtime": "7.4.0",
    "@babel/preset-env": "7.4.2",
    "core-js": "3.0.0",
```

This is all I need in this scenario.

`preset-env` will load the installed core-js version based on the setting I have set (3) and will add the polyfills needed based on usage. And the transform runtime and runtime packages will enable the re-use of Babel's injected helper code to save on codesize.

Not sure where `babel-runtime-corejs3` package comes into this scenario.

I think, that if I pass corejs version to the `plugin-transform-runtime` as I did for preset-env then I will need to install `babel-runtime-corejs3` because that one besides `regenerator-runtime` adds `core-js-pure`.

Is this correct?

I think my problem is understanding what preset-env does and the transform runtime, and the dependencies they need to bring to work correctly.

Also `preset-env` needs `core-js` installed and the version passed into its config, always.

Where if I do not use `preset-env` at all and I just use `plugin-transform-runtime` I have a few options. I can either install `@babel/runtime` and `core-js` or I can install `babel-runtime-corejs3` and nothing else. Is this assumption correct also?

I tried to read the docs multiple times and I am still confused about how this works.

**Comment by radum** [comment]
@renchap What are you npm modules for babel that you have installed under your configuration above?

**Comment by zloirock** [comment]
@radum you understood everything correctly. Documentation on `babel`'s site still not updated, see https://github.com/babel/website/pull/1987

**Comment by radum** [comment]
Thanks @zloirock that makes much more sense now :)

I think this issue can be closed now.

**Comment by jcolmenarez** [comment]
@renchap I encountered this very same issue by running the `webpack-bundle-analyzer` plugin while I was using Webpack + Babel + dynamic imports and running some optimizations such as code splitting and group caching (_I must point out that I'm actually learning, it is my first time with Webpack, Babel and everything within their ecosystems_).

And I found out a way (_although I'm not sure if it could be a safe way, again, I'm just a newbie learning my way through Webpack and Babel_) that it might require a more intensive testing in order to discard malfunctions or bugs, but a way that seems to be working.

And by _"working"_ I mean that it is adding only one `core-js` reference (the `core-js-pure` one) to the bundles and keeping both the polyfills benefits from using `useBuiltIns: 'usage'` in `preset-env` and the Babel's helpers optimization along with the regenerator transform from `@babel/plugin-transform-runtime`.

### Possible workaround
- Replace the package `core-js` dependency with (_or install according to the case_) the `core-js-pure` ( _It is available via_ `npm i --save core-js-pure@latest`).
- Create an alias in the Webpack's configuration `resolve.alias` property in order to resolve the `core-js` module import/require references to the `core-js-pure` one (_make sure to define the_ `node_modules` _path in the_ `resolve.modules` _property_).

Feel free to review or use this Webpack's setup & config file at [https://github.com/jcolmenarez/webpack-boilerplate](https://github.com/jcolmenarez/webpack-boilerplate) and it would be really useful if any of the Babel's engineers could let me know if this is an acceptable way of solving this issue for now, until a more proper solution is suggested and if there is any problem or bug related to it (_because I was planning to use it for my personal testing projects_).

Many thanks in advanced!

### Environment
- Babel version: 7.4.5
- Node/NPM versions: 12.3.1/6.9.0
- OS: OS X 10.14.5
- How you are using Babel: Webpack's `babel-loader`
