### ISSUE TITLE
Change the way template literals are transpiled for performance

### ISSUE THREAD

**Issue by JakenHerman** [babel/babel#9743]
## Feature Request

**The current compilation**
If I have a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) like so ``const x = `${1 + 2} is 3 and ${1 - 2} is -1`;``, babel returns me 
```
"use strict";

var x = "".concat(1 + 2, " is 3 and ").concat(1 - 2, " is -1");
```

**The problem**
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/concat),

> It is strongly recommended that the assignment operators (+, +=) are used instead of the concat() method. 
> According to [this](https://jsperf.com/concat-vs-plus-vs-join) performance test, the assignment operators are several times faster.

**The solution**
Change the way babel handles template literals to optimize for performance by using the assignment operators instead of `concat()`

**Comment by JakenHerman** [comment]
I am more than happy to help with this, by the way.

**Comment by jridgewell** [comment]
This was changed in https://github.com/babel/babel/pull/5791 to match the spec behavior. I believe the loose transform still performs `+` operations.

**Comment by JakenHerman** [comment]
@jridgewell I made this issue after testing this on the Babel "Try it out" page - https://babeljs.io/repl, so maybe that version just hasn't been updated and this issue is misplaced?

**Comment by loganfsmyth** [comment]
The transform with `loose: true` produces

```
var x = 1 + 2 + " is 3 and " + (1 - 2) + " is -1";
```
which is what you're looking for. This cannot be the default however because it is not spec-compliant. 

Per the spec, each substitution item needs to be processed via the spec's [`ToString`](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-tostring) algoritm. If we use `+`, the items are instead processed using [`ToPrimitive`](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-toprimitive) which can result in different behavior. For example:
```
var obj = {
  toString(){ return "string"; },
  valueOf(){ return "value"; },
};

`_${obj}_` === "_string_";
"_" + obj + "_" === "_value_";
```

**Comment by nicolo-ribaudo** [comment]
@JakenHerman When using the repl, it works: https://babeljs.io/repl#?babili=false&browsers=%3E%201%25%2C%20last%202%20versions&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAHjAvDABgEgN4EYYGoYBMAvjAJYQwDMMAhmACYyY4C0hJ5MLWKA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015-loose&prettier=false&targets=&version=7.4.2

Maybe you enabled the `es2015` preset instead of `es2015-loose`?
