### ISSUE TITLE
Property decorator issues

### ISSUE THREAD

**Issue by elderapo** [babel/babel#9773]
## Bug Report

**Current Behavior**
Babel 7 emits code with broken property injection.

**Input Code**
- [Reproducible repo](https://github.com/elderapo/babel-7-property-decorator-issue)

```ts
const LogUpdate = () => {
  return (target: Object, key: string | symbol) => {
    let val = target[key];

    const getter = () => {
      return val;
    };

    const setter = next => {
      console.log(`Updating: ${val} => ${next}...`);
      val = next;
    };

    Object.defineProperty(target, key, {
      get: getter,
      set: setter,
      enumerable: true,
      configurable: true
    });
  };
};

class Something {
  @LogUpdate()
  public count: number = 0;
}

const something = new Something();
something.count++;
something.count = 123;
something.count = -1;
```

**Expected behavior/code**
Code compiled with babel doesn't trigger logger:
```bash
elderapo@******:~/nodejs/babel-7-property-decorator-issue$ yarn babel-start
yarn run v1.13.0
$ yarn babel-build && node ./compiled-with-babel/index.js
$ babel src --out-dir compiled-with-babel --extensions ".ts,.tsx" --source-maps inline
Successfully compiled 1 file with Babel.
Done in 0.70s.
```
On the other hand code compipled with `tsc` works just fine:
```bash
elderapo@******:~/nodejs/babel-7-property-decorator-issue$ yarn ts-node-start
yarn run v1.13.0
$ ts-node ./src/index.ts
Updating: undefined => 0...
Updating: 0 => 1...
Updating: 1 => 123...
Updating: 123 => -1...
Done in 1.17s.
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ],
  "presets": ["@babel/env", "@babel/preset-typescript"]
}
```

**Environment**
- Babel version(s): 7.4.0
- Node/npm version: doesn't matter
- OS: doesn't matter
- Monorepo: doesn't matter
- How you are using Babel: doesn't matter

**Possible Solution**

**Additional context/Screenshots**
This example is pretty trivial but property decorators are often used in dependency injection. It's possible to use https://github.com/inversify/InversifyJS to get stuff injected into constructor but it's not always possible. One of the examples is react ecosystem where it's really hard to use constructor injection and property injection comes in handy.

**Comment by nicolo-ribaudo** [comment]
I'm not sure what we should do here. I belive that you decorator should be rewritten to return a property descriptor (with an optional `.initializer` property which will be called when you create a new instance of the class to get the property value), but https://github.com/wycats/javascript-decorators doesn't say anything about class properties.

**Comment by leonardfactory** [comment]
The actual problem seems to resides in property initializers; while TSC do not add one (`Object.defineProperty`) on class instance and only adds the decorator to the prototype, babel instead defines the property on the instance. 

So, while the `prototype` correctly has the decorated getter, the instance cannot access it. (These are my findings after playing with a sample [here](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/blob/48bd0bb21ca28bb920d89bf502f7b690726b50a1/examples/inversify/src/index.ts)).

It seems to me that the `inversifyjs` decorator plays with getter and setter without using `initializer`, and this does not play with the spec. I'm not exactly sure about this, but I'm going to investigate it further these days: maybe a simple patch to `lazyInject` (in the way @nicolo-ribaudo specified) could provide a working solution.

PS: This is all based on the *legacy* transform, but in the near future decorators will approach stage 3 & beyond, is there any plan between TS/Babel and the libraries using decorators to provide a migration path / ensure everything is working? I'd like to help there.

**Comment by nicolo-ribaudo** [comment]
Babel also supports decorators as specified up to the end of 2018 (you just need to disable the `legacy` option).
In the last few weeks the proposal has been rewriting, and I'm working on reimplementing it.

**Comment by endel** [comment]
I'm having the same problem using [@colyseus/schema](https://github.com/colyseus/schema) + Babel. The lib doesn't work using Babel, only plain TypeScript, I'm wondering what can I do to make it compatible with Babel.

I believe it's related to the `initializerDefineProperty_default` calls from Babel, not really sure.

**Comment by elderapo** [comment]
@endel You might want to have a look at [babel-plugin-transform-typescript-metadata](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata).

I haven't looked enough into `@colyseus/schema` code to determine if your problem is caused by the lack of metadata at the runtime or incorrect property initializers. If it's the metadata then this plugin should definitely help you. If it's the property initializers check out [this issue](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/issues/2).

**Comment by endel** [comment]
@elderapo thanks for the suggestion, `@colyseus/schema` actually does not use metadata, I'll try to create a repository reproducing the issue to post here in a few days!
