### ISSUE TITLE
sh: babel: command not found

### ISSUE THREAD

**Issue by wmgstar** [babel/babel#9792]
```
command:
git clone https://github.com/mozilla/nunjucks.git
cd nunjucks
yarn install or npm install
```

![Screen Shot 2019-03-29 at 11 34 41 AM](https://user-images.githubusercontent.com/47307975/55255247-5c6ec700-5217-11e9-8d2d-7fd38c1a3f1c.png)

**Comment by nicolo-ribaudo** [comment]
It tried cloning that repo and it seems to work :thinking:
Probably there was a problem during `yarn install`, and it didn't correctly put the Babel executable in `node_modules/.bin/babel` or it isn't picking it up from `npm run` scripts. Anyway, this is not a bug with Babel since it throws _before_ running Babel; it is probably a bug with the package manager you are using.
