### ISSUE TITLE
[TypeScript] Parameter decorators in constructors with public/private modifier removes imports

### ISSUE THREAD

**Issue by jezzgoodwin** [babel/babel#9838]
## Bug Report

**Current Behavior**
When using parameter decorators in class constructors combined with the `public` or `private` keyword, Babel loses the import information.

If public/private is not used, it works correctly.

This is a similar issue to #8634 but specifically regarding the use of public/private.

**Input Code**
```javascript
import { inject } from "./inject";
import { UserService } from "./UserService";

export class Store {
    constructor(@inject(UserService) private userService: UserService) {}
}
```

**Expected behavior/code**
I would expect an output along the lines of:

```javascript
Object(_includes__WEBPACK_IMPORTED_MODULE_1__["inject"])(_PageStore__WEBPACK_IMPORTED_MODULE_2__["UserService"])(Store.prototype, "", 0);
```

But what I get is:

```javascript
inject(UserService)(Store.prototype, "", 0);
```

Which doesn't work because `inject` and `UserService` aren't valid variables.

**Babel Configuration**

.babelrc
```javascript
{
	"presets": [
		"@babel/preset-typescript",
		"@babel/react"
	],
	"plugins": [
		["@babel/proposal-decorators", { "legacy": true }],
		["@babel/proposal-class-properties", { "loose": true }],
		"./parameterDecorator.js" // plugin to add calls to parameter decorators: https://github.com/WarnerHooh/babel-plugin-parameter-decorator
	]
}
```

**Environment**
- Babel version: 7.4.3
- Node/npm version: Node 11.10.0, npm 6.7.0
- OS: Windows 10
- How you are using Babel: WebPack

**Comment by Strnadj** [comment]
I am sorry to open this thread, but this bug irritates me a lot, we have few nasty workarounds to make this work... :(

**Comment by nicolo-ribaudo** [comment]
This is a problem with Babel's "type inference" (*): since the decorators are used in a TypeScript-only position, the imported variables are considered as if they were types.

A few workarounds/fixes:
1. (Real fix) The plugin which transforms the parameter decorator should call `scope.crawl()` in the scope where they moved the decorator to, so that Babel can mark it as used in a non-TypeScript position
2. (Hack) You can manually mark the decorator as used in a non-TypeScript position:
    ```js
    import { inject } from "./inject";
    import { UserService } from "./UserService";

    inject; // Babel: This is not only used in a TypeScript-only position

    export class Store {
        constructor(@inject(UserService) private userService: UserService) {}
    }
    ```
3. (Official solution) Starting from Babel 7.9.0, which we will probably release later today, you will be able to disable Babel's unreliable(*) inference and only use explicit `type` imports (supported by TypeScript 3.8). Then, you will be able to pass the `"onlyRemoveTypeImports": true` option to the TypeScript plugin/preset. - https://github.com/babel/babel/pull/11171

(*) Babel's inference has a problem because we don't do any type analysis, for two reasons:
1. It would make Babel way slower
2. That's `tsc`'s space, not ours

**Comment by am0wa** [comment]
Check the [stackoverflow.com::babel-7-inversify-4-webpack-4-unexpected-character-on-inject](https://stackoverflow.com/questions/52557878/babel-7-inversify-4-webpack-4-unexpected-character-on-inject) answer.

`babel-plugin-transform-typescript-metadata` plugin helps. Wish it would be part of `@babel/preset-typescript` to work out of box

**Comment by jezzgoodwin** [comment]
Thanks for the info @am0wa . The last time I tried the `babel-plugin-transform-typescript-metadata` plugin I found it would add lots of warnings to the console about unrecognized objects - it would fail to locate typescript only objects such as interfaces. This is quite possibly fixed now though.  (My previous testing was over a year and a half ago!)
