### ISSUE TITLE
@babel/register doesn't work with monorepo config

### ISSUE THREAD

**Issue by chrisands** [babel/babel#9881]
## Bug Report

**Current Behavior**
`webpack.config.babel.js` in monorepo doesn't compile on the fly by `@babel/register` if I use `babel.config.js`.
It does If I place `.babelrc` file in package.

**Input Code**
Repo with an example (use _webpack-es6_ branch). 
https://github.com/chrisands/vdcalc/tree/webpack-es6

**Expected behavior/code**
Compile file without placing `.babelrc` with all settings or with placing `.babelrc` with `rootMode: 'upward'`

**Babel Configuration (.babelrc, package.json, cli command)**

_babel.config.js_
```js
module.exports = ({
  presets: [
    [
      '@babel/preset-env',
      {
        shippedProposals: true,
      },
    ],
    '@babel/preset-react',
  ],
  plugins: [
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-class-properties',
    'react-hot-loader/babel',
  ],
  babelrcRoots: [
    '.',
    './packages/*',
  ],
})
```

**Environment**
- Babel version(s): v7.4.3
- Node/npm version: node v11.14.0 / npm v6.9.0
- OS: OSX 10.14.4 (18E226)
- Monorepo: lerna/yarn workspaces
- How you are using Babel: register

**Possible Solution**
The solution that first comes in mind is adding the ability to use `rootMode: 'upward'`  in `.babelrc`.

**Comment by nicolo-ribaudo** [comment]
Where is babel/register used in that repo?

**Comment by chrisands** [comment]
@nicolo-ribaudo everything in `packages/dashboard`.

**Comment by vikr01** [comment]
Webpack reads configs ending with `.babel.js` with `@babel/register`. `rootMode` is not for `.babelrc` but an option for `@babel/register`. What you can do is write a commonjs script that calls `@babel/register` with `rootMode: 'upward`' first and then import and export the webpack configs to be transpiled.

**Comment by chrisands** [comment]
@vikr01 I used in my previous projects this like a webpack config
```
require('@babel/register')({
  rootMode: 'upward',
})

export.defaults = require('./dev.babel.js') 
```
But it would be nice not to mix CommonJS and ESM.
As I understand it is not a bug, but a feature request, am I right?

**Comment by nicolo-ribaudo** [comment]
It would probably be a feature request for webpack: they would need a cli flag to specify Babel's `rootMode` option.
When Babel is run, it's too late to change that option's value.

**Comment by chrisands** [comment]
@nicolo-ribaudo as I understand, to implement it the whole system how `rootMode` works should be rewritten?

**Comment by nicolo-ribaudo** [comment]
`rootMode` tells Babel where to look for the config file: even if we rewrote everyhing, we can't read `rootMode` from a config file _before_ deciding where to look for the config file.
It's up to who calls Babel (either using `@babel/register`, `babel.transform`, `babel-loader` or `@babel/cli`) to specify it.

**Comment by chrisands** [comment]
@nicolo-ribaudo is it not possible to link from `.babelrc` to `babel.config.js` like `babelrcRoots` in root config?

**Comment by vikr01** [comment]
@chrisands Since there are other options for `@babel/register` besides `rootMode`, `webpack` should add a cli flag for the options to pass to it like @nicolo-ribaudo said.

**Comment by chrisands** [comment]
@vikr01 @nicolo-ribaudo thank you for your time.

**Comment by nicolo-ribaudo** [comment]
> @nicolo-ribaudo is it not possible to link from .babelrc to babel.config.js like babelrcRoots in root config?

The problem is that `.babelrc` is loaded even later.
Babel's config resolution process looks like this:

1) Call Babel with a `root` path (which defaults to the `cwd`), an optional `rootMode` and the path of the file which needs to be transpiled.
2) Following on the `rootMode` option (which can either be "in the root folder" or "in the root folder and its ancestor"), search for `babel.config.js`.
3) Once `babel.config.js` il loaded, decide if the file should be transpiled or not.
4) If the file to be transpiled is a descendant of a `babelrdRoots` folder (which defaults to "the same as `babel.config.js`'s folder") and there are no `package.json` files between the `babelrcRoot` and the file, walk the directories tree starting to the babelrc root down to the source file and load any `.babelrc` that is found.
5) For each `.babelrc` file, check again if the file should be ignored
6) Merge those `.babelrc` on top of `babel.config.js`

That is the reason for which, for example, you can't specify `rootMode` in any config file or `extensions`/`babelrcRoots` in a `.babelrc` file.

**Comment by chrisands** [comment]
Thank you for explanation of process.
