### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by sebmck** [babel/babel#992]
- CLA
 - Expand in `CONTRIBUTING.md`

**Comment by alawatthe** [comment]
I'm interested, why do you want to add a CLA?

**Comment by sebmck** [comment]
Better to be safe than sorry. There are also some interested parties
interested in using and contributing to Babel so the extra safety is nice.

On Wednesday, 11 March 2015, Alexander Zeilmann <notifications@github.com>
wrote:

> I'm interested, why do you want to add a CLA?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/992#issuecomment-78230540>.
>


-- 
Sebastian McKenzie

**Comment by alawatthe** [comment]
You probably saw from my comment, that I am not a big fan of CLAs. Or at least not of most of the CLAs out there. Why?

Because most CLAs require you to provide
1. your real name
2. your mailing address
3. your phone number
4. and (my favorite one) your employer's policy for contributing to open source

Why is this a problem? Because for every of these points, there are situations, where one is not able to provide some of the information (e.g. some time ago, I was without a phone, so what do I put as a phone number? Or, do you really think, I should bother my boss with creating such a policy, because I want to fix a typo in a project?). I am not even talking about, not wanting to provide the information, but about not being able to provide them. 

I was told in the past, "if someone isn't able to provide all the information for the CLA we can't merge his pull requests". So suddenly your Open Source project isn't open any longer. This definitely shouldn't be a goal for any open source project.

What are my suggestions? 
Well, I am against adding a CLA, because other projects have it or some random person suggested to do it, but urge you to seek professional legal advice. Don't rush into it.

You should also be aware, that having a of any form CLA will reduce the contributions to your project. Joyent for example removed the CLA with the goal of [broadening Node.js contributions](https://www.joyent.com/blog/broadening-node-js-contributions).

If you really want to add a CLA, I would suggest you model it after [yahoo's CLA](https://yahoocla.herokuapp.com), which is (in my opion) a more or less perfect CLA, since it addresses my above concerns and also provides a human-readable summary.

**Comment by sebmck** [comment]
I think you're overestimating what my questions would be for a CLA. Something like the [ESLint](http://eslint.org/cla/) or [jQuery](http://contribute.jquery.org/CLA/) CLA where you only need to provide your:

 - Full name
 - Email

Easy peasy. If you're willing to go through the trouble of submitting a PR then filling in two boxes is no problem.

**Comment by alawatthe** [comment]
Full name and email is ok for me :-)
Sorry for having you annoyed with this pet peeve of mine :-/

**Comment by sebmck** [comment]
@alawatthe All good :stuck_out_tongue: In future jobs I may use Babel or Babel-related tech and this is just covering myself.

**Comment by timoxley** [comment]
What exactly is this covering that the License does not? Node had a contributor license agreement and it sure pissed a lot of people off and they ultimately got rid of it:

> In an effort to make it easier for users to contribute to Node.js the project has decided to lift the requirement of signing the CLA before contributions are eligible for integration. Having to sign the CLA could at times be a stumbling block for a contribution. It could involve a long conversation with your legal department to ultimately contribute typo corrections.

**Comment by sebmck** [comment]
@timoxley I think we both know that Node's CLA wasn't the biggest reason for lack of contributors. There are also a lot of projects that have plenty of contributors that have a CLA (jQuery, ESLint, lodash, Grunt)

**Comment by timoxley** [comment]
Wasn't suggesting that was *the* problem with Node, just suggesting it left a bad taste in people's mouths.

**Comment by sebmck** [comment]
I think the difference between a large company wanting you to sign over your copyright and work to them so they have complete control is a bit different from a sole developer who would rather not risk getting into any legal trouble.

**Comment by sebmck** [comment]
Since opening this issue I've fleshed out the contribution guide a bit more. Regarding a CLA, it's potentially something I'm going to revisit in the future. For those of you concerned about contributor hostility, I'll just remind you of the current [`git fame`](https://github.com/oleander/git-fame-rb):

```
+---------------------------------+--------+---------+-------+--------------------+
| name                            | loc    | commits | files | distribution       |
+---------------------------------+--------+---------+-------+--------------------+
| Sebastian McKenzie              | 95,517 | 3,251   | 1,596 | 98.2 / 92.2 / 96.9 |
| James Kyle                      | 430    | 17      | 13    | 0.4 / 0.5 / 0.8    |
| Dan Abramov                     | 261    | 17      | 17    | 0.3 / 0.5 / 1.0    |
| Ondrej Kraus                    | 246    | 29      | 25    | 0.3 / 0.8 / 1.5    |
| Brian Donovan                   | 104    | 24      | 15    | 0.1 / 0.7 / 0.9    |
| Ingvar Stepanyan                | 101    | 16      | 20    | 0.1 / 0.5 / 1.2    |
| Douglas Duteil                  | 62     | 3       | 12    | 0.1 / 0.1 / 0.7    |
...
...

i think if there was any substantial barrier to contribution then it would already be existing.
