### ISSUE TITLE
The scope of the arguments default value is different from what was expected in ES2015 (参数默认值的作用域与 ES2015 的预期结果不同)

### ISSUE THREAD

**Issue by Yangfan2016** [babel/babel#9947]
## Bug Report

**Current Behavior**
The scope of the arguments default value is different from what was expected in ES2015

**Input Code**

[online view](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAZg9jEF4IHIYFcwgE7INwCh8o0A7AYzAEsYSIAjAQywApjzEJmBKRAPmjg8A3vggRQkWPCTJKJEtjyiIZGgGcYoAHTAYAc1aky3LgQC-hRi1MQA9LYjpMWfEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.4.4&externalPlugins=)

This is source code of ES2015: 
```js
let foo = 'outer';

function bar(func = () => foo) {
  let foo = 'inner';
  console.log(func());
}

bar(); // outer

```
The result of run it: 

```js
outer
```

This is transform code by babel: 

```js
"use strict";

var foo = 'outer';

function bar() {
  var func = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : function () {
    return foo;
  };
  var foo = 'inner';
  console.log(func());
}

bar(); // outer

```

The result of run it: 

```js
inner
```

**Expected behavior/code**

Expect the results of the Babel conversion to be consistent with ES2015 performance

**Babel Configuration (.babelrc, package.json, cli command)**

**Environment**
- Babel version(s): [v7.4.4]
- Node/npm version: [Node 8.9/npm 5]
- OS: [Windows 10]
- Monorepo: [no]
- How you are using Babel: [babeljs.io]

**Possible Solution**

```js
"use strict";

var foo = 'outer';

function bar() {
    var func = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : function() {
        return foo;
    }
    ;
    (function() {

        var foo = 'inner';
        console.log(func());

    }())
}

bar();

```

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by JLHwung** [comment]
Hi 杨帆,

Thanks for the reproducing examples. It helps a lot narrow down the problem.

The possible solution you mentioned above is promising. In fact there is a `iife` state in the `transform-parameters` to determine whether the whole function body should be wrapped into an extra closure. 

It is interesting to find that there was a similar bug people had already solved [here](https://github.com/babel/babel/blob/v7.4.5/packages/babel-plugin-transform-parameters/test/fixtures/parameters/default-eval/input.js), so as a workaround, you can replace
```js
function bar(func = () => foo) {
}
```

to

```js
function bar(func = () => eval("foo")) {
}
```

And babel will work this time. I admit that it is ugly hack and the bug should be fixed in `transform-parameters`. I would look into this in a couple of days.
