### ISSUE TITLE
Anonymous function binding into "for" loop

### ISSUE THREAD

**Issue by bidos** [babel/babel#995]
In this snippet of code :
```javascript
class A {

    show(){
        console.log("class A")
    }
}

class B {
    show(){
        console.log("class B")
    }
}

var array1 = {
    "a1" : new A(),
    "a2" : new A(),
    "b1" : new B()
};

var field, executions =[];

for(field in array1){
    var f1 = function(){
        return array1[field]["show"].bind(array1[field])();
    };
    executions.push(f1);
}

executions[0]();
executions[1]();
executions[2]();

var field2, executions2 =[];

for(field2 in array1){
    executions2.push(array1[field2]["show"].bind(array1[field2]));
}

executions2[0]();
executions2[1]();
executions2[2]();
```
I can't understand why there are a problem in the first "executions" ! I have the follwing result when i run this code with node.js
class B
class B
class B
class A
class A
class B

**Comment by sebmck** [comment]
Not a bug in Babel. You're referencing the `for...`in` iteration variable in a closure and since it's not scoped to the current iteration it's effectively going to be the last one. Use a `let` variable if you want iteration specific bindings.

See the [REPL](http://babeljs.io/repl/#?experimental=false&playground=false&evaluate=true&loose=false&spec=true&code=class%20A%20%7B%0A%0A%20%20%20%20show()%7B%0A%20%20%20%20%20%20%20%20console.log(%22class%20A%22)%0A%20%20%20%20%7D%0A%7D%0A%0Aclass%20B%20%7B%0A%20%20%20%20show()%7B%0A%20%20%20%20%20%20%20%20console.log(%22class%20B%22)%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20array1%20%3D%20%7B%0A%20%20%20%20%22a1%22%20%3A%20new%20A()%2C%0A%20%20%20%20%22a2%22%20%3A%20new%20A()%2C%0A%20%20%20%20%22b1%22%20%3A%20new%20B()%0A%7D%3B%0A%0Avar%20executions%20%3D%5B%5D%3B%0A%0Afor(let%20field%20in%20array1)%7B%0A%20%20%20%20var%20f1%20%3D%20function()%7B%0A%20%20%20%20%20%20%20%20return%20array1%5Bfield%5D%5B%22show%22%5D.bind(array1%5Bfield%5D)()%3B%0A%20%20%20%20%7D%3B%0A%20%20%20%20executions.push(f1)%3B%0A%7D%0A%0Aexecutions%5B0%5D()%3B%0Aexecutions%5B1%5D()%3B%0Aexecutions%5B2%5D()%3B%0A%0Avar%20executions2%20%3D%5B%5D%3B%0A%0Afor(let%20field2%20in%20array1)%7B%0A%20%20%20%20executions2.push(array1%5Bfield2%5D%5B%22show%22%5D.bind(array1%5Bfield2%5D))%3B%0A%7D%0A%0Aexecutions2%5B0%5D()%3B%0Aexecutions2%5B1%5D()%3B%0Aexecutions2%5B2%5D()%3B).

**Comment by bidos** [comment]
Think you very much :)
