### ISSUE TITLE
@babel/register: Why node_modules ignored by default?!

### ISSUE THREAD

**Issue by martinoppitz** [babel/babel#9961]
I have problems by precompiling code from own node_modules.

Is there any way to set the ignore option?

**Comment by martinoppitz** [comment]
https://github.com/babel/babel/blob/1969e6b6aa7d90be3fbb3aca98ea96849656a55a/packages/babel-register/src/node.js#L145

**Comment by martinoppitz** [comment]
See too: https://github.com/mochajs/mocha/issues/3908

**Comment by loganfsmyth** [comment]
> Is there any way to set the ignore option?

You can call the module and set the options, e.g.
```
require("@babel/register")({
  only: [
    "./node_modules/something-to-compile",
    "./src",
  ],
});
```
for example. I'd very much recommend not compiling _all_ `node_modules` though since that can be quite slow and generally requires additional configuration.

For Mochi you can stick that in a file and do `--require ./babel-register.js` or whatever filename you'd like.

**Comment by martinoppitz** [comment]
https://babeljs.io/docs/en/babel-register
