### ISSUE TITLE
Lodash fixes - Babel needs upgrade

### ISSUE THREAD

**Issue by ekkis** [babel/babel#9966]
## Bug Report

Babel and related packages all depend on lodash, which is broken.  I've produced a fix for it, which has been merged but Babel will need to upgrade.  here's the fix:

https://github.com/lodash/lodash/pull/4290

**Current Behavior**
Packages that depend on Babel break under the conditions described in the PR above

**Expected behavior/code**
Expected not to break

**Babel Configuration (.babelrc, package.json, cli command)**
Any configuration
**Environment**
Any version of Babel/Node/npm/OS

**Possible Solution**
upgrade to version of lodash containing patch

**Comment by nicolo-ribaudo** [comment]
Do you want to open a PR updating lodash?

**Comment by ekkis** [comment]
oh.  sure!

**Comment by sharang-d** [comment]
Can this be closed? Looks like it was fixed recently.
Refer https://github.com/babel/babel/issues/10226#issuecomment-512592466.

**Comment by cdeutsch** [comment]
When I run `npm audit`, `@babel/types` still reports issues, because it's referencing an old version of `lodash`

![image](https://user-images.githubusercontent.com/404765/62738675-7eaff700-b9f8-11e9-8967-6699faa42e84.png)

It seems like it should install a newer version, but something seems to be locking it
