### ISSUE TITLE
Drop support for node <8.9.0

### ISSUE THREAD

**Issue by danez** [babel/babel#9981]

**Comment by nicolo-ribaudo** [comment]
Note that at the eol of node 8 is December 2019. We might drop support for <10 at that point.

**Comment by Andarist** [comment]
Just to add a note here - besides bumping transpilation target it would be good to update dependencies as well. I.e. `chokidar` should be bumped to `>3.x` (currently lower versions are sometimes giving me lots of warnings in the console because of the used `fsevents` version) - this can't be done right now, as chokidar@3 has already dropped support for node@6 which babel still supports at this moment.

**Comment by danez** [comment]
Seems this was merged into the v8 branch.
